### ISSUE TITLE
Error occurs when running flame_audio example

### ISSUE THREAD

**Issue by tatsuya-sagara** [flame-engine/flame#1025]
When I run the flame_audio example, I get the following error.

Error: NotAllowedError: play() failed because the user didn't interact with the document first.

**Comment by spydon** [comment]
This is not a Flame issue, this is a general thing with browsers and audio. Some background can be seen here: https://gamedev.stackexchange.com/a/165431

Basically you'll have to start playing the audio once something is clicked, like a "start game"-button for example.
