### ISSUE TITLE
Glow effect

### ISSUE THREAD

**Issue by erickzanardo** [flame-engine/flame#1027]
# Problem to solve
A new paint effect for glowing effects

# Proposal
As saw in the last FlameCon on the Orbit game talk, We could use Paint maskFilter to create a glow effect

https://api.flutter.dev/flutter/dart-ui/Paint/maskFilter.html

**Comment by cnsumner** [comment]
I can take a look at this.

**Comment by spydon** [comment]
> I can take a look at this.

Great! I'll assign you to this and join our Discord if you have any questions.

**Comment by spydon** [comment]
Hi @cnsumner, there is less than a week left of Hacktoberfest now, do you think that you'll be able to complete this issue in time? If not we'll open it up to other contributors.

**Comment by spydon** [comment]
> @spydon probably not unfortunately. I haven't had much time and what time I did spend on it was unsuccessful.

Thanks for letting us know, then I'll unassign you so that someone else can take it on. :)
