### ISSUE TITLE
CustomPainterComponent

### ISSUE THREAD

**Issue by erickzanardo** [flame-engine/flame#1028]
# Problem to solve

Flutter offer a class called custom painter to make custom rendering on its widget tree.

Flame could provide a component that wraps that so we could:

- Share code between the game and widgets
- Have a simple way of adding support for flutter shape maker https://fluttershapemaker.com/

# Proposal
This should be pretty simple, just a component that receives a custom paint instance and call it's paint method on the component render method.

# More information

**Comment by erickzanardo** [comment]
That would work too, I wouldn't mind having it in the core because in a manner, I see it as core feature as it is direct related to Flutter and there is no external dependency and the implementation would be relatively small.

But an external package seems a good option too

**Comment by wolfenrain** [comment]
> That would work too, I wouldn't mind having it in the core because in a manner, I see it as core feature as it is direct related to Flutter and there is no external dependency and the implementation would be relatively small.
> 
> But an external package seems a good option too

Yea was more a point for discussion, I am also fine with both but I was on the opposite side of the fence haha.

**Comment by erickzanardo** [comment]
We could probably draft a pr for this, and when looking into the implementation we will have a clearer idea on which solution will be best

**Comment by spydon** [comment]
Closing this since the PR was merged
