### ISSUE TITLE
Parallelize `test` step in cicd

### ISSUE THREAD

**Issue by mugbug** [flame-engine/flame#1032]
# What could be improved

Based on this issue: https://github.com/flame-engine/flame/issues/954, I noticed that we could also go for the same approach for the packages' unit/widget tests execution, and run each package tests in parallel.

# Why should this be improved

- When tests fail, it isn't that easy to know which package was the cause. It requires a deeper look inside the workflow logs. Making the tests run in parallel, that will be easily visible from the PR checks
- It'll probably decrease some seconds or even minutes from the `cicd` workflow execution, and we can add many more tests on smaller packages and don't increase this execution time.

# Any risks?

None AFAIK

# More information

This implementation should be pretty similar to this one: https://github.com/flame-engine/flame/pull/1029

Also, I'd be happy to help with this one as well, but it seems to be a pretty nice `good first issue` for new contributors =]

**Comment by erickzanardo** [comment]
That would be awesome!

**Comment by spydon** [comment]
@mugbug now when hacktoberfest is over I don't think any newcomers will pick this up, do you want to do it? :)

**Comment by mugbug** [comment]
For sure! I'm just a little busy these days, but as soon as I have some free time I'll take a look on this 🙂

**Comment by spydon** [comment]
Kind of solved with Spec.
