### ISSUE TITLE
How to correctly handle taps and gestures when using basic flutter widgets for home/settings screens and flame's game.widget on other screens 

### ISSUE THREAD

**Issue by Harmonic999** [flame-engine/flame#107]
So this is our basic screen with flutter widgets. When we press the button it redirects us to the game screen where i register new TapGestureRecognizer. The thing is that it doesn't trigger onTapUp action at all on the game screen and works only when we return back to the base screen. Could you tell me please what is wrong in my actions and how to do it correctly?
```
void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flame Game',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: HomeScreen(),
    );
  }
}

class HomeScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: RaisedButton(
            child: Text("Play"),
            onPressed: () {
              Navigator.push(
                context,
                MaterialPageRoute(builder: (context) {
                  return MyGame().widget;
                }),
              );
            }),
      ),
    );
  }
}
```
```
class MyGame extends BaseGame {
  MyGame() {
    Util util = Flame.util;
    var tapsListener = TapGestureRecognizer();
    tapsListener.onTapUp = handleTapUp;
    util.addGestureRecognizer(tapsListener);
  }

  handleTapUp(TapUpDetails details) {
    print('TAP UP');
  }
}
```

**Comment by luanpotter** [comment]
Hi, @Harmonic999 , normally I bind every custom event via addGestureRecognizer on the Flame.util on the `main` function, and then I save a static instance of the game class (in order for not to recreate it needless during re-render and lose game state), and then I check if the game instance is not null, my handler calls the methods on the instance, otherwise, it does nothing.

Please take a look at one of our sample games, bgug:
https://github.com/fireslime/bgug/blob/master/lib/main.dart

this file has the exact code that you need.

please let us know if you were successful or if it's unclear :)

**Comment by Harmonic999** [comment]
@luanpotter thanks for your answer. I found a solution to all my problems.
1. On the new screen make game's widget as a child of Scaffold like this, or user's input won't work correctly.

```
Widget build(BuildContext context) {
    GameEngine engine = GameEngine();
    CardsGame game = CardsGame(size.width, size.height);
    engine.setGameStateListener(game);

    return Scaffold(
      body: engine.widget,
    );
  }
```
2. Never create second instance of the game, because it starts to behave very strange, as said @luanpotter create and use only one instance of the game. My solution below, create singleton and just bind a listener to it every time. Also you can see how it is done in the first example.

```
class GameEngine extends BaseGame {
  static final GameEngine _instance = GameEngine._internal();

  factory GameEngine() {
    _initTapHandlers();
    return _instance;
  }

  GameEngine._internal();

  static GameStateListener gameStateListener;

  void setGameStateListener(GameStateListener gst) {
    gameStateListener = gst;
  }

  static void _initTapHandlers() {
    var util = Util();
    var tapsRecognizer = TapGestureRecognizer();
    tapsRecognizer.onTapUp = _onTapUp;
    util.addGestureRecognizer(tapsRecognizer);
  }

  static void _onTapUp(TapUpDetails details) {
    if (gameStateListener != null) gameStateListener.onTapUp(details);
  }

  @override
  void update(double t) {
    if (gameStateListener != null) gameStateListener.update(t);
  }

  @override
  void render(Canvas canvas) {
    if (gameStateListener != null) gameStateListener.render(canvas);
  }
}

abstract class GameStateListener {
  void update(double t);

  void render(Canvas canvas);

  void onTapUp(TapUpDetails details);
}
```
3. `Flame.util.fullScreen() `Method forces game's widget to rebuild every time the player presses Home button on android, be careful.

**Comment by erickzanardo** [comment]
Glad you got your problems solved @Harmonic999 , let us know if have any more issues.
