### ISSUE TITLE
Sprite.load cannot load pictures with different resolutions

### ISSUE THREAD

**Issue by zhouge870103** [flame-engine/flame#1074]
Sprite.load cannot load pictures with different resolutions
AssetImage is correct

**Comment by erickzanardo** [comment]
Not sure I understand the issue, Sprite.load can load images of any resolution.

Please edit your issue, add more info and follow the issue template

**Comment by spydon** [comment]
I think they refer to how it is done in `AssetImage` where you can have several resolutions of the same image and the image with good enough resolution for the pixel density and size will be used.
https://api.flutter.dev/flutter/painting/AssetImage-class.html

**Comment by erickzanardo** [comment]
Alright, changing this to improvement then as this is not a bug but rather an enhancement

**Comment by spydon** [comment]
I'll add `post-v1` too.

**Comment by spydon** [comment]
Related to #116

**Comment by erickzanardo** [comment]
After some internal discussion, we decided to not do this. Game engines usually refrain from this since loading textures from an image depends on their size, so automatically changing which image is loaded according to the device resolution can cause some confusion.
