### ISSUE TITLE
`TextBoxComponent` should have the possiblity to align text within itself

### ISSUE THREAD

**Issue by spydon** [flame-engine/flame#1088]
# Problem to solve
Right now the text within a `TextBoxComponent` can only be left aligned.

# Proposal
I propose that we add a `textAlign` field in `TextBoxConfig`. The type of the field could either be `TextAlign` or an `Anchor`.

# More information

**Comment by st-pasha** [comment]
I just looked into `TextBoxComponent`, and can't figure out why `TextBoxConfig` is a separate class -- is it just a rudiment of an unfinished refactor? It doesn't seem to be used anywhere else, nor is it ever subclassed.

**Comment by spydon** [comment]
It is used in `TextBoxComponent`. It was a long time since it was created, but I think the idea was that you could create multiple `TextBoxComponent`s with the same config.

**Comment by LahaLuhem** [comment]
![screencap](https://user-images.githubusercontent.com/47954571/154305134-256e7bfc-9119-4a94-8481-614100d713ad.png)
Need this enhancements asap. No way to align the text

**Comment by LahaLuhem** [comment]
![screencap](https://user-images.githubusercontent.com/47954571/154305423-6a607279-b432-45d0-ade5-1466920c8470.png)
Need this enhancement asap. No way to align the text to the center directly

**Comment by large** [comment]
Totally agree! My first try on flame, but that was a flaw straight away.

I combined SpriteButtonComponent with TextBoxComponent and wanted to have centered text.
Everything is fine until you need multiline, see the difference
![image](https://user-images.githubusercontent.com/535446/167943555-455c4ff2-143e-4eab-a89b-a3e71336edf0.png)

In multiline it does not look good
![image](https://user-images.githubusercontent.com/535446/167943756-ee536648-5b51-4dec-82f6-fe680d00d3c0.png)

When I get warm in Flame I'll create a PR for fixing this ;)

**Comment by large** [comment]
I had a go to solve this little puzzle, and here is a way to get it as expected
Copy the TextBoxComponent to a new file: https://github.com/flame-engine/flame/blob/main/packages/flame/lib/src/components/text_box_component.dart

Rename the class to for instance MyTextBoxComponent:
```dart
class MyTextBoxComponent<T extends TextRenderer> extends TextComponent {
//(...)
  //Add this paramter
  final TextAlign textAlign; 
//(....)
  MyTextBoxComponent({
//(...)
    int? priority,
    this.textAlign = TextAlign.left, //Defaults to left alignment
  })  : _boxConfig = boxConfig ?? TextBoxConfig(),
        pixelRatio = pixelRatio ?? window.devicePixelRatio,
        super( .............
```

Find the _drawLine routine and change it to this:
```dart
  void _drawLine(Canvas c, String line, double dy) {
    if(textAlign == TextAlign.left)
      {
        textRenderer.render(c, line, Vector2(_boxConfig.margins.left, dy));
      }
    if(textAlign == TextAlign.center)
      {
        double _lineActualLength = getLineWidth(line, line.length);
        double _lineWidth = ( size.x - _boxConfig.margins.right - _lineActualLength  ) / 2;
        textRenderer.render(c, line, Vector2(_boxConfig.margins.left + _lineWidth, dy));
      }
    if(textAlign == TextAlign.right)
      {
        double _lineActualLength = getLineWidth(line, line.length);
        double _lineWidth = ( size.x - _boxConfig.margins.right - _lineActualLength );
        textRenderer.render(c, line, Vector2(_boxConfig.margins.left + _lineWidth, dy));
      }
  }
```

Text will now show correctly:
![image](https://user-images.githubusercontent.com/535446/167949956-e506d627-4fa0-4c7e-8407-3509798adabf.png)
![image](https://user-images.githubusercontent.com/535446/167950135-06d284ba-d479-43be-b3e0-3f5104128921.png)

This solution is "good enough" for me.
My suggestion is to implement all TextAlign features before PR-ing this to flame; https://api.flutter.dev/flutter/dart-ui/TextAlign.html

I do not need TextAlign.start, TextAlign.justify and TextAlign.end for my project.
Also did not see a quick solution to get that working.
If someone does, please share your code to get the quality we all want in flame ;)

**Comment by spydon** [comment]
@large nice that you provided a work around, we had kind of forgotten about this issue. I assigned @st-pasha to it now, so it'll probably be fixed in no time!

**Comment by st-pasha** [comment]
> I propose that we add a textAlign field in TextBoxConfig. The type of the field could either be TextAlign or an Anchor.

The `Anchor` option is really interesting -- it would allow to control both vertical and horizontal alignment with a single parameter. At the same time, it doesn't allow the "justified" option (not sure whether it is needed though).
