### ISSUE TITLE
"resource android:attr/lStar not found." when building for Android

### ISSUE THREAD

**Issue by leandertolksdorf** [flame-engine/flame#1089]
# Current bug behaviour
When trying to build an app (specifically this one: https://github.com/ecklf/flutters ) for Android, I get this error:

```
* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\Leander\.gradle\caches\transforms-2\files-2.1\574d96996a78f48619a014c868c26e7e\core-1.7.0\res\values\values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 27s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

```

# Expected behaviour
Successful build like on web and iOS.

# More environment information

* Flame version 0.29.4
* Platforms affected: android
* Platform version affected: tested with 31 and 28

# More information
From my research, this issue seems to come from the package `audioplayers` and has been fixed in `audioplayers v20`, but Flame uses 0.18.3

**Comment by spydon** [comment]
If you are just starting to use Flame I highly suggest that you start using `1.0.0-releasecandidate.16`, it has support for the newest audioplayers, is more stable than `0.29.4` and all the docs and examples are written for that version.

**Comment by spydon** [comment]
Ah sorry, wrote the wrong version of `flame_audio` is should be `1.0.0-rc.15`, updated now.

**Comment by leandertolksdorf** [comment]
Thank you! That worked.
