### ISSUE TITLE
How I can create a Sprite.fromImage from a new image with ImageRepeat characters?

### ISSUE THREAD

**Issue by amfangYahoo** [flame-engine/flame#109]
HI guys, I hope to create a moving background Sprite by 1 image loaded and created with repeat: ImageRepeat.repeatY, but when I create the Sprite with this image by Sprite.fromImage, there has the issue with below:

Error: The argument type 'Image/*1*/' can't be assigned to the parameter type 'Image/*2*/'.

How can I work this? Thanks.

Image nebulaImg = Image.asset(
    "assets/images/nebula.png",
    repeat: ImageRepeat.repeatY,
  );

sprite = Sprite.fromImage(
      nebulaImg,
      x: 0.0,
      y: 0.0,
      width: nebulaImg.width,
      height: nebulaImg.height,
    );

**Comment by erickzanardo** [comment]
I am not sure why you are having this problem, but I think what you want to do, is better achieved with Flame's Animation class, check its documentation here: https://github.com/flame-engine/flame/blob/master/doc/images.md#animation

**Comment by amfangYahoo** [comment]
I tried there can created a Component to put 2 copies of 1 image Sprite into together to make the image Sprite repeat load. Thanks.

**Comment by erickzanardo** [comment]
I don't understand, did you solved your issue?

**Comment by amfangYahoo** [comment]
There has one example of https://github.com/flame-engine/trex-flame/blob/master/lib/game/horizon/horizon_line.dart, horizon_line(image sprite) cycles unlimited, I just want to act this, now I can do it.

**Comment by erickzanardo** [comment]
Alright, glad you figured it out.
