### ISSUE TITLE
Add method Component.updateTree

### ISSUE THREAD

**Issue by st-pasha** [flame-engine/flame#1115]
Method `updateTree` will relate to `update` as `renderTree` relates to `render` right now.

Reasons:
1. Symmetry. It's easier to understand the component's lifecycle if `render` and `update` are used in exactly the same manner.
2. No need to mark the update method as `@mustCallSuper` anymore. Thus, no need to write `super.update(dt)` every time.
3. More straightforward to implement methods that need to manipulate the update pipeline of their children.

**Comment by spydon** [comment]
Good idea, since this is quite small but also a breaking change I vote that we get this in before v1.

**Comment by spydon** [comment]
@flame-engine/flame-colab two thumbs up so far, are everybody onboard with doing this change before v1?

**Comment by erickzanardo** [comment]
Sounds good to me.

Btw, I was looking at the code to remember the renderTree idea, and shouldn't it be `mustCallSuper`?  the same for this updateTree?

**Comment by st-pasha** [comment]
@erickzanardo The main reason why one would want to override `renderTree()` is to somehow modify the rendering of the children. There are cases (such as `PositionComponent`) where the original `renderTree` can be reused, but then there are those where your implementation of `renderTree` will be completely different. 

For example:
 - completely suppress rendering of children;
 - render only some of the children (e.g. only those that are visible through the viewport);
 - create a set of custom components that have context-aware rendering mechanism (e.g. `myrender(canvas, context)`), in which case the parent's `renderTree` will need to call these custom renderers, and will need to know how to build the context.
