### ISSUE TITLE
Can't search for `FPS` in the docs

### ISSUE THREAD

**Issue by spydon** [flame-engine/flame#1119]
# Current bug behaviour
If you search for `FPS` in the docs you get no results, but if you search for `fps` it returns results (even a result with upper case `FPS` in it).

# Expected behaviour
It should work to search for uppercase words, ultimately I don't think it should matter if it's in caps or not.

# Steps to reproduce
https://docs.flame-engine.org/1.0.0-releasecandidate.16/search.html?q=fps# - works
https://docs.flame-engine.org/1.0.0-releasecandidate.16/search.html?q=FPS# - doesn't work

**Comment by st-pasha** [comment]
This is a strange one...

Both words work:
- https://docs.flame-engine.org/main/search.html?q=dom#
- https://docs.flame-engine.org/main/search.html?q=DOM#

Neither words work (though the word is present on the main page):
- https://docs.flame-engine.org/main/search.html?q=fcs#
- https://docs.flame-engine.org/main/search.html?q=FCS#

I think the problem somehow in the stemming algorithm -- the script thinks that "FPS" is a plural of "FP", but it doesn't collect two-letter phrases...

**Comment by spydon** [comment]
> I think the problem somehow in the stemming algorithm -- the script thinks that "FPS" is a plural of "FP", but it doesn't collect two-letter phrases...

It sounds plausible, but then it is weird that `fps` work with lower-case letters.
