### ISSUE TITLE
At large values of the camera position, the render starts to slow down noticeably

### ISSUE THREAD

**Issue by Vasilisk8** [flame-engine/flame#1126]
# Current bug behaviour
Animation slows down, when position camera Vector2(345451171 ,0);

# Expected behaviour
The camera position should not affect the animation

# Steps to reproduce
    SpriteAnimationComponent spTest = SpriteAnimationComponent();
    spTest.animation = SpriteAnimation.fromFrameData(
        Flame.images.fromCache('airship.png'),
        SpriteAnimationData.sequenced(
          textureSize: Vector2(32, 32),
          amount: 1,
          stepTime: 0.1,
        ));
    spTest.position = Vector2(345451171 ,0);
    spTest.anchor = Anchor.center;

    camera.followComponent(spTest);

# Flutter doctor output
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.19043.1348], locale ru-RU)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.2)
[√] VS Code, 64-bit edition (version 1.62.3)
[√] Connected device (2 available)

# More environment information

# More information

**Comment by spydon** [comment]
Is the fps dropping, or only the animation slowing down? Does the game lag too?

**Comment by Vasilisk8** [comment]
only render.

**Comment by spydon** [comment]
Which platforms does this happen on, all?

**Comment by Vasilisk8** [comment]
Web

**Comment by st-pasha** [comment]
I suspect there's some numerical instability in how the transform matrix is applied to the canvas.

**Comment by Vasilisk8** [comment]
I guessed, it is possible to somehow limit the border of the camera, so that other consumers would not conduct research in search of a problem place

**Comment by spydon** [comment]
> I guessed, it is possible to somehow limit the border of the camera, so that other consumers would not conduct research in search of a problem place

Yes, you can set `worldBounds` on the `Camera`, see here:
https://examples.flame-engine.org/#/Camera%20%26%20Viewport_Follow%20Component
And the code:
https://github.com/flame-engine/flame/blob/main/examples/lib/stories/camera_and_viewport/follow_component_example.dart#L40
If you are not following a component you can set `camera.worldBounds` directly instead.

**Comment by Vasilisk8** [comment]
I know that. You probably misunderstood. I spent 4 hours localizing the place where the render fell. If I knew in advance that large values can cause problems, I would not use the camera, but implement my own grid. Protect your users from a known problem area. At least put a warning that the camera does not work well with large values.

**Comment by spydon** [comment]
> I know that. You probably misunderstood. I spent 4 hours localizing the place where the render fell. If I knew in advance that large values can cause problems, I would not use the camera, but implement my own grid. Protect your users from a known problem area. At least put a warning that the camera does not work well with large values.

Since this will behave differently on different platforms it is not something we should restrict in code, but a note about it in the docs would indeed be good. PRs are very welcome.

**Comment by Vasilisk8** [comment]
Yes, the warning is enough.
