### ISSUE TITLE
flame_tiled not rendering in smartphones

### ISSUE THREAD

**Issue by Jcupzz** [flame-engine/flame#1129]
# Current bug behaviour

flame_tiled is not rendering in mobile phones. I hosted a flame_tiled website in firebase hosting and it is not rendering in mobile phones. I used `flutter build web --release` to build the web and hosted it. In laptop's it is rendering but in phones it is not!
# Expected behaviour

Actually it should render on phones

# Steps to reproduce

Website:    https://beach-website.web.app/#/
GitHub  :    https://github.com/Jcupzz/beach_hack_website_2022
# Flutter doctor output

```
Output of: flutter doctor -v

[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19042.1348], locale en-IN)
    • Flutter version 2.5.3 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (5 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc3)
    • Android SDK at C:\Users\jcupz\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0-rc3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.62.3)
    • VS Code at C:\Users\jcupz\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.28.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.45
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 95.0.1020.53

• No issues found!
```

# More environment information

  flame: ^1.0.0-releasecandidate.16
  flame_tiled: ^1.0.0-releasecandidate.15
  affected in android

# Log information

```
Enter log information in this code block
```

# More information

**Comment by KyleKun** [comment]
Did you try building with canvaskit? Just append `--web-renderer canvaskit` to your build command.

**Comment by Jcupzz** [comment]
> Did you try building with canvaskit? Just append `--web-renderer canvaskit` to your build command.

Yes, I have tried that too....Actually I have tried both `--web-renderer canvaskit` and `--web-renderer html`. Both of them are not working. html is preffered for phones I guess

**Comment by spydon** [comment]
Does this happen with the example here too?
https://github.com/flame-engine/flame/tree/main/packages/flame_tiled/example

**Comment by Jcupzz** [comment]
> Does this happen with the example here too? https://github.com/flame-engine/flame/tree/main/packages/flame_tiled/example

Yes this happens with the example too. I uploaded the example you specified to firebase hosting and it doesn't gets rendered in mobile. In web( in laptop) it is getting rendered. In mobile if I switch to desktop mode in settings of browser, then it is rendering. 

hosted link of example :  https://testingtiled.web.app/

**Comment by Jcupzz** [comment]
Issue solved! refer https://docs.flame-engine.org/1.0.0-releasecandidate.18/platforms.html#flame-web
