### ISSUE TITLE
Events on `PositionComponent` doesn't work in `flame_forge2d` for non-hud components

### ISSUE THREAD

**Issue by spydon** [flame-engine/flame#1132]
# Current bug behaviour
When adding a `PositionComponent` that has `isHud = false` (default) directly to a `Forge2DGame`, events aren't received since the coordinate system is flipped and `containsPoint` is looking at the flipped coordinates, which is not the coordinates that the component is rendered with.

# Expected behaviour
That `Draggable`, `Tappable` etc should work on `PositionComponent`s added directly to a `Forge2DGame`.

# Steps to reproduce
Create a non-hud `PositionComponent` with for example `Draggable` and add it to a `Forge2DGame` that has `HasDraggables`.

# More environment information

Create a list of more environment information, like:
* Flame version: 1.0.0-releasecandidate.16
* Forge2D version: 0.8.1
* flame_forge2d version: 0.8.2-releasecandidate.15
* Platform affected: android, ios, web
* Platform version affected: android 9, ios 13

# Workaround
Override `absoluteToLocal` in your `PositionComponent`:
```dart
  @override
  Vector2 absoluteToLocal(Vector2 point) {
    return super.absoluteToLocal(point..y *= -1);
  }
  ```

**Comment by OlegNovosad** [comment]
I think a lot of issues like that may appear due to flipped Y axis by `forge2d`. Will it take much effort to update forge2d with the same coordinate system as Flame uses?

**Comment by spydon** [comment]
> I think a lot of issues like that may appear due to flipped Y axis by `forge2d`. Will it take much effort to update forge2d with the same coordinate system as Flame uses?

Yes, it is very hard since all of the math is built around the normal coordinate system.
What is easier is to say that all Flame components that are non-huds should be in the forge2d coordinate system instead.

**Comment by OlegNovosad** [comment]
Should we directly check exactly for the `Forge2DGame`? E.g.:

```dart
/// Test whether the `point` (given in global coordinates) lies within this
  /// component. The top and the left borders of the component are inclusive,
  /// while the bottom and the right borders are exclusive.
  @override
  bool containsPoint(Vector2 point) {
    final Vector2 local;
    if (isHud) {
      local = absoluteToLocal(point);
    } else {
      final game = findParent<FlameGame>();
      if (game.runtimeType == FlameGame) {
        local = absoluteToLocal(point);
      } else {
        // Assume we have Forge2DGame in this case
        local = absoluteToLocal(point..y *= -1);
      }
    }

    return (local.x >= 0) &&
        (local.y >= 0) &&
        (local.x < _size.x) &&
        (local.y < _size.y);
  }
```

**Comment by spydon** [comment]
> Should we directly check exactly for the `Forge2DGame`? E.g.:
> 
> ```dart
> /// Test whether the `point` (given in global coordinates) lies within this
>   /// component. The top and the left borders of the component are inclusive,
>   /// while the bottom and the right borders are exclusive.
>   @override
>   bool containsPoint(Vector2 point) {
>     final Vector2 local;
>     if (isHud) {
>       local = absoluteToLocal(point);
>     } else {
>       final game = findParent<FlameGame>();
>       if (game.runtimeType == FlameGame) {
>         local = absoluteToLocal(point);
>       } else {
>         // Assume we have Forge2DGame in this case
>         local = absoluteToLocal(point..y *= -1);
>       }
>     }
> 
>     return (local.x >= 0) &&
>         (local.y >= 0) &&
>         (local.x < _size.x) &&
>         (local.y < _size.y);
>   }
> ```

No, the solution has to be in flame_forge2d.
This would affect the performance of other flame games, and also it is a bit dirty to do runtime type checking.
