### ISSUE TITLE
Update documentation on flame_rive integration within releasecandidate17

### ISSUE THREAD

**Issue by nmarafo** [flame-engine/flame#1141]
It is impossible for me to add the flame_rive package within the releasecandidate17 and there is no documentation within the web.

**Comment by spydon** [comment]
This is two separate issues. Can you reformulate this to be for the docs? And I'll look into if we need to release a new flame_rive version right away.

**Comment by spydon** [comment]
There we go, the SDK restrictions were too hard on the released version, now you can use `1.0.0-releasecandidate.2` with rc17. I'll keep this ticket open for the documentation part of it.

**Comment by spydon** [comment]
Closing this since #1143 was opened
