### ISSUE TITLE
Artificial intelligence for game development

### ISSUE THREAD

**Issue by nmarafo** [flame-engine/flame#1164]
It would be great if flame engine included an artificial intelligence framework such as [gdx-ai](https://github.com/libgdx/gdx-ai).

**Comment by spydon** [comment]
This sounds like something we could have as a bridge library, do you know any good Dart packages that could be bundled into this? I only know about the a-star lib.

**Comment by nmarafo** [comment]
I've been looking and can't find anything intended to dart. You could do something similar to what was done with flame_forge2d and box2d.

Gdx-ai seems to me to be quite robust.

Therefore, if the conversion from java to dart is considered feasible and guidelines are set, the community could collaborate in that regard.

**Comment by spydon** [comment]
> I've been looking and can't find anything intended to dart. You could do something similar to what was done with flame_forge2d and box2d.
> 
> Gdx-ai seems to me to be quite robust.
> 
> Therefore, if the conversion from java to dart is considered feasible and guidelines are set, the community could collaborate in that regard.

It is a looot of work to port big java libs to dart, but it can be done, so if anyone does it, I'd be happy to help with the bridge package.

**Comment by nmarafo** [comment]
Well, I think it's wonderful that a line of work could be opened in this regard.
I'm going to study the gdx-ai structure a bit and from my humble knowledge see if a simple assimilation for Flame engine is feasible.

**Comment by nmarafo** [comment]
After an arduous research task I have encountered several problems translating the library from java to dart. I don't know what type of Vector to use. I have seen that the flame-forge2d library uses "vector_math" but I have a problem about how to transcribe "class <T extends Vector <T>>", since I cannot find "Vector <T extends Vector>". I would also like to know from which library to import a Math class for Math.sqrt.
On the other hand, I think there will be no problem with the "Steering Behaviors" adapter, which at first seems to me to be one of the most useful functionalities to get started.

**Comment by spydon** [comment]
For Vector, we use the `Vector2` class which is from `vector_math`, I don't think you'd have to generics on it.
`sqrt` exists in `dart:math`, so no need for a dependency there.

**Comment by nmarafo** [comment]
I would need help again. Apologies in advance. 

If I extend Vector2 (flame / extensions.dart) this class uses a constructor with "factory" so when I transcribe the gdx-ai classes that extend Vector2, it forces me to build with factory.

The problem is that I can't call "super" if I build the new class with factory.

So I would need some way to make Vector2 not build with "factory" or skip that rule somehow when I create a class that extends Vector2. 

Any help on this? Thanks in advance.

**Comment by st-pasha** [comment]
1. If you already working on implementing this, it might be helpful to open a draft pull request so that we could review the architecture and provide feedback.
2. Aim at implementing the smallest amount of functionality at first. Even if it's just one class. That way we could figure out how this is going to integrate with the rest of the system.
3. Frankly, I'm not sure why `SteerableAdapter` would need to inherit from Vector2. However, if you do need to inherit from Vector2 then create an explicit constructor that will call one of the Vector2 named constructors:
```dart
class MyVector extends Vector2 {
  MyVector() : super.zero();
}
```

**Comment by nmarafo** [comment]
I have made this repository public [flame-ai](https://github.com/nmarafo/flame_ai), which is rather an experiment because I don't have much experience.

I'm not quite sure how to open a draft pull request, so I apologize, I would need advice on this.

At the moment I am working with the steer folder to try to implement Steering Behavior the way it is done in this [Pacman](https://github.com/yichen0831/Pacman_libGdx) project.

**Comment by st-pasha** [comment]
> I'm not quite sure how to open a draft pull request

This is actually quite simple. Start making a pull request as usual, then after filling out a form -- instead of pressing the green [Create Pull Request] button, click a small arrow on the right side of that button. This will open a drop-down with the option to create a Draft pull request instead.

Also, if you already created a regular PR, it can be converted into a Draft -- just click the "convert to Draft" link in the Reviewers section.

**Comment by spydon** [comment]
I don't think we want such an early draft, it will be open for too long. Better discuss it on the other repository first until it is closer to release and then we can go through it and check if it is a package that we can include under the organization (if you'd want it of course).

**Comment by nmarafo** [comment]
Actually I think that maybe a person with a greater technique than me when developing should take a first step in an external repository as Lukas thinks, so that the rest of us can make contributions, suggestions...

**Comment by st-pasha** [comment]
> Actually I think that maybe a person with a greater technique than me when developing should take a first step in an external repository as Lukas thinks, so that the rest of us can make contributions, suggestions...

Don't worry Norberto, we'll figure it out. Adding AI capabilities in Flame seem like a very important feature.

**Comment by spydon** [comment]
https://github.com/flame-engine/radiance
