### ISSUE TITLE
Can I set one sprite as a child of another one?

### ISSUE THREAD

**Issue by ProgrammingLife** [flame-engine/flame#117]
Can I set one sprite as a child of another one? For example, for applying some transformations like rotation, scaling to the root of bunch of sprites.

**Comment by erickzanardo** [comment]
Take a look on the Composed component, I think it is what you want https://github.com/flame-engine/flame/blob/master/doc/components.md#composed-component

**Comment by erickzanardo** [comment]
Closing this, if you have any more questions, feels free to comment here.
