### ISSUE TITLE
ability to override FilterQuality parameter for Parallax

### ISSUE THREAD

**Issue by newntech** [flame-engine/flame#1204]
Parallax render() method uses the paintImage() method (flutter painting package decoration_image.dart).
This has a default parameter  FilterQuality filterQuality = FilterQuality.low.

`void paintImage({
  required Canvas canvas,
  required Rect rect,
  required ui.Image image,
  String? debugImageLabel,
  double scale = 1.0,
  double opacity = 1.0,
  ColorFilter? colorFilter,
  BoxFit? fit,
  Alignment alignment = Alignment.center,
  Rect? centerSlice,
  ImageRepeat repeat = ImageRepeat.noRepeat,
  bool flipHorizontally = false,
  bool invertColors = false,
  FilterQuality filterQuality = FilterQuality.low,
  bool isAntiAlias = false,
})`

This has the undesired effect of causing blurring on pixel sprite backgrounds.
![example](https://user-images.githubusercontent.com/11397193/145673516-53c23faf-9342-4c1c-84af-599f9fe8424d.png)

Require the ability to override this parameter. FilterQuality.none resolves the above issue.

**Comment by spydon** [comment]
Fixed in #1206
