### ISSUE TITLE
Add example games to docs

### ISSUE THREAD

**Issue by impulse** [flame-engine/flame#121]
Could be one or two sections:

1) Barebone examples like the existing one in the repo
2) Community made open source projects f.ex Alekhins stuff

**Comment by luanpotter** [comment]
@impulse totally agree! There are some specific examples in the doc/examples folder, but I think we should add more complete examples as well in the README, like BGUG, haunt, renan's trex, erick's games, alekhin's games...

**Comment by impulse** [comment]
@luanpotter it would also be an option to put community made games in an external curated list and link it from the docs. Would require a new repo though since the awesome-flutter owner does not want to accept small games anymore.

**Comment by renancaraujo** [comment]
How about a "Flame awesome" kind of stuff?

**Comment by impulse** [comment]
Further discussion on the flame-awesome repo: https://github.com/flame-engine/flame-awesome/pull/1
