### ISSUE TITLE
Bring mock_canvas and ordered_set into the monorepo

### ISSUE THREAD

**Issue by st-pasha** [flame-engine/flame#1217]
## What can be improved

The primary advantage of having all flame_* packages in a single repository is that it becomes simple to implement changes that have to span across multiple packages. For the same reason, it would be much more convenient to have `mock_canvas` and `ordered_set` brought under the same umbrella. The `MockCanvas` can either go into `flame_test` repo, or become a mini-package of its own...

As an example, suppose I'm writing a test that uses MockCanvas, and need to add a new mock-drawing command into that class. Currently, this would entail going into another repository, making a pull request there, waiting until it is approved and merged, then waiting until that repository publishes a new release, then updating the dependency version in `flame`, and only then I'd be able to continue writing the test that I was writing. This is an enormous amount of friction...

## Any risks?
I can't think of any.

**Comment by erickzanardo** [comment]
Neither of those packages have direct relation to Flame, they are packages on their own that can be used (and probably are already) by projects not related to Flame.

On the mono repo we only keep things related to flame.

**Comment by st-pasha** [comment]
> they are packages on their own that can be used (and probably are already) by projects not related to Flame.

From the outside world's perspective, they will still remain as standalone packages that can be used by projects not related to Flame.

From the Flame's perspective it makes a lot of sense to integrate those projects (as they were originally part of Flame), in order to make the development within those packages more manageable. We don't want to be in a situation where Flame needs to keep its own implementation of MockCanvas or OrderedSet, or maintain extensions for them.

**Comment by wolfenrain** [comment]
> From the outside world's perspective, they will still remain as standalone packages that can be used by projects not related to Flame.
> 
> From the Flame's perspective it makes a lot of sense to integrate those projects (as they were originally part of Flame), in order to make the development within those packages more manageable. We don't want to be in a situation where Flame needs to keep its own implementation of MockCanvas or OrderedSet, or maintain extensions for them.

I would opt for not adding them in this repo as they are completely separate from Flame (despite the fact that they originated from here or that we use them). If we would put them in here instead of their own repos than we would also get issues related to them here, which would pollute our issue tracking with non-flame related things.
