### ISSUE TITLE
Remove {callOwnUpdate} parameter in updateTree()

### ISSUE THREAD

**Issue by st-pasha** [flame-engine/flame#1219]
## What could be improved
Function `Component.updateTree()` takes an optional parameter `bool calOwnUpdate = true`, which can be removed.

## Why should this be improved
1. The parameter was added very recently, just before the 1.0 release, and there wasn't enough time to carefully consider its implications. We can say that because of its novelty, removing the parameter does not constitute a breaking change.
2. The documentation for the parameter says that "if you call this method (updateTree) from update you need to set callOwnUpdate to false" -- however there is never a need (outside of `FlameGame`) to call `updateTree` from `update`, since the game structure is such that for every component `updateTree()` is called first. The only reason `FlameGame` is an exception is because of an unfortunate fact that both `Game` and `Component` define `update()` to mean different things, and `FlameGame` inherits from both...
3. The real problem with `callOwnUpdate` is that it imposes high burden on anyone who needs to override `updateTree()`, because this parameter has to be propagated everywhere. Then, the implementation of `updateTree` needs to think about what to do if this parameter is either true or false, and that may create impossible challenges. For example, what if the parameter says `callOwnUpdate = true` but the component doesn't implement its own update? Or if the parameter says `callOwnUpdate = false` but the component would not work without calling its `update()` method?

# Any risks?
Minimal. Since the parameter was added very recently, and it is unlikely that anyone created new components that override `updateTree()`, it shouldn't break anyone's code.

# More information
- [x] Are you interested in working on a PR for this?

**Comment by spydon** [comment]
How would it be possible to be able to remove it, since `update` is called from the `GameRenderBox` and we don't want to expose `updateTree`?

**Comment by st-pasha** [comment]
One possible solution:

1. The `Game` class defines method `onGameTick(double dt) => update(dt)`;
2. The `FlameGame` class redefines `onGameTick(double dt) => updateTree(dt)`;
3. The `GameRenderBox` invokes `onGameTick(dt)` instead of `update(dt)`.

**Comment by spydon** [comment]
Sgtm, I think this is a change we should do very soon then since it will be breaking (but it's most likely not a very used feature).
