### ISSUE TITLE
How to draw a "aim" or Is there any way to draw something outside render() ?

### ISSUE THREAD

**Issue by HarrisonQi** [flame-engine/flame#1220]
# Problem to solve

I am developing a function similar to the line of sight (Like the aim in 8 Ball Game)

![image](https://user-images.githubusercontent.com/33210899/145993708-f5eeaea8-e8dc-46a3-b1ec-a707982bbfa9.png)

I wanna draw a line when I touch on screen, and the line will change when my touch position changed, so I use 
```
world.raycast(callback, startPos, endPos);
```
And in my custom `RayCastCallback`, call the "draw line" method in `Game`. Maybe my way is wrong...

Thanks for any help and tips!

# Proposal

Maybe I can access `render()` outside of game?

# More information

**Comment by erickzanardo** [comment]
Can you elaborate more and maybe give some code examples? I don't feel that we have enough information here to help.

For questions, consider joining our discord and asking them there.

**Comment by HarrisonQi** [comment]
Ok, I'll ask in discord
