### ISSUE TITLE
Components may be added into game tree out of order

### ISSUE THREAD

**Issue by st-pasha** [flame-engine/flame#1222]
## Current bug behavior
As noted in a [Discord discussion](https://discord.com/channels/509714518008528896/516639688581316629/920074132488609822), when multiple components are added into a game, they may end up being in a different order from how the user intended. The primary cause for this is that each component is only truly added into the game tree once its `onLoad` has finished its job, which means a component with longer-running onLoad may end up being pushed "to the end of the line".

## Expected behavior
The components should appear exactly in the same order as they were added by the user.

**Comment by erickzanardo** [comment]
If the order is important, those components should have different priorities. This is probably happening because all the components added at the same time, have the same priority.

**Comment by spydon** [comment]
We could solve this by just having a counter and include the components "add number" in the comparator if the priority is the same. I don't think we promise that the order of the components should appear in the order that they are added anywhere, so this would be labeled as an enhancement, and not a bug. I think it would be worth doing it though, I have seen a lot of confused questions regarding this.

**Comment by st-pasha** [comment]
> I don't think we promise that the order of the components should appear in the order that they are added anywhere, so this would be labeled as an enhancement

True, there is no such promise. In fact, we call it the `ComponentSet`, where the word "set" implies orderlessness.
Still, I could easily imagine scenarios where such guarantees are exactly what the user needs. So perhaps in those cases the user might install a different component-set factory that returns order-preserving component sets. 

So, this issue then becomes a Feature Request for such alternative implementation of a ComponentSet.
