### ISSUE TITLE
JoystickComponent's priority

### ISSUE THREAD

**Issue by zhusonger** [flame-engine/flame#1226]
# Current bug behaviour
Hello, I found  `JoystickComponent` has no  `priority ` attribute on constructor,  and it's under my other ’s component  which `priority` greater or equal than 0

# Expected behaviour

`JoystickComponent` need above all of other game component.

**Comment by spydon** [comment]
Good catch, you can still set the priority though, just do it before you add the component.
```dart
final component = JoystickComponent(...);
component.changePriorityWithoutResorting(5);
add(component);
```

**Comment by zhusonger** [comment]
> Good catch, you can still set the priority though, just do it before you add the component.
> 
> ```dart
> final component = JoystickComponent(...);
> component.changePriorityWithoutResorting(5);
> add(component);
> ```

Thanks, it's a great idea.
