### ISSUE TITLE
Slow TapGestureRecognizer

### ISSUE THREAD

**Issue by eskalera** [flame-engine/flame#125]
I register a TapGestureRecognizer like this:
```
Flame.util.addGestureRecognizer(
    TapGestureRecognizer()
        ..onTapDown = (TapDownDetails d) =>
            game.onTapDown(d));
```

which removes one of many SpriteComponents, in a smiliar fashion as done [here](https://github.com/japalekhin/langaw/blob/b255ccb15d9572e0dbeb9049ed2bbfe020cd526d/lib/langaw-game.dart#L208) in the Langaw Game, by calling this method
```
void onTapDown(TapDownDetails d) {
    for (var comp in components) {
      if (comp is MyComponent) {
        if (comp.toRect().contains(d.globalPosition)) {
          remove(comp);
        }
      }
    }
  }
```
My problem is that the response of the `onTapDown` is not smooth. The component must be tapped a bit longer than expected.

I have looked at the memory heap and Flutter performance and everything seems to be ok. 
I tried attaching the `TapGestureRecognizer` to every `Component`, but all components disappear at once when one is tapped.

Is the loop over components the way you'd go? Is there any way you recommed attaching a `TapGestureRecognizer` to a `Component`? 

Regards.

**Comment by erickzanardo** [comment]
A couple of questions to help us try to track your problem:

Where did the problem happen? iOs? Android? Both?
Are you using `Game` or `BaseGame` class?
Did you tried setting a `print` on the beginning of the onTap method? To be sure that the problem is with the gesture or the game logic?

About using a `for` I don't much problem, unless the number of components are really, really high, otherwise it should not bring any perfomance issues.

**Comment by eskalera** [comment]
It happened in a OnePlus 5 with Android 9. I haven't tried on an iPhone.
My Game class extends BaseGame.

I did set a print on the onTap method. When it prints, it also does the rest of the onTap method. The problem is that is hard/slow  to get into invoke the event. I need to press the component for a little too long. This behaviour seems to be more accussed some times than others. Usually it never happens the first time after a fresh install.

The number of components on screen at the same time is never higher than 20 to 40 components.

**Comment by erickzanardo** [comment]
But does the print also has delay to happen?

20 to 50 components is not that much and should not bring you any problems.

Do you have any sample code with the problem so we can try to run and test it?

**Comment by eskalera** [comment]
The print happens at the same time as the event. The problem is the event is not responding unless it is long.

I mean, it is not that after tapping I can lift the finger and wait for a delayed response. It is rather that I tap the component multiple times without response, unless I intentionally hold the tap a little longer.

I wouldn't really know what other code to share with you to reproduce the problem, other than the whole project.

**Comment by erickzanardo** [comment]
I see, so this problem may happens because of the arena.

If you have multiple gesture detectors, all possible gestures (drag start, swipe, tap, double tap) will enter the arena and the system will "wait" for one gesture to win before calling the handler for that gesture

Do you have multiple gesture detectors added?

**Comment by eskalera** [comment]
No, this is the only GestureDetector I have. I have read somewhere that the Listener class might be faster than the GestureDetector. Any clue about this?

**Comment by spydon** [comment]
`onTapDown` should trigger after 100ms regardless of whether it has won the arena or not, if it wins the arena and is no longer in contact with the screen `onTapUp` will be called and if it doesn't win the arena `onTapCancel` is called. So I don't think this is a problem with the arena.

**Comment by eskalera** [comment]
I finally solved this although I'm not sure why it happened. It had something to do with the way I bound the BaseGame class with the GameUI, built with Material Widgets. 

```
gameUI = SnailGameUI();
game = SnailGame(gameUI.state);
gameUI.state.game = game;
```
I now do this every time I build the `PlayScreen`, which is a `Stack` with `game.widget` and `gameUI` as children.

**Comment by erickzanardo** [comment]
I am glad you solved it, thanks for reporting back
