### ISSUE TITLE
Input vector gets modified by Forge2DGame.worldToScreen

### ISSUE THREAD

**Issue by ufrshubham** [flame-engine/flame#1254]
# Current bug behaviour
Calling `worldToScreen` method from `Forge2DGame` causes the y component of **input** vector to flip.

# Expected behaviour
Input vector shouldn't be modified.

# Steps to reproduce

Add following code inside `onLoad()` of any Forge2DGame and run the game.
```dart
final vec = Vector2(5, 6);
print(vec);
worldToScreen(vec);
print(vec);
```
You'll see this output:
```
[5,6]
[5,-6]
```

# Flutter doctor output

```
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.22000.376], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.3)
[!] Android Studio (not installed)
[√] VS Code (version 1.63.2)
[√] Connected device (3 available)

! Doctor found issues in 1 category.
```

# More environment information

* flame version: 1.0.0
* flame_forge2d: 0.8.3
* Platform affected: all

# Log information
NA

# More information
`screenToWorld` does not have this bug.

**Comment by ufrshubham** [comment]
Forge2DCamera.projectVector is causing this. Instead of cloning, it scales y component of input vector by -1. If I change,
` ((worldCoordinates...y *= -1) - position)..scale(zoom);`
to
` ((worldCoordinates.clone()..y *= -1) - position)..scale(zoom);`
it solves the problem.

**Comment by spydon** [comment]
Makes sense, do you want to put up a PR for this? (With a small test too preferably)

**Comment by spydon** [comment]
Haha, you must have put up the PR exactly at the same time as I wrote the comment. Nice!

**Comment by ufrshubham** [comment]
Opened a PR already!
