### ISSUE TITLE
Mixin HasCollidables should work with Game

### ISSUE THREAD

**Issue by st-pasha** [flame-engine/flame#1256]
# What could be improved
Currently the mixin is defined as `on FlameGame`, but it should be `on Game` instead.

# Why should this be improved
Because we support more than one type of games (and will support even more in the future), so it would be nice to have collidable functionality in all of them.

# Any risks?
No, since `FlameGame` is a `Game`, so this is an extension of the current functionality.

# More information
Flame v1.0.0

**Comment by spydon** [comment]
The `Collidable` mixin only work on `Component`, so it doesn't make much sense to have it on a game that doesn't support FCS.

**Comment by st-pasha** [comment]
Well, in that case we can ask whether we can make `Collidable` work on non-`Component`s too.
But even if we stick with FCS, `FlameGame` is not the only possible FCS game. For example, we may want to have `FlameGame2` as backwards-incompatible "next evolution" of FlameGame. Also, we give possibility for people to build their own implementations on top of `Game`, so it might be good to support those.

**Comment by spydon** [comment]
By having the mixin as `on FlameGame` it is clear that FCS is needed for it to work, if somebody builds their own FCS game implementation without using `FlameGame`, which I find highly unlikely, we can also reconsider the decision at that point (or just let them create their own mixin, which should be very simple).

I don't think we'll ever create a `FlameGame2`, since we are going to do releases in more of a Flutter manner. I also don't think we want to support non-FCS with collidable's (at least the way they work now), it will be too much over-engineering and harder to maintain.

**Comment by erickzanardo** [comment]
`Game` is the most abstract form of the game, it shouldn't bundle anything other than the basic of a game. It exists for people that wants to build their own solution other than `FCS`, so since collision detection is very tied to FCS, I don't think this mixin should be handled outside our system.

**Comment by st-pasha** [comment]
I see, if the collision system is indeed inseparable* from the component system, then indeed the mixin should depend on an `FCS` game. We don't have the FCS game defined right now, though. Perhaps it could be just a simple interface that participating games would implement?

--
* - what about `OxygenGame` though, don't we want the collisions to work there too?

**Comment by spydon** [comment]
>     * what about `OxygenGame` though, don't we want the collisions to work there too?

Collisions in an ECS sense would work in a completely different way, since that would be a system within ECS acting on the components there (which is a completely different concept to our components, FCS components are more like the entities together with the ECS components).

**Comment by wolfenrain** [comment]
> >     * what about `OxygenGame` though, don't we want the collisions to work there too?
> 
> 
> 
> Collisions in an ECS sense would work in a completely different way, since that would be a system within ECS acting on the components there (which is a completely different concept to our components, FCS components are more like the entities together with the ECS components). I do however think that @wolfenrain tried to make it work by interfacing with the collision detection directly, but the mixin wasn't used for that.

Correct on both the ECS part and me trying to get it to work, I eventually gave up on that as most of the collision code was tied too much into FCS components that it was more of a massive copy paste.

Abstracting the collision code in general could have some benefits as a lower level API, but would be hard imho as it requires a certain "code taste"
