### ISSUE TITLE
Lottie support

### ISSUE THREAD

**Issue by spydon** [flame-engine/flame#1258]
# What could be improved
It would be great to have a bridge package that implemented support for lottie animations.

# Why should this be improved
Lottie is an open source animation file format that’s tiny, high quality, interactive, and can be manipulated at runtime. The top 500 apps on the App store now use Lottie to engage users and enhance conversions.

# Any risks?
Since this would be done as a bridge package; no.

# More information
https://pub.dev/packages/lottie
https://lottiefiles.com/

**Comment by chenenyu** [comment]
[spine](http://esotericsoftware.com/) please 😆

**Comment by spydon** [comment]
> [spine](http://esotericsoftware.com/) please 😆 

That should be its own issue. Looks like there are some dart integrations done for Spine already at least, that the one that builds the bridge library could have a look at.

**Comment by doug-orchard** [comment]
Why not use Rive? Lottie has performance issues especially on iOS. Even the native swift package struggles with anything whilst a Lottie animation is being played.

**Comment by spydon** [comment]
> Why not use Rive? Lottie has performance issues especially on iOS. Even the native swift package struggles with anything whilst a Lottie animation is being played.

We have support for rive already. I didn't know about the performance issues of Lottie, I haven't seen any performance issues in Duolingo for example while they are playing lottie animations, is there anywhere to read more about this?

**Comment by doug-orchard** [comment]
Our iOS devs have struggled to get the animations to play smoothly. They explained the last version degraded performance significantly. https://github.com/airbnb/lottie-ios/issues/1314 is a good example of the issue.

**Comment by spydon** [comment]
Have you tried the Flutter library for it? Since it is pure Dart it is possible that it wouldn't have the same performance issues on iOS.
https://pub.dev/packages/lottie

**Comment by NashIlli** [comment]
> Our iOS devs have struggled to get the animations to play smoothly. They explained the last version degraded performance significantly. [airbnb/lottie-ios#1314](https://github.com/airbnb/lottie-ios/issues/1314) is a good example of the issue.

Hey! That issue [airbnb/lottie-ios#1314](https://github.com/airbnb/lottie-ios/issues/1314) was recently solved and closed. So maybe it i a good time for including lottie in Flame Engine? It would be an amazing feature!

**Comment by NashIlli** [comment]
Any comments on this? I think that the previous issue was resolved on Lottie Ios https://github.com/airbnb/lottie-ios/issues/1314 
Is it on your roadmap or something similar? Thanks in advance! :)
@doug-orchard

**Comment by spydon** [comment]
> Any comments on this? I think that the previous issue was resolved on Lottie Ios [airbnb/lottie-ios#1314](https://github.com/airbnb/lottie-ios/issues/1314) Is it on your roadmap or something similar? Thanks in advance! :) @doug-orchard

If anyone makes a bridge package (`flame_lottie`) just like with rive we will happily review and accept it into the code base. We don't have any plans of creating this package ourselves at the moment.

**Comment by tozu** [comment]
I would be interested looking into this feature :)

**Comment by dipakp2726** [comment]
Hi,
@tozu please let me know if you are not planing to do this,

@spydon i am intersted in taking this one

**Comment by tozu** [comment]
Hi @dipakp2726 

I'm still planning to do this, and I'm currently in the works

My apologies that it takes a bit longer 😥

// Tozu

**Comment by dipakp2726** [comment]
Hi @spydon 
this is indeed special issue and shouldn't have ticket reservation.
if he doesn't able to complete it than an only special issue is going to be wasted,

**Comment by NashIlli** [comment]
Hello @tozu ! Is there an ETA for this issue? We are planning how to handle the animations in Flame and we really hope that we can use Lottie animations.

Thanks a lot for your work!
