### ISSUE TITLE
Clean up uses of expectVector

### ISSUE THREAD

**Issue by st-pasha** [flame-engine/flame#1273]
# What could be improved

In tests we use `expectVector2()`, which could be replaced with `expect(..., closeToVector())`.

# Why should this be improved

The dart-y and flutter-y way of writing tests is through the universal construct `expect(something, matcher)`. The function `closeToVector()` adheres to this standard, whereas `expectVector2` does not. 

Another problem with `expectVector2` is that when it fails, it produces confusing error messages like this:
```
Expected: a numeric value within <0.01> of <0.0>
  Actual: <22.360679774997898>
   Which:  differs by <22.360679774997898>
```
This does not show what the value of the actual vector and the expected vector was.

# Any risks?

No, they are just tests.

**Comment by spydon** [comment]
Should I assign you to this?

**Comment by st-pasha** [comment]
yeah, sure
