### ISSUE TITLE
Clipping mask

### ISSUE THREAD

**Issue by mancj** [flame-engine/flame#1274]
Is there a possibility to create a clipping mask for sprites? 
I mean something similar to [this](https://www.google.com/search?q=clipping+mask+sprite&tbm=isch&ved=2ahUKEwihy9TN1YL1AhXPPOwKHWXgBzcQ2-cCegQIABAC&oq=clipping+mask+sprite&gs_lcp=ChJtb2JpbGUtZ3dzLXdpei1pbWcQAzoFCAAQgAQ6BAgAEB46BAgAEBM6BAgAEBg6BAgeEApQ9QdYzxpghx5oAHAAeACAAXaIAeAGkgEDMi42mAEAoAEBwAEB&sclient=mobile-gws-wiz-img&ei=ZwHJYeH7PM_5sAflwJ-4Aw&bih=655&biw=360&client=ms-android-samsung-ss&prmd=ivsxn&hl=ru#imgrc=TGj4KWVUEFjATM&imgdii=A6QEmxD3vbmrcM)

**Comment by spydon** [comment]
You can clip the canvas that the sprite is rendered on by overriding `render` in `SpriteComponent`, would that achieve what you want?

**Comment by erickzanardo** [comment]
Closing this due inactivity, feel free to add a comment here and we can reopen the issue.
