### ISSUE TITLE
NineTileBox should use canvas.drawImageNine for rendering

### ISSUE THREAD

**Issue by st-pasha** [flame-engine/flame#1282]
# What could be improved and why
Currently, NineTileBox does image patching manually; however the same effect can be achieved with a combination of canvas scaling and [`.drawImageNine`](https://api.flutter.dev/flutter/dart-ui/Canvas/drawImageNine.html) function. This would have the following benefits:
 - simpler code;
 - less buggy (currently, scaling the image up/down several times in the example reveals drawing artifacts);
 - easier to extend (the .drawImageNine doesn't require the source image to be split into 9 **equal** parts, so we can loosen that restriction too).

# Any risks?
Probably, since there are no tests for NineTileBox, it's hard to know if we break anything or not.

**Comment by spydon** [comment]
Wow, had no idea that existed, seems very convenient.
Should I assign you to this?
