### ISSUE TITLE
Noise algorithms

### ISSUE THREAD

**Issue by spydon** [flame-engine/flame#1283]
# Problem to solve
We closed #1263 since we don't want to duplicate functionality already provided by other packages in the dart ecosystem and since it wasn't necessary for anything internally in the engine (yet). However, we are not sure whether https://github.com/frankpepermans/fast_noise/ is actively maintained so that we could add 1d noise in there that @st-pasha wanted.

# Proposal
1. Contact the author of fast_noise to see whether they would be up for accepting PRs or not. (@frankpepermans)
2. If 1 doesn't work, possibly fork that library under blue fire and release it with some other name.

This will give more value to the Flutter+Dart community than having it bundled into Flame.

**Comment by st-pasha** [comment]
As it turns out, we already have implementation of one kind of noise available: the `SimplexNoise` class in the `vector_math_64` library (also adopted from Stefan Gustavson's work). Unfortunately, they don't have 1d noise either.

**Comment by frankpepermans** [comment]
Hey guys,

Wouldn't mind helping out if still needed, gladly accept PRs for fast_noise.

**Comment by spydon** [comment]
That's aweseme @frankpepermans, thanks for the reply.

**Comment by spydon** [comment]
Closing this since we now have flame_noise which we can continue to add more algorithms to.
