### ISSUE TITLE
Flame has a version conflict !

### ISSUE THREAD

**Issue by Pingear** [flame-engine/flame#1284]
Flame 1.0.0 packages differ at https://pub.dev/packages/flame and https://github.com/flame-engine/flame.

ZigzagEffectController, SineEffectController, RandomEffectController and SequenceEffect are missing on pub.dev.
At the same time, both pub and github have the same version 1.0.0

**Comment by spydon** [comment]
You are looking at the `main` branch which is the development branch, if you look at the `1.0.0` tag you'll see the code that has been released. It can be found here: https://github.com/flame-engine/flame/tree/1.0.0

**Comment by Pingear** [comment]
> You are looking at the `main` branch which is the development branch, if you look at the `1.0.0` tag you'll see the code that has been released. It can be found here: https://github.com/flame-engine/flame/tree/1.0.0

Oops!
Sorry, you're right, I was wrong)
