### ISSUE TITLE
Dual Effect and Removal

### ISSUE THREAD

**Issue by YohanWadia** [flame-engine/flame#1287]
# What could be improved
Some Example or Code to show how to add & remove effects when you are using more than 1 effect on a component.

# Why should this be improved
There is surely a time when you might need one effect to stop... but the other effect is needed to go on

# Any risks?

# More information
SO this is what I have come up with

```
import 'package:flame/components.dart';
import 'package:flame/effects.dart';
import 'package:flame/game.dart';
import 'package:flame/input.dart';
import 'package:flutter/material.dart';
import '../../commons/ember.dart';

class DualEffectRemovalExample extends FlameGame with TapDetector {
  static const String description = '''
    In this example we show how a dual effect can be used.
    And removed.To remove just tap anywhere on the screen.
    1st tap will remove Opacity Effect 2nd tap removes the color effect.    
  ''';

  late final SpriteComponent mySprite;
  late  ColorEffect fx;
  late OpacityEffect opfx;
  int count = 0;
  EffectController controller1 = EffectController(duration: 2,reverseDuration: 2,infinite: true,);
  EffectController controller2 = EffectController(duration: 1,reverseDuration: 1,infinite: true,);

  @override
  Future<void> onLoad() async {
    await super.onLoad();

    Sprite flameSprite = await loadSprite('flame.png');
    Vector2 sz = flameSprite.srcSize;
    Vector2 pos = Vector2(50,50);
    mySprite = SpriteComponent(sprite: flameSprite,position: pos,size: sz);
    add(mySprite);
    fx = ColorEffect(Colors.blue, const Offset(0.0, 0.8,), controller1 );
    mySprite.add(fx);
    opfx = OpacityEffect.fadeOut(controller2);
    mySprite.add(opfx);


  }

  @override
  void onTap() {
    count++;
    if(count>1){
      controller1.setToStart();
      Future.delayed(const Duration(milliseconds: 25), () {
        mySprite.remove(fx);
      });
    }
    else{
      controller2.setToStart();
      Future.delayed(const Duration(milliseconds: 25), () {
        mySprite.remove(opfx);
      });
    }
  }

}
```
# Question about Controller's Behavior
Whats weird in my trials is that- if I ran the code without **Future.delayed(eg. code below)** it always failed to work correctly. Any idea about why does that happen... is it an expected behavior?
```
//below code was unsuccessful
controller2.setToStart();
mySprite.remove(opfx);

```

Yes I would like to rectify this efficiently with your help and submit a PR.

**Comment by st-pasha** [comment]
This happens because when you reset controller to start, this changed isn't applied to the effect itself until the next call to `update()`. However, you also remove the effect immediately, so the change never gets applied.

Try the following:
```dart
    if (count > 1) {
      fx.apply(0);
      fx.removeFromParent();
    }
    else{
      opfx.apply(0);
      opfx.removeFromParent();
    }
```

**Comment by YohanWadia** [comment]
@st-pasha ... thanks for the reply. It works like charm and I feel way more efficiently than my workaround... AND...
Yes, what you said makes sense for the observed behavior.
I think this is important, as dual effects and their removals are often used. Especially when they are removed from a component separately. I will submit a PR. thanks
