### ISSUE TITLE
After upgrading to 1.0, below Android 9 cannot use the physical buttons to adjust the volume

### ISSUE THREAD

**Issue by nasio-limbo** [flame-engine/flame#1288]
# Current bug behaviour

After upgrading to 1.0, the system below Android 9 cannot use the physical buttons to adjust the volume

# my code
## main.dart
![1](https://user-images.githubusercontent.com/81147916/147814528-7d3a2176-579a-481a-9c50-5413d1df8406.png)
## game.dart
![2](https://user-images.githubusercontent.com/81147916/147814532-3ec9baeb-216a-4654-ac55-f42bbbfddfad.png)

**Comment by st-pasha** [comment]
This doesn't seem to be Flame-related, perhaps you can ask on the Flutter repository?

**Comment by nasio-limbo** [comment]
Before i enter game, i can use physical button to change volume. But when i press action button enter game, physical button not working. android os version is below 9, after 9 is no issue.

**Comment by nasio-limbo** [comment]
my solution is:

`GameWidget(game: _game!, autofocus: false)`

autofocus default is true, while android os version is below 9 should set false.
