### ISSUE TITLE
An onReleased callback for HudButtonComponent

### ISSUE THREAD

**Issue by ufrshubham** [flame-engine/flame#1290]
# Problem to solve

Right now `HudButtonComponent`  only exposes `onPressed`. If an `onReleased` is also provided, it will make it easier for users to perform some action while the button is held down. For example, hold to fire or hold to keep moving.

# Proposal

Add `void Function()? onReleased;` member to `HudButtonComponent`, expose it as an optional parameter to constructor and then call it from `onTapCancel()`.

# More information
Yes, if proposed solution is acceptable, I can submit a PR.

**Comment by spydon** [comment]
> it will make it easier for users to perform some action while the button is held down.

This is what the current callback is doing?

> expose it as an optional parameter to constructor and then call it from onTapCancel().

I think that it should be called from `onTapUp` and not `onTapCancel`, but other than that is sounds like a good addition.
Do you want me to assign you to this issue?

**Comment by ufrshubham** [comment]
Yeah, you can assign this to me.
