### ISSUE TITLE
ContactCallback is invalid if not set the userData of bodydef. And there's not any hints

### ISSUE THREAD

**Issue by HarrisonQi** [flame-engine/flame#1291]
# Current bug behaviour

ContactCallback is invalid if not set the userData of bodydef
```dart

class XXComponent extends BodyComponent {
  
   ...

  @override
  Body createBody() {
    final bodyDef = BodyDef()
      ..userData = this.       // if not set this, ContactCallback is invalid
      ..type = BodyType.kinematic 
      ..position = initPosition; 
   
   ...
  }
}

```

# Expected behaviour

Need any hint, or set default userData, or set it as required... Any way just let developer know. This problem takes me a few hours..

# Steps to reproduce

# Flutter doctor output

```
Output of: flutter doctor -v
```

# More environment information

# Log information

```
Enter log information in this code block
```

# More information

**Comment by spydon** [comment]
There is not much docs about Forge2D, but this particular thing is actually in the docs:
https://docs.flame-engine.org/1.0.0/forge2d.html?highlight=forge2d#contact-callbacks

**Comment by spydon** [comment]
I don't think there is anything we can do here, because userdata shouldn't be mandatory (and it can't since it is not an argument). So I'll close this.
