### ISSUE TITLE
Tappables hit location based on Window size and not Canvas size

### ISSUE THREAD

**Issue by doug-orchard** [flame-engine/flame#1292]
# Current bug behaviour
If a canvas size is set (FixedResolutionViewport) when adding a tappple component, the hit area ignores the canvas position and prefers the windows position. For example a canvas size of 360x720 but window is 1440x720 the hit would be position according to the window space and not game space however the component would be located to the canvas space. Making the hit and component separated.

# Expected behaviour
Hit area for tappables aligned with game space and their respected component.

# Steps to reproduce
Obviously a MacOS issue since you can resize. 
• Fixed a game/canvas space. 
• Add a tappable with a fixed location.
• resize window. 
•try to hit the original tappable.

# More environment information
* Flame version: 1.0.0
* Platform affected: macOs

**Comment by spydon** [comment]
What do you mean with a fixed canvas space?
I just tried with a `FixedResolutionViewport` and it works fine while resizing.
Could you provide a MWE?

**Comment by doug-orchard** [comment]
Seems after some investigating, a misplaced translate ended up being the issue. :(

**Comment by spydon** [comment]
> Seems after some investigating, a misplaced translate ended up being the issue. :(

Ah, we have all fallen into that trap in the beginning. Just as a hint to others that might end up on this issue; you almost never have to use `translate`. Set the `position` of your component and all the translation will be done for you by the engine.
