### ISSUE TITLE
FlameGame.onGameResize - Zero value when game is closed and restarted

### ISSUE THREAD

**Issue by couturmi** [flame-engine/flame#1293]
# Current bug behaviour
I'm seeing this issue on iOS (physical device only) when the app is closed/dismissed then quickly reopened.

On the first run the `onGameResize` will return a nonzero `Vector2`.
After closing & reopening, the `onGameResize` returns (0,0).

The below images show the different states of printing the `Vector2` passed to `onGameResize` on startup:
| First Run| After Closing and Restarting |
| ------- | ------- |
| <img src="https://user-images.githubusercontent.com/9330448/148103606-4eeffad6-64e0-4fc7-80cd-cd667c37f95e.PNG" height=400> | <img src="https://user-images.githubusercontent.com/9330448/148103570-4299692c-6655-48b6-8c10-69f80ae2fc40.PNG" height=400> |

This issue is causing any components that depend on game size (whether it be size or position) to be incorrectly loaded on startup. In my case, many components are all appearing in the top left corner rather than the center since the gameSize is 0.

# Expected behaviour
`onGameResize` should always return a nonzero size when the app is started.

# Steps to reproduce
I have only noticed this issue on physical iOS devices (simulator does not have this issue).

This occurs with only this small amount of code in a new Flutter project:
```
import 'package:flame/components.dart';
import 'package:flame/game.dart';
import 'package:flutter/material.dart';

class MyGame extends FlameGame {
  String text = "";
  @override
  Future<void> onLoad() async {
    text += "onLoad occurred\n";
    await super.onLoad();
    add(TextComponent(text: text, position: Vector2(50, 50)));
  }

  @override
  void onGameResize(Vector2 canvasSize) {
    text += "onGameResize occurred\n\tCanvas Size: $canvasSize\n";
    super.onGameResize(canvasSize);
  }
}

main() {
  final myGame = MyGame();
  runApp(
    GameWidget(
      game: myGame,
    ),
  );
}

```
1. On a physical device, open the app and confirm that the size text displayed is a nonzero Vector2.
2. Swipe up and dismiss/close the app.
3. Quickly reopen the app and confirm that the size text is now (0,0). _(If this did not occur, repeat steps 2-3 a few times until it does)_

# More environment information
* Flame version: 1.0.0
* Flutter version: 2.8.1
* Dart version: 2.15.1

# Log information
n/a

**Comment by spydon** [comment]
Strange, is there another resize after the (0, 0) resize?

**Comment by couturmi** [comment]
> Strange, is there another resize after the (0, 0) resize?

After the (0, 0) resize, the app will continue to open with (0, 0). 
I have been able to successfully "reset" the app error state by:
1. Closing the game app.
2. Opening up / scrolling around other applications on the device for a bit.
3. Reopening the game app.

**Comment by mancj** [comment]
I think this issue related to mine #1305

**Comment by couturmi** [comment]
> Strange, is there another resize after the (0, 0) resize?

After some further testing, it does look like `onGameResize` is called again after the (0,0) resize, but at this point, both `onLoad` and `onMount` have already been called, so any component initialization that needed the actual game size would already have occurred.

So the order is as follows:
1. `onGameResize` - (0, 0)
2.  `onLoad` 
3. `onMount`
4. `onGameResize` - (x, y)

**Comment by mancj** [comment]
@couturmi i did a simple fix, could you please check if this bug is reproduced on this branch? https://github.com/mancj/flame/tree/fix-game-resize

**Comment by couturmi** [comment]
@mancj The issue still occurs even with running off of your branch

**Comment by st-pasha** [comment]
@couturmi Can you check if #1308 resolves the problem?

**Comment by couturmi** [comment]
@st-pasha Still seeing the issue even after using your branch

**Comment by st-pasha** [comment]
@couturmi Can you put a breakpoint in your `onGameResize` and then post a stacktrace of what happens when size is zero?

**Comment by couturmi** [comment]
Like I said, the issue only occurs after closing the application and reopening it directly (only on physical iOS devices). 
To achieve this, I've had to archive/export to my device directly every time I retest.

I'm not able to check for a breakpoint.

But as I've already said, this is the flow of events:

> So the order is as follows:
> 
> onGameResize - (0, 0)
> onLoad
> onMount
> onGameResize - (x, y)

**Comment by st-pasha** [comment]
I think the best course of action here would be to delay marking the game as `hasLayout = true` and running its `onLoad()` method until it receives non-zero canvas size. I'm not sure how to implement this though.

**Comment by spydon** [comment]
> I think the best course of action here would be to delay marking the game as `hasLayout = true` and running its `onLoad()` method until it receives non-zero canvas size. I'm not sure how to implement this though.

We have actually had that logic before, and it was accidentally removed because it was thought to not being needed anymore. Does anyone have a pointer to the old code that did this @flame-engine/flame-colab?

**Comment by st-pasha** [comment]
@couturmi Could you please check whether #1337 solves this problem?

**Comment by couturmi** [comment]
@st-pasha It looks like #1337 does fix the problem. I'm not able to reproduce the issue on that branch.
