### ISSUE TITLE
Spritesheet json support

### ISSUE THREAD

**Issue by michael-ottink** [flame-engine/flame#1295]
# Problem to solve
From what we could tell from the docs, there is no way to read spritesheet information from a json file. Applications like TexturePacker are exporting a json file that contains information on the position, size and orientation of each sprite and also contains the animations. This would increase productivity.

# Proposal
Having a json file structure for spritesheets that suits the flame idiomatic way of creating animations (we use the pixijs data settings). And having a parser that can parse the json file and output animations. Possibly even contacting TexturePacker if they can add support for this format. And have included in the documentation.

**Comment by spydon** [comment]
We have the [FireAtlas](https://github.com/flame-engine/fire-atlas) editor and format, have you looked into that anything?

**Comment by spydon** [comment]
Have you tried [flame_texturepacker](https://github.com/Brixto/flame_texturepacker)? It was just updated to support 1.0.0 (it's a package maintained by a community member).

**Comment by erickzanardo** [comment]
Closing this since we have fire atlas and texture packer already for that.

Feel free to add a comment with additional info in case any of the options above don't fit your need.
