### ISSUE TITLE
renderFlipX and renderFlipY is not working according to the specifications.

### ISSUE THREAD

**Issue by Pingear** [flame-engine/flame#1303]
Hi) 
The documentation says to change the direction of your components rendering, you can also use renderFlipX and renderFlipY - https://docs.flame-engine.org/1.0.0/components.html#render-positioncomponent 
but the code editor swears that -  The setter 'renderFlipX' isn't defined for the type 'SpriteAnimationComponent'.

**Comment by ufrshubham** [comment]
From the changelog I can see that `renderFlipX` and `renderFlipY` were replaced with `flipHorizontally()` and `flipVertically` respectively in rc14. Docs must have gotten out of sync then.
