### ISSUE TITLE
Deprecate Images.decodeImageFromPixels

### ISSUE THREAD

**Issue by st-pasha** [flame-engine/flame#1315]
# What could be improved

Currently, the documentation (`images.md`) says the following:
```
The [dart-ui decodeImageFromPixels](https://api.flutter.dev/flutter/dart-ui/decodeImageFromPixels.html)
currently does not support the web platform. So if you are looking for a way to manipulate pixel
data on the web this method can be used as a replacement for `dart-ui decodeImageFromPixels`:
```

However, the referenced problem has already been fixed upstream (https://github.com/flutter/flutter/issues/45190), so our own function can be removed (via the deprecation process of course). 

So I suggest to:
 1. mark the function `Images.decodeImageFromPixels` as deprecated;
 2. ignore its `runAsWeb` parameter;
 3. remove `_createBmp`.

Besides reducing the amount of code, this will also fix a memory leak that currently exists in the `_createBmp` function.

# Any risks?
Unlikely.

# More information
Somewhat related to #1312

**Comment by spydon** [comment]
Sgtm, what do you think @erickzanardo? (I think you wrote that function)

**Comment by erickzanardo** [comment]
> Sgtm, what do you think @erickzanardo? (I think you wrote that function)

I think it was @wolfenrain actually. But it LGTM, always good to remove fallbakcs

**Comment by spydon** [comment]
Should I assign you to this @st-pasha?

**Comment by st-pasha** [comment]
ok
