### ISSUE TITLE
🐘 Upgrade events system

### ISSUE THREAD

**Issue by st-pasha** [flame-engine/flame#1326]
This issue records that, which we have known for quite some time now, but didn't dare to bring up: **our events system no longer fits into the Flame engine**.

For the background, the Flame engine is built around the concept of a _component tree_ -- the structure that contains all components that are currently in game. The semantics of this tree is that of ownership: which components "own" which; but we also use the tree in order to traverse it in order to dispatch `update` events, `render` events, `resize` events, pointer (tap/drag) events (tap/drag), etc.

The `render` events are of particular interest here, because pointer events ought to be dispatched to whichever component is rendered at that point of the screen where the event occurred. So, in the "normal" case, the components in the tree are rendered according to their pre-order traversal. But it is also possible that a component overrides their `renderTree()` method, completely altering their rendering pipeline. 

Thus, if an engine allows the components to be rendered out-of-tree-order, it must also allow for the pointer events to be properly dispatched to those rendered components.

I don't know yet how exactly to implement this upgrade, so this issue is a call for proposals. I'll post mine too, if I come up with one. But regardless, this elephant in the room ought to be addressed.

**Comment by spydon** [comment]
We are pretty clear with that children will have to live within their parents boundaries (the parent can override `containsPoint` if it wants to expand the standard boundaries). I think this enhancement won't give much to the engine, or do you have an example where this would be useful? 

It will also potentially be less efficient since we'll have to traverse more components, but I don't think that is important here.

**Comment by st-pasha** [comment]
> We are pretty clear with that children will have to live within their parents boundaries

I never seen this statement in the docs; regardless, it can't be true, because many components (notably `Component`) have no notion of size or boundaries.

> do you have an example where this would be useful?

Of course: any component that implements non-standard `renderTree()`:
 - `PositionComponent` changes the canvas coordinate system within its `renderTree`. However, we also require that all other components be aware of this behavior, and recalculate event coordinates within their `containsPoint` method. It's not documented anywhere, but it works. And yes, it's a hack.
 - `FlameGame` has a `Camera` that also does some coordinate transformations. It works right now because we hard-coded camera transforms into the event itself. Which means it no longer works when you have a game-in-game.
 - `ParallaxComponent` does some interesting manipulations with canvas coordinates; it also doesn't support having children components, so you won't notice that events don't work correctly there.
 - And then, of course, the most important category: user-defined components:
   - A component that "hides" some of its children (better not be able to tap them);
   - A component that clips its children content (don't propagate event if it's clipped);
   - A component that skips rendering some of its children if it knows they are off-screen (better not waste our time trying to "click" them);
   - A minimap component, which has its own camera - not that different from game-in-game;
   - "Mirror image" magic component that renders several copies of its children in different places on the screen.

And so on. The point is, surely `renderTree` is an advanced feature, but we have to fully support that feature, including handling of events.

**Comment by spydon** [comment]
> I never seen this statement in the docs; regardless, it can't be true, because many components (notably `Component`) have no notion of size or boundaries.

If you want your component to be tappable, you just override `containsPoint`, or you add children to it that implement `containsPoint`, which makes it possible to have it as a layer for `PositionComponent`s without having to extend it.

>     * `FlameGame` has a `Camera` that also does some coordinate transformations. It works right now because we hard-coded camera transforms into the event itself. Which means it no longer works when you have a game-in-game.

True, that needs to be looked into.

> And so on. The point is, surely `renderTree` is an advanced feature, but we have to fully support that feature, including handling of events.

If you have a good idea of how to be able to support this without making the base case (and the internal code) much more complex I'm all ears, to me it sounds like it would be a lot more complicated than it currently is and only very few would benefit from it. But if you (or somebody else) can come up with a simple system that can provide this it would definitely be a good enhancement!

**Comment by st-pasha** [comment]
> But if you (or somebody else) can come up with a simple system that can provide this it would definitely be a good enhancement!

Absolutely, would be great to hear different designs and compare their pros and cons. Here's what I've been able to come up with so far:

### A Modest Proposal
Define a method in the base `Component` class:
```dart
Iterable<Component> raycast(Vector2 point) sync*;
```
The idea of this method is that it takes a `point` (in the component parent's coordinate space), and produces an iterator of components that intersect with that point, including self. The default implementation would be something like this:
```dart
Iterable<Component> raycast(Vector2 point) sync* {
  if (children != null) {
    for (final child in children!.reversed()) {
      yield* child.raycast(point);
    } 
  }
  if (containsPoint(point)) {
    yield this;
  }
}
```
Any component that redefines `renderTree` would then be strongly advised to override `raycast()` method as well, and make sure that both methods are working in unison.

For example, `PositionComponent` would override it to apply coordinate transform to `point` before passing it to children. The `Camera` would override it in order to properly account for those "ignoreCamera"/"ignoreViewport" flags. The component that hides some of its children would simply skip those children during raycasting. The component that clips its children would check whether the `point` is inside the clip mask before propagating raycast. And so on.

The events system is then built on top of this raycast method: whenever an event comes in which defines a point in the canvas coordinate space, we raycast it into the top-level Game instance, which yields a sequence of components that are at the point where the event has occurred. We iterate through those components until we find one that can respond to the event (`Tappable`, `Draggable`, etc) and trigger the corresponding `onEvent()` callback. After the callback we either stop iterating, or continue, depending on whether the user requested to stop propagation or continue.

The name "raycast" (instead of, say, "propagatePointerEvent") because it's a generic procedure that may also be used for things other than events.

**Comment by spydon** [comment]
Looks quite good. A few concerns though:

 - It doesn't seem to be a way to stop the propagation if a child has handled the event?
 - It should probably be called raycastZ or something since it only raycasts in that axis, if I understand it correctly, and later there should be more classic raycast methods related to the hitboxes.
 - This also overlaps a bit with the hitboxes which will be added as component children in the new design, feels like this could cause problems with them?

**Comment by st-pasha** [comment]
> It doesn't seem to be a way to stop the propagation if a child has handled the event?

The method returns an iterable, so you stop propagation at any point by `break`-ing out of the iteration loop.

> It should probably be called raycastZ or something since it only raycasts in that axis, if I understand it correctly

The default implementation raycasts in the _priority_ order (which should have been called Z, but for some reason wasn't), because that's how default rendering is set up. However, other renderers can use their own rendering logic, so they would implement raycasting accordingly. For example, an `IsometricCamera` may order the components according to their `x-y`. 

> and later there should be more classic raycast methods related to the hitboxes.

I'm not sure I understand this -- how are hitboxes related here?

**Comment by spydon** [comment]
> The method returns an iterable, so you stop propagation at any point by `break`-ing out of the iteration loop.

But how does a child "tell" that to the parent?
 
> The default implementation raycasts in the _priority_ order (which should have been called Z, but for some reason wasn't), because that's how default rendering is set up. However, other renderers can use their own rendering logic, so they would implement raycasting accordingly. For example, an `IsometricCamera` may order the components according to their `x-y`.

Alright, hmm, maybe this shouldn't be called raycast since you can't really choose how to cast the ray, or not in the normal sense at least?

> I'm not sure I understand this -- how are hitboxes related here?

Because hitboxes are used to determine whether a gesture is within a component or not.

**Comment by spydon** [comment]
> which should have been called Z, but for some reason wasn't

I think that this was due to that we might have an actual Z in the future and that `priority` also controls which order they are updated in.

**Comment by st-pasha** [comment]
> But how does a child "tell" that to the parent?

I guess, in much the same way as it's doing it now? Suppose you're processing `tapDown` event, and a child is "hit" by a ray. If the child is `Tappable`, we would call its `onTapDown` handler, which would in turn either return a `false` or set up a `stopPropagation` flag, and thus we'll know that iteration can be stopped.

> Alright, hmm, maybe this shouldn't be called raycast since you can't really choose how to cast the ray, or not in the normal sense at least?

I believe what you're saying is that, generally, a ray can be cast from any object and in any direction, whereas in this case we have a ray that's coming from the screen itself. So maybe we could call it `raycast4thWall()` -- because that's where it's coming from.

**Comment by spydon** [comment]
> I guess, in much the same way as it's doing it now? Suppose you're processing `tapDown` event, and a child is "hit" by a ray. If the child is `Tappable`, we would call its `onTapDown` handler, which would in turn either return a `false` or set up a `stopPropagation` flag, and thus we'll know that iteration can be stopped.

Ah yes ofc, I mixed up how it works.

> I believe what you're saying is that, generally, a ray can be cast from any object and in any direction, whereas in this case we have a ray that's coming from the screen itself. So maybe we could call it `raycast4thWall()` -- because that's where it's coming from.

Yes, exactly, and we don't want it to be confused when we have a more general raycasting concept in the collision detection system later. Hmm, naming is always so hard... Not completely satisfied with `raycast4thWall()` either.

**Comment by st-pasha** [comment]
Ok, just brainstorming here:
- `cherrypick()`
- `pickComponents()`
- `pointIntersection()`
- `queryRender()`

**Comment by spydon** [comment]
`pointIntersection` I quite like, then it sounds related to `containsPoint` too.

**Comment by spydon** [comment]
This should not be closed yet right?

**Comment by st-pasha** [comment]
Yeah, I'd say we need drag events too, and then it's good to close.

**Comment by pdeveltere** [comment]
this still seems to be a problem. The tappable events are not correct, whem I do camera movements. e.g. zoom or snapTo...

**Comment by st-pasha** [comment]
You would need to use the new CameraComponent, see https://docs.flame-engine.org/1.3.0/flame/camera_component.html
