### ISSUE TITLE
Improving Flame testing by allowing users to wait for game to load

### ISSUE THREAD

**Issue by erickzanardo** [flame-engine/flame#1335]
# What could be improved
Right now, when unit testing a flame game, it is very hard to ensure that the game is loaded before triggering events, making assertions, this makes testing quite challenging sometimes.

We have however an easy way to provide this for users. the FlameGame class already have an attribute called `onLoadCache`, which holds a future of the loading of the game, by awaiting that future, we can be sure that the game was completely loaded.

The problem is that this attribute is marked with `@internal`.

My suggestion is to keep that attribute internal, but offer a public getter for it, so people can write their tests like this example:

```dart
          tester.widgetTest(
            'pick up the item when it is close enough',
            (game, tester) async {
              await tester.pump();

              await game.ensureAdd(
                Pickupable(item: GameItem.sword)
                  ..position = Vector2(
                    0,
                    40,
                  ),
              );

              await game.gameLoading();
              await tester.pump();

              final event = MockRawKeyDownEvent();
              when(() => event.logicalKey).thenReturn(LogicalKeyboardKey.space);

              game.player.onKeyEvent(event, {});

              verify(
                () => inventoryBloc.add(
                  const GameItemPickedUp(GameItem.sword),
                ),
              ).called(1);
            },
          )
```

Maybe this is something that cold be handled on #1333 
 
# Why should this be improved
To make testing easier

# Any risks?
None come to mind

# More information

**Comment by erickzanardo** [comment]
Unfortunately calling pump doesn't ensure that the game is loaded because the loading, since the onLoad is called on a future builder, that may take several frames to finish.

**Comment by Dev-Owl** [comment]
Would it not be an option to provide a loaded game to the widget by default? So, calling `initializeGame`  and hand it to the widget? That code is already there and at least for the `test` method it works fine.

**Comment by erickzanardo** [comment]
I am not sure, if that would work, but still, I wouldn't do that, the user may want to test their load state for example, if we provide a loaded game already, that wouldn't be possible.

I think that just providing a way for the user to ensure that the game is loaded before triggering stuff and doing asserts is the only way to cover all the possible scenarios.

We could provide helpers though, like a test method that abstract that for the user and only call the verify method once the fame has finished loading and things like that.
