### ISSUE TITLE
Scrolling background loop anomaly with ParallaxComponent

### ISSUE THREAD

**Issue by magicleon94** [flame-engine/flame#134]
Hi,
I'm trying to achieve an infinite scrolling background by looping an image which has end and beginning contiguous.
As far as I discovered from the docs, using a `ParallaxComponent` should do the trick, so this was my test:

```
class BoxGame extends BaseGame {
  Size screenSize;
  bool loaded = false;
  ParallaxComponent parallaxComponent;

  BoxGame() {
    _start();
  }

  void _background() {
    parallaxComponent = ParallaxComponent();
    parallaxComponent.load(["background.jpg"]);
    add(parallaxComponent);
  }

  void _start() {
    _background();
    loaded = true;
  }

  @override
  bool debugMode() => true;

  void render(Canvas canvas) {
    Rect bgRect = Rect.fromLTWH(0, 0, screenSize.width, screenSize.height);
    Paint bgPaint = Paint();
    bgPaint.color = Color(0xffffffff);
    canvas.drawRect(bgRect, bgPaint);

    if (parallaxComponent.loaded()) {
      parallaxComponent.render(canvas);
    }
  }

  void update(double t) {
    if (parallaxComponent.loaded()) {
      parallaxComponent.update(t);
    }
  }

  void resize(Size size) {
    screenSize = size;
    if (parallaxComponent.loaded()) {
      parallaxComponent.resize(size);
    }
    super.resize(size);
  }
}
```

Now, the scrolling is ok, but even if it loops in the first place, it jumps to the beginning unexpectedly while scrolling, like the animation resets or something.
[Here's a video of what's happening to me](https://streamable.com/65i39)
and this is the background image. ![](https://user-images.githubusercontent.com/5605705/61566282-ecad7200-aa7b-11e9-8875-83ede0f2e04d.jpg)

What am I missing?

**Comment by erickzanardo** [comment]
A new ParallaxComponent was added on #138 I think this will solve what you are trying to achieve, if you want to try right away you can point your Flame dependency to the develop branch. Otherwise a new release of Flame should be shipped next week.

Sorry for the delay to handle this issue.
