### ISSUE TITLE
Move `prepareComponent` to after the onMount

### ISSUE THREAD

**Issue by st-pasha** [flame-engine/flame#1340]
Currently, `FlameGame.prepareComponent` is executed as the very first method in component's lifecycle, before even `onLoad`. However, `Component.onLoad` is the place where the component is usually initialized, and can be considered as "asynchronous constructor". After `onLoad` is finished, the component can be considered fully initialized, and after `onMount` is finished, the component is fully integrated into the game tree.

I argue that it is not safe to execute `prepareComponent`, which may contain arbitrary code, before the component is fully initialized or mounted.

For example, currently `prepareComponent` is used in 2 places: `FlameBlocGame` uses it to subscribe the component to some state-change events, and `HasCollidables` puts the component into the list of things that can collide. Both of these use cases only need that the component was "prepared" at _some point_; in fact they'd probably prefer to only deal with the components that are fully initialized/mounted. It might even be the case that those use-cases contain actual bugs if acting upon a component that hasn't finished loading before it receives a subscription event or needs to handle a collision.

NB: the "main" `prepareComponent` is currently in charge of calling `onGameResize`, but that method can just as easily be invoked from the `add()` method itself. This would even improve encapsulation, since `FlameGame` shouldn't really be responsible for handling part of the `Component`s lifecycle.

Given all this, I'd suggest the following change in component's lifecycle:
 - `prepareComponent` to be invoked only after the component is fully loaded and mounted;
 - rename the method into `onChildMounted`, to make the name better match the intended purpose.

**Comment by spydon** [comment]
It also sets the parent which needs to be done before `onLoad`, but possibly that could be done by add too.

**Comment by spydon** [comment]
The plan was to remove `prepareComponent` completely after v1 actually, we never made a ticket for it but we have it on our internal planning board. Which usecases do you see for the `onChildMounted` lifecycle method?

**Comment by st-pasha** [comment]
There are currently 2 use-cases: in FlameBlocGame, and in Collidables.
So if those can be removed, it'd be even better.

**Comment by erickzanardo** [comment]
I am not sure about collisions, but I was planning on moving the bloc subscription to the onMount of the components, but never got to it.
