### ISSUE TITLE
Spine support

### ISSUE THREAD

**Issue by phamconganh** [flame-engine/flame#1341]
# Problem to solve

It would be great to have a bridge package that implemented support for spine animations.

# Proposal

I tested some spine in the example of spine_flutter package. Has any plan for render spine on flame?

# More information

https://github.com/jtakakura/spine_flutter

**Comment by spydon** [comment]
> Has any plan for render spine on flame?

We don't have any plan for it currently, but I think it would be a very good fit for a bridge package so if someone wants to work on this it shouldn't be a problem.

**Comment by magixmin** [comment]
Dose rive can replace the spine features?

**Comment by dipakp2726** [comment]
@phamconganh @spydon 
the package [spine_core](https://pub.dev/packages/spine_core) is not an open source.
please check License.

**Comment by spydon** [comment]
> i dont think we should bridge non-open source package

I don't know how common spine is, but if it is quite heavily used I think it could bring value to our users by having a bridge package for it. Possibly we shouldn't include it in the monorepo though.

**Comment by dipakp2726** [comment]
i am interested in working on this.

**Comment by dipakp2726** [comment]
hey @spydon, i would like to work on this

**Comment by spydon** [comment]
Alright, I've assigned you!

**Comment by aytunch** [comment]
It would be awesome if Rive supports characters created with their platforms to be used in Flame games and be controlled by their spine/skeletons.
https://rive.app/
They have great support for Flutter so far so maybe they will consider this. Anyone have any contact from their team?
