### ISSUE TITLE
Outdated example : Zoom , Coordinate System

### ISSUE THREAD

**Issue by Sid911** [flame-engine/flame#1345]
# What could be improved
Currently the example codes doesn't account for current version of 🔥 flame engine (1.0.0) where [ScaleUpdateInfo](https://pub.dev/documentation/flame/latest/input/ScaleUpdateInfo-class.html) where the property `delta` is not present

I haven't used flame engine long enough to know the api's but either this has been removed intentionally or mistakenly but either way the example should be updated appropriately.

Example - Zoom page
https://github.com/flame-engine/flame/blob/6e66baa12fdad7b27f35ca274433acd55165f106/examples/lib/stories/camera_and_viewport/zoom_example.dart#L55-L63

Coordinate Example Page - 
![image](https://user-images.githubusercontent.com/27860105/151855395-29d65072-b5c3-4cb8-8ba0-c2f2c216b8c3.png)
The coordinate page always has delta empty for some reason while the zoom page works

# What it is currently
Current implementation doesn't have any similar property from what I can tell (please do let me know if there is one) but either way the code should be updated for the current version

For zoom example A migration could be as simple as setting a field as we do for zoom variable anyway

```dart
class ZoomExample extends FlameGame with ScrollDetector, ScaleDetector {
....
  Vector2 startScalePosition;
....
  @override
  void onScaleStart(ScaleStartInfo info) {
    startPosition = info.eventPosition.game;
    startZoom = camera.zoom;
  }

  @override
  void onScaleUpdate(ScaleUpdateInfo info) {
    final currentScale = info.scale.global;
    if (!currentScale.isIdentity()) {
      camera.zoom = startZoom * currentScale.y;
      clampZoom();
    } else {
      camera.translateBy(startScalePosition - info.eventPosition.game);
      camera.snap();
    }
  }
```
> I am ommiting the environment details from the report as they are not required

# What are the risks
Well people who are new to flutter and flame will be very confused why is the example is not working on their own code.

**Comment by spydon** [comment]
You are looking at the example that is for `main`, the example that is for `1.0.0` is under the `1.0.01 tag so it can be found here:
https://github.com/flame-engine/flame/blob/1.0.0/examples/lib/stories/camera_and_viewport/zoom_example.dart

**Comment by Sid911** [comment]
@spydon oh right... i was redirected there from the https://examples.flame-engine.org/#/ page using the code button on the right so I assumed that was the correct one

**Comment by spydon** [comment]
Yeah, we should probably build something similar to the version selector that we have on the docs.
