### ISSUE TITLE
Tests should use only properly initialized game instances

### ISSUE THREAD

**Issue by st-pasha** [flame-engine/flame#1351]
Currently there are multiple tests which create a `FlameGame` instance manually and partially initialize it.

In order to reduce the amount of test breakage when the initialization process of a game changes, we should change those tests to only use a game instance acquired from properly initialized sources (such as flame_test).

**Comment by idlehart** [comment]
Is this something i can do for hacktoberfest?

**Comment by spydon** [comment]
> Is this something i can do for hacktoberfest?

Go for it! I'm not sure how many unconverted tests that there are left, but I guess that is part of the ticket to find out. :)

**Comment by spydon** [comment]
Do we have to create a new function that replaces the widget tests too?
