### ISSUE TITLE
Isometric TiledComponent not working properly.

### ISSUE THREAD

**Issue by Pingear** [flame-engine/flame#1359]
Hello)
Isometric display of the map does not working properly.
Here is the code - 
```
import 'package:flame/game.dart';
import 'package:flame_tiled/flame_tiled.dart';
import 'package:flutter/material.dart';
import 'package:flame/flame.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Flame.device.setLandscape();
  await Flame.device.fullScreen();

  final game = TheGame();

  runApp(MaterialApp(
    home: GameWidget(
      game: game,
    ),
  ));
}

class TheGame extends FlameGame {
  @override
  Future<void>? onLoad() async {
    await super.onLoad();

    final tiledMap = await TiledComponent.load('10x10.tmx', Vector2.all(64));
    print(tiledMap.tileMap.map.orientation);
    add(tiledMap);
  }
}

```
Here is the content of 10x10.tmx and iso-64x64-building.tsx files -
**10x10.tmx** -
```
<?xml version="1.0" encoding="UTF-8"?>
<map version="1.5" tiledversion="1.7.2" orientation="isometric" renderorder="right-down" width="10" height="10" tilewidth="64" tileheight="32" infinite="0" nextlayerid="2" nextobjectid="1">
 <tileset firstgid="1" source="iso-64x64-building.tsx"/>
 <layer id="1" name="Tile Layer 1" width="10" height="10">
  <data encoding="csv">
1,21,21,21,21,21,21,21,21,21,
1,3,3,3,3,3,3,3,3,3,
1,3,3,3,3,3,3,3,3,3,
1,3,3,3,3,3,3,3,3,3,
1,3,3,3,3,3,3,3,3,3,
1,3,3,3,3,3,3,3,3,3,
1,3,3,3,3,3,3,3,3,3,
1,3,3,3,3,3,3,3,3,3,
1,3,3,3,3,3,3,3,3,3,
1,3,3,3,3,3,3,3,3,3
</data>
 </layer>
</map>
```

**iso-64x64-building.tsx** -
```
<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.5" tiledversion="1.7.2" name="iso-64x64-building" tilewidth="64" tileheight="64" tilecount="80" columns="10">
 <image source="iso-64x64-building.png" width="640" height="512"/>
</tileset>
```
This is what spriteSheet looks like **iso-64x64-building.png** - 
![image](https://user-images.githubusercontent.com/16469484/152864013-f14aea60-0ad3-43f4-ae2f-4e16dd786fa5.png)

And here is how the map is rendered - 

![image](https://user-images.githubusercontent.com/16469484/152864229-a56a2e9f-acf1-4875-8bce-61c017e4a4d7.png)

No isometric(

Maybe I'm doing something wrong, but in the comments to the code [https://github.com/flame-engine/tiled.dart/blob/main/lib/src/tiled_map.dar](https://github.com/flame-engine/tiled.dart/blob/main/lib/src/tiled_map.dart#:~:text=///%20*%20orientation%3A%20Map%20orientation,hexagonal%E2%80%9D%20(since%200.11).) support for isometric map display is indicated

**Comment by spydon** [comment]
Unfortunately `flame_tiled` doesn't support isometric tilemaps yet, we have the `IsometricTilemapComponent` that supports isometric, but that isn't created from `tiled`. We are of course open for PRs that implement this feature.
