### ISSUE TITLE
Flare Animation doesnt fully load with Flare Bitmap Animation

### ISSUE THREAD

**Issue by phturb** [flame-engine/flame#136]
I dont have any exemple of the error since it's work related, but here is how it happened. When we import a flare animation file that is purely made of svg files, it shows up alright, therefore when I try to import my own flare animation made with png files, what I get is the box contour of each of the png files and thats it. The animation turn into boxes of the size that the png should render in.

This is the file we are trying to render as a Flare Animation component : [https://www.2dimensions.com/a/amelie.ng06/files/flare/tondeuse/preview](url)

There is no exception showing up in the debbugger.

**Comment by erickzanardo** [comment]
@phturb Fixed on `develop` branch, this should be shipped on the next version, mean while, with you already want to use it, I suggest you pointing your dependency to flame's git developer branch.

Thanks.
