### ISSUE TITLE
Allow to pass a camera to the ForgeGame class

### ISSUE THREAD

**Issue by Dev-Owl** [flame-engine/flame#1363]
# What could be improved
The ForgeGame class right now doesn't allow adding a camera and the user has to use the ForgeCamera.

# Why should this be improved
It might be required that the user wants a custom camera and right now, it would require to reimplement all bases classes to get this.

# Any risks?
Nope

# More information
From my point of view we just need an optional parameter for the constructor that by default uses the existing ForgeCamera.

**Comment by spydon** [comment]
Sounds good, do you want to make a PR for it?

**Comment by Dev-Owl** [comment]
Sure
