### ISSUE TITLE
Stucked Hot Restart/Reload

### ISSUE THREAD

**Issue by Tamerlanchiques** [flame-engine/flame#1372]
When I had stepTime property at zero my project didn't Hot Reload/Restart.
When I tried to trigger manual restart there was the message: "Reload already in progress, ignoring request".
```
 final edgeIdle = await gameRef.loadSpriteAnimation(
      'characters/edgeworth/image-022.gif',
      SpriteAnimationData.sequenced(
        amount: 1,
        stepTime: 0, // issue here I guess
        textureSize: Vector2(256, 192),
      ),
    );
```

After changing stepTime to 1 my project started to reload fine. Looks like zero value of stepTime is not correct value.

**Comment by spydon** [comment]
Why would you want a `stepTime` of 0?
