### ISSUE TITLE
SpriteAnimation's function "onComplete" dont work when the animation has only one frame.

### ISSUE THREAD

**Issue by YugeCse** [flame-engine/flame#1379]
SpriteAnimation(
        [SpriteAnimationFrame(await Sprite.load('enemy3_hit.png'), 0.1)],
        loop: false)
      ..onComplete = () => current = EnemyState.normal; 

This is my code, but I have only one animation frame, the onComplete fuction dont work. Is it a bug ?

**Comment by spydon** [comment]
Are you using that `SpriteAnimation` in a `SpriteAnimationComponent`, or how are you rendering it? 
I'm suspecting that its `update` method is never called, I'd recommend adding it to a `SpriteAnimationComponent` and then add that component to your game (or to another component in a component tree that is attached to the game).

**Comment by YugeCse** [comment]
Hi, thanks for your answers. This is my code:
`
/// 战斗机
class WarEnemy extends BaseEnemy {
  WarEnemy() : super(Vector2(69, 109) / 2.0, blood: 3, speed: 48, score: 2);

  @override
  Future<void>? onLoad() async {
    await super.onLoad();
    final _normalAnimation = SpriteAnimation.spriteList([
      await Sprite.load('enemy2.png'),
      await Sprite.load('enemy2.png'),
    ], stepTime: 0.1);
    final hitAnimation = SpriteAnimation.spriteList([
      await Sprite.load('enemy2_hit.png'),
      await Sprite.load('enemy2_hit.png'),
    ], stepTime: 0.1, loop: false)
      ..onComplete = () => current = EnemyState.normal;
    final _deadAnimation = SpriteAnimation.spriteList(
        await Future.wait(
            [1, 2, 3, 4].map((el) => Sprite.load('enemy2_down$el.png'))),
        stepTime: 0.1,
        loop: false)
      ..onComplete = () => isDestory = true;
    animations = {
      EnemyState.normal: _normalAnimation,
      EnemyState.hit: hitAnimation,
      EnemyState.dead: _deadAnimation,
    };
  }

  @override
  void onMount() {
    super.onMount();
    FlameAudio.play('enemy2_out.mp3');
  }

  @override
  void onPlaneHit() {
    if (current != EnemyState.hit) {
      animation?.done();
    }
    current = EnemyState.hit;
  }

  @override
  void onPlaneDestroy() {
    if (current != EnemyState.dead) {
      FlameAudio.play('enemy2_down.mp3');
      current = EnemyState.dead;
    }
  }
}
`
When I have single-frame , the 'onComplete' function dont work. Sometimes, the state cannot work well. Because I found that after I changed the sprite's current state, the frame dont have any changes.

**Comment by st-pasha** [comment]
@YugeCse Try the branch of PR #1387 and see if it fixes the problem.
