### ISSUE TITLE
Deprecate `shouldRemove`

### ISSUE THREAD

**Issue by st-pasha** [flame-engine/flame#1380]
Currently there are two different ways to remove a component: either by calling the `remove()` method on its parent, or by setting the component's `shouldRemove` flag to true. These two approaches use different execution paths, which is error-prone.

I suggest to refactor this functionality so that:
- both methods of removal worked the same way;
- deprecate the `shouldRemove` flag (this is efficiency improvement: we won't have to check this flag on every game tick, and it reduces memory size of `Component`);
- Use Component's `LifecycleManager` to handle deletion instead of the `ComponentSet` -- this cleanup improves encapsulation of the Component class as ComponentSet will no longer need to handle this aspect of lifecycle.

**Comment by spydon** [comment]
Sounds good to me!
