### ISSUE TITLE
Add support for physical game pads

### ISSUE THREAD

**Issue by erickzanardo** [flame-engine/flame#1381]
# Problem to solve

Flame has a `flame_gamepad` plugin, but it isn't being maintained and isn't working properly. We should remedy that.

# Proposal
Update flame_famepad to add support on physical gamepads for Android, iOS and Web (initially, in the future we can try desktop as well)

**Comment by spydon** [comment]
This is an issue for the https://github.com/flame-engine/gamepads repository (which didn't exist when this issue was created).
