### ISSUE TITLE
Refactor `flame_forge2d` to better handle `PositionComponent`s

### ISSUE THREAD

**Issue by spydon** [flame-engine/flame#1384]
# What could be improved
A lot has happened to `flame` meanwhile `flame_forge2d` hasn't seen much improvements lately.
I suggest a full overhaul of `flame_forge2d` which removes the need for `PositionBodyComponent` and makes it possible to add `PositionComponent`s directly as children to `BodyComponent`s.

To do this we need to at least rewrite the `Forge2DCamera`. The coordinate system should still be the normal coordinate system that `Forge2D` uses (with the flipped Y-axis, where Y is shrinking downwards).

# Why should this be improved
Because the current state is not very user friendly, prone to bugs and inefficient (`PositionBodyComponent._updatePositionComponent` in particular).

# Any risks?
It will completely break the current API, but it is definitely worth it.

**Comment by erickzanardo** [comment]
The `PositionBodyComponent` was removed already, so what is missing here is flipped y, which we have other issues tracking that (like #1484), so lets close this.
