### ISSUE TITLE
Forge2dGame Constructor Has No Camera Parameter

### ISSUE THREAD

**Issue by cedarbob** [flame-engine/flame#1391]
I would like to use a customized Camera extension which overrides the  onPositionUpdate method to monitor camera movement.  However the Forge2DGame constructor does not accept a Camera parameter and passes a Forge2dCamera instance to the FlameGame superclass constructor.  And there is no way to replace the camera after game instantiation that I can see.

**Comment by spydon** [comment]
Duplicate of #1363.
