### ISSUE TITLE
"Suggest edit" feature not working on website

### ISSUE THREAD

**Issue by danPyk** [flame-engine/flame#1392]
Hello, when I try to use "suggest edit" option on website, here for example: https://docs.flame-engine.org/1.0.0/game.html#changing-component-priorities-render-update-order I'm getting error 404.
![2022-02-21_18h33_06](https://user-images.githubusercontent.com/78931719/155003438-5443e8ac-06ba-4a27-86e0-d1c57c1b96c8.png)

**Comment by spydon** [comment]
This feature has been removed from the latest versions of the docs (https://docs.flame-engine.org/main/), right @st-pasha?
To suggest and edit you can navigate to the markdown file on GitHub and press the pen.
![image](https://user-images.githubusercontent.com/744771/155007274-651c5d9a-e60c-499a-8a3f-692bc59a93c0.png)

All markdown files can be found [here](https://github.com/flame-engine/flame/blob/main/doc/).

**Comment by st-pasha** [comment]
Yes, it was removed because (1) it's always possible to go to GitHub and find the doc file there; and (2) this feature cannot work reliably because doc files may move or significantly change between versions, so suggesting an edit to any version other than the `main` may not work as intended.
