### ISSUE TITLE
[flame_forge2d] Moving a component captured by the camera will cause that component to be displaced.

### ISSUE THREAD

**Issue by KurtLa** [flame-engine/flame#1395]
# Current bug behaviour
My `camera.followComponent(_player.positionComponent);` centres a component, but the component is somehow offset due to the velocity.

I have created a short GIF: 
![Without debugMode](https://user-images.githubusercontent.com/9027932/155371378-3eb167fd-0949-4b29-ad00-5716e94cf25a.gif)

And a GIF with `debugMode` enabled. 
![With debugMode](https://user-images.githubusercontent.com/9027932/155371489-a6d934a3-dfe2-4991-a6ab-4d7840dcd0c9.gif)

# Expected behaviour
The character sprite should always stays in the centre of the rectangle while moving.

# Steps to reproduce
I've made a minimal runnable example.
Clone it, "pug get" it and run it on your desired device.
https://bitbucket.org/Jinairu/minimalmovementexample/src/master/

# Flutter doctor output
```
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.5.2 20G95
    darwin-x64, locale en-DE)
    • Flutter version 2.8.1 at
      /Users/k.laabs/Documents/FlutterProjekte/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (10 weeks ago), 2021-12-16
      08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK
    version 31.0.0-rc5)
    • Android SDK at /Users/k.laabs/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0-rc5
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is
      necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch
        /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform
        side's plugin code that responds to your plugin usage on
        the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see
      https://guides.cocoapods.org/using/getting-started.html#ins
      tallation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google
      Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.8+10-b944.6916264)

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome
      98.0.4758.102```

# More environment information

* flame: 1.0.0
* flame_forge2d: ^0.8.3
* Platform affected: android, web

**Comment by spydon** [comment]
Can you try if `camera.followVector(positionBodyComponent.body.position);` works better?

**Comment by KurtLa** [comment]
Yes, that works better. 
Now the y-axis of the body and the y-axis of the camera are opposite and I can't figure out how to solve this.
I also feel that the movement is not as fluid as with `followComponent` (but maybe this is a self-made positioning-movement-vector-calculation problem).

`positionBodyComponent.positionComponent.position` and `positionBodyComponent.body.position` behave differently. 

The offset issue persists:
`camera.followVector2(positionBodyComponent.positionComponent.position);`

This seems to work, but inverts the Body-Y-movement (not the camera y-axis itself)
`camera.followVector2(positionBodyComponent.body.position);`

**Comment by KurtLa** [comment]
Updated, thanks for notice.
