### ISSUE TITLE
In a Forge2DGame, camera world coordinates differ from rendered objects' world coordinates.  

### ISSUE THREAD

**Issue by cedarbob** [flame-engine/flame#1402]
The rendering code in flame_forge2d BodyComponent flips the y sign so that bodies render correctly.  But the Forge2DCamera also flips the y sign in it's projection methods.  The result is that a camera with camera.position of (-10,-10) is above the world x axis, and shows a forge2d body positioned at world coordinate (0, -10) as located below the x axis.  It is confusing to people such as myself trying to spin up on the project by plotting some simple Forge2D bodies.

**Comment by erickzanardo** [comment]
@spydon I think this is the same as #1484
