### ISSUE TITLE
Flame audio and hot restart produce unhandled exceptions

### ISSUE THREAD

**Issue by JaviBonilla** [flame-engine/flame#141]
This instruction in **main** and a **hot restart** in Android Studio produce the following two exceptions repeated over timer.

`Flame.audio.loopLongAudio('song.mp3');`

```
Performing hot restart...
Syncing files to device Nexus 5...
Restarted application in 3,116ms.
D/MediaPlayer(18405): setSubtitleAnchor in MediaPlayer
E/flutter (18405): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The getter '_durationController' was called on null.
E/flutter (18405): Receiver: null
E/flutter (18405): Tried calling: _durationController
E/flutter (18405): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
E/flutter (18405): #1      AudioPlayer._doHandlePlatformCall (package:audioplayers/audioplayers.dart:369:16)
E/flutter (18405): <asynchronous suspension>
E/flutter (18405): #2      AudioPlayer.platformCallHandler (package:audioplayers/audioplayers.dart:352:7)
E/flutter (18405): <asynchronous suspension>
E/flutter (18405): #3      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:397:55)
E/flutter (18405): <asynchronous suspension>
E/flutter (18405): #4      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:365:54)
E/flutter (18405): #5      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binary_messenger.dart:110:33)
E/flutter (18405): <asynchronous suspension>
E/flutter (18405): #6      _invoke3.<anonymous closure> (dart:ui/hooks.dart:280:15)
E/flutter (18405): #7      _rootRun (dart:async/zone.dart:1124:13)
E/flutter (18405): #8      _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (18405): #9      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (18405): #10     _invoke3 (dart:ui/hooks.dart:279:10)
E/flutter (18405): #11     _dispatchPlatformMessage (dart:ui/hooks.dart:141:5)
E/flutter (18405): 
E/flutter (18405): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The getter '_positionController' was called on null.
E/flutter (18405): Receiver: null
E/flutter (18405): Tried calling: _positionController
E/flutter (18405): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
E/flutter (18405): #1      AudioPlayer._doHandlePlatformCall (package:audioplayers/audioplayers.dart:375:16)
E/flutter (18405): <asynchronous suspension>
E/flutter (18405): #2      AudioPlayer.platformCallHandler (package:audioplayers/audioplayers.dart:352:7)
E/flutter (18405): <asynchronous suspension>
E/flutter (18405): #3      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:397:55)
E/flutter (18405): <asynchronous suspension>
E/flutter (18405): #4      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:365:54)
E/flutter (18405): #5      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binary_messenger.dart:110:33)
E/flutter (18405): <asynchronous suspension>
E/flutter (18405): #6      _invoke3.<anonymous closure> (dart:ui/hooks.dart:280:15)
E/flutter (18405): #7      _rootRun (dart:async/zone.dart:1124:13)
E/flutter (18405): #8      _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (18405): #9      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (18405): #10     _invoke3 (dart:ui/hooks.dart:279:10)
E/flutter (18405): #11     _dispatchPlatformMessage (dart:ui/hooks.dart:141:5)
```

- Android Studio 3.5
Build #AI-191.8026.42.35.5791312, built on August 9, 2019
JRE: 1.8.0_202-release-1483-b49-5587405 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.2.8-1-default

- Flutter 1.7.8+hotfix.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 20e59316b8 (5 weeks ago) • 2019-07-18 20:04:33 -0700
Engine • revision fee001c93f
Tools • Dart 2.4.0

- Flame 0.15.1

**Comment by luanpotter** [comment]
possibly a bug in [audioplayers](https://github.com/luanpotter/audioplayers)?

**Comment by JaviBonilla** [comment]
@luanpotter Probably, I followed this approach, https://jap.alekhin.io/background-music-in-a-flame-game, and still have the same issue.

Is anyone having the same problem?

**Comment by erickzanardo** [comment]
@JaviBonilla when you hot reload, some stuff get deallocated from the memory, and this kind of errors starts to happen. I don't know if there anything we can do about this. What we usually do here, is to disable the audio when testing in debug mode.

It has come to my attention recently that there is a `hot reload` hook that you can listen on Flutter.

You could stop the music from playing on that hook, but I haven't tested it yet.

You can check more here: https://stackoverflow.com/questions/55281077/how-to-detect-hot-reload-inside-the-code-of-a-flutter-app

**Comment by JaviBonilla** [comment]
Thanks for the info @erickzanardo.

Yes, for `hot reloads` stopping the music in the `reassemble` method works. But for `hot restarts` I haven’t found a way to make it works.

The `reassemble` method executes before both, `hot reloads` and `hot restarts`, but I think there is no way to know which one is going to be performed. Also, I don’t what to do in the ‘hot restart’ case, maybe ‘removeAll’?

So, I will follow your advice and disable audio in debug mode.

**Comment by erickzanardo** [comment]
What I do, is usually hold the instance of the current music looping (you probably won't be looping more than one instance) and then stop it.

You could take a look on how I manage sounds on this game: https://github.com/fireslime/bounce_box/blob/master/game/lib/sound_manager.dart

maybe you can take some ideas from it.

**Comment by JaviBonilla** [comment]
Thanks a lot @erickzanardo!

**Comment by erickzanardo** [comment]
Closing this, if you have any more trouble with this, let us know, thanks!
