### ISSUE TITLE
Convert Component.positionType into a mixin

### ISSUE THREAD

**Issue by st-pasha** [flame-engine/flame#1419]
Given that `.positionType` is only used by 2 classes, I suggest moving this field out of the main `Component` class into a separate mixin. This would reduce the complexity of the class somewhat, and also its size.

**Comment by spydon** [comment]
It's only used by two of our classes, but removing it increases the complexity for our users, since it is used a lot by them. I also don't think an enum is as expensive as an object, but that should be investigated.

**Comment by st-pasha** [comment]
> but removing it increases the complexity for our users, since it is used a lot by them. 

Can you give me an example of how it is used by the users? I thought it was mostly for the internal event processing logic.

**Comment by spydon** [comment]
> Can you give me an example of how it is used by the users? I thought it was mostly for the internal event processing logic.

People mostly use it to build huds from other components.

**Comment by spydon** [comment]
Not valid anymore with the use of the `CameraComponent`.
