### ISSUE TITLE
Frame rate sometimes drop when audio is played.

### ISSUE THREAD

**Issue by vikk** [flame-engine/flame#142]
I have started to create a little game using flame( [app-release.zip](https://github.com/flame-engine/flame/files/3534268/app-release.zip)). The problem is that frame rate sometimes(seems randomly to me) drop when audio is starting to play. Literally there is 0.1- 0.2 second where the rendering is completely blocked. The sounds are very short (1 second). If I comment out lines where audio is played( Flame.audio.play(...)) everything work just fine.

```
import 'dart:math';
import 'package:shared_preferences/shared_preferences.dart';
import 'dart:async';
import 'package:flame/flame.dart';

Future<SharedPreferences> _getStorage() async => await SharedPreferences.getInstance();
final Future<SharedPreferences> _storage = _getStorage();

Future<void> _getSounds() async => await Flame.audio.loadAll(['point.mp3','flip.mp3','boom.mp3']);

.....
.....

class Drawing {

    ....

  Drawing(this.streamController){
     _getSounds();
  }

 ......
 
  void touch(){
     ....
      Flame.audio.play('flip.mp3');
    .....
 }

}
```

**Comment by luanpotter** [comment]
@vikk to avoid this, you must pre-load the audios. It takes a few millis to do so, and doing it on the fly might be noticeable. Use `Flame.audio.load` or `Flame.audio.loadAll` and wait for the promises while you show a loading screen :)

**Comment by vikk** [comment]
I preload the audios in here(see previous comment):
``Future<void> _getSounds() async => await Flame.audio.loadAll(['point.mp3','flip.mp3','boom.mp3']);``
which I call in a constructor. Does not matter if the audio is playing 10s - 20s after preload. It is still somehow blocking canvas rendering.

**Comment by vikk** [comment]
I am using version: 0.15.1 (the latest one)

**Comment by luanpotter** [comment]
@vikk please try using the AudioPool class for minimum delays when playing audio :)

**Comment by erickzanardo** [comment]
Closing this due inactivity, Luan suggestions should help you with the frame drop, but if you still have trouble, let us know.
