### ISSUE TITLE
Steam support

### ISSUE THREAD

**Issue by t1gu1** [flame-engine/flame#1423]
Since windows is now truly release for flutter, it could be crazy to see the SDK Steamworks integrated to Flame-engine.

## Proposal

An integration to get access to SDK Steamworks.

## More information

- https://partner.steamgames.com/
- https://partner.steamgames.com/doc/gettingstarted

---

**It's more an idea that I share than a request.**
It may be an external package, but it certainly make flame-engine an even better solution for 2D PC games.

**Comment by erickzanardo** [comment]
This is an awesome idea.

I wouldn't add this directly to Flame though, this should probably live inside a bridge package, or even a stand alone package since I bet other frameworks could benefit from such an integration

**Comment by spydon** [comment]
https://github.com/aeb-dev/flame_steamworks
