### ISSUE TITLE
Change priority from int to double

### ISSUE THREAD

**Issue by fwh1990** [flame-engine/flame#1428]
# What could be improved
`Component._priority`

# Why should this be improved
Change to **double** type

# Any risks?
No

# More information
For `team cooperation` product, it's very important to make sure who create the node earlier from different devices at the same time, and change the priority smaller or bigger when conflict happens since the priorities are all unique for us. However I can't simply `+1` or `-1` because other nodes may hit next priority, it's more safe to `+0.01` or `-0.01` or other number.

**Comment by fwh1990** [comment]
The second case is when I'm sorting the nodes from `A -> B -> C -> ...` to `A -> C -> B -> ...`, the priority of C should be `(A + B) / 2`, that means double is necessary.

**Comment by spydon** [comment]
This seems like a very specific need for your product, z-index in general is an int so I don't think we'll change that until we start supporting three dimensional position vectors.

Can't you multiply for example 1000 to your priorites and treat the zeroes as if they'd be decimals?

**Comment by st-pasha** [comment]
I concur with closing this issue for now.

At the same time, as @wolfenrain mentions, we do need to start thinking about the evolution of the current priority system. So maybe start a discussion about that? What are the future requirements? Can we start making at least _some_ steps in that direction?

**Comment by st-pasha** [comment]
The discussion for this issue moved to #1457.
