### ISSUE TITLE
Allow prefix of the Images instance on the Game to be customisable

### ISSUE THREAD

**Issue by erickzanardo** [flame-engine/flame#1429]
# Problem to solve

Flame `Images` class has a default prefix to `assets/images`, which can be changed upon instantiation.

`Game` bundles an `Images` instance, but it is directly instantiated upon declaration, which makes it impossible to customise the prefix of that instance.

So users that want to use a different prefix can't use the bundled `images` instance on the `Game` and have to create and manually manage another instance.

# Proposal
We should provide a way for that prefix to be changed.

I believe that a simple solution would be to add an attribute to game, called `imagesPrefix = 'assets/images`, which users could override.

That is a simple solution, which will be retro compatible, but also open to other ideas 

# More information

**Comment by wolfenrain** [comment]
As discussed in our group chat, I am for having it more customizable but not sure if adding another "floating" attribute is the way to go. I currently do not have an alternative tho.

I'll noodle on this as well and see if I can find a "cleaner" solution that is backwards compatible, but it wont be the end of the world for me if we go with this route ;-).

**Comment by st-pasha** [comment]
What if we simply make `Images.prefix` a settable (non-final) property? Then a user would be able to write at the beginning of the game something like
```dart
void main() {
  final game = MyGame();
  game.images.prefix = 'assets/pictures/';
  runApp(GameWidget(game: game));
}
```

**Comment by erickzanardo** [comment]
Yeah, we raised that on other forum, but @wolfenrain was worried that this could be more prone to user error, any more context you want to bring about it @wolfenrain ?

**Comment by st-pasha** [comment]
My thinking was that it would be a setter, which would do basic checks on the validity of the passed value.

**Comment by st-pasha** [comment]
I guess this can be closed now.
