### ISSUE TITLE
Unit testing in Flame

### ISSUE THREAD

**Issue by SumeetMathews** [flame-engine/flame#143]
how to do unit testing in flame. for component like Rect

**Comment by luanpotter** [comment]
for unit tests you can use Flutter test packages normally. For example, take a look at the unit tests for position class in the flame repo: https://github.com/flame-engine/flame/blob/master/test/position_test.dart

for more advanced tests, like component or integration tests, you are going to need to mock and monkey patch stuff. there is nothing built in yet, but it's not very hard either.

**Comment by erickzanardo** [comment]
Closing due inactivity, if you still have questions, please try contacting us on the Discord server.
