### ISSUE TITLE
Component-centered built-in effects

### ISSUE THREAD

**Issue by AdrienDelgado** [flame-engine/flame#1438]
# Problem to solve

Difficulty to use built-in effects that extend Transform2D in relation to the center of the targeted `Component`s.

When beginning a new project, one might expect components to be related to the position of their center, instead of their top-left corner. While `position` and `size` are easily handled from the top-left corner, effects can be a hassle to adapt to component-centerd logic. 

# Proposal

The proposal would be to include a centered version of built-in movement effects. It could include:
- `MoveEffect` -> `CenteredMoveEffect`, via `CenteredMoveEffect.to` and `CenteredMoveEffect.by` methods
- `RotateEffect` -> `CenteredRotateEffect`, via `CenteredRotateEffect.to` and `CenteredRotateEffect.by` methods
- `ScaleEffect` -> `CenteredScaleEffect`, via `CenteredScaleEffect.to` and `CenteredScaleEffect.by` methods
- `SizeEffect` -> `CenteredSizeEffect`, via `CenteredSizeEffect.to` and `CenteredSizeEffect.by` methods

This implementation would allow users to create easily available component-centered effects.

# More information

The implementation of centered effects would be very similar to currently existing effects. 

Below is an example of implementation for `CenteredScaleEffect`:

```dart
import 'package:vector_math/vector_math_64.dart';

import 'controllers/effect_controller.dart';
import 'transform2d_effect.dart';

/// Scale a component with its center as fix point.
///
/// The following constructors are provided:
///
///   - [CenteredScaleEffect.by] will scale the target by the given factor, relative to
///     its current scale;
///   - [CenteredScaleEffect.to] will scale the target to the specified scale.
///
/// This effect applies incremental changes to the component's scale
/// and position, and requires that any other effect or update logic applied
/// to the same component also used incremental updates.
class CenteredScaleEffect extends Transform2DEffect {
  CenteredScaleEffect.by(Vector2 scaleFactor, EffectController controller)
      : _scaleFactor = scaleFactor.clone(),
        super(controller);

  factory CenteredScaleEffect.to(
          Vector2 targetScale, EffectController controller) =>
      _CenteredScaleToEffect(targetScale, controller);

  final Vector2 _scaleFactor;
  late Vector2 _scaleDelta;
  late Vector2 _positionDelta;

  @override
  void onStart() {
    _scaleDelta = Vector2(
      target.scale.x * (_scaleFactor.x - 1),
      target.scale.y * (_scaleFactor.y - 1),
    );
    _positionDelta = Vector2(
      _scaleDelta.x * target.size.x / 2,
      _scaleDelta.y * target.size.y / 2,
    );
  }

  @override
  void apply(double progress) {
    final dProgress = progress - previousProgress;
    target.scale += _scaleDelta * dProgress;
    target.position -= _positionDelta * dProgress;
    super.apply(progress);
  }
}

/// Implementation class for [ScaleEffect.to]
class _CenteredScaleToEffect extends CenteredScaleEffect {
  final Vector2 _targetScale;

  _CenteredScaleToEffect(Vector2 targetScale, EffectController controller)
      : _targetScale = targetScale.clone(),
        super.by(Vector2.zero(), controller);

  @override
  void onStart() {
    _scaleDelta = _targetScale - target.scale;
    _positionDelta = Vector2(
      _scaleDelta.x * target.size.x / 2,
      _scaleDelta.y * target.size.y / 2,
    );
  }
}
```

**Comment by spydon** [comment]
Just set `anchor = Anchor.center;` and the effects (and other transforms) will take that into account.

**Comment by AdrienDelgado** [comment]
I found the `anchor` argument, but setting it to `Anchor.center` in the target component does not seem effective.

Here is my override:
```dart
@override
Anchor get anchor => Anchor.center;
```

**Comment by spydon** [comment]
@st-pasha doesn't the `ScaleEffect` take the `anchor` into consideration?

@AdrienDelgado I think it should work for the other effects you mentioned at least, have you tried with the rotation effect for example? On that one it should be pretty clear whether it works or not.

**Comment by AdrienDelgado** [comment]
The rotation effect is still bound to the corner with the anchor set to center.

I am adding the effect to the component via a child component. Code is therefore, from the child component: `parent.add(effect);`. However I migrated the effect in the component itself, same result.

**Comment by AdrienDelgado** [comment]
Ok, solved the issue.

Dumb thig, I did override the `get anchor` but forgot to initialize it as `Anchor.center`. Because of that, the getter was set to center, but the setter was set to topLeft.

Thank you for your help.
