### ISSUE TITLE
Audio not respecting silent phone

### ISSUE THREAD

**Issue by ddonze** [flame-engine/flame#145]
When playing audio on an iOS device, Flame does not respect the phone's silent mode and plays the audio regardless. The plugin has a field to handle this, but it is not exposed through Flame.

**Comment by luanpotter** [comment]
It should be, as an optional parameter...

**Comment by erickzanardo** [comment]
I was going to start developing exactly that @luanpotter, but then I realised that it is not necessary.

You can just do `Flame.audio.audioCache.respectSilence = true`

Should this be enough @ddonze ?

**Comment by dd-celerity** [comment]
Yes, that solves the problem! Thanks.

**Comment by ddonze** [comment]
Yup, this solves it! Thanks!
