### ISSUE TITLE
Include `findNestedChildren` and `findNestedChild`

### ISSUE THREAD

**Issue by alestiago** [flame-engine/flame#1456]
# Problem to solve
Currently one needs to define their custom logic to find if a component has a child in its subtrees that matches the given criteria. Particularly useful for tests where you don't want to make subcomponents public.

# Proposal
I think something, as follows, might be helpful:

<details>

<summary> Code example </summary>

```dart
extension ComponentX on Component {
  T findNestedChild<T extends Component>({
    bool Function(T)? condition,
  }) {
    T? nestedChild;
    propagateToChildren<T>((child) {
      final foundChild = (condition ?? (_) => true)(child);
      if (foundChild) {
        nestedChild = child;
      }

      return !foundChild;
    });

    if (nestedChild == null) {
      throw Exception('No child of type $T found.');
    } else {
      return nestedChild!;
    }
  }

  List<T> findNestedChildren<T extends Component>({
    bool Function(T)? condition,
  }) {
    final nestedChildren = <T>[];
    propagateToChildren<T>((child) {
      final foundChild = (condition ?? (_) => true)(child);
      if (foundChild) {
        nestedChildren.add(child);
      }

      return true;
    });

    return nestedChildren;
  }
}
```

The above is an `Extension` ideally, this would be within `Component` and with documentation that warns that this might be a  very expensive method. The above is just an example, function signatures can be modified to adapt to what's more convenient. For example, perhaps a `ComponentSet` is more desired than a `List`?
</details>

# More information

I'm open for better names, suggestions and discussion.
I'm interested in working on a PR for this.

**Comment by st-pasha** [comment]
In Dart, iterables are lazy. That is, `descendants()` by itself will do almost no work -- just create an `Iterable` object and return it. An Iterable is an object that _knows_ how to retrieve its elements one-by-one, but it won't retrieve those elements unless explicitly asked. Then `descendants().firstWhere(condition)` will ask for those elements, one by one, and will stop as soon as it finds the first one that satisfies the condition. So there won't be any unnecessary computations involved. Similarly, `descendants().where(condition).toList()` will iterate over all the components only once, for each one testing whether it satisfies the condition, and if yes placing it into the final list.

**Comment by Dan-Crane** [comment]
Oh! it very good proposal. I wanted to do the same thing this weekend, but you beat me to it) thank you❤️

```dart
Iterable<Component> get descendants sync* {
  if (!hasChildren) return;

  for (var element in children) {
    if (element.hasChildren) {
      yield element;
      yield* element.descendants;
    } else {
      yield element;
    }
  }
}
```

**Comment by st-pasha** [comment]
@Dan-Crane That's a nice and concise implementation! I would also add a boolean parameter `includeSelf = false`, to make it more in line with the `ancestors()` method.

> do we need to use assert(!lifecycle.hasPendingEvents) to alert us that there are pending events?

I don't think so. Some components are very volatile in terms of their children (you may be adding/removing enemies or bullets or special effects on almost every tick), so for them some lifecycle events will always be pending.

**Comment by Dan-Crane** [comment]
> @Dan-Crane That's a nice and concise implementation! I would also add a boolean parameter includeSelf = false, to make it more in line with the ancestors() method.

Do you mean do this?
```dart
Iterable<Component> descendants([bool includeSelf = false]) sync* {
  if (!hasChildren) return;

  for (final component in children) {
    if (component.hasChildren) {
      if (includeSelf) yield component;
      
      yield* component.descendants(includeSelf);
    } else {
      yield component;
    }
  }
}
```
In this case, components that contain children will be skipped.
For example I have a structure like this:
```dart
ComponentA(                 // The place where the method was called.
  children: [
    ComponentB(             // The component i want to get.
      children: [
        ComponentC(),
      ],
    ),
  ],
)

descendants() // Will return ComponentC. ComponentA and ComponentB will be skipped;
```
Won't this confuse users?

**Comment by st-pasha** [comment]
Maybe
```dart
Iterable<Component> descendants({bool includeSelf = false}) sync* {
  if (includeSelf) yield component;
  if (!hasChildren) return;
  for (final component in children) {
    yield component;
    if (component.hasChildren) {
      yield* component.descendants(includeSelf: false);
    }
  }
}
```

**Comment by Dan-Crane** [comment]
Exactly! You are right!) i like it
