### ISSUE TITLE
Memory leak problem

### ISSUE THREAD

**Issue by perfperm** [flame-engine/flame#1462]
Hello!

Using Flame for online window builder

# Current bug behaviour
For some reason, when removing components from the game field - they remain in memory
As a result, a memory leak occurs and the application crashes (when reaching 2gb)

# Steps to reproduce
![image](https://user-images.githubusercontent.com/8552709/158794261-cbe3ad89-ad16-429f-98d2-342b95c65cae.png)
![image](https://user-images.githubusercontent.com/8552709/158795249-e405b56f-41e9-449a-9980-2f95f83b8b9c.png)

Each step, the components are removed from the game field and the modified ones are added again

Tried to remove components with Component.**shouldRemove** flag, Component.**remove** and Component.**removeFromParent** methods

Components removing from game field, but still in memory

# Flutter doctor output

```
[✓] Flutter (Channel stable, 2.10.1, on macOS 12.1 21C52 darwin-x64, locale ru-RU)
    • Flutter version 2.10.1 at /Users/username/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (5 недель назад), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/username/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • iPhone (Иван) (mobile)              • 00008101-000E211E3E92001E            • ios            • iOS 15.1.1 19B81
    • iPhone SE (2nd generation) (mobile) • E7F342C4-8A95-4C1E-AF73-F65E40314490 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

# More environment information
* Flame version: 1.0.0
* Platform affected: android, ios

Thanks!

**Comment by spydon** [comment]
Can you test of this is still the case with 1.0.0-releasecandidate.5?

**Comment by perfperm** [comment]
> Can you test of this is still the case with 1.1.0-releasecandidate.5?

Yep, tried this version too, same problem

Error:
`* thread #9, name = 'io.flutter.1.raster', stop reason = EXC_RESOURCE RESOURCE_TYPE_MEMORY (limit=2098 MB, unused=0x0)
    frame #0: 0x00000001f24d9aa8 libsystem_platform.dylib`_platform_memmove + 88
libsystem_platform.dylib`_platform_memmove:
->  0x1f24d9aa8 <+88>:  stnp   q0, q1, [x3]
    0x1f24d9aac <+92>:  add    x3, x3, #0x20             ; =0x20
    0x1f24d9ab0 <+96>:  ldnp   q0, q1, [x1]
    0x1f24d9ab4 <+100>: add    x1, x1, #0x20             ; =0x20
Target 0: (Runner) stopped.
`

**Comment by st-pasha** [comment]
Can you check whether the #1441 branch resolves the leak? It had some changes regarding image disposal.

**Comment by perfperm** [comment]
> @perfperm can you share minimal code that reproduces this issue?

```
abstract class FramerPositionComponent extends PositionComponent {
  final List<LineSegment> contour;

  FramerPositionComponent({
    required Vector2 position,
    required Vector2 size,
    required this.contour,
    double angle = 0.0,
    int priority = 0,
  }) : super(
          position: position,
          size: size,
          angle: angle,
          priority: priority,
        );
  ...
}
```

```
class Construction extends FramerPositionComponent {
  // Product is a FramerPositionComponent too
  final List<Product> products;

  Construction({
    required this.products,
    required Vector2 size,
    required List<LineSegment> contour,
    bool byProduct = false,
  }) : super(
          position: Vector2.zero(),
          size: size,
          contour: contour,
        );

  @override
  Future<void> onLoad() async {
    super.onLoad();

    for (var product in products) {
      add(product);

      product.init();
      ...
    }

    ...
  }
}
```

```
abstract class Designer extends FlameGame
    with HasTappables, MultiTouchTapDetector, MultiTouchDragDetector {

// GetxController, contains current model state and notify listeners on change
late final ConstructionController constructionController;

Designer() {
    constructionController = Get.find(tag: getTag());
    ...
    constructionController.subscribe(_constructionListener);
    ...
  }

  String getTag();

  void initModel();

  @override
  Future<Function> onLoad() async {
    super.onLoad();
    initModel();

    return () {};
  }

  // Main function, calls when we get updated model from server
  // Removes old PositionComponents from game field and adding modified ones
  void _constructionListener(List<Construction> constructions) {
    if (!_addingSameConstruction(constructions)) {
      _constructions.forEach((construction) {
        // Same behaviour, objects removed from field, but still in memory
        // super.remove(construction);
        // construction.shouldRemove = true;
        construction.removeFromParent();
      });
      _constructions.clear();

      _constructions.addAll(constructions);
      _constructions.forEach((construction) {
        // Prepares and registers a component to be added on the next game tick
        add(construction);
      });
    }
  }

  bool _addingSameConstruction(List<Construction> constructions) {
    return constructions.length == 1 &&
        _constructions.length == 1 &&
        constructions.first == _constructions.first;
  }
}
```

**Comment by perfperm** [comment]
> #1441

Thanks for the reply

I guess that's not exactly what we need
We do not use image objects or assets, components on the game field are calculated directly from the model according to the business logic

**Comment by st-pasha** [comment]
> We do not use image objects or assets

I was looking at the screenshots that you posted, and in the first one `_Image` takes 129Mb out of 130Mb `External`, in the second it's 456Mb out of 457Mb, and in the third it's 1.08Gb out of 1.29Gb. Or perhaps I'm misunderstanding the tool that you're using?

**Comment by perfperm** [comment]
> > We do not use image objects or assets
> 
> I was looking at the screenshots that you posted, and in the first one `_Image` takes 129Mb out of 130Mb `External`, in the second it's 456Mb out of 457Mb, and in the third it's 1.08Gb out of 1.29Gb. Or perhaps I'm misunderstanding the tool that you're using?

I'm using Flutter DevTools in VSC

The screenshots are made of memory snapshots, each snapshot is the state after deleting existing and adding new objects to the playing field
Objects on the playing field - drawn using vectors from the parameters of the original model

It seems to me that after removing the component from the playing field - the images of the object that appeared after the `render` are not correctly removed from memory. As a result, with each step, the section `_Image` grows

**Comment by spydon** [comment]
> - the images of the object that appeared after the render are not correctly removed from memory.

Which images are you talking about here? If you are creating image objects on your own you have to call [dispose](https://api.flutter.dev/flutter/dart-ui/Image/dispose.html) on them for them to get GC:d.

**Comment by perfperm** [comment]
> > * the images of the object that appeared after the render are not correctly removed from memory.
> 
> Which images are you talking about here? If you are creating image objects on your own you have to call [dispose](https://api.flutter.dev/flutter/dart-ui/Image/dispose.html) on them for them to get GC:d.

Sorry, its about `[Pictures]`
![image](https://user-images.githubusercontent.com/8552709/159150177-d551b981-aae2-4272-9fbb-924701cc9646.png)

**Comment by spydon** [comment]
Could you create a minimal reproducible example that is runnable?
Preferably without GetX and other things non-related to Flame.

**Comment by perfperm** [comment]
> Could you create a minimal reproducible example that is runnable? Preferably without GetX and other things non-related to Flame.

Ill try, but it takes some time

Maybe there will be other suggestions to fix this or debug somehow?

**Comment by st-pasha** [comment]
Try to find where your system produces `Image` objects, and what those are. Maybe you're using `Sprite.toImage()`, or `ImageComposition`, or `ParallaxAnimation`, or `PreRenderedLayer`, or any similar class. Check whether you're using canvas's picture recording.

**Comment by t1gu1** [comment]
Hi guys!

I got something that seems related to performance issues.

I'm not really sure if it's really related to this problem and if I should create an other issue, but there is an example that you can use to test:
<https://github.com/t1gu1/flame_engine_render_stress_test>

**Comment by spydon** [comment]
@t1gu1 you are creating new paint objects on every tick here:
https://github.com/t1gu1/flame_engine_render_stress_test/blob/main/lib/Objects/groundChild.dart#L39

Any specific reason that you aren't using `SpriteComponent`?

**Comment by t1gu1** [comment]
@spydon an idea was to be able to change the color of the ground over time.
But yeah, I remove it to test and it's definitively THE things that make the process slower here.

For the SpriteComponent thing.. Don't hurt me.. but no reason here. 😨 

---

I get it, if i want I could pre render painted block one time and clone/reused these painted block and position it.
Thanks ❤️

**Comment by spydon** [comment]
@oerfperm did you manage to figure this out?

**Comment by perfperm** [comment]
@spydon, yep, we found the reason for the increase in memory consumption

It is called by text components on the playing field extended from TextBoxComponent, judging by the code - an image with text is generated there
![telegram-cloud-photo-size-2-5422722384357603406-y](https://user-images.githubusercontent.com/8552709/165221170-e9c34655-d491-4004-ad7a-e81f768e0491.jpg)

**Comment by spydon** [comment]
Good catch! Seems like we need to dispose of that image in `onRemove` and when it is updated then.

**Comment by perfperm** [comment]
Solved this problem by using **TextComponent**

Thanks for help!

**Comment by st-pasha** [comment]
We still need to fix the problem with the TextBoxComponent though, so @spydon can you reopen this?

**Comment by spydon** [comment]
> We still need to fix the problem with the TextBoxComponent though, so @spydon can you reopen this?

Indeed, should be a quick fix, but someone's got to do it.
(And we should check if we use images like this somewhere else)
