### ISSUE TITLE
Load sprite sheet

### ISSUE THREAD

**Issue by damienaicheh** [flame-engine/flame#147]
Hi! I would like to know if you can provide a way to load sprite sheet (A sprite sheet packs a number of smaller images into a single large image.) ? Some tools like TexturePacker help you to create these sprite sheets and it's based on json to load these images.

Thanks for your answer!

**Comment by erickzanardo** [comment]
We provide this already, you can use both the class `Sprite` and `SpriteSheet`.

https://github.com/flame-engine/flame/blob/master/doc/images.md

**Comment by damienaicheh** [comment]
Yes I saw it but it looks like very simple and it's only possible to load animations of a character that is design in a single line. In my case I would like to load a big sprite sheet with a lot of different images that can be objects, menu assets, a lot of images that will be not animated. All these objects are not of the same size. Like in this image for example : https://amakaseev.github.io/sprite-sheet-packer/screens/main.png

**Comment by erickzanardo** [comment]
You can already load this using the `Sprite` class, when creating a new Sprite it receives parameters `x`, `y`, `width` and `height`, with those parameters you can select parts of the image.

The only annoying thing about this is that given that image you provided as example, it would be a very manual process.

The Spritesheet class is meant to be only a help class on top of the Sprite class, and it covers aonly the basic, common uses that we identified.

I imagine that an image like the example you provided, would be needing some kind of metadata, like a json or xml to describe the positions and dimensions of each chunk.

We could create our own format for that, shouldn't be very hard, but if you happen to know, or use one already, and if it is something generic enough, we could try to integrate it on Flame.

**Comment by damienaicheh** [comment]
Yes manual job it's not a good thing. [TexturePaker](http://www.codeandweb.com/texturepacker) provide you a generic json file that discribe how you put your images here is an example it's pretty basic : 

```
{"frames": [
{
	"filename": "image1.png",
	"frame": {"x":579,"y":604,"w":62,"h":62},
	"rotated": false,
	"trimmed": true,
	"spriteSourceSize": {"x":1,"y":1,"w":62,"h":62},
	"sourceSize": {"w":64,"h":64},
	"pivot": {"x":0.5,"y":0.5}
},
{
	"filename": "image2.png",
	"frame": {"x":511,"y":668,"w":62,"h":62},
	"rotated": false,
	"trimmed": true,
	"spriteSourceSize": {"x":1,"y":1,"w":62,"h":62},
	"sourceSize": {"w":64,"h":64},
	"pivot": {"x":0.5,"y":0.5}
}],
"meta": {
	"app": "http://www.codeandweb.com/texturepacker",
	"version": "1.0",
	"image": "sprites.png",
	"format": "RGBA8888",
	"size": {"w":1206,"h":1003},
	"scale": "1",
	"smartupdate": "$TexturePacker:SmartUpdate:b5fb5d5db8ad960a7927226c3156595b:fd6909c3527bc05911568aa5fd053d0d:1eabdf11f75e3a4fe3147baf7b5be24b$"
}
}
```

**Comment by erickzanardo** [comment]
Okay, we could add support to TexturePacker, since we already have spritesheet support on flame, and what you need is support for a third party tool format, I will close this and ask you to open a new issue, asking specifically for TexturePacker support.

On the new issue, please link the documentation for this tool format, and if you could provide an example image and its metadata file, would help us a lot.
