### ISSUE TITLE
Game in Game not working in flame 1.1.0-releasecandidate.5

### ISSUE THREAD

**Issue by nmarafo** [flame-engine/flame#1474]
# Current bug behaviour
If you try to add a FlameGame or a Forge2dGame as a component in onLoad it gives the error:
hasLayout,
      '"size" is not ready yet. Did you try to access it on the Game'
      'builder? Use the "onLoad" method instead.'

# Expected behaviour
Game load normally

# Steps to reproduce
Add a game like component into another game.

# Flutter doctor output
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.3, on Ubuntu 20.04.4 LTS 5.13.0-35-generic, locale es_ES.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.1)
[✓] Android Studio
[✓] VS Code (version 1.65.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

```

# More environment information

# Log information
```
hasLayout,
      '"size" is not ready yet. Did you try to access it on the Game'
      'builder? Use the "onLoad" method instead.'
```

**Comment by spydon** [comment]
Do you know what could be happening here @st-pasha? I thought we tested this when that singleton was introduced, any changes after that that could have affected it? It doesn't work on `main` either.

**Comment by st-pasha** [comment]
I'll post a patch later tonight
