### ISSUE TITLE
Interface stability and compatibility

### ISSUE THREAD

**Issue by Jokergz** [flame-engine/flame#1475]
Hi dude.
Too much change between interface versions of this engine.
The change from 0.9 to 1.0 is understandable.
The 1.0 to 1.1 change is also so big.
The latest 1.0 version introduced by pub.dev.
Refer to the examples to get your head around.

**Comment by spydon** [comment]
Hi there,
from v1 to v2 we will not go with a pure semver versioning style (a bit like the Flutter versioning), so there might be some breaking changes in minor bumps.

> The 1.0 to 1.1 change is also so big.

The only really big breaking change in 1.1 is the collision detection system, which is a change that we planned to get out before v1, but there was not enough time and we wanted to do the co-release with Google, so we simply had to cut it.

With this said we are definitely trying to minimize breaking changes.
