### ISSUE TITLE
Collision callbacks start and end are called in the same tick with many added hitboxes

### ISSUE THREAD

**Issue by Hwan-seok** [flame-engine/flame#1478]
# Current bug behaviour
When two hitboxs has same size and overlaps perfectly,
`onCollisionStart` and `onCollisionEnd` callback called alternately and indefinitely even though there is no position changed. 

# Expected behaviour
I don't know actually but at least current behavior is weired...

# Steps to reproduce
1. Create Two components that has hitbox
2. Set hitbox size as same as each other

# Flutter doctor output
```
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.1 21C52 darwin-arm, locale ko-KR)
    • Flutter version 2.10.3 at /Users/lafity101/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (3 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/lafity101/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • iPhone (mobile) • DEVICE_ID • ios            • iOS 15.1 19B74
    • Chrome (web)          • chrome                    • web-javascript • Google Chrome 99.0.4844.74

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

# More environment information

* Flame version: `main` branch

# Log information

```dart
[ +31 ms] flutter: start collision other: [2448.0,1296.0], size: [32.0,32.0] // me: center: [2448.0,1296.0], size: [32.0,52.0]
[ ] flutter: end collision other: [2448.0,1296.0], size: [32.0,32.0] // me: center: [2448.0,1296.0], size: [32.0,52.0]
[ +33 ms] flutter: start collision other: [2448.0,1296.0], size: [32.0,32.0] // me: center: [2448.0,1296.0], size: [32.0,52.0]
[ ] flutter: end collision other: [2448.0,1296.0], size: [32.0,32.0] // me: center: [2448.0,1296.0], size: [32.0,52.0]
[ +31 ms] flutter: start collision other: [2448.0,1296.0], size: [32.0,32.0] // me: center: [2448.0,1296.0], size: [32.0,52.0]
[ ] flutter: end collision other: [2448.0,1296.0], size: [32.0,32.0] // me: center: [2448.0,1296.0], size: [32.0,52.0]
[ +16 ms] flutter: start collision other: [2448.0,1296.0], size: [32.0,32.0] // me: center: [2448.0,1296.0], size: [32.0,52.0]
[ ] flutter: end collision other: [2448.0,1296.0], size: [32.0,32.0] // me: center: [2448.0,1296.0], size: [32.0,52.0]
... you can see this at the following video
```

https://user-images.githubusercontent.com/38072762/159412816-5b081754-77a1-40f5-aee3-76358794aaab.mov

**Comment by spydon** [comment]
I tried to reproduce this in #1481, but it seems to work like it should there (`onCollisionStart` is only called once`)
Could you have a look on the test I created in the PR to see if it correctly tests the behavior that you are seeing?

**Comment by Hwan-seok** [comment]
@spydon 
Not exactly the same as I tried.
In mine, the blocks are started from different positions which have no collision.

**Comment by spydon** [comment]
> @spydon Not exactly the same as I tried. In mine, the blocks are started from different positions which have no collision.

I tried this in #1481 now and the test still checks out. Can you try to make a minimal reproducible example?
The simplest is probably to make a test where you use the same parameters as in your code.

**Comment by Hwan-seok** [comment]
@spydon 
I updated [reproducible repository](https://github.com/Hwan-seok/flame-collision-v1.1-reproduction.git)
See [Here](https://github.com/Hwan-seok/flame-collision-v1.1-reproduction/blob/a0970a70ac049e55d24ae9a865a9a85d4878cbc2/test/widget_test.dart#L19)
Or you can just run the main code

### FYI
After further digging, this is not the issue with "perfectly" overlapped.
But related to two sides of the block.
Also, It is not reproducible on "every" block. I do not know why but maybe it is related to the broad phase..?

**Comment by spydon** [comment]
Great that you managed to make a reproducible!
I initially thought it would be this line (`if​ (activeBox.max.x ​>=​ currentMin)` in `sweep.dart`) missing an `=`, but it looks to be correct. I'll have a closer look after work.

**Comment by spydon** [comment]
Thanks for the reproducible, I managed to find, and fix, the issue with it.
Could you please try depending on the branch of the PR (#1481) to verify that it fixes it?

**Comment by Hwan-seok** [comment]
Hmm... It is still brokes my test and also reproducible when running code.

**Comment by spydon** [comment]
https://github.com/flame-engine/flame/blob/a559d9a12bfb42e161469745795fb91cdf161f8b/packages/flame/test/collisions/collision_callback_test.dart#L324

I've reproduced the very strange issue here, it only happens if you add many hitboxes, and the outcome differs depending on how many hitboxes you add, even though the extra hitboxes seemingly should have nothing to do with the single ongoing collision.

**Comment by Hwan-seok** [comment]
Very strange indeed....
My application has so many hitboxes so it can be easily affected by this issue.

I really wanna dig into but I have no experience with the game engine.
Please tell me if I can help.

**Comment by Hwan-seok** [comment]
Further digging, I might think it is related to Sweep.query() this time.
I used @spydon's test code.

After I insert the following lines below sorting, I found that the sort result is not consistent.

```dart
for (var idx = 0; idx < items.length; idx++) {
  final e = items[idx];
  print('$idx type:${e.runtimeType}, min: ${e.aabb.min}'); 
}
```
https://github.com/flame-engine/flame/blob/fa2eabad65e06d09128439be4adfe435e12ac168/packages/flame/lib/src/collisions/sweep.dart#L15

As a result, the `a` and `b` of `CollisionProspect` is reversed
https://github.com/flame-engine/flame/blob/fa2eabad65e06d09128439be4adfe435e12ac168/packages/flame/lib/src/collisions/sweep.dart#L32

Finally, The `_lastPotential` and the `potential` is actually same but is does not treated as same because it's order does matter
https://github.com/flame-engine/flame/blob/fa2eabad65e06d09128439be4adfe435e12ac168/packages/flame/lib/src/collisions/collision_detection.dart#L51

**Comment by spydon** [comment]
Well done @Hwan-seok, really appreciate it!
I think that the solution should be trivial then, we have to make order to not matter in the overrides for `hashCode` and `==` in `CollisionProspect`. I can do a PR with the fix after work, if you don't want to do it since you've done all the hard work? 😄
