### ISSUE TITLE
Add support to Texture Packer free tool.

### ISSUE THREAD

**Issue by damienaicheh** [flame-engine/flame#148]
Hi!
To load multiple images inside a single sprite sheet we have a tool that is used a lot in the game world : [TexturePacker](https://www.codeandweb.com/texturepacker). 
Here is the [free version](https://www.codeandweb.com/free-sprite-sheet-packer) of TexturePacker with the basic tool. This is enough for Flame developpement to generate sprite sheet. It could be added to the Flame documentation too.
You will find  in this link an image and the associated json generated.

Can you provide an implementation for it ?

Thanks for your help!

**Comment by Brixto** [comment]
I wrote a simple plugin for this functionality, check it out here: https://pub.dev/packages/flame_texturepacker

**Comment by erickzanardo** [comment]
This is really cool @Brixto can I suggest you adding this to our awesome-flame repository?

**Comment by erickzanardo** [comment]
Closing this, as @Brixto released the plugin, and it is already on flame awesome.
