### ISSUE TITLE
MoveEffect will be unstable when apply multiple effects

### ISSUE THREAD

**Issue by HarrisonQi** [flame-engine/flame#1486]
# Current bug behaviour

When I use MoveEffect into a loop, it will be unstable

# Expected behaviour

The component move to the correct position.

It works several times, but not always correct.

# Steps to reproduce

Here's the code, you can run this, and tap on the block below:
```dart
import 'package:flame/components.dart';
import 'package:flame/effects.dart';
import 'package:flame/game.dart';
import 'package:flame/input.dart';
import 'package:flutter/animation.dart';

import 'package:flutter/material.dart';

void main() {
  runApp(GameWidget(game: TestMove()));
}

class TestMove extends FlameGame with HasTappables {
  RectangleComponent rect1 =
      RectangleComponent.square(size: 20, position: Vector2(50, 50));
  RectangleComponent rect2 =
      RectangleComponent.square(size: 20, position: Vector2(200, 50));

  Rect3 rect3 = Rect3(20, Vector2(50, 100));

  @override
  Future<void> onLoad() async {
    super.onLoad();

    add(rect1);
    add(rect2);
    add(rect3);
  }
}

class Rect3 extends RectangleComponent with Tappable {
  Rect3(double size, Vector2 position)
      : super.square(size: size, position: position);

  @override
  bool onTapDown(TapDownInfo info) {
    doMove();
    return true;
  }

  void doMove() async {
    // 50 -> 200

    for (int i = 1; i <= 10; i++) {
      var movePos = Vector2(50 + i * 15, 100);
      await moveTo(this, movePos);
    }
  }
}

Future<void> moveTo(PositionComponent c, Vector2 position) async {
  await c.add(MoveEffect.to(
      position,
      EffectController(
        duration: 0.5,
        curve: Curves.easeOut,
      )));

  c.position = position;
}

```

# Flutter doctor output

```
Output of: flutter doctor -v
[√] Flutter (Channel stable, 2.5.2, on Microsoft Windows [Version 10.0.18363.2158], locale zh-CN)
    • Flutter version 2.5.2 at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (6 months ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\HarrisonQI\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1.4
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] IntelliJ IDEA Community Edition (version 2021.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 8.1.0 (API 27) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 92.0.4515.131
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 99.0.1150.46

! Doctor found issues in 1 category.

```

# More environment information

```
Flame version: ^1.0.0
Platform affected: android
```

# Log information

```
Enter log information in this code block
```

# More information

This question is asked because using `cc.moveTo()` in `cocos` does not have this problem, it will eventually appear correctly in the corresponding position whether it is in a loop or not.

Maybe I need to change my way to use? Thank you for your reading

**Comment by spydon** [comment]
This line looks very strange to me:
```dart
c.position = position;
```
Why are you setting the position directly of the component that you want to add a `MoveEffect` to? And also why do you have the method as `async` and `await` the add of the the effect?

**Comment by spydon** [comment]
Ah, and also, you are adding several `MoveEffect.to` to the same component, they will all run simultaneously, I guess you want them to run after each other? Your `await` will not wait for the effect to be done running, if that was the intention.

**Comment by HarrisonQi** [comment]
Thank you for your pointing. But in my scenes , the "number of moves" is uncertainty. So it's hard to determine paths.

Is there any way to remove a running effect? My idea is to remove the previous effect before applying a new effect to the component, so maybe it won't conflict?

**Comment by HarrisonQi** [comment]
> Thank you for your pointing. But in my scenes , the "number of moves" is uncertainty. So it's hard to determine paths.
> 
> Is there any way to remove/stop a running effect? My idea is to remove the previous effect before applying a new effect to the component, so maybe it won't conflict?

I am try to use `removeFromParent()`, I'll reply later

**Comment by HarrisonQi** [comment]
After several tests, still not stable.

You can run this new test code :
```dart
import 'package:flame/components.dart';
import 'package:flame/effects.dart';
import 'package:flame/game.dart';
import 'package:flame/input.dart';
import 'package:flutter/animation.dart';

import 'package:flutter/material.dart';

void main() {
  runApp(GameWidget(game: TestMove()));
}

class TestMove extends FlameGame with HasTappables {
  RectangleComponent rect1 =
      RectangleComponent.square(size: 20, position: Vector2(50, 50));
  RectangleComponent rect2 =
      RectangleComponent.square(size: 20, position: Vector2(200, 50));

  Rect3 rect3 = Rect3(20, Vector2(50, 100));

  @override
  Future<void> onLoad() async {
    super.onLoad();

    add(rect1);
    add(rect2);
    add(rect3);
  }
}

class Rect3 extends RectangleComponent with Tappable {
  Rect3(double size, Vector2 position)
      : super.square(size: size, position: position);

  @override
  bool onTapDown(TapDownInfo info) {
    print('onTapDown');
    doMove();
    return true;
  }

  int count = 1;

  void doMove() async {
    moveTo(this, Vector2(50 + count * 15, 100), () {
      if (count < 10) {
        doMove();
        count++;
      }
    });
  }

  @override
  void update(double dt) {
    if (count >= 10) {
      print('current pos:${position}');
    }
  }
}

void moveTo(PositionComponent c, Vector2 position, Function callback) async {
  print('moveTo $position start ->>');

  c.children.whereType<MoveEffect>().forEach((element) {
    element.removeFromParent();
  });

  print('moveTo $position add');

  await c.add(MoveEffect.to(
      position,
      EffectController(
        duration: 0.1,
        curve: Curves.easeOut,
      )));

  print('moveTo $position end <<-');

  await callback.call();
}

```

I think this effect should be stable, because many times we need to interrupt the current action immediately to trigger a new action. The final position should be guaranteed to be correct. 

Thanks for your reading!

**Comment by st-pasha** [comment]
Have you tried removing the current effect, and then adding the new one?

The effect is not "unstable" -- it's just that trying to move a component to two different points simultaneously is a bit of an ill-defined operation.

**Comment by HarrisonQi** [comment]
> ```dart
> c.children.whereType<MoveEffect>().forEach((element) {
>     element.removeFromParent();
>   });
> ```

Yeah , I have try this. This the part of my demo:
```dart
c.children.whereType<MoveEffect>().forEach((element) {
    element.removeFromParent();
  });
```

Is this correct?

**Comment by HarrisonQi** [comment]
> Have you tried removing the current effect, and then adding the new one?
> 
> The effect is not "unstable" -- it's just that trying to move a component to two different points simultaneously is a bit of an ill-defined operation.

Yeah , I have try this. This the part of my demo:
```dart
c.children.whereType<MoveEffect>().forEach((element) {
    element.removeFromParent();
  });
```

Is this correct?

**Comment by st-pasha** [comment]
Adding a component is not an immediate operation, and not even an async operation -- it will at best complete by the start of the next cycle. So, adding a child and then immediately trying to find and remove it will not work because it hasn't actually been mounted yet.

**Comment by HarrisonQi** [comment]
> Adding a component is not an immediate operation, and not even an async operation -- it will at best complete by the start of the next cycle. So, adding a child and then immediately trying to find and remove it will not work because it hasn't actually been mounted yet.

Thanks for pointing. How to remove? I tried looking for a way to remove the effect immediately, but couldn't find it.

**Comment by st-pasha** [comment]
We don't have a way to operate on components that are "in limbo", that is, those that haven't been fully added yet.
I still don't fully understand your use case though: why do you need to add and remove effects repeatedly within the same game cycle? Maybe you can first decide which effect to add, and only then add it?

**Comment by HarrisonQi** [comment]
I'm trying to transplant cocos to flame. The api `cc.moveTo` from cocos is safe when I call many times (final position is correct). 

Is it possible to monitor the end of MoveEffect? I try to use `await add(Effect)` but the end not correct.

**Comment by spydon** [comment]
> Is it possible to monitor the end of MoveEffect(If you used cocos, just like `cc.sequence()`)? I try to use `await add(Effect)` but the end not correct.

If you use `1.1.0-releasecandidate.6` you can use the `onFinishCallback`:

> Optional user-provided onFinishCallback, which will be invoked when the effect has just completed its execution but before it is removed from the game.

https://docs.flame-engine.org/main/flame/effects.html#effect

**Comment by HarrisonQi** [comment]
> onFinishCallback

Thanks, I'll update my flame version to try this

**Comment by HarrisonQi** [comment]
> > Is it possible to monitor the end of MoveEffect(If you used cocos, just like `cc.sequence()`)? I try to use `await add(Effect)` but the end not correct.
> 
> If you use `1.1.0-releasecandidate.6` you can use the `onFinishCallback`:
> 
> > Optional user-provided onFinishCallback, which will be invoked when the effect has just completed its execution but before it is removed from the game.
> 
> https://docs.flame-engine.org/main/flame/effects.html#effect

Thanks, I'll update my flame version to try this

**Comment by HarrisonQi** [comment]
Thanks so much, finally I fix this by upgrade to newest version, use the `onFinishCallback()`. It is very useful for my case.

Here's the demo code. Click the block below, it will move to correct position stable:

```dart
import 'package:flame/components.dart';
import 'package:flame/effects.dart';
import 'package:flame/game.dart';
import 'package:flame/input.dart';

import 'package:flutter/material.dart';

void main() {
  runApp(GameWidget(game: TestMove()));
}

class TestMove extends FlameGame with HasTappables {
  RectangleComponent rect1 =
      RectangleComponent.square(size: 20, position: Vector2(50, 50));
  RectangleComponent rect2 =
      RectangleComponent.square(size: 20, position: Vector2(350, 50));

  Rect3 rect3 = Rect3(20, Vector2(50, 100));

  @override
  Future<void> onLoad() async {
    super.onLoad();

    add(rect1);
    add(rect2);
    add(rect3);
  }
}

class Rect3 extends RectangleComponent with Tappable {
  Rect3(double size, Vector2 position)
      : super.square(size: size, position: position);

  @override
  bool onTapDown(TapDownInfo info) {
    print('onTapDown');
    doMove();
    return true;
  }

  int count = 1;

  Future<void> doMove() async {
    moveTo(this, Vector2(50 + count * 50, 100), () {
      if (count < 7) {
        doMove();
        count++;
      }
    });
  }
}

Future<void> moveTo(
    PositionComponent c, Vector2 position, Function callback) async {
  MoveEffect effect = MoveEffect.to(
      position,
      EffectController(
        duration: 0.01,
      ));

  await c.add(effect
    ..onFinishCallback = () {
      callback.call();
    });
}

```

@spydon @st-pasha  Thank you so much. This question almost made me give up flame. 
You may close this and change the tag instead of "bug"
