### ISSUE TITLE
`descendants` should allow enforcing a search depth limit

### ISSUE THREAD

**Issue by alestiago** [flame-engine/flame#1487]
# Problem to solve
Currently, Flame's API `descendants` method will look at the entire subtree. Sometimes, usually for testing purposes, one might require to limit the search to a specific depth (depth limited search). Or perhaps, some information about the depth is already known and this might serve as optimisation.

# Proposal
One solution could be adding an optional named parameter to the method:
`Iterable<Component> descendants({bool includeSelf = false, int? depthLimit}) sync* {`

# More information
Continuation of #1456

**Comment by alestiago** [comment]
(cc: @st-pasha , @Dan-Crane , @spydon)

**Comment by spydon** [comment]
I don't think this is something that should be handled in the method, since you get an `Iterable` back it is easy for the user to handle it on their side. 
You can use [this method](https://pub.dev/documentation/collection/latest/collection/IterableExtension/whereIndexed.html) for example.

**Comment by spydon** [comment]
Very overkill in the method above, just realized you can do `descendants.take(4)` instead.

**Comment by spydon** [comment]
Ah, right, it is the depth you want to limit, not the amount of results (was confused by the `limit` name).
I still think this is a parameter that is too implementation specific to include on `decendants` (if we don't get plenty of people asking for it of course). Or do you have a common usecase example that you could share?

**Comment by alestiago** [comment]
Definitely, the parameter `limit` requires renaming. Indeed I'm talking about the depth limit. I'm not sure if there's already a fancy way of achieving this with existing API's, perhaps @st-pasha might have some insight.

I think it can suit well within `descendants` since it's basically like saying "return me all my sons and grandsons, but not my grand-grand-sons or further". 

Regarding examples, I haven't got any specific ones that might help here.

Let's see what others think about this issue.

**Comment by st-pasha** [comment]
There isn't a way to filter the current `descendants()` to a specific depth.

On the other hand, we probably shouldn't be implementing features for which there is no conceivable use case, because that's just more effort to document, to test, and to maintain.

**Comment by alestiago** [comment]
Personally, I haven't ended up with a giant tree of components. But there might be a game that does require this performance optimisation.

I agree that for the time being, we can avoid implementing it. If someone is willing to implement, document and test I wouldn’t be against it. Since it's a nice performance optimisation that could be handy at some point.

**Comment by alestiago** [comment]
Sounds good to me @spydon !
