### ISSUE TITLE
sPositionComponent in 1.1.0-releasecandidate.6

### ISSUE THREAD

**Issue by t1gu1** [flame-engine/flame#1497]
# Current bug behaviour
There is an extra **_s_** to add to PositionComponent when we extend a class. So we have to change it with sPositionComponent.

## Expected behaviour
Change sPositionComponent to PositionComponent 

## Steps to reproduce
In the pubspec.yaml change the flame vertion to the releasecandidate.6.

`flame: 1.1.0-releasecandidate.6`

### Create a class like that one:

```dart
class Bird extends PositionComponent with GestureHitboxes, CollisionCallbacks {
// .......
}
```

### It will give an error until its change to:

```dart
class Bird extends sPositionComponent with GestureHitboxes, CollisionCallbacks {
// .......
}
```

---

![image](https://user-images.githubusercontent.com/12479055/160315393-e3bf235a-67e9-4221-8d12-14fe21f1b998.png)

---

![image](https://user-images.githubusercontent.com/12479055/160315785-eb69264f-1fcf-4bf6-8433-7b03c5c57f4d.png)

**Comment by st-pasha** [comment]
There is no `sPositionComponent` anywhere in Flame. Perhaps the source file somehow got corrupted on your system?

**Comment by wolfenrain** [comment]
Checked out the source code of that version and seems the file got edited on your file system as the [PositionComponent](https://github.com/flame-engine/flame/blob/flame-v1.1.0-releasecandidate.6/packages/flame/lib/src/components/position_component.dart) has no `s` in it.

You could clear your pub cache to make sure you are running the clean and latest version of the code.

**Comment by t1gu1** [comment]
Oh god, that's soooo weird..

**Everything works now** when I try the` 1.1.0-releasecandidate.6`..

I was switching between `1.1.0-releasecandidate.5` and `1.1.0-releasecandidate.6` and only the `1.1.0-releasecandidate.6` got the problem yesterday.

So sorry for that waste of time. O.o

**Comment by spydon** [comment]
No problem, you know that `1.1.0` is released now right? :)

**Comment by t1gu1** [comment]
@spydon Yeah I was surprise to see the new doc on the website haha!
**That's pretty nice**! 

No need to read the engine code anymore to test/implement new things hehe :P

It feels more nice and easy to read the new doc of the 1.1.0 than the 1.0.0.
I love how it evolve!

For the name changing it's always a little pain to change, but the wording just make more sense!
I simply go releasecandidate by releasecandidate and check what was breaking and check the **changelogs** and without the doc and I succeed to do it hehe.

With doc its easier now cause you think about it and write it here: <https://docs.flame-engine.org/1.1.0/flame/collision_detection.html#name-changes>

I was thinking about it and I think it could be interesting to have a "**breaking changes section**" in the **doc** that simply list the **breaking changes** from the **previous version only**.

**Comment by spydon** [comment]
> I was thinking about it and I think it could be interesting to have a "**breaking changes section**" in the **doc** that simply list the **breaking changes** from the **previous version only**. 
> Maybe a section for each version like `Migration from the v1.0 to v1.1` .

Our plan was actually to have that for v1.1 but we (I) forgot about it. 😅
Maybe l'll still add it, otherwise it will definitely be there for the next version!

**Comment by st-pasha** [comment]
> Our plan was actually to have that for v1.1 but we (I) forgot about it. 😅

I believe the tracking issue for that was #1225.
