### ISSUE TITLE
Generate diagrams in the docs from code instead of having static images

### ISSUE THREAD

**Issue by spydon** [flame-engine/flame#1504]
# What could be improved
We should generate the diagrams in the docs instead of using static images

# Why should this be improved
It improves the ability to see the changes in version control and it becomes much easier to change for the people that don't sit on the source files for the images.

# Any risks?
The images might look uglier.

# More information

**Comment by alestiago** [comment]
Linking this to #1503

**Comment by ufrshubham** [comment]
Isn't this fixed by #1986? Or are we talking about automating the whole process of generating the mermaid as well?

**Comment by spydon** [comment]
> Isn't this fixed by #1986? Or are we talking about automating the whole process of generating the mermaid as well?

It is for sure, this is a duplicate :)
