### ISSUE TITLE
Camera documentation is lacking/confusing

### ISSUE THREAD

**Issue by kurtome** [flame-engine/flame#151]
Hello, I'm new to Flutter so it's possible I'm mis-understanding how Canvas rendering works (although it looks similar to android).

I'm having trouble figuring how what the "correct" usage of camera positioning is based on the docs and the behavior when I run it. The docs for `BaseGame.camera` are:
> Camera position; every non-HUD component is translated so that the camera is drawn in the center of the screen

Which I assume means if the Camera's position is [10, 10] and my component's position is [10,10], then my component will be center screen.

However, what I'm seeing is that `BaseGame.camera` controls the position of the top-left of the screen and not the center. I think top-left kind of makes sense, because [0,0] is top left of the canvas, but the docs are confusing.

Should the docs be updated to more accurately reflect the behavior?

**Comment by luanpotter** [comment]
Yes, you are correct in your final conclusion. If you'd like to submit a PR improving the wording on the docs/comments, I'd be happy to merge :)

**Comment by erickzanardo** [comment]
Fixed on #152
