### ISSUE TITLE
Tap gesture not propagating properly with the CameraComponent

### ISSUE THREAD

**Issue by Arthil** [flame-engine/flame#1511]
# Current bug behaviour
When using the new experimental CameraComponent the tap gesture event doesn't get propagated properly. Tapping on the screen results in incorrect tappable components being called if the camera position is moved. 

# Expected behaviour
The tap event should propagate to the component tapped even after moving the camera.

# Steps to reproduce
1. Create a FlameGame class with HasTappables
2. Extend the world class and include tappable SpriteComponents.
3. Create and add a CameraComponent to the onLoad method of this class.
4. Translate the CameraComponent to another position
5. Try tapping the tappable SpriteComponents in the world -> They don't get called when tapping on them. But you can find a position on the screen where they do get called.

# More environment information
* Flame version: 1.1.0
* Platform affected:  Android, probably iOS too.

# More information
Example code structure:
```
class CustomGame extends FlameGame with HasTappables, HasDraggables{
@override
  Future<void> onLoad() async {
    await super.onLoad();

    final world = CustomWorld();
    await add(world);
    final camera = CameraComponent(world: world);
    await add(camera);

    camera.viewfinder.position = Vector2(200,200);
    camera.viewfinder.zoom = 0.4;
  }
}

class CustomWorld extends World {
  @override
  Future<void> onLoad() async {
     add(CustomSprite(200,200));
     add(CustomSprite(0,0));
     add(CustomSprite(200,400));
    }
  }

}


class CustomSprite extends SpriteComponent with HasGameRef<CustomGame> , Tappable{
   CustomSprite (double x, double y) {
    this.x = x;
    this.y = y;
  }
  @override
  Future<void> onLoad() async {
    await super.onLoad();
    sprite = await gameRef.loadSprite('any-image-here.png');
    size = Vector2(200,200);
  }
  
  @override
  bool onTapDown(TapDownInfo info) {
    print("Tapped");
    return true;
  }

}
```

**Comment by Arthil** [comment]
Two example images illustrating the issue.
Blue area: Where user clicks
Red area: Tappable Component that gets called

![before_camera_movement](https://user-images.githubusercontent.com/6719409/161447958-67aceca7-f9d2-465d-91e4-97fc7ae190bc.jpeg)
![post_camera_movement](https://user-images.githubusercontent.com/6719409/161447959-a4284d37-d340-406c-bbdc-62dad9c50f17.jpeg)

**Comment by spydon** [comment]
Blocked by #1326

**Comment by spydon** [comment]
@pdeveltere I missed your ping here, is this an issue for you in Flame v1.4.0 too? If so, could you provide a minimal reproduction?

**Comment by spydon** [comment]
> hi @spydon thanks for replying. But no, it was solved by this: https://github.com/flame-engine/flame/issues/1326#issuecomment-1253976147. The new camera component works like a charm!

Super! Thanks for the quick response.
