### ISSUE TITLE
FlameOxygen example fails to get dependencies

### ISSUE THREAD

**Issue by alestiago** [flame-engine/flame#1512]
# Current bug behaviour
Opening the flame oxygen example and running `flutter pub get` fails.

# Expected behaviour
There should be no conflicting dependencies and `flutter pub get` should smoothly run.

# Steps to reproduce
1. Open the Flame Oxygen example (flame_oxygen/example)
2. Run `flutter pub get`

# Flutter doctor output

<details>

<summary> Flutter doctor output </summary>

```
[✓] Flutter (Channel stable, 2.10.1, on macOS 12.2 21D49 darwin-arm, locale en-GB)
    • Flutter version 2.10.1 at /Users/ale/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (8 weeks ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/ale/Library/Android/sdk
    • Platform android-32, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

# Log information

<details>

<summary> Log information </summary>

```
Running "flutter pub get" in example...                        
Because every version of flame_oxygen from path depends on flame from hosted and flame_oxygen_example depends on flame from path, flame_oxygen from path is forbidden.
Running "flutter pub get" in example...                        
So, because flame_oxygen_example depends on flame_oxygen from path, version solving failed.
Running "flutter pub get" in example...                                 
pub get failed (1; So, because flame_oxygen_example depends on
flame_oxygen from path, version solving failed.)
```

</details>

# More information

**Comment by spydon** [comment]
Does this also happen if you run `melos bootstrap`, instead of `pub get`?

https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md#environment-setup

**Comment by alestiago** [comment]
Thanks @spydon.

I personally don't use `melos`. I think it might be a good tool. However, personally, I think it would be nicer to don't directly depend on `melos` for this kind of thing to work. I think this because `melos` increases the barrier of entry for new contributors or developers that are simply interested in the library and want to simply run an example from their desired IDE.

In this scenario, it's easier to adjust the version from path to number and get it working over installing `melos` and trying to learn what `melos` can and is doing.

Feel free to close this issue.

**Comment by st-pasha** [comment]
@spydon What if we integrated the examples into the docs, so that they can be run directly from the browser?

**Comment by spydon** [comment]
> @spydon What if we integrated the examples into the docs, so that they can be run directly from the browser?

I think that is good for smaller examples, but I think the examples site is better for larger examples, which will be coming (small reference games etc).
