### ISSUE TITLE
Can it support dragonbones ？

### ISSUE THREAD

**Issue by 826327700** [flame-engine/flame#1516]
This is really a good engine for flutter , but I often use dragonbones to make game character animation. Do you plan to add support for dragonbones or have better alternatives?

**Comment by 826327700** [comment]
dragonbones docs:[
](https://docs.egret.com/dragonbones/en)

**Comment by spydon** [comment]
From what I can tell you can export your animation to a spritesheet and then use it in Flame. Otherwise I can recommend Rive which we have a bridge library for.
