### ISSUE TITLE
Adding a new Vector2 variable to SpriteComponent

### ISSUE THREAD

**Issue by deraleks1** [flame-engine/flame#1517]
Heyo,

i have been trying to do a sling game. The way I wanted to implement this is to:
- use a joystickComponent as a base
- Save the position of the knob of the JoystickComponent to determine where the projectile starts
- Determine a vector2 on the line where the projectile (SpriteComponent) should travel
I tried to visualize this:
![direction](https://user-images.githubusercontent.com/86529921/162033735-0a7b1f8d-633a-4051-9770-386588872eef.png)
Vector2 direction = (joystick.knob.position - _baseKnobPosition) * -1
Basically direction is a point of the line the projectile travels across

# Problem to solve
The problem is, that I can only pass the "position" variable but not the "direction". I need to pass both variables.
I tried importing half the flame library to allow me to add this variable but got nowhere.

# Proposal
Can I have a new Vector2 for SpriteComponent, to determine the direction to which the projectile travels?

# More information
I am trying to do this, kind of:
![proposed_code](https://user-images.githubusercontent.com/86529921/162034664-783fe8ba-3fc3-43b3-846a-239f9efd63e7.jpeg)

Thanks in advance ^^

**Comment by spydon** [comment]
Since you have extended the class, you can just add it yourself.
Something like this:

```dart
class Bullet extends SpriteComponent ... {
  Vector2 direction;

  Bullet({
    ...
    this.direction,
  }) : super (...);
```

**Comment by deraleks1** [comment]
That did it. Thanks :D
