### ISSUE TITLE
Improve components with a declarative API

### ISSUE THREAD

**Issue by erickzanardo** [flame-engine/flame#1522]
# What could be improved

Flame already favors composability, Components can have children, their children can have their own and so on.

To put Flame more in line with Flutter APIs, we could a `children` attribute on all components in order to allow a more declarative way of developing composable components, for example:

```dart
add(
  PositionComponent(
    children: [
       SpriteComponent(sprite: playerSprite),
       KeyboardController(),
       ....
    ],
  ),
);
```

# Why should this be improved
It will allow better declarative programming and bring Flame even closer to the "Flutter way"

# Any risks?
Idk how complicated this would be to implement, on a naive idea, I think that just by receiving a list o Component on the constructor and adding then all on the component default `onLoad` will me enough, but we need to test and check if this will bring any issues with the Flame lifecycle.

# More information

**Comment by erickzanardo** [comment]
cc @felangel @alestiago

**Comment by spydon** [comment]
Interesting idea! I think it could be pretty nice.

**Comment by alestiago** [comment]
I'm in love with this.

**Comment by st-pasha** [comment]
> If children can be specified, what happens when children are also added via the onLoad? How will the children be ordered?

The ones in the constructor come first, those from onLoad after.
