### ISSUE TITLE
Error when add and remove component while game engine paused

### ISSUE THREAD

**Issue by Hwan-seok** [flame-engine/flame#1532]
# Current bug behaviour

Add the component to the game after pausing engine and remove it before engine resume causes assertion fails.

# Expected behaviour
Prevent failing assertions.

# Steps to reproduce
```
import 'package:flame/components.dart';
import 'package:flame/game.dart';
import 'package:flame_test/flame_test.dart';

class MyGame extends FlameGame {}

final tester = FlameTester(MyGame.new);

void main() {
  tester.test('test', (game) async {
    game.pauseEngine();

    final component = Component();
    await game.add(component);
    game.remove(component);

    game.resumeEngine();
    game.update(0);
  });
}

```
# Flutter doctor output

```
✓] Flutter (Channel stable, 2.10.4, on macOS 12.1 21C52 darwin-arm, locale ko-KR)
    • Flutter version 2.10.4 at /Users/lafity101/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (2 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/lafity101/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.66.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (3 available)
    • SM G986N (mobile)           • ...               • android-arm64  •
      Android 11 (API 30)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

# More environment information
> flame version: 1.1.0

# Log information

```
'package:flame[/src/components/component.dart]()': Failed assertion: line 495 pos 12: '_state == LifecycleState.loaded || _state == LifecycleState.removed': is not true.
package:flame/…/components/component.dart:495

```

**Comment by st-pasha** [comment]
I think there are two problems here:

1. A component that is added and then immediately removed before it was mounted will produce an assertion error. 
2. When a game engine is paused, normal component lifecycle stops working, and the components cannot be added or removed.

The second issue here is a bit more problematic, since fixing it would require us to modify the game loop itself, and instead of stopping it entirely, merely pausing the update/render invocations.

@spydon What is the level of functionality that is expected from the engine when the game loop is paused?

@Hwan-seok What do you expect to continue working while the game loop is paused?

**Comment by spydon** [comment]
> @spydon What is the level of functionality that is expected from the engine when the game loop is paused?

We have never discussed it, I don't think I've ever come across a usecase where it has been needed.
It shouldn't be hard for the user to work around this, so I don't know if it is worth spending time on?

What is your use-case here @Hwan-seok?

**Comment by Hwan-seok** [comment]
@st-pasha @spydon 
In my case, I have one main screen which contains `gameWidget` and several subroutes which can do some actions or look at the records.
The time spent on the subroutes can be both short and long(maximum 12+ hours).

Initially, I didn't pause the engine but lots of users complained about high battery consumption and overheating problem.
So I decided to pause the engine when the main game screen is covered by other subroutes(via didPush, didPopNext). As a result, the complaining rate is very lowered after pausing.

Regardless of the user's route, the user has websocket connection between server because it is multiplayer game.

This is the point.
When the user is doing action on the subroute which is paused engine, and another user came in and goes out(this causes add component and removes component).

**Comment by spydon** [comment]
A workaround could be to maintain a separate list of components meanwhile the engine is paused, which you can both add and remove from, and then when you resume the engine you add that component list to the game.

**Comment by Hwan-seok** [comment]
@st-pasha 
I saw you merged that component is safely removable on an `uninitialized` state.
I am just wondering if you have any plan to apply this to `loaded` or `loading`?
