### ISSUE TITLE
[flame_tiled] add availability to loading TiledMap directly 

### ISSUE THREAD

**Issue by Hwan-seok** [flame-engine/flame#1533]
# What could be improved
Change `_loadMap` to public and create new method `static Future<RenderableTiledMap> fromMap(TiledMap map, Vector2 destTileSize)`
https://github.com/flame-engine/flame/blob/cae8c0ceb395416ed86fd644c1dd7790eae127ca/packages/flame_tiled/lib/src/renderable_tile_map.dart#L106

# Why should this be improved

Currently, there are only `fromFile` and `fromString` methods for making `RenderableTileMap` and cannot make `TiledMap` directly.
The `fromString` uses `_loadMap` to loading `TiledMap` and loads the image directly at the next line.
As a result, there is no chance of retrieving and manipulating the map's image path before the image is actually loaded.
https://github.com/flame-engine/flame/blob/cae8c0ceb395416ed86fd644c1dd7790eae127ca/packages/flame_tiled/lib/src/renderable_tile_map.dart#L108

Imagine that we want to get images from a remote URL. 
But `_loadImages` loads SpriteBatch directly before we know the path of the imageSets of TileMap.
So we cannot inject the image files from a remote URL before flame loads it from local assets.

# Any risks?

Misusing of loadMap..? but this isn't very common.

# More information

Are you interested in working on a PR for this?  **YES**

It is a long way to go to acheving dynamically fetching maps.. I think this one is starting.

**Comment by spydon** [comment]
Sounds like a good addition to me, I'll assign you to the issue.
