### ISSUE TITLE
TextConfig issue on release mode

### ISSUE THREAD

**Issue by erickzanardo** [flame-engine/flame#154]
Originally reported on: Reported on https://github.com/flame-engine/flame/issues/146

> I'm also facing some issues with text rendering's color. I tried different colors like black and pink, but the color seem to appear correctly only in debugging mode. When in release mode, it's always showing white. TextConfig(color: Color(0xff000000), fontSize: 20.0, fontFamily: 'Arial', textAlign: TextAlign.left); I also tried color: BasicPalette.black.color.

**Comment by erickzanardo** [comment]
@luanpotter you have worked a lot with TextPainter classes, any clues on this?

**Comment by erickzanardo** [comment]
@luanpotter have you had any chance to take a look on this?

**Comment by vanduong185** [comment]
I have the same problem. Does anyone have a solution ?

**Comment by erickzanardo** [comment]
@luanpotter any news?

**Comment by johrpan** [comment]
This seems to be a Flutter issue. I opened flutter/flutter#48114 there.

**Comment by erickzanardo** [comment]
Can anyone test to confirm if this stills happens on more recent Flutter version? @renancaraujo @luanpotter

**Comment by luanpotter** [comment]
@erickzanardo I never experienced this issue, so I cannot reproduce. Must ask OP. However it seems the underlying issue on flutter engine is fixed? either way seems not to be a bug on flame.

**Comment by renancaraujo** [comment]
Agree on this being a framework bug, should not be kept open.

**Comment by erickzanardo** [comment]
I would only close this if the bug on Flutter is fixed, even this not been a problem on Flame, if the bug still happens, there is a high probability that another issue regarding that will be open.

**Comment by renancaraujo** [comment]
Tested using material colors and params reported on https://github.com/flutter/flutter/issues/48114. Looks good.
