### ISSUE TITLE
camera.moveTo - future then

### ISSUE THREAD

**Issue by JCzz** [flame-engine/flame#1544]
# Problem to solve
When calling `camera.moveTo(<position>)` I suggest having a callback method or using a Future then.

# Proposal
Future then like [this](https://api.flutter.dev/flutter/dart-async/Future/then.html)

**Comment by spydon** [comment]
This can be done with a `MoveToEffect` added to `camera.viewfinder`, I'm guessing this issue was opened for the old camera system.
