### ISSUE TITLE
Availability to add/remove multiple overlays at once

### ISSUE THREAD

**Issue by Hwan-seok** [flame-engine/flame#1546]
# What could be improved
Currently, the `ActiveOverlaysNotifier` can add/remove only one by one.
It can add/remove multiple overlays at once.

# Why should this be improved
Imagine adding/removing multiple sets of overlays.
It can lead to multiple function calls to flame users in addition to executing multiple `notifyListeners()` inside the Flame.

# Any risks?
No

# More information

https://github.com/flame-engine/flame/blob/ac3d4bf61b1386df555de4673e2bb6da1f0edd50/packages/flame/lib/src/game/mixins/game.dart#L319
Are you interested in working on a PR for this?  **Yes**

**Comment by spydon** [comment]
Sounds good to me!
Maybe we should also consider if we should prohibit modifications to the underlying set externally too, because now you could do `overlays.value.addAll(..)` for example and circumvent sending out notifications.

**Comment by st-pasha** [comment]
> Maybe we should also consider if we should prohibit modifications to the underlying set externally too,

This is already done in #1498.

**Comment by spydon** [comment]
I guess we should wait with this issue until that PR is merged, since it changes that class a lot.
