### ISSUE TITLE
Tapeable mixin not working on grandchildren component

### ISSUE THREAD

**Issue by HumbleCarl** [flame-engine/flame#155]
tap events not working on children components of composed component can anyone help me with this?

**Comment by erickzanardo** [comment]
Indeed this is something that we didn't anticipated, marking this as a bug.

**Comment by luanpotter** [comment]
It's a bug indeed, I think composed component must call preAdd on its children, must find a good way to do this

**Comment by luanpotter** [comment]
should be fixed in dev branch, added a test for it.

**Comment by erickzanardo** [comment]
Fixed on https://github.com/flame-engine/flame/commit/0d9d847ff731fe1c22a98874e0efba9b90d88e3c
