### ISSUE TITLE
FixedResolutionViewport doesn't handle fast resizes

### ISSUE THREAD

**Issue by stx** [flame-engine/flame#1553]
When quickly resizing FixedResolutionViewport in Chrome, black bars are added and the final resize is never rendered.

When resizing slowly, or when using DefaultViewport, it works as expected. It'd be nice if this could work as smoothly as DefaultViewport.

See demo:

https://user-images.githubusercontent.com/1284134/163741866-8551b530-4b96-4e1d-8d46-06423948e5fb.mp4

Is there a better solution to keeping Flame in the assigned Flutter widget tree rendering area than `FixedResolutionViewport(canvasSize)`?

# Steps to reproduce

Use `camera.viewport = FixedResolutionViewport(canvasSize)` in your FlameGame's onLoad.

Component:

```
class GameMap extends SpriteComponent with HasGameRef {
  @override
  Future<void> onLoad() async {
    await super.onLoad();

    sprite = await gameRef.loadSprite('map.png');

    size = sprite!.originalSize;
  }
}
```

**Comment by st-pasha** [comment]
`FixedResolutionViewport` is supposed to add black bars around the canvas, in order to maintain the fixed aspect ratio.

**Comment by stx** [comment]
Please watch the video and notice how the behavior changes based on resize speed. Is this intentional that black bars are added while resizing quickly, and not added while being resized slowly?

Is there a better solution to keeping Flame in the assigned Flutter widget tree rendering area than `FixedResolutionViewport(canvasSize)`?

**Comment by st-pasha** [comment]
> Please watch the video and notice how the behavior changes based on resize speed. Is this intentional that black bars are added while resizing quickly, and not added while being resized slowly?

The behavior of the viewport shouldn't depend on the speed of resizing. On the other hand, the `FixedResolutionViewport` usually maintains a fixed aspect ratio of the canvas, whereas in your video it keeps filling the entire canvas. Which could indicate that you have some additional logic in your `onGameResize` handler that changes the `effectiveSize` of the viewport. It's hard to say what's causing the behavior that you observe without seeing the full code sample.

> Is there a better solution to keeping Flame in the assigned Flutter widget tree rendering area than FixedResolutionViewport(canvasSize)?

Sorry, I don't understand what you are asking here.

**Comment by spydon** [comment]
I tried to reproduce this in this example:

https://examples.flame-engine.org/#/Camera%20%26%20Viewport_Fixed%20Resolution%20viewport

But it works like it should. Are you dynamically changing the size of the fixed viewport somewhere in your code?

**Comment by stx** [comment]
> I tried to reproduce this in this example:
> 
> https://examples.flame-engine.org/#/Camera%20%26%20Viewport_Fixed%20Resolution%20viewport
> 
> But it works like it should. Are you dynamically changing the size of the fixed viewport somewhere in your code?

Yep! `camera.viewport = FixedResolutionViewport(canvasSize)` in repro steps above.

Reproduction here: https://github.com/stx/camera_viewport_resize

**Comment by stx** [comment]
@spydon had a genius `ClipRect` suggestion in Discord — thank you! 🙏

That's a perfect solution without needing to mess with the viewport calculation.

I thought this would just cut off Flame's rendering - I had no idea it would recalculate the canvas from it! I find this to be a sensible and helpful default so you can just drop FlameGame into an app. Something to consider. :)

**Comment by spydon** [comment]
> I had thought this strategy would just cut off Flame's rendering - I had no idea it would recalculate the canvas from it!

That is what it does, what you experienced earlier was Flame painting outside of its boundaries (which is standard for Flutter widgets if you don't tell them not to). In the new experimental camera system (which is already very usable) all viewports have a clip mask so that you can tell them to clip the way that you like.
