### ISSUE TITLE
Bug in sample code: packages / flame_forge2d / example / lib / mouse_joint_sample.dart

### ISSUE THREAD

**Issue by JCzz** [flame-engine/flame#1558]
I think I found a bug, the code should be:

      @override
      bool onDragUpdate(int pointerId, DragUpdateInfo details) {
        final mouseJointDef = MouseJointDef()
          ..maxForce = 3000 * ball.body.mass * 10
          ..dampingRatio = 0.1
          ..frequencyHz = 5
          ..target.setFrom(ball.body.position)
          ..collideConnected = false
          ..bodyA = groundBody
          ..bodyB = ball.body;
    
        if (mouseJoint == null) {
          mouseJoint = MouseJoint(mouseJointDef);
          world.createJoint(mouseJoint!);
        }
        mouseJoint?.setTarget(details.eventPosition.game);
        return false;
      }

And not

      @override
      bool onDragUpdate(int pointerId, DragUpdateInfo details) {
        final mouseJointDef = MouseJointDef()
          ..maxForce = 3000 * ball.body.mass * 10
          ..dampingRatio = 0.1
          ..frequencyHz = 5
          ..target.setFrom(ball.body.position)
          ..collideConnected = false
          ..bodyA = groundBody
          ..bodyB = ball.body;
    
        mouseJoint ??= MouseJoint(mouseJointDef);
        world.createJoint(mouseJoint!);
    
        mouseJoint?.setTarget(details.eventPosition.game);
        return false;
      }

See this for elaboration: https://stackoverflow.com/questions/71928016/mousejoint-gets-less-and-less-reactive/71938577#71938577

**Comment by spydon** [comment]
Makes sense, so you want to open a PR for this fix?

**Comment by JCzz** [comment]
Yes, created: https://github.com/flame-engine/flame/pull/1562
