### ISSUE TITLE
OpacityEffect not being triggered, maybe a problem on HasPaint?

### ISSUE THREAD

**Issue by arcadekenan** [flame-engine/flame#1559]
# Current bug behaviour
Whenever I try to `add(...)` a OpacityEffect to any type of component, it does not seem to be triggered at any point in execution.

# Expected behaviour
Be able to use the OpacityEffect normally.

# Steps to reproduce
Basically just instancing and trying to `add(...)` the OpacityEffect should reproduce it.
Here the TextComponent I'm trying to fade with OpacityEffect as an example
(Note: The ScaleEffect works just fine and as expected)
```
import 'package:flame/components.dart';
import 'package:flame/effects.dart';

import '../utils/text_styles.dart';

class ScoreHint extends TextComponent with HasPaint {
  final int score;
  final double arenaSize;
  final Vector2 arenaCenter;
  final scaleEffect =
      ScaleEffect.by(Vector2.all(2), EffectController(duration: 1));
  final opacityEffect = OpacityEffect.fadeOut(EffectController(duration: 0.5));
  // final opacityEffect = OpacityEffect.to(0, EffectController(duration: 0.5));

  Timer? dismissCountdown;

  ScoreHint(
      {required this.score, required this.arenaCenter, required this.arenaSize})
      : super(
            text: score.toString(),
            position: arenaCenter,
            size: Vector2.all(arenaSize / 4),
            anchor: Anchor.center,
            priority: 0) {
    dismissCountdown = Timer(1, onTick: dismiss, repeat: false);
    textRenderer = TextPaint(style: titleStyle());
    add(scaleEffect);
    add(opacityEffect);
  }

  @override
  void update(double dt) {
    super.update(dt);
    if (dismissCountdown != null) {
      dismissCountdown!.update(dt);
    }
  }

  void dismiss() {
    removeFromParent();
  }
}

```
here is the constant TextStyle I'm using
```
import "package:flutter/material.dart";

TextStyle titleStyle() {
  const Color shadowColor = Color.fromARGB(127, 255, 255, 255);
  return const TextStyle(
      inherit: true,
      color: Color.fromARGB(127, 255, 145, 0),
      shadows: [
        Shadow(
            // bottomLeft
            offset: Offset(-0.5, -0.5),
            color: shadowColor),
        Shadow(
            // bottomRight
            offset: Offset(0.5, -0.5),
            color: shadowColor),
        Shadow(
            // topRight
            offset: Offset(0.5, 0.5),
            color: shadowColor),
        Shadow(
            // topLeft
            offset: Offset(-0.5, 0.5),
            color: shadowColor),
      ]);
}
```
# Flutter doctor output

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.2 21D49 darwin-x64, locale
    pt-BR)
    • Flutter version 2.10.5 at /Users/davibispo/Git/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (2 days ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /Users/davibispo/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

# More environment information
* Flame version: 1.1.1
* Forge2D version: 0.11.0
* Platform affected: web (not tested on iOS and Android)

# Log information
Whenever I try to inspect whats inside the Paint attribute of my component, this is the log I get.
```
paint
CkPaint
    <error>:<getObject: Exception: Could not find library: dart:_engine>
```

# More information

**Comment by spydon** [comment]
The only thing that the `OpacityEffect` does currently is changing the `paint` object that the `HasPaint` mixin is providing, and your `TextStyle` is not using that `Paint` object. It's not enough to only add the `HasPaint` mixin to make it work unfortunately.
The `SpriteComponent` for example already has the `HasPaint` mixin and makes use of `paint` when rendering, so for components like that you can add the `OpacityEffect` directly.
https://examples.flame-engine.org/#/Effects_Opacity%20Effect
https://github.com/flame-engine/flame/blob/main/examples/lib/stories/effects/opacity_effect_example.dart

**Comment by arcadekenan** [comment]
@spydon So it wraps up to be a limitation on the TextComponent or I ended up making my TextStyle incorrectly? 
I do prefer to use the TextComponent specially to avoid adding more complexity with a dedicated font or asset text.

**Comment by spydon** [comment]
`TextComponent` isn't really made for using `OpacityEffect` on it, what you can do is create a new `TextStyle` with the `paint` in the update method of `ScoreHint`. It will be inefficient since it will create a new `TextStyle` object 60 times a second, but if you don't do that a lot in your game it should be fine.

**Comment by arcadekenan** [comment]
@spydon Thanks for the idea! I thing it might make sense in my case, because the `ScoreHint` appears and is removed within a second, I'll try and see if it behaves as I envisioned. 
Maybe a good thing to add to a TODO list, is map the Components that each Effect has no affect on them and add a Note section on the documentation for future reference ^^
