### ISSUE TITLE
Problem with gestures

### ISSUE THREAD

**Issue by Gericop** [flame-engine/flame#156]
No matter what I try, I can't make the `PanGestureRecognizer` work and I don't know whether I'm doing something wrong, or the engine is failing, or Flutter is having some weird fun.

When I touch the screen, `onDown` is called (twice, actually, for whatever reason). Then if I start moving my finger, nothing happens even though I expect the `onStart` / `onUpdate` to be called. After moving my finger some distance from the initial touch location, `onCancel` is called, then `onStart` / `onUpdate` / `onEnd` as it should.

Here's the sample app that produces this behavior:

```dart
import 'package:flame/components/component.dart';
import 'package:flame/components/events/gestures.dart';
import 'package:flame/flame.dart';
import 'package:flame/game.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/services.dart';
import 'package:flutter/widgets.dart';

void main() {
  SystemChrome.setPreferredOrientations(
          [DeviceOrientation.landscapeLeft, DeviceOrientation.landscapeRight])
      .then((_) {
    MainGame game = new MainGame();
    runApp(game.widget);
  });
}

class MainGame extends BaseGame {
  PanGestureRecognizer _createPanGestureRecognizer() => PanGestureRecognizer()
    ..onDown = (evt) {
      debugPrint("[PAN] onDown: $evt");
    }
    ..onStart = (evt) {
      debugPrint("[PAN] onStart: $evt");
    }
    ..onUpdate = (evt) {
      debugPrint("[PAN] onUpdate: $evt");
    }
    ..onEnd = (evt) {
      debugPrint("[PAN] onEnd: $evt");
    }
    ..onCancel = () {
      debugPrint("[PAN] onCancel");
    };

  PanGestureRecognizer _panGestureRecognizer;

  @override
  bool debugMode() => true;

  @override
  void onAttach() {
    super.onAttach();

    if (_panGestureRecognizer != null) {
      Flame.util.removeGestureRecognizer(_panGestureRecognizer);
    }
    _panGestureRecognizer = _createPanGestureRecognizer();
    Flame.util.addGestureRecognizer(_panGestureRecognizer);

    Flame.util.fullScreen();
  }

  @override
  void onDetach() {
    super.onDetach();

    if (_panGestureRecognizer != null) {
      Flame.util.removeGestureRecognizer(_panGestureRecognizer);
    }
  }
}
```

**Comment by erickzanardo** [comment]
I am not very expert on Flutter gestures, but I think Pan has some delay indeed, I suggest you trying this recognizer: https://api.flutter.dev/flutter/gestures/ImmediateMultiDragGestureRecognizer-class.html

I have used it and it seems to work very well, and without delays.

**Comment by luanpotter** [comment]
@renancaraujo knows a lot about advanced flutter gesture recognizers

**Comment by Gericop** [comment]
@erickzanardo The problem with that is that I need to detect the end of drag (i.e. when the users lift their fingers). To better understand the problem, here's the use case:
_There are 2 objects on the screen and the user needs to connect them with a line. This means that the user must tap and hold on object 1, move the finger to object 2, and lift it up._

I assumed `PanGestureRecognizer` would solve the problem as, well, it's a panning move, but any recommendations are welcome.

**Comment by erickzanardo** [comment]
We have added a new API for gesture detection on version `0.17.0`, this should fix this, gonna close this, but if there is still problems, feel free to open a new issue
