### ISSUE TITLE
How to create an empty circle box container/wall/boundary, rather than a solid ball wall?

### ISSUE THREAD

**Issue by denghejun** [flame-engine/flame#1563]
```
class CircleWall extends BodyComponent {
  double radius;
  Vector2 position;

  CircleWall(
    this.position,
    this.radius,
  );

  @override
  Body createBody() {
    final shape = CircleShape();
    shape.radius = this.radius;
    final fixtureDef = FixtureDef(shape, friction: 0.3);
    final bodyDef = BodyDef(
      userData: this, // To be able to determine object in collision
      position: this.position,
    );

    return world.createBody(bodyDef)..createFixture(fixtureDef);
  }
}
```

**Comment by spydon** [comment]
You just have to change the `style` of the `paint` that is being used.
Put this in `createBody` for example:
```dart
      paint.style = PaintingStyle.stroke;
```

**Comment by denghejun** [comment]
> You just have to change the `style` of the `paint` that is being used. Put this in `createBody` for example:
> 
> ```dart
> paint.style = PaintingStyle.stroke;
> ```
<img width="320" alt="Screen Shot 2022-04-22 at 5 09 56 PM" src="https://user-images.githubusercontent.com/8454695/164675280-021ffe86-6c00-4c24-978a-ba56790cdb2c.png">


Thanks, it works, but another question, how can I put a ball in this circle box?

**Comment by spydon** [comment]
You can't, a body is a solid object.
And I don't think you can create a circle in another way, what you could do is using a [chain shape](https://box2d.org/documentation/md__d_1__git_hub_box2d_docs_collision.html#autotoc_md40) with many edges to contain the balls, but it won't be circular.

**Comment by denghejun** [comment]
> You can't, a body is a solid object. And I don't think you can create a circle in another way, what you could do is using a [chain shape](https://box2d.org/documentation/md__d_1__git_hub_box2d_docs_collision.html#autotoc_md40) with many edges to contain the balls, but it won't be circular.
<img width="298" alt="Screen Shot 2022-04-22 at 6 17 24 PM" src="https://user-images.githubusercontent.com/8454695/164688966-21c0f96f-147b-485a-b926-9b16f677a81f.png">

Thanks, I did it as you suggested
