### ISSUE TITLE
MoveAlongPathEffect parametrize _lastAngle

### ISSUE THREAD

**Issue by Rhesos** [flame-engine/flame#1567]
# What could be improved
MoveAlongPathEffect sets the attribute _lastAngle to 0. It would be nice to be able to change it but currently there seems to be no way.

# Why should this be improved
I have a use case of MoveAlongPathEffect making use of quadraticBezierTo Path, and using the flag oriented: true. The effect must be applied on a component that has an already tweaked angle value. Therefore _lastAngle value to 0 does not match and leads to incorrect component orientation during the effect.

# Any risks?
I do not see a risk, as this improvment should be backward compatible.

**Comment by spydon** [comment]
Is your usecase solved by using the new `nativeAngle` on `PositionComponent`, or do you need it to be fully configurable?
