### ISSUE TITLE
Box2D implementation documentation

### ISSUE THREAD

**Issue by HumbleCarl** [flame-engine/flame#158]
Hi guys, does anyone here have idea on implementing Box2d on my proj. cause I need the collision effect for my 2 sprite component. Thanks in advance

**Comment by luanpotter** [comment]
Hi, @HumbleCarl , our docs for box2d are [here](https://flame-engine.org/docs/box2d.md), but currently the only docs are:

* the box2d repository itself
* the game haunt by @feroult that exemplifies the usage of box2d apis.

However ours is a simple wrapper over box2d, so any box2d tutorial you might find for other languages (java, c) should give you enough information to understand the basis.

However IMO we should have a doc for box2d, so I'll leave this open if someone wants to help out.

**Comment by HumbleCarl** [comment]
Thank you for your response! Will take a look at it.

**Comment by wolfenrain** [comment]
In case anyone stumbles upon this issue, I am currently adapting some Box2D C++ tutorials to work with dart: https://wolfenra.in/series/dart-box2d-fundamentals/
