### ISSUE TITLE
feat: Allow games to know if a component has handled a tap/drag event

### ISSUE THREAD

**Issue by wolfenrain** [flame-engine/flame#1586]
# Problem to solve
Currently when you have components that are tappable or dragable you can not detect in the game class if they have handled (returned a false) the event. 

# Proposal
Update the `HasTappables` and `HasDraggables` APIs to return a boolean for each type of event, we already use the `propagateToChildren` in the events so we can return the output value from that.

# More information

**Comment by spydon** [comment]
You can! The event that comes back has a mutable bool that can be set to let components (including the game) further down the chain that it should be regarded as handled.
