### ISSUE TITLE
Improve API of componentsAtPoint()

### ISSUE THREAD

**Issue by st-pasha** [flame-engine/flame#1592]
# What could be improved

It's been 4 days since `componentsAtPoint` was introduced, but I think there's a way to make it better. Well, [we already talked](https://github.com/flame-engine/flame/pull/1518#discussion_r844946743) about the API not being ideal, but couldn't come up with a better solution.

So, here's a proposed solution:
```dart
Iterable<Component> componentsAtPoint(Vector2 point, [NestedLocation? nestedLocation]);
```
Here the `nestedLocation` argument, if given, will be used to store the local coordinates of `point` for the component being returned. In fact, it will also store the entire stack of points for every ancestor of the component being returned. For example, if you want to know not only the local coordinates of the point, but also the corresponding coordinates in the parent coordinate space, or in the world coordinate space, then that information will be available.

# Any risks?

Technically this is a breaking behavior, but since the method was just introduced, and there hasn't been a release yet, the risk to users is very low.

# More information

Are you interested in working on a PR for this? Yes.

**Comment by spydon** [comment]
Isn't it nicer to have this bundled with the return instead of as an argument, or is that not possible? Although nice that it returns an iterable of components instead now.
