### ISSUE TITLE
TMX format support for Isometric World

### ISSUE THREAD

**Issue by marvelaman** [flame-engine/flame#1598]
Will tmx format appear next updates?

I tried to make isometric map but figured out that I need to use List<List<int>>  for IsometricMap which is not suitable for people who design levels with Tiled app. I will do other work if there is upcoming update with tmx support. otherwise I will have to implement this feature
Btw thank your for your great work!

Best regards!

**Comment by marvelaman** [comment]
assetes.readJson does read tmj file. Only need to decompose List<int> from json["data"] to List<List<int>> to add it to IsometricTileMapComponent

**Comment by spydon** [comment]
Can't you use `flame_tiled` for this?
