### ISSUE TITLE
feat : Isometric Props and gameplay behaviour

### ISSUE THREAD

**Issue by Sid911** [flame-engine/flame#1616]
# Problem to solve
As discussed in PR #1468 Currently there no way to show props in an isometric grid. (Props here being things like static fences, maybe buildings mountain parts, even fake shadow etc.) Which can be of different sizes depending upon how many props developers have and variants.

# Proposal
Based on discussion on last PRs the best way to implement this would be to create a different class which handles props rather than fitting it into current `IsometricTileMapComponent` class.

About the problem of Sprite packing and caching there are two proposals at the moment.
- Stick with grid-based Sprite Sheet with multiple gridsizes for fitting all shapes and sizes of props and use the current method to cache. 

  > This method is very cache inefficient, bad for packing sprites because of grid alignments, bad for artistic workflow but is pretty easily implemented.

- Use xml or json format to locate each sprite with its size in a spritesheet just like a texture atlas. I am not a industry standard game developer but I have seen this being used in many cases *(example below)* and it makes sense. Artists can pack a huge spritesheet with different sizes props and even reference them by sprite name depending on how we want to implement this.

> I also believe loading Sprite in this way even normally would be better but its something related rather than directly affecting this issue.

![image](https://user-images.githubusercontent.com/27860105/167953944-46a9ae43-8a8e-4bff-bc5d-73f694fe61a7.png)

> Example of Kenny S. tower defense asset.

![image](https://user-images.githubusercontent.com/27860105/167954108-508d356d-d352-4f2a-a408-d0a604a4f028.png)

# More information

- I believe there are already many software to generate something like this, we can take reference, so it will be easy on artists to generate. Or we can write our own Texture packing software.

- Behavior of "player" (which would probably be an animated sprite) and its interaction with props in an isometric view is something to be discussed, things like player going back or front of any prop and many edge cases.

**Comment by spydon** [comment]
Have you seen our own tool [FireAtlas](https://github.com/flame-engine/fire-atlas)? And there is also [flame_texturepacker](https://pub.dev/packages/flame_texturepacker) (which we maybe should ask if we can bring in to the monorepo).

**Comment by Sid911** [comment]
That awesome then, if we already have these things, it will be a breeze to implement now. I didn't know texture packer already exsisted.

I will have to take a glance at its workings. After that I can start working on a PR if you guys want me to work on it.

**Comment by spydon** [comment]
Sounds great, I'll assign you to the issue!

**Comment by spydon** [comment]
@Sid911 Do you still plan to work at this at some point? :)

**Comment by Sid911** [comment]
@spydon wow, I actually forgot that I got this issue assigned, lot of stuff has happened. It would be nice to work on it this sunday and catch up with flame. 

Thanks for the reminder.
