### ISSUE TITLE
Unwanted Collision end

### ISSUE THREAD

**Issue by rayanebenzina** [flame-engine/flame#1632]
Hello, 
# Current bug behaviour

In collision_detection.dart, function run() :
There are some collisions that the broadphase doesn't report anymore but that are still colliding.
In these case, handleCollisionEnd is called wrongly.
# Expected behaviour
I don't know if the problem can be fixed in the broadphase but i think that an additional test should be done in order to avoid that.
In order to fix this in my project, i just added this test : 
![image](https://user-images.githubusercontent.com/37687491/168639929-0ba132c3-238d-4534-b1db-215a73371d54.png)
I'm just posting this for you to know that this can happen, as it was a month ago and i don't have the situation anymore to let you reproduce this bug and to know exactly what happened in the broadphase for that to happen.

**Comment by spydon** [comment]
Are you certain that this happens in v1.1.1?
I'm pretty sure it was solved with #1519

**Comment by rayanebenzina** [comment]
My bad, the project was created two days before the update, so it was still on v1.1.0, i think the issue should be solved with #1519 
Thank you for your fast answer :)
