### ISSUE TITLE
`ScaleEffect.to` not working properly when shrinking

### ISSUE THREAD

**Issue by spydon** [flame-engine/flame#1636]
# Current bug behaviour
When setting `ScaleEffect.to(Vector2.zero(), ...)` for example, it will first scale down to 0 and then overshoot and make the component larger again, because the `scale` becomes negative.

# Expected behaviour
It should scale down to the given new scale.

# Steps to reproduce
Set the argument of `ScaleEffect.to` to zero (or any vector smaller than the current scale).

# Flutter doctor output

```
[✓] Flutter (Channel stable, 3.0.0, on Arch Linux 5.17.1-arch1-1, locale en_DK.UTF-8)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

# More environment information
```
* Flame version: main
* Platform affected: all
```

**Comment by spydon** [comment]
Aaah, nvm, it was being added multiple times.
Is `ScaleEffect.to` supposed to be able to have several `ScaleEffect`s running at once and end up on the last ending effects `.to` argument @st-pasha? If not, I'll close this.

**Comment by st-pasha** [comment]
It's similar to `MoveToEffect`: it is not possible to move to two different points at the same time. So, if there are two such effects applied to a component, the result would be that it would arrive somewhere that is neither of those destinations.

It may not be the best behavior (for example, having two move-to effects with the same destination will not lead to that destination), so this could be an area of improvement.
