### ISSUE TITLE
Add support for Pointer events

### ISSUE THREAD

**Issue by lastant** [flame-engine/flame#164]
As written here, Flutter supports both Gestures and raw Pointer events: https://flutter.dev/docs/development/ui/advanced/gestures

But for multi-touch applications Gestures have some limitations:
> For example, down-1, down-2, up-1, up-2 produces only one tap on up-1.

Also, there are no Move gestures.

**Comment by erickzanardo** [comment]
Hey @lastant, what do you mean about add support? Flame does not implement any gestures, all we do is to add some helpers functions to help the developer with what we thinks are the most common used gesture recognizar (taps). But you can always wrap the game widget on a `RawGestureDetector` and use all that flutter has to offer, you can see a good example here: https://github.com/flame-engine/flame/issues/157#issuecomment-533884398

**Comment by lastant** [comment]
Yes, what I did eventually was
```dart
Listener(
  child: game.widget,
  behavior: HitTestBehavior.opaque,
  onPointerDown: (PointerDownEvent pointerDownEvent) {
    game.onPointerDown(pointerDownEvent);
  },
  onPointerUp: (PointerUpEvent pointerUpEvent) {
    game.onPointerUp(pointerUpEvent);
  },
  onPointerMove: (PointerMoveEvent pointerMoveEvent) {
    game.onPointerMove(pointerMoveEvent);
  },
)
```

**Comment by erickzanardo** [comment]
We have added a new API for gesture detection on version `0.17.0`, this should fix this, gonna close this, but if there is still problems, feel free to open a new issue
