### ISSUE TITLE
Because flame depends on flame, version solving failed.

### ISSUE THREAD

**Issue by ashikulislamdev** [flame-engine/flame#1642]
When I try to add flame , it was show me "Because flame depends on flame, version solving failed.
pub finished with exit code 65"
To solve this problem I upgrade my flutter 2.10.3 to 3.0.0 and change my channel stable to beta, but it shown same arror.
What can I do now?

**Comment by erickzanardo** [comment]
Flame does not depend on itself. Given your error, I bet you named your project as flame too, so that is probably why you are seeing this conflict. Can you confirm and rename your project if that is the case?

**Comment by ashikulislamdev** [comment]
ohhhhppppsssss.... You made my day! Also thanks for the support and first contribution.

**Comment by erickzanardo** [comment]
Glad to help!
