### ISSUE TITLE
DestroyBody error

### ISSUE THREAD

**Issue by HumbleCarl** [flame-engine/flame#165]
I got this error when I try to destroy the body of the box. Using world.destroyBody(this.brick.body); after they collide. Here's the error log: 

'package:box2d_flame/src/dynamics/world.dart': Failed assertion: line 329 pos 12: 'isLocked() == false': is not true.

Or does anyone uses different way to destroy the body after collision.

Hope you'll notice this :)

**Comment by erickzanardo** [comment]
@japalekhin can you help us on this?

**Comment by japalekhin** [comment]
@HumbleCarl I think you're destroying it too early. Please paste your code. I'm assuming you're trying to destroy a body from a `ContactListener` which at that point, the body is still locked.

The best way would be to have a flag (`isForDeletion` for example) and set it to true in the `ContactListener`. Inside `update` destroy the body (preferably at the tail end of the update).

**Comment by HumbleCarl** [comment]
@japalekhin here's my full code 




import 'package:flame/box2d/box2d_component.dart';
import 'package:flame/flame.dart';
import 'package:flutter/gestures.dart';
import 'package:box2d_flame/box2d.dart';
import 'package:game_structure/classes/layout/SampleBricks/Brick.dart';
import 'characterobject/samplecharacterboject/SampleCharacter.dart';
import 'characterobject/samplecharacterboject/SampleCharacterBody/SampleCharacterBody.dart';
import 'layout/SampleLayout/SampleLayout.dart';
import 'package:game_structure/classes/common/TempStateController.dart' as tempState;

class GameWorld extends Box2DComponent implements ContactListener{
  SampleCharacterBody sampleCharacterBody;
  Brick brick;
  
  GameWorld() : super(scale: 4.0){
    brick = new Brick(this);
    this.world.setContactListener(this);
    initializeWorld();
  }

  @override
  void initializeWorld() {
    // TODO: implement initializeWorld add all your objects in here.
    addAll(SampleLayout(this).bodies);
    add(Brick(this));
    if(sampleCharacterBody == null){
      add(sampleCharacterBody = new SampleCharacterBody(this));
    }  
  }

  @override
  void update(t) {
    super.update(t);
    // Uncomment this if you will need your main character/object to be followed
    // cameraFollow(component_to_be_followed, horizontal: 0.4, vertical: 0.4);
  }

  Drag handleDrag(Offset position) {
    return sampleCharacterBody.handleDrag(position);
  }

  @override
  void beginContact(Contact contact) {
    // TODO: implement beginContact
    Map a = contact.fixtureA.userData;
    Map b = contact.fixtureB.userData;
    if(b['name'] == 'ball1' && a['name'] == 'bottomwall'){
      tempState.ballRestitution = 0;
      this.sampleCharacterBody.body.linearVelocity = Vector2(0,0);
      this.sampleCharacterBody.body.angularVelocity = 0.0;
    }
    else if(b['name'] == 'ball1' && a['name'] == 'box'){
      world.destroyBody(this.brick.body);  
    }
    // Flame.audio.play('sample.mp3',volume: 1.0);
    // Flame.audio.disableLog();
  }

  @override
  void endContact(Contact contact) {
    // TODO: implement endContact
  }

  @override
  void postSolve(Contact contact, ContactImpulse impulse) {
    // TODO: implement postSolve
  }

  @override
  void preSolve(Contact contact, Manifold oldManifold) {
    // TODO: implement preSolve
  }

  
}

**Comment by japalekhin** [comment]
```dart
void beginContact(Contact contact) {
  ...
    world.destroyBody(this.brick.body);
}
```

yup, add a flag somewhere (`bool isForDestruction = false;` or `bool isForDeletion = false;` for example).

in the `world.destroyBody(...` line, replace it with `isForDestruction = true;`. then in update put the following:
```dart
@override
void update(t) {
  super.update(t);
  if (isForDestruction) { // or isForDeletion depending on what is the name of your flag
    world.destroyBody(this.brick.body);
  }
}
```

**Comment by HumbleCarl** [comment]
@japalekhin hi sir I encountered new error here's the log:

'package:box2d_flame/src/dynamics/island.dart': Failed assertion: line 541 pos 12: '_bodyCount  _bodyCapacity': is not true.

**Comment by japalekhin** [comment]
Hmm check the stack trace and paste the code around the line that gives the error that is in your project (not in `package:box2d_flame` or `package:flame`)

**Comment by HumbleCarl** [comment]
When the exception was thrown, this was the stack:
 #2      Island.addBody (package:box2d_flame/src/dynamics/island.dart:541:12)
#3      World.solve (package:box2d_flame/src/dynamics/world.dart:1001:16)
#4      World.stepDt (package:box2d_flame/src/dynamics/world.dart:597:7)
 #5      Box2DComponent.update (package:flame/box2d/box2d_component.dart:40:11)
#6      GameWorld.update (package:game_structure/classes/world.dart:40:11)
#7      Game.update (package:game_structure/game.dart:34:15)
#8      GameRenderBox._update (package:flame/game.dart:360:10)
#9      GameRenderBox._tick (package:flame/game.dart:353:5)
#10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1033:15)
 #11     SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:951:11)
#12     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#13     SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:949:17)
 #14     SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:883:5)
#18     _invoke1 (dart:ui/hooks.dart:263:10)
 #19     _beginFrame (dart:ui/hooks.dart:190:3)
 (elided 5 frames from class _AssertionError and package dart:async)

**Comment by HumbleCarl** [comment]
Here it is po

**Comment by japalekhin** [comment]
hmmm, you see this inside `initializeWorld`?
```dart
add(Brick(this));
```

i think when you destroy the body, you need to remove this brick too.

**Comment by HumbleCarl** [comment]
Like this po?

```
world.destroyBody(this.brick.body); 
this.remove(this.brick); 
```

**Comment by japalekhin** [comment]
something like that yes, please try it out.

**Comment by HumbleCarl** [comment]
The error was still there.

**Comment by japalekhin** [comment]
Please describe when the error happens. Does it happen on collision or on initialization?

**Comment by HumbleCarl** [comment]
It happens on collision.

**Comment by japalekhin** [comment]
please paste your `beginContact` and `update` again

**Comment by HumbleCarl** [comment]
Here's my beginContact method
```
 void beginContact(Contact contact) {
    // TODO: implement beginContact
    Map a = contact.fixtureA.userData;
    Map b = contact.fixtureB.userData;
    if(b['name'] == 'ball1' && a['name'] == 'bottomwall'){
      tempState.ballRestitution = 0;
      this.sampleCharacterBody.body.linearVelocity = Vector2(0,0);
      this.sampleCharacterBody.body.angularVelocity = 0.0;
    }
    else if(b['name'] == 'ball1' && a['name'] == 'box'){
      isBrickToBeDestroyed = true;
    }
    // Flame.audio.play('sample.mp3',volume: 1.0);
    // Flame.audio.disableLog();
  }
```
and for update
```
void update(t) {
    super.update(t);
    // Uncomment this if you will need your main character/object to be followed
    // cameraFollow(component_to_be_followed, horizontal: 0.4, vertical: 0.4);
    if(isBrickToBeDestroyed){
      print('hit');
      this.remove(this.brick); 
      world.destroyBody(this.brick.body); 
      // isBrickToBeDestroyed = false;
    }
  }
```

**Comment by japalekhin** [comment]
can you identify which specific line in those 2 functions throws the error? you can use `print` in between lines to see which `print` message is shown just before the error.

also since you're accessing `this.brick.body`, it's a good idea to remove `this.brick` after the `destroyBody` call. just for safety measures. highly unlikely, but maybe GC will clean up the removed/freed `this.brick` before the `destroyBody` call.

**Comment by HumbleCarl** [comment]
it is being called more than once since it was update method and there's no error on remove and destroyBody method it just don't take effect, however I tried to set the flag to false to avoid the being execute more than once. But still the object was still there.

**Comment by japalekhin** [comment]
also @HumbleCarl, this doesn't seem like a Flame issue, more like a support request so if possible let's take this into the [FireSlime Discord server](https://discord.gg/pxrBmy4) so i can close this here.

**Comment by japalekhin** [comment]
@erickzanardo let's close this one out, thanks.

**Comment by aytunch** [comment]
> Like this po?
> 
> ```
> world.destroyBody(this.brick.body); 
> this.remove(this.brick); 
> ```
This should work if anyone is having this issue still:
```
world.destroyBody(body);
gameRef.remove(this);
```
