### ISSUE TITLE
Overlays sometimes can't be removed

### ISSUE THREAD

**Issue by spydon** [flame-engine/flame#1658]
# Current bug behaviour
There seems to have been a regression in #1498 so that overlays can't always be removed properly.

# Expected behaviour
Overlays shouldn't be rendered when they are not in the overlays list.

# Steps to reproduce
- Go to https://examples.flame-engine.org/#/System_Overlay
- Click a few times to see the square appear and disappear
- Open the side menu and click again
Result: the square is not disappearing

# More environment information

* Flame version: main

**Comment by spydon** [comment]
@st-pasha do you think that you can tackle this one?

**Comment by st-pasha** [comment]
sure
