### ISSUE TITLE
Split SpriteWidget according to whether it loads an image or not

### ISSUE THREAD

**Issue by Hwan-seok** [flame-engine/flame#1667]
# What could be improved
Remove loading when SpriteWidget does not need to load the image.

# Why should this be improved
SpriteWidget is unified by `BaseFutureBuilder` whether the `Image(Sprite)` has already loaded or not.
This forces every `SpriteWidget` to show a loading widget even though it has already loaded `Sprite`.
This leads to preventing gapless playback when `Image(Sprite)` changes.

# Any risks?
No

# More information

Are you interested in working on a PR for this? Yes

### Before
https://user-images.githubusercontent.com/38072762/170801424-0f09c9af-5234-46f0-974e-01305059bc0e.mov

### After

https://user-images.githubusercontent.com/38072762/170801441-dd65fb79-35b8-44eb-b17f-87b5b3cbc776.mov

**Comment by spydon** [comment]
Nice, will you put up a PR for this?
