### ISSUE TITLE
Write step 4 of the Klondike tutorial

### ISSUE THREAD

**Issue by st-pasha** [flame-engine/flame#1678]
# What could be improved

This would be the next step in the tutorial on how to make the Klondike game. This would focus on moving the cards around the field.

# More information
Blocked by #1677
Blocked by #1661

**Comment by FMorschel** [comment]
As mentioned in #1213, there could be issues created to track the tutorials. Maybe a main issue tracking the overall development for the tutorials and then keep adding the steps in a TODO? 

Also, could the issues be exposed in the actual docs so people can subscribe on GitHub to be alerted of progression?

**Comment by spydon** [comment]
> As mentioned in #1213, there could be issues created to track the tutorials. Maybe a main issue tracking the overall development for the tutorials and then keep adding the steps in a TODO? 
> 
> Also, could the issues be exposed in the actual docs so people can subscribe on GitHub to be alerted of progression?

Sounds good, feel free to create the issue and the PR to the docs if you want to. :)

**Comment by FMorschel** [comment]
I'm not sure how you guys mean to progress in the tutorials so I'll leave the tutorial-specific issues to you (pointing out the remaining steps TBD). I can create an issue to track if the issues for this were created and added to the docs if you think that's necessary, but I think only adding that to the actual issue could be enough. 

I'll suggest something else though, if you agree with me to create one issue for tracking the Klondike and another for the Space Shooter, there could be a tag for tutorials in the issues. So if there is any issue/PR related to them, this could be a place for people to look out for.

I'm not sure where are the docs, but I can look for them later (although, IMO, the person who does the tutorials should be able to do that themselves if they end up creating the issues)

**Comment by spydon** [comment]
> I'm not sure how you guys mean to progress in the tutorials so I'll leave the tutorial-specific issues to you (pointing out the remaining steps TBD). I can create an issue to track if the issues for this were created and added to the docs if you think that's necessary, but I think only adding that to the actual issue could be enough.

The remaining steps I think only @erickzanardo (Space shooter) and @st-pasha (Klondike) knows, so maybe they could write up the issue.

> I'll suggest something else though, if you agree with me to create one issue for tracking the Klondike and another for the Space Shooter, there could be a tag for tutorials in the issues. So if there is any issue/PR related to them, this could be a place for people to look out for.

Sounds good!

> I'm not sure where are the docs, but I can look for them later (although, IMO, the person who does the tutorials should be able to do that themselves if they end up creating the issues)

This is where the docs live:
https://github.com/flame-engine/flame/tree/main/doc
