### ISSUE TITLE
Ability to check the whether ImageAsset is present

### ISSUE THREAD

**Issue by Hwan-seok** [flame-engine/flame#1679]
# What could be improved
Add the `hasCache` method to the Images class.
maybe changing return type of `fromCache` to nullable could be one of solution but this makes a breaking change so the former one is more appropriate.

# Why should this be improved

Currently, class `Images` has no way to some key is present(cached). 
The only way is  try-catching `fromCache` method with a null check operator exception.

# Any risks?
No

# More information

Are you interested in working on a PR for this? Yes

**Comment by spydon** [comment]
Doesn't `Images.containsKey` do what you want here?

**Comment by Hwan-seok** [comment]
Oh my, you did this by #1624!
I am using a very old version of flame🤣 so I missed it.
I wish I could use this near future.

**Comment by spydon** [comment]
> Oh my, you did this by #1624!
> I am using a very old version of flame🤣 so I missed it.
> I wish I could use this near future.

Once #1637 is merged we will release a new version. :)
