### ISSUE TITLE
Better example within the library?

### ISSUE THREAD

**Issue by dvlj** [flame-engine/flame#168]
It would be great to have better example with more use of components and mixins~

**Comment by luanpotter** [comment]
@dvlj there is an example folder inside the docs with lots of examples showcasing flame features. for more complete examples, our open source games work as good, complete examples as well. Is there any component/mixin in particular that you think we could improve or add an example to?

**Comment by dvlj** [comment]
ok thanks, i will look into those examples u mentioned. Somehow, project with version 0.15.2 is not compatible with 0.16.1 when i upgraded, especially the ComposedComponent, any idea?

**Comment by luanpotter** [comment]
it's not, since we are pre 1.0.0 we have breaking changes on minor and minor changes on patch. composed component was remodelled to have better interop with Resizable and Tapables. you will need to update your code, there is a test file for that if you want to take a look

**Comment by dvlj** [comment]
Thanks for the reply~ i will try this later, close issue!
