### ISSUE TITLE
[flame_audio] Upgrade audioplayers to version 1.0.0 (audio support for Linux and Windows)

### ISSUE THREAD

**Issue by TaylorHo** [flame-engine/flame#1687]
# Problem to solve
Implement audio on Linux and Windows with [flame_audio](https://pub.dev/packages/flame_audio) (in addition to Mac, IOS, and Android, already supported).

# Proposal
The [flame_audio](https://pub.dev/packages/flame_audio) package use [audioplayers](https://pub.dev/packages/audioplayers/) package to reproduce the sounds, and now the audioplayers package (in his [version 1.0.0](https://pub.dev/packages/audioplayers/versions/1.0.0-rc.4)) added support for Linux and Windows (that isn't yet supported by flame_audio).
To also add audio in games for these platforms, the upgrade is necessary, an would be awesome if it were done!

# More information
- [Link for audioplayers v1.0.0](https://pub.dev/packages/audioplayers/versions/1.0.0-rc.4) (that supports Linux and Windows)

**Comment by spydon** [comment]
v1.0.0 is not released yet, what you are linking to is a release candidate (`audioplayers` is our package, so we have full control over its release :slightly_smiling_face:). In the coming days we'll hopefully release Flame v1.2.0 and all its packages, and `audioplayers` v1.0.0 depends on the new version of `flame_lint` that will be released then, so v1 of `audioplayers` can be released after that has happened, and then we can release a new version of `flame_audio`.

If it drags out too long we'll release an RC of `flame_lint` and then upgrade `audioplayers` etc, so it should soon be out no matter what happens.

**Comment by TaylorHo** [comment]
Ohh, okay. Thanks for the explanation!!

**Comment by spydon** [comment]
I'll reopen this since we haven't released flame_audio with audioplayers v1 support yet. Hopefully it'll be done this weekend though! :)

**Comment by TaylorHo** [comment]
Hi, the v1 was released, and all is working nicely!! Thank y'all for the update!!
btw, can the issue be closed now?

**Comment by spydon** [comment]
It can, I'll close it. :)
