### ISSUE TITLE
Nested artboards in Rive files doesn't work if you use RiveComponent

### ISSUE THREAD

**Issue by nmarafo** [flame-engine/flame#1692]
# Current bug behaviour
Nested artboards in Rive files doesn't appear if you use RiveComponent, because this use RiveFile like is comented in [this issue](https://github.com/rive-app/rive-flutter/issues/193). You would use RiveAnimation.asset() or wait to Rive team solve the bug.

# Expected behaviour
Nested artboards render and animate.

# Steps to reproduce
Add a RiveComponent with Nested Artboards

# Flutter doctor output

```
[✓] Flutter (Channel stable, 3.0.1, on Ubuntu 20.04.4 LTS 5.13.0-44-generic, locale es_ES.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc1)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.1)
[✓] Android Studio (version 2021.2)
[✓] Android Studio
[✓] VS Code (version 1.66.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

```

# More environment information

log information in this code block
```

**Comment by nmarafo** [comment]
Since RiveComponent inherits from PositionComponent and uses a RiveFile, and since the loading of a RiveAnimation in the Flame Engine can be far from being a StatefulWidget, a good solution for loading the different artboards from a .riv file is to group them in a single PositionComponent, loading them as a StateMachine. Example:
```
class RiveExampleGame extends FlameGame {

  @override
  Future<void>? onLoad() async {
    await super.onLoad();
    add(MyRiveAnimation());
  }
}

class MyRiveAnimation extends PositionComponent {

  @override
  Future<void>? onLoad() async {
    await super.onLoad();
    final skillsArtboard_background= await loadArtboard(RiveFile.asset('assets/rive_file.riv'),artboardName: 'background');
    final skillsArtboard_cloud= await loadArtboard(RiveFile.asset('assets/rive_filer.riv'),artboardName: 'cloud');

    add(SkillsAnimationComponent(skillsArtboard_background));
    add(SkillsAnimationComponent(skillsArtboard_cloud));
  }
}


class SkillsAnimationComponent extends RiveComponent {
  SkillsAnimationComponent(Artboard artboard)
      : super(
    artboard: artboard,
    size: Vector2.all(550),
  );

  @override
  Future<void>? onLoad() {
    final controller = StateMachineController.fromArtboard(artboard, 'state_machine');
    artboard.addController(controller!);

    return super.onLoad();
  }
}
```

**Comment by nmarafo** [comment]
The solution is thancs to @zplata in https://github.com/rive-app/rive-flutter/issues/193#issuecomment-1158134343

**Comment by S-Khavin** [comment]
The Nested artboard is loading, but its inputs are null.

**Comment by nmarafo** [comment]
Hi, could you add some .riv to test?
