### ISSUE TITLE
Keyboard events are not reported when using GameWidget.controlled

### ISSUE THREAD

**Issue by Hwan-seok** [flame-engine/flame#1744]
# Current bug behaviour
As constructor GameWidget.controlled has no game, `widget.game` is null in the `_handleKeyEvent`.
As a result, no key events are reported.
https://github.com/flame-engine/flame/blob/e97893f94b10d5c2290d36ba9c67d62da23599ac/packages/flame/lib/src/game/game_widget/game_widget.dart#L286-L292

# Expected behaviour
Report key events.

# More environment information
* Flame version: main

# More information

 Are you interested in working on a PR for this? YES

**Comment by spydon** [comment]
I think this might already be fixed in #1725, right @renancaraujo?

**Comment by Hwan-seok** [comment]
I can carefully say that It seems a little different scope, doesn't it?

**Comment by spydon** [comment]
> I can carefully say that It seems a little different scope, doesn't it?

Ah right, I confused things! :)
