### ISSUE TITLE
Change FpsComponent as optional parameter to FpsTextComponent

### ISSUE THREAD

**Issue by Hwan-seok** [flame-engine/flame#1748]
# What could be improved

Add optional parameter FpsComponent to FpsTextComponent.
It could reuse the FpsComponent used by outside of the TextComponent.

# Why should this be improved

Currently, the FpsTextComponent is creating FpsComponent inside of the constructor. 
https://github.com/flame-engine/flame/blob/c175617714e2f15f4379ed8ea412c7cb8bfa1842/packages/flame/lib/src/components/fps_text_component.dart#L17
In some games, FpsComponent is used not only for printing on the screen but also for other functions.
So it should create multiple FpsComponent if the game is using FpsTextComponent and the FpsComponent in the other place.
 

# Any risks?

No

# More information

Are you interested in working on a PR for this? Yes

**Comment by spydon** [comment]
Sounds like a quite specific usecase, but also don't see the harm in adding it as an optional argument.
Should I assign you to the issue?

**Comment by Hwan-seok** [comment]
> Sounds like a quite specific usecase  

I agree that it's a specific use case.

It's a little different topic but let me introduce my use case.

My use case is interpolating the position of the component which is followed by a camera.
The camera's following behavior is not interpolating because its following component position is assumed as interpolated.
But the dt reported by the update method can be inconsistent if the game is very complicated and large(ex, has a large map).

As dt based on flutter ticker, it could be "jump" value(ex, 0.016 => 0.033).
Inconsistency of dt and jumping a little is OK (like from 0.016 to 0.017~0.018) but jumping twice its value can cause the camera to be literally "shaking".

So I decided to use `1 / FpsComponent.fps` instead of dt as it is can report interpolated values and it works perfectly.

This could be a great workaround if someone suffers from the camera shaking.

> Should I assign you to the issue?

Yes, I would like to do this.

**Comment by spydon** [comment]
> So I decided to use 1 / FpsComponent.fps instead of dt as it is can report interpolated values and it works perfectly.

This sounds very strange, sounds like we have a bug with how the `dt` values are reported then.
But `FpsComponent.fps` is also using `dt` to calculate the `fps`, so I really don't get how it can help to use `fps`. :sweat_smile:

**Comment by Hwan-seok** [comment]
As you can see here, its fps is from an average of 60 frames(by default but I am using 180 as a windowSize)
https://github.com/flame-engine/flame/blob/b69e8d85c77346081d1fc5a2ee5cbf9c204a9edf/packages/flame/lib/src/components/fps_component.dart#L34-L36

**Comment by spydon** [comment]
Ah, right, that makes sense. I still think it is a bit strange to use the `FpcComponent` the get a smooth movement here, but if it works, it works. :)
I'll assign you to the issue.

**Comment by Hwan-seok** [comment]
Right, It is weird 🤣 but I don't have any other great idea to get the smooth movement right now...
If I fix the dt as ds=0.016, the low-end devices which have low fps get a lower speed compared with others.

**Comment by Hwan-seok** [comment]
On second thought, this is not enhancement but weakening.

The FpsTextComponent is usually used for debug mode so it does not strongly need to be reused.
And if the optional parameter is exposed to the user API, they could be confused about it at glance.

I was a little stupid.
Closing the issue and reopen it if you don't agree.
