### ISSUE TITLE
Merge game.images and Flame.images

### ISSUE THREAD

**Issue by st-pasha** [flame-engine/flame#1750]
# What could be improved

Multiple objects in Flame take an optional `Images? images` argument, which defaults to `Flame.images` if not provided. At the same time, many `Game.load...` methods default to the `Game.images` cache for storing images. The net result is that a user can quite easily end up in a situation where some image would get loaded twice: once into the game cache, and once into the global `Flame.cache`.

I suggest to simply make `Game.images` refer to the same cache as `Flame.images` by default, and to let the user supply their own cache if necessary.

# Any risks?

Not much, unless the user's code somehow relies on these two caches being distinct. In this case they would have to explicitly request a separate `Images` cache instance for their `Game`.

**Comment by spydon** [comment]
Sounds good to me
