### ISSUE TITLE
 Unhandled Exception: Object has been disposed

### ISSUE THREAD

**Issue by GenPingYuan** [flame-engine/flame#1758]
![image](https://user-images.githubusercontent.com/20609414/176224507-7a938638-aa5a-4f69-97cf-cbe510d86088.png)

![image](https://user-images.githubusercontent.com/20609414/176224415-487a29fd-1466-4e07-96cb-a5ae37def2a5.png)

![image](https://user-images.githubusercontent.com/20609414/176224557-2321f693-bc03-42c3-b12a-e7157cf75a9f.png)

**Comment by GenPingYuan** [comment]
my pubspec.yaml config
![image](https://user-images.githubusercontent.com/20609414/176225188-05679c18-85d6-454d-92bf-e26e3cfad1ec.png)

**Comment by erickzanardo** [comment]
Hey, please be sure to always add a description on your issue, only the source code may not be enough to realise what is happening.

But on a quick look, I noticed that you are doing the sprite load on the same method that you are rendering it. Be sure to load it before hand, like on the game `onLoad` method for example and then on the render method, you just render it.

**Comment by GenPingYuan** [comment]
I solved it by changing it to this

![image](https://user-images.githubusercontent.com/20609414/176235390-d6bb1362-1923-4e63-8415-7f376baee266.png)

![image](https://user-images.githubusercontent.com/20609414/176235450-bb5b59d3-9627-40a0-b2dd-ba26958a0e43.png)

~Thank u
