### ISSUE TITLE
Allow overlays to be added/removed via the Navigator

### ISSUE THREAD

**Issue by st-pasha** [flame-engine/flame#1762]
# Proposal

As discussed in https://github.com/flame-engine/flame/pull/1755#discussion_r906873141, we should have an ability to treat overlays as `Route`s of the `Navigator`.

**Comment by rivella50** [comment]
As i understand overlays in Flame context these are Flutter widgets.
What about overlays which extend Component? Currently such classes can only be added to another component or used as pages when used with the just added routing mechanism, but not as overlays supported by routing.
Is such a support also possible?

**Comment by spydon** [comment]
@rivella50 that is possible with #1755, to use that functionality you can either depend on `main` or wait a few days until we release v1.3.0.

**Comment by rivella50** [comment]
@spydon Ah ok, good to know. Thanks for clarifying.
