### ISSUE TITLE
Separate docs site from docs content

### ISSUE THREAD

**Issue by spydon** [flame-engine/flame#1768]
# What could be improved
Currently the docs site is built from a Flame version tag.
This means that if we improve the docs site or change its theme, or when we have a bug in it, it will remain like how it was when that tag was published forever when you look at that tag.

My suggestion is that the `_sphinx` directory is moved to the [flame-docs-site](https://github.com/flame-engine/flame-docs-site) repo and that the script for publishing is updated accordingly.

# Why should this be improved
To have consistency on the site and the possibility to fix bugs.

# Any risks?
Older versions could break with new functionality introduced for the site.

# More information

**Comment by st-pasha** [comment]
Hmm, it's still possible to build the older branches using the latest doc theme: 
1. First, check out the latest flame repo
2. Copy its `_sphinx` folder into a temporary folder
3. Check out the branch that is needed
4. Replace its `_sphinx` folder with the one copied in step 2

Surely, this is few extra steps, but those are pretty trivial for a script.

**Comment by spydon** [comment]
https://github.com/flame-engine/flame-docs-site/pull/5/
