### ISSUE TITLE
[FlameAudio] [iOS] [Real Device] Error occurs when sound is played continuously.

### ISSUE THREAD

**Issue by hukusuke1007** [flame-engine/flame#1784]
# Current bug behaviour
I am making a game in which you tap a series of buttons to make a sound.
At first the sound sounds fine, but after a few taps the sound stops. At that time an error occurs.

No errors occur in the simulator. However, errors do occur on the real device.

Is there any way to solve this problem?

```dart
FlameAudio.play(filename, volume: volume);
```

The filename is obtained from Assets in the application.
volume is 1.5

# Expected behaviour
No error occurs and correct sound.

# Steps to reproduce
1. Press the button more than 10 times. (Sound in sync with it.)
→ Error occurs.

# Flutter doctor output

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.4 21F79 darwin-arm, locale
    ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.68.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

# More environment information
```
flame: ^1.2.0
flame_svg: ^1.3.0
flame_audio: ^1.2.0
flame_forge2d: ^0.12.0
```
Platform affected: ios
Platform version affected: 15.5

# Log information

```
[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: AVPlayerItem.Status.failed
#0      MethodChannelAudioplayersPlatform._doHandlePlatformCall (package:audioplayers_platform_interface/method_channel_audioplayers_platform.dart:174:9)
#1      MethodChannelAudioplayersPlatform.platformCallHandler (package:audioplayers_platform_interface/method_channel_audioplayers_platform.dart:147:7)
#2      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:404:55)
#3      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:397:34)
#4      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:380:35)
#5      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:377:46)
#6      _invoke2.<anonymous closure> (dart:ui/hooks.dart:190:15)
#7      _rootRun (dart:async/zone.dart:1426:13)
```

# More information
Audio file is "mp3".

**Comment by hukusuke1007** [comment]
https://github.com/bluefireteam/audioplayers/issues/1204

**Comment by hukusuke1007** [comment]
Use soundpool instead of this plugin. This plugin worked fine.
https://pub.dev/packages/soundpool

**Comment by wl1395182472** [comment]
Can soundpool cause frame rate loss?

**Comment by spydon** [comment]
@hukusuke1007 you should use `AudioPool` from `flame_audio` instead of the `AudioPlayer` class directly when playing the same audio multiple times within a short time span.
