### ISSUE TITLE
Make images in README point to absolute path instead of relative path

### ISSUE THREAD

**Issue by immadisairaj** [flame-engine/flame#1795]
# What could be improved

The images in README under "Sponsors" are having relative path (`/media/<image>`) which can be made into absolute path (`https://<path-to-image>`)

# Why should this be improved

This has to be improved because, when this README is hosted somewhere, the images won't be visible.
For example, [docs from pub](https://pub.dev/documentation/flame/latest/)

<img width="333" alt="Screenshot 2022-07-11 at 20 51 27" src="https://user-images.githubusercontent.com/40348358/178299064-fd2e0042-81e5-4872-a19a-8acb2e5ec9c4.png">

# Any risks?
No risks involved

# More information
If there are any more places these images are used in the code, have to make them absolute.

I would love to work on this issue.

**Comment by spydon** [comment]
I'll assign you to the issue!
