### ISSUE TITLE
Improve navigation to #-links in documentation

### ISSUE THREAD

**Issue by st-pasha** [flame-engine/flame#1798]
# Problem to solve

Currently, when you follow a link to a sub-header within the page (such as https://docs.flame-engine.org/main/flame/components.html#component), the page will scroll so that the sub-header is at the top of the page. However, we also have a menu bar at the top of the page. This menu bar will obscure the header, with the end result that after following the link the header corresponding to that link will not be visible, which is very confusing.

# Proposal

Add a small script that runs after the page loads, and if it sees any `#`-target in the URL, then simply scroll the page up for 50 or so pixels.

**Comment by spydon** [comment]
Sounds good to me. We'll have a lot of little scripts duct taping together everything on the docs, but I guess it's fine.
