### ISSUE TITLE
Game simulation becomes slow after lock screen.

### ISSUE THREAD

**Issue by HumbleCarl** [flame-engine/flame#180]
My app becomes slow after my phone screen locked and also when I switch to another app. How can I fix this? Thank you in advance

**Comment by erickzanardo** [comment]
Can you provide more info? How do you know that the game has slowed down if the screen is locked or if you have other app opened?

**Comment by HumbleCarl** [comment]
The movement of the body slow down.

**Comment by HumbleCarl** [comment]
https://drive.google.com/open?id=1-H0eiI401zeC_6zUIUhoEqMbCpsM_-Av here's the link of the screen record of the game

**Comment by HumbleCarl** [comment]
Anyone who encounter the same problem as mine?

**Comment by ddonze** [comment]
I have seen a similar issue in iOS, but it is very inconsistent and I have not been able to reliably reproduce it.

**Comment by HumbleCarl** [comment]
It seems it's related with the box2d. Have you figured it out?

**Comment by ddonze** [comment]
I’m not using Box2D. I wrote my own very simple physics code. But I have noticed that my physics methods generally run at 10-20microseconds but will occasionally jump to several hundred microseconds. I’m inclined to believe it’s an issue with Flutter or the Dart runtime, and not a Flame issue. But I still can’t reliably reproduce anything so it’s all speculation.

**Comment by HumbleCarl** [comment]
I see. I put logic on the `lifecycleStateChanged` to apple force once that state was `AppLifecycleState.resumed`; on the bodies that are moving, but the speed does not change at all.

**Comment by luanpotter** [comment]
do you pause the game when it backgrounds? normally I pause the game and I have to add custom logic to update to avoid having a gigantic time step

**Comment by HumbleCarl** [comment]
How do I pause the game? @luanpotter
