### ISSUE TITLE
`renderChain` should allow open-ended chain drawing

### ISSUE THREAD

**Issue by aeb-dev** [flame-engine/flame#1803]
# Current bug behaviour
https://github.com/flame-engine/flame/blob/main/packages/flame_forge2d/lib/body_component.dart#L127

`renderChain` does not allow open-ended chain drawing. As you can see from [the docs of box2d](https://box2d.org/documentation/md__d_1__git_hub_box2d_docs_collision.html), chains can be open-ended.

Also `renderChain` uses `PaintingStyle.fill` but it should not.

# Expected behaviour
`renderChain` should allow open-ended chain drawing with `PaintingStyle.stroke`

Side notes:
- Inside `render{Shape}` functions, `canvas.drawPoints` can be used instead of `Path` to decrease allocations, when applicable.
- I can create a PR if you like

# More information
* Flutter: 3.0.5
* Flame version: 1.2.1
* Flame Forge2D version: 0.12.1

**Comment by spydon** [comment]
Good catch, a PR would be appreciated.
