### ISSUE TITLE
When images rendered, The render is buried under the Component.

### ISSUE THREAD

**Issue by riruhyun** [flame-engine/flame#1808]
# Current bug behaviour
| ![Screenshot_1658286992](https://user-images.githubusercontent.com/74291106/179889268-d1888202-ebde-404b-aaed-aac289e48e27.png) | ![Screenshot_1658286317](https://user-images.githubusercontent.com/74291106/179889542-7e113486-7cdd-4b1b-8b37-0b3ce035a2b2.png) | ![Screenshot_1658287015](https://user-images.githubusercontent.com/74291106/179889649-0665fea9-76f2-4a3a-96c1-4dbbf0d49a80.png) |
|----|----|----|
| Rendered screen I want | Rendered screen ***(current)*** | Without only background component from the current |

I think If I add 'Get Ready' with `add`, it does not disappear later.
So, to show 'Get Ready!' **only** when the player has not started the game, I used the `render function` instead of the `add function(in onLoad)`.

But after 'Get Ready!' is rendered, the background component seems to be added on top, so 'Get Ready' is not displayed on the screen.
I tried setting the component's `priority` lower than 0, but no difference.
Is there a way to change this order so that 'Get Ready!' is placed on top of the component **with render function**?

***Or is there a better way?***

# Expected behaviour
I expected the text 'Get Ready!' to be rendered on the background component.

# Steps to reproduce
```dart
import 'package:flame/components.dart';
import 'package:flame/game.dart';
import 'package:flutter/material.dart';

Size size = MediaQueryData.fromWindow(WidgetsBinding.instance.window).size;

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(GameWidget(game: MyGame()));
}

class MyGame extends FlameGame {
  late Sprite getReady;

  @override
  Future<void> onLoad() async {
    var spriteSheet = await images.load("sprites.png");
    getReady = Sprite(
      spriteSheet,
      srcPosition: Vector2(295, 59),
      srcSize: Vector2(92, 25),
    );

    add(SpriteComponent.fromImage(
      await images.load("bg.png"),
      size: Vector2(size.width, size.height),
    ));

    return super.onLoad();
  }

  @override
  void render(Canvas canvas) {
    getReady.render(
      canvas,
      position: Vector2(size.width * 0.2, size.height * 0.2),
      size: Vector2(size.width * 0.6, size.width * 0.6 / 92 * 25),
    );

    super.render(canvas);
  }
}
```

# Flutter doctor output
```
[√] Flutter (Channel stable, 3.0.4, on Microsoft Windows [Version 10.0.19043.1826], locale ko-KR)
    • Flutter version 3.0.4 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (3 weeks ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.69.2)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.44.0

[√] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64 • Microsoft Windows [Version 10.0.19043.1826]

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

# More environment information
* Flame version: `^1.2.1 (latest)`
* Platform affected: `android, not tested others`
* Platform version affected: `android 10 (API 29)`

**Comment by spydon** [comment]
Just use `add` like you did at first and then call `removeFromParent()` on the component once you don't want it to show anymore. Or call `remove(component)` from the components parent.

It is not recommended to call `render` manually.

**Comment by riruhyun** [comment]
> Just use `add` like you did at first and then call `removeFromParent()` on the component once you don't want it to show anymore. Or call `remove(component)` from the components parent.
> 
> It is not recommended to call `render` manually.

As you answered, I changed `getReady` from `Sprite` to `SpriteComponent` and checked that it was deleted using `add` and `removeFromParent()`.
However, I want to use `remove()` because I want to show it when the player starts the game again.

So, I used `remove(getReady)` in `update`.
Then, another error occurred.
```
Exception has occurred.
_AssertionError ('package:flame/src/components/component.dart': Failed assertion: line 552 pos 7: 'component._parent != null': Trying to remove a component that doesn't belong to any parent)
```

How do I fix this?

**Comment by spydon** [comment]
Just like the error says, you removed the component before it was added (or maybe you removed it twice in the same tick).
