### ISSUE TITLE
Lock to 30 FPS?

### ISSUE THREAD

**Issue by chris-rutkowski** [flame-engine/flame#1816]
Hey, excellent work with Flame, congrats!

In games there are scenarios where we may need to reduce the FPS, reasons such as:
- reduce battery consumption
- address the performance
- synchronise the frames with available frames in spritesheets

I checked the `FlameGame` and `Game` and I don't see the property such as desired/maximum FPS. Is there one? Otherwise, is it a planned feature? Shall we invoke the update method by self-made scheduler?

**Comment by spydon** [comment]
There is currently no such feature.
But it should be quite easy to implement yourself, just override `update` in `FlameGame` and do something like this:

```dart
  const minDt = 1/30; // 30 fps
  double dtOverflow = 0;

  @override
  @mustCallSuper
  void update(double dt) {
    dtOverflow += dt;
    if(dtOverflow < minDt) {
      return;
    } 
    if (parent == null) {
      updateTree(dtOverflow);
    }
    _cameraWrapper.update(dtOverflow);
   dtOverflow = 0;
  }
```

**Comment by chris-rutkowski** [comment]
Thanks @spydon ! That will work.
