### ISSUE TITLE
 `onTapXX` method called incorrect with TapCallbacks  on Flame 1.2.0+

### ISSUE THREAD

**Issue by ChadCSong** [flame-engine/flame#1832]
# Current bug behaviour
I am using  `FlameGame` and try to add a `PositionComponent` to game. `onTapXX` method called incorrect with TapCallbacks when I change the PositionComponent's position on version 1.2.1
I found the method `componentsAtPoint` in `Component` class is incorrectly pass the global point into `containsLocalPoint`.

# Expected behaviour
I think the point need parentToLocal first when the component is CoordinateTransform and parent is not null.

# Steps to reproduce
call parentToLocal before containsLocalPoint
```var localPoint = point;
    if (this is CoordinateTransform && parent != null) {
      localPoint = (this as CoordinateTransform).parentToLocal(point) ?? point;
    }
    if (containsLocalPoint(localPoint)) {
      yield this;
    }
```

# Flutter doctor output
```
not need
```

# More environment information
* Flame version: 1.2.1

# Log information

# More information

I will make a pull request to fix this bug.

**Comment by st-pasha** [comment]
The method `componentsAtPoint(point)` is supposed to accept a `point` which is in the local coordinate space. So I believe that it works as it's supposed to.

The tap events do get dispatched as they are supposed to, as can be seen in demos at
https://docs.flame-engine.org/main/tutorials/klondike/step4.html and https://docs.flame-engine.org/main/flame/inputs/tap-events.html#demo.

If you did find a certain configuration which cause a buggy behavior, then a Minimum Reproducible Example would help greatly to debug it.

**Comment by ChadCSong** [comment]
Tap the PeopleComponent first and the TapEvent will incorrect call when the Component moving down( Tap area is far from the drawed Rect).

```
class MainGame extends FlameGame with HasTappableComponents {
  @override
  Future<void>? onLoad() {
    add(PeopleComponent());
    return super.onLoad();
  }
}

class PeopleComponent extends PositionComponent with TapCallbacks {
  PeopleComponent() : super(size: Vector2(160, 160));

  Offset circleCenter = const Offset(0, 0);
  final Paint paint = Paint()..color = Colors.yellow;
  bool isMoving = false;

  var move = Vector2(0, 1);

  @override
  void render(Canvas canvas) {
    super.render(canvas);
    canvas.drawRect(Rect.fromCircle(center: center.toOffset(), radius: 80), paint);
  }

  @override
  void update(double dt) {
    super.update(dt);
    if (isMoving) {
      position = position += move;
    }
  }

  @override
  void onTapDown(TapDownEvent event) {
    super.onTapDown(event);
    isMoving = !isMoving;
  }
}

```

**Comment by ChadCSong** [comment]
Override the follow method can resolve this bug, but I think that is not the origin design.
```
  @override
  bool containsLocalPoint(Vector2 point) {
    return super.containsLocalPoint(absoluteToLocal(point));
  }

```

**Comment by ChadCSong** [comment]
The follow method called `componentsAtPoint` by pass canvasPosition value.
Is the canvasPosition is global position,not the local position?

```
@internal
  void deliverAtPoint<T extends Component>({
    required Component rootComponent,
    required void Function(T component) eventHandler,
    bool deliverToAll = false,
  }) {
    for (final child in rootComponent
        .componentsAtPoint(canvasPosition, renderingTrace)
        .whereType<T>()) {
      continuePropagation = deliverToAll;
      eventHandler(child);
      if (!continuePropagation) {
        CameraComponent.currentCameras.clear();
        break;
      }
    }
  }
```

**Comment by st-pasha** [comment]
If you turn on the debug mode `add(PeopleComponent()..debugMode=true);`, you'd see where the component is considered to be for the purposes of tap detection. You'll notice that the position of the component diverges from where the yellow square is rendered.

This is because `PositionComponent`'s `render()` is executed after the canvas translation, i.e. in the component's local coordinate space. Thus, within the `render()` method you don't have to take into account the component's movement at all:
```
void render(Canvas canvas) {
  canvas.drawRect(const Rect.fromLTWH(0, 0, 160, 160), paint);
}
```

Once you do that, the taps will now work as you expect them to.

**Comment by ChadCSong** [comment]
thanks for your anwser, I will try.
