### ISSUE TITLE
SpriteButton not releasing upon tap cancellation

### ISSUE THREAD

**Issue by CalvinMT** [flame-engine/flame#1843]
# Current bug behaviour
When cancelling a tap on a `SpriteButton`, the sprite of the `SpriteButton` stays in its pressed version, although the finger isn't pressing the screen anymore.

# Expected behaviour
It was expected for the `SpriteButton` to appear released upon cancelling its press.

# Steps to reproduce
Add a `SpriteButton.asset()` to a widget's build function and give it the paths to two distinct sprites to clearly distinguish the button's state (pressed and unpressed).
Launch the application and press on the button **without releasing**.
Drag the finger away from the button and release.

# More information
The fix might be as simple as to add the following lines to the `GestureDetector()` of the `_ButtonState` class in [sprite_button.dart](https://github.com/flame-engine/flame/blob/main/packages/flame/lib/src/widgets/sprite_button.dart):
```
onTapCancel: (_) {
  setState(() => _pressed = false);
},
```
A PR will shortly be added with the mentioned fix.

**Comment by spydon** [comment]
Thanks for your fix!
