### ISSUE TITLE
Key Event dings in MacOS when using KeyboardHandler in Component

### ISSUE THREAD

**Issue by immadisairaj** [flame-engine/flame#1849]
I am trying to add a key event for the sprite component in the game. I have used `KeyboardHandler` mixin in `SpriteComponent` and `HasKeyboardHandlerComponents` mixin in game.

# Current bug behaviour
With `KeyboardHandler`, I when overriding the `bool onKeyEvent`, and returning true to handle key events, The macOS dings telling it's not handled (which is not).
But, when using `KeyboardEvents` in game and not inside the component, the ding doesn't come. which means it's handled.

# Expected behaviour
Even when using the `onKeyEvent` from within the component, the os shouldn't ding and should be handled properly.

# Steps to reproduce
The below dings:
```dart
class CustomGame extends FlameGame with HasKeyboardHandlerComponents {
  @override
  Future<void>? onLoad() {
    add(CustomComponent());
  }
}

class CustomComponent extends SpriteComponent with KeyboardHandler {
  // ...
  @override
  bool onKeyEvent(
    RawKeyEvent event,
    Set<LogicalKeyboardKey> keysPressed,
  ) {
    final isKeyDown = event is RawKeyDownEvent;
    if (isKeyDown) {
      return true;
    }
    return false;
  }
}
```

The below doesn't ding:
```dart
// game.dart
class CustomGame extends FlameGame with KeyboardEvents {
  // ...
  @override
  KeyEventResult onKeyEvent(
    RawKeyEvent event,
    Set<LogicalKeyboardKey> keysPressed,
  ) {
    final isKeyDown = event is RawKeyDownEvent;
    if (isKeyDown) {
      return KeyEventResult.handled;
    }
    return KeyEventResult.ignored;
  }
}
```

# Flutter doctor output

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5 21G72 darwin-arm, locale en-IN)
    • Flutter version 3.0.5 at /Users/immadisairaj/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at /Users/immadisairaj/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc1
    • ANDROID_HOME = /Users/immadisairaj/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

# More environment information

Create a list of more environment information, like:
* Flame version: 1.2.1
* Platform affected: macOS (didn't check for other platforms)
* Platform version affected: macOS 12.5

# More information

I would like to work on this issue with some guidance. And, I am not sure if this is working fine on main branch.
I probably think we should make the component return `KeyboardEventResult` instead of `bool`.

**Comment by spydon** [comment]
The boolean that is returned from the component mixin is not for marking whether the event is handled or not, but whether it should keep on propagating to the next component or not. But maybe there is still a fix needed in the `HasKeyboardHandlerComponents` mixin.

**Comment by immadisairaj** [comment]
Looking at `keyboard.dart`

```dart
final blockedPropagation = !propagateToChildren<KeyboardHandler>(
  (KeyboardHandler child) => child.onKeyEvent(event, keysPressed),
);

// If any component received the event, return handled,
// otherwise, ignore it.
if (blockedPropagation) {
  return KeyEventResult.handled;
}
```

I think, if a child gets the event, the `blockedPropagation` has to be true which should result in the event handled?

I might be missing something here.

On a side note: we can add the doc comments in `keyboard_handler.dart` to easily understand the use of return type.

**Comment by immadisairaj** [comment]
I tried to play with it a bit and following are what I have observed.

- When we don't override `onKeyEvent`:
  - The `blockedPropogation` is being set to `false` when no event is being handled - which is expected

- When we override `onKeyEvent`:
  - The `blockedPropogation` is being set to `false` when we return `true` in the method
  - The `blockedPropogation` is being set to `true` when we return `false` in the method

when we override, the expected behaviour is reversed.
The problem might be in the `keyboard.dart`? (or not documented properly?)

What is the exact expected behaviour of the method and the return values (how they should be)?

cc: @renancaraujo @spydon

**Comment by immadisairaj** [comment]
I am not sure of how it has changed with the version `1.5.0`. This doesn't work when I am trying now (not even dings).

Maybe there would be needing some documentation regarding this? or is this really a new bug?

**Comment by spydon** [comment]
@immadisairaj can you explain a bit more, what it is that doesn't work? What do you do and what is the expected outcome?

**Comment by immadisairaj** [comment]
Ohh.. gosh! Sorry to bother you @spydon. I missed using `HasKeyboardHandlerComponents` and so is not working. Now it works as expected. Even the ding sound is not coming now (the issue is resolved and can be closed). Thank you and sorry for the trouble. :)

**Comment by spydon** [comment]
> Ohh.. gosh! Sorry to bother you @spydon. I missed using `HasKeyboardHandlerComponents` and so is not working. Now it works as expected. Even the ding sound is not coming now (the issue is resolved and can be closed). Thank you and sorry for the trouble. :)
> 

Super, glad to hear that it is working! 🙂
