### ISSUE TITLE
`SpriteBodyComponent` seems to not exist

### ISSUE THREAD

**Issue by dshukertjr** [flame-engine/flame#1850]
# Current bug behaviour
I was trying to create a `BodyComponent` with an image and I found [SpriteBodyComponent](https://docs.flame-engine.org/1.0.0/forge2d.html#spritebodycomponent) on the docs, but it seems like `SpriteBodyComponent` does not exist in the code base. 

# Expected behaviour
I think this is an outdated documentation, so it would be amazing if the section about `SpriteBodyComponent` was updated!

**Comment by spydon** [comment]
That must be updated in the docs indeed! The correct way now is to create a `BodyComponent` and add a `SpriteComponent` as a child to it.

**Comment by dshukertjr** [comment]
@spydon 
Thank you so much for the quick response!

**Comment by spydon** [comment]
I realized that this is actually already updated, the link in the issue is going to an old version of the docs.
This is the latest version https://docs.flame-engine.org/1.3.0/flame_forge2d/forge2d.html

I wonder if we can tell google to only index the last version...
