### ISSUE TITLE
Raycast from within CircleHitbox ignores the hitbox

### ISSUE THREAD

**Issue by ufrshubham** [flame-engine/flame#1865]
# Current bug behaviour
I found an issues when using CircleHitboxes and raycast. It seems that if I cast a ray from inside a circular hitbox, it automatically ignores that hitbox. But if the hitbox is replaced with a rectangular hitbox, it works fine.

# Expected behaviour
Ideally the raycast should stop at the circular hitbox similar to how it does for rectangle.

# Steps to reproduce
Here is an sample code that shows the bug.
```dart
class RayCastGame extends FlameGame with HasCollisionDetection {
  RaycastResult<ShapeHitbox>? result;
  late ShapeHitbox shapeHitbox1;
  late ShapeHitbox shapeHitbox2;

  @override
  Future<void>? onLoad() {
    debugMode = true;
    add(
      CircleComponent(
        radius: 20,
        position: size / 2,
        anchor: Anchor.center,
        paint: Paint()..color = Colors.red,
      )..add(
          shapeHitbox1 = CircleHitbox(), // Left - wrong output
          //shapeHitbox1 = RectangleHitbox(), // Right - correct output
        ),
    );

    add(
      CircleComponent(
        radius: 20,
        position: Vector2(size.x / 2, 30),
        anchor: Anchor.center,
        paint: Paint()..color = Colors.blue,
      )..add(
          shapeHitbox2 = CircleHitbox(),
        ),
    );

    return super.onLoad();
  }

  @override
  void update(double dt) {
    final ray = Ray2(
      origin: size / 2,
      direction: Vector2(0, -1),
    );

    result = collisionDetection.raycast(
      ray,
    );

    super.update(dt);
  }

  @override
  void render(Canvas canvas) {
    if (result != null) {
      canvas.drawLine(
        (size / 2).toOffset(),
        (result!.intersectionPoint)!.toOffset(),
        Paint()
          ..color = Colors.yellow
          ..strokeWidth = 5,
      );
    }
    super.render(canvas);
  }
}
```
And here are the 2 outputs when using hitbox for red circle as CircleHitbox and RectangleHitbox. Left one uses a circular hitbox and right one uses rectangular hitbox. For some reason the ray cast passes through the hitbox of red circle in first example.

![image](https://user-images.githubusercontent.com/33748002/186083396-bfbf2cab-12ff-42f7-a5cc-1850666a6cf1.png)

# Flutter doctor output
```bash
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.22000.856], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.1)
[!] Android Studio (not installed)
[√] VS Code (version 1.70.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.
```

# More environment information
* Flame version: 1.3.0
* Platform affected: Windows (probably others too)
* Platform version affected: 11

# More information

**Comment by spydon** [comment]
I wonder if it is because the ray is straight up or something, because it works on here:
https://examples.flame-engine.org/#/Collision%20Detection_Raytracing
Very strange, will try to solve it tomorrow if I get some time!

**Comment by spydon** [comment]
@ufrshubham does this happen if you cast the ray in any other direction?

**Comment by ufrshubham** [comment]
Nope. I observed this behaviour only for vertically up raycasts.
