### ISSUE TITLE
game.overlays.removeAll causes concurrentModificationException

### ISSUE THREAD

**Issue by Hwan-seok** [flame-engine/flame#1871]
# Current bug behaviour
Imagine that you do not know current active overlays and want to remove all overlays.
You should use `game.overlays.removeAll(overlays.activeOverlays)`.

But when you use `game.overlays.removeAll(overlays.activeOverlays)`, the overlays throws `ConcurrentModificationException`.

# Expected behaviour
Safely remove all overlays.

# Steps to reproduce
- You can reproduce it by running this test
https://github.com/Hwan-seok/flame/blob/a7bd00e59c24bd767bc1ad3da088d9055b2991b7/packages/flame/test/game/overlays_manager_test.dart#L153-L160

# More environment information
* Flame version: 1.3.0

# Log information
```dart
Concurrent modification during iteration: Instance of 'UnmodifiableListView<String>'.
dart:collection                                    ListMixin.forEach
OverlayManager.removeAll
package:flame/…/game/overlay_manager.dart:81
main.<fn>.<fn>
```

# More information

 
 Are you interested in working on a PR for this?  Yes

**Comment by Hwan-seok** [comment]
I think it is related to the usage of overlays but not the overlay itself.

The following is the workaround.
```dart
overlays.removeAll({...overlays.activeOverlays}); 
```

**Comment by spydon** [comment]
You can call `overlays.clear()` if you want to remove all the overlays.

**Comment by Hwan-seok** [comment]
You are right. When simply removing all overlays, `overlays.clear()` would be OK.

Actually, in my case, it has more implementation internally about "protected" overlay.
I have many overlays in my app and sometimes all should be removed except for "protected".
So when I remove all overlays, I should filter the "protected" from overlays.activeOverlays and use removeAll.
So it is different from `clear()`

There are many use cases about protected overlays but it might be used in a very small portion of the large app so It is very specific to my case.

**Comment by spydon** [comment]
If you filter it first you shouldn't get a `ConcurrentModificationException` since you get back a new iteratable after doing `where`:
```dart
overlays.removeAll(overlays.activeOverlays.where(...));
```

**Comment by Hwan-seok** [comment]
Yes, but creating a new Iterable does not prevent it.
it should be used with `...where(...).toList()`.

I added both tests, you can check them in here
https://github.com/Hwan-seok/flame/blob/b6e06389e95ae8703774aaf2c4782834e9cefa44/packages/flame/test/game/overlays_manager_test.dart#L162-L187

**Comment by spydon** [comment]
True true, I forgot that the iterable is lazy.
