### ISSUE TITLE
Allow children of `ComposedParticle` to have varied lifespan

### ISSUE THREAD

**Issue by akvus** [flame-engine/flame#1872]
# Problem to solve
`ComposedParticle` propagates its lifespan to all its children when it is constructed. This overrides the lifespan assigned to its children (i.e. while using `Particle.generate`).

# Proposal
Make a version of `ComposedParticle` that would allow children to use their own lifespan.

**Comment by spydon** [comment]
Sounds sensible, it could probably be an optional argument to the constructor. Do you want to work on a PR for this?

**Comment by akvus** [comment]
I believe there is one question first. 
If we'll have separate lifespans for the particles within `ComposedParticle`, then they won't get removed once they reach the end of their lifecycles. They will get removed when `ComposedParticle` reaches the end of its lifespan. This means a developer would need to manually stop rendering the particles when `progress` reaches 1 so they don't just keep hanging on the screen.
Also, a particle that has a longer lifespan than `ComposedParticle` will get cut off when `ComposedParticle` is removed.
What would be the best approach here?
