### ISSUE TITLE
Doc of `RenderableTileMap.getLayer<T extends Layer>` from `flame_tiled` is misleading

### ISSUE THREAD

**Issue by raulmabe** [flame-engine/flame#1873]
# What could be improved

The documentation or implementation of `RenderableTileMap.getLayer<T extends Layer>(String name)` from `flame_tiled`

# Why should this be improved

Doc of `RenderableTileMap.getLayer<T extends Layer>(String name)` from `flame_tiled` is misleading IMO:

>  /// Returns a layer of type [T] with given [name] from all the layers
  /// of this map. If no such layer is found, null is returned.

Reading this I thought it would recursively check from all the layers of the map; although it doesn't. 

I have the following Tiled map structure:

```
TileMap/
├─ Foreground/
│  ├─ spawns
│  ├─ collisions
│  ├─ trees
├─ Background/
│  ├─ weed
│  ├─ floor
```

I expected that `_mapComponent.tileMap.getLayer<ObjectGroup>('collisions')` would return the proper layer instead of `null`, but it doesn't. 

# Proposed solutions

Any of these 2 solutions are good to me:

1. Update the doc of `RenderableTileMap.getLayer<T extends Layer>(String name)` to explicitly inform it only searches for layers on the first level while adding the same method to `Group` layer to be able to find the layer with the same API as in `RenderableTileMap`.
3. Update `RenderableTileMap.getLayer<T extends Layer>(String name)` implementation to search inside `Group` layers too for the specific layer.

# Any risks?

I haven't identified any atm.

# More information

- I can do a PR if it looks good

**Comment by spydon** [comment]
I vote for number 2. It will be a breaking change of course, but I doubt anyone's current code will be affected by it. I'll assign you to the issue.

**Comment by raulmabe** [comment]
Good! Let me propose another solution and you decide:

3. Update the docs of the current method and add another one to `RenderableTileMap` maybe called `getLayerRecursively()` or `getDeepLayer()` with the new implementation.

This way it won't be a breaking change; although I also doubt anyone's code will be affected by it.

**Comment by spydon** [comment]
I think 2 is fine still.

**Comment by ufrshubham** [comment]
We should proceed with caution with option 2, because layers from different groups can have same name. In fact, any 2 layers in the same level can have same name too. So searching recursively for just one will return just the first match. Maybe we should add a `getLayerById()` because `id` is unique for each layer.

**Comment by spydon** [comment]
Alright, maybe better to add a boolean optional argument to `getLayer` that is used to decide whether it should search recursively or not then? And seems fitting to use BFS here, to make that the result is alike as the current one as possible. 

> Maybe we should add a getLayerById() because id is unique for each layer.

Sounds like something we could also add.

**Comment by munsterlander** [comment]
When we wrote that code, the basic thinking was you wouldn't create layers with the same name, but I agree in that it should probably use by id because that is truly unique. That makes the code less understandable though. Another thought is using dot notation for nested layers so you can use names and not recurse.

**Comment by raulmabe** [comment]
> The real issue though would be getting parent group parameters passed to the child layer. This is not exactly a straight cut issue.

I am looking at the libGDX code to see how they did it and get some inspiration:

1. [They keep a reference of the parent layer in each Layer.](https://github.com/libgdx/libgdx/blob/b86c20cf1a354f5345fd1e8612dcd46c9b46a972/gdx/src/com/badlogic/gdx/maps/MapLayer.java#L31)
2. [They invalidate/validate the layer offset when some parent layer has updated its offset](https://github.com/libgdx/libgdx/blob/b86c20cf1a354f5345fd1e8612dcd46c9b46a972/gdx/src/com/badlogic/gdx/maps/MapLayer.java#L77-L92). If invalidate, it will redo the calculations to validate it again.
3. [They won't render the children layers if the group layer is not visible](https://github.com/libgdx/libgdx/blob/b86c20cf1a354f5345fd1e8612dcd46c9b46a972/gdx/src/com/badlogic/gdx/maps/tiled/renderers/BatchTiledMapRenderer.java#L154-L161) (more relatable to #1874)

I don't seem to find how the opacity property of a groupLayer affects the children layers...
