### ISSUE TITLE
`flame_tiled` `RenderableTileMap ` does not render nested `TileLayer` & `ImageLayer`

### ISSUE THREAD

**Issue by raulmabe** [flame-engine/flame#1874]
Very related to https://github.com/flame-engine/flame/issues/1873

I don't know if this is expected as I am not a heavy Tiled user, but seems off to me and libGDX did render every TileLayer without caring about levels deep.

# Current bug behaviour
Currently [`RenderableTileMap` does only consider the first level of layers to render](https://github.com/flame-engine/flame/blob/main/packages/flame_tiled/lib/src/renderable_tile_map.dart#L138). 

Thus if I have the following Tiled map structure the current implementation will fail to render all layers, as it will only consider the two group layers (Foreground and Background), which will be considered as `_UnrenderableLayer`:

```
TileMap/
├─ Foreground/
│  ├─ spawns
│  ├─ collisions
│  ├─ trees
├─ Background/
│  ├─ weed
│  ├─ floor (TileLayer)
```

# Expected behaviour
I expect that `RenderableTileMap` looks for *every* renderable layer and renders it accordingly. It shouldn't care about its deep.

# Steps to reproduce
1. Make a TiledMap with the structure attached before
2. Check how `RenderableTileMap` ignores the `TileLayer` and `ImageLayer`

# Flutter doctor output

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 11.6 20G165 darwin-x64, locale es-ES)
    • Flutter version 3.0.5 at /Users/raulmateobeneyto/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (7 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/raulmateobeneyto/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.6 20G165 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

# More environment information

 - flame: ^1.3.0
-  flame_tiled: ^1.7.2

# More information

- I am open to make a PR.

**Comment by spydon** [comment]
This will probably be quite a big undertaking, but we are of course open to PRs if you're interested in building this!
What do you think @kurtome @ufrshubham @nathanaelneveux?

**Comment by kurtome** [comment]
It might be really simple to just add the child layers of Groups recursively as independent renderable layers. 

I'm not sure if parent Group properties (like offset x/y) can affect the children though.

**Comment by ufrshubham** [comment]
> I'm not sure if parent Group properties (like offset x/y) can affect the children though.

Yeah, they do affect all the child layers.

**Comment by raulmabe** [comment]
What do you think about the following solution:

- Render all renderable layers without caring about its level deep, doing a DFS.
- Each layer should have a reference to its parent layer in order to calc the resulting properties.

So if each layer has a reference to its parent layer, forming a LayerTree; we could have the following getters:

- opacity -> `get opacity => (parent?.opacity ?? 1) * opacity;`
- offsetX -> `get offsetX => (parent?.offsetX ?? 0) + offsetX`
- offsetY -> `get offsetY => (parent?.offsetY ?? 0) + offsetY`

[libGDX does an invalidation and validation pattern](https://github.com/libgdx/libgdx/blob/b86c20cf1a354f5345fd1e8612dcd46c9b46a972/gdx/src/com/badlogic/gdx/maps/MapLayer.java#L77-L92) to only do these calculations when they have been modified. I don't know if this a big improvement on performance; although it seems like the only reason.

Lmk if I'm missing something

**Comment by spydon** [comment]
Sounds like these layers possibly could be built with `PositionComponent`s? Which would enable a lot of cool things.

**Comment by raulmabe** [comment]
That sounds interesting although I don't know the full benefits as I am just learning about flame. Would you care elaborating? As I understand the current layers are not build as `PositionComponent`s are they?

**Comment by ufrshubham** [comment]
Yeah, extending layers from the position component seems worth it. Along with handling the transformations automatically and correctly, it will also allow users to play around with priority values for each layer. Creating a foreground and background layer using the same tilemap will become possible.

**Comment by kurtome** [comment]
> So if each layer has a reference to its parent layer, forming a LayerTree; we could have the following getters:
>
> - opacity -> get opacity => (parent?.opacity ?? 1) * opacity;
> - offsetX -> get offsetX => (parent?.offsetX ?? 0) + offsetX
> - offsetY -> get offsetY => (parent?.offsetY ?? 0) + offsetY

This looks right to me, I played with Tiled a bit and the offsets are definitely additive and the opacity is multiplicative. I'm guessing the `parallaxX` and `parallaxY` are also multiplied with their parent (so, 0.5 and 0.5 => 0.25), similar to opacity. Although I didn't test the parallax much.

Another important note here is that you can nest groups within groups, so when calculating the value for the current layer, you need to use the parent's value based on it's parents all the way up the tree. So, you probably want to store the calculated value at each group layer for its children to access.

This actually seems pretty doable with the current structure of the code, a new `_RenderableGroupLayer` can call render on its children, etc.

> Sounds like these layers possibly could be built with PositionComponents? Which would enable a lot of cool things.
Ya! This would be awesome, it's definitely a much bigger refactor to accomplish this though.

**Comment by kurtome** [comment]
Related to Group layers generally: https://github.com/flame-engine/tiled.dart/pull/51

**Comment by kurtome** [comment]
This isn't the prettiest solution, but it seems to get the job done: https://github.com/flame-engine/flame/pull/1886
