### ISSUE TITLE
MissingPluginException when try to play audio in Android

### ISSUE THREAD

**Issue by mhd-barikhan** [flame-engine/flame#188]
[ERROR]MissingPluginException(No implementation found for method startHeadlessService on channel xyz.luan/audioplayers)

`Flame.audio.play('test.mp3');`

the sound play fine but showing above error in android.

**Comment by luanpotter** [comment]
This is clearly a bug in Audio Players, in fact, one already open that, already fixed I believe (just need to release a new version): https://github.com/luanpotter/audioplayers/pull/332
