### ISSUE TITLE
Background music coming out of earpiece speaker only on iOS (Flame audio)

### ISSUE THREAD

**Issue by uristrimber** [flame-engine/flame#1880]
# Current bug behaviour

Background music coming out of earpiece speaker only on iOS
# Expected behaviour

The sound should come out of the main speaker also
# Steps to reproduce

Initialize bgm music, play any file.

# More environment information

Create a list of more environment information, like:
* Flame version: 1.3.0
* Platform affected: ios
* Platform version affected: ios 15

**Comment by spydon** [comment]
Duplicate of #1194

**Comment by uristrimber** [comment]
@spydon do you want me to pr the fix to flame_audio? I just came to the same solution as on https://github.com/bluefireteam/audioplayers/issues/1194

**Comment by spydon** [comment]
> @spydon do you want me to pr the fix to flame_audio? I just came to the same solution as on https://github.com/bluefireteam/audioplayers/issues/1194

The PR should go to audioplayers (we maintain that too) if you have a good fix, flame_audio is just a thin wrapper.
