### ISSUE TITLE
`flame_tiled` does not render on Web with packed tilesets

### ISSUE THREAD

**Issue by jtmcdole** [flame-engine/flame#1888]
# Current bug behaviour
`TiledComponent.load()` with a tmx file containing an internal (packed) tileset does not render when running Flame on Chrome or Edge targets.

# Expected behaviour
It renders on web.

# Steps to reproduce
E.g. embedded tileset:

```
 <tileset firstgid="1" name="flat_hex" tilewidth="60" tileheight="60" tilecount="12" columns="4">
  <image source="../images/tileset/Tileset_Hexagonal_FlatTop_60x39_60x60.png" width="240" height="180"/>
 </tileset>
 ```

To get it working:

```
 <tileset firstgid="1" source="Tileset_Hexagonal_FlatTop_60x39_60x60.tsx"/>
```

# Flutter doctor output
```
[√] Flutter (Channel stable, 3.3.0, on Microsoft Windows [Version 10.0.19044.1949], locale en-US)
    • Flutter version 3.3.0 on channel stable at C:\Development\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (6 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Development\Android\Sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = C:\Development\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32825.248
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.71.0)
    • VS Code at C:\Users\john\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.48.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1949]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 105.0.5195.52
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 105.0.1343.27

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

# More environment information
* Flame version: 1.3.0
* Platform affected: web

# Log information
There are actually no error logs. It fails silently.

# More information

It **does** render on Android and Windows native.

**Comment by jtmcdole** [comment]
In _RenderableTileLayer._cacheLayerTiles():

```dart
        batch.addTransform(
          source: src,
          transform: ui.RSTransform(
            scos,
            ssin,
            offsetX + -scos * anchorX + ssin * anchorY,
            offsetY + -ssin * anchorX - scos * anchorY,
            flip: false,  // <- We don't need Flip here.
            // flip: flips.flip,
          ),
        );
```

If `flip` is true, `SpriteBatch.addTransform`, a synchronous function, calls an unawaited async function `_makeFlippedAtlas`. 

Whatever `_makeFlippedAtlas` is doing is broken on Web.  Even with an unpacked `tsx` file, if it contains a single tile that's flipped, it will not be rendered.  However - is `flip: true` even needed if the rotation is accounted for?  If I remove it from my tree; all of my tilemaps (packed, unpacked tilesets, and loose images) all render.

**Comment by jtmcdole** [comment]
`flip` is needed (for you guessed it.. flips not rotations) - but `_makeFlippedAtlas` does not work on web.

**Comment by spydon** [comment]
Have you tried running it in any non-chrome based browsers?

**Comment by spydon** [comment]
Any difference on different renderers?
https://docs.flutter.dev/development/platform-integration/web/renderers#command-line-options

**Comment by jtmcdole** [comment]
Last comment:

in `_RenderableTileLayer.load` - if you pass `useAtlas: !kIsWeb` to SpriteBatch.load, it at least fixes that issue with localhost.

**Comment by jtmcdole** [comment]
> Any difference on different renderers? https://docs.flutter.dev/development/platform-integration/web/renderers#command-line-options

Chrome-desktop with HTML render:  no images loaded. FpsTextComponent shows "2" - not 100.
Chrome-android with HTML render: no images loads, FpsTexTcomponent shows "15" - was showing 30 (on other flame games, I was getting 120fps).
Safari on iPad with HTML render: some images broken, isomorphic with individual images loads. Fps 3.

**Comment by jtmcdole** [comment]
**--web-renderer canvaskit and useAtlas: !kIsWeb**

`flutter run -d web-server  --web-port 8080 --web-hostname 0.0.0.0 --web-renderer canvaskit`

Chrome Desktop (localhost, ip:port): 100fps (smooth as glass) all images load
Chrome Android (ip:port): ~95fps, all images load
Safari iPad (ip:port): 60fps (smooth), all images load.

**Comment by jtmcdole** [comment]
I'm also not getting bad boundary paints with `useAtlas: !kIsWeb`  whereas before I was getting a sliver of texture painted at the top of tiles at different zoom levels. 

I could put up my hacky "codefu is playing with tiled way more than he should be" project if you'd like to see the repos.

**Comment by spydon** [comment]
The sliver you are talking about is probably this issue: https://github.com/flutter/flutter/issues/14288
It should be possible to solve by using this viewport (or using Impeller :sweat_smile:) https://github.com/flame-engine/flame/pull/1866

> I'm also not getting bad boundary paints with useAtlas: !kIsWeb whereas before I was getting a sliver of texture painted at the top of tiles at different zoom levels.

I wonder if this is a degradation in Flutter then, because we used to have this by default in the code some versions ago if I remember correctly.

**Comment by jtmcdole** [comment]
The sliver problem is not vertical lines, but horizontal.  If zoom level is 1, no problems.  I think it is more around the non-power-of-2 sprite sheets. 

![image](https://user-images.githubusercontent.com/1924313/188507788-39413041-a307-4bd0-a809-5c4b4c806241.png)

**Comment by jtmcdole** [comment]
It's this bug!  flutter/flutter/issues/103803  

Closing this as its a Flutter bug for 3.3.0

**Comment by jtmcdole** [comment]
for anyone else on flutter 3.3.0 and testing:

```
flutter run -d chrome --dart-define=BROWSER_IMAGE_DECODING_ENABLED=false --profile
```
