### ISSUE TITLE
Use Flutter Tweening for easing on Flame Components

### ISSUE THREAD

**Issue by nisimjoseph** [flame-engine/flame#189]
How can I use a Flame Component and Flutter Tweening, or any other moving/rotation/scale animation, to any Flame component? (I am not talking about Sprite animation using images)
Currently, I see that I can only set values and not do animation on them.

**Comment by erickzanardo** [comment]
This not something that is implemented on Flame yet, we sure do want to add this feature, but at the moment you need to implement it yourself on your component. Hopefully this example can help you in the meanwhile https://github.com/fireslime/bounce_box/blob/master/game/lib/screens/game/in_game_message.dart

**Comment by nisimjoseph** [comment]
thank you.
