### ISSUE TITLE
Make TiledMapComponent positionable 

### ISSUE THREAD

**Issue by jtmcdole** [flame-engine/flame#1890]
# What could be improved
`TiledMapComponent` extends `Component` - in discord conversations it was agreed that they should extend `PositionComponents`

bonus points: tiles could also be positionable, leading to some interesting animations of tiles entering the world.

# Why should this be improved
No other way to position aside from wrapping the map in a Position component.  No way to position tils either.  If tiles existed as individual components; items could just be easily added to them with "add()".

# Any risks?
Rendering would have to visit objects to do the same as today's:

```dart
_cachedSpriteBatches.values.forEach((batch) {
      batch.render(canvas, paint: _layerPaint);
    });
```

# More information
* I'm interested in working on it.
* Potential breaking change for anyone depending on tiles?

**Comment by spydon** [comment]
It will be very cool when you can start applying effects to tiles!
Definitely worth making breaking changes here, I think a lot of the code can be simplified when it makes use of the fields in the `PositionComponent`.

I assigned you to the issue.

**Comment by spydon** [comment]
As mentioned in Discord, making the tiles `PositionComponent` won't be efficient enough sadly, but it should be fine to have the `TiledMapComponent` as a `PositionComponent`.

**Comment by jtmcdole** [comment]
Yeah - I think this warrants more exploration. If someone has a smaller map games (e.g. Into the Breach has only 8x8 tiles!) might not care about all the optimizations if they want to do their animations: 

![image](https://user-images.githubusercontent.com/1924313/188687705-655bbcba-218b-477d-8516-f0bdc423478d.png)

**Comment by jtmcdole** [comment]
(note: this grid is similar to hex grids. its h = w*.75).. will have to play with this concept later...

**Comment by jtmcdole** [comment]
Skipping individual tile positioning for now; going with the title "just let me move this thing around".
