### ISSUE TITLE
Refactor packages/flame_tiled/lib/src/renderable_tile_map.dart

### ISSUE THREAD

**Issue by securez** [flame-engine/flame#1913]
# What could be improved
Split some large files that holds several classes, Ex: packages/flame_tiled/lib/src/renderable_tile_map.dart

# Why should this be improved
To ease refactor and work on the package.

# Any risks?
I don't recall for any

# More information
I already refactored packages/flame_tiled/lib/src/renderable_tile_map.dart to split them in multiple files that are parts, and split a class that has 4 behaviours into 4 different classes, but before submit a PR, I don't know if there's a plan for this package?, 
And if makes sense to make _RenderableLayer family public and a default factory, this can be used to supply custom implementations to render some layers of the map.

**Comment by ufrshubham** [comment]
I literally did the same thing today. It is definitely worth it to refactor that file before it goes out of control. Splitting into part should be fine.

As for making _RenderableTileLayer public, not sure how much value it can add. If someone really wants to do custom rendering they can always directly access the layers from the tiled package.

**Comment by spydon** [comment]
> I literally did the same thing today. It is definitely worth it to refactor that file before it goes out of control. Splitting into part should be fine.
> 
> As for making _RenderableTileLayer public, not sure how much value it can add. If someone really wants to do custom rendering they can always directly access the layers from the tiled package.
> 

Should I assign you to the issue @ufrshubham?

**Comment by ufrshubham** [comment]
> Should I assign you to the issue @ufrshubham?

Yeah I can create a PR for this, unless @securez already has plans to take up this issue.

**Comment by securez** [comment]
I already did split all the files but didn't change visibility:

```
part 'renderable_tile_layer.dart';
part 'renderable_tile_layer_tile.dart';
part 'renderable_tile_layer_utils.dart';
```
One class that I'm started to think to split is _RenderableTileLayer into _RenderableIsometricTileLayer, etc. but I'm need some more use case testing with object over the map prior to refactor _RenderableTileLayer.

I can submit a PR with the split files only.

**Comment by spydon** [comment]
@kurtome @jtmcdole

**Comment by jtmcdole** [comment]
I can split the renderable tile layer, but not sure how much value that brings when it's only caching that is different.

I do see value in the caching math being exposed for path finding more so than messing with the blitting.

**Comment by ufrshubham** [comment]
@jtmcdole maybe in your PR just move the layer classes into part files and let it merge. After that we can think of splitting the renderable tile layer if needed.

**Comment by jtmcdole** [comment]
> @jtmcdole maybe in your PR just move the layer classes into part files and let it merge. After that we can think of splitting the renderable tile layer if needed.

Which PR :D

**Comment by ufrshubham** [comment]
> Which PR :D

I was thinking #1906, but since it is now fully ready, let's do this refactor in a separate PR.
