### ISSUE TITLE
Support animated tiles

### ISSUE THREAD

**Issue by jtmcdole** [flame-engine/flame#1914]
# What could be improved

Tiled supports animated tiles. tiled.dart looks to parse them.  We can support animated tiles easily once #1910 lands.

# Why should this be improved

Animations rock:
![Animation](https://user-images.githubusercontent.com/1924313/190887021-30901a80-0c6b-4660-a73c-57baa6d7f8aa.gif)

# Any risks?

Update to layers to be more component like - they need an update() phase.

# More information

I'll take it from here.

**Comment by spydon** [comment]
> to be more component like

Couldn't they just be components?

**Comment by jtmcdole** [comment]
> > to be more component like
> 
> Couldn't they just be components?

They can, but that is a different pr
