### ISSUE TITLE
How to simulate the software effect? Like a rope.

### ISSUE THREAD

**Issue by iBinbro** [flame-engine/flame#1929]
# Problem to solve
flame is a very good game engine, thank you very much for your contributions. Now I have a problem in using it, how to simulate the software effect? Like a rope.

# More information
![rope](https://user-images.githubusercontent.com/15324447/191409057-713eb0e8-ca6e-4641-a8e4-77105df57a31.gif)

**Comment by ufrshubham** [comment]
This is already supported by forge2d's rope joint.

**Comment by st-pasha** [comment]
You could model a rope like that by creating a chain of stick-shaped rigid bodies, each with some small but nonzero mass.

**Comment by iBinbro** [comment]
> You could model a rope like that by creating a chain of stick-shaped rigid bodies, each with some small but nonzero mass.

Thanks, it's a really good idea so far.
But is there a performance issue if my rope is too long?
How do I achieve a stretchable rubber band effect?

**Comment by iBinbro** [comment]
> This is already supported by forge2d's rope joint.



> 

Thanks, I know. But what I'm trying to achieve right now is that rope.
