### ISSUE TITLE
Create SpriteFont class

### ISSUE THREAD

**Issue by st-pasha** [flame-engine/flame#1935]
Currently we have `SpriteFontTextFormatter`, but not the `SpriteFont` class. Encapsulating the font  information into a dedicated class would make it easier to create multiple formatters from the same font definition (i.e. for different font sizes, colors, etc); and also to support sprite-fonts from the `TextStyle` class.

The change would affect the construction of the `SpriteFontTextFormatter`. We could make it slow via the regular deprecation cycle, or fast by making a breaking change.

**Comment by spydon** [comment]
How would the slow deprecation cycle look like here when it is the constructor that needs to be deprecated?
Are there only optional arguments that need to be deprecated?

**Comment by st-pasha** [comment]
> How would the slow deprecation cycle look like here when it is the constructor that needs to be deprecated?

We could make the new constructor a factory one, and deprecate the default constructor. Then, after few releases the default constructor can be removed, and then later we can make the default constructor do the same thing as the factory constructor and deprecate the latter.

A slightly more breaking approach would be to rename the current constructor into `.legacy()`, and make the new default constructor with the new API. This would require the users to adjust their code only a little at first, and then making the full switch at a later time.

**Comment by spydon** [comment]
The first approach sounds good.
