### ISSUE TITLE
[core] Create a new BareFlameGame class

### ISSUE THREAD

**Issue by st-pasha** [flame-engine/flame#1936]
The `BareFlameGame` class would be like the `FlameGame` (i.e. based on a component tree), but without the built-in camera (hence, "bare"). Thus, its structure would be something like this:
```dart
class BareFlameGame extends Game {
  final Component root;

  void update(dt) => root.updateTree(dt);
  void render(canvas) => root.renderTree(canvas);
  Future<void> add(child) => root.add(child);
  Future<void> addAll(children) => root.addAll(children);
  void remove(child) => root.remove(child);
  void removeAll(children) => root.removeAll(children);

  // + more pass-through methods like that.
}
```

This would essentially be a bare-bones FCS game, without any additional features. 

This class would make it easier to use the new `CameraComponent` without having to carry around the old camera too.

**Comment by jtmcdole** [comment]
For components that care about the camera (`TiledComponent`), how would they get access to the camera?

**Comment by spydon** [comment]
> For components that care about the camera (`TiledComponent`), how would they get access to the camera? 

The `TiledComponent` will have to take a `CameraComponent` into consideration too,  how is the current `TiledComponent` using the old camera?

**Comment by spydon** [comment]
> The BareFlameGame class would be like the FlameGame (i.e. based on a component tree), but without the built-in camera (hence, "bare"). 

Sounds good, I think in Flame 2.0 this would be the new `FlameGame` and the other camera completely removed.

**Comment by jtmcdole** [comment]
> how is the current `TiledComponent` using the old camera?

With the mixin `with HasGameRef<T>` where `T extends FlameGame` - so you can see that's immediately wrong.  

`onLoad` it grabs the camera and then shoves it on the `RenderableTileMap`.

So in the future, it is expected that `CameraComponent` will be passed to render? The TiledComponent is in the "world" and multiple cameras can render it... so you could just say `TileComponent()..camera = myCamera1`, but that will still just give it one camera and render is tied elsewhere.

**Comment by st-pasha** [comment]
@jtmcdole Generally, components shouldn't really care about the camera; though there could be some that may want to take into account certain properties related to the camera: the currently visible region of the world, camera zoom level, etc. We were planning to pass this information along with the `RenderingContext`, see #1684 for the discussion around that.
