### ISSUE TITLE
Windows specific test failures

### ISSUE THREAD

**Issue by ufrshubham** [flame-engine/flame#1942]
# Current bug behaviour

When I run `melos run test` on Windows, 2 tests constantly fail. These are the 2 test:
- Vector2 test scaleTo (packages\flame\test\extensions\vector2_test.dart)
- SpriteAnimationWidget can safely change animation parameter (packages\flame\test\widgets\sprite_animation_widget_test.dart)

These tests do not fail in the github workflow (runs on Ubuntu).

The first test fails due to a minor deviation in expected and actual values of `length`, `x` and `y` of a scaled vector. Using `expectDouble` is enough to avoid that failure.
The second test is a bit strange. For some reason, after doing `pump()` in that test, the `dt` values in the `SpriteAnimation` turns out to be 0.

# Expected behaviour

Ideally these tests should pass on all the platforms.

# Steps to reproduce

Unfortunately, you'll need to be on a windows platform to reproduce this problem.

# Flutter doctor output

<details>
  <summary>Show</summary>
  
```
[√] Flutter (Channel stable, 3.3.2, on Microsoft Windows [Version 10.0.22000.1042], locale en-US)
    • Flutter version 3.3.2 on channel stable at C:\apps\android\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (13 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\apps\android
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = C:\apps\android
    • ANDROID_SDK_ROOT = C:\apps\android\cmdline-tools\tools
    • Java binary at: C:\apps\openjdk-11.0.2_windows-x64_bin\jdk-11.0.2\bin\java
    • Java version OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32901.215
    • Windows 10 SDK version 10.0.22000.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.71.2)
    • VS Code at C:\Users\Ryuzaki\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.48.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.1042]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 105.0.5195.127
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 105.0.1343.42

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

# More environment information

# Log information

<details>
  <summary>Vector2 test scaleTo</summary>
  
```
Expected: <2.0>
  Actual: <2.0000000000000004>

package:test_api                        expect
test\extensions\vector2_test.dart 74:7  main.<fn>.<fn>
```
</details>

<details>
  <summary>SpriteAnimationWidget test</summary>
  
```
The following TestFailure was thrown running a test:
Expected: a value equal to <0>
  Actual: <921>
   Which: is not a value equal to <0>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure>.<anonymous closure> (file:///C:/dev/Flutter/packages/flame/packages/flame/test/widgets/sprite_animation_widget_test.dart:110:9)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///C:/dev/Flutter/packages/flame/packages/flame/test/widgets/sprite_animation_widget_test.dart line 110
The test description was:
  can safely change animation parameter
```
</details>

# More information

I'll create a draft PR fixing first test and will investigate the second on further.

**Comment by st-pasha** [comment]
The second test is weird - why does it catch a `TestFailure`? Perhaps if we removed that try-catch, the error would be more apparent. Not to mention that the test runs itself 1000 times, which is also not good.

**Comment by ufrshubham** [comment]
> The second test is weird - why does it catch a `TestFailure`? Perhaps if we removed that try-catch, the error would be more apparent. Not to mention that the test runs itself 1000 times, which is also not good.

Yeah, that try-catch is totally unnecessary. Removing it was the first thing I tried, but then the `isNotZero` checks on `.elapsed` fail. Even if I run the loop 5 times, it still fails.

**Comment by munsterlander** [comment]
Can confirm the issues and solutions and the causes.  I would like to think this is due to how amazingly fast Windows machines are....
