### ISSUE TITLE
Flame_bloc: The method 'removeWhere' isn't defined for the type 'SpaceShooterGame'

### ISSUE THREAD

**Issue by JCzz** [flame-engine/flame#1946]
```
flutter --version
Flutter 3.4.0-33.0.pre.37 • channel master • https://github.com/flutter/flutter.git
Framework • revision a7355d1d32 (34 minutes ago) • 2022-09-28 03:35:24 -0400
Engine • revision ec650e216c
Tools • Dart 2.19.0 (build 2.19.0-249.0.dev) • DevTools 2.17.0

```

Update: Same for channel stable

In `packages/flame_bloc/example/lib/src/game/game.dart` line 21 I get:
'removeWhere' isn't defined for the type 'SpaceShooterGame:

```
class GameStatsController extends Component with HasGameRef<SpaceShooterGame> {
  @override
  Future<void>? onLoad() async {
    add(
      FlameBlocListener<GameStatsBloc, GameStatsState>(
        listenWhen: (previousState, newState) {
          return previousState.status != newState.status &&
              newState.status == GameStatus.initial;
        },
        onNewState: (state) {
          gameRef.removeWhere((element) => element is EnemyComponent);
        },
      ),
    );
  }
}
```

**Comment by ufrshubham** [comment]
Seems to be working fine for me. @JCzz are you on the latest commit? `removeWhere` seems to have been added a month back by this commit abd28f28a627799ea4602026d91f52bc97feb91e

**Comment by spydon** [comment]
This is an unreleased feature, you'd have to depend on `main` (or wait for the next release) for this to work.

**Comment by JCzz** [comment]
Ahh ok right, thanks @spydon and @ufrshubham I will do that. Thanks for verifying that it works. 5 min, I will get back...

**Comment by JCzz** [comment]
@spydon & @ufrshubham

It totally works, I also just needed to run  `flutter pub global activate melos`. It has ben a while since I had to build flame. Love this, good work.
