### ISSUE TITLE
Interactive docs: `MoveEffect`

### ISSUE THREAD

**Issue by spydon** [flame-engine/flame#1949]
# Interactive doc for the `MoveEffect`s

The three `MoveEffect`s should have small examples that show how the effect is applied and how it works. This could for example be just clicking somewhere in the game and moving a geometrical shape to the position where the reader clicked.

https://docs.flame-engine.org/1.3.0/flame/effects.html#movebyeffect
https://docs.flame-engine.org/1.3.0/flame/effects.html#movetoeffect
https://docs.flame-engine.org/1.3.0/flame/effects.html#movealongpatheffect

# What are interactive docs?

On our documentation site has the possibility to run inline interactive examples and we would like every visual feature to have a **small**, pretty and easily understandable example attached to it. Some current examples are the [router](https://docs.flame-engine.org/1.3.0/flame/router.html) and the [decorators](https://docs.flame-engine.org/1.3.0/flame/rendering/decorators.html).
Some inspiration can also be found on our [examples page](https://examples.flame-engine.org) where we have examples for most features.

# Good to know

Make sure that you comment on the issue that you will be working on this before starting to program.

To set up the Flame environment you need to follow the instructions in our [contributing.md](https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md#environment-setup) doc, if you have any problems setting up your environment (or other issues of course) feel free to ask for help in the Flame channel on our [Discord server](https://discord.com/invite/pxrBmy4).

Since this is a documentation change, you need to be able to build the docs. Instructions for building the documentation site locally can be found here: https://docs.flame-engine.org/main/development/documentation.html#building-documentation-locally

Make sure to include a video of the example when you upload the PR so that it will be easier for us to review it. (You can attach videos directly in the PR, so no need to upload them somewhere else)

**Happy hacking!**

**Comment by sccalabr** [comment]
id like to get this a try

**Comment by spydon** [comment]
> id like to get this a try

Great! You are assigned to the issue, please join our Discord server if you have any question. :)

**Comment by munsterlander** [comment]
I will gladly help out if needed.

**Comment by sccalabr** [comment]
I think everything looks ok but when build the docs the flower doesnt show up. Any ideas on why that would be happening 

https://github.com/flame-engine/flame/compare/main...sccalabr:flame:moveeffect?expand=1

**Comment by munsterlander** [comment]
Several things:

- Use the naming convention already established for file and class names.  `MoveToEffectGame` move_to_effect.dart, etc.
- The other sections use the factory: `MoveEffect.to` and not `MoveToEffect`.  
- You are creating the effect and applying it after when you will be better served to create the effect in the `onTap`.
- Reset the effect so users do not need to refresh the whole page to see what happens again.

As far as your flower not showing, I am not certain because that looks correct.  Do you see a warning when you build the docs?

**Comment by sccalabr** [comment]
is there a fast way to debug dart files the build clean and build takes forever

**Comment by munsterlander** [comment]
Just run main in web debugger and put your route name in the url like: `http://localhost:61757/?move_to_effect`

**Comment by munsterlander** [comment]
Here is a full working `move_to_effect.dart` file.  Compare to yours so you can see what is going on:

```dart
import 'package:doc_flame_examples/flower.dart';
import 'package:flame/effects.dart';
import 'package:flame/experimental.dart';
import 'package:flame/game.dart';

class MoveToEffectGame extends FlameGame with HasTappableComponents {
  bool reset = false;
  @override
  Future<void> onLoad() async {
    final flower = Flower(
      size: 60,
      position: canvasSize / 2,
      onTap: (flower) {
        if (reset = !reset) {
          flower.add(
            MoveEffect.to(
              Vector2(30, 30),
              EffectController(duration: 1.0),
            ),
          );
        } else {
          flower.add(
            MoveEffect.by(
              Vector2(size.x / 2, size.y / 2),
              EffectController(duration: 1.0),
            ),
          );
        }
      },
    );
    add(flower);
  }
}
```

**Comment by sccalabr** [comment]
Thanks I think I figured everything out. Let me know what you think.
