### ISSUE TITLE
Interactive docs: `ScaleEffect`

### ISSUE THREAD

**Issue by spydon** [flame-engine/flame#1951]
# Interactive doc for the `ScaleEffect`s

The two `ScaleEffect`s should have small examples that show how the effect is applied and how it works. This could for example be just clicking somewhere in the game and scaling a geometrical shape.

https://docs.flame-engine.org/1.3.0/flame/effects.html#scaleeffect-by
https://docs.flame-engine.org/1.3.0/flame/effects.html#scaleeffect-to

# What are interactive docs?

On our documentation site has the possibility to run inline interactive examples and we would like every visual feature to have a **small**, pretty and easily understandable example attached to it. Some current examples are the [router](https://docs.flame-engine.org/1.3.0/flame/router.html) and the [decorators](https://docs.flame-engine.org/1.3.0/flame/rendering/decorators.html).
Some inspiration can also be found on our [examples page](https://examples.flame-engine.org) where we have examples for most features.

# Good to know

Make sure that you comment on the issue that you will be working on this before starting to program.

To set up the Flame environment you need to follow the instructions in our [contributing.md](https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md#environment-setup) doc, if you have any problems setting up your environment (or other issues of course) feel free to ask for help in the Flame channel on our [Discord server](https://discord.com/invite/pxrBmy4).

Since this is a documentation change, you need to be able to build the docs. Instructions for building the documentation site locally can be found here: https://docs.flame-engine.org/main/development/documentation.html#building-documentation-locally

Make sure to include a video of the example when you upload the PR so that it will be easier for us to review it. (You can attach videos directly in the PR, so no need to upload them somewhere else)

**Happy hacking!**

**Comment by immadisairaj** [comment]
I would be interested in adding examples to ScaleEffect.

**Comment by erickzanardo** [comment]
Awesome @immadisairaj , assigned you to the issue :D

**Comment by munsterlander** [comment]
I will gladly help out if needed.

**Comment by immadisairaj** [comment]
> I will gladly help out if needed.

Thanks you @munsterlander. But, I have figured it out already :) (just didn't had time to send a PR)

By the way, I have a doubt @spydon. How do we reset the code again so that it can be interacted again? Or is it not needed?

**Comment by immadisairaj** [comment]
Yep, that can be done. Would be better. I think similar has to be done in the other examples also? (because if it is uniform it will be a good one)

Also, `ScaleEffect.to` in example contains `Vector2.zero()` maybe I have to change it a bit in documentation as well as interactive example? (as if the scale is down to zero, it won't be able to react)

**Comment by spydon** [comment]
> I have tried to add two effects (forward and reverse) @spydon. But, it gives me error when I try to click 3rd time. Maybe it is best to keep it the way it is for now?
> 
> Error:
> ```
> _parent == null
> "Instance of 'ScaleEffect' cannot be added to Instance of 'Flower' because it already has a parent:
> Instance of 'Flower'"
> ``` 
> PS: I get the same error if I try to remove the effect and add again

You have to do `changeParent` if you want to add and remove a component in the same tick (an effect is a component), but here you shouldn't need to. You should probably just create a new effect every time the user clicks instead (if an effect isn't already active).

**Comment by immadisairaj** [comment]
> just create a new effect every time the user clicks instead

Works perfectly fine if I create a new effect every time

**Comment by munsterlander** [comment]
I will update my prs to reset as well then.

**Comment by immadisairaj** [comment]
I have pushed a new commit with these changes in the PR. Please have a look at it @munsterlander.
