### ISSUE TITLE
Interactive docs: `SequenceEffect`

### ISSUE THREAD

**Issue by spydon** [flame-engine/flame#1954]
# Interactive doc for the `SequenceEffect`

The `SequenceEffect` should have small examples that show how the effect is applied and how it works. This could for example be just clicking somewhere in the game and applying a sequence of effects to a geometrical shape to the position.

https://docs.flame-engine.org/1.3.0/flame/effects.html#sequenceeffect

# What are interactive docs?

On our documentation site has the possibility to run inline interactive examples and we would like every visual feature to have a **small**, pretty and easily understandable example attached to it. Some current examples are the [router](https://docs.flame-engine.org/1.3.0/flame/router.html) and the [decorators](https://docs.flame-engine.org/1.3.0/flame/rendering/decorators.html).
Some inspiration can also be found on our [examples page](https://examples.flame-engine.org) where we have examples for most features.

# Good to know

Make sure that you comment on the issue that you will be working on this before starting to program.

To set up the Flame environment you need to follow the instructions in our [contributing.md](https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md#environment-setup) doc, if you have any problems setting up your environment (or other issues of course) feel free to ask for help in the Flame channel on our [Discord server](https://discord.com/invite/pxrBmy4).

Since this is a documentation change, you need to be able to build the docs. Instructions for building the documentation site locally can be found here: https://docs.flame-engine.org/main/development/documentation.html#building-documentation-locally

Make sure to include a video of the example when you upload the PR so that it will be easier for us to review it. (You can attach videos directly in the PR, so no need to upload them somewhere else)

**Happy hacking!**

**Comment by munsterlander** [comment]
This one is easy.  I will take it as well.
