### ISSUE TITLE
Add Component.removed

### ISSUE THREAD

**Issue by erickzanardo** [flame-engine/flame#1956]
# Problem to solve
We need a way to subscribe/listen for a component removal.

# Proposal
All Flame components already provide a `mounted` property that returns `Future` that is completed when the component is mounted on the tree.

We could follow this approach (both in concept and implementation) and implement an equivalent for a `removed` property.

**Comment by hey24sheep** [comment]
Dispose is unmount equivalent. Event's can be fired from overriden dispose to other subscribers.
```dart
 @override
  void dispose() {
    super.dispose();
  }
```

**Comment by ufrshubham** [comment]
> Dispose is unmount equivalent. Event's can be fired from overriden dispose to other subscribers.

It is not the same. One can hold a reference to unmounted component and mount it at a later point. Dispose is more like a destructor. Also, `Component` does not extent anything to override dispose from.

**Comment by hey24sheep** [comment]
I see, there is also ["unmount"](https://api.flutter.dev/flutter/widgets/StatefulElement/unmount.html). In my previous org, we used to dispose most component to save memory and make the app faster. So, I never looked into unmount. 

> Also, Component does not extent anything to override dispose from.

Could you give a file or line ref where this base abstract class resides. So, I can understand how mount and other stuff is working, I would really appreciate it. As, it is hacktober fest so I am looking to contribute.

**Comment by ufrshubham** [comment]
> I see, there is also ["unmount"](https://api.flutter.dev/flutter/widgets/StatefulElement/unmount.html). In my previous org, we used to dispose most component to save memory and make the app faster. So, I never looked into unmount.

Okay, just to make it clear, component in Flame's context means the `Component` class. It has nothing to do with Flutter widget and/or the state lifecycle events (maybe conceptually they do have some similarities).

> Could you give a file or line ref where this base abstract class resides. So, I can understand how mount and other stuff is working, I would really appreciate it. As, it is hacktober fest so I am looking to contribute.

Code for that class can be found [here](https://github.com/flame-engine/flame/blob/main/packages/flame/lib/src/components/core/component.dart). You should be able to get there using your IDE's go to definition feature. I'll also recommend taking a look at Flame's docs to get an idea of how components work in Flame.

**Comment by rivella50** [comment]
This feature can be used to detect if a relayout is necessary for the children of the planned components `ComponentRow` and `ComponentColumn`. #1944

**Comment by ufrshubham** [comment]
Hey @hey24sheep, can you confirm if you are working on this? If so @spydon or someone else can assign it to you.

**Comment by spydon** [comment]
I think this issue is up for grabs, hey24sheep most likely only tripped into this repo after I made a PR on one of their repos. :smile:

**Comment by hey24sheep** [comment]
@ufrshubham I apologize for delayed response, keep it open for anyone. As, I can see there is already a lot of progress farther than I can make as I still do not understand clearly the problem. I can see there is a base remove function and it is being used in the new PR of LayoutComponent. I think of `StreamBuilders` and `InheritedWidget` as that's what I have used in past to update parents about children and to maintain dynamic loading of child components. 

@spydon Yes, but, I contribute to Hacktoberfest and I see there are a lot of open issues with the same. So, thought of filling up my Hacktoberfest PR count 😄

**Comment by spydon** [comment]
> @spydon Yes, but, I contribute to Hacktoberfest and I see there are a lot of open issues with the same. So, thought of filling up my Hacktoberfest PR count 😄

Makes sense. :)
Components in Flame are not widgets, that's why `StreamBuilder` or `InheritedWidget` can't be used btw.

**Comment by ufrshubham** [comment]
If this issues is still free till October last week, I will take a look. Will drop a comment here when I do start working on it.

**Comment by spydon** [comment]
@JigneshWorld I can't assign you to this before you have commented on it. :)

**Comment by idlehart** [comment]
I can have a look at this unless JigneshWorld is on it already :)
