### ISSUE TITLE
Use Mermaid for diagrams 

### ISSUE THREAD

**Issue by spydon** [flame-engine/flame#1960]
# Diagrams as code by using Mermaid

Today we are having some static pictures for diagrams, like these ones:
https://docs.flame-engine.org/1.3.0/flame/components.html

These are hard to maintain and should therefore be replaced by a system that can generate diagrams from code. Preferably this system should be [Mermaid](https://mermaid-js.github.io/mermaid/#/), but if you know of another system that you'd think would fit better we are open for suggestions.

The default theme for mermaid is not very pretty so in this issue you also need to create a theme that fits in with the rest of the Flame docs color scheme.

# What are interactive docs?

On our documentation site has the possibility to run inline interactive examples and we would like every visual feature to have a **small**, pretty and easily understandable example attached to it. Some current examples are the [router](https://docs.flame-engine.org/1.3.0/flame/router.html) and the [decorators](https://docs.flame-engine.org/1.3.0/flame/rendering/decorators.html).
Some inspiration can also be found on our [examples page](https://examples.flame-engine.org) where we have examples for most features.

# Good to know

Make sure that you comment on the issue that you will be working on this before starting to program.

To set up the Flame environment you need to follow the instructions in our [contributing.md](https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md#environment-setup) doc, if you have any problems setting up your environment (or other issues of course) feel free to ask for help in the Flame channel on our [Discord server](https://discord.com/invite/pxrBmy4).

Since this is a documentation change, you need to be able to build the docs. Instructions for building the documentation site locally can be found here: https://docs.flame-engine.org/main/development/documentation.html#building-documentation-locally

Make sure to include a video of the example when you upload the PR so that it will be easier for us to review it. (You can attach videos directly in the PR, so no need to upload them somewhere else)

**Happy hacking!**

**Comment by st-pasha** [comment]
Instructions for building the documentation site on your computer: https://docs.flame-engine.org/1.3.0/development/documentation.html#building-documentation-locally

Also see [this comment](https://github.com/flame-engine/flame/issues/1503#issuecomment-1250144157) for how to add a mermaid diagram into the documentation. That comment also shows how to use the "dark" theme for the diagram, which works significantly better for our site than the default theme.

**Comment by dipakp2726** [comment]
Hi , i would like to work on this

**Comment by spydon** [comment]
> Hi , i would like to work on this

Super! Assigned you to the issue, make sure to join our Discord server if you have any questions. :)
