### ISSUE TITLE
Bridge package docs: `flame_rive`

### ISSUE THREAD

**Issue by spydon** [flame-engine/flame#1963]
# Bridge package docs for `flame_rive`

This bridge package should have its own documentation section on the docs site, similarly to `flame_audio` for example:
https://docs.flame-engine.org/main/flame_audio/flame_audio.html

For inspiration (and copy-pasting) you can have a look at the documentation for the package written in the `README.md` file and the documentation that the package is bridging too.

This PR should include an interactive code example to show a `RiveComponent` live in the docs.

# Good to know

Make sure that you comment on the issue that you will be working on this before starting to program.

To set up the Flame environment you need to follow the instructions in our [contributing.md](https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md#environment-setup) doc, if you have any problems setting up your environment (or other issues of course) feel free to ask for help in the Flame channel on our [Discord server](https://discord.com/invite/pxrBmy4).

Since this is a documentation change, you need to be able to build the docs. You can do that by running `melos sphinxdoc` after you have followed the instructions in the contributing.md doc and also [installed Sphinx on your system](https://www.sphinx-doc.org/en/master/usage/installation.html). After you have built the docs you can open the `doc/_build/html/index.html` file in your web browser to see the changes.

Make sure to include a video of the example when you upload the PR so that it will be easier for us to review it. (You can attach videos directly in the PR, so no need to upload them somewhere else)

**Happy hacking!**

**Comment by anilorcn** [comment]
I'm working on it.

**Comment by spydon** [comment]
> I'm working on it.

Super! Assigned you to the issue, make sure to join our Discord server if you have any questions. :)

**Comment by TheZal** [comment]
Is this still available? I can work on that!

**Comment by spydon** [comment]
@TheZal take one of them at the time, so start with `flame_svg` that I just assigned to you.

**Comment by TheZal** [comment]
ok!

**Comment by spydon** [comment]
Hi @anilorcn, any progress on this? If you don't plan to do this please let us know so that we can open up this issue for other people. :)

**Comment by dipakp2726** [comment]
i would be interested in working if available😀

**Comment by dipakp2726** [comment]
hello,
i am interested in working on it,

**Comment by spydon** [comment]
Hi @anilorcn, there is less than a week left of Hacktoberfest now, do you think that you'll be able to complete this issue in time? If not we'll open it up to other contributors.

**Comment by dipakp2726** [comment]
i am interested in working on it

**Comment by spydon** [comment]
Alright, since there hasn't been any reply for almost two weeks I'll assign it to you @dipakp2726
