### ISSUE TITLE
Bridge package docs: `flame_tiled`

### ISSUE THREAD

**Issue by spydon** [flame-engine/flame#1965]
# Bridge package docs for `flame_tiled`

This bridge package should have its own documentation section on the docs site, similarly to `flame_audio` for example:
https://docs.flame-engine.org/main/flame_audio/flame_audio.html

For inspiration (and copy-pasting) you can have a look at the documentation for the package written in the `README.md` file and the documentation that the package is bridging too.

# Good to know

Make sure that you comment on the issue that you will be working on this before starting to program.

To set up the Flame environment you need to follow the instructions in our [contributing.md](https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md#environment-setup) doc, if you have any problems setting up your environment (or other issues of course) feel free to ask for help in the Flame channel on our [Discord server](https://discord.com/invite/pxrBmy4).

Since this is a documentation change, you need to be able to build the docs. You can do that by running `melos sphinxdoc` after you have followed the instructions in the contributing.md doc and also [installed Sphinx on your system](https://www.sphinx-doc.org/en/master/usage/installation.html). After you have built the docs you can open the `doc/_build/html/index.html` file in your web browser to see the changes.

Make sure to include a video of the example when you upload the PR so that it will be easier for us to review it. (You can attach videos directly in the PR, so no need to upload them somewhere else)

**Happy hacking!**

**Comment by spydon** [comment]
@ufrshubham @jtmcdole maybe one of you already started this, or did I dream that? :sweat_smile:

**Comment by ufrshubham** [comment]
I haven't. I think it was @jtmcdole.

**Comment by jtmcdole** [comment]
We talked about doing it as a step - instead of a subsection.  good hackathon topic though

**Comment by spydon** [comment]
> We talked about doing it as a step - instead of a subsection. good hackathon topic though

What do you mean with "as a step"? 🤔

**Comment by jtmcdole** [comment]
> What do you mean with "as a step"? 🤔

I meant I shouldn't write comments at 5am 🤣 I was intending to say it was one of the steps to "make a new release" for tiled.  I wrote a sub-section for tile stacking and it was suggested there we write a whole new section.

**Comment by spydon** [comment]
Yeah, so we should both have more more docs in the `Other modules/tiled` and then also the new `flame_tiled` section that describes the bridge package, and that is what this issue is about. :)

**Comment by ufrshubham** [comment]
An additional things that should be done as part of this is updating the Getting Started section of Flame docs. In [`file structure section`](https://docs.flame-engine.org/main/flame/structure.html#structure), where it specifies that `assets/audio` and `assets/images` folders, we should also specify `assets/tiles`. It is the location where `TiledComponent` from `flame_tiled` looks for the map files.

**Comment by munsterlander** [comment]
So who is taking this one?

**Comment by spydon** [comment]
@munsterlander I'll assign it to you and you can do the basis, and then the rest of us can fill in with more PRs later.

**Comment by munsterlander** [comment]
@st-pasha Quasi related as I am re-working the docs, but about a year ago when you setup Sphinx's `conf.py` you included `summary.md` and @spydon has been maintaining and updating this as of 18 days ago.  My question though, what is the purpose of ignoring `summary.md`?  I can't find any other link to that document other than the conf.  Do we need to be updating that summary document with all files that are created or is it doing something else?

**Comment by st-pasha** [comment]
Oh.
So, originally we had the documentation as a simple directory of .md files on GitHub. And that `summary.md` served as a table of contents for all other files. At that point we were trying to set up a "real" documentation site -- but since we weren't sure whether it'd be reliable and how it was going to work, we wanted to keep things backward-compatible as much as possible. So we kept the `summary.md` file for that purpose. It still works too -- if you wanted to see how the documentation was back then -- go [here](https://github.com/flame-engine/flame/blob/main/doc/summary.md).

Ok, now that you're done laughing -- I think it's probably time to get rid of that file. It's not like anybody's updating it anyways.

**Comment by munsterlander** [comment]
I just wasn't sure what all was needed in it as it was missing items and I saw git blame for Spydon, but I realized later that this is from the build process and so no actual updates have been added.  I will remove this and the entry in the conf file in my docs redo branch.  Its getting massive, but its not unreviewable as most everything is spelling/grammar changes that grammarly picked up (which I guess the new spell checker in the pipeline would catch too - still very curious on that one).

**Comment by st-pasha** [comment]
The spelling errors should be fixed within the #2006 PR. But grammarly may also flag up some grammatical or sentence structure errors in addition.

**Comment by munsterlander** [comment]
Grammarly has definitely picked up a lot of small errors.  Lots of missing commas, incorrect word choice, i.e. `this components` should be `these components`, etc.  Its a wonderful free extension for VS Code.  None the less, the initial PR is fairly large, but its lots of little stuff.  Here is the re-org (I will remove the placeholders for the bridge packages unless those folks start submitting the pr's, then I will merge):

![image](https://user-images.githubusercontent.com/17042581/194724098-587dce02-d507-499f-b7e1-4e5422260a8e.png)
