### ISSUE TITLE
Unit tests for particles

### ISSUE THREAD

**Issue by spydon** [flame-engine/flame#1966]
# What could be improved

Currently the particles and the particle system barely has any tests, it would be good to improve the test coverage here.

# Why should this be improved

So that we don't accidentally break anything when doing changes.

# More information

https://github.com/flame-engine/flame/tree/main/packages/flame/lib/src/particles
https://github.com/flame-engine/flame/tree/main/packages/flame/test/particles

# Good to know

Make sure that you comment on the issue that you will be working on this before starting to program.

To set up the Flame environment you need to follow the instructions in our [contributing.md](https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md#environment-setup) doc, if you have any problems setting up your environment (or other issues of course) feel free to ask for help in the Flame channel on our [Discord server](https://discord.com/invite/pxrBmy4).

Read through this to see how we organize the tests in flame:
https://docs.flame-engine.org/1.4.0/development/testing_guide.html

**Comment by thisisamank** [comment]
Hi there, can I take this up?

**Comment by sshiv5768** [comment]
Hey, I want to work on this issue! Please assign me!

**Comment by spydon** [comment]
> Hey, I want to work on this issue! Please assign me!

Super! I've assigned you to the issue, remember to join our Discord server if you have any questions etc. :)

**Comment by sshiv5768** [comment]
Thanks @spydon for assigning me this issue.

**Comment by ShwetaChauhan18** [comment]
@sshiv5768: Let me know if you are not planning to complete this issue. I can start work ASAP.

**Comment by ShwetaChauhan18** [comment]
@spydon: Let me know if you have unit test, widget test task.

**Comment by spydon** [comment]
> @spydon: Let me know if you have unit test, widget test task.

I'll create a task for you, you have done great work so far! :)

**Comment by depimomo** [comment]
Hi @spydon ! I'm also interested if you have any unit test task, please let me know if you need more help 😆

**Comment by spydon** [comment]
Any progress here @sshiv5768? Otherwise I'll assign this to @ShwetaChauhan18.

**Comment by ShwetaChauhan18** [comment]
@sshiv5768 , @spydon: Can I start this?

**Comment by spydon** [comment]
> @sshiv5768 , @spydon: Can I start this?
> 

Since we've had no reply I've assigned it to you.
