### ISSUE TITLE
Unit tests for extensions

### ISSUE THREAD

**Issue by spydon** [flame-engine/flame#1968]
# What could be improved

Currently the extension methods aren't very well tested, it would be good to improve the test coverage here.

# Why should this be improved

So that we don't accidentally break anything when doing changes.

# More information

https://github.com/flame-engine/flame/tree/main/packages/flame/lib/src/extensions
https://github.com/flame-engine/flame/tree/main/packages/flame/test/extensions

# Good to know

You can run `melos coverage` to generate coverage files for Flame, just open `packages/flame/coverage/index.html` in your browser to see the results.

Make sure that you comment on the issue that you will be working on this before starting to program.

To set up the Flame environment you need to follow the instructions in our [contributing.md](https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md#environment-setup) doc, if you have any problems setting up your environment (or other issues of course) feel free to ask for help in the Flame channel on our [Discord server](https://discord.com/invite/pxrBmy4).

**Comment by quentin7b** [comment]
Hi there !

I'd like to work on this :)

**Comment by spydon** [comment]
> Hi there !
> 
> I'd like to work on this :) 

Super! Assigned you to the issue, make sure to join our Discord server if you have any questions. :)
