### ISSUE TITLE
Add Component.onChildrenChanged() lifecycle method

### ISSUE THREAD

**Issue by st-pasha** [flame-engine/flame#1973]
# Problem to solve

Currently a component has no way of knowing when it acquires new children or loses existing ones. Which is a shame really, because how it can take good care of its children if it doesn't know what happens to them?

# Proposal

Add a new lifecycle method `.onChildrenChanged()` which would fire whenever new children are added to the component, or existing children removed.

The method could have an argument `child`, which would indicate the component that caused the lifecycle event. If `child.parent == this` then the child was just added to the current component; otherwise it was removed.

# More information
This would be useful for #1944

**Comment by ufrshubham** [comment]
> Which is a shame really, because how it can take good care of its children if it doesn't know what happens to them?

Quite irresponsible parent they are 😅

**Comment by spydon** [comment]
@rivella50 have to tag you here to be able to assign you to the issue seemingly.

**Comment by rivella50** [comment]
@spydon Done
