### ISSUE TITLE
Problem with isomeric maps from Tiled app

### ISSUE THREAD

**Issue by PawelSzymanski89** [flame-engine/flame#1974]
# Current bug behaviour
<img width="1106" alt="Zrzut ekranu 2022-10-1 o 00 08 08" src="https://user-images.githubusercontent.com/26041449/193364323-c71f3464-bc9f-4b8b-a144-93ac275a3361.png">

# Expected behaviour
<img width="1109" alt="Zrzut ekranu 2022-10-1 o 00 06 39" src="https://user-images.githubusercontent.com/26041449/193364365-6d49ce7b-c284-45dc-b1df-9c11fdb4cbb5.png">
<img width="1082" alt="Zrzut ekranu 2022-10-1 o 00 07 54" src="https://user-images.githubusercontent.com/26041449/193364369-a87904f3-93b5-4274-9adf-561c28a2c5ac.png">

# Steps to reproduce
<img width="664" alt="Zrzut ekranu 2022-10-1 o 00 08 02" src="https://user-images.githubusercontent.com/26041449/193364402-ed86c45b-6c5e-428c-b0f7-bfd509c005f4.png">

# Flutter doctor output

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.6 21G115 darwin-x64, locale pl-PL)
    • Flutter version 3.0.5 at /Users/cygan/Documents/sdk/dart/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (3 months ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/cygan/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.3739.24

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-x64 • macOS 12.6 21G115 darwin-x64
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected and unlocked. (code -13)

[✓] HTTP Host Availability
    • All required HTTP hosts are available


```

# More environment information

**Comment by ufrshubham** [comment]
@PawelSzymanski89 support for isometric maps was added recently via https://github.com/flame-engine/flame/pull/1885
You might have to wait for next version of `flame_tiled` or you can depend on the `main` branch.

**Comment by spydon** [comment]
`flame_tiled` 1.8.0 is now released with isometric tile support.

**Comment by jtmcdole** [comment]
I love it when other people use the same tileset as me!

**Comment by PawelSzymanski89** [comment]
xd thanks all :) working now!
