### ISSUE TITLE
Fullscreen issue, status bar shrinks the screen size

### ISSUE THREAD

**Issue by Renkon117** [flame-engine/flame#198]
Hello, I am currently using this library and I am loving it! but I have some issue on Util()...
I am using the game class inside of the scaffold of home as a game widget.

For now it run
`Flame.Util().fullScreen();` 
to get screen size of the device, but at the same time, I want the screen to have status bar in the app. So, I am using 
`SystemChrome.setEnabledSystemUIOverlays(SystemUiOverlay.values);` 
as well.

If I have both method written inside the main(), it shrink the actual game screen, so gesture detector is not working properly. Like I have to tap one object a little upper of the actual position. So, the game size is shrunk with the same height as the status bar.

Please give me any suggestions.

**Comment by luanpotter** [comment]
> For now it run
> Flame.Util().fullScreen();
> to get screen size of the device, 

You can use `await Flame.util.initialDimensions();` to get the size of the screen.

The `Flame.util` namespace also has some other helpers for you to se full screen or not and the orientation desired :)

**Comment by Renkon117** [comment]
Thanks for the reply, it helped a lot
