### ISSUE TITLE
Unit tests for `AssetsCache`

### ISSUE THREAD

**Issue by spydon** [flame-engine/flame#1998]
# What could be improved

Currently the `AssetsCache` class doesn't have any tested, it would be good to improve the test coverage here. It is a lot simpler to write these tests than it sounds like, just have a look at how the tests for the other caches are written here:
https://github.com/flame-engine/flame/tree/main/packages/flame/test/cache

# Why should this be improved

So that we don't accidentally break anything when doing changes.

# Good to know

You can run `melos coverage` to generate coverage files for Flame, just open `packages/flame/coverage/index.html` in your browser to see the results.

Make sure that you comment on the issue that you will be working on this before starting to program.

To set up the Flame environment you need to follow the instructions in our [contributing.md](https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md#environment-setup) doc, if you have any problems setting up your environment (or other issues of course) feel free to ask for help in the Flame channel on our [Discord server](https://discord.com/invite/pxrBmy4).

**Comment by JigneshWorld** [comment]
Hi @spydon!

I'd like to work on this :)

**Comment by spydon** [comment]
> Hi @spydon!
> 
> I'd like to work on this :)
> 

Let me just verify that @ShwetaChauhan18 isn't already working on this since I recommended it to her.

**Comment by ShwetaChauhan18** [comment]
@spydon : I am taking this

**Comment by JigneshWorld** [comment]
Thanks @spydon @ShwetaChauhan18 🎉 

Let me know if any input I can add.
