### ISSUE TITLE
Drawing a Sprite more than once

### ISSUE THREAD

**Issue by lhk** [flame-engine/flame#200]
I have to draw the same object many times and would like to reuse a `Sprite` object.
To experiment, I've tried to reimplement bunnymark. But using `SpriteComponents` seems to mess up the positioning of sprites.
As soon as a `Sprite` object is rendered with a `SpriteComponent`, all subsequent calls to render lead to strange offsets.

Here is an example of the problem. I'm drawing three rows of rabbit sprites. In the first row I'm rendering the same `Sprite` object twice. Then I'm rendering a `Sprite`, a `SpriteComponent` (which relies on this `Sprite`) and then the `Sprite` again. In the third row are two `SpriteComponents` that seemingly shouldn't rely on the same `Sprite` object.
```
import 'dart:ui';

import 'package:flame/components/component.dart';
import 'package:flame/flame.dart';
import 'package:flame/game.dart';
import 'package:flame/position.dart';
import 'package:flame/sprite.dart';
import 'package:flutter/cupertino.dart';

class BunnyMark extends Game {
  Size screenSize;
  Sprite onlySprite;
  Sprite sharedWithComp;

  SpriteComponent compShared1;

  SpriteComponent compNotShared1;
  SpriteComponent compNotShared2;

  BunnyMark() {
    initialize();
  }

  void initialize() async {
    resize(await Flame.util.initialDimensions());

    // image used exclusively by this sprite
    onlySprite = Sprite('rabbitv3_tron.png');

    //  image shared between components
    sharedWithComp = Sprite('rabbitv3_batman.png');
    compShared1 = SpriteComponent.fromSprite(50, 50, sharedWithComp);

    // image loaded twice
    compNotShared1 =
        SpriteComponent.fromSprite(50, 50, Sprite('rabbitv3_wolverine.png'));
    compNotShared2 =
        SpriteComponent.fromSprite(50, 50, Sprite('rabbitv3_wolverine.png'));
  }

  void render(Canvas canvas) {
    // clear background
    Rect bgRect = Rect.fromLTWH(0, 0, screenSize.width, screenSize.height);
    Paint bgPaint = Paint();
    bgPaint.color = Color(0xff000000);
    canvas.drawRect(bgRect, bgPaint);

    // render same sprite twice -- ok
    onlySprite.renderPosition(canvas, Position(50, 50), size: Position(50, 50));
    onlySprite.renderPosition(canvas, Position(100, 50),
        size: Position(50, 50));

    // render sprite then component (so far ok), then sprite again (broken)
    sharedWithComp.renderPosition(canvas, Position(50, 150),
        size: Position(50, 50));
    compShared1.x = 100;
    compShared1.y = 150;
    compShared1.render(canvas);
    sharedWithComp.renderPosition(canvas, Position(150, 150),
        size: Position(50, 50));

    // render two components that don't share a sprite -- broken
    compNotShared1.x = 50;
    compNotShared1.y = 250;
    compNotShared1.render(canvas);
    compNotShared2.x = 100;
    compNotShared2.y = 250;
    compNotShared2.render(canvas);
  }

  void update(double t) {}
  void resize(Size size) {
    screenSize = size;
    super.resize(size);
  }
}

```

The output is this:

![image](https://user-images.githubusercontent.com/1475537/71722422-fe67b380-2e28-11ea-8860-9848797d2e53.png)

Is it possible to reuse `Sprite` objects with `SpriteComponents`? How can I use multiple `SpriteComponents` that rely on the same image?

As far as I understand from the discord chat, the components are supposed to be used in connection with BaseGame only. So I tried another approach:

```
class BunnyMark extends BaseGame {

//....
// in initialize
    add(compShared1);
    add(compNotShared1);
    add(compNotShared2);

// delete the component.render() calls from render()
```

Now the components are simply not drawn.

**Comment by erickzanardo** [comment]
Like I commented on discord, to use SpriteComponents, or other Components, you need to use `BaseGame`  class instead of `Game`, because most components, uses transformations on its render, and `BaseGame` is the one who manages that, that is why you are seeing that weird offset.

I am not sure why the components are not draw when using `BaseGame`, maybe you missed something, take a look on this example, here there are some SpriteComponents been rendered: https://github.com/flame-engine/flame/blob/master/doc/examples/spritesheet/lib/main.dart

Be  sure that if you overriden the  render/update methods from your base game, you must call super.

**Comment by erickzanardo** [comment]
If you need further help on this issue, feel free to add new comments.
