### ISSUE TITLE
Documentation: Minor improvements

### ISSUE THREAD

**Issue by ufrshubham** [flame-engine/flame#2002]
# What could be improved

1. Getting Started -> Installation -> Multiple links to latest version (https://docs.flame-engine.org/main/#installation)
2. `repository, It contains quite a` should be `repository. It contains quite a` or `repository, it contains quite a` (https://docs.flame-engine.org/main/#id1)
3. This section needs some rephrasing. Specifically the second sentence. It feels too lengthy and incorrect grammatically (https://docs.flame-engine.org/main/#outside-of-the-scope-of-the-engine)
4. In `Game Loop` section, fix typo in first sentence. (https://docs.flame-engine.org/main/flame/game.html#flamegame)
5. In `Lifecycle` section, the sentence `When a game first is added to a Flutter widget tree` should be `When a game is first added to a Flutter widget tree` (https://docs.flame-engine.org/main/flame/game.html#lifecycle)
6. In `Priority` section, there is no `or` part for `either` in the statement `To update the priority of a component you have to either just set it to a new value` (https://docs.flame-engine.org/main/flame/components.html#priority)

# Why should this be improved

Just some quality of life improvements.

# Good to know
Make sure that you comment on the issue that you will be working on this before starting to program.

To set up the Flame environment you need to follow the instructions in our [contributing.md](https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md#environment-setup) doc, if you have any problems setting up your environment (or other issues of course) feel free to ask for help in the Flame channel on our [Discord server](https://discord.com/invite/pxrBmy4).

Since this is a documentation change, you need to be able to build the docs. You can do that by running melos sphinxdoc after you have followed the instructions in the contributing.md doc and also [installed Sphinx on your system](https://www.sphinx-doc.org/en/master/usage/installation.html). After you have built the docs you can open the doc/_build/html/index.html file in your web browser to see the changes.

Make sure to include a video of the example when you upload the PR so that it will be easier for us to review it. (You can attach videos directly in the PR, so no need to upload them somewhere else)

**Happy hacking!**

**Comment by vikramadityasinghs** [comment]
hey, @spydon @ufrshubham could this issue be assigned to me?

**Comment by ayrotideysarkar** [comment]
Can you assign this to me I can do some rephrasing of the sentences and also omit the typos..

**Comment by spydon** [comment]
> Can you assign this to me I can do some rephrasing of the sentences and also omit the typos..

This is already taken by @vikramadityasinghs

**Comment by ayrotideysarkar** [comment]
Okay🥲

**Comment by Aatmaj-Zephyr** [comment]
is this fixed by @vikramadityasinghs yet or can I try to fix it?

**Comment by ayrotideysarkar** [comment]
I also want to try if it can still be assigned to me eagerly waiting

**Comment by ayrotideysarkar** [comment]
Is this still open?

**Comment by munsterlander** [comment]
They merged a few fixes. The major sections are still left.  I would opine that my other assignment will clash slightly with this, so be ready for merge conflicts.

**Comment by ayrotideysarkar** [comment]
I am also ready to take it... i don't have any other assignments in my hands right now, so if it is assigned to me I can try my best to solve issues..

**Comment by spydon** [comment]
This is already assigned to @vikramadityasinghs, let's not stress people. If you decide to not do it @vikramadityasinghs, please let us know. 🙂

**Comment by munsterlander** [comment]
> I don't think anything is fixed from this issue.

I just saw the merged so I thought a partial fix was implemented,  lol

**Comment by ayrotideysarkar** [comment]
Me too but I think it is still open😅

**Comment by ayrotideysarkar** [comment]
Any update? 😅

**Comment by vikramadityasinghs** [comment]
hey @spydon, im interested in working on this.
I'm starting work on this particular issue. 😀

**Comment by munsterlander** [comment]
This has been addressed in:  https://github.com/flame-engine/flame/pull/2063
