### ISSUE TITLE
Documentation: Forge2D joints

### ISSUE THREAD

**Issue by spydon** [flame-engine/flame#2005]
# What could be improved

All the different joint types in Forge2D should be explained and have examples, currently there is no pure `other moduler/forge2d` section so either create that section or put these docs under `flame_forge2d` meanwhile.

https://docs.flame-engine.org/main/flame_forge2d/forge2d.html

# Good to know
Make sure that you comment on the issue that you will be working on this before starting to program.

To set up the Flame environment you need to follow the instructions in our [contributing.md](https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md#environment-setup) doc, if you have any problems setting up your environment (or other issues of course) feel free to ask for help in the Flame channel on our [Discord server](https://discord.com/invite/pxrBmy4).

Since this is a documentation change, you need to be able to build the docs. You can do that by running melos sphinxdoc after you have followed the instructions in the contributing.md doc and also [installed Sphinx on your system](https://www.sphinx-doc.org/en/master/usage/installation.html). After you have built the docs you can open the doc/_build/html/index.html file in your web browser to see the changes.

Make sure to include a video of the example when you upload the PR so that it will be easier for us to review it. (You can attach videos directly in the PR, so no need to upload them somewhere else)

**Happy hacking!**

**Comment by AbhishekTiwari23** [comment]
Please assign to me

**Comment by spydon** [comment]
> Please assign to me

Super! I've assigned you to the issue, remember to join our Discord server if you have any questions etc. :)

**Comment by AbhishekTiwari23** [comment]
> > Please assign to me
> 
> Super! I've assigned you to the issue, remember to join our Discord server if you have any questions etc. :)

Thanks, @spydon, for assigning me. I will respond as soon as possible.

**Comment by spydon** [comment]
> > Hi @AbhishekTiwari23, any progress on this? If you don't plan to do this, please let us know so we can open up this issue for others. :)
> 
> I will make a pr by tomorrow. Actually, there is a fest going on, and I am getting less time for this, but surely I will do it.

Good to hear!

**Comment by spydon** [comment]
Hi @AbhishekTiwari23, there is less than a week left of Hacktoberfest now, do you think that you'll be able to complete this issue in time?

**Comment by munsterlander** [comment]
Less than 48 hours remaining.

**Comment by spydon** [comment]
Since we haven't had any response from the assignee, this is again up for grabs!

**Comment by eukleshnin** [comment]
@spydon Happy to pick it up

**Comment by spydon** [comment]
> @spydon Happy to pick it up

Cool! I'll assign you. Make sure to read our contribution guide before starting, if you haven't already. :)

**Comment by spydon** [comment]
I think most joints have docs and examples now.
