### ISSUE TITLE
Add `toString()` methods to Event objects

### ISSUE THREAD

**Issue by st-pasha** [flame-engine/flame#2007]
# What could be improved

The `Event` objects in `flame/lib/src/events/messages/` are pure data objects, and can benefit from having meaningful `toString()` representations.

# Why should this be improved

Occasionally users need to debug events, and in that case printing the event object into a console is the easiest. However, without a `toString()` method, the objects are printed as "Instance of <DragStartEvent>", which is nearly useless. A good `toString` method would also show the event coordinates, pointer id, etc.

# Any risks?

None, since `toString()` is used mostly for debugging.

**Comment by omjikush09** [comment]
@st-pasha   If I am understanding right then, I think I  have to add a method to base event class to convert its object to json string
like this  
  Map<String, dynamic> toJson() => {
        'handled': handled,
        'continuePropagationl': continuePropagation,
      };

**Comment by spydon** [comment]
There is no need to convert it to json, you just have to return a string that has a meaningful representation of the object.
See this one from the tutorial as an example:
https://github.com/flame-engine/flame/blob/main/doc/tutorials/klondike/app/lib/step4/components/card.dart#L31
Here the card should be represented as a string and that is done with:
```dart
  @override
  String toString() => rank.label + suit.label; // e.g. "Q♠" or "10♦"
```

So for this issue you have to create meaningful and consistent strings for the events.

**Comment by amoghrajesh** [comment]
@spydon @st-pasha is this issue still open. Would like to work on it

**Comment by himanshugarg08** [comment]
```dart
class DragStartEvent extends PositionEvent {
  DragStartEvent(this.pointerId, DragStartDetails details)
      : deviceKind = details.kind ?? PointerDeviceKind.unknown,
        super(
          canvasPosition: details.localPosition.toVector2(),
          devicePosition: details.globalPosition.toVector2(),
        );

  /// The unique identifier of the drag event.
  ///
  /// Subsequent [DragUpdateEvent] or [DragEndEvent] will carry the same pointer
  /// id. This allows distinguishing multiple drags that may occur at the same
  /// time on the same component.
  final int pointerId;

  final PointerDeviceKind deviceKind;

  /// Converts this event into the legacy [DragStartInfo] representation.
  DragStartInfo asInfo(FlameGame game) {
    return DragStartInfo.fromDetails(
      game,
      DragStartDetails(
        globalPosition: devicePosition.toOffset(),
        localPosition: canvasPosition.toOffset(),
        kind: deviceKind,
      ),
    );
  }

  @override
  String toString() =>
      'DragStartEvent(pointerId: $pointerId deviceKind: $deviceKind '
      'canvasPosition: $canvasPosition devicePosition: $devicePosition)';
}
```

If this is a good example of what needs to be done, I can also take this up :)

**Comment by spydon** [comment]
@amoghrajesh @himanshugarg08 this has already been handled by @sumit7577 (they forgot to write in here though, so I can't assign them).
