### ISSUE TITLE
Add scan distance input for raycast

### ISSUE THREAD

**Issue by ufrshubham** [flame-engine/flame#2011]
# Problem to solve

Current raycast API allows for ignoring hitboxes, but it does not allow limiting the hit scan distance for the cast. As a result users have to perform additional check on distance in their code.

Use case: Implementing an entity with ranged sight. For example, an enemy that can see objects within a certain range.

![image](https://user-images.githubusercontent.com/33748002/193758796-3b907860-0027-4187-b53f-7fd92f88a2df.png)
![image](https://user-images.githubusercontent.com/33748002/193758826-92208125-0dd0-46ef-bcdc-325b97b7ae3a.png)

# Proposal

Add an optional input to raycast using which users can specify the max distance for scanning ray hits.

# More information

I will work on this.

**Comment by spydon** [comment]
Haha, love the images!
