### ISSUE TITLE
Unit tests for event mixins

### ISSUE THREAD

**Issue by spydon** [flame-engine/flame#2017]
# What could be improved

Currently the event mixins are not tested at, it would be good to improve the test coverage here.

# Why should this be improved

So that we don't accidentally break anything when doing changes.

# More information

https://github.com/flame-engine/flame/tree/main/packages/flame/lib/src/events/component_mixins
https://github.com/flame-engine/flame/tree/main/packages/flame/lib/src/events/flame_game_mixins
https://github.com/flame-engine/flame/tree/main/packages/flame/lib/src/events/game_mixins

# Good to know

Make sure that you comment on the issue that you will be working on this before starting to program.

To set up the Flame environment you need to follow the instructions in our [contributing.md](https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md#environment-setup) doc, if you have any problems setting up your environment (or other issues of course) feel free to ask for help in the Flame channel on our [Discord server](https://discord.com/invite/pxrBmy4).

Read through this to see how we organize the tests in flame:
https://docs.flame-engine.org/1.4.0/development/testing_guide.html

**Comment by spydon** [comment]
@ShwetaChauhan18 here is an issue you can tackle!

**Comment by ShwetaChauhan18** [comment]
Ok, I am taking this

**Comment by ShwetaChauhan18** [comment]
@spydon : If you have any unit testing task then let me know

**Comment by spydon** [comment]
> @spydon : If you have any unit testing task then let me know

This one is open if you want to tackle that one:
https://github.com/flame-engine/flame/issues/2031
