### ISSUE TITLE
Unit tests for component mixins

### ISSUE THREAD

**Issue by spydon** [flame-engine/flame#2018]
# What could be improved

Currently the component mixins barely have any tests, it would be good to improve the test coverage here.

# Why should this be improved

So that we don't accidentally break anything when doing changes.

# More information

https://github.com/flame-engine/flame/tree/main/packages/flame/lib/src/components/mixins

# Good to know

Make sure that you comment on the issue that you will be working on this before starting to program.

To set up the Flame environment you need to follow the instructions in our [contributing.md](https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md#environment-setup) doc, if you have any problems setting up your environment (or other issues of course) feel free to ask for help in the Flame channel on our [Discord server](https://discord.com/invite/pxrBmy4).

Read through this to see how we organize the tests in flame:
https://docs.flame-engine.org/1.4.0/development/testing_guide.html

**Comment by dipakp2726** [comment]
Hi lukas,
i would like to work on it

**Comment by spydon** [comment]
> Hi lukas, i would like to work on it

Super! I've assigned you to the issue, remember to join our Discord server if you have any questions etc.

**Comment by dipakp2726** [comment]
i would love to take on more issues.
please let me know more @spydon
