### ISSUE TITLE
Unit tests for gesture detectors

### ISSUE THREAD

**Issue by spydon** [flame-engine/flame#2019]
# What could be improved

Currently the gesture detectors are not tested at, it would be good to improve the test coverage here.
The tests should be widget tests where mocked gesture input is used.

Do note that this issue is probably a bit more complicated than the other ones if you are not used to widget tests.

# Why should this be improved

So that we don't accidentally break anything when doing changes.

# More information

https://github.com/flame-engine/flame/tree/main/packages/flame/lib/src/gestures

# Good to know

Make sure that you comment on the issue that you will be working on this before starting to program.

To set up the Flame environment you need to follow the instructions in our [contributing.md](https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md#environment-setup) doc, if you have any problems setting up your environment (or other issues of course) feel free to ask for help in the Flame channel on our [Discord server](https://discord.com/invite/pxrBmy4).

Read through this to see how we organize the tests in flame:
https://docs.flame-engine.org/1.4.0/development/testing_guide.html

**Comment by ShrutiJ-01** [comment]
Hey @spydon , I'd like to take this up

**Comment by spydon** [comment]
> Hey @spydon , I'd like to take this up

Super! I've assigned you to the issue, remember to join our Discord server if you have any questions etc. :)

**Comment by dipakp2726** [comment]
hello @ShrutiJ-01, let me know if you are not working on it,

**Comment by dipakp2726** [comment]
hi @spydon ,
may be Assignee is inactive,
let me know if you can assign it to me

**Comment by ShrutiJ-01** [comment]
Hey @spydon , I am relatively new to writing unit tests, and after looking at the code I think it is a little too complex for me right now.I think it would be better if this issue was assigned to @dipakp2726 instead

**Comment by dipakp2726** [comment]
thank you @ShrutiJ-01 ,
