### ISSUE TITLE
Documentation:  Override MyST parser to allow external links to open in a new tab

### ISSUE THREAD

**Issue by munsterlander** [flame-engine/flame#2021]
# What could be improved

Currently in the help docs, any external link opens in the current window.  

# Why should this be improved

Allowing these links to open in new tabs means developers do not lose their point of reference in flame documentation for the issue they are working.

# Any risks?

This requires overriding the existing MyST htmltranslation parser and augmenting a method.

# More information

I will do the PR on this as I already have this tested and working.  Because it is a significant change, I do not want to lump it in with the other links PR.

**Comment by munsterlander** [comment]
I will take this if you all think this is smart to do.

**Comment by spydon** [comment]
Do we really need that, can't we use `<a href= target=` directly?

**Comment by st-pasha** [comment]
I believe it is actually recommended that links open in the same tab by default. For example see https://uxdesign.cc/linking-to-a-new-tab-vs-same-tab-f88b495d2187 or https://ux.stackexchange.com/questions/31579/when-if-ever-should-links-be-opened-in-a-new-window

**Comment by munsterlander** [comment]
> Do we really need that, can't we use `<a href= target=` directly?

You would think, but no.

**Comment by munsterlander** [comment]
> > I believe it is actually recommended that links open in the same tab by default. For example see https://uxdesign.cc/linking-to-a-new-tab-vs-same-tab-f88b495d2187 or https://ux.stackexchange.com/questions/31579/when-if-ever-should-links-be-opened-in-a-new-window
> 
> Makes sense, the user can open it in a new tab if they want to.

I guess, but it's annoying. Oh well.

**Comment by st-pasha** [comment]
> because the external link would be a tangential thought.

Not necessarily. If you click on "API docs", it would often be because you want to go and see the APIs.

**Comment by munsterlander** [comment]
> > because the external link would be a tangential thought.
> 
> Not necessarily. If you click on "API docs", it would often be because you want to go and see the APIs.

True.  My thought process though was because this isn't linked in an actual section but in the side bar, if I'm viewing say the SpriteAnimationComponent section of the help docs, I often like to look at the api docs and the examples too, so I can see the code and the available methods so I understand what the docs are saying.   This is no big deal, just thought it could provide benefit while I was working on it AND the fact of how hard it is to actually implement.   I mean it's just overriding one function in python, but wow, MyST really makes that buried.  Several github issues on it and several SO questions. 

Just to be clear, I'm not arguing. Just wanted to express my opinion, lol.
