### ISSUE TITLE
Documentation code blocks' "dart" position changes

### ISSUE THREAD

**Issue by immadisairaj** [flame-engine/flame#2025]
The flame documentation is good which contains code blocks that shows the code language also. But, there is a slight problem in it while scrolling the block horizontally. The language tag also moves along with it.

Maybe below screenshot will better explain.

# Current bug behaviour

![image](https://user-images.githubusercontent.com/40348358/194067493-e602effc-f30b-4ca3-b13e-d4a81629c167.jpeg)

# Expected behaviour

The language tag (dart here) should be fixed to the right side and shouldn't move.

# Steps to reproduce

Go to flame documentation page => https://docs.flame-engine.org/

And click on any section that contains code block, try to change width of window to be able to scroll. Then scroll the code block.

# Flutter doctor output

Not needed

# More environment information

Not needed

# Log information

Not needed

# More information

I will update here once I search for more information on this issue.

I am interested in working on a PR for this.

**Comment by munsterlander** [comment]
Its a bug, but we also have been changing these blocks to proper multi-lines so mobile users aren't scrolling.

**Comment by spydon** [comment]
Would be good to fix this anyways if it is possible, I fear it might be quite hard since it comes from Sphinx.

**Comment by spydon** [comment]
You should have written here and been assigned to the issue before you started it @lex111 (since @immadisairaj is already assigned to it), but what's done is done, maybe you can review it @immadisairaj?

**Comment by immadisairaj** [comment]
I was working on it and almost got to the end 😮‍💨 @spydon

I was checking the PR and have a simpler solution for it. The PR is a bit similar but I feel is overdone.

**Comment by spydon** [comment]
> I was working on it and almost got to the end 😮‍💨 @spydon @lex111 
> 
> I was checking the PR and have a simpler solution for it. The PR is a bit similar but I feel is overdone.

Then your PR will be prioritized of course. :)

**Comment by immadisairaj** [comment]
The below is a working screen recording of what I have done. Shall I proceed with PR @spydon?

https://user-images.githubusercontent.com/40348358/194288688-b966bbbe-0530-4944-99ac-07e4f2279ec4.mov

**Comment by spydon** [comment]
> The below is a working screen recording of what I have done. Shall I proceed with PR @spydon?
> 
> https://user-images.githubusercontent.com/40348358/194288688-b966bbbe-0530-4944-99ac-07e4f2279ec4.mov
> 
> 

Sure, lgtm!
