### ISSUE TITLE
Live Examples: Improvements

### ISSUE THREAD

**Issue by ufrshubham** [flame-engine/flame#2026]
# What could be improved

Flame has a lot of live examples along with their source code to help new users understand how Flame's APIs work. But here are some problem in those examples:

- Example stops responding to key inputs after visiting instructions panel or viewing source code:
  - Camera & Viewport->Follow Component
  - Collision Detection->QuadTree collision
  - Experimental->Follow and World bounds
  - Input->Keyboard
  - Input->Keyboard (Component)
  - System->Without FlameGame

- In `Audio->Basic Audio` audio does not stop playing after navigating to different example

# More information

- Button to open instructions panel and viewing source code can be found in the top right corner.
![image](https://user-images.githubusercontent.com/33748002/194086776-c9957d6a-1a01-4eb5-864d-7d80b56314f8.png)
- Link to Flame examples: https://examples.flame-engine.org/

**Comment by ufrshubham** [comment]
@ayrotideysarkar would be interested in working on this?

**Comment by ayrotideysarkar** [comment]
what needs to be done? can you tell me first? and how to do it?

**Comment by ayrotideysarkar** [comment]
Okay can you guide me so that i can do the work in here and can I chat with you in another platform ? it's getting lengthy and i don't wanna spam

**Comment by ayrotideysarkar** [comment]
and I want to work on this

**Comment by spydon** [comment]
> Okay can you guide me so that i can do the work in here and can I chat with you in another platform ? it's getting lengthy and i don't wanna spam

Join our discord server here: https://discord.com/invite/pxrbmy4

**Comment by ayrotideysarkar** [comment]
the discord link is expired

**Comment by ufrshubham** [comment]
> the discord link is expired

Use the one from [contributing](https://github.com/flame-engine/flame#contributing) section of the readme

**Comment by ayrotideysarkar** [comment]
@spydon is it fine if I submit a PR fixing only the broken links?

**Comment by spydon** [comment]
> @spydon is it fine if I submit a PR fixing only the broken links?

Hmm, it's a little bit too small task, but alright.

**Comment by ayrotideysarkar** [comment]
can you check discord little bit?

**Comment by spydon** [comment]
The rest of this issue is now open for someone else to tackle.

**Comment by munsterlander** [comment]
More than likely I can tackle this.  Give me a bit today to review please.

**Comment by munsterlander** [comment]
@erickzanardo Are you the focus specialist?

**Comment by spydon** [comment]
> @erickzanardo Are you the focus specialist?

I think @renancaraujo is even more a focus specialist.

**Comment by munsterlander** [comment]
@renancaraujo Looking for any help as to why the keyboard listener would stop after the popup is being shown.  An alternative would be, how do you trigger the keyboard listener to be rebound on an event?

**Comment by renancaraujo** [comment]
As far as I could test, this pr fixes this: https://github.com/flame-engine/flame/pull/1725

**Comment by munsterlander** [comment]
> As far as I could test, this pr fixes this: #1725

Thank you!

**Comment by munsterlander** [comment]
I was able to run everything and can confirm the prior PR fixes the keyboard focus problem.  This issue can be closed.
