### ISSUE TITLE
Lag/Jitter on iOS but not Android

### ISSUE THREAD

**Issue by willhlas** [flame-engine/flame#203]
I've made a game that runs smoothly on Android, but for some reason lags on iOS. I've tried just about everything to fix this but nothing seems to work!

Is anyone else is experiencing an issue with their game on iOS?

I've also opened the question at:
https://stackoverflow.com/questions/59695778/has-anyone-else-had-lag-on-ios-apps-games-built-using-flutter-and-flame

**Comment by luanpotter** [comment]
Please share a little bit of code or try to create a minimal reproducible example of the problem, otherwise we have no idea what the problem is...

**Comment by erickzanardo** [comment]
we have been testing our games on iOS for some time now, and it has always run very nice, you can check an example [here](https://apps.apple.com/br/app/bob-box/id1475025340).

In addition to @luanpotter said, it would help to know what resources are you using, Sprite, Animation, etc, and most important what device are you using for testing?
