### ISSUE TITLE
Unit tests for `flame_forge2d`

### ISSUE THREAD

**Issue by spydon** [flame-engine/flame#2031]
# What could be improved

Currently the bridge library `flame_forge2d` barely has any tests, it would be good to improve the test coverage here.

- The `BodyComponent` should be tested
- It should test that you can add children to the `BodyComponent`
- That those children move and rotate properly with their `BodyComponent` parent
- Tests for `Forge2DGame`
- Other things that you can come up with

# Why should this be improved

So that we don't accidentally break anything when doing changes.

# More information

https://github.com/flame-engine/flame/tree/main/packages/flame_forge2d

# Good to know

Make sure that you comment on the issue that you will be working on this before starting to program.

To set up the Flame environment you need to follow the instructions in our [contributing.md](https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md#environment-setup) doc, if you have any problems setting up your environment (or other issues of course) feel free to ask for help in the Flame channel on our [Discord server](https://discord.com/invite/pxrBmy4).

Read through this to see how we organize the tests in flame:
https://docs.flame-engine.org/1.4.0/development/testing_guide.html

**Comment by depimomo** [comment]
Okay, I'll give it a shot!

**Comment by dipakp2726** [comment]
hello,
i would like to work on it

**Comment by ShwetaChauhan18** [comment]
@dipakp2726: Let me know if you are not working on this.

@spydon: If @dipakp2726 is not going to complete then I will take this.

**Comment by spydon** [comment]
> hello, i would like to work on it

@dipakp2726 finish your current one first and then we can create some a new one for you. :)
