### ISSUE TITLE
Unit tests for `flame_rive`

### ISSUE THREAD

**Issue by spydon** [flame-engine/flame#2032]
# What could be improved

Currently the bridge library `flame_rive` barely has any tests, it would be good to improve the test coverage here.

- The `RiveComponent` should be tested
- The `RiveComponent` should move around and transform correctly
- It should test that you can add children to the `RiveComponent`
- Other things that you can come up with

# Why should this be improved

So that we don't accidentally break anything when doing changes.

# More information

https://github.com/flame-engine/flame/tree/main/packages/flame_rive

# Good to know

Make sure that you comment on the issue that you will be working on this before starting to program.

To set up the Flame environment you need to follow the instructions in our [contributing.md](https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md#environment-setup) doc, if you have any problems setting up your environment (or other issues of course) feel free to ask for help in the Flame channel on our [Discord server](https://discord.com/invite/pxrBmy4).

Read through this to see how we organize the tests in flame:
https://docs.flame-engine.org/1.4.0/development/testing_guide.html

**Comment by Anas35** [comment]
Hey, I would like to work on this issue.

**Comment by spydon** [comment]
Super! I've assigned you to the issue, remember to join our Discord server if you have any questions etc. :)
https://discord.gg/tREXPqMPnV
