### ISSUE TITLE
docs: Split the Components page

### ISSUE THREAD

**Issue by st-pasha** [flame-engine/flame#2037]
# What could be improved

Currently, the "Components" page (https://docs.flame-engine.org/1.4.0/flame/components.html) is very long, and becomes bigger and bigger with every new component added. It would be easier to read if each of these components got a separate page. The Components page itself would then only contain the links to pages for each of the components (perhaps grouped by subtopics), and some generic description of what the Flame Component System is.

**Comment by ufrshubham** [comment]
This is reported in #2003 as well

**Comment by munsterlander** [comment]
I'm reworking the docs right now. I will just take this on.

**Comment by munsterlander** [comment]
Are we against going to 3 levels in the table of contents?

**Comment by st-pasha** [comment]
> This is reported in https://github.com/flame-engine/flame/issues/2003 as well

Ah, right, I somehow missed that part. 

> Are we against going to 3 levels in the table of contents?

Not at all.
