### ISSUE TITLE
[flame_rive] null exception when no artboard with specified name is exists

### ISSUE THREAD

**Issue by Anas35** [flame-engine/flame#2043]
# Current bug behaviour
Throws Null Exception [Null Checks used on null value]

# Expected behaviour
Return null or throw new Exceptions?

# Steps to reproduce
In Rive Component's Example Code, change 
`final skillsArtboard = await loadArtboard(RiveFile.asset('assets/skills.riv'));` to
`final skillsArtboard = await loadArtboard(RiveFile.asset('assets/skills.riv'), artboardName: 'Not Exist')`;

# More information

**Do you have any other useful information about this bug report?**
This cause because of https://github.com/rive-app/rive-flutter/blob/6d229dcdd990ca20450c160f5877566e3b7095a0/lib/src/rive_file.dart#L298-#L302

**Are you interested in working on a PR for this?**
yep, but Not sure how to fix it. There are three soln I came up with,
- Make `loadArtboard()` return nullable Artboard which will be breaking.
- Throw Some Type of Exception when Artboard with that name does not exist (Drawback is: User can only know when there run the App)
- Return `mainArtboard` when Artboard with that name does not exist

**Comment by spydon** [comment]
I think Image.asset for example throws an exception when there is a non existent asset, we should do the same, if we aren't already doing that?

**Comment by st-pasha** [comment]
I think if the user passes a name for an artboard, they expect that artboard to exist. So, we should signal an error if it doesn't.

In this case I'd recommend to use a simple `assert()` that `artboardByName()` returned a non-null result. Thus, the only difference from the current behavior would be that the error message would be nicer and tell the user what exactly went wrong.

**Comment by spydon** [comment]
Agree that an asserr would be best here, to make it non-breaking.
