### ISSUE TITLE
docs:  Reorganize the help docs and implement standards throughout all the existing files

### ISSUE THREAD

**Issue by munsterlander** [flame-engine/flame#2045]
# What could be improved

The docs currently suffer from clear versions of additions.  Meaning, as they are today, you can tell which parts where added after each version and by different people.  The writing styles vary, file names vary, directory structure varies, etc.  Additionally, the `toctrees` vary across files and it causes a very weird caching issue with repeat builds.

# Why should this be improved

For the docs to grow and provide consistency, an agreed upon manner should be decided to provide a clear structure of documentation.  Google references the Kubernetes style guide as one of the best out there: https://kubernetes.io/docs/contribute/style/style-guide/.  While I don't think we need to go that far with spelling out every possible contribution, providing clearer guidance (there is some already) as well as applying that guidance to all existing files will benefit the documents for all new comers.

# Any risks?

None.

# More information

While I have been working on this and do have a branch ready to go, I am holding off on submitting a PR until everyone submits their hacktoberfest submissions.  Having said that, it may also benefit contributors if we implement this now, so there is a standard for their submissions especially for the bridge packages.

In my branch, I use the Grammarly extension and it already identified numerous files with spelling errors and basic grammar errors that have been missed and not identified in other issues.  So recommending that be a start for contributors as well.

**Comment by st-pasha** [comment]
Note: the "weird thing" with TOC caching is that if you update TOC in one file those changes won't be visible in every other file after a `make build`. I believe it's an intended behavior, not a bug, since it minimizes the rebuild time when prototyping.

In order to get all files updated, run `make clean` -- it will force rebuilding of all files.

**Comment by munsterlander** [comment]
So the weird caching thing I was referencing was actual how a few toctrees were rst and not myst.  They worked, but viewing the file would sometimes go crazy between refreshes and you would get warnings about missing files.  Once I converted them all to myst markdown, it disappeared.  It very well could be what you reference as well.  Either way, I felt that making them all the same through out the docs was the right approach.

**Comment by st-pasha** [comment]
`make html` should still work, as long as you're in the `doc/_sphinx` directory. But the equivalent of `make clean` would be `melos doc-clean`.

**Comment by munsterlander** [comment]
I guess I meant if you have not ran melos bootstrap (which I have now added to the docs for building the docs) first, when you run make html it throws errors as documented here: https://github.com/flame-engine/flame/issues/1950.  Is there any benefit and should we document which is preferred (after melos setup), `make html` or `melos doc-build`?

**Comment by st-pasha** [comment]
Either one works. The `melos doc-build` command has the advantage that you can run it from any directory in the flame repo. The `make html` can only be run from `doc/_sphinx`, but then its output is colorized, and wherever it prints %-progress statuses, those get overwritten correctly instead of spanning multiple lines. So, whatever you find more convenient.

Regarding the `CONTRIBUTING.md` -- I wonder if it might be a good idea to mirror it in the docs/development section. It could be just a simple include directive.

**Comment by munsterlander** [comment]
Absolutely can do on the including the `contributing.md`.  It is a bit lengthy and not all required for docs where in that section it was how to setup the local environment for building the docs, BUT because of the live examples, if you aren't running melos, then the builds fail and you get 404's and such, so it definitely is a requirement.

Having said that, because it is outside the `doc` directory, I don't know if it will be included in the build.  Currently, I have it with a relative link, but that fails because it never gets generated.  It might have to be a url OR I think there is a way in conf to include that specific file by using `include_patterns`?

**Comment by st-pasha** [comment]
It works fine (at least for the local builds). For docs-site build needs to be verified (and perhaps the publish script adjusted).

**Comment by munsterlander** [comment]
Well this is the warning that I get `WARNING: 'myst' reference target not found: ../../CONTRIBUTING.md#environment-setup` .  Can you not do relative links  in this method?  The linter and auto-complete shows everything correctly.

**Comment by st-pasha** [comment]
No, I don't think you could make a link like that.
I was suggesting rather to include the contributing file like
````
```{include} ../CONTRIBUTING.md
```
````
so that it becomes a proper file inside the doc-site, but the content of that file is fetched from an outside source.

**Comment by munsterlander** [comment]
Ok, I knew the include but I hadn't tried it because its so large.  I will play with that a bit more.

**Comment by munsterlander** [comment]
So I also want to bring to here some options that I had been discussing with Spydon in Discord.  

- I created a grouping called Bridge Packages but in the Flame readme, its referenced as Bridge Libraries. 
  - What is the preference?
- Flame Oxygen is listed under Other Modules in the docs currently, but is listed under Bridge Libraries in the readme.  
  -  Should it be with bridge_packages(libraries) in the docs or should the readme be updated?
- How do you feel about flame_splash_screen?
  - Is it a bridge_package or Other Module?

**Comment by munsterlander** [comment]
As mentioned here: https://github.com/flame-engine/flame/issues/2046 Do you want me to move spaceshooter under tutorials proper?

**Comment by spydon** [comment]
> As mentioned here: https://github.com/flame-engine/flame/issues/2046 Do you want me to move spaceshooter under tutorials proper?

That is up to @erickzanardo, personally I think it would be good so that all tutorials are gathered on the same place.

> Edit: Also while going through, I see that the bare flame game tutorial references the old version.  I believe we should use --VERSION-- for this as well, right? https://docs.flame-engine.org/1.4.0/tutorials/bare_flame_game.html

Yeah, that sounds good.
