### ISSUE TITLE
Platformer tutorial

### ISSUE THREAD

**Issue by spydon** [flame-engine/flame#2046]
# What could be improved
Currently we only have a card game tutorial, it would be great to include a tutorial (which is also starting from the basics) for a platformer game, since they are quite common and also uses pretty much all of Flame's features.

# Why should this be improved
To make is easier for new users to start with Flame.

# More information
The tutorial should live in the tutorial section of the docs
https://docs.flame-engine.org/1.4.0/tutorials/tutorials.html

**Comment by spydon** [comment]
@ufrshubham @munsterlander I was thinking of you two when I wrote this issue, is this maybe something that you two would like to team up on? :)

**Comment by spydon** [comment]
I'll add the `hacktoberfest-special` tag to this issue too, because it is quite a big undertaking.

![image](https://user-images.githubusercontent.com/744771/194702262-12cc5816-9c5c-4037-8536-7a279838b0cc.png)

**Comment by munsterlander** [comment]
I'm down if @ufrshubham is!

**Comment by Anikalp1** [comment]
I wanna work on this too.

**Comment by st-pasha** [comment]
@spydon Should we also move the space-shooter tutorial to the documentation site, and finish it? (Separate issue though)

**Comment by munsterlander** [comment]
What about pad racer in examples?

**Comment by spydon** [comment]
> What about pad racer in examples?

That one isn't a tutorial, it's just an example game so I think it fits pretty well on the examples page.

**Comment by spydon** [comment]
> @spydon Should we also move the space-shooter tutorial to the documentation site, and finish it? (Separate issue though)

I think it sounds like a pretty good plan, but what do you think @erickzanardo?

**Comment by spydon** [comment]
> I wanna work on this too.

Sorry, this one is already taken.

**Comment by munsterlander** [comment]
> > What about pad racer in examples?
> 
> That one isn't a tutorial, it's just an example game so I think it fits pretty well on the examples page.

Perfect.  Was just trying to see what all should be reorganized overall.

**Comment by ufrshubham** [comment]
> @ufrshubham @munsterlander I was thinking of you two when I wrote this issue, is this maybe something that you two would like to team up on? :)

Sorry, I'll have to pass. I already have my own simple platformer series, so this is a conflict of interest for me.

**Comment by munsterlander** [comment]
> > I wanna work on this too.
> 
> Sorry, this one is already taken.

You can assign me and I will do my best.

**Comment by Smartmind12** [comment]
> > > I wanna work on this too.
> > 
> > 
> > Sorry, this one is already taken.
> 
> You can assign me and I will do my best.

Hey @munsterlander can i assist you in this issue in place of @ufrshubham ??

**Comment by munsterlander** [comment]
@spydon Do you want this to use tiled or no?

**Comment by munsterlander** [comment]
@Smartmind12 Hit me up in discord.

**Comment by Smartmind12** [comment]
> @Smartmind12 Hit me up in discord.

Can you share me your discord ID??

**Comment by munsterlander** [comment]
Munsterlander in the flame discord.

**Comment by spydon** [comment]
> @spydon Do you want this to use tiled or no?  I'm thinking no to keep it simple unless you want this one to be a complex platformer.  I have an idea already and will write something up. 

Yeah I'm thinking that too, that pure Flame would be best for this one. :)

**Comment by erickzanardo** [comment]
> > @spydon Should we also move the space-shooter tutorial to the documentation site, and finish it? (Separate issue though)
> 
> I think it sounds like a pretty good plan, but what do you think @erickzanardo?

SGTM!

**Comment by munsterlander** [comment]
Ok, I can do this under the main doc reorg pr.  How does the subdomain for tutorials get dropped? Just simply moving the folder does it?

**Comment by spydon** [comment]
> Ok, I can do this under the main doc reorg pr.  How does the subdomain for tutorials get dropped? Just simply moving the folder does it? 

Better do that in a separate PR, it will be quite a lot of changes. We can sort out dropping the subdomain once everything is moved.

**Comment by munsterlander** [comment]
> > Ok, I can do this under the main doc reorg pr.  How does the subdomain for tutorials get dropped? Just simply moving the folder does it?
> 
> Better do that in a separate PR, it will be quite a lot of changes. We can sort out dropping the subdomain once everything is moved.

Will do.
