### ISSUE TITLE
Contributors on github

### ISSUE THREAD

**Issue by Aatmaj-Zephyr** [flame-engine/flame#2047]
Can you please add Contributors' images on GitHub readme?

**Comment by ufrshubham** [comment]
I feel it will make the readme unnecessarily bloated. Contributors are anyways listed under the `contributors` section on GitHub.

**Comment by munsterlander** [comment]
I mean, its there already and done automatically:

![image](https://user-images.githubusercontent.com/17042581/194723606-93709b43-9b89-42c1-a9c5-4e3d8d9b5a0a.png)

**Comment by spydon** [comment]
Agree, let's not bloat the readme.
