### ISSUE TITLE
OpacityEffect should allow using generic `paintId`

### ISSUE THREAD

**Issue by ufrshubham** [flame-engine/flame#2053]
# Problem to solve

- `OpacityEffect`s cannot be applied on components using HasPaint with custom `paintId`.
   If a component is using multiple paints, with a custom type for `paintId`, it is not possible to use opacity effect. This is because right now opacity effect supports only string type `paintId`.

- Single `OpacityEffect` cannot be applied to multiple paints easily.
  This is because `OpacityEffect` only accepts a single paintId.

# Proposal

- Add a generic type argument for OpacityEffect and use that type as `paintId`
- Convert single `paintId` into a list of id

# More information

I'll work on this.

**Comment by st-pasha** [comment]
Generally, we want OpacityEffect to be applicable in a broader context - so the best course of action would be to define an `OpacityProvider` interface (which would be implemented by HasPaint).

**Comment by ufrshubham** [comment]
> so the best course of action would be to define an `OpacityProvider` interface

I assume this is roughly what you have in your mind.

```dart
abstract class OpacityProvider<T extends Object> {
  double getOpacity(T id);
  void setOpacity(double value, T id);
}

mixin HasPaint<T extends Object> on Component implements OpacityProvider<T>{
  final Map<T, Paint> _paints = {};

  @override
  double getOpacity(T id) {
    return _paints[id].color.opacity;
  }

  @override
  void setOpacity(double value, T id) {
    _paints[id].color.opacity = value;
  }
}
```
I am right?

**Comment by st-pasha** [comment]
Rather,
```dart
abstract class OpacityProvider {
  double get opacity;
  set opacity(double value);
}
```

Then, if an object has multiple paints, then you can define multiple ways to set its opacity:
```
mixin HasPaint<T> on Component implements OpacityProvider {
  OpacityProvider opacityForPaint(T id) {...}
  OpacityProvider opacityForPaints(List<T> ids) {...}

  // The default OpacityProvider implementation would apply to all paints
  double get opacity => ...;
  set opacity(value) => ...;
}
```

The idea is that `OpacityEffect` should be applicable to components that don't use `HasPaint`. After all, `HasPaint` is pretty inefficient: it uses a map even for components that need a single paint. Also, there could be situations where you want a gradient color or something like that.

**Comment by ufrshubham** [comment]
Okay, but this approach will remove the ability to apply `OpacityEffect` to a specific paint from `HasPaint`. Logically this makes sense because each component should ideally have only one opacity. Just trying to confirm if this is what we are aiming for?
