### ISSUE TITLE
[flame_rive] functionality of `useArtboardSize` is missing

### ISSUE THREAD

**Issue by Anas35** [flame-engine/flame#2058]
On looking into the source code, `useArtboardSize` variable acts as an empty instance variable that does nothings.  

From rive-flutter source code,
https://github.com/rive-app/rive-flutter/blob/6d229dcdd990ca20450c160f5877566e3b7095a0/lib/src/rive.dart#L12-#L29

# Current bug behaviour
Does nothings

# Expected behaviour
Should do same as Rive?

# More information

**Comment by spydon** [comment]
Are you interested in taking on this one too?

**Comment by Anas35** [comment]
Hey @spydon, #2076 doesn't fixed it. The functionality of `useArtboardSize` is still missing.

**Comment by spydon** [comment]
> Hey @spydon, #2076 doesn't fixed this issue. The functionality of `useArtboardSize` is still missing.  

Aaah right, I'll open it up again

**Comment by sumit7577** [comment]
i want to work on this issue

**Comment by Anas35** [comment]
Feel free to work on this. I haven't quite yet gone into depth. This should have same features as this, https://github.com/rive-app/rive-flutter/blob/6d229dcdd990ca20450c160f5877566e3b7095a0/lib/src/rive.dart#L12-#L29

**Comment by sumit7577** [comment]
The artboard size doesn't change even if size is given in rive constructor so I assume i have to set the sizes according to user if useArtboardSize is true.

**Comment by spydon** [comment]
> The artboard size doesn't change even if size is given in rive constructor so I assume i have to set the sizes according to user if useArtboardSize is false. 

That is already fixed in #2076.

**Comment by sumit7577** [comment]
Any more info about this issue?

**Comment by Anas35** [comment]
You have to understand how `useArtboardSize` works in `rive-flutter` package first.  

The current behavior in `flame-rive`: Artboard's size is set up `size` property.

According to `flutter-rive` docs,
> when `false`, i.e. defaults to sizing based on the available
   constraints instead of the artboard size.

The current behaviour of `flame-rive`. i.e, Sizing should be based on `size` property.

> When `true`, the artboard size is constrained by the parent constraints.
    Using the artboard size has the benefit that the widget now has an

`size` property should be ignored, Artboard size should constrained by the parent constraints. Like this,
https://github.com/rive-app/rive-flutter/blob/6d229dcdd990ca20450c160f5877566e3b7095a0/lib/src/rive_render_box.dart#L84-#L85

IDK If this is the correct approach or I may have missed something.

**Comment by spydon** [comment]
Anyone that wants to pick this up? :)

**Comment by Anas35** [comment]
I will try and pick this up once again later this week. Will update here on any progress :)
