### ISSUE TITLE
docs: use `melos doc-serve` which replaces `melos doc-build-live`

### ISSUE THREAD

**Issue by immadisairaj** [flame-engine/flame#2075]
# Problem to solve

The command to build the documentation site (which serves) : `melos doc-build-live` doesn't exactly makes sense and a bit lengthy.

# Proposal

The proposed solution is that to use `melos doc-serve` command that replaces the `melos doc-build-live` command.

Making it as `serve` will make it on par with other site build commands and easier to remember.

Also, this issue addresses to update the documentation of `building documentation locally` section in docs. This removes the use of `make` in documentation and will use the `melos` workflow which can be static and non confusing to the contributors.

### Additional Things discussed:
As per the previous description, the addressed was to mainly solve the use of clean build when one is working for example on styling changes. This can be done using `melos doc-clean && melos doc-serve`.

If one wants to go deeper and use `make`. They can use them by going into `doc/_sphinx`. The `melos` is indirectly using `make` under the hood. So, it is mostly one's preference on what they use. The command that will work to do a clean build, after moving into the docs directory will be `make clean livehtml`. This command already works before the PR for this merges.

# More information
This could be achieved mostly by adding a new command into [`melos.yaml`](https://github.com/flame-engine/flame/blob/main/melos.yaml).

Mostly similar (a part of) to the PR which Lukas already send before #1970 

I am interested in working on this issue.

**Comment by immadisairaj** [comment]
This will need to add a documentation update of documentation which might conflict with #2063. But, it won't be that big of an issue.

**Comment by spydon** [comment]
What would be the reason for having two ways of serving the docs locally?

**Comment by st-pasha** [comment]
The `make clean` command deletes the `build` directory entirely (and then `make build` creates a new directory again); so if you were serving from that directory, then at least in MacOS the server will continue serving files from the deleted directory. Which is SUPER confusing, because what you see in the browser will be different from what you see in the file system.

Now, doing `doc-clean` is not particularly common, but occasionally it is necessary. For example when changing the stylesheet of the document, I usually have to restart the server (and even switch to a different port) in order for the new CSS file to get picked up by the browser. But I'm not sure whether the proposed solution with `doc-serve` will work in this case.

**Comment by spydon** [comment]
But you could just as well do `doc-clean` and then `doc-build-live` to get a server up and running with the docs?
Possibly we could rename `doc-build-live` to `doc-serve` and just document that it automatically updates once the files change?

**Comment by immadisairaj** [comment]
> But I'm not sure whether the proposed solution with `doc-serve` will work in this case.

You are correct @st-pasha. The new proposed command will not be able to solve this. We would have to use `doc-clean` again to build.

> But you could just as well do `doc-clean` and then `doc-build-live` to get a server up and running with the docs?

Yep, I could have done that. I hadn't got that idea 😬

> Possibly we could rename `doc-build-live` to `doc-serve` and just document that it automatically updates once the files change?

This can work. Please let me know if it's a go so that I can work up on this.

I have another one to propose after thinking and reading a bit. How about we combine both the commands into one?
Combining the clean + build + serve. Probably `doc-clean-serve` (or some other name)?
We could achieve this with `make` by using `make clean html` to build and to live build we can use `make clean livehtml`.

**Comment by spydon** [comment]
I think have too many commands for the docs will confuse people more than it will help them, and they might end up using the one that cleans everything out even though it is very rarely needed. When they need to clean everything out it's not hard to keep a line with `&&` and the existing Melos commands in their shell history.

**Comment by immadisairaj** [comment]
Yep, I understand. Now that I've found the `make clean livehtml`, I will be using this often probably or `melos doc-clean && melos doc-build-live`. We don't need to confuse with many commands. Please feel free to close this if no longer needed.

**Comment by ufrshubham** [comment]
> I think have too many commands for the docs will confuse people more than it will help them

Should we also remove all the `make` commands from docs? Having just the `melos` commands will make sure that all the contributors follow same workflow and setup `melos` properly.

**Comment by immadisairaj** [comment]
> Should we also remove all the `make` commands from docs?

Can I work on this? Or is it better for this to be included in the major docs redo PR by @munsterlander?

**Comment by spydon** [comment]
Do you want to sort that out @immadisairaj? I think we can rename the current `doc-live-build` to `doc-serve` instead too (and update the docs regarding that).

**Comment by spydon** [comment]
> > Should we also remove all the `make` commands from docs?
> 
> Can I work on this? Or is it better for this to be included in the major docs redo PR by @munsterlander?
> 
> 

Didn't see you comment before I posted mine, go ahead! Can you repurpose this issue to reflect what you'll do on the description and title? I'll assign you to it.

**Comment by immadisairaj** [comment]
> Do you want to sort that out @immadisairaj? I think we can rename the current `doc-live-build` to `doc-serve` instead too (and update the docs regarding that).

Sure thing. Then, I'll get working on it.

**Comment by munsterlander** [comment]
I had already removed make from the docs but you will need to update your section. Don't worry though, I will just resolve the conflicts.

**Comment by munsterlander** [comment]
@immadisairaj No problem resolving merge conflicts in my PR.  Thanks for making it super easy!
