### ISSUE TITLE
docs: Guideline Links Unavailable in CONTRIBUTING.md

### ISSUE THREAD

**Issue by SarojWasti** [flame-engine/flame#2088]
# What could be improved
The links for [Style Guide and Testing Writing Guide](https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md#how-to-contribute) in CONTRIBUTING.md are pointing towards default homepage of Flame instead of their own sections.

# Why should this be improved

Because it will be easier for everyone to visit the recommended section and follow guidelines for contributing.

# Any risks?

No

# More information

**Comment by spydon** [comment]
Thanks for notifying us, the fixed links should be up momentarily.
