### ISSUE TITLE
Fix all typos reported by cspell

### ISSUE THREAD

**Issue by spydon** [flame-engine/flame#2108]
# What could be improved

**Do note that only proficient native English speakers (or proof of proficiency by published articles or similar) will be considered for this ticket, otherwise there will be too much work for the reviewers.**

All reported errors by the spell checker should either be fixed or added to the [word list](https://github.com/flame-engine/flame/blob/main/.github/cspell.json#L5).

# Why should this be improved

To rid our repository of typos.

# More information

You can either run `cspell` locally or look at what it reports in [the pipeline](https://github.com/flame-engine/flame/actions/runs/3303657189/jobs/5451857009).

**Comment by munsterlander** [comment]
So oddly enough, I am just intrigued enough to and like misery enough to want to do this.  If no one else wants it, I can do it, but I would say let others have a chance and if its open in a few more days, I will take it.

**Comment by dipakp2726** [comment]
i am interested in working on it

**Comment by Dojeto** [comment]
I wanna work on this issue.

**Comment by spydon** [comment]
@dipakp2726 sorry, but this issue is only for really proficient English speakers (I've already had to correct both grammar and typos in your PRs). This PR will just be too massive for us to review if it is not somebody that is on a native (and skilled, some native speakers are terrible at their own language) level that takes on it.

@Dojeto are you a native English speaker and have some article or text published that we could have a look at?

**Comment by Dojeto** [comment]
I am not a native speaker, but just give me some time definitely my contribution will help you a lot.

**Comment by aryabyte21** [comment]
I am a native english speaker. I have written [an article on MLOps.](https://aryabyte.hashnode.dev/mlops-for-data-scientist)

**Comment by munsterlander** [comment]
I haven't read this but this may be able to use the files generated as well:  https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

I mention this because it seems there might be some config options that mean we do not have to add all the words exactly.

**Comment by spydon** [comment]
> I am a native English speaker. I have written [an article on MLOps.](https://aryabyte.hashnode.dev/mlops-for-data-scientist)

Perfect, I'll assign you @aryabyte21!
Tell us if you need help with anything and I recommend joining our discord server if you haven't already. :)

**Comment by mursalfk** [comment]
Hello.
I would also love to work on this issue. Can you assign it to me?

**Comment by spydon** [comment]
> Hello.
> I would also love to work on this issue. Can you assign it to me?

This is already assigned to @aryabyte21.

**Comment by Kritika30032002** [comment]
is this still available?

**Comment by spydon** [comment]
> is this still available?

Unfortunately not, there are already PRs open for it.

**Comment by Kritika30032002** [comment]
> > is this still available?
> 
> Unfortunately not, there are already PRs open for it.

But none of them is merged since it has been 4 days.
That's why I asked

**Comment by spydon** [comment]
> > > is this still available?
> > 
> > Unfortunately not, there are already PRs open for it.
> 
> But none of them is merged since it has been 4 days.
> That's why I asked

One of them has been merged, we're waiting for the author to fix up the other two so that it's all contained in one PR.
