### ISSUE TITLE
It looks like Flame'd logo is giving me the finger

### ISSUE THREAD

**Issue by felipebueno** [flame-engine/flame#211]
![image](https://user-images.githubusercontent.com/241271/73096368-660e9d00-3ec3-11ea-9c0b-68251d5676fc.png)

:smile:

**Comment by erickzanardo** [comment]
You sure have some imagination...

Either way I have been thinking on retiring the old and leaving only the new one, your thoughts @luanpotter ?

**Comment by luanpotter** [comment]
I actually like both, @erickzanardo . A nice small square image as logo has some good usages, for example, our favicon. Is it easy to randomize the flame a little bit to make it not look like a hand? (if it even does, I can see the point but it does require some imagination haha).

**Comment by felipebueno** [comment]
I agree that it does require a bit of imagination but it's the first thing that comes into my mind when I look at the logo and I can't unsee it. The same thing happened with Resident Evil 6's logo :smile:

**Comment by kingsleyh** [comment]
gosh now it's in my head too lol

**Comment by erickzanardo** [comment]
I am gonna close this, it does require a good amount of imagination to see that, and this issue open could influence people the wrong way. We will nevertheless try to change the logo a little bit.

**Comment by renancaraujo** [comment]
Updated the logo.
