### ISSUE TITLE
HasTappableComponents with FixedResolutionViewport appears register taps in the wrong place

### ISSUE THREAD

**Issue by duck-dev-go** [flame-engine/flame#2141]
# Current bug behaviour
Using HasTappableComponents with TapCallbacks gives strange results in a FixedResolutionViewport game. The router seems to render my component centered and then the tap seems to register on the place where it would be if my component wasn't centered. The image below shows where the tap registers with a red arrow.

![image](https://user-images.githubusercontent.com/15832303/199343301-0a07db68-6115-4ae8-9024-a1780790f0f5.png)

# Expected behaviour
I expect the tap to register on the red square.

# Steps to reproduce
```
import 'package:flame/components.dart';
import 'package:flame/experimental.dart';
import 'package:flame/game.dart';
import 'package:flutter/rendering.dart';

class TestGame extends FlameGame with HasTappableComponents {
  @override
  Future<void>? onLoad() async {
    camera.viewport = FixedResolutionViewport(
      Vector2(540, 960),
    );
    await add(
      RouterComponent(
        initialRoute: 'home',
        routes: {
          'home': Route(SceneComponent.new),
        },
      ),
    );
    return super.onLoad();
  }
}

class SceneComponent extends PositionComponent with HasGameRef<TestGame> {
  @override
  Future<void>? onLoad() async {
    size = gameRef.size;
    await add(
      TestComponent(
        position: Vector2(
          size.x * 0.5,
          size.y * 0.5,
        ),
        size: Vector2(100, 100),
        anchor: Anchor.center,
      ),
    );
    return super.onLoad();
  }

  @override
  void render(Canvas canvas) {
    canvas.drawRect(size.toRect(), Paint()..color = Color.fromARGB(255, 0, 255, 119));
    return super.render(canvas);
  }
}

class TestComponent extends PositionComponent with TapCallbacks {
  TestComponent({
    super.position,
    super.size,
    super.scale,
    super.angle,
    super.nativeAngle,
    super.anchor,
    super.children,
    super.priority,
  });

  @override
  void onTapDown(TapDownEvent event) {
    print('tap');
    super.onTapDown(event);
  }

  @override
  void render(Canvas canvas) {
    canvas.drawRect(
      size.toRect(),
      Paint()..color = Color.fromARGB(255, 255, 0, 0),
    );
  }
}
```

# More information
flutter: 3.3.3
flame: ^1.4.0

**Comment by GraysonE** [comment]
@duck-dev-go you beat me to it. I'm experiencing this as well. I have a FixedResolutionViewport of 800x360 and the tap is registering above the component, but not directly on the component.

**Comment by spydon** [comment]
Have you tried using the `CameraComponent` instead of the camera on FlameGame?

**Comment by GraysonE** [comment]
No sir. I'll give that a shot.

**Comment by klubxxl** [comment]
yep, the same issue

**Comment by klubxxl** [comment]
> No sir. I'll give that a shot.
> […](#)
> On Nov 2, 2022, 3:35 AM -0600, Lukas Klingsbo ***@***.***>, wrote: Have you tried using the CameraComponent instead of the camera on FlameGame? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

Have you tried?

**Comment by klubxxl** [comment]
> No sir. I'll give that a shot.
> […](#)
> On Nov 2, 2022, 3:35 AM -0600, Lukas Klingsbo ***@***.***>, wrote: Have you tried using the CameraComponent instead of the camera on FlameGame? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

Have you tried?

**Comment by GraysonE** [comment]
> > No sir. I'll give that a shot.
> > […](#)
> > On Nov 2, 2022, 3:35 AM -0600, Lukas Klingsbo _**@**_._**>, wrote: Have you tried using the CameraComponent instead of the camera on FlameGame? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.**_>
> 
> Have you tried?

I did and it works with the CameraComponent. It's quite the overhaul tho :/

**Comment by spydon** [comment]
> I did and it works with the CameraComponent. It's quite the overhaul tho :/

At least you will be future proof now since the `CameraComponent` is what will replace the built-in `Camera` class in `FlameGame`. There are also a lot of cool things you can do with the `CameraComponent` that you can't do with the normal `Camera`. :)

**Comment by spydon** [comment]
> Tbh, I too find the new camera APIs a little complex compared to existing ones. I hope there will be a migration guide for this going forward.

We should be able to have a game class that does most of it for you, like it is now with the old camera.
And if you have any specific pain points we're of course all ears!

**Comment by GraysonE** [comment]
I think some basic examples in the docs would really help.
