### ISSUE TITLE
HoverCallbacks mixin

### ISSUE THREAD

**Issue by duck-dev-go** [flame-engine/flame#2142]
# Problem to solve
When using the new flame router, hoverables seem to be still detected when you are on a different page. This can be a problem when for example you want to change the mouse cursor when hovering a component. The cursor will also change on the different page.

# Proposal
@spydon suggested in the discord channel

> The old event system is not aware of the router, so a HoverCallbacks mixin would have to be created

**Comment by spydon** [comment]
I'll create the needed mixins.

**Comment by spydon** [comment]
This needs to be created for V2, since `Hoverable` will be deprecated.

**Comment by garysm** [comment]
@spydon refer to one of my recent commits, 0f0db95f1f4b2461caf7ac181a80e0e12da77cd0.  Is `CursorHoverCallbacks` along the lines of what you're looking for to replace `Hoverable`?

**Comment by projectitis** [comment]
Watching 👀 
Thanks! 😄

**Comment by spydon** [comment]
Done by #2706
