### ISSUE TITLE
TextBoxComponent's boxConfig timePerChar generates "Optimized Out" error

### ISSUE THREAD

**Issue by gnarhard** [flame-engine/flame#2143]
# Current bug behaviour
When using the TextBoxComponent with a custom box config, having a fast timePerChar value generates this error:

> Unhandled Exception: 'dart:ui/painting.dart': Failed assertion: line 1681 pos 12: '<optimized out>': is not true.

# Steps to reproduce
```dart
static TextPaint textPaint = TextPaint(
    style: const TextStyle(
      height: 2,
      fontSize: 10,
      color: Colors.white70,
      letterSpacing: 2.0,
    ),
  );

  static TextBoxConfig textBoxConfig = TextBoxConfig(
    maxWidth: 400,
    timePerChar: 0.025, // timePerChar generates an optimized out painting assertion
    growingBox: false,
    margins: const EdgeInsets.only(left: 25, top: 25, bottom: 25),
  );
```

File attached for convenience.
[main.dart.zip](https://github.com/flame-engine/flame/files/9915601/main.dart.zip)

# More environment information

Create a list of more environment information, like:
* Flame version: 1.4.0
* Platform affected: android and ios. Haven't checked web or anywhere else.
* Platform version affected: Most recent versions of both android and ios as of writing this.

**Comment by spydon** [comment]
Interesting, so the assert that it fails on is this one:
```dart
    assert(!_disposed && !_image._disposed);
```

**Comment by fpv999** [comment]
same here with flame: ^1.6.0

**Comment by fpv999** [comment]
ok, my temporary solution was to clone text_box_component.dart and modify redraw() method from:

`
+  final Set<Image> cachedToRemove = {};
   Future<void> redraw() async {
     final newSize = _recomputeSize();
     final cachedImage = cache;
-    if (cachedImage != null) {
+    if (cachedImage != null && !cachedToRemove.contains(cachedImage)) {
+      cachedToRemove.add(cachedImage);
       // Do not dispose of the cached image immediately, since it may have been
       // sent into the rendering pipeline where it is still pending to be used.
       // See issue #1618 for details.
-      Future.delayed(const Duration(milliseconds: 200), () {
+      Future.delayed(const Duration(milliseconds: 100), () async {
+        cachedToRemove.remove(cachedImage);
+        cachedImage.dispose();
       });
     }
     cache = await _fullRenderAsImage(newSize);
`

**Comment by fpv999** [comment]
ok, my temporary solution was to clone text_box_component.dart and modify redraw() method like this:

```
+  final Set<Image> cachedToRemove = {};
   Future<void> redraw() async {
     final newSize = _recomputeSize();
     final cachedImage = cache;
-    if (cachedImage != null) {
+    if (cachedImage != null && !cachedToRemove.contains(cachedImage)) {
+      cachedToRemove.add(cachedImage);
       // Do not dispose of the cached image immediately, since it may have been
       // sent into the rendering pipeline where it is still pending to be used.
       // See issue #1618 for details.
-      Future.delayed(const Duration(milliseconds: 100), () {
+      Future.delayed(const Duration(milliseconds: 100), () async {
+        cachedToRemove.remove(cachedImage);
+        cachedImage.dispose();
       });
     }
     cache = await _fullRenderAsImage(newSize);

```

Error was happening because `cachedImage.dispose();` was called multiple times on the same object.

**Comment by spydon** [comment]
@fpv999 good catch, do you want to put up a PR with this fix?

**Comment by fpv999** [comment]
Yes, and no. I'm too busy at the moment.
