### ISSUE TITLE
TapDetector sometime not working when Flutter flame app embeded by ifame inside another website

### ISSUE THREAD

**Issue by khanhduy39nn** [flame-engine/flame#2156]
# Current bug behavior
All event onTapUp, onTapDown... are not working when I Flutter flame app (iframe) inside another website even though the drag event still works
Only happen on Android devices with chrome.
Frequency of error cases: 6/10

# Expected behavior
Tap event is good

# Steps to reproduce
1. Create a small app that counts the number of touches
2. flutter build web --web-renderer canvaskit
3. create a web server inside ./build/web
 I'am using http-server by command: http-server -p 5001
4. Create a html file like:
`<body><iframe src="http://localhost:5001"><body>
`

5. Test this html file on Chrome (android).

# Flutter doctor output

[✓] Flutter (Channel stable, 3.3.5, on macOS 13.0 22A380 darwin-arm, locale en-VN)
    • Flutter version 3.3.5 on channel stable at /Users/duynk/devlopment/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d9111f6402 (3 weeks ago), 2022-10-19 12:27:13 -0700
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/duynk/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more
      details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.0 22A380 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 106.0.5249.103

[✓] HTTP Host Availability
    • All required HTTP hosts are available

# More environment information

**Comment by spydon** [comment]
Do the taps work normally if you just use a tapdetector in Flutter web without Flame?

**Comment by spydon** [comment]
Any update on this @khanhduy39nn? Othwewise I'll close it as stale.
