### ISSUE TITLE
Add property to Route to allow the page to rebuild when the route is revisited

### ISSUE THREAD

**Issue by pastordougdev** [flame-engine/flame#2160]
When a Route is popped from the stack, its state is maintained by the Router.  Therefore, if the Route is pushed back onto the stack, the state of the Route's child Component is exactly where it was when the Route was popped.  There are some use cases where it would be beneficial for the Route's build method to be called each time the Route is pushed on the stack, thereby, rebuilding the Route's child Component.

As discussed on Discord (10/31/2022), the proposal is to add a boolean property to the Route component named pageTransient.  When true (by default), the current behavior remains where the state of the child Component is retained.  If pageTransient is set to false, the child Component of the Route will be rebuilt when the Route is pushed onto the stack again.

Please assign issue to me and I can submit the PR for this.

Thanks!!!!!

**Comment by spydon** [comment]
@st-pasha
