### ISSUE TITLE
[flame_audio] normalize simultaneously playing sounds

### ISSUE THREAD

**Issue by lukepighetti** [flame-engine/flame#2163]
Right now if you play multiple sounds simultaneously the audio volume will increase until the signal clips

I understand this is probably upstream in `audioplayers`, but I wanted to track it here since `flame_audio` specializes in low latency simultaneous playback

I'm not aware of what algorithms are used in video game audio engines to control this phenomenon, but it's absent in all modern video games to the best of my knowledge

**Comment by spydon** [comment]
Did you create an issue in the audioplayers package too?
We are maintaining that package too, if you didn't know.

**Comment by spydon** [comment]
Closing this since it has an open issue in AP.
