### ISSUE TITLE
Broken link to tutorials on front page of documentation

### ISSUE THREAD

**Issue by tim-taylor** [flame-engine/flame#2169]
# Current bug behavior
The link to the tutorials folder in the Getting Started section on the front page of the docs (at https://docs.flame-engine.org/1.4.0/ and https://github.com/flame-engine/flame/tree/main/doc) is broken

# Expected behavior
The link should (I think?) point to https://docs.flame-engine.org/1.4.0/tutorials/tutorials.html (or whichever version is appropriate) or https://github.com/flame-engine/flame/blob/main/doc/tutorials/tutorials.md. Instead it points to https://github.com/flame-engine/flame/tree/main/tutorials, which is a broken link

# Steps to reproduce
1. https://flame-engine.org/
2. Click on Docs in the top menu
3. Scroll down to the third subsection ("Getting started")
4. Click on the "tutorials folder" link
5. Link takes you to a 404 page

**Comment by munsterlander** [comment]
It should go to:  https://github.com/flame-engine/flame/tree/main/doc/tutorials

**Comment by spydon** [comment]
> It should go to:  https://github.com/flame-engine/flame/tree/main/doc/tutorials
> 
> I can knock out a pr real quick unless you just want to direct fix @spydon.  Let me know. 

Go for it, I'm in Kenya atm so not very active this week :)

**Comment by ufrshubham** [comment]
@munsterlander if possible, can you also update the link for this example: https://examples.flame-engine.org/#/FlameIsolate_Simple%20isolate%20example? 
Here is the correct link: https://github.com/flame-engine/flame/blob/main/examples/lib/stories/bridge_libraries/flame_isolate/simple_isolate_example.dart

**Comment by tim-taylor** [comment]
@munsterlander Thanks very much for taking this on. One extra related thing I just noticed: the index page of the tutorials at [https://github.com/flame-engine/flame/tree/main/doc/tutorials/tutorials.md](https://github.com/flame-engine/flame/tree/main/doc/tutorials/tutorials.md) starts with the sentence "This chapter contains only one tutorial for now, but we'll be adding more soon!", but it looks like there are now four tutorials there. This first sentence could be removed or updated, if you get the chance.

**Comment by munsterlander** [comment]
I will hit them all!

**Comment by munsterlander** [comment]
> https://examples.flame-engine.org/#/FlameIsolate_Simple%20isolate%20example

Where is the link to this?
