### ISSUE TITLE
Need a pushReplacementNamed and pushReplacement for `RouterComponent`

### ISSUE THREAD

**Issue by ufrshubham** [flame-engine/flame#2177]
# Problem to solve

As of now, there is no way to push and replace current route with a new one in a single call. It can be achieved using two separate pop() and push() calls, but only if there are more than 2 routes on the stack.

My use case involves an `OverlayRoute` as the initial route and a normal component based route. To navigate from the initial route to the component based one, I have to first pop() the initial route (because `OverlayRoute`s are always rendered on top). But in doing so, the `length > 1` assertion gets triggered.

# Proposal

It would be good to have `pushReplacementNamed` and `pushReplacement` style APIs for RouterComponent, similar to flutter's navigator.

# More information

**Comment by spydon** [comment]
Should I assign you to this @ufrshubham or do you want to take it @st-pasha?

**Comment by ufrshubham** [comment]
> Should I assign you to this @ufrshubham or do you want to take it @st-pasha?

I am completely new to the routing system, so it would be better if Pasha takes a look at this.

**Comment by munsterlander** [comment]
@spydon You can assign this to me.  I think I have it all done.
