### ISSUE TITLE
Any problem when develop a flutter game with flame and flare?

### ISSUE THREAD

**Issue by ggslayer** [flame-engine/flame#218]
I am new for game develop, And In my new project, I should develop a game with flutter, engine select flame, but some game characters have animation affect, So, I want to use flare make some animation, will this occur any problem?

**Comment by ggslayer** [comment]
than you, wait for your response...

**Comment by erickzanardo** [comment]
No problem should occur, you can take a look on the examples for flare on doc/examples for references.

Closing this, as this is not an issue, but if you have further questions feel free to add comments here.

**Comment by ggslayer** [comment]
thanks very much！
