### ISSUE TITLE
HudButtonComponent doesn't respond to taps

### ISSUE THREAD

**Issue by lukepighetti** [flame-engine/flame#2180]
I am not able to get this `HudButtonComponent` to respond to taps. Here is a reproduction:

```dart
import 'package:flutter/material.dart';
import 'package:flame/components.dart';
import 'package:flame/game.dart';
import 'package:flame/input.dart';

Future<void> main() async {
  runApp(MaterialApp(
    title: 'plt',
    theme: ThemeData.dark(),
    home: GameWidget.controlled(
      gameFactory: () => MyGame(),
    ),
  ));
}

class MyGame extends FlameGame with HasTappables, SingleGameInstance {
  MyGame() {
    this.camera.zoom = 40.0;
  }

  late final controller = MobileController();

  @override
  Future<void> onLoad() async {
    await add(controller);
    camera.followComponent(controller);
  }
}

class MobileController extends PositionComponent {
  late final button = HudButtonComponent(
    position: Vector2(1, -1),
    onPressed: () => print('onPressed'),
    onReleased: () => print('onReleased'),
    anchor: Anchor.bottomLeft,
    button: CircleComponent(
      radius: 1,
      paint: Paint()..color = Colors.green,
    ),
    buttonDown: CircleComponent(
      radius: 1,
      paint: Paint()..color = Colors.yellow,
    ),
  );

  @override
  Future<void>? onLoad() {
    add(button);
    return super.onLoad();
  }
}
```

I am tapping whenever I am hovering in this video

https://user-images.githubusercontent.com/666539/203455325-2ec84db9-ceb2-4692-87ad-2da531bf5a54.mov

**Comment by lukepighetti** [comment]
In fact, I can't even get this to paint at all.

<details>
```dart
import 'package:flutter/material.dart';
import 'package:flame/components.dart';
import 'package:flame/game.dart';
import 'package:flame/input.dart';

Future<void> main() async {
  runApp(MaterialApp(
    title: 'plt',
    theme: ThemeData.dark(),
    home: GameWidget.controlled(
      gameFactory: () => MyGame(),
    ),
  ));
}

class MyGame extends FlameGame with HasTappables, SingleGameInstance {
  MyGame() {
    this.camera.zoom = 40.0;
  }

  late final button = HudButtonComponent(
    onPressed: () => print('onPressed'),
    onReleased: () => print('onReleased'),
    button: CircleComponent(
      radius: 1,
      paint: Paint()..color = Colors.green,
    ),
    buttonDown: CircleComponent(
      radius: 1,
      paint: Paint()..color = Colors.yellow,
    ),
  );

  @override
  Future<void> onLoad() async {
    await add(button);
    camera.followComponent(button);
  }
}
```
</details>

**Comment by munsterlander** [comment]
Is there a reason your are not using the `Tappable` mixin for class `MobileController`?

**Comment by spydon** [comment]
The `HudMarginComponent` needs to be added in the root if I'm not mistaken. It also doesn't work with `CameraConponent`, but it doesn't seem like you are using that.

**Comment by munsterlander** [comment]
> The `HudMarginComponent` needs to be added in the root (as a child directly to the game) if I'm not mistaken. It also doesn't work with `CameraConponent`, but it doesn't seem like you are using that.

Wrong issue I think?

**Comment by spydon** [comment]
> > The `HudMarginComponent` needs to be added in the root (as a child directly to the game) if I'm not mistaken. It also doesn't work with `CameraConponent`, but it doesn't seem like you are using that.
> 
> Wrong issue I think? Did you mean this for #2181?

No, correct issue, since he wraps the `HudButtonComponent` in the `MobileController` here. Wrote the wrong component though.

**Comment by lukepighetti** [comment]
> Is there a reason your are not using the `Tappable` mixin for class `MobileController`?

MobileController is intended to be a group of HUDButtonComponents. Not to handle gestures itself.

> The `HudButtonComponent` needs to be added in the root (as a child directly to the game) if I'm not mistaken.

I considered making this a "cannot group HudButtonComponents in another component" issue but wasn't sure if that was the case

**Comment by spydon** [comment]
> I considered making this a "cannot group HudButtonComponents in another component" issue but wasn't sure if that was the case

Fairly sure that is the case, but try. You don't have to create an issue for it since HudButtonComponent will be going away with the new camera system.

**Comment by spydon** [comment]
Ah it is mentioned on `positionType` in the docs, so not that easy to find:
https://docs.flame-engine.org/main/flame/components.html#positiontype

> Do note that this setting is only respected if the component is added directly to the root FlameGame and not as a child component of another component.

**Comment by aytunch** [comment]
This problem continues and can be seen in the examples as well;
https://examples.flame-engine.org/#/Input_Joystick%20Advanced
Try to press any of the 5 buttons quickly and you will see they sometimes disappear. And sometimes the `onPressed` don't work(especially on macOS and iOS)

**Comment by spydon** [comment]
> This problem continues and can be seen in the examples as well; https://examples.flame-engine.org/#/Input_Joystick%20Advanced Try to press any of the 5 buttons quickly and you will see they sometimes disappear. And sometimes the `onPressed` don't work(especially on macOS and iOS)

I can't replicate this, are you sure that you aren't on a cached version of the examples page? Try running it in incognito mode.
