### ISSUE TITLE
HudMarginComponent is not resilient to extra margin parameters

### ISSUE THREAD

**Issue by lukepighetti** [flame-engine/flame#2181]
This works to position something in the bottom right

```dart
await add(
  HudMarginComponent(
    children: [primaryButton2],
    margin: EdgeInsets.only(bottom: 25, right: 25),
    anchor: Anchor.bottomRight,
  ),
);
```
<img width="724" alt="Screen Shot 2022-11-23 at 7 23 37 AM" src="https://user-images.githubusercontent.com/666539/203546115-5c7b1133-1022-470c-bb69-7281836a8a9b.png">

This changes the viewport anchor to top left and positions 25 pixels from the top left of that anchor 
```dart
await add(
  HudMarginComponent(
    children: [primaryButton2],
    margin: EdgeInsets.all(25),
    anchor: Anchor.bottomRight,
  ),
);
```

<img width="724" alt="Screen Shot 2022-11-23 at 7 23 48 AM" src="https://user-images.githubusercontent.com/666539/203546140-96f7b1e9-b8bc-4805-b555-65b292f9bac3.png">

**Comment by spydon** [comment]
Have you checked what position that it ends up at? It probably paints, but not visibly.

**Comment by lukepighetti** [comment]
Looks like it's painting out 25 pixels from the top left of the screen to the bottom right of the component

instead of 25 pixels from the bottom right of the screen to the bottom right of the component

**Comment by lukepighetti** [comment]
I think this may be a fundamental misunderstanding on my part about what anchor does, going to close this.
