### ISSUE TITLE
Add Component.onUnload() so components can dispose native resources

### ISSUE THREAD

**Issue by badlogic** [flame-engine/flame#2184]
# What could be improved
`Component` offers to override `Component.onLoad()`, a method called exactly once throughout the life-time of the component, used to load any resources required by the component.

I propose a corresponding `Component.onUnload()`, a method called exactly once at the end of the life-time of the component, after it is no longer in the scene tree.

# Why should this be improved
When loading native resources in `Component.onLoad()`, there is no way to properly release the native resource using the life-cycle callbacks of `Component`. Instead, the component must expose a method that lets its user manually dispose of the native resource, e.g. in `FlameGame.onDetach()`. A simple example:

```dart
class SimpleFlameExample extends FlameGame {
  late final SpineComponent spineboy;

  @override
  Future<void> onLoad() async {
    // Load the Spineboy atlas and skeleton data from asset files
    // and create a SpineComponent from them, scaled down and
    // centered on the screen
    spineboy = await SpineComponent.fromAssets(
        "assets/spineboy.atlas", "assets/spineboy-pro.skel",
        scale: Vector2(0.4, 0.4),
        anchor: Anchor.center,
        position: Vector2(size.x / 2, size.y / 2)
    );

    // Set the "walk" animation on track 0 in looping mode
    spineboy.animationState.setAnimationByName(0, "walk", true);
    await add(spineboy);
  }

  @override
  void onDetach() {
    // Dispose the native resources that have been loaded for spineboy.
    spineboy.dispose();
  }
}
```

The static method `SpineComponent.fromAssets()` asynchronously loads a handful of native resources from which it constructs a `SpineComponent` instance. These native resources need to be disposed once the component is at the end of its life-cycle. Currently, end users of the component have to do this manually by overriding `FlameGame.onDetach()`, as this is the only place in the API, where it is guaranteed that the component is no longer visible (and thus won't access its native resources) and likely at the end of its life-cycle.

Note that doing this in `Component.onRemove()` is not an option, as the component can still be re-inserted into the scene at a later point.

# Any risks?
From my non-expert understanding of the Flame API, add a `Component.onUnload()` method should not pose any risk to existing code.

There may be some risk in how unloading of components is implemented, i.e. it must be guaranteed, that the component can no longer be re-inserted into the scene tree after `Component.onUnload()` was called.

# More information
An executable example relying on manual disposal can be found here:
https://github.com/EsotericSoftware/spine-runtimes/blob/4.2-beta/spine-flutter/example/lib/flame_example.dart#L104

Note how cumbersome and error prone this is. If an end user forgets to dispose the `SpineComponent`, the underlying native memory will never be freed, leading to a memory leak.

**Comment by spydon** [comment]
It sounds like a good idea, but I don't know where we could trigger such a call.
It can't be called from `onDetach`, because the game can be attached again after it has been detached.

**Comment by badlogic** [comment]
I had an hour to look through Flame's internals, and I too see that there's no place where this could actually be done. I'm closing this issue out so it doesn't clog up your tracker. I guess I'll try my luck with unreliable GC finalizers.

**Comment by spydon** [comment]
> I had an hour to look through Flame's internals, and I too see that there's no place where this could actually be done. I'm closing this issue out so it doesn't clog up your tracker. I guess I'll try my luck with unreliable GC finalizers.

Or just document that the user manually has to call dispose when the component won't be used anymore?
It's the same with the `Image` object in Flutter too.
