### ISSUE TITLE
Because examples depends on trex_game any which doesn't exist (could not find package trex_game at https://pub.flutter-io.cn), version solving failed.

### ISSUE THREAD

**Issue by wengxianxun** [flame-engine/flame#2188]
<img width="1352" alt="image" src="https://user-images.githubusercontent.com/831898/203877182-ee19b7cc-52c2-40c4-bbb9-c0b177658f65.png">

**Comment by munsterlander** [comment]
Did you bootstrap the repo with melos?

**Comment by spydon** [comment]
Closing this since it's most definitely `melos bootstrap` missing. Remember that you can see all examples running at https://examples.flame-engine.org too.
