### ISSUE TITLE
about flare'controller mechanism

### ISSUE THREAD

**Issue by ggslayer** [flame-engine/flame#219]
Hi, I saw the "flare" example, now I wan't to play audio when the flare animation reach some keyframe, In the flare runtime, there is a parameter "controller" where I can call the api: triggerEvent to test if there is a event, but in the flame's FlareAnimation class, I can't find any interface where i can do that.    Is this not support or something else i missed?

if there is no such mechanism to do that, is there any recommend for my propose (play sound when the flare's keyfame reach )?

Waiting for your reply, thanks very much!

**Comment by erickzanardo** [comment]
At the moment, there is no way to pass a controller to FlareAnimation or FlareComponent, this could be an improvement on Flame support of Flare.

In the meantime, the only way I can think on doing that, would be playing the sound on a time event, and kind of sincronize it with your animation, try checking this https://github.com/flame-engine/flame/blob/master/doc/util.md#timer

**Comment by ggslayer** [comment]
Thanks!~  Because it is very importort for me,  so, I can wait,  Can you add this to your schdule?

**Comment by luanpotter** [comment]
@ggslayer feel free to contribute with a PR, that would be a great feature!

**Comment by erickzanardo** [comment]
@renancaraujo want do assign this to yourself? I know you are messing around with this.

**Comment by renancaraujo** [comment]
YAS!

**Comment by erickzanardo** [comment]
This will be solved by https://github.com/flame-engine/flame-flare/pull/2

**Comment by erickzanardo** [comment]
This is available on the `flame_flare` package. Closing this.
