### ISSUE TITLE
ButtonComponent doesn't handle onTapCancel

### ISSUE THREAD

**Issue by lukepighetti** [flame-engine/flame#2191]
If you create a `ButtonComponent`, press down, then drag your finger off the button, `onReleased` is not called. This leaves consuming code in an incorrect state where it still thinks the button is pressed when it's not.

I think we should either call `onReleased` or add an `onCancel` callback to `ButtonComponent`

**Comment by spydon** [comment]
Sounds like `onCancel` should be called when that happens.

**Comment by lukepighetti** [comment]
I don't believe that member exists, I wasn't able to find it.

<img width="562" alt="Screen Shot 2022-11-26 at 8 05 04 AM" src="https://user-images.githubusercontent.com/666539/204090426-7ca43cd2-9ab7-4e5e-9c69-c793f495548a.png">

**Comment by spydon** [comment]
Yeah, I mean that it should be added. :)

**Comment by spydon** [comment]
Fixed by #2193
