### ISSUE TITLE
the document is outdoutdated

### ISSUE THREAD

**Issue by whyming** [flame-engine/flame#2195]
# Current bug behavior

# Expected behavior

# Steps to reproduce

# Flutter doctor output

```
Output of: flutter doctor -v
```

# More environment information

# Log information

```
Enter log information in this code block
```

# More information

**Comment by ufrshubham** [comment]
@whyming can you provide more information about which document you are talking?

**Comment by spydon** [comment]
Closing this since it doesn't specify what is outdated.
