### ISSUE TITLE
FlameAudio.audioCache.loadAll

### ISSUE THREAD

**Issue by dd9913762113** [flame-engine/flame#2212]
FlameAudio.audioCache.loadAll 

 static AudioCache audioCache = AudioCache(prefix: 'assets/audio/');

may i change audioCache path? 
like  
 'assets/audio1/'  
 'assets/audio2/'  
 'assets/audio3/'
i had many audios  for many folders

**Comment by dd9913762113** [comment]
> You can, but why don't you just have those folders inside of `audio`?

How to do ? 

because i had many different kind of audios 
Wouldn't it be better if we put it in a different kind of path

assets/audio/audio1
assets/audio/audio2
assets/audio/audio3

**Comment by ufrshubham** [comment]
> > You can, but why don't you just have those folders inside of `audio`?
> 
> How to do ?
> 
> because i had many different kind of audios Wouldn't it be better if we put it in a different kind of path
> 
> assets/audio/audio1/ assets/audio/audio2/ assets/audio/audio3/

You can actually put audio files in different paths. You will just have to specify the relative path from `assets/audio/` while loading those files. For example, if you have a structure like this:

```bash
assets
└─ audio
   ├── bgm
   │   ├── bgm1.mp3
   │   ├── bgm2.mp3
   │   └── bgm3.mp3
   └── sfx
       ├── sfx1.mp3
       ├── sfx2.mp3
       └── sfx3.mp3
```

then your loadAll call would look something like this:
```dart
audio.loadAll(['bgm/bgm1.mp3', 'bgm/bgm2.mp3', 'bgm/bgm3.mp3', 'sfx/sfx1.mp3', 'sfx/sfx2.mp3', 'sfx/sfx3.mp3']);
```

**Comment by spydon** [comment]
If you really want to change the path that the `AudioCache` is looking at, which I expect you don't, you can just set a new `audioCache` in `FlameAudio` with a new `prefix`.
```dart
FlameAudio.audioCache = AudioCache(prefix: 'assets/');
```

I would recommend going with @ufrshubham's solution though.

**Comment by dd9913762113** [comment]
Thanks full
