### ISSUE TITLE
flame_audio: don't force use of path `assets/audio/*`

### ISSUE THREAD

**Issue by lukepighetti** [flame-engine/flame#2223]

**Comment by ufrshubham** [comment]
Doesn't AudioCache with custom path prefix work for you?

**Comment by lukepighetti** [comment]
A static setter for base path would work better, as it would allow the rest of the API to remain useful

**Comment by ufrshubham** [comment]
> A static setter for base path might be better, as it would allow the rest of the API to remain useful

For example which API doesn't work with custom prefixed audio cache?

**Comment by ufrshubham** [comment]
> I think something like this would preserve the ability to use the static methods
> 
> ```dart
> FlameAudio.assetPath = 'assets/my-custom-audio-folder/';
> FlameAudio.play('sound.mp3');
> ```
> 
> Or if you wanted to disable it entirely
> 
> ```dart
> FlameAudio.assetPath = null;
> FlameAudio.play('assets/my-custom-audio-folder/sound.mp3');
> ```

Which can be achieved with this as well.

 ```dart
 ~~FlameAudio.assetPath = 'assets/my-custom-audio-folder/';~~
FlameAudio.audioCache = AudioCache(prefix: 'assets/my-custom-audio-folder/');
 FlameAudio.play('sound.mp3');
 ```
 
 Or if you wanted to disable it entirely
 
 ```dart
 ~~FlameAudio.assetPath = null;~~
 FlameAudio.play('assets/my-custom-audio-folder/sound.mp3');
 ```
Not sure if a new static member is needed for this.

**Comment by lukepighetti** [comment]
That would work, thanks!

**Comment by st-pasha** [comment]
I think you can also say `FlameAudio.audioCache.prefix = 'whatever'`.
