### ISSUE TITLE
ComposedComponent vs HasGameRef vs BaseGame/Game

### ISSUE THREAD

**Issue by juanitogan** [flame-engine/flame#223]
So, it seems this is currently the correct way to use ComposedComponent without implementing a bunch of overrides (not quite what the doc says):

```dart
class StartScene extends PositionComponent with HasGameRef, Tapable, ComposedComponent {}
```

If, however, you want to ref your own BaseGame class, you might try this:

```dart
class StartScene extends PositionComponent with HasGameRef<MyGame>, Tapable, ComposedComponent {}
```

That, however, generates messages like this:

> Error: 'PositionComponent with HasGameRef, Tapable, ComposedComponent' can't implement both 'HasGameRef\<MyGame>' and 'HasGameRef\<Game>'

And, yet, without ComposedComponent, it passes:

```dart
class StartScene extends PositionComponent with HasGameRef<MyGame>, Tapable {}
```

Now, I've read #167 and look forward to the ComposedComponent changes discussed there.  So, that may make this irrelevant.

**Comment by erickzanardo** [comment]
This is indeed very similar to #167, I am going to link this issue there, and close this one, so we can track this in one only one place.
