### ISSUE TITLE
Flame gesture API does not support multi touch

### ISSUE THREAD

**Issue by erickzanardo** [flame-engine/flame#224]
Currently, Flame Gesture API (TapDetector and etc) don't work with multiple touches, I think this is an important feature and needs to be supported by Flame.

I have created a branch (`gesture-detector-multitaps`) on Flame with a little game to expose the problem, you can find the example here: `doc/examples/gestures/lib/main_multitap.dart`

@luanpotter @renancaraujo I am researching on how to make this work but still haven't much idea on how to make it happen, I would love to have some help on this issue.

**Comment by erickzanardo** [comment]
Alright, I have found a possible solution, this will be a lot of work, but will make Flame gesture api way powerful, we can use RawGestureDetector to combine the detectors that supports multi handlers, something like that:

```dart
    return RawGestureDetector(
        gestures: {
          MultiTapGestureRecognizer: GestureRecognizerFactoryWithHandlers<MultiTapGestureRecognizer>(
            () => MultiTapGestureRecognizer(),
            (MultiTapGestureRecognizer instance) {
              if (game is TapDetector) {
                final tapDetectorGame = game as TapDetector;
                instance.onTapDown = (_, TapDownDetails d) => tapDetectorGame.onTapDown(d);
                instance.onTapUp = (_, TapUpDetails d) => tapDetectorGame.onTapUp(d);
              }
            }
          )
        },
```

I will continue to work on this.

**Comment by JunoNgx** [comment]
Is there anyway to implement `MultiDragGestureRecognizer` at the moment, or is that a lost cause? There's nothing built-in in Flame that supports any multitouch at the moment.

I was able to attach an `ImmediateMultiDragGestureRecognizer` with `flame\util`, but its API is very bizarre, not the conventional `onDragStart. I have no idea what to do with `createNewPointerState(PointerDownEvent event) → _ImmediatePointerState`.

`MultiTapRecognizer` doesn't support drag and `PanRecognizer` supports only single touch.

Any ETA on when a functional multitouch support would be implemented?

**Comment by erickzanardo** [comment]
Multi tap and multi drag support added on `0.21.0`
