### ISSUE TITLE
Subcomponents are not allowed mention in documentation

### ISSUE THREAD

**Issue by bmd007** [flame-engine/flame#2240]
# What could be improved 
Forge2D/Box2D doesn't have a concept of nested bodies and all bodies should live on a top level in the physics world. However, it's hard to know this for people who stat with Forge2d right away. It would be nice to have it clearly mentioned in the documentations. 

I'll create a PR for updating the documentation my self.

**Comment by bmd007** [comment]
I tried to push, however I didn't have permission to create a new branch.

**Comment by spydon** [comment]
> I tried to push, however I didn't have permission to create a new branch.

You have to fork it and then create a PR from the fork.
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork
