### ISSUE TITLE
`onKeyEvent` doesn't work if you press two buttons.

### ISSUE THREAD

**Issue by bernaferrari** [flame-engine/flame#2245]
How to reproduce:
- Press "arrow right".
- Press "arrow up".
- Take the finger out from "arrow up".
- onKeyEvent will stop triggering.

https://user-images.githubusercontent.com/351125/210114593-03997f69-ae95-4d3d-8bac-c29d648262af.mov

Really simple code:
```dart
  @override
  KeyEventResult onKeyEvent(
      RawKeyEvent event, Set<LogicalKeyboardKey> keysPressed) {
  print('keysPressed: ${keysPressed.map((e) => e.keyLabel)}');
   return super.onKeyEvent(event, keysPressed);
}
```

Using Flame 1.5.0 and Flutter (Channel main, 3.7.0-13.0.pre.127, on macOS 13.1 22C65 darwin-x64,
    locale en-BR)

**Comment by spydon** [comment]
Have you tried on the stable channel of Flutter?

**Comment by bernaferrari** [comment]
Yes, same issue.

**Comment by spydon** [comment]
Very strange, this definitely used to work! It seems to not happen all the time either.
I would guess that this is a Flutter bug, so it would be good to try this in a pure Flutter app.

Here is a full repro if anyone wants to try:
https://dartpad.dev/?id=96f38607b6d255a7c9b7b19954ec19a6

**Comment by bernaferrari** [comment]
For me, Flutter-only seems to be working fine.

This is an old sample, it is working:

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(),
      home: const HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Focus(
        autofocus: true,
        onKey: (FocusNode node, RawKeyEvent event) {
          KeyEventResult result = KeyEventResult.ignored;
          if (event is RawKeyDownEvent) {
            if (event.logicalKey == LogicalKeyboardKey.keyZ ||
                event.logicalKey == const LogicalKeyboardKey(0x0000005a)) {
              // When press Z, ctrl+Z, meta+Z, shift+Z:
              print('Z pressed');
              result = KeyEventResult.handled;
            } else {
              // When press meta+shift+Z.
              print('something pressed (???)');
            }
          }
          setState(() {});
          return result;
        },
        child: Text('key is: ${RawKeyboard.instance.keysPressed}'),
      ),
    );
  }
}
```

**Comment by bernaferrari** [comment]
Hold on. Still debugging.

**Comment by bernaferrari** [comment]
This is not a Flutter issue, this is how the OS works. These are the possible workarounds:

<img width="915" alt="image" src="https://user-images.githubusercontent.com/351125/210251973-05a6e067-0847-4df3-8f5b-daea9a877e70.png">

**Comment by spydon** [comment]
> This is not a Flutter issue, this is how the OS works. These are the possible workarounds:
> 
> <img width="915" alt="image" src="https://user-images.githubusercontent.com/351125/210251973-05a6e067-0847-4df3-8f5b-daea9a877e70.png">
> 
> Also this:
> https://github.com/flutter/flutter/issues/117841#issuecomment-1369048897

Thanks for investigating it! I guess we should close this then.

**Comment by bernaferrari** [comment]
Yes and no, ideally you could refactor `onKeyEvent` or add the proposed method into the framework, so would help more people, as the behavior will probably be unclear for many (like Bonfire, etc).

**Comment by bernaferrari** [comment]
I made a sketch for a mixin that could be integrated into Flame, since it guarantees the button works:

```dart
mixin WithCorrectTimer {
  Timer? _timer;
  final List<String?> keysPressed = [];

  void timerStart(int interval) {
    _timer?.cancel();
    _timer = Timer.periodic(
        Duration(milliseconds: interval), (Timer t) => updateMovement());

    RawKeyboard.instance.addListener(_listenForKeys);
  }

  void _listenForKeys(RawKeyEvent k) {
    if (k.runtimeType == RawKeyDownEvent) {
      keysPressed.add(k.logicalKey.debugName);
    } else {
      keysPressed.remove(k.logicalKey.debugName);
    }
  }

  void updateMovement();

  void timerStop() {
    RawKeyboard.instance.removeListener(_listenForKeys);
    _timer?.cancel();
  }
}
```

**Comment by spydon** [comment]
You shouldn't need the timer of you use `on Component` in the mixin, then you can hook in and use `update` instead.

**Comment by st-pasha** [comment]
My worry here is that there could be a situation where a key gets released without the corresponding "KeyUp" event -- say it gets released when the game widget has no focus. In that case we would keep thinking that the key is pressed, and it will effectively become "stuck".

**Comment by st-pasha** [comment]
But perhaps we could create a new version of the `KeyboardEvents` mixin, allowing the people to gradually transition, with the possibility of falling back to the old mixin if something is not working. Similar to how we introduced new draggables and tappables mixins.

**Comment by bernaferrari** [comment]
> My worry here is that there could be a situation where a key gets released without the corresponding "KeyUp" event

There is a Flutter "bug" that already happens when you switch window. It will be fixed in the coming months when the key behavior is synced across window.

Right **NOW**, the only way to not trigger the bug behavior is using ShortcutActivator or SingleActivator, which you aren't using on keyboard event. So there wouldn't be any change.

**Comment by bernaferrari** [comment]
I can't believe you worked so hard on it. I thought I was happy with my placeholder (which came from you, lol). And you ended up doing something even better. Thanks!!
