### ISSUE TITLE
RouterComponent.pushOverlay() causes concurrent modification exception.

### ISSUE THREAD

**Issue by pastordougdev** [flame-engine/flame#2263]
# Current bug behavior
In the update method of a component in the component tree, I am detecting the game over condition and calling the router's pushOverlay() method to push a game over dialog.  When pushOverlay is called, the remainder of the component tree finishes the update methods for the current game loop tick as is normal, but the router is going ahead with adding the overlay route to the component tree, resulting in a concurrent modification exception.

# Expected behavior
Expected behavior is to be able to push the route, allow the game tick to complete and then the overlay route be rendered on the screen.

# Steps to reproduce
1 - call the router component's pushOverlay method from a component in the tree, such as below:
```dart
@override
  void update(double dt) {
    debugger(when: gameStatus == GameStatus.gameOver);
    if (gameStatus == GameStatus.gameOver) {
      print('game is over');
      if (!_showingOverlay) {
        _showingOverlay = true;
        gameRef.router.pushOverlay('gameOver');
      }
      return;
    }
```

# More environment information

# Log information

```
======== Exception caught by scheduler library =====================================================
The following ConcurrentModificationError was thrown during a scheduler callback:
Concurrent modification during iteration: Instance of 'SplayTreeSet<LinkedHashSet<Component>>'.

When the exception was thrown, this was the stack: 
#0      _SplayTreeIterator.moveNext (dart:collection/splay_tree.dart:763:7)
#1      ExpandIterator.moveNext (dart:_internal/iterable.dart:477:21)
#2      IterableMixin.forEach (dart:collection/iterable.dart:45:23)
#3      Component.updateTree (package:flame/src/components/core/component.dart:479:16)
#4      Component.updateTree.<anonymous closure> (package:flame/src/components/core/component.dart:479:33)
```

# More information

I have not determined a cause or fix yet, but I will be happy to assist with a PR for this issue.

**Comment by munsterlander** [comment]
Have you tried returning: `return super.update(dt);`?

**Comment by st-pasha** [comment]
It's possible that this is caused by `Component.reorderChildren()` which may modify the component tree during the `update()` which traverses the component tree.

**Comment by munsterlander** [comment]
Yes, we have confirmed that is it, but we are looking at how you can invoke this without tripping it, unless you think there is a true bug here in that call?

**Comment by munsterlander** [comment]
I have confirmed the issue is with `Component.reorderChildren()` but the question I have, is it needed because when I comment out the call to `reorderChildren();`, it still runs fine without the error now?

```dart
void _adjustRoutesOrder() {
    for (var i = 0; i < _routeStack.length; i++) {
      _routeStack[i].changePriorityWithoutResorting(i);
    }
    //reorderChildren();
  }
  ```

**Comment by munsterlander** [comment]
Ok, reconfiguring that is going to be beyond my skillset then.
