### ISSUE TITLE
Animation and AnimationComponent must ensure stepTime is informed

### ISSUE THREAD

**Issue by erickzanardo** [flame-engine/flame#227]
Is the a value for `stepTime` ins't informed, a NullPointerException can happen, we must add a `@required` to ensure that it is informed upon creation.

**Comment by renancaraujo** [comment]
Since required is removed on compilation, an assert would coimplete it with a more explicit error in debug runtime.

**Comment by erickzanardo** [comment]
In this case, I vote for both!

It is very user friendly to receive an handled error in compilation time instead of runtime.

**Comment by renancaraujo** [comment]
Yep, me too. Thats why I wrote `complete it`.

**Comment by erickzanardo** [comment]
Fair enough!

**Comment by luanpotter** [comment]
I'm ok with both, sincerely I think we don't necessarily need to add asserts to all our `@required`, if we had the annotation the user will know already before even running the code. But I'm ok with it. We should def. add required were needed

**Comment by erickzanardo** [comment]
Fixed on v1
