### ISSUE TITLE
Remove "items" variable from core Broadphase class

### ISSUE THREAD

**Issue by ASGAlex** [flame-engine/flame#2283]
# What could be improved
More complex algorithms require more complex data structures. The basic `Broadphase` class contains the `items` variable that most probably will be unuseful in algorithms that are more complex than Sweep.
Also, the Flame forces other broadphase implementations to fill the `item` with unneeded data. And also, which is more important, it forces to remove each hitbox from `items` whereas such operation becomes extremely slow for a big count of objects because `items` is just a simple `List`

# Why should this be improved
Keeping items in the core class affects performance for hitbox removal operation and consumes additional memory.

# Any risks?
This change will be breaking, if somebody counts on the `items` variable and uses QuadTree or any own collision detection system implementation. 

# More information
I figured out this while running a performance test for another broadphase implementation. All performance improvements was riuned just thanks to this variable :-)

**Comment by spydon** [comment]
Do you want to make a PR for removing it? I don't think many rely on that variable. :)

**Comment by ASGAlex** [comment]
Yes, I'll do. Just checked that my idea would not be rejected at the starting point 👍🏻
