### ISSUE TITLE
Box2d dynamic body falling at startup in 0 gravity

### ISSUE THREAD

**Issue by cedarbob** [flame-engine/flame#231]
I'm checking out Flame with a trivial game that extends Game and has 2 box2d bodies.  A static background body and a small circular dynamic body added on top.  The world is configured with 0 gravity and the dynamic body initialized at (0,0) in world coordinates and (0,0) velocity.  Yet the dynamic body immediately drifts down to the bottom of the screen.  If I make it kinematic or static, it remains at (0,0) as expected.  I haven't been able to get the debugger to break inside of box2d body.dart but, added some print statements inside the methods that apply forces and impulses and none seem to be applied at the outset.  I tried a bunch of feasible settings for friction and restitution; still got the same result.  Below is the complete code for creating the dynamic body:

  ToyPlayer(Box2DComponent box) : super(box) {

    final shape = CircleShape();
    shape.radius = 0.5;

    final fixtureDef = FixtureDef()
      ..shape = shape
      ..restitution = 0.25
      ..density = 75.0
      ..friction = 0.25;

    final bodyDef = BodyDef()
      ..linearVelocity = Vector2(0.0, 0.0)
      ..position = Vector2(0.0, 0.0)
      ..angularDamping = 0.0
      ..linearDamping = 0.0
      ..type = BodyType.DYNAMIC;

    this.body = world.createBody(bodyDef)
      ..createFixtureFromFixtureDef(fixtureDef);

  }

To try to determine if the problem could be in box2d itself, I created a similar toy project in Spritewidget.  I used a version of Flame's Box2dComponent and BodyComponent, modified to work in Spritewidget and added a ToyPlayer to the box2d world created in the modified Box2dComponent.  I didn't see the anomalous movement at the outset I saw in Flame.  That suggests that the issue isn't in the box2d port.  I'll fiddle with the Flame version a bit more to see if I can narrow things down any.

After further testing, I discovered that if I take out the static background body, the dynamic body behaves normally.  Perhaps I have botched it's creation somehow.  If I create and add the background body, but set it to inactive, the dynamic body works but the background body is not displayed.

Below is the world initialization code and the code that creates the static background body (Field class):

class FootballWorld extends Box2DComponent {

  final     log = Logger("FootballWorld");

  Field     field;
  ToyPlayer toyPlayer;

  FootballWorld() : super(scale: 9.0, gravity: 0.0);

  /// Construct background and any initial players.
  @override
  void initializeWorld() {

    field = Field(this);
    toyPlayer = ToyPlayer(this);

    add(field);

    add(toyPlayer);

    log.info('field.center: ${field.center}');
    log.info('toyPlayer.center: ${toyPlayer.center}');
  }

  /// Pass thru to player for now.
  void handleDoubleTap() {

    toyPlayer.stop();
  }

  /// Pass thru to player for now
  void handleTap() {

      toyPlayer.start();
  }
} 

  Field(Box2DComponent box) : super(box) {

    _loadSvg();

    final shape = PolygonShape();
    shape.setAsBoxXY(worldWidth / 2.0, worldHeight / 2.0);

    final fixtureDef = FixtureDef();
    fixtureDef.shape = shape;
    fixtureDef.restitution = 0.0;
    fixtureDef.friction = 0.0;

    final bodyDef = BodyDef();
    bodyDef.position = Vector2(0.0, 0.0);
    Body groundBody = world.createBody(bodyDef);
    groundBody.createFixtureFromFixtureDef(fixtureDef);
    this.body = groundBody;
  }

**Comment by erickzanardo** [comment]
@japalekhin could you help us with this?

**Comment by japalekhin** [comment]
@cedarbob i don't see world initialization code, can you post that part too?

also, you can look at my break-out example and see how i initialized the world https://github.com/japalekhin/brick-head/blob/master/lib/brick-game.dart#L27

**Comment by cedarbob** [comment]
We can close or delete this issue.  Turns out I neglected to set up collision filtering to prohibit the static background body from colliding with the dynamic body and it was apparently pushing the dynamic body down.  Sorry to waste anyone's time.
