### ISSUE TITLE
[flame_tiled] Conflict between tilesets

### ISSUE THREAD

**Issue by gtgalone** [flame-engine/flame#2320]
# Current bug behavior

<img width="250" alt="Screen Shot 2023-02-05 at 12 15 27 AM" src="https://user-images.githubusercontent.com/23162037/216809732-4be5a237-b0ee-46bb-8968-ba33a218dcdb.png">

# Expected behavior

<img width="573" alt="Screen Shot 2023-02-05 at 12 14 35 AM" src="https://user-images.githubusercontent.com/23162037/216809740-4e203cbe-090e-4549-b407-5e7f3d73f635.png">

# Steps to reproduce

# Flutter doctor output

```
Output of: flutter doctor -v
```

# More environment information

# Log information

```
Enter log information in this code block
```

# More information

**Comment by spydon** [comment]
@Hwan-seok @ufrshubham @kurtome @jtmcdole does any of you understand what the bug is from these pictures?

**Comment by ufrshubham** [comment]
> @Hwan-seok @ufrshubham @kurtome @jtmcdole does any of you understand what the bug is from these pictures?

I don't 😅

**Comment by kurtome** [comment]
> @Hwan-seok @ufrshubham @kurtome @jtmcdole does any of you understand what the bug is from these pictures?

It looks like maybe it's using the wrong tile image? But if that's the case we'd need the tmx file and everything to compare and debug

**Comment by Hwan-seok** [comment]
Me neither at glance.
@gtgalone Can you provide a reproducible example?

**Comment by gtgalone** [comment]
@Hwan-seok Of course thing.

https://github.com/gtgalone/flame_test

Here is the full example.

**Comment by Hwan-seok** [comment]
I tried this on Android and works fine. 
Can you provide more information you tried? 
Such as platform, os version, and device name.
![스크린샷 2023-02-06 오전 12 59 06](https://user-images.githubusercontent.com/38072762/216830166-5ed42211-3f44-45d9-bec9-1ab59608a460.png)


It seems your texture size is big enough to break some device's texture size limits.
```xml
 <tileset firstgid="1" name="water" tilewidth="32" tileheight="32" tilecount="3072" columns="64">
  <image source="../images/tilesets/water.png" width="2048" height="1536"/>
 </tileset>
 <tileset firstgid="3073" name="basechip" tilewidth="32" tileheight="32" tilecount="1064" columns="8">
  <image source="../images/tilesets/basechip.png" width="256" height="4256"/>
 </tileset>
```

**Comment by kurtome** [comment]
The internal rendering code does some image packing that could have weird edge cases with these giant tileset images. The packing is a performance optimization to attempt to keep as few images in memory at once as possible (I think)

As Hwan-seok is saying, the max image size is different per platform, which could also be a factor

**Comment by gtgalone** [comment]
I just tested in Android. It works fine. 

My original env is

Platform is Chrome(web)
OS Version is MacOS Monterey
DeviceName is Macbook.

Only for this spec.
I got that bug.

If you guys tried to Chrome 
```
"args": [
        "-d",
        "chrome",
      ],
```

That bug will be appeared.

**Comment by kurtome** [comment]
Based on this comment, I think it's a Flutter/system limitation that we have to work around:

```
/// Note: Chrome on Android has a maximum texture size of 4096x4096. kIsWeb is
/// used to select the smaller texture and might overflow. Consider using
/// smaller textures for web targets, or, pack your own atlas.
```

I think we should update the documentation to make it more clear that that max tileset image size is 4096px.

**Comment by spydon** [comment]
Thanks for all the help all the people that I tagged! :)
Does anyone want to take the responsibility for updating the docs?

**Comment by jtmcdole** [comment]
Its a system limitation on Android Web, not Flutter.   I think we need a developers guide for best practices when targeting different platforms.  For a few of these conditions, I'd also suggest pre-packing all of your tile-sets could get around this.
