### ISSUE TITLE
Add DoubleTapCallbacks

### ISSUE THREAD

**Issue by Hwan-seok** [flame-engine/flame#2321]
# Problem to solve
Since there is no direct way to detect double-tapping inside a component, we need to manually propagate the double-tap event to a component tree by users. It would be better to provide a way to detect a double tap inside a component conveniently.

# Proposal

- Implement ~~DoubleTappableComponents &~~ DoubleTapCallbacks to follow the new gesture system.
- Since there are no `DoubleTappable`, I don't think the bridge is needed.

Edit: Seems all `hasXXXComponents` will be replaced with `XXXDispatcher`. `DoubleTap` should be the same too.

# More information
 

Are you interested in working on a PR for this?  **Yes**

**Comment by spydon** [comment]
I'll assign you to the issue. :)
