### ISSUE TITLE
Create a `/latest` path in the docs

### ISSUE THREAD

**Issue by FMorschel** [flame-engine/flame#2345]
# What could be improved
I was following the tutorial on https://docs.flame-engine.org/1.6.0/tutorials/klondike/klondike.html (not this exact link, but my point stands exactly in this) and I saw a warning on top of the page that told me I needed to go to the latest docs because they might be outdated. There could be a path like `https://docs.flame-engine.org/latest/` so that people are not confused when starting with flame and finding it through Google or somewhere that could lead them to the older versions.

# Why should this be improved
So that when linking to the flame docs through a post on medium, a video description on youtube or anywhere the person will always go to the latest version.

**Comment by spydon** [comment]
Sounds like a good idea, we should probably block search engine indexing of specific versions and only let it index /latest and possibly /main.

**Comment by immadisairaj** [comment]
I am interested in looking at this issue. From simply looking, I feel that we are just passing the `version` directly into the respective directories.

Ref link: https://github.com/flame-engine/flame-docs-site/blob/b47b87ddc787eae7cdcf47c7dd3bda2db798ac09/publish.sh#L98

Currently what we do is:
```
Inside flame-doc-site (publish.sh):
- We get the versions
- add them directly into respective folders
- Add the versions to the versions.txt
Inside the doc:
- Get the versions
- Link them to the respective `html` link.
```

What I would propose to do is
```
Inside flame-doc-site (publish.sh):
- We get the versions
- add them directly into respective folders if not latest version
- If latest version, add it into the `/latest` folder
- Add the versions to the versions.txt (as it is)
Inside the doc:
- Get the versions
- Link them to the respective `html` link if not latest version
- Link the version to the `latest` html if it is the latest version
```

Additional details:
Just another idea - we could also probably add `(latest)` to the latest version say for example `1.7.0 (latest)` or something other that you suggest?

**Comment by spydon** [comment]
>  Just another idea - we could also probably add (latest) to the latest version say for example 1.7.0 (latest) or something other that you suggest?

This sounds like a good solution. What we need to do too is to add a `robots.txt` that only allows search engines to crawl the `/latest` directory, so that it doesn't give links to old versions in the search results like it does today.

**Comment by FMorschel** [comment]
> (...) What we need to do too is to add a `robots.txt` that only allows search engines to crawl the `/latest` directory, so that it doesn't give links to old versions in the search results like it does today.

Has this been done? I was watching [Observable Flutter: Speed-coding Pong](https://www.youtube.com/watch?v=3KpOyfxyPes) and [searching "flame collision" on Google](https://www.google.com/search?q=flame+collision&oq=flame+collision&aqs=chrome..69i57j69i60l2.7377j0j7&sourceid=chrome&ie=UTF-8)(on an incognito tab as well), the first result was of version `1.0.0` which is not `latest`.

**Comment by spydon** [comment]
> Has this been done? I was watching [Observable Flutter: Speed-coding Pong](https://www.youtube.com/watch?v=3KpOyfxyPes) and [searching "flame collision" on Google](https://www.google.com/search?q=flame+collision&oq=flame+collision&aqs=chrome..69i57j69i60l2.7377j0j7&sourceid=chrome&ie=UTF-8)(on an incognito tab as well), the first result was of version `1.0.0` which is not `latest`. And Craig got a little confused because his results weren't linear with what he was using.

It has not, I think it was forgotten, this part is left:
> Apparently noindex is the way to go instead of robots.txt:
https://developers.google.com/search/docs/crawling-indexing/block-indexing

Should be a very quick fix in https://github.com/flame-engine/flame-docs-site

**Comment by immadisairaj** [comment]
Well, yeah I didn't find time (was not well) and started looking at it today. I think it'll mostly be adding `noindex` inside the `<meta>` for non-latest versions' `index.html`.

correct me if I am wrong @spydon.

**Comment by spydon** [comment]
Glad you are better now @immadisairaj!

> I think it'll mostly be adding noindex inside the <meta> for non-latest versions' index.html.

Exactly :)

**Comment by spydon** [comment]
This is now live on the site, now we just have to wait for google to re-index it.
