### ISSUE TITLE
Being able to add more time to a `Timer`

### ISSUE THREAD

**Issue by Skyost** [flame-engine/flame#2357]
# What could be improved

Currently, it isn't possible to change the elapsed time of a `Timer`. It's also not possible to change the limit.
I think this could easily be improved by removing the `final` keyword of the `limit` variable in the `Timer` class.

# Why should this be improved

I use timers in my game as a countdown before the player dies in a level. But some objects should act as bonus that give some time to the player.

What I've done so far is that I've created a `MutableTimer` class that allows me to change the limit :

<details>

```dart
/// A [Timer] that allows to change its limit.
class MutableTimer extends Timer {
  /// The current timer limit.
  double _limit;

  /// Creates a new mutable timer instance.
  MutableTimer(
    double limit, {
    super.onTick,
    super.repeat,
    super.autoStart,
  })  : _limit = limit,
        super(limit);

  @override
  double get limit => _limit;

  /// Changes the current timer limit.
  set limit(double limit) => _limit = limit;
}
```

</details>

but it really is a workaround.

# Any risks?

Not to my knowledge.

**Comment by spydon** [comment]
Sounds reasonable, I don't see any reason for keeping it final.
Should I assign you to the issue?

**Comment by Skyost** [comment]
@spydon I can totally make a PR if you want 🙂
