### ISSUE TITLE
docs: Mermaid graphs in docs are not rendering

### ISSUE THREAD

**Issue by erickzanardo** [flame-engine/flame#2360]
Flame docs have some broken content, I've noticed both on `1.6.0` and `main` channels.

An example page: https://docs.flame-engine.org/main/flame/components.html#components

<img width="807" alt="Screenshot 2023-02-21 at 19 05 55" src="https://user-images.githubusercontent.com/835641/220469290-224bd697-3a28-425b-8447-4cc75f05a811.png">

**Comment by spydon** [comment]
Looks like the graph didn't get properly generated.

**Comment by spydon** [comment]
I think this is the issue: https://github.com/mgaitan/sphinxcontrib-mermaid/issues/110

**Comment by spydon** [comment]
Fixed it by updating the sphinxcontrib-mermaid version to the latest.
