### ISSUE TITLE
TiledComponent renders wrong map if some condition is met 

### ISSUE THREAD

**Issue by Hwan-seok** [flame-engine/flame#2390]
# Current bug behavior
If there are several maps with the same tileset but different tile alignments and also they have only one tileset, the latter one is not rendered correctly.

Let's say there are two Tiled maps `A` and `B`
Each of them has the same tileset named `image`.
But they have different tile alignments respectively.

When we load map A and then load B, The latter one not renders correctly but renders tile alignments of A.

This is because TiledAtlas caches its map based on its tilesets' names.
Please see the following section, there is operator `??=` which makes this issue.
https://github.com/flame-engine/flame/blob/f125593aaaaef160395b772180b1514f6be3ac4f/packages/flame_tiled/lib/src/tile_atlas.dart#L98-L108

# Expected behavior
Regardless of the `TiledComponent` loading order, they will render correctly.

# More environment information

* Flame version: main

# More information

Are you interested in working on a PR for this? Yes

**Comment by spydon** [comment]
Good find, I'll assign you to the issue
