### ISSUE TITLE
Multi touch detection In Flutter flame

### ISSUE THREAD

**Issue by patolax** [flame-engine/flame#2396]
I want to implement game control for a boxing game.

Four sections in black represent uppercuts and jabs. In order to block, the player should use multi-touch, where one figure should be on the left half of the screen and another figure on the right half. This is clearly overlapping other controls.

What is the best way to handle multi-touch with little conflicts with other controls in the Flame engine (flutter)? (if the user has two fingers for several seconds, the game should keep the player in the blocking mode)

I tried adding MultiTouchTapDetector but this did not give any indication as to user is tapping and keep pressing from two fingers. 

![image](https://user-images.githubusercontent.com/29444156/224532688-817ec8bb-29b8-4400-8425-4d26ec303d0a.png)

**Comment by ufrshubham** [comment]
@patolax did you try using `Tappble` mixin on components? Here is a simple example where I am able to detect block as you mentioned. 

```dart
class MultiTapGame extends FlameGame with HasTappables {
  @override
  Future<void> onLoad() async {
    debugMode = true;
    await add(Controls());
  }
}

class Controls extends Component with HasGameRef {
  bool isLeftDown = false;
  bool isRightDown = false;

  @override
  Future<void> onLoad() async {
    await addAll(
      [
        TappableRegion(
          position: Vector2.all(0),
          size: Vector2(gameRef.size.x * 0.5, gameRef.size.y * 0.75),
          onTapDownCallback: () {
            isLeftDown = true;
            if (isRightDown) {
              print("Block");
            } else {
              print("Left Uppercut");
            }
          },
          onTapUpCallback: () {
            isLeftDown = false;
          },
        ),
        TappableRegion(
          position: Vector2(gameRef.size.x * 0.5, 0),
          size: Vector2(gameRef.size.x * 0.5, gameRef.size.y * 0.75),
          onTapDownCallback: () {
            isRightDown = true;
            if (isLeftDown) {
              print("Block");
            } else {
              print("Right Uppercut");
            }
          },
          onTapUpCallback: () {
            isRightDown = false;
          },
        ),
        TappableRegion(
          position: Vector2(0, gameRef.size.y * 0.75),
          size: Vector2(gameRef.size.x * 0.5, gameRef.size.y * 0.25),
          onTapDownCallback: () {
            isLeftDown = true;
            if (isRightDown) {
              print("Block");
            } else {
              print("Left Jab");
            }
          },
          onTapUpCallback: () {
            isLeftDown = false;
          },
        ),
        TappableRegion(
          position: Vector2(gameRef.size.x * 0.5, gameRef.size.y * 0.75),
          size: Vector2(gameRef.size.x * 0.5, gameRef.size.y * 0.25),
          onTapDownCallback: () {
            isRightDown = true;
            if (isLeftDown) {
              print("Block");
            } else {
              print("Right Jab");
            }
          },
          onTapUpCallback: () {
            isRightDown = false;
          },
        ),
      ],
    );
  }
}

class TappableRegion extends PositionComponent with Tappable {
  TappableRegion({
    super.position,
    super.size,
    super.scale,
    super.angle,
    super.nativeAngle,
    super.anchor,
    super.children,
    super.priority,
    this.onTapDownCallback,
    this.onTapUpCallback,
  });

  late RectangleComponent _rectangleComponent;

  @override
  FutureOr<void> onLoad() {
    _rectangleComponent = RectangleComponent(
      size: size,
      paint: Paint()..color = Colors.green,
    );
    return super.onLoad();
  }

  void Function()? onTapDownCallback;
  void Function()? onTapUpCallback;

  @override
  bool onTapDown(TapDownInfo info) {
    onTapDownCallback?.call();
    add(_rectangleComponent);
    return super.onTapDown(info);
  }

  @override
  bool onTapUp(TapUpInfo info) {
    onTapUpCallback?.call();
    _rectangleComponent.removeFromParent();
    return super.onTapUp(info);
  }

  @override
  bool onTapCancel() {
    onTapUpCallback?.call();
    _rectangleComponent.removeFromParent();
    return super.onTapCancel();
  }
}
```

**Comment by patolax** [comment]
Wow big fan, I started flame yesterday after watching your spaceshooter series. And the code below you will see that I have used the command system from spaceshooter.

Your approach is much more stable than what I ended up with. 
I change the above logic to add stop-blocking animation when the user stops multi-tapping. Hope this is correct.

import 'dart:async';
import 'package:chessboxing/logic/game.dart';
import 'package:chessboxing/models/enums.dart';
import 'package:flame/components.dart';
import 'package:flame/events.dart';
import 'package:flutter/material.dart';

import '../logic/command.dart';
import '../logic/player.dart';

class Controls extends Component with HasGameRef<ChessBoxing> {
  bool isLeftDown = false;
  bool isRightDown = false;
  bool isBlocking = false;

  @override
  Future<void> onLoad() async {
    await addAll(
      [
        TappableRegion(
          position: Vector2.all(0),
          size: Vector2(gameRef.size.x * 0.5, gameRef.size.y * 0.75),
          onTapDownCallback: () {
            isLeftDown = true;
            if (isRightDown) {
              addCommand(JabTypes.blockStart);
              print("Block");
            } else {
              addCommand(JabTypes.leftUppercut);
              print("Left Uppercut");
            }
          },
          onTapUpCallback: () {
            isLeftDown = false;
            stopBlocking();
          },
        ),
        TappableRegion(
          position: Vector2(gameRef.size.x * 0.5, 0),
          size: Vector2(gameRef.size.x * 0.5, gameRef.size.y * 0.75),
          onTapDownCallback: () {
            isRightDown = true;
            if (isLeftDown) {
              addCommand(JabTypes.blockStart);
              print("Block");
            } else {
              addCommand(JabTypes.rightUppercut);
              print("Right Uppercut");
            }
          },
          onTapUpCallback: () {
            isRightDown = false;
            stopBlocking();
          },
        ),
        TappableRegion(
          position: Vector2(0, gameRef.size.y * 0.75),
          size: Vector2(gameRef.size.x * 0.5, gameRef.size.y * 0.25),
          onTapDownCallback: () {
            isLeftDown = true;
            if (isRightDown) {
              addCommand(JabTypes.blockStart);
            } else {
              addCommand(JabTypes.leftJab);
            }
          },
          onTapUpCallback: () {
            isLeftDown = false;
            stopBlocking();
          },
        ),
        TappableRegion(
          position: Vector2(gameRef.size.x * 0.5, gameRef.size.y * 0.75),
          size: Vector2(gameRef.size.x * 0.5, gameRef.size.y * 0.25),
          onTapDownCallback: () {
            isRightDown = true;
            if (isLeftDown) {
              print("Block");
              addCommand(JabTypes.blockStart);
            } else {
              print("Right Jab");
              addCommand(JabTypes.rightJab);
            }
          },
          onTapUpCallback: () {
            isRightDown = false;
            stopBlocking();
          },
        ),
      ],
    );
  }

  stopBlocking() {
    if (isBlocking) {
      isBlocking = false;
      addCommand(JabTypes.blockStop);
    }
  }

  addCommand(JabTypes jabType) {
    if (jabType == JabTypes.blockStart) {
      isBlocking = true;
    }
    final command = Command<Player>(action: (player) {
      player.action(jabType);
    });
    gameRef.addCommand(command);
  }
}

class TappableRegion extends PositionComponent with Tappable {
  TappableRegion({
    super.position,
    super.size,
    super.scale,
    super.angle,
    super.nativeAngle,
    super.anchor,
    super.children,
    super.priority,
    this.onTapDownCallback,
    this.onTapUpCallback,
  });

  late RectangleComponent _rectangleComponent;

  @override
  FutureOr<void> onLoad() {
    _rectangleComponent = RectangleComponent(
      size: size,
      paint: Paint()..color = Colors.green,
    );
    return super.onLoad();
  }

  void Function()? onTapDownCallback;
  void Function()? onTapUpCallback;

  @override
  bool onTapDown(TapDownInfo info) {
    onTapDownCallback?.call();
    return super.onTapDown(info);
  }

  @override
  bool onTapUp(TapUpInfo info) {
    onTapUpCallback?.call();
    return super.onTapUp(info);
  }

  @override
  bool onTapCancel() {
    onTapUpCallback?.call();
    return super.onTapCancel();
  }
}

**Comment by ufrshubham** [comment]
@patolax that looks correct 👍🏼. 

Also just a tip for the future, if you ever run into such "how-to-do-xyz-in-flame" style questions, try posting them in Flame's discord server or in the [Discussions](https://github.com/flame-engine/flame/discussions) of this repo. That will make it visible to more people more quickly 😉

**Comment by patolax** [comment]
will do. Thanks for the tip.
While you are here, couple of other questions on flame.
- what's the best way to detect punches on the opponents? (currently, the sprite is a square, I am guessing the player square and opponent square should be overlapping and the player should be in a jabbing state)
- what's the best way to handle skins. Say I want the player to have configurable 
1. skin colour - white, black, brown
2. head guards with and without
3. glove colors (red, blue, gold, white)
4. body types (skinny, jacked, normal)
5. maybe hairstyles (bold, short and normal)
as you can see if there are so many variations, we have to ship the app with so many sprites. any idea how to implement such thing?

thanks a lot.

**Comment by spydon** [comment]
> will do. Thanks for the tip.
> While you are here, couple of other questions on flame.
> - what's the best way to detect punches on the opponents? (currently, the sprite is a square, I am guessing the player square and opponent square should be overlapping and the player should be in a jabbing state)
> - what's the best way to handle skins. Say I want the player to have configurable 
> 1. skin colour - white, black, brown
> 2. head guards with and without
> 3. glove colors (red, blue, gold, white)
> 4. body types (skinny, jacked, normal)
> as you can see if there are so many variations, we have to ship the app with so many sprites. any idea how to implement such thing?
> 
> thanks a lot.
> 

Take those questions on discord or in separate GitHub discussions (just like DevKage said) since they aren't related to the original question in the issue you opened. :)
