### ISSUE TITLE
Colliders collide with each other, but there are some areas that do not detect collisions.

### ISSUE THREAD

**Issue by kindkmj** [flame-engine/flame#2409]
# Current bug behavior

Colliders collide with each other, but there are some areas that do not detect collisions.

# Expected behavior

# Steps to reproduce

# Flutter doctor output

```
Output of: flutter doctor -v
```
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.8, on macOS 13.0.1 22A400 darwin-arm, locale ko-KR)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
[✓] VS Code (version 1.76.1)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

```

# More environment information

```
flame: ^1.6.0
Platform affected: ios
Platform version affected: ios 16.2
```

# Log information

```
Enter log information in this code block
```

# More information

Obviously, it's a normal area to detect a collision, but it doesn't collide and just passes through it.

![스크린샷 2023-03-15 오전 11 34 33](https://user-images.githubusercontent.com/41276448/225190431-811d1dc4-8fc5-494b-b887-a26053c5b2e0.png)

https://user-images.githubusercontent.com/41276448/225190478-bda3716a-2c38-42cb-ab22-1fbad326e22e.mov

you can check my issue 

i upload video and image

**Comment by ufrshubham** [comment]
Can you place a rect and a circle in that specific configuration with no movement and see if it still doesn't trigger the collision callbacks?

**Comment by kindkmj** [comment]
@ufrshubham  https://github.com/Umigishi-Aoi/block_breaker code here 
i used him code

**Comment by ufrshubham** [comment]
@kindkmj can you confirm that indeed the collision callbacks are not called? I'm suspecting that maybe your collisions handling code might be flawed.

Can you provide a minimal reproducible example where we wouldn't have to play the game and encounter this issue randomly?

**Comment by kindkmj** [comment]
i will try it ...

**Comment by kindkmj** [comment]
@spydon no i don`t because i think flutter flame not ready package 
change my project unity
