### ISSUE TITLE
Example game padracing control keys not functioning after restart

### ISSUE THREAD

**Issue by mkhan-akhan** [flame-engine/flame#2414]
Current bug behavior
Control keys not functioning after restarting the game.

Expected behavior
Car should respond to control keys as per how it does when the game is initially started.

Steps to reproduce
1. Run the game
2. Choose 1 Player (Arrow keys)
3. Play until game over
4. Choose restart
5. Choose 1 Player (Arrow keys)
6. Play the game (Arrow keys do not move the car)

More environment information
This problem exists in the padracing version 1.0.0+1

More information
The issue relates to how the activeKeyMaps list is generated and cleared.
activeKeyMaps = List.generate(numberOfPlayers, (i) => playersKeys[i]);
I believe that activeKeyMaps ends up actually referencing the playersKeys keymaps.
On restart the code reads:
void reset() {
...
for (final keyMap in activeKeyMaps) {
      keyMap.clear();
}
...
}

The result is that keyMaps in the playersKeys list is actually removed, leaving an empty map set. Hence, on restart activeKeyMaps ends up with an empty map as well.

The fix that worked for me was to replace the code above with activeKeyMaps.clear() which leaves the playersKeys intact.

**Comment by spydon** [comment]
Do you want to put up a PR with your fix? :)

**Comment by mkhan-akhan** [comment]
> Do you want to put up a PR with your fix? :)

I haven't put up a PR ever before :) Hence not familiar :(. Could you do it this time round  please :) :)

**Comment by mkhan-akhan** [comment]
Would have been a good opportunity to get familiar with the process. Unfortunately, 'under the pump at the moment'. So sorry.

**Comment by spydon** [comment]
Np, fixed it up in #2415, you can verify that it was the fix you intended.
I tried at least and it works.

**Comment by mkhan-akhan** [comment]
> Np, fixed it up in #2415, you can verify that it was the fix you intended. I tried at least and it works.

Yes, all good. Thank you very much.
