### ISSUE TITLE
`SpriteComponent` doesn't auto-resize

### ISSUE THREAD

**Issue by ufrshubham** [flame-engine/flame#2419]
# Current bug behavior

If sprite of a `SpriteComponent` is set or updated after construction of the component, the size of the component does not update.

# Expected behavior

Ideally the size of `SpriteComponent` should be automatically updated by default. Additionally a an option can be provided to turn this resizing off by setting a flag in `SpriteComponent`.

# Steps to reproduce

Setting up a sprite component like this will make it render with zero size:
```dart
final spriteComponent = SpriteComponent();
spriteComponent.sprite = await Sprite.load('arrow_up.png');
add(spriteComponent);
```

# Flutter doctor output

NA

# More environment information

Flame version: 1.6.0
Platform affected: All

# Log information

```
Enter log information in this code block
```
NA

# More information

I can work on this.

**Comment by spydon** [comment]
I assigned you to the issue :)
I guess this is the same in SpriteAnimationComponent?
