### ISSUE TITLE
Contents in the documentation doesn't have a scroll option

### ISSUE THREAD

**Issue by immadisairaj** [flame-engine/flame#2423]
# What could be improved

When going through the documentation, even if there is a contents on the right, I find it hard to navigate. Because it overflows out of the page vertically.

<img width="232" alt="Screenshot 2023-03-23 at 18 44 48" src="https://user-images.githubusercontent.com/40348358/227217054-6b229408-42d7-4c90-bbb0-78ab162832e9.png">

# Why should this be improved

We can probably add a scrollbar for it so that we can directly go to that particular section.

# Any risks?
No risks

# More information

I probably think playing around with the styles can fix this issue.

> Are you interested in working on a PR for this?

Yes

**Comment by spydon** [comment]
I don't fully understand what you mean, could you send a video? If it is for the content in the menu I can scroll that?

**Comment by immadisairaj** [comment]
https://user-images.githubusercontent.com/40348358/227220286-e70ef4de-f745-4ba5-b7d3-f4f3465f2690.mov

I am unable to scroll the content to see what's at the bottom.

> If it is for the content in the menu I can scroll that?

But, how is that I am unable to scroll? I tried on safari and chrome.. I am using [this](https://docs.flame-engine.org/main/flame/effects.html) link.

**Comment by immadisairaj** [comment]
Yes. It's still the same. I think we are not handling any overflow over there. I click, it goes to that place in the main content, but the sidebar is still the same.

**Comment by spydon** [comment]
Okay, I'll assign you to the issue then :)

**Comment by st-pasha** [comment]
It's something like `overflow-y: auto` on the sidebar element

**Comment by immadisairaj** [comment]
That isn't just enough from what I saw as the width drastically reduced and we need to adjust proper width + margin and set overflow-x to hidden. Playing around with it for now. Maybe we might probably need a fixed width (not sure, looking for options to have flexible bar).
