### ISSUE TITLE
Setting `visibleGameSize` for `CameraComponent.withFixedResolution` raises `Assertion failed` exception

### ISSUE THREAD

**Issue by trunghq3101** [flame-engine/flame#2426]
# Current bug behavior

The game can't run because of this exception:

![image](https://user-images.githubusercontent.com/37343767/227399236-3f0259ec-03de-469d-8e9d-7d70e12e38d6.png)

# Expected behavior

It used to work fine on Flame 1.6.0.
If it's a breaking change, it should be documented somewhere to know how to set `visibleGameSize` correctly.

# Steps to reproduce

Minimal code to reproduce: https://zapp.run/edit/flame-zweq06qwwer0

# Flutter doctor output

```
Output of: flutter doctor -v
```

# More environment information

* Flame version: main
* Platform affected: desktop

# Log information

```
Enter log information in this code block
```

# More information

**Comment by st-pasha** [comment]
Thank you for posting a good MRE.

It looks like the problem is caused by the fact that `camera.viewport.size` is zero at the point when `set visibleGameSize` is called. Not sure what caused this bug, if it used to work in 1.6.0

**Comment by spydon** [comment]
@st-pasha I did a `git bisect` and #2317 is where the issue is introduced.

**Comment by spydon** [comment]
I converted it to a test for easier debugging:
```dart
    testWithFlameGame('can change visibleGameSize directly', (game) async {
      final world = World()..addToParent(game);
      final cameraComponent = CameraComponent(world: world)..addToParent(game);
      expect(
        () => cameraComponent.viewfinder.visibleGameSize = Vector2(100, 100),
        returnsNormally,
      );
    });
 ```
