### ISSUE TITLE
docs: Error in flame_svg code snippets in documentation causing issues in IDE

### ISSUE THREAD

**Issue by jithuraj** [flame-engine/flame#2432]
# Current bug behavior
Reference - [flame_svg docs](https://docs.flame-engine.org/1.6.0/bridge_packages/flame_svg/svg.html#how-to-use-flame-svg)
code - ```Svg svgInstance = Svg('android.svg');```
IDE error - The argument type 'String' can't be assigned to the parameter type 'DrawableRoot'

code - ```final svgComponent = SvgComponent.fromSvg(size, position, svgInstance,);```
fix - can be fixed by passing these values as named parameters to `SvgComponent();`

# Steps to reproduce
[Minimal reproducible example](https://github.com/jithuraj/flame_svg_sample)

**Comment by jithuraj** [comment]
Can I submit a PR on this?

**Comment by spydon** [comment]
> Can I submit a PR on this?

Please do!
Just to make sure, this is only an update to outdated docs right? No actual change to flame_svg?

**Comment by jithuraj** [comment]
Thank you @spydon for getting back to me and for assigning me to this issue.
No actual changes to flame_svg. It is just an update to outdated docs.

Also, can I remove this code snippet? (I don't have any idea how to fix it )
```
Svg svgInstance = Svg('android.svg');

final position = Vector2(100, 100);
final size = Vector2(300, 300);

svgInstance.renderPosition(canvas, position, size);
```
And maintain this corrected code snippet only?

```
final svgInstance = await Svg.load('android.svg');
final size = Vector2.all(100);
final position = Vector2.all(100);
final svgComponent = SvgComponent(
  size: size,
  position: position,
  svg: svgInstance,
);

add(svgComponent);
```

**Comment by spydon** [comment]
Just change the first line to the same first line as in the second snippet, so that there is an example both for using it as a component and for rendering it stand-alone.
