### ISSUE TITLE
Unable to set joystick to spriteComponent

### ISSUE THREAD

**Issue by DYernar** [flame-engine/flame#2434]
Cannot update sprite position from joystick delta. Accessing joystick delta from hasGameRef.

# Current bug behavior
getting following error

# Expected behavior
`This exception was thrown in the context of a scheduler callback. When the scheduler callback was _registered_ (as opposed to when the exception was thrown), this was the
stack:
#2      SchedulerBinding.scheduleFrameCallback (package:flutter/src/scheduler/binding.dart:571:49)
#3      Ticker.scheduleTick (package:flutter/src/scheduler/ticker.dart:265:46)
#4      Ticker.start (package:flutter/src/scheduler/ticker.dart:171:7)
#5      GameLoop.start (package:flame/src/game/game_loop.dart:54:15)
#6      GameRenderBox._attachGame (package:flame/src/game/game_render_box.dart:80:16)
#7      GameRenderBox.attach (package:flame/src/game/game_render_box.dart:71:5)
#8      AbstractNode.adoptChild (package:flutter/src/foundation/node.dart:139:13)
#9      RenderObject.adoptChild (package:flutter/src/rendering/object.dart:1517:11)
#10     RenderObjectWithChildMixin.child= (package:flutter/src/rendering/object.dart:3576:7)
#11     SingleChildRenderObjectElement.insertRenderObjectChild (package:flutter/src/widgets/framework.dart:6392:18)
#12     RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:6156:35)
#13     RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5828:5)
...     Normal element mounting (15 frames)
#28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#29     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6512:36)
#30     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6524:32)
#31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#32     Element.updateChild (package:flutter/src/widgets/framework.dart:3676:20)
#33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#34     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#35     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#36     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2743:19)
#37     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:863:21)
#38     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:381:5)
#39     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#40     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218:9)
#41     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1076:5)
#42     _invoke (dart:ui/hooks.dart:145:13)
#43     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338:5)
#44     _drawFrame (dart:ui/hooks.dart:112:31)
(elided 2 frames from class _FrameCallbackEntry)`

# Steps to reproduce
clone this repo: https://github.com/DYernar/test_flame_app/tree/main/lib
flutter run

# Flutter doctor output

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.7, on macOS 12.6 21G115 darwin-arm64, locale en-KZ)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.76.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

# More environment information

# Log information

```
Enter log information in this code block
```

# More information

**Comment by ufrshubham** [comment]
@DYernar please recheck your code. You have a shadowing joystick object here:

 https://github.com/DYernar/test_flame_app/blob/7254ce48550726373db83cf0419eac654a4a0a30/lib/flame_layer/my_game.dart#L48
