### ISSUE TITLE
docs: Hidden toctree details for flame_audio & flame_forge2d

### ISSUE THREAD

**Issue by jithuraj** [flame-engine/flame#2445]
# Current bug behavior
Is the [flame_audio](https://docs.flame-engine.org/main/bridge_packages/flame_audio/flame_audio.html) toctree hidden on purpose?
``` # flame_audio

```{toctree}
:hidden:

General audio    <audio.md>
Background music <bgm.md>
AudioPool        <audio_pool.md>
```

Same for [flame_forge2d](https://docs.flame-engine.org/main/bridge_packages/flame_forge2d/flame_forge2d.html)
```# flame_forge2d

```{toctree}
:hidden:

Overview    <forge2d.md>
Joints    <joints.md>
```

**Comment by spydon** [comment]
It's probably left from when they were in progress, they can be shown now
