### ISSUE TITLE
doc: Remove unnecessary async from code snippets in documentation

### ISSUE THREAD

**Issue by jithuraj** [flame-engine/flame#2449]
Can I remove unnecessary `async` from code snippets in `documentation` and submit a PR?

**Comment by spydon** [comment]
Please go ahead.
Remember that it is only `onLoad` that is `FutureOr<void>`.

**Comment by jithuraj** [comment]
Hi, Sorry for the delayed response.
I am new to flutter and contributing to OSS.
I didn't understand your last comment properly.
Does that mean only remove `async` keywords from `onLoad` function which are `FutureOr<void>`?

or can I change 
```   
@override
Future<void> onLoad() async {

}
```
to 
```
@override
void onLoad() {

}
```
if no `await` was used in its body?

**Comment by spydon** [comment]
> if no await was used in its body?

Yes and if no async methods are called from the body, methods returning futures that is

**Comment by jithuraj** [comment]
hi,
is it mandatory to pass `melos run test`?

I am getting this output
```console
[flame]: 
[flame]: 01:44 +1290: All tests passed!                                                                                                                                                                         
---------------------------------------------------------------------------------------------------------------------

$ melos exec
  └> flutter test
     └> FAILED (in 2 packages)
        └> examples (with exit code 1)
        └> jenny (with exit code 1)

melos run test:select
  └> melos exec -- flutter test
     └> FAILED
ScriptException: The script test:select failed to execute.


melos run test
  └> melos run test:select --no-select
     └> FAILED
ScriptException: The script test failed to execute.
```

**Comment by ufrshubham** [comment]
Ideally yes. If you want you can create a PR and see if it fails in CI runs.
