### ISSUE TITLE
docs: Design of copy button in code snippets are not as expected

### ISSUE THREAD

**Issue by jithuraj** [flame-engine/flame#2463]
# Current bug behavior
Sorry for reopening this issue (#2456) again. 

I changed the file name `custom.css` to `copy-button.css` and forgot to update the `conf.py` 

```
# Configuration options for sphinx_copybutton.
html_static_path = ["theme"]
html_css_files = ["copy-button.css"]
```

Adding this will fix the issue. Can I submit a PR on this?

**Comment by spydon** [comment]
You don't have to open an issue for fixes like this, you can just submit a PR directly :smile:
