### ISSUE TITLE
Component.remove of a child is no longer called during removeFromParent() since 1.7.0

### ISSUE THREAD

**Issue by ASGAlex** [flame-engine/flame#2464]
# Current bug behavior
Calling removeFromParent()  does not trigger parent.remove() function since version 1.7.0. It looks odd comparing to previous versions, it also does not mentioned evidently in "breaking changes" list in changelog. 

# Expected behavior
In older Flame version calling removeFromParent() used parent.remove() function. 

# More information
It looks like since 1.7.0 we should to avoid creating custom logic at components remove() function since it is not called in some causes. If it was exactly what was desired, it should be mentioned at function's documentation, developer should be warned. It also forces developer to use `onChildrenChanged` to handle child removing events. 

It seems to me, the main problen of new approach is that now we need to implement custom code for children removal twice: one time for cause when removeFromParent is called and another time for calling remove() explicitly

**Comment by spydon** [comment]
@st-pasha this was your change, and it was intentional that it doesn't go through the parent's `remove` method right?

Since `remove` is not a callback meant to be overridden by the user I wouldn't call this a breaking change, we should probably be clearer on that in the docs though, maybe even mark it with a meta tag.

What is your usecase @ASGAlex? And why do you need to implement it twice if you have `onChildrenChanged`? I guess `onRemove` of the children can't be used because you don't extend the child components?

**Comment by ASGAlex** [comment]
>And why do you need to implement it twice  

Ah, you right , i really don't need that, my mistake

I made special utility component wich optimizes it's child components: renders it into single picture and re-renders only 
 if any child's transform is changed and on components adding/removing. It also optimizes component's collisions, merging small hitboxes into bigger one. 
So, originally I reimplemented `add()` and `remove()` methods because them did not look like something that prohibited from modification. That solution simply lied on the surface - opposite to `onChildrenChanged` which was found only during investigation "what's going wrong?"

**Comment by spydon** [comment]
Alright, makes sense! `onChildrenChanged` should cover your use-case then at least?
Maybe we should add `@nonVirtual` to `add` and `remove`, or maybe just explain in the dartdoc that one can't expect them to be called unless they are called directly by the user.
