### ISSUE TITLE
Make the Component lifecycle graph readable

### ISSUE THREAD

**Issue by spydon** [flame-engine/flame#2465]
# What could be improved
It is currently very hard to read the Component Lifecycle graph:
![image](https://user-images.githubusercontent.com/744771/229741542-9b9ff580-a89e-4f45-8d77-2161fd114a64.png)

# Any risks?
No.

# More information
The graph is generated so it should be fairly easy to just update the colors it uses for "Runs Once" and for the bottom arrow.

**Comment by spydon** [comment]
Right, this graph is actually wrong now too, `onGameResize` should be moved to before `onMount` instead.

**Comment by immadisairaj** [comment]
I'd like to work on this @spydon. Can you assign me this issue?
