### ISSUE TITLE
Proposal widgetbuilder work with Listener that handle pointevent

### ISSUE THREAD

**Issue by bung87** [flame-engine/flame#247]
current it using `GestureDetector` which is good.
[Listener](https://api.flutter.dev/flutter/widgets/Listener-class.html)  

or prefer leave the end developer custom their own `WidgetBuilder`?

**Comment by erickzanardo** [comment]
Can you point the benefits of using Listener instead of the GestureDetector?

From what I see, Listener has only Raw inputs, while GestureDetector offers a higher end detectors, if we change to use Listener, the developer will have to write a lot of code to detect specific gestures, while GestureDetector already does that.

**Comment by bung87** [comment]
I think `GestureDetector` is more fit application use cases, I'm trying using ComposedComponent but it requires `with tapable` ,which I dont need, I'm trying implement a minimap component like photoshop navigator that can handle point down point move events.

or maybe I just implement it as `OverlayWidget`?

**Comment by erickzanardo** [comment]
We have some work been done to improve Flame gesture API to provides multitouches as reported here: #224 

Today we always wrap the game widget on a GestureDetector widget, I think what we can do, is to not wrap the game widget inside a GestureDetector widget if no Flame gesture detector is used on the game, then the user is free to implement its own solution of gesture detection in the case of the provided out of the box is not sufficient.

**Comment by bung87** [comment]
I think game class could be Generic class, let the end developer decide which detector as container, for now I will try `OverlayWidget `.

**Comment by erickzanardo** [comment]
I like the idea to let the end dev to decide what to use, but it is nice to let Flame provides out of the box solutions that makes it easier for you if you don't have a complex need.

Anyway, I think it is valid to wrap the game widget on `GestureDetector` only when Flame APIs are used, so it will not conflict in the case of the dev wanting to use their own getector container.

**Comment by bung87** [comment]
yeah, may have some articles about this thread,  extends Game class and rewrite builder property will cover this.

**Comment by erickzanardo** [comment]
Multi tap and multi drag support added on `0.21.0`
