### ISSUE TITLE
Issues receiving back button/gesture events on Android using KeyEvents

### ISSUE THREAD

**Issue by anst270125** [flame-engine/flame#2486]
# Current bug behavior
I'm trying to intercept the back button/gesture on Android, in order to prevent directly exiting the game  on such actions.  Using Flutter I'd do this with `WillPopScope`, but with Flame I tried using `KeyEvents ` / `HasKeyboardHandlerComponents`. The issue is the following: Tapping the back button triggers `onKeyEvent` only if I pressed another physical key in advance(only testable in emulator).

# Expected behavior
Have `onKeyEvent` called any time the back navigation button is pressed.

# Steps to reproduce
Complete code:
```
import 'dart:async';
import 'package:flame/components.dart';
import 'package:flame/input.dart'; 
import 'package:flame/flame.dart';
import 'package:flame/game.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  Flame.device.setLandscape();
  Flame.device.fullScreen();
  runApp(GameWidget(
    game: TestGame(),
    autofocus: true,
  ));
}

class TestGame extends FlameGame with HasKeyboardHandlerComponents, SingleGameInstance {
  @override
  KeyEventResult onKeyEvent(RawKeyEvent event, Set<LogicalKeyboardKey> keysPressed) {
    print('${event.runtimeType} ${event.logicalKey.keyLabel}');
    final isBackUp = event is RawKeyUpEvent && event.logicalKey == LogicalKeyboardKey.goBack;
    return isBackUp ? KeyEventResult.handled : super.onKeyEvent(event, keysPressed);
  }

  @override
  FutureOr<void> onLoad() {
    add(TextComponent(text: "Test"));
  }
}
```
### Scenario 1
1. Run the app in the Android emulator
2. Click on the back navigation button in the emulator
3. `onKeyEvent` is not called, the game exits 

### Scenario 2
1. Run the app in the Android emulator
2. Press any key on your PC keyboard. Let's say I pressed X.
3. `onKeyEvent` is called twice, outputting `RawKeyDownEvent X`   `RawKeyUpEvent X`
4. Click on the back navigation button in the emulator
5. `onKeyEvent` is called twice, outputting `RawKeyDownEvent Go Back`    `RawKeyUpEvent Go Back`
6. As wished, the game does not exit.

# Flutter doctor output
```
[√] Flutter (Channel stable, 3.7.0, on Microsoft Windows [Version 10.0.22621.1413], locale en-US)
    • Flutter version 3.7.0 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (3 months ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\an\AppData\Local\Android\sdk
    • Platform android-33-ext4, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[√] VS Code (version 1.77.1)
    • VS Code at C:\Users\an\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.62.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.1413]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 111.0.5563.147
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 110.0.1587.41

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

# More environment information

**Comment by anst270125** [comment]
This only works if I also wrap `WillPopScope` with `MaterialApp`. I'd like to avoid creating a `MaterialApp` just for fixing this. Is there really no other way?

**Comment by spydon** [comment]
If Flutter doesn't expose that button/action as a KeyEvent I don't see how we could handle it from within Flame.

**Comment by renancaraujo** [comment]
> I'd like to avoid creating a MaterialApp just for fixing this. 

Having a `WidgetsApp` in the root of your application is always a good idea. In fact, one of the very reasons this widget exists is to provide context capture of user navigation. 

See the [docs](https://api.flutter.dev/flutter/widgets/WidgetsApp-class.html): 

> One of the primary roles that [WidgetsApp](https://api.flutter.dev/flutter/widgets/WidgetsApp-class.html) provides is binding the system back button to popping the [Navigator](https://api.flutter.dev/flutter/widgets/Navigator-class.html) or quitting the application.


So, the solution should either use a `WidgetsApp` widget (like `MaterialApp`) or look into its source code and reimplement that behavior yourself. 

Regardless of that, I don't think this is a flame issue now should be resolved within the engine.

**Comment by anst270125** [comment]
The interesting thing is, the back key was in fact captured, if another key was pressed in advance.
I ended up using MaterialApp and WillPopScope.
