### ISSUE TITLE
bug: with enabled autoResize transform listeners callbacks are called constantly

### ISSUE THREAD

**Issue by ASGAlex** [flame-engine/flame#2488]
# Current bug behavior
If to subscribe to component's transform events and enable autoResize, callbacks will be called even there are no any changes.

# Expected behavior
Transform callbacks should be called only when something really changed

# More information
We should to check equality of current component's size and sprite's size before calling `size.setFrom` here: https://github.com/flame-engine/flame/blob/95e34515dfbeed09f7cbfaace5e3659321dcf659/packages/flame/lib/src/components/sprite_animation_group_component.dart#L172

**Comment by spydon** [comment]
@ufrshubham
