### ISSUE TITLE
After upgrade from 1.5.0 to 1.7.2, JoystickComponent not working

### ISSUE THREAD

**Issue by denghejun** [flame-engine/flame#2489]
Can not drag the knob to move, the joystick is not dragable anymore.

```
joystick = JoystickComponent(
      priority: Consts.PRIORITY_OPERATION_UI,
      knob: SpriteComponent(
        sprite: knobImage.getSpriteById(0),
        size: Vector2.all(40),
      )..setAlpha(255),
      background: SpriteComponent(
        sprite: joyImage.getSpriteById(0),
        size: Vector2.all(120),
      )..setAlpha(200),
      margin: const EdgeInsets.only(left: 80, bottom: 40),
    );
```

**Comment by ufrshubham** [comment]
@denghejun try removing `HasDraggables` and `HasTappables` mixin from your FlameGame class.

**Comment by denghejun** [comment]
> HasDraggables

But If I really need HasTappables on my game class, but all buttons not working, how can I deal with?

**Comment by ufrshubham** [comment]
In 1.7.2 those mixins are not really needed for drag and tap detection. One possible cause of buttons not working might be the old camera system. I had to migrate all my projects to the new `CameraComponent` APIs to make the buttons work correctly.

**Comment by denghejun** [comment]
> In 1.7.2 those mixins are not really needed for drag and tap detection. One possible cause of buttons not working might be the old camera system. I had to migrate all my projects to the new `CameraComponent` APIs to make the buttons work correctly.

great! thanks, big help.
