### ISSUE TITLE
Bug with TapCallbacks & camera.zoom or camera.flow

### ISSUE THREAD

**Issue by null-safety** [flame-engine/flame#2491]
When I use camera.zoom or camera.flow, it becomes difficult to hit TapCallbacks. The point returned by containsLocalPoint is not accurate.

easy test  
/flame/examples/lib/stories/input/tap_callbacks_example.dart

```
  @override
  Future<void> onLoad() async {
    add(TappableSquare()..anchor = Anchor.center);
    add(TappableSquare()..y = 350);

    // add this
    camera.zoom = 0.5;
  }
```

**Comment by spydon** [comment]
I would recommend using the `CameraComponent` if you are using `TapCallbacks`, I'm not sure that the `TapCallbacks` fully take the old camera into consideration. If you don't want to use the `CameraComponent` another workaround could be to use `Tappable` instead of `TapCallbacks`.
https://docs.flame-engine.org/1.7.0/flame/camera_component.html

**Comment by spydon** [comment]
I don't think that would work for nested components.

**Comment by ashkryab-fl** [comment]
have some issue.

**Comment by ashkryab-fl** [comment]
i just wont override some getter in TapCallbacks mixin, like
set positionType (PositionType value)=>
and choose, my component can be moved/scaled and i need to calculate its position by local or global

**Comment by null-safety** [comment]
> I don't think that would work for nested components.

Yes, I agree. Nested components may need to traverse up to each parent until the root parent, and then calculate accordingly.

**Comment by Cubel89** [comment]
I don't know if it will be for the same reason or not, but I have noticed that when I apply "TapCallbacks" to a "PositionComponent" it works perfectly but if it is a "BodyComponent" it seems to completely ignore the tap.

**Comment by spydon** [comment]
> but if it is a "BodyComponent" it seems to completely ignore the tap.

Unfortunately gestures combined with the `CameraComponent` isn't fully fixed in flame_forge2d yet, but I have an ongoing branch for it which I will finish up once [Flutter & Friends](https://flutterfriends.dev) is over.
