### ISSUE TITLE
can initialDimensions just using WidgetsBinding.instance.window

### ISSUE THREAD

**Issue by bung87** [flame-engine/flame#250]
https://github.com/flame-engine/flame/blob/e1d4886c67dcc53d0e08c3b80b0d99753bfefbeb/lib/util.dart#L96

[WidgetsBinding.instance.window](https://api.flutter.dev/flutter/dart-ui/Window-class.html)

Currently I using `WidgetsBinding.instance.window` everywhere, and works fine.

**Comment by erickzanardo** [comment]
Please provide a meaningful description of your problem, what problem you are facing and etc, otherwise we can't help.

**Comment by bung87** [comment]
this is not a problem , just confirm the current solution.

**Comment by erickzanardo** [comment]
I see, closing this then, let us know if you have further questions, consider joining the Discord for that kind of doubts.
