### ISSUE TITLE
Update flame_audio readme

### ISSUE THREAD

**Issue by spydon** [flame-engine/flame#2511]
# What could be improved
The readme for flame_audio should have some introduction and some examples since it will show up on pub.dev.

# Why should this be improved
To make it easier for users to get started.

# Any risks?
No

# More information
Current readme: https://github.com/flame-engine/flame/blob/main/packages/flame_audio/README.md

**Comment by xjyribro** [comment]
Yo @spydon 

I can write the docs and provide the example codes for this. I will open a PR within a few weeks.

**Comment by spydon** [comment]
> Yo @spydon 
> 
> I can write the docs and provide the example codes for this. I will open a PR within a few weeks.

Great! I'll assign you to the issue.

**Comment by xjyribro** [comment]
opened new PR https://github.com/flame-engine/flame/pull/3119 for this issue
