### ISSUE TITLE
flame_test testGoldens needs to allow for a threshold

### ISSUE THREAD

**Issue by maks** [flame-engine/flame#2527]
There are unfortunately multiple open issues in the Flutter SDK due to Golden tests failing with tiny differences due to running on different architectures and OS's:
* https://github.com/flutter/flutter/issues/111739
* https://github.com/flutter/flutter/issues/108399

A workaround is [described in this article](https://rows.com/blog/post/writing-a-localfilecomparator-with-threshold-for-flutter-golden-tests) which allows for setting a threshold for Golden Tests. Because `flmaee_test` package defines its own `testGolden()` it would be useful to modify that to allow for setting a threshold to prevent these Goldentest visually insignificant failures due to machine arch or OS differences.

**Comment by spydon** [comment]
Do you want to work on this?
We only run and generate goldens on one platform to make sure they are exact, so we don't need this internally, but I see how it would be useful for others.

**Comment by maks** [comment]
Thanks for being open to this @spydon ! Yes I'm happy to give it a go. I actually ran into this with the Sashimi package, which is using `testGolden()` in its own tests.

**Comment by spydon** [comment]
I assigned you to the issue :)

**Comment by spydon** [comment]
I'll close this as stale, please comment if you are planning to work on this and I'll re-open it. :)
