### ISSUE TITLE
Tap events does not work correctly when camera properties change

### ISSUE THREAD

**Issue by hacker-takeda** [flame-engine/flame#2528]
# Current bug behavior
Tap events do not work correctly when adding settings such as `camera.followComponent()` with a Component set to tap events using `TapCallbacks`.
For example, onTapDown() does not work correctly in the following example code.

https://github.com/flame-engine/flame/blob/main/examples/lib/stories/camera_and_viewport/follow_component_example.dart#L187

I do not know the cause of this event, but it seems that the tapable area is displaced by changes to the camera properties.

# Expected behavior
Tap event follows the target component even if the camera properties are changed.

# Steps to reproduce
1. Prepare a component with Tap events like `onTapDown()` in `TapCallbacks`.
2. Set followComponent(), change viewport, etc. in the Camera component.
3. Tap a component with Tap events set.

The following flame example confirms that the tap event does not work.
https://examples.flame-engine.org/#/   <= Camera & Viewport - Follow Component

# More environment information
* Flame version: 1.7.3
* Platform affected: android, ios, web

**Comment by ufrshubham** [comment]
Could be similar to https://github.com/flame-engine/flame/issues/2491. @hacker-takeda a recommended solution is to use the new `CameraComponent` APIs instead. Most probably the current camera system is going to be deprecated in flame 2.0.

**Comment by spydon** [comment]
You can see here as well:
https://stackoverflow.com/a/76148594/789545

I guess we'll have to deprecate the old behaviour rather soon, or fix it...

**Comment by hacker-takeda** [comment]
@ufrshubham @spydon 
I have confirmed that tap events work as expected by using `CameraComponent`.
Thank you very much!

This issue is closed.
