### ISSUE TITLE
FilterQuality.high drawing output is pixelted on both canvas and overlay

### ISSUE THREAD

**Issue by patolax** [flame-engine/flame#2551]
My code is below and the drawing output. The sprite size used is 512x512.
The game has no scaling and this is a simple 2D game.

As shown by the code we use size to scale the sprite size as required by the game and `paint.filterQuality = FilterQuality.high;` to improve output quality.

The image shows, what's drawn on canvas and an overlay dialog box. 
As you can see lines and edges are super pixelated on both canvas and overlay. How can I improve this output?
(any vertical or horizontal line looks ok)

```
class Sprite extends SpriteComponent {

  Sprite(double size) {
    size = Vector2(size , size);
    init(piece);
  }

  
  void init() async {
    sprite = Sprite(await Flame.images.load('path');
    paint.filterQuality = FilterQuality.high;
  }
}
```
![image](https://github.com/flame-engine/flame/assets/29444156/33eb5b71-f262-424a-84b1-7ba090cedd05)

**Comment by spydon** [comment]
Is this on all platforms? Have you tried with a Flutter versions before 3.10.0?

**Comment by patolax** [comment]
I think I am using 
environment:
  sdk: '>=2.18.4 <3.0.0'
dependencies:
  flame: ^1.6.0

**Comment by spydon** [comment]
What does `flutter --version` say?

**Comment by patolax** [comment]
> What does `flutter --version` say?

Flutter 3.10.0 • channel stable • https://github.com/flutter/flutter.git 
Framework • revision 84a1e904f4 (2 weeks ago) • 2023-05-09 07:41:44 -0700
Engine • revision d44b5a94c9
Tools • Dart 3.0.0 • DevTools 2.23.1

**Comment by patolax** [comment]
@spydon anything I can look at here? 100x00 is ok for now but the issue is on tablets this might not look nice.

**Comment by spydon** [comment]
Did you try with a flutter version before 3.10? So that we can rule out a regression from flutter?

**Comment by patolax** [comment]
@spydon 

There is no difference in output fluter 3.0.0. 512x512 pixelates while 100x100 works.

![image](https://github.com/flame-engine/flame/assets/29444156/6835fbd6-829f-451b-9452-0b11339c55c2)

Flutter 3.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ee4e09cce0 (1 year, 1 month ago) • 2022-05-09 16:45:18 -0700
Engine • revision d1b9a6938a
Tools • Dart 2.17.0 • DevTools 2.12.2

**Comment by spydon** [comment]
And what size did you say that the image was?

**Comment by patolax** [comment]
100px x100px works. anything bigger ends up with this issue.

**Comment by spydon** [comment]
I mean the source image, what size is that?

**Comment by spydon** [comment]
Ah that is the size for the source image, that's strange. Can you upload the images here?

**Comment by patolax** [comment]
100
![king_black](https://github.com/flame-engine/flame/assets/29444156/2f0d8d96-7750-4469-8c33-9e834f2fce1d)
512
![king_black](https://github.com/flame-engine/flame/assets/29444156/b1c8c9db-6630-4870-9082-d41595a3fc0e)

**Comment by spydon** [comment]
And what size are you rendering it at? I would guess that you're scaling down the larger image in the `SpriteComponent`? Because the large image renders just fine in it's normal resolution for me.
Try to change the size of the `Image` object and then pass that to a `Sprite` object that you then pass to the `SpriteComponent`.

**Comment by patolax** [comment]
When I debug the size of the image is 46. Basically, think of it as fill screen width/8. 
This is the test [phone](https://www.jbhifi.com.au/products/motorola-g22-128gb-cosmic-black) Resolution (Pixels)
1600 x 720.

My Code can be found at the top. Can you give me hints as to how to implement what you are saying? 
(also I use an Image widget in the overlay dialog. That also renders poorly if the image is large)

**Comment by spydon** [comment]
There is an extension on `Image` in Flame where you can resize the image, so it would be something like this:

```dart
class ChessPiece extends SpriteComponent {
  final double sideLength;
  ChessPiece(this.sideLength) : super(size: Vector2.all(sideLength);

  @override
  Future<void> onLoad() async {
    final sourceImage = Flame.images.load('path');
    final image = sourceImage.resize(size);
    sprite = Sprite(image);
  }
}
```

if that doesn't work I would try to use a `FixedResolutionViewport` and have the source image size close to the size that it will render as.

**Comment by patolax** [comment]
![image](https://github.com/flame-engine/flame/assets/29444156/ba50a96b-75a4-4563-93d1-61a1a02e6268)
That did not work, it even screwed up 100x100 image that worked.

**Comment by spydon** [comment]
That is the old way of doing it, now you should use the `CameraComponent` instead, you can read more about how to set it up here:
https://docs.flame-engine.org/latest/flame/camera_component.html

**Comment by patolax** [comment]
This is my code with a camera. I reverted the image resizing logic you recommend earlier. I don't see any difference. 

![image](https://github.com/flame-engine/flame/assets/29444156/dbde2f23-46db-4443-bf21-178b64b0d64d)

```
final camera = CameraComponent.withFixedResolution(
      world: _world,
      width: size.x,
      height: size.x,
    );
    camera.viewfinder.anchor = Anchor.topLeft;
    add(_world);
    add(camera);
```

**Comment by spydon** [comment]
Seems like this is a regression in Flutter then (or it's just particularly bad on your image), you could try the same thing in a `CustomPainter` to see if you get the same result in pure flutter.

**Comment by spydon** [comment]
@patolax did you ever try this in a custom painter? To see whether the issue is with Flutter or not.

**Comment by patolax** [comment]
FilterQulity.Medium is what's best apparently. This is a flutter issue. FilterQulity.Medium fixed it for me.

**Comment by spydon** [comment]
Oooh, thanks for the info! It even says so in the dartdocs.
