### ISSUE TITLE
Regression in `camera.worldBounds`

### ISSUE THREAD

**Issue by Skyost** [flame-engine/flame#2564]
# Current bug behavior

Using `cameraComponent.setBounds()`, the camera still renders out of bounds components. This happens because the `BoundedPositionBehavior` object only prevents the center of the view finder to go out of the screen.

![Schema 1](https://github.com/flame-engine/flame/assets/3882599/cb836c08-3387-475c-8284-46481247c55d)

Also, the docs state that the bounds should be _given in the world coordinates_, but it seems that I need to multiply them by `cameraComponent.viewfinder.zoom` to be correctly taken into account.

# Expected behavior

Well, I except the new camera component to behave like the old camera object :

![Schema 2](https://github.com/flame-engine/flame/assets/3882599/df51587b-aa2f-4192-8601-312891b7f2b3)

# Steps to reproduce
Migrate from `camera.worldBounds = ...` to `cameraComponent.setBounds(...)`.

# Flutter doctor output

```
C:\Users\Hugo>flutter doctor -v
[√] Flutter (Channel stable, 3.10.2, on Microsoft Windows [version 10.0.22621.1702], locale fr-FR)
    • Flutter version 3.10.2 on channel stable at C:\Users\Hugo\AppData\Roaming\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (13 days ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\Hugo\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: D:\Projets\Jetbrains IDEs\apps\AndroidStudio\ch-0\222.4459.24.2221.10121639\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.5.33627.172
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.2)
    • Android Studio at D:\Projets\Jetbrains IDEs\apps\AndroidStudio\ch-0\222.4459.24.2221.10121639
    • Flutter plugin version 74.0.2
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [version 10.0.22621.1702]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 113.0.1774.42

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

# More environment information

* Flame version: 1.8.0
* Platform affected: all, I think

**Comment by spydon** [comment]
I think this is the intended behavior, since the `viewfinder` shouldn't be responsible for what is being rendered.
You can see the dartdoc comment for `setBounds`:
>   /// Sets or clears the world bounds for the camera's viewfinder.
  ///
  /// The bound is a [Shape], given in the world coordinates. The viewfinder's
  /// position will be restricted to always remain inside this region. Note that
  /// if you want the camera to never see the empty space outside of the world's
  /// rendering area, then you should set up the bounds to be smaller than the
  /// size of the world.

**Comment by Skyost** [comment]
Oh, well, I'm sorry if this is the case. Do you know how to get back to the old behavior @spydon ?

**Comment by Skyost** [comment]
@spydon Can I reopen this issue, and eventually, turn it into a question ?

**Comment by spydon** [comment]
@Skyost after having a look my conclusion is that the bounds are only for the viewfinder, and as such it makes sense in its current implementation, so it is not a bug.
I understand what it is that you want to do though, but that should be handled differently, so it would be better if you opened a new feature request instead.

**Comment by Skyost** [comment]
Fine ! 🙂
