### ISSUE TITLE
Loading any tiled map throws exceptions after using Flame.images.clearCache()

### ISSUE THREAD

**Issue by ASGAlex** [flame-engine/flame#2585]
# Current bug behavior

Try this sequence: 
1. Disposing a previous game
2. Calling Flame.images.clearCache();
3. Loading a new game with different image assets but some tiles are similar
4. Catching exception "Cannot clone a disposed image", because TiledAtlas.atlasMap is newer cleared, but Flame.images.clearCache(); disposed all it's images

# Expected behavior
There should be a way to clear atlasMap after Flame.images.clearCache();
Maybe we should implement a public method to clear caches for tiled too?

# More environment information

* Flame version: 1.8.0
* flame_tiled version: 1.11.0
* tiled version: 1.10.1
* Platform affected: all

**Comment by spydon** [comment]
Indeed seems like it, do you want to create a PR for that?

**Comment by ASGAlex** [comment]
Sure, but maybe not very soon. Most probably in July. If it is ok - assign the issue on me 👌🏼
