### ISSUE TITLE
Add support for GDX Texture Packer. 

### ISSUE THREAD

**Issue by Yayo-Arellano** [flame-engine/flame#2589]
# Problem to solve
Currently, if we want to use a sprite sheet in Flame we have two options:

- [Fire Atlas](https://github.com/flame-engine/fire-atlas): Very limited and hard to use
- [Flame TexturePacker](https://pub.dev/packages/flame_texturepacker): It allows us to use [code & web texture packer](https://www.codeandweb.com/texturepacker) to create sprite sheets and load into Flame. But the implementation is minimal; it only supports the most basic packing options and no optimizations.  

[GDX Texture Packer](https://github.com/crashinvaders/gdx-texture-packer-gui) is free software and supports many different optimizations like rotating sprites to make the sprite sheet smaller, removing unused pixels, splitting the sprite sheet into multiple images, etc.

# Proposal
I forked [Flame TexturePacker](https://pub.dev/packages/flame_texturepacker) and modified it to support GDX Texture Packer. So far can:

- Support images packed on multiple pages
- Support rotates sprites
- Support indexes.

Other features that we can also support are: removing white pixels, filters, image format, etc.

# More information
[Here](https://github.com/Yayo-Arellano/flame_texturepacker/commit/44eab45ab22c6c0221ce9ec86ca8ae03e6e39613) is the commit that adds support to Gdx texture packer.

**Comment by spydon** [comment]
Looks like a big step forward for that package, have you spoken to @brixto about this?

However, I don't think a new component should be created but that the current `SpriteAnimationComponent` should be used, and just passing in the data read out from the atlas, is there anything stopping that?

**Comment by Yayo-Arellano** [comment]
@spydon, thanks for the answer. I haven't spoken with @Brixto about it. But now that he is in the loop, it would be nice to get some feedback. If we support GDX Texture Packer we can "kill two birds with one stone" because Code & Web Texture Packer also supports exporting sprite sheets with the extension `.atlas`. 

> However, I don't think a new component should be created but that the current SpriteAnimationComponent should be used, and just passing in the data read out from the atlas, is there anything stopping that?

Initially, I tried to use only `SpriteAnimationComponent`, but the problem is that some sprites from the animation will be rotated 90 degrees in the sprite sheet, and some will not. To un-rotate the particular frames, the width, and height must be swapped.

I've been trying to replicate the code from [Libgdx](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/graphics/g2d/TextureAtlas.java#L730) so I think if I can do the rotation & resize in the `Sprite` then I do not need to create the classes `AtlasSpriteComponent` & `AtlasSpriteAnimationComponent`.

**Comment by Yayo-Arellano** [comment]
@spydon It was a simple change. Now the rotation is done in `AtlasSprite` so we can use `SpriteAnimationComponent` and `SpriteComponents`. I deleted the other components.

**Comment by Brixto** [comment]
Would love to see support of GDX Texture Packer in the flame_texturepacker plugin. Feel free to open a Pull Request 👍

**Comment by Yayo-Arellano** [comment]
Great. I created a [pull request](https://github.com/Brixto/flame_texturepacker/pull/8) please let me know if there are comments
