### ISSUE TITLE
Option to prevent propogating collision events from ShapeHitbox to _hitboxParent

### ISSUE THREAD

**Issue by ASGAlex** [flame-engine/flame#2590]
# What could be improved
In some complex cases a component need to have several hitboxes and some of them could have very utility function. For example, a vechicle could have body hitbox to control collisions and side hitboxes to check availability to turn left or right. So, colliding with body hitbox means a collision with component itself, whereas colliding with side hitbox does not mean a real collision and should not be propogated to hitbox's parent. 

# Why should this be improved
Of course we can do these checks in 'on collsion' functions or handle utulity logics there, but this is not flexible if we want to separate logics to components, to use ECS approach and so on. 

# Any risks?
Just one option to ShapeHitbox, which could be completely ignored if not needed.

**Comment by spydon** [comment]
Sounds good, maybe just a boolean `triggersParentCollision` (that defaults to false) or something like that.
