### ISSUE TITLE
world add component Abnormal display

### ISSUE THREAD

**Issue by hanleiZoro** [flame-engine/flame#2600]
I'm wondering if I'm doing something wrong?

![image](https://github.com/flame-engine/flame/assets/38712031/da792c81-609d-4532-9065-f10803071481)
It's code.
![image](https://github.com/flame-engine/flame/assets/38712031/0e9cbd00-d05f-4011-9a2d-6bb934e74940)

**Comment by ufrshubham** [comment]
Looks perfect fine to me. By default the camera looks at/targets the origin of the world. Default anchor of viewfinder is centre that is why it places the target at the centre.
