### ISSUE TITLE
Add the ability to calculate make the camera component bounds to behave like the old camera object

### ISSUE THREAD

**Issue by Skyost** [flame-engine/flame#2601]
# What could be improved

Using `cameraComponent.setBounds()`, the camera still renders out of bounds components. This happens because the `BoundedPositionBehavior` object only prevents the center of the view finder to go out of the screen.

![243453810-cb836c08-3387-475c-8284-46481247c55d](https://github.com/flame-engine/flame/assets/3882599/ea949a0d-f029-47bc-b703-94b56cfddb14)

I think it's nicer to not render empty space, as it was the case with the old camera object.

![243454292-df51587b-aa2f-4192-8601-312891b7f2b3](https://github.com/flame-engine/flame/assets/3882599/369f5c98-ecfb-4fb6-87b5-286b3d0c1cc9)

Note that this is the intended behavior, as discussed in #2564.

# Why should this be improved

Well, it would be nice for the camera to not render empty space.

# Any risks?

No risk. I think the best way to do it would be to create a `cameraComponent.calculateVisibleWorldViewfinderBounds()` or something like that, so that it can be used alongside of `cameraComponent.setBounds()`.

**Comment by spydon** [comment]
Here is a work around for anyone that might need it:
https://stackoverflow.com/a/77167193/789545

It shouldn't be too hard to implement that into the camera either (remember to take the zoom level into consideration too though) if anyone is keen to do a PR.

**Comment by Skyost** [comment]
Just opened a PR @spydon 👍
