### ISSUE TITLE
How about to use viewfinder.zoom in forge2d instead of use OpenGL zoom.

### ISSUE THREAD

**Issue by mrbeardad** [flame-engine/flame#2606]
# Problem to solve

The default zoom of Forge2DGame is 10, which use OpenGL to zoom the entire game, include world and camera component. So the components in viewport is also scaled. And the viewport is actually bigger than window!
![image](https://github.com/flame-engine/flame/assets/54128430/0f6da7c9-9aa2-4a94-97a5-bfc82e1e99bf)

# Proposal

Use viewfinder to zoom the world, so the camera component works properly.
```dart
class Forge2DExample extends Forge2DGame {
  late final CameraComponent mainCamera;
  late final World cameraWorld;

  Forge2DExample() : super(zoom: 1);

  @override
  Future<void> onLoad() async {
    cameraWorld = World();
    mainCamera = CameraComponent(world: cameraWorld)
      ..viewport.add(AlignComponent(child: FpsTextComponent()))
      ..viewfinder.anchor = Anchor.topLeft
      ..viewfinder.zoom = zoom; // and use vector.scaled(1/zoom) to transform pixles to forge world meters
    addAll([mainCamera, cameraWorld]);
    // ...
  }
}
```
# More information

**Comment by spydon** [comment]
This is already underway, since flame_forge2d unfortunately almost is unusable now with the new CameraComponent system.
