### ISSUE TITLE
Examples: Various instances of broken links when navigating to the source code from within the hosted Example project

### ISSUE THREAD

**Issue by markvideon** [flame-engine/flame#2618]
There are a number of examples that do not correctly point to the source, this appears to be the result of refactoring the file structure. 

The instances of this that I have found:

- **System -> Step Game**  'view code' button directs the user to 
step_engine_game.dart which does not exist. The file that appears to correspond to this example is called step_engine_example.dart, in the same directory.

- A number of the flame_forge2d examples appear to have been affected by a move of the joint examples in a subdirectory named joints. These are:
  - **flame_forge2d -> Revolute Joint** 
  - **flame_forge2d -> Rope Joint** 
  - **flame_forge2d -> Weld Joint**

- A number of bridge library examples appear to be affected by a move into a subdirectory called bridge_libraries. The affected examples:
  - **FlameLottie -> Lottie animation example**
  - **FlameSpine -> Basic animation example**
  - **FlameSpine -> SpineComponent with shared data**

# Current bug behavior

Link points to a file that does not exist

# Expected behavior

Link should point to correct source file 

# Steps to reproduce

Visit https://examples.flame-engine.org/#/, navigate to relevant example, click 'See code' on an affected example

# More information

**Comment by spydon** [comment]
For the one picking this up, if you are not used to the monorepo, the examples live in here:
https://github.com/flame-engine/flame/tree/main/examples/lib/stories

**Comment by yoonnikuu** [comment]
I can handle this one! :)
