### ISSUE TITLE
Strange overlapping issue with tilesets using flame_tiled

### ISSUE THREAD

**Issue by invennicoofficial** [flame-engine/flame#2619]
# Current bug behavior

There is a strange overlapping issue occurring at the time of rendering the map. I am using embedded tilesets and external as well. I have tried all the encodings(Base64, CSV), but still facing the same. The map is isometric with 256*128 tile size.
<img width="1512" alt="Screenshot 2023-07-24 at 11 10 40 AM" src="https://github.com/flame-engine/flame/assets/42467816/c1036054-92aa-43b3-8f46-3dbac148614a">

# Expected behavior

![Screenshot 2023-07-24 at 11 11 30 AM](https://github.com/flame-engine/flame/assets/42467816/85d19159-f710-48bf-8980-7ff55317ed3a)

# Steps to reproduce

You will need to load isometric tilesets of 256*128 px size. Connect with me if you want the files.

# Flutter doctor output

```
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F770820d darwin-arm64,
    locale en-IN)
    • Flutter version 3.10.6 on channel stable at
      /Users/ayaanpathan/Desktop/Development/FlutterSDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (11 days ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/ayaanpathan/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.76.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.4.1 22F770820d
      darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

# More environment information

Create a list of more environment information, like:
* Flame version: 1.8.0
* Flame tiled version: 1.12.0
* Platform affected: android, ios, web
* Platform version affected: tested on android 12, iOS 16 and web

# Log information

```
No errors
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/flame-engine) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/flame-engine/flame/issues/2619">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/flame-engine/flame/issues/2619/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/flame-engine/flame/issues/2619/pledge.svg">
</picture>
</a>

**Comment by invennicoofficial** [comment]
@spydon any idea on why this behaviour is happening?

**Comment by spydon** [comment]
> @spydon any idea on why this behaviour is happening?

No idea, I've barely used tiled.
Maybe @ufrshubham @jtmcdole or @Hwan-seok knows?

**Comment by invennicoofficial** [comment]
Thanks @spydon have you worked with isometric maps before? if so, any tool you can suggest which will work for generating readable formats for flame?

**Comment by spydon** [comment]
> Thanks @spydon have you worked with isometric maps before? if so, any tool you can suggest which will work for generating readable formats for flame?

I have only used the `IsometricTileMapComponent`, so not anything where you externally generate the map.

**Comment by invennicoofficial** [comment]
Thanks @spydon

**Comment by Hwan-seok** [comment]
@invennicoofficial 
Could you send your map resources to tttkhs96@gmail.com?
I can't affirm the problem will be discovered but I will give it a try.

**Comment by invennicoofficial** [comment]
Absolutely @Hwan-seok Thank you!!

**Comment by invennicoofficial** [comment]
@Hwan-seok done.

**Comment by jtmcdole** [comment]
Late to the game. What is the tile sizes here? They don't look correct even in the Tiled editor shot you have.

**Comment by chippydip** [comment]
I just realized this may be the same issue I just reported (#2633) with a fix. Is the grid size smaller than your tile size? If so, I believe the scale calculation is incorrect in that case.

**Comment by invennicoofficial** [comment]
Tile size is 256*128

**Comment by invennicoofficial** [comment]
This is my map properties

<img width="442" alt="Screenshot 2023-08-01 at 12 14 20 PM" src="https://github.com/flame-engine/flame/assets/42467816/42385a1d-7772-4698-a5dd-b35cce408d25">

**Comment by chippydip** [comment]
In the Tiled screenshot it looks like each tile is much larger than the map's grid size. Are all of those building individual 256x128 tiles stitched together or is the school (for example) one big ~2560x1280 single tile image that covers multiple grid cells?

**Comment by Hwan-seok** [comment]
![스크린샷 2023-08-02 오전 1 51 41](https://github.com/flame-engine/flame/assets/38072762/200ab675-bbd0-465a-aa01-f5fb0bcfb9d6)

Fine with Flutter 3.7.10, 

But it crashes after upgrading Flutter to 3.10.xx with exactly the same code and dependencies.

**Comment by invennicoofficial** [comment]
> In the Tiled screenshot it looks like each tile is much larger than the map's grid size. Are all of those building individual 256x128 tiles stitched together or is the school (for example) one big ~2560x1280 single tile image that covers multiple grid cells?

@chippydip Yes, all are individual 256X128 tiles stitched together, we've created multiple layers and tile set with each buildings

**Comment by invennicoofficial** [comment]
@Hwan-seok thanks for your snippet, we've tried to same way again with same file but buildings are still overlapping.

**Comment by invennicoofficial** [comment]
@spydon @Hwan-seok @chippydip I've tried to implement the same tmx file into unity game engine and it's working fine but loading same tmx file into flame, I'm facing issue of  overlapping the two buildings.

Can you please help me here with solution so I can quickly apply into the game.

- Unity Game Screenshot 
![image](https://github.com/flame-engine/flame/assets/42467816/cde61d85-c6ad-43a0-80f1-bc959d9e936c)

Note: Firstly, I was getting error of smaller size sprite on unity but once I've update the max size of sprite, the error resolved and works fine on unity.

![image](https://github.com/flame-engine/flame/assets/42467816/beab13a4-5fe4-4ec9-bf29-ed95dc504907)

**Comment by ufrshubham** [comment]
Okay, so I've looked in this problem and it seem like this is happening due to the size limits we use in `RectangleBinPacker` for web.
https://github.com/flame-engine/flame/blob/1485f8426ebb6dd1390a0062c5e83ed1c0461f21/packages/flame_tiled/lib/src/rectangle_bin_packer.dart#L26-L27

Following comment explains why we choose those limits,
https://github.com/flame-engine/flame/blob/1485f8426ebb6dd1390a0062c5e83ed1c0461f21/packages/flame_tiled/lib/src/rectangle_bin_packer.dart#L15-L17

but can't remember if the problem was with just web builds running on Android or was it for web builds on desktop too. If it was just for web-Android, then probably we should check for platform along with `KIsWeb` before reducing the size.

---

From the files shared by @invennicoofficial, I was able to reproduce the problem and can confirm that the bin packer overflows and starts placing the new rects at the top left. This happens because we return `Rect.zero` when the packer is filled.
https://github.com/flame-engine/flame/blob/1485f8426ebb6dd1390a0062c5e83ed1c0461f21/packages/flame_tiled/lib/src/rectangle_bin_packer.dart#L41-L44

I think it would be better if the packer could report that it is overflowing instead of silently overlapping the images. It will at least help the users understand why they are seems the wrong output.

@jtmcdole a question for you:
Is it absolutely necessary to have a single atlas for the whole tilemap? IIRC, this packing was done to optimize the rendering. If so, can't we create a new one once the previous one starts overflowing?

Also, I noticed that we pack all the images from all the tilesets of a map. But it is possible that some tilesets is not event used in the tilemap. This unnecessarily makes the packer run out of space due to images from unused tilesets. Not sure if it is even possible to detect this, but I experienced this problem with embeded tilesets. Even doing a proper export from Tiled wasn't able to get rid of the unused tilesets.

**Comment by ufrshubham** [comment]
> * How big is the tileset being used?

In the example that they shared, each tileset was made up of a single image and average size of images was around **1000x1000**. The total packed size was turning out to be **6885×3274**.


> * Are any of the tiles being flipped? This automatically increases the size of the map.

No.


> * Can it be tiled ahead of time? (would give you ultimate control of the sprite map packing)

This is one solution that I've suggested them to try. But looking at their image dimensions, I think they'll have to create multiple atlas to keep everything under 4k.


> * Do we want to have a fallback to an alternative rendering format with multiple atlas?

Only if we start getting more of such usecases from users. For pixel art style games I don't see us hitting these limits that often.

**Comment by spydon** [comment]
> Just to close the loop, here is what I think can be done for now:
> 
> - Add an assert or debugPrint to let the users know about the overflow. Bluefire team can take a call on this.
> - If possible add some way to let the users override the `maxX` and `maxY`. This will allow them the freedom to use custom sized packer based on their target platform and hardware.

Both good suggestions that would be implemented I think!

**Comment by jtmcdole** [comment]
> If possible add some way to let the users override the maxX and maxY. This will allow them the freedom to use custom sized packer based on their target platform and hardware.

We can do this with environment variables. You will have a bad time on systems that don't support max{XY} though.  This information is AVAILABLE at a webgl layer... but I don't think it is exposed by Flutter. We could write a silly non-flutter, webgl library that checks and returns this information?
