### ISSUE TITLE
Address performance issues of QuadTreeBroadphase collision detection

### ISSUE THREAD

**Issue by filiph** [flame-engine/flame#2622]
# What could be improved

I noticed that when having a lot of moving components with collision detection, the `HasQuadTreeCollisionDetection` algorithm is significantly _slower_ than the standard `HasCollisionDetection` (using `Sweep`). For something like 800 entities, quad tree is about 3 times slower.

<img width="912" alt="Screenshot 2023-07-23 at 19 09 31" src="https://github.com/flame-engine/flame/assets/919717/e2dfb567-10de-4a7e-83ab-70fba47da7c2">

<img width="912" alt="Screenshot 2023-07-23 at 19 08 43" src="https://github.com/flame-engine/flame/assets/919717/b73bdc0d-dfc1-46fb-b28d-6ccb7a7c51b8">

(Sidenote: the "benchmark" code isn't trying to be particularly _correct_ — you can see that many objects that are clearly colliding are white instead of red. This is because we're just blindly switching colors on collision start and on end, and don't care whether there are other collisions active. My point is to stress the collision detection code, not to build a simulation.)

I realize no optimization is a good fit for all cases, but this was a surprise to me, as I thought that QuadTree would deal with this exact case (lots of moving objects, some of which are far away from each other) better than the default.

I looked into it in profile mode, and it seems that a _lot_ of the slowness comes from adding things into the `HashSet` of `CollisionProspect`s and doing other operations on various Sets. 

<img width="1428" alt="Screenshot 2023-07-24 at 13 59 19" src="https://github.com/flame-engine/flame/assets/919717/6dacd489-d630-4054-98e3-ae82796524fe">

<img width="427" alt="Screenshot 2023-07-24 at 13 59 31" src="https://github.com/flame-engine/flame/assets/919717/fd3a53bb-ea50-457f-b425-31920260e4d5">

<img width="433" alt="Screenshot 2023-07-24 at 14 00 14" src="https://github.com/flame-engine/flame/assets/919717/f04f6ce6-463e-42f1-91ed-9a9047b5143e">

I tried different low-effort optimizations (such as caching `CollisionProspect`'s `hashCode` or trying different ways to implement `CollisionProspect.==`) but nothing yielded significant improvements. It's of course possible that I'm missing something obvious, but I'm thinking that maybe the whole approach of using Sets of prospects might need to be rethought. 

One idea I had was to try to implement a much simpler broadphase algorithm (based on a simple grid of static proportions). But I think the current API would still force me to use Sets of prospects, which could undermine any performance improvements over `Sweep`.

I'm seeking opinions and feedback. Maybe I'm just holding it wrong?

Code of my simple "benchmark" in [this repo](https://github.com/filiph/flame-collision-benchmark). DartPad here:
https://dartpad.dev/?id=a36320487f5a18fd6418f1db1e21a1da

# Why should this be improved

Movement of a lot of collidable objects on a large map is a prerequisite for quite a lot of 2D game genres (shoot 'em ups, RTS, physics games, etc.).

It should be easy to make this relatively fast, and potential pitfalls should be documented.

# Any risks?

- The options I see could lead to breaking changes of the CollisionDetection API (especially for the "internals" — when someone is providing their own `Broadphase` — other users might not even notice).
- This could be a lot of finicky work that ultimately only serves a small minority of Flame users.

# More information

I'd be interested in taking this on but I have trouble gauging how big of a problem this is for Flame as a whole. My game is pretty special in that it has a big world with lots of entities — but that might be an outlier. I'd hate to work on a scalable solution to a problem that only a few people actually have. In such cases, my policy is to solve only the particular problem at hand (my own game) and document it, instead of throwing hours of work at an "elegant" solution that isn't needed (YAGNI).

**Comment by spydon** [comment]
Thanks for a well written issue! I have seen this behavior previously before too on the quad tree implementation.
@ASGAlex has done a lot more work on this after the current QuadTree broadphase was released, so he might  be able to provide some insights too.

> But I think the current API would still force me to use Sets of prospects, which could undermine any performance improvements over Sweep.

I think we could create a breaking change and use another type than sets here.

> The options I see could lead to breaking changes of the CollisionDetection API (especially for the "internals" — when someone is providing their own Broadphase — other users might not even notice).

What options have you thought about?

**Comment by spydon** [comment]
That would make it impossible to run with different broadphases though, so I don't think that is an option unfortunately, since in the more advanced cases you sometimes have to have a broadphase that is specific to your use-case.

An optimization that I see directly is that we should make the `CollisionProspect` mutable and start pooling it.
I see there are new lists created in the quad tree implementation that are very easy to get around too.

**Comment by ASGAlex** [comment]
Quad Tree is not a good thing for continuously moving objects, because it become necessary to recalculate all spatial partitioning for every run. You need a static spatial grid for such purposes and yes, you need to cache everything you can.

Every Quad Tree modification will not solve your problem. I think it's future in Flame engine should be like staying in it's current state, receiving bug-fixes and compatibility patches only.

I can suggest you to try my experimental library, it has statical partitional grid and works with object's speed and size , offers advanced type filtering and so on to reduce collision checking as much as possible ...
But I am not sure that architecture is final and of course not all bugs are solved.

https://github.com/ASGAlex/flame_spatial_grid

You can check a live demo, press C to spawn more moving components and compare performance with another approaches. I'm sure, my will be faster 🤟

I have plans to port it into Flame, but it will not happen too soon

**Comment by filiph** [comment]
Got it, thanks both!

What would you say, @ASGAlex, is the best-case scenario for QuadTreeBroadphase? Is it a game with, say, 70-90% non-moving entities (such as a platformer)? I think that if we come up with some guidance, we can put it in the API docs, at the very least. Something like:

```dart
/// Use [HasQuadTreeCollisionDetection] if you have lots of collidable entities in your game,
/// but most of them are static (such as platforms, walls, trees).
```

I think that would address this issue, and I'm happy to create the PR.

Also, I love that you're already working on a spatial grid implementation. Is this meant to become a `Broadphase` subclass at some point? (Something like `SpatialGridBroadphase`?) Or is that a separate approach? (Just curious. This is not blocking this issue.)

**Comment by ASGAlex** [comment]
I'm not sure about exact list of game type such as platformer and so on... With QuadTree you can make something like old-school Fallout or Arcanum but without map streaming. With QuadTree you can also create a classic RTS, but not something such epic as Supreme Commander is. With Spatial grid you have a chance, but the chance would be bigger with normal multithreading support and with shared memory, but Dart is too limited here, sadly.

My custom spatial grid implementation already extends core Flame classes, just check the sources. I prefer to write separate compatible library first, rather then to modify engine itself for every R&D experiment. And after creation of such separate library - to move well-tested features with stable architecture into the Engine one-by-one. But this is a long story. So if you need a solution right now - just use the library. Maybe next year it will be ported to engine, at least it's core part. But! Maybe not 🤷🏽‍♂️😔 This is just hobby project, I'm even not a Flutter developer in my everyday work.

**Comment by filiph** [comment]
Thanks!

What do you think about the proposed doc comment, then?

```dart
/// Use [HasQuadTreeCollisionDetection] if you have lots of collidable entities in your game,
/// but most of them are static (such as platforms, walls, trees).
```

I know there are exceptions, and exceptions to exceptions, and so on. But I believe it's better to say something than to leave folks to learn this lesson the hard way.

**Comment by ASGAlex** [comment]
I'm agree, that additional doc comment might be useful, along with explaining same things at Flame *.md documentation.
I'm not so risky to write documentation longreads because of compassion to @spydon , who always corrects my crooked English 😂

**Comment by filiph** [comment]
Thanks, I'm going to prepare a PR soon.

For what it's worth, my very simplistic benchmark does show an increase in performance when I make most of the components static (as in, I don't move them) but it's still a lot slower than `Sweep`.

<img width="912" alt="Screenshot 2023-07-24 at 21 34 52" src="https://github.com/flame-engine/flame/assets/919717/d30937e1-82ad-40ed-9028-576234a44850">

<img width="912" alt="Screenshot 2023-07-24 at 21 40 41" src="https://github.com/flame-engine/flame/assets/919717/5115a620-c93d-4526-b417-22f0b8e0bf27">

<img width="912" alt="Screenshot 2023-07-24 at 21 42 33" src="https://github.com/flame-engine/flame/assets/919717/262450cc-a224-47e0-9b7d-bf0578e8a370">

What do you think, @ASGAlex? Is it because the entities are too close together and too uniformly distributed for the QuadTree optimization to really kick in?

**Comment by ASGAlex** [comment]
It looks like you faced the main issue of QuadTree algorithm itself, I described it in my article https://asgalex.medium.com/make-flame-32-times-faster-with-collision-detection-and-additional-tricks-3c212404b0b0 at "Problems" section. Unfortunately, there is no fix. And this is another reason why I think that Quad Tree itself does not worth any additional performance improvements: it always will have this general problem and general limitations. We just need to find a better approach.
