### ISSUE TITLE
Handling events with HUD and World components

### ISSUE THREAD

**Issue by NashIlli** [flame-engine/flame#2623]
# Current bug behavior
In the screen I see a HUD component over a World component. But the event is handled by the world element first.
It is happening in Flame 1.8. In version 1.7 it works properly without the CameraComponent. Since Flame 1.8 the old camera is deprecated, I tried to migrate to CameraComponent and it didnt work in the same way.

# Expected behavior
The event should be handled first by the element that is visible and then, if it continues the propagation, could be handled by the covered component.

# Steps to reproduce
1. Add World and camera component to the FlameGame
2. Add a component to the world with size 100x100, position (0, 0) and with TapCallbacks.
3. Add a HUD component (add the component to the cameraComponent viewport) at position (0, 0) and 100x100 size with Tap Callbacks.
4. The Hud component is renderized over the world component. 
5. Tap the hud component, and the event is handled first by the world component. The world component is the first who handle the OnTap events.

# Flutter doctor output
Output of: flutter doctor -v
[✓] Flutter (Channel stable, 3.10.6, on Ubuntu 22.04.2 LTS 5.19.0-46-generic, locale en_US.UTF-8)
    • Flutter version 3.10.6 on channel stable at /home/kirby/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (12 days ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /home/kirby/Android/Sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /snap/android-studio/126/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2022.2)
    • Android Studio at /snap/android-studio/126/android-studio
    • Flutter plugin version 74.0.2
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Connected device (3 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Linux (desktop)            • linux         • linux-x64      • Ubuntu 22.04.2 LTS 5.19.0-46-generic
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 115.0.5790.98

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by spydon** [comment]
I'll just copy what I wrote in Discord so that we don't forget:
> I think I know what the problem is, it's that the world is added to the tree before the viewport is, so when the events trickle through the tree it will first hit the world.

**Comment by spydon** [comment]
Could you try running your code on `main`? Because I see now that we've added `super.priority = -0x7fffffff,` to the world, so it should be hit after the `CameraComponent`.
To use `main`, just put this into your pubspec instead of your current Flame entry:
```yaml
flame:
  git:
    url: https://github.com/flame-engine/flame.git
    path: packages/flame
    ref: main
 ```

**Comment by spydon** [comment]
Ah nvm, that change is already released.
