### ISSUE TITLE
flame_tiled: Isometric tiles not scaled properly when image size does not match the map tile size.

### ISSUE THREAD

**Issue by chippydip** [flame-engine/flame#2633]
# Current bug behavior
Tiles larger than the map's grid size are resized so they fit into the map's grid:
![image](https://github.com/flame-engine/flame/assets/552649/3b9f4b5c-975a-452d-bd14-fb086ef12b8a)

# Expected behavior
Tiles should overflow the map's grid when they are naturally larger than the cells:
![image](https://github.com/flame-engine/flame/assets/552649/85ba6991-335e-4e38-8423-fdc0f33c5e87)

# Steps to reproduce
- Create a tileset in Tiled (eg with 96x48 tiles)
- Create an Isometric map with a smaller grid size (eg 48x24)
- Place some tiles and load the tmx file into a RenderableTileMap
- Notice the tiles are spaced twice as far apart as they appeared in the Tiled editor

# More environment information
* Flame version: 1.8.1
* flame_tiled version: 1.12.0

# More information
It appears that `IsometricTileLayer` is computing the `scale` value incorrectly. Scale is currently calculated by dividing the destination tile size by the natural size of the tile image. Instead, the scale should be computed by diving the destination tile size by the map's native tile size. If the images are the same size as the map's tiles then these result in the same scale factor, but if larger images are placed on a smaller grid the resulting scale factor is incorrect (compared to the preview in the Tiled editor).

I can PR this fix in `isometric_tile_layer.dart`:
```
-        final scale = size.x / src.width;
+        final scale = size.x / map.tileWidth;
```

# Fixed behavior
![image](https://github.com/flame-engine/flame/assets/552649/4169afea-2631-40d8-9e43-505daca28c96)
Notice no gaps and the tiles are twice as large at 100% scale, matching what appears in the Tiled editor.

**Comment by jtmcdole** [comment]
Nice find. I hadn't tested out any tiles with padding in Tiled.
