### ISSUE TITLE
Can't set FixedResolutionViewport in FlameGame

### ISSUE THREAD

**Issue by adil192** [flame-engine/flame#2637]
# Current bug behavior
I first tried to set the viewport with `camera.viewport = FixedResolutionViewport(...);` but the `camera` getter is [deprecated and says to use a `World` and `CameraComponent`](https://github.com/flame-engine/flame/blob/c542d3c34bf911cec8332dcdeb65d0017e6cb576/packages/flame/lib/src/game/flame_game.dart#L41-L71).

I did as instructed and tried to set the viewport with `cameraComponent.viewport = FixedResolutionViewport(...);` but `viewport` is final. So then I tried to set the viewport in the constructor:
```dart
cameraComponent = CameraComponent(
  world: world,
  viewport: FixedResolutionViewport(
    Vector2(1000, 2000),
    clip: false,
  ),
);
```
but I get this error:
`The argument type 'FixedResolutionViewport' can't be assigned to the parameter type 'Viewport?'.dart[argument_type_not_assignable](https://dart.dev/diagnostics/argument_type_not_assignable)`

# Expected behavior
An easy way to set a `FixedResolutionViewport`. If I'm doing something wrong, the correct code snippet should be added to the relevant [documentation](https://docs.flame-engine.org/latest/flame/camera_and_viewport.html#viewport) .

# Steps to reproduce

I tried to set this up in zapp but it's using an old version of Flutter/Dart/Flame which doesn't have the deprecation, so I've just pasted the snippet here:
```dart
import 'package:flame/camera.dart';
import 'package:flame/game.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(
    GameWidget(
      game: MyGame(),
    ),
  );
}

class MyGame extends FlameGame {
  late final world = World();
  late final CameraComponent cameraComponent;

  @override
  Future<void> onLoad() async {
    await super.onLoad();

    cameraComponent = CameraComponent(
      world: world,
      viewport: FixedResolutionViewport(
        Vector2(1000, 2000),
        clip: false,
      ),
    );
    addAll([cameraComponent, world]);
  }
}
```

# Flutter doctor output

```
[✓] Flutter (Channel stable, 3.10.6, on Pop!_OS 22.04 LTS 6.4.7-surface, locale en_GB.UTF-8)
    • Flutter version 3.10.6 on channel stable at /home/ahanney/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (3 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/ahanney/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /home/ahanney/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.10121639/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1.1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2022.2)
    • Android Studio at /home/ahanney/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.10121639
    • Flutter plugin version 74.0.2
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.70.0

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Pop!_OS 22.04 LTS 6.4.7-surface

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

# More environment information

- Flame version: 1.8.1
- Flutter 3.10.6
- Platform affected: all

# Log information

# More information

Messing with the types a little reveals that we have two `Viewport` classes. Is this intentional?
- 'package:flame/src/camera/viewport.dart (via package:flame/camera.dart)'
- 'package:flame/src/game/camera/viewport.dart (via package:flame/game.dart)'

**Comment by wolfenrain** [comment]
The `FixedResolutionViewport` is from the old API, you either need to use `FixedSizeViewport` or `FixedAspectRatioViewport` depending on what you want to achieve.

See the docs for more information: https://docs.flame-engine.org/latest/flame/camera_component.html#viewport

**Comment by adil192** [comment]
Oh I see, I was using https://docs.flame-engine.org/latest/flame/camera_and_viewport.html.

**Comment by ufrshubham** [comment]
You can use `CameraComponent.withFixedResolution` to achieve the same results with the new camera system.
