### ISSUE TITLE
Rogue Shooter demo has poor performance on Linux desktop

### ISSUE THREAD

**Issue by CyberShadow** [flame-engine/flame#2640]
Hi! I am evaluating Flutter and maybe Flame as a platform for updating an old video game.

In doing so, I tried out the demo games in this repository, and I noticed some performance issues:

1. Looking at the FPS display in Rogue Shooter, it seems to never go above 60 FPS, even when the monitor it's on is running at a higher refresh rate. It might be limiting itself to the maximum refresh rate of the wrong monitor, or it might simply not be able to run faster than 60 FPS.
2. The demo game exhibits regular stuttering. Every few seconds, it seems to drop about 100ms or more worth of frames. This is also visible in the line of bullets fired by the player-controlled ship: when the stutter occurs, there is a "break" in the otherwise-continuous line of bullets.

![image](https://github.com/flame-engine/flame/assets/160894/26d27aea-402d-4399-8b2c-53f42789ffa7)

By the way, I also noticed that I had to run `flutter create --platforms=windows,macos,linux .` to enable targeting the Linux desktop.

# Current bug behavior
Low performance

# Expected behavior
For such a game on good system specs, I think it would be completely reasonable to expect perfectly smooth full FPS with no stutter.

# Steps to reproduce
In `examples/games/rogue_shooter`, run `flutter create --platforms=windows,macos,linux` and then `flutter run -d linux --release`.

# Flutter doctor output

```
[✓] Flutter (Channel main, 3.13.0-17.0.pre.71, on Arch Linux 6.4.4-arch1-1, locale en_US.UTF-8)
    • Flutter version 3.13.0-17.0.pre.71 on channel main at /mnt/2020-nvme-2t-raid/@fastscratch/moved/home/vladimir/opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c09a9b4c46 (32 hours ago), 2023-08-05 19:20:34 -0400
    • Engine revision cdafc05a72
    • Dart version 3.2.0 (build 3.2.0-41.0.dev)
    • DevTools version 2.26.1

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/vladimir/opt/adt/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 15.0.7
    • cmake version 3.27.0
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[✓] Android Studio (version 2022.2)
    • Android Studio at /mnt/2020-nvme-2t-raid/@fastscratch/moved/home/vladimir/opt/android-studio
    • Flutter plugin version 74.0.2
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Community Edition (version 2023.1)
    • IntelliJ at /usr/share/idea
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Arch Linux 6.4.4-arch1-1
    • Chrome (web)    • chrome • web-javascript • Chromium 115.0.5790.102 Arch Linux

[✓] Network resources
    • All expected network resources are available.
```

# More environment information

* Flame version: dac2ebbf506ff48ca8f34d872bbc47cba3ad6c7b
* Platform affected: Linux desktop
* Platform version affected: Linux 6.4.4, Xorg 21.1.8

# Log information
N/A

# More information
N/A

**Comment by spydon** [comment]
1. This is either a problem of your machine reporting 60hz to Flutter or a problem in Flutter, the first is the most likely, try with only having one display that is capable of >60hz connected (check `xrandr` to verify).
2. This might be the Dart GC kicking in, not much we can do about that unfortunately. It most likely doesn't happen if you have a lower amount of components on the screen, this example is meant to test the extremes.

**Comment by CyberShadow** [comment]
Thanks!

> the first is the most likely

I disagree, I have not seen this type of problem with other types of graphics applications (web browsers, native Linux games, Windows games emulated in Wine or Proton).

Flutter might be using an old API (e.g. something pre-RandR) and getting confused from that, will have a look in that direction.

> not much we can do about that unfortunately.

I think it would be helpful to clearly document the current performance limitations in the README, so that users don't expect too much.

**Comment by CyberShadow** [comment]
> None of those are Flutter applications though, my comment was specifically about Flutter picking up the wrong refresh rate from your machine.

Ah, sorry for the misunderstanding.

> And it isn't?

I don't know; I would guess that it wasn't. I was seeing a little bit of stutter with the other demos, but I did not try to measure it objectively.

Are there any action games (i.e., games with a high learning curve where an experienced player might get frustrated by poor performance or stuttering) that use the Flame engine that I could try running on Linux?

**Comment by CyberShadow** [comment]
> I don't know what we would write that would explain the limitations, since the upper boundary depends on Flutter and the hardware that you are running on.

One approach would be to try to implement the same game in different video game engines, and collect objective benchmarks of all implementations. That would allow readers to judge where the performance of Flame is compared to the competition. Something like https://arewefastyet.com/

**Comment by spydon** [comment]
> Then, perhaps such a program is more suitable as a benchmark rather than an example or demo.

That is exactly what it is, this is what it says in the readme of the demo: 😅

"Flame Performance Test Game

Simple scrolling shooter game used for testing the performance of Flame."

Maybe the word benchmark should be included to make it even clearer, but I think that it is pretty clear already?

> Are there any action games (i.e., games with a high learning curve where an experienced player might get frustrated by poor performance or stuttering) that use the Flame engine that I could try running on Linux?

Maybe @yasfdany could give you a Linux build of Gunslinger that you could try. :)

>One approach would be to try to implement the same game in different video game engines

If anyone wants to spend time on that we are of course open to include such a benchmark, we have way too many things to do ourselves in the core team to put time into that. I'm not sure that it would give that much either honestly, everyone knows that game engines written in low level languages will be faster.

**Comment by ufrshubham** [comment]
> One approach would be to try to implement the same game in different video game engines, and collect objective benchmarks of all implementations.

This is not very maintainable approach. Making the same game in different engine means we'd have to know the other engine in and out to make the comparison fair. Creating non-optimal game is xyz engine and comparing it with flame would be the worst. Plus someone will have to maintain all the ports, because engines keep releasing new updates. Unless someone is willingly ready to maintain these extra codebases, I don't think it will work.

Also, I vaguely remember @spydon once saying that the Rouge Shooter is not exactly optimized. It is more of a stress test than a tech demo.

**Comment by yasfdany** [comment]
> 

Unfortunately, I can't build the Linux build for you because there are a lot of dependencies that I use that don't support Linux, therefore I tried Linux build a long time ago and yes the performance of the Linux build isn't that good. but I think it's not Flame Engine problem it's Flutter desktop performance problem in general, Flutter web is slightly better in terms of performance.

**Comment by yasfdany** [comment]
> > Then, perhaps such a program is more suitable as a benchmark rather than an example or demo.
> 
> That is exactly what it is, this is what it says in the readme of the demo: sweat_smile
> 
> "Flame Performance Test Game
> 
> Simple scrolling shooter game used for testing the performance of Flame."
> 
> Maybe the word benchmark should be included to make it even clearer, but I think that it is pretty clear already?
> 
> > Are there any action games (i.e., games with a high learning curve where an experienced player might get frustrated by poor performance or stuttering) that use the Flame engine that I could try running on Linux?
> 
> Maybe @yasfdany could give you a Linux build of Gunslinger that you could try. :)
> 
> > One approach would be to try to implement the same game in different video game engines
> 
> If anyone wants to spend time on that we are of course open to include such a benchmark, we have way too many things to do ourselves in the core team to put time into that. I'm not sure that it would give that much either honestly, everyone knows that game engines written in low level languages will be faster.

> 

Unfortunately, I can't build the Linux build for you because there are a lot of dependencies that I use that don't support Linux, therefore I tried Linux build a long time ago and yes the performance of the Linux build isn't that good. but I think it's not Flame Engine problem it's Flutter desktop performance problem in general, Flutter web is slightly better in terms of performance.

**Comment by CyberShadow** [comment]
> Maybe the word benchmark should be included to make it even clearer, but I think that it is pretty clear already?

Ah... To be honest, it is not clear to me. The goal that the program attempts to accomplish at first glance does not seem unreasonable to me. There are many games which can display a very large number of enemies with complicated animations and AI, not to mention collision detection. 

Is it the *method* that it is trying to accomplish that goal that's important - i.e., is it using an intentionally slow method for the sake of benchmarking a particular aspect of Flamer or Flutter or demonstrating a particular technique?

> everyone knows that game engines written in low level languages will be faster.

Well, for example most Unity games use C# for scripting, which also includes a garbage collector. I think a comparison with Unity would not be unreasonable.

The language that the *engine itself* is written in seems like an implementation detail to me. Unity exposes a C# (.NET) API, which may or may not mean that it was once written in C#; it might be written in C++ now and something else tomorrow, which won't matter to users unless the API changes.

> Creating non-optimal game is xyz engine and comparing it with flame would be the worst. 

Actually, I think it should not be optimal; it should be done in the most straight-forward way possible, i.e. which would correspond to how an average developer would try to implement it according to the official documentation and examples. Hope that makes sense.

> Plus someone will have to maintain all the ports, because engines keep releasing new updates.

I think specifying the version of the engine used for the benchmark would be enough, and already very honest by itself, to be honest.

> Unfortunately, I can't build the Linux build for you because there are a lot of dependencies that I use that don't support Linux, therefore I tried Linux build a long time ago and yes the performance of the Linux build isn't that good. but I think it's not Flame Engine problem it's Flutter desktop performance problem in general, Flutter web is slightly better in terms of performance.

Thanks! What about a native Windows version?

**Comment by spydon** [comment]
> Ah... To be honest, it is not clear to me. The goal that the program attempts to accomplish at first glance does not seem unreasonable to me. There are many games which can display a very large number of enemies with complicated animations and AI, not to mention collision detection.

I'll try to clarify the readme later then.

> Is it the method that it is trying to accomplish that goal that's important - i.e., is it using an intentionally slow method for the sake of benchmarking a particular aspect of Flame or Flutter or demonstrating a particular technique?

Nope, it is just doing collision detection with many hitboxes involved, and during development this example can be used to try out different broadphase methods.

> Well, for example most Unity games use C# for scripting, which also includes a garbage collector. I think a comparison with Unity would not be unreasonable.

None of the performance critical systems are implemented in C# though, like collision detection in this case.

> Actually, I think it should not be optimal; it should be done in the most straight-forward way possible, i.e. which would correspond to how an average developer would try to implement it according to the official documentation and examples. Hope that makes sense.

If you want to work in it, go ahead, but otherwise I don't think it is going to happen. 😉

**Comment by CyberShadow** [comment]
> therefore I tried Linux build a long time ago and yes the performance of the Linux build isn't that good. but I think it's not Flame Engine problem it's Flutter desktop performance problem in general, Flutter web is slightly better in terms of performance.

If you know of any issues on the Flutter bug tracker that track the performance problems you've seen, please share them, as I would be interested in following Flutter's progress on performance.
