### ISSUE TITLE
It would be nice to allow flame_tiled to load assets from directories OTHER than the hardcoded one

### ISSUE THREAD

**Issue by JosephCarrington** [flame-engine/flame#2641]
# What could be improved

At present, all tiled files must be located in `assets/tiles/`. It would be nice if we could specify an asset path.

# Why should this be improved

This is a problem if the software that implements flame_tiled is being used as a package that another codebase relies on, as we don't have access to `assets/tiles` at that point. Also, if we wanted to download a tsx from the internet and parse that, I am not sure we can write files to the assets directory.

# Any risks?

I suspect that if you follow the same practices as other flame subpackages (ie: `assets/tiles/` is default but changeble) then there would be no issues. I would do it myself but don't know how to write tests for Dart yet.

# More information

I am interested in working on a PR for this, but need to learn how to write Dart tests first.

**Comment by spydon** [comment]
Sounds like a good idea, should be fairly simple to add just an optional argument to the load method. :)
