### ISSUE TITLE
Separate timeScale for forge2d world

### ISSUE THREAD

**Issue by tibotix** [flame-engine/flame#2648]
# Problem to solve

The [`HasTimeScale`](https://docs.flame-engine.org/latest/flame/other/util.html#time-scale) mixin only works on `Components` that use `update` to update its state. `BodyComponents` however rely on the Forge2D `World` class to update the state according to the physics. In the `Forge2DGame` class this is done in `update`:
```dart
class Forge2DGame extends FlameGame {
  // [...]
  @override
  void update(double dt) {
    super.update(dt);
    world.stepDt(dt);
  }
  // [...]
}
```
Now, my feature request adresses the issue i have when i want to timeScale the Forge2DWorld separately from the "normal" Flame logic. 

# Proposal

The obvious and simplest solution is to add a mutable `forge2DTimeScale` (naming can be adjusted of course) member variable to the `Forge2DGame` which would be used inside the `update` method:
```dart
class Forge2DGame extends FlameGame {
  // [...]
  @override
  void update(double dt) {
    super.update(dt);
    world.stepDt(dt * forge2DTimeScale);
  }
  // [...]
}
```
we could of course also hide the `forge2DTimeScale` variable behind a public get/set or increase/decrease API.

Alternatively we could make the timeScale specific to each `BodyComponent`. I honestly have no idea how difficult that would be in terms of physics caluclation and solving.

# More information

If we can agree to a plan on how to implement this feature i would be willing to work on a PR for this.

**Comment by spydon** [comment]
You can't have different timescales for different bodies in Forge2D, that would completely break the physics, so the only place to do this now is in the `Forge2DGame` and I don't think this is a feature that we want to bundle in that class.
You can of course still apply `HasTimeScale` directly to your `Forge2DGame` though and it'll slow down everything, or just override it like you've done and only apply the changed `dt` to the Forge2D world.

**Comment by tibotix** [comment]
Okay, yeah i thought that wouldn't work well with the physics.
I preferably not have to make my own version of `Forge2DGame` and override the `update` method of `FlameGame` this way, as it would eventually become inconsistent with future versions of the original `Forge2DGame`, but maybe thats not a big deal though (Note that i cannot just subclass `Forge2DGame`, as when calling `super.update()`, `world.stepDt(dt)` would still be called inside the `Forge2DGame.update` method). 
Maybe a better place for such a timeScale variable is the `World` class. This way the user can access the world through `Forge2DGame.world` and change the timeScale.
Maybe we could also refactor the `world.stepDt(dt)` part in `Forge2DGame.update` out to a separate method which then can be more easily overwritten by a subclass/Mixin.
Anyway, do you think this feature can be covered by flame/forge2d, or is it the users responsibility to implement this.

**Comment by spydon** [comment]
> Note that i cannot just subclass Forge2DGame, as when calling super.update(), world.stepDt(dt) would still be called inside the Forge2DGame.update method

You can, just don't call `super.update`, call `super.updateTree` instead.

> Anyway, do you think this feature can be covered by flame/forge2d, or is it the users responsibility to implement this.

I think this will have to be up to the user, since I think the group that needs this use-case is very small (you're the first that has asked for it).

The `Forge2DGame` is currently being refactored to use the `CameraComponent` and I think the overrides will be easier to do once that refactor is done.

**Comment by tibotix** [comment]
> You can, just don't call super.update, call super.updateTree instead.

Oh, i see. Thanks for pointing this out. 

> I think this will have to be up to the user, since I think the group that needs this use-case is very small (you're the first that has asked for it).

Okay that seems fair. 

> The Forge2DGame is currently being refactored to use the CameraComponent and I think the overrides will be easier to do once that refactor is done.

Okay, sounds good. 

As far as i am concerned this issue can be closed now, maybe in future versions or if more people ask for this feature it can be reopened. Thanks for your suggestions.
