### ISSUE TITLE
potential memory leak

### ISSUE THREAD

**Issue by MiaoShichang** [flame-engine/flame#2654]
I have discovered a potential memory leak, but I am not sure.

https://github.com/flame-engine/flame/blob/d08284ddcaf5d2ad6e5312336a71a113702dc241/packages/flame/lib/src/game/game.dart#L334

Game holds overlays, overlays also holds game,  i did not find where it is be broke .

**Comment by spydon** [comment]
I don't follow, how would this be a memory leak?

**Comment by MiaoShichang** [comment]
for example

```dart
class One {
  late Two two = Two(this);
}

class Two {
  One one;
  Two(this.one);
  
  void putout(){
    print("class Two");
  }
}

void main(){
  One one = One();
  one.two.putout();
}
```

**Comment by spydon** [comment]
I still don't understand, why would this be a memory leak? Both `One` and `Two` is needed here, i.e. no GC should clean them up.

**Comment by MiaoShichang** [comment]
Circular references refer to two or more objects that refer to each other, making them unable to be garbage collected.

now , the One refer to Two and Two refer to One,  making them unable to be garbage collected.

**Comment by spydon** [comment]
The Dart GC is smart enough to handle circular references (almost all GCs are nowadays), when `One` is not referenced anymore it will be able to determine that it is not connected to the tree anymore, even though `Two` is referencing `One`.

**Comment by MiaoShichang** [comment]
```dart
class One {
  late Two? two = Two(this);

  void remove() {
    two = null;
  }
}

class Two {
  One? one;
  Two(this.one);

  void remove() {
    one = null;
  }

  void putout() {
    print("class Two");
  }
}

void main() {
  One one = One();
  one.two?.putout();

  one.remove();
  // or
  // one.two?.remove();
}
```

i think this code is correct.

**Comment by spydon** [comment]
This is not needed, the GC will handle it already. :)
Set `one = null` after your call and you can see for yourself.

**Comment by spydon** [comment]
Yes: https://docs.flutter.dev/tools/devtools/memory#reachability
