### ISSUE TITLE
feat(component): Visibility support

### ISSUE THREAD

**Issue by projectitis** [flame-engine/flame#2669]
# Problem to solve

Often a component needs to stay on the tree, but just be invisible for a while.

The [suggested method](https://stackoverflow.com/questions/71971021/show-hide-a-spritecomponent-using-flame-in-flutter) (?) is to remove them from the tree. Adding and removing them has several problems:
- It's an async operation, and a remove followed by an immediate add again can cause issues
- Lifecycle events are fired, when all you want to do is not render the component

# Proposal

~~Mixin~~ A change (and `visibilty` flag) that adds visibility to components while still on the tree.

# More information

With suggestions from maintainers on how this could best be implemented, I'd be willing to contribute it.

**Comment by spydon** [comment]
Hmm, how were you planning to do this with a mixin? I'm imagining that it would use `renderTree`, but it wouldn't be able to cancel out the `renderTree` from the component?

**Comment by projectitis** [comment]
I hadn't really looked in to it yet. Just seemed to be a good first suggestion :) 
Do you know if there is any reason it wasn't implemented?

**Comment by spydon** [comment]
Well due to the reason that I don't think it is possible to do it with a mixin. 😅
But you can try!

**Comment by projectitis** [comment]
Forget I said mixin 🤣 
Sounds like it should be an addition to a base class at a lower level?

**Comment by projectitis** [comment]
Well, this seems to work just fine.
Any reservations before I continue and do further testing, update docs etc?

```dart
mixin Visible on Component {
  bool visible = true;

  @override
  void renderTree(Canvas canvas) {
    if (visible) {
      super.renderTree(canvas);
    }
  }
}
```

**Comment by spydon** [comment]
Right, it will work in the cases where the component that you use the mixin on hasn't overridden `renderTree` (then it will call both the mixin and the local override, no matter the value of `visible` is), but I think that is such a rare use-case that it can be accepted, just make sure to add a note in the docs about it.

I would name the mixin `Visibility` and the variable `isVisible`, other than that it looks good!

**Comment by projectitis** [comment]
Ah yes, I see what you mean.  As well as maybe being rare - in that case the author can manually add a check for `isVisible` to their custom `renderTree` method, since they are authoring the component.

Agree with your suggestions 👍

**Comment by projectitis** [comment]
```
The name 'Visibility' is defined in the libraries
- 'package:flame/src/components/mixins/visibility.dart (via package:flame/components.dart)'
- 'package:flutter/src/widgets/visibility.dart'.

Try using 'as prefix' for one of the import directives, or hiding the name from all but one of the imports
```

@spydon do you prefer:

- Change the name of my mixin (e.g. `HasVisibility`) ?
- Add documentation to tell the developer to hide the other imports (i.e. hide flutter's widget visibility package) ?

**Comment by spydon** [comment]
Ah, I don't think many try to import widget imports in their components, but let's go with `HasVisibility` anyways.

**Comment by projectitis** [comment]
I don't mind changing it back to `Visibility` if that is preferred. I prefer it myself :grin:
