### ISSUE TITLE
Adding Linux support for Example project

### ISSUE THREAD

**Issue by guyluz11** [flame-engine/flame#2670]
When running `Example` project on Linux I am getting an error that Linux support is currently not supported for this project.

# What could be improved

As suggested by the flutter debuger in the console there are simple instructions in [flutter site](https://docs.flutter.dev/platform-integration/desktop#add-desktop-support-to-an-existing-flutter-app) to add support for more platforms.
Just running the commend `flutter create --platforms=windows,macos,linux .` will do

# Why should this be improved

So that new users who try to run `Example` project will have more options.
Sometimes developing apps on desktop native is faster because of build time and grater performance.
And the change required for that is so small there is no reason not to do so. 

# Any risks?

Safe

# More information

 
Interested working on this pr

**Comment by spydon** [comment]
As you can see here we don't have any of the platform specific directories added to the example app:
https://github.com/flame-engine/flame/tree/main/packages/flame/example

And it's not something that we want to have in the repository either, the readme for the example app could be improved to say that the user is responsible for running `flutter create` with the platforms that they want to run it on.

**Comment by guyluz11** [comment]
Thanks for the quick response.
Will close the issue
