### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by erf** [flame-engine/flame#268]
Hi. I'm considering Flutter for game dev and i'm curious regarding performance compared to other cross platform frameworks like Love2d / Corona etc., where you have a C++ / OpenGL library, handling the low level graphics stuff, with Lua on top. I know Flutter is using Skia, which is a low level library, and using OpenGL / Metal for rendering, but i wonder if you are able to tap into those low level API's in order to access this performance for fast rendering of let's say lot's of 2d sprites / textured quads etc, in the same manner that other mentioned frameworks would, which is built for this use case specifically. I have not looked deep into this framework or low level Flutter rendering capabilities yet, but i'm happy if you could explaing performance / limitations. Also if the Dart language or garbage collection causing performance degrade. Are there any benchmarks?

**Comment by ProgrammingLife** [comment]
Depends on your needs. What type of games are you going to develop? If something like crosswords, sudoku, japan crosswords or some other puzzle games where you don't have forever animation so you don't need to update screen every frame than performance might be increased in many times by solving this issue :) https://github.com/flame-engine/flame/issues/110

**Comment by erickzanardo** [comment]
> Hi. I'm considering Flutter for game dev and i'm curious regarding performance compared to other cross platform frameworks like Love2d / Corona etc., where you have a C++ / OpenGL library, handling the low level graphics stuff, with Lua on top. I know Flutter is using Skia, which is a low level library, and using OpenGL / Metal for rendering, but i wonder if you are able to tap into those low level API's in order to access this performance for fast rendering of let's say lot's of 2d sprites / textured quads etc, in the same manner that other mentioned frameworks would, which is built for this use case specifically. I have not looked deep into this framework or low level Flutter rendering capabilities yet, but i'm happy if you could explaing performance / limitations. Also if the Dart language or garbage collection causing performance degrade. Are there any benchmarks? 

Hey,

I would say it perform pretty well, Flutter already has made a lot of progress on skia and it’s apps strive for 60fps, even on devices not that powerfully.

It will probably not be as fastest as some tools specifically made for game dev, but given the nature of how flutter works, it rendered a lot of good results so far.

I have done a small perfomance test recently, it for web, but that should give you some idea, you can check it here: https://twitter.com/cptpixel/status/1246466357811728386?s=21

Regarding dart and the garbage collector, it works pretty well, and Dart AOT gives it a pretty good perfomance.

I will close this since this is more a question and not an issue, but feel free to add more comments here, or join our discord so we can talk.

**Comment by feroult** [comment]
I wonder if it is a good idea do just close it? 

Have we checked the overall perfomance by enabling/disabling repainting on games with different number of components?

Don't you think we could improve performance on games with lots of components? 

Flutter has a complex system to detect render boxes, overlays, hit tests, etc... we could borrow some ideas form them.

Food for thought.

**Comment by erf** [comment]
@erickzanardo thanks, it seem like the performance is pretty good for real time games. it would perhaps be interesting to set up a demo for rendering a bunch of sprites, but then a sprite batch renderer should probably be impl first. now metal is enabled by default for ios on master, so perf is probably up.

@ProgrammingLife if you dont need realtime updates, like a shooter, physics game etc, but rather a puzzle game, i would perhaps just use the flutter engine to paint stuff. it would perhaps be a good idea if you could pull in some classes from the flame engine for rendering pixel animation etc. in combination with a normal flutter app. ( not sure if you can now..? )

**Comment by erf** [comment]
@erickzanardo @feroult it seem you now use `Canvas.drawImageRect` for rendering sprites, it is mentioned in the [docs](https://api.flutter.dev/flutter/dart-ui/Canvas/drawImageRect.html) you can use [Canvas.drawAtlas](https://api.flutter.dev/flutter/dart-ui/Canvas/drawAtlas.html) to render multiple sprites, given a sprite sheet. You could impl a `SpriteBatchRenderer` based on this, which would probably render faster than #196

**Comment by erickzanardo** [comment]
@feroult The point on painting and repaint, is that this not something that would fit on a game engine, at least not like it would fit on a conventional app.

Game Engines are made with active rendering in mind, where a lot of updates will happen even when there is no input from the user, not to mention the high number of things moving, glowing and etc that happens on a game. So calculating if we need to repaint or not, is not as easy as it would be for a convencional app, where most of it can even be done on a virtual canvas/dom, or even based on state change (like what redux and those type of frameworks do).

Like @erf mentioned, if you are creating a game where there is not much updates happening on the same time, you shouldn't even be using a game engine, and Flutter itself would already be enough.

But even so, we already have an issue opened for that (#110) so I don't think we need to keep this open, as they are different things IMO.

**Comment by erickzanardo** [comment]
@erf I wasn't aware of that `drawAtlas`, this seems pretty cool, I am going to take a look on it and see how it would fit on Flame, thanks for pointing this out.

**Comment by erf** [comment]
@erickzanardo i could perhaps help out with this, but i'm afraid implementing `drawAtlas` would cause big structural changes which is perhaps better implemented by the creators

**Comment by erickzanardo** [comment]
> @erickzanardo i could perhaps help out with this, but i'm afraid implementing `drawAtlas` would cause big structural changes which is perhaps better implemented by the creators

I think we could think on a way to support it, without breaking the existing stuff. The bad thing is that `drawAtlas` is [undocumented](https://api.flutter.dev/flutter/dart-ui/Canvas/drawAtlas.html) on and receives a lot of parameters.

Either way, it seems to receive an image, it is what we currently use for the other classes like Sprite, so this probably could work well together.

**Comment by erf** [comment]
@erickzanardo Maybe they added the method recently and thats why its not documented yet, but the method is pretty self explantory. And we could just test it out. Buffering a bunch of transformed, textured, triangles or sprites for rendering is pretty normal in most graphics engines. You could add support for it without breaking existing stuff by adding a type of `SpriteBatchRendrerer` where you would add the parameters needed for the `drawAtlas` call, instead of creating a bunch of single sprites. But it i think it would be a good idea to refactor a lot of the existing classes for performance, especially `SpriteSheet` to be rendered using this ( as i mentioned in my previous comment ), since it only uses on image.

**Comment by erickzanardo** [comment]
@erf I say we would do this by steps, and do the refactor bit by bit. Would you like to open an issue so we can track that there?

**Comment by erf** [comment]
@erickzanardo it sound like a good idea. i would like to get a bit familiar with the codebase first. i added an issue #279  as i had some problems with making an example file which loads a sprite

**Comment by erf** [comment]
@erickzanardo i added a PR #281. 

i'm thinking i could add a new issue for a sprite batch.
