### ISSUE TITLE
improvement(Jenny): Finer control over object storage

### ISSUE THREAD

**Issue by projectitis** [flame-engine/flame#2686]
# What could be improved

1. Add `CharacterStorage.clear()` and `CharacterStorage.remove(String name)` (example usage `project.characters.clear();`)
2. Add `VariableStorage.clear({bool clearNodeVisits = false})` and `VariableStorage.remove(String name)` (example usage `project.variables.remove('cash');`)
    a. By default, node visit counts are retained, but can also be cleared by setting `clearNodeVisits` to true
3. Add `FunctionStorage.clear()` and `FunctionStorage.remove(String name)` (example usage `project.functions.remove('myFunc');`)
4. Add `CommandStorage.clear()` and `CommandStorage.remove(String name)` (example usage `project.commands.clear();`)

# Why should this be improved

For games with large amounts of dialog (nodes), it can be helpful to have finer control over the objects stored within a YarnProject. For example, when moving from one area to the next, the user may want to clear out the nodes already loaded and load new ones, or clear the characters from the last area of the game and load in a new set. The same applies for variables, commands and functions that are loaded/set.

This means that the same YarnProject can persist but the user can load and unload data as the player moves through the game.

Nodes are stored in a map, so it is already possible to clear these. However, characters, functions, commands and variables are stored in custom storage classes that do not implement a clear or remove feature.

In my own use-case (adventure-type game) when the user moves between areas I want to clear out the characters, but retain everything else. But I can imagine cases where the user would want to do any of the proposed improvements.

# Any risks?

This is not a change, so no risk to existing use.

# More information

Please assign me to this issue :)

**Comment by spydon** [comment]
@projectitis sounds like a good idea!

**Comment by projectitis** [comment]
PRs added for all of these.

**Comment by projectitis** [comment]
Done :)
