### ISSUE TITLE
feature: Snapshot a component (like a layer, but not)

### ISSUE THREAD

**Issue by projectitis** [flame-engine/flame#2693]
# Problem to solve

I want to render part of a component tree, but then cache it (like a `Layer`) until I choose to render it again. One example usage (but by far not the only one) is to freeze the game and show a dialog over the top. The 'frozen' game is a snapshot of a complex component tree, but is not being re-rendered every frame.

This means you can use all the goodness of `PositionComponent`s without having to write custom code for a `Layer`, or for calling `render` on the layer manually. It's just another component on the tree.

I've been looking through the docs and scouring the internet, but if I've missed an existing solution or suggestion (that isn't [layers](https://docs.flame-engine.org/latest/flame/rendering/layers.html)) please let me know!

# Proposal

A `Snapshot` mixin on `Component` that renders it's component tree to a picture, and from then on displays the picture (just like a layer does). It would have two modes:
- `snapshot = false;`. No change to renderTree. Renders every frame.
- `snapshot = true;`. Renders tree once to a picture, then displays that picture.

In snapshot mode, calling `takeSnapshot()` will trigger an update to the snapshot by re-rendering to the picture.

In non-snapshot mode, calling `takeSnapshot()` will also render a snapshot to the picture, but will continue to render normally to the canvas. The snapshot can be used for saving screenshots (I'm sure there are other uses).

# More information

Are you interested in working on a PR for this? - of course 😁

**Comment by spydon** [comment]
Sounds good! I guess you'll use `PictureRecorder`?
I would name the `snapshot` variable to `renderSnapshot` or something like that.

**Comment by projectitis** [comment]
Yes, indeed with `PictureRecorder`.

Good idea:
- `set renderSnapshot(bool value){}` (and getter)
- `Future<Picture> takeSnapshot(){}` (available after next `render`)
- and `Picture? get snapshot => _snapshot` 
?

**Comment by spydon** [comment]
Why do you need a setter and getter for `renderSnapshot`, is that going to trigger `takeSnapshot` from the setter?
The rest looks good.

**Comment by projectitis** [comment]
Hmm. Good point. It just needs to be a `bool`.

How much more efficient is a `Picture` than a full render? Doesn't a picture just hold all the commands to re-render the same thing again? I think I'd rather (finally) snapshot to `Image` using `Picture.toImage`. This is async, so I see it working something like (simplified):

```dart
// In render...
if (_image != null) {
    canvas.drawImage( ... );
} else if (_picture != null) {
    canvas.drawPicture( ... );
} else {
    _recorder = PictureRecorder();
    _canvas = Canvas(_recorder!);
    render(_canvas);
    _picture = _recorder?.endRecording();
    _image = _picture.toImage(size.x, size.y).whenCompleted(()=>_picture - null; };
    _recorder = null;
    _canvas = null;
}
```

Perhaps whether the snapshot is a picture or an image could be a user option?

Thoughts?

**Comment by spydon** [comment]
There is also a `Picture.toImageSync` which I think should have really good performance.

Do you only want to snapshot the current component and not it's children? Because if you do you'll have to use `renderTree` and not `render`.

> // likely also need to copy transforms from original canvas?

It shouldn't need to, because when rendering this snapshot later it will have the previous transforms applied.

**Comment by projectitis** [comment]
Yes, `renderTree` for sure, as in my original description, Sorry, was just a quick brain dump for that example.

I'll do some testing around performance of rendering image vs picture, and also `Picture.toImageSync`.

**Comment by ufrshubham** [comment]
> The snapshot can be used for saving screenshots (I'm sure there are other uses).

If I understand this correctly, this will allow me to capture a screen texture of the whole game, right? If so this will definitely open up options to implement some cool shaders 🙂

**Comment by projectitis** [comment]
Yes. I already have it finished 😁. Now I just need to work on some more tests and documentation before I create the PR.

**Comment by projectitis** [comment]
What's the recommended way to advance a `FlameGame` (update + render) for several frames in a `testWithGame`?

**Comment by projectitis** [comment]
Last hurdle. How do I compare an `Image` to a golden within a `testWithGame`? Example:

```dart
final image = component.snapshot.toImageSync(200, 200);
await expectLater(
    image,
    matchesGoldenFile('../../_goldens/test.png'),
);
```

I get this:

```
Binding has not yet been initialized.
  The "instance" getter on the TestWidgetsFlutterBinding binding mixin is only available once that binding has been initialized.
  Typically, this is done by calling "WidgetsFlutterBinding.ensureInitialized()" or "runApp()" (the latter calls the former). Typically this call is done in the "void main()" method. The "ensureInitialized" method is idempotent; calling it multiple times is not harmful. After calling that method, the "instance" getter will return the binding.
  In a test, one can call "TestWidgetsFlutterBinding.ensureInitialized()" as the first line in the test's "main()" method to initialize the binding.
  If TestWidgetsFlutterBinding is a custom binding mixin, there must also be a custom binding class, like WidgetsFlutterBinding, but that mixes in the selected binding, and that is the class that must be constructed before using the "instance" getter.

  package:flutter/src/foundation/binding.dart 302:9   BindingBase.checkInstance.<fn>
```

**Comment by spydon** [comment]
> The "instance" getter on the TestWidgetsFlutterBinding binding mixin

I think you have to run this before starting the test `TestWidgetsFlutterBinding.ensureInitialized();`
