### ISSUE TITLE
Example code in "Game Loop" documentation does not work (contains errors in Dart code)

### ISSUE THREAD

**Issue by tim-taylor** [flame-engine/flame#2712]
# Current bug behavior

The first code example in https://github.com/flame-engine/flame/blob/main/doc/flame/game.md does not work because it contains incorrect Dart code

# Expected behavior

Code shown in the documentation should compile and run without errors, when accompanied by appropriate imports.

# Steps to reproduce

1. Copy and paste the code from the example into a main.dart file
2. Add the required imports at the top of the file: ```import 'package:flame/components.dart';
import 'package:flame/game.dart';
import 'package:flutter/material.dart';```
3. Try to compile

# Flutter doctor output

```
Output of: flutter doctor -v
```
N/A

# More environment information

Flame version: 1.8.2

# Log information

```
Enter log information in this code block
```

# More information

The example code is as follows:
```
/// A component that renders the crate sprite, with a 16 x 16 size.
class MyCrate extends SpriteComponent {
  MyCrate() : super(size: Vector2.all(16));

  @override
  Future<void> onLoad() async {
    sprite = await Sprite.load('crate.png');
  }
}

class MyGame extends FlameGame {
  @override
  Future<void> onLoad() async {
    await add(MyCrate());
  }
}

main() {
  final myGame = MyGame(children: [MyCrate]);
  runApp(
    GameWidget(
      game: myGame,
    ),
  );
}
```

Problems with this code:

- The main() method should be declared with a return type:
```void main() {```
- The ```MyGame``` class needs a constructor that takes an optional named ```children```  parameter in order for the first line of the ```main``` method to work: ```MyGame({super.children});```
- The creation of a new ```MyCrate``` object in the first line of the ```main``` method needs open and close brackets: ```final myGame = MyGame(children: [MyCrate()]);```

So the whole example should look like this:

```
/// A component that renders the crate sprite, with a 16 x 16 size.
class MyCrate extends SpriteComponent {
  MyCrate() : super(size: Vector2.all(16));

  @override
  Future<void> onLoad() async {
    sprite = await Sprite.load('crate.png');
  }
}

class MyGame extends FlameGame {
  MyGame({super.children});

  @override
  Future<void> onLoad() async {
    await add(MyCrate());
  }
}

void main() {
  final myGame = MyGame(children: [MyCrate()]);
  runApp(
    GameWidget(
      game: myGame,
    ),
  );
}
```

**Comment by spydon** [comment]
Good find, would you like to put up a PR that fixes this? :)

**Comment by tim-taylor** [comment]
Thank you @spydon!  Sorry I didn't have time to do this myself.
