### ISSUE TITLE
3d/shader support?

### ISSUE THREAD

**Issue by chengenzhao** [flame-engine/flame#273]
Hi:

Recently we play around with Swiftui and Sprite Kit and Metal
for ios development Apple provides Metal Kit and Mtkview to easily integrate shader file(.metal) into Swiftui 
so is it possible for us to provide a similar widget that allow us to integrate shader files? 
like vk widget or mtl widget?

If so that should be great

**Comment by erickzanardo** [comment]
I don't think we can support 3d, as we only use what Flutter provides, and 3d is not supported by Flutter yet.

About Shaders, Flutter provides a very small set of Shaders that can be used on its paint API, you can check it here: https://api.flutter.dev/flutter/dart-ui/Shader-class.html

**Comment by PritishSawant** [comment]
This could become a reality thanks to impeller

**Comment by chengenzhao** [comment]
Yeah right
It is time to implement 3D rendering now

**Comment by spydon** [comment]
Absolutely, this issue is mostly about Flutter doing the basic ground work first though and that still has a long way to go before it supports all platforms, so I'll keep this issue closed for now and we'll open more specific issues when the time has come. :)

**Comment by PritishSawant** [comment]
yup still a long way to go

**Comment by guyluz11** [comment]
> I don't think we can support 3d, as we only use what Flutter provides, and 3d is not supported by Flutter yet.

Can you open/link the flutter issue to support 3D?

**Comment by Gustl22** [comment]
As ref:
https://www.youtube.com/watch?v=yO5oQGs2WCk
https://docs.flutter.dev/ui/design/graphics/fragment-shaders

**Comment by pritish-thub** [comment]
I follow [this](https://twitter.com/algebrandon) guy Brandon on Twitter. I think he works on Impeller. Lately he has been posting ton of 3d stuff with flutter like [this](https://x.com/algebrandon/status/1736197936978203061?s=20)

**Comment by ufrshubham** [comment]
Here are few more relevant links:
https://github.com/flutter/flutter/wiki/Flutter-GPU
https://docs.google.com/document/d/1Sh1BAC5c_kkuMVreo7ymBzPoMzb7lamZRPsI7GBXv5M/edit?resourcekey=0-5w8u2V-LS41tCHeoE8bDTQ

**Comment by spydon** [comment]
We should probably open different issues for this, since this issue is way too wide (and closed). I can please you to say that @renancaraujo is working on better shader support within Flame at least. :)

We are following Brandon's work closely with Flutter GPU.

**Comment by wolfenrain** [comment]
Just wanted to ping everyone on this thread: https://github.com/flame-engine/flame/pull/3012/ we are getting there
