### ISSUE TITLE
Obtain local "game" coordinates using TappableCallabacks and CameraComponent

### ISSUE THREAD

**Issue by massimilianoporzio** [flame-engine/flame#2737]
# Problem to solve
I would like to have a position of the tapped point in terms of "world coordinates" as with using old Tappable mixin and
camera.screenToWorld(info.eventPosition).

# Proposal
 If I use the new CameraComponent and the new Mixin I cannot do it.
I am trying to add the possibility to recognize the point tapped NOT inside a PositionComponent but in the main FlameGame. Is it possible? By now I am always getting the x,y coord of my screen and NOT the one in my game .
Is it possible to have a screenToWorld function fot the newCameraComponent and TappableCallbacks?

I am trying to place a "block" to the game by tapping on the screen..then move my player so I cannot see the adde block....then return to the block position and find the added block. By now I can place the block only in the same x,y position relative to my screen and NOT to my world coordinates.

# More information

**Comment by spydon** [comment]
This is solved by #2720 and will be released in a few days.
