### ISSUE TITLE
在开发游戏中，节点被删除后  在被添加出现的问题！

### ISSUE THREAD

**Issue by wufuqi123** [flame-engine/flame#2744]
问题1：   节点在UI上显示，但是当前节点的 parent == null。这时候无法删除节点，只能重新添加节点后再删除。
问题2：   节点的宽高会出现问题，无法做上下左右对齐操作。

出现的在1.8.2版本内，请尽快修复。

**Comment by spydon** [comment]
Like I said on the other issue, we only accept issues in english.
