### ISSUE TITLE
游戏的事件分发机制问题。

### ISSUE THREAD

**Issue by wufuqi123** [flame-engine/flame#2745]
在正常游戏开发中，mask是非常常见的，比如一个listview，一个scollview，比如一个进度条等等。

但是使用：
  var mask = ClipComponent.rectangle(
        position: Vector2(0, 0),
        size: Vector2(scrolling.width, scrolling.height),
        children: [contentView]);
去做mask时，会出现点击不显示部分事件会被触发。

建议不要使用  with TapCallbacks  方式去绑定事件。

建议重做事件分发，从根view去往下下发事件，这样可以完美控制子view的事件问题。

**Comment by spydon** [comment]
We unfortunately only accept issues in English, either translate your issue, or it will be closed.

**Comment by spydon** [comment]
I google translated your question and you just have to add a `Hitbox` (in this case a `RectangleHitbox`) that matched your mask and add the `GestureHitboxes` mixin to your component.
