### ISSUE TITLE
docs: Update EmberQuest to use latest features

### ISSUE THREAD

**Issue by spydon** [flame-engine/flame#2747]
# What could be improved
There has been some new features released after EmberQuest was written and it would be good to migrate it to use the following things:
* The built-in CameraComponent and World
* HasGameReference instead of HasGameRef
* Anything else?

# Why should this be improved
To make new users use new features.

# Any risks?
No.

**Comment by spydon** [comment]
Do you want to take this on @munsterlander? :)

**Comment by munsterlander** [comment]
Will do.

**Comment by spydon** [comment]
Fixed in #2904 :)
