### ISSUE TITLE
Flame mixins `... on FlameGame` require a generic type to be useable.

### ISSUE THREAD

**Issue by kurtome** [flame-engine/flame#2761]
Currently `HasKeyboardHandlerComponents` (and possible other mixin) are unusable if you're using a subtype of `FlameGame` which itself has a custom `World` type.

For example:

```dart
class LeapGame extends FlameGame<LeapWorld> with HasKeyboardHandlerComponents {
   ...
}

```

Example error messages:

```
The class 'LeapGame' can't implement both 'FlameGame<LeapWorld>' and 'FlameGame<World>' because the type arguments are different.
```

```
The setter 'FlameGame.world' ('void Function(LeapWorld)') isn't a valid concrete implementation of 'FlameGame.world' ('void Function(World)').
```

This error is unfixable unless `HasKeyboardHandlerComponents on FlameGame` is updated to `HasKeyboardHandlerComponents<T extends FlameGame> on T`.

**Comment by spydon** [comment]
Aah, good catch, as a workaround, don't use the generics on FlameGame meanwhile using that mixin until we have fixed it, and just cast where you need it. Or if it is in a component, use `HasWorldReference`.
