### ISSUE TITLE
Missing implementations

### ISSUE THREAD

**Issue by CodingDavid8** [flame-engine/flame#277]
Got a weird message when I try to debug my project and have no clue what to do about it. Any known fixes?
My flutter is on channel main and I upgraded it, Flame version is 0.19.0, I ran pub get.

`Compiler message:
/C:/src/Flutter/.pub-cache/hosted/pub.dartlang.org/flame-0.19.0/lib/flame.dart:67:7: Error: The non-abstract class 'FlameBiding' is missing implementations for these members:
 - SchedulerBinding.addPersistentFrameCallback
 - SchedulerBinding.addPostFrameCallback
 - SchedulerBinding.addTimingsCallback
 - SchedulerBinding.cancelFrameCallbackWithId
 - SchedulerBinding.currentFrameTimeStamp
 - SchedulerBinding.currentSystemFrameTimeStamp
 - SchedulerBinding.debugAssertNoTransientCallbacks
 - SchedulerBinding.endOfFrame
 - SchedulerBinding.ensureFrameCallbacksRegistered
 - SchedulerBinding.ensureVisualUpdate
 - SchedulerBinding.framesEnabled
 - SchedulerBinding.handleAppLifecycleStateChanged
 - SchedulerBinding.handleBeginFrame
 - SchedulerBinding.handleDrawFrame
 - SchedulerBinding.handleEventLoopCallback
 - SchedulerBinding.hasScheduledFrame
 - SchedulerBinding.lifecycleState
 - SchedulerBinding.removeTimingsCallback
 - SchedulerBinding.resetEpoch
 - SchedulerBinding.scheduleForcedFrame
 - SchedulerBinding.scheduleFrame
 - SchedulerBinding.scheduleFrameCallback
 - SchedulerBinding.scheduleTask
 - SchedulerBinding.scheduleWarmUpFrame
 - SchedulerBinding.schedulerPhase
 - SchedulerBinding.schedulingStrategy
 - SchedulerBinding.transientCallbackCount
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class FlameBiding extends BindingBase with GestureBinding, ServicesBinding {
      ^^^^^^^^^^^
/C:/src/Flutter/packages/flutter/lib/src/scheduler/binding.dart:607:8: Context: 'SchedulerBinding.addPersistentFrameCallback' is defined here.
  void addPersistentFrameCallback(FrameCallback callback) {
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/src/Flutter/packages/flutter/lib/src/scheduler/binding.dart:633:8: Context: 'SchedulerBinding.addPostFrameCallback' is defined here.
  void addPostFrameCallback(FrameCallback callback) {
       ^^^^^^^^^^^^^^^^^^^^
/C:/src/Flutter/packages/flutter/lib/src/scheduler/binding.dart:227:8: Context: 'SchedulerBinding.addTimingsCallback' is defined here.
  void addTimingsCallback(TimingsCallback callback) {
       ^^^^^^^^^^^^^^^^^^
/C:/src/Flutter/packages/flutter/lib/src/scheduler/binding.dart:496:8: Context: 'SchedulerBinding.cancelFrameCallbackWithId' is defined here.
  void cancelFrameCallbackWithId(int id) {
       ^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/src/Flutter/packages/flutter/lib/src/scheduler/binding.dart:889:16: Context: 'SchedulerBinding.currentFrameTimeStamp' is defined here.
  Duration get currentFrameTimeStamp {
               ^^^^^^^^^^^^^^^^^^^^^
/C:/src/Flutter/packages/flutter/lib/src/scheduler/binding.dart:906:16: Context: 'SchedulerBinding.currentSystemFrameTimeStamp' is defined here.
  Duration get currentSystemFrameTimeStamp {
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/src/Flutter/packages/flutter/lib/src/scheduler/binding.dart:522:8: Context: 'SchedulerBinding.debugAssertNoTransientCallbacks' is defined here.
  bool debugAssertNoTransientCallbacks(String reason) {
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/src/Flutter/packages/flutter/lib/src/scheduler/binding.dart:648:20: Context: 'SchedulerBinding.endOfFrame' is defined here.
  Future<void> get endOfFrame {
                   ^^^^^^^^^^
/C:/src/Flutter/packages/flutter/lib/src/scheduler/binding.dart:684:8: Context: 'SchedulerBinding.ensureFrameCallbacksRegistered' is defined here.
  void ensureFrameCallbacksRegistered() {
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/src/Flutter/packages/flutter/lib/src/scheduler/binding.dart:702:8: Context: 'SchedulerBinding.ensureVisualUpdate' is defined here.
  void ensureVisualUpdate() {
       ^^^^^^^^^^^^^^^^^^
/C:/src/Flutter/packages/flutter/lib/src/scheduler/binding.dart:672:12: Context: 'SchedulerBinding.framesEnabled' is defined here.
  bool get framesEnabled => _framesEnabled;
           ^^^^^^^^^^^^^
/C:/src/Flutter/packages/flutter/lib/src/scheduler/binding.dart:313:8: Context: 'SchedulerBinding.handleAppLifecycleStateChanged' is defined here.
  void handleAppLifecycleStateChanged(AppLifecycleState state) {
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/src/Flutter/packages/flutter/lib/src/scheduler/binding.dart:955:8: Context: 'SchedulerBinding.handleBeginFrame' is defined here.
  void handleBeginFrame(Duration rawTimeStamp) {
       ^^^^^^^^^^^^^^^^
/C:/src/Flutter/packages/flutter/lib/src/scheduler/binding.dart:1006:8: Context: 'SchedulerBinding.handleDrawFrame' is defined here.
  void handleDrawFrame() {
       ^^^^^^^^^^^^^^^
/C:/src/Flutter/packages/flutter/lib/src/scheduler/binding.dart:415:8: Context: 'SchedulerBinding.handleEventLoopCallback' is defined here.
  bool handleEventLoopCallback() {
       ^^^^^^^^^^^^^^^^^^^^^^^
/C:/src/Flutter/packages/flutter/lib/src/scheduler/binding.dart:662:12: Context: 'SchedulerBinding.hasScheduledFrame' is defined here.
  bool get hasScheduledFrame => _hasScheduledFrame;
           ^^^^^^^^^^^^^^^^^
/C:/src/Flutter/packages/flutter/lib/src/scheduler/binding.dart:302:25: Context: 'SchedulerBinding.lifecycleState' is defined here.
  AppLifecycleState get lifecycleState => _lifecycleState;
                        ^^^^^^^^^^^^^^
/C:/src/Flutter/packages/flutter/lib/src/scheduler/binding.dart:237:8: Context: 'SchedulerBinding.removeTimingsCallback' is defined here.
  void removeTimingsCallback(TimingsCallback callback) {
       ^^^^^^^^^^^^^^^^^^^^^
/C:/src/Flutter/packages/flutter/lib/src/scheduler/binding.dart:866:8: Context: 'SchedulerBinding.resetEpoch' is defined here.
  void resetEpoch() {
       ^^^^^^^^^^
/C:/src/Flutter/packages/flutter/lib/src/scheduler/binding.dart:774:8: Context: 'SchedulerBinding.scheduleForcedFrame' is defined here.
  void scheduleForcedFrame() {
       ^^^^^^^^^^^^^^^^^^^
/C:/src/Flutter/packages/flutter/lib/src/scheduler/binding.dart:742:8: Context: 'SchedulerBinding.scheduleFrame' is defined here.
  void scheduleFrame() {
       ^^^^^^^^^^^^^
/C:/src/Flutter/packages/flutter/lib/src/scheduler/binding.dart:482:7: Context: 'SchedulerBinding.scheduleFrameCallback' is defined here.
  int scheduleFrameCallback(FrameCallback callback, { bool rescheduling = false }) {
      ^^^^^^^^^^^^^^^^^^^^^
/C:/src/Flutter/packages/flutter/lib/src/scheduler/binding.dart:357:13: Context: 'SchedulerBinding.scheduleTask' is defined here.
  Future<T> scheduleTask<T>(
            ^^^^^^^^^^^^
/C:/src/Flutter/packages/flutter/lib/src/scheduler/binding.dart:808:8: Context: 'SchedulerBinding.scheduleWarmUpFrame' is defined here.
  void scheduleWarmUpFrame() {
       ^^^^^^^^^^^^^^^^^^^
/C:/src/Flutter/packages/flutter/lib/src/scheduler/binding.dart:666:22: Context: 'SchedulerBinding.schedulerPhase' is defined here.
  SchedulerPhase get schedulerPhase => _schedulerPhase;
                     ^^^^^^^^^^^^^^
/C:/src/Flutter/packages/flutter/lib/src/scheduler/binding.dart:331:22: Context: 'SchedulerBinding.schedulingStrategy' is defined here.
  SchedulingStrategy schedulingStrategy = defaultSchedulingStrategy;
                     ^^^^^^^^^^^^^^^^^^
/C:/src/Flutter/packages/flutter/lib/src/scheduler/binding.dart:461:11: Context: 'SchedulerBinding.transientCallbackCount' is defined here.
  int get transientCallbackCount => _transientCallbacks.length;
          ^^^^^^^^^^^^^^^^^^^^^^`

**Comment by erickzanardo** [comment]
This is happening only on newer versions of Flutter, there is already a PR to address that #276

**Comment by CodingDavid8** [comment]
Thanks - so what exactly am I supposed to do?

**Comment by erickzanardo** [comment]
At the moment, you could downgrade your flutter (I have been using the beta channel with no problems so far), or you could try using the branch from the PR, until it is merged.

**Comment by CodingDavid8** [comment]
Thanks, that helped me. Also wanted to say: You guys are incredible! Didn't expect such a fast reaction.
Enjoy your week and stay healthy ;)

**Comment by spydon** [comment]
@CodingDavid8 it is now fixed in the latest Flame release, so you can upgrade to that and upgrade to latest Flutter again if you wish.
