### ISSUE TITLE
the CameraComponent how to convert screen position to world position

### ISSUE THREAD

**Issue by HaiboLee** [flame-engine/flame#2772]
i can't find the api  screenToWorld  in CameraComponent

**Comment by spydon** [comment]
Most of the time you don't have to do that, because you'll get that information from the gesture events. For example, add the TapCallbacks mixin on the world instead of on the game.

What is your use-case? And I can tell you what the correct way of doing it is :)

**Comment by HaiboLee** [comment]
I want to drag the characters purchased from the store into the world in the game

**Comment by HaiboLee** [comment]
Create a point in the world at the beginning of the drag and drop, and when this point collides with an item in the store, copy an item and add it to the world for drag and drop. Is this feasible? ：)

**Comment by spydon** [comment]
> Create a point in the world at the beginning of the drag and drop, and when this point collides with an item in the store, copy an item and add it to the world for drag and drop. Is this feasible? ：)

Depending on how your store works (if it is in the world or on the viewport for example) you might have to do `camera.globalToLocal` if the drag doesn't start on the world.

**Comment by HaiboLee** [comment]
When I click on an item, I pass its name to the world and create it for drag and drop in the world. thanks ：）
