### ISSUE TITLE
[flame_tiled] Image layers don't correctly handle `repeatX` / `repeatY` setting in the layer

### ISSUE THREAD

**Issue by kurtome** [flame-engine/flame#2777]
# Current bug behavior

The image is only painted as wide as the viewport, but doesn't repeat forever like it does in tiled, you can see this as the camera moves from its initial position.

# Expected behavior

An image with repeat X setting should repeat forever as the camera scrolls left/right.

# Steps to reproduce

See this screenshot, you can find this by running https://github.com/kurtome/leap/tree/main/examples/standard_platformer (with the current PR to update to the latest version of Flame).

<img width="791" alt="image" src="https://github.com/flame-engine/flame/assets/458375/99d98741-a75a-419d-a0a6-c7a9ab8022b8">

# More information

This is likely because the `_paintArea` rect is set to the screen size inside `ImageLayer`: https://github.com/flame-engine/flame/blob/bde34efef7264c91f49b237b589c74ba80a1554e/packages/flame_tiled/lib/src/renderable_layers/image_layer.dart#L30

**Comment by spydon** [comment]
Do you want to work on a fix for this @kurtome?

**Comment by kurtome** [comment]
> Do you want to work on a fix for this @kurtome?

If I could think of an approach I would... (when I have time)

Off the top of my head I'm not sure what the solution is though
