### ISSUE TITLE
Fail to load assets from the example folder

### ISSUE THREAD

**Issue by erf** [flame-engine/flame#279]
I'm trying to get familiar with the codebase and got into some problems when trying to load a sprite image from a file in the example folder.

I added a test file `example/lib/sprites.dart` to the `flame` lib in order to test some functionality.

I had to do a `flutter create .` in the `example` folder in order to run the example code.

I then tried to create a sprite with image `test.png`.

Just to be sure, i added `test.png` to both `root/assets/images` and `root/example/assets/images` and added the asset to the `pubspec.yaml` in both the `root` and `example` folder, as i'm not quite sure how assets are handled now.
```
assets:
  - assets/images/test.png
```

Complete example code:
```
import 'package:flutter/material.dart';
import 'package:flame/components/component.dart';
import 'package:flame/game.dart';
import 'package:flame/sprite.dart';

void main() {
  final game = MyGame();

  runApp(game.widget);
}

class MyGame extends BaseGame {
  MyGame() {
    List.generate(10, (index) {
      return SpriteComponent.fromSprite(
          32, 32, Sprite('test.png', x: 0, y: 0, width: 32, height: 32));
    }).forEach((sprite) {
      add(sprite);
    });
  }
}
```

The code fails in `images.dart`:
```
  Future<Image> _fetchToMemory(String name) async {
    final ByteData data = await Flame.bundle.load('assets/images/' + name);
```

with the error message:
```
ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
If you're running an application and nee
```

I tried to add the following as suggested:
```
  WidgetsFlutterBinding.ensureInitialized();
```
but now it failed in:
```
class PlatformAssetBundle extends CachingAssetBundle {
  @override
  Future<ByteData> load(String key) async {
```

Do you have any idea what im doing wrong or is it not possbile to load assets when running code from the example folder?

**Comment by erickzanardo** [comment]
Where have you added the `WidgetsFlutterBinding.ensureInitialized();`? When it is required, it needs to be added first thing on your `runApp`

**Comment by erf** [comment]
@erickzanardo i did try to add it first in main, i just did not include it in the example

**Comment by erf** [comment]
How do you usually work on the flame lib if you want to test out new features?

**Comment by erf** [comment]
Should i be on the stable branch?

**Comment by erf** [comment]
I tried to boil down loading image assets from the Example code to the following:
```
    final data = await rootBundle.load('images/test.png');
    final image = await decodeImageFromList(data.buffer.asUint8List());
```
but fail with 
```
Unable to load asset: images/test.png
```

**Comment by erickzanardo** [comment]
> How do you usually work on the flame lib if you want to test out new features?
> 
> Should i be on the stable flutter channel? Im on dev now.

I usually use the beta channel of flutter, because of the web support

I am not sure why you are facing those problems, just yesterday I have used Flame and everything working ok regarding that.

If you want to, commit your example on some repository, so I can take a look and help you trouble shoot this problem.

**Comment by erf** [comment]
I found the error, i was missing a line in the pubspec.yaml file.
