### ISSUE TITLE
Klondike Tutorial step4.md does not keep all 52 card under KlondikeGame ownership

### ISSUE THREAD

**Issue by IanWadham** [flame-engine/flame#2798]
# Current bug behavior
During the shuffle and deal in Step 4 of Flame's Klondike Tutorial, 26 Card objects are removed from KlondikeGame ownership and placed under Tableau pile ownership. This contradicts what the documentation says earlier: "the `Card` components are owned directly by the `KlondikeGame` itself, whereas the `StockPile` and other piles are merely aware of which cards are currently placed there". This is true of the StockPile immediately after the deal when it has 24 cards in it and the List of Cards in KlondikeGame has the same 24 cards. But it is not true of the other piles - they are holding 26 cards which have been removed from the master-list in KlondikeGame. I believe the problem lies in the use of cards.removeLast() when dealing the cards, both in the `step4.md` file and in the `app/lib/step4/klondike_game.dart` file. Same bug in 2 places.

# Expected behavior
The List\<Card\>cards should contain 52 cards at all times after the shuffle() operation.

In the Klondike Tutorial app code as it stands, nothing is visibly wrong on the screen, but the problem will appear when you try to add features at the Klondike Game level that involve all 52 cards, such as making them fly off the screen when the user wins. I discovered the problem when trying to implement such a feature.

# Steps to reproduce
Add a print() statement to a running version of the Klondike game, to print out the number of cards in List\<Card\> in `app/lib/step4/klondike_game.dart`, immediately after the deal. It should be 52 but will be 24 with the code as it stands.

# Flutter doctor output
```
[✓] Flutter (Channel stable, 3.13.6, on macOS 12.6 21G115 darwin-arm64, locale
    en-AU)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[!] Android Studio (not installed)
[✓] VS Code (version 1.82.2)
[✓] Connected device (1 available)
[✓] Network resources
```
# More information
I have a solution to the problem and am interested in working on a PR for it.

**Comment by spydon** [comment]
I'll assign you to the issue
