### ISSUE TITLE
Any plans on making a VideoComponent? 

### ISSUE THREAD

**Issue by bangonkali** [flame-engine/flame#280]
Hi Guys, we're looking into mounting a Video on the Canvas for this Engine. Are there any plans on making a `VideoComponent`? Or can you send tips one where to start if I'm going to make one?

**Comment by erickzanardo** [comment]
We don't have any plans on that. That could be quite a big taking and we probably have a lot on our queue already.

But I think you could easily accomplish what you need, using a video player package from Flutter, on Flame you can show any kind of Widget on top of the canvas using the widget overlay API, more about this here: https://github.com/flame-engine/flame/blob/master/doc/game.md#flutter-widgets-and-game-instances

**Comment by luanpotter** [comment]
That might be a bit out of scope, but feel free to make like a flame-video package, as we have for other addons. We would definitely add that to the flame-awesome!
