### ISSUE TITLE
Use issue template forms for issues

### ISSUE THREAD

**Issue by spydon** [flame-engine/flame#2805]
# What could be improved
Currently you have to manually edit a markdown template text when submitting issues, we should configure so that we are using the issue form feature instead.

# Why should this be improved
Easier for our users to file issues and less chance that they miss something, or just remove the whole template.

# Any risks?
That it is less versatile then our current solution.

# More information
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms

**Comment by clairecharles** [comment]
Hi @spydon can i work on this?

**Comment by spydon** [comment]
Sure, I'll assign you to you @clairecharles! The issue templates live here:
https://github.com/flame-engine/flame/tree/main/.github/ISSUE_TEMPLATE
