### ISSUE TITLE
Sprite batch

### ISSUE THREAD

**Issue by erf** [flame-engine/flame#282]
As per my discussion with @erickzanardo in #268, i would like to add a new `SpriteBatch` class, which will use the [Canvas.drawAtlas](https://api.flutter.dev/flutter/dart-ui/Canvas/drawAtlas.html) call to render a a set of sprites with transforms. This will have performance benefits when drawing sprite atlases, and will not break existing functionality. Next we could create a component for this, and look into refactoring `SpriteSheet` and perhaps `Animation` to use this.

**Comment by erf** [comment]
@erickzanardo i've added a PR for this now in #283 

There is is improvements to be made, but should be a start. Let me know what you think.

**Comment by erickzanardo** [comment]
Awesome, will look when I get some time

**Comment by erf** [comment]
Thank you for the merge!

I think next would be interesting to implement `SpriteSheet`and/or `Animation` using this, and add to `SpriteBatch` as needed.
