### ISSUE TITLE
docs: Missing step to include _fanOutTopCards inside acquireCard in Klondike tutorial

### ISSUE THREAD

**Issue by qmffkem** [flame-engine/flame#2828]
# What could be improved

After following Klondike tutorial upto step 4. gameplay, I noticed that the cards in wastePile is not panned out after clicking stockPile, rather the three cards are all stacked on top of each other as before. After checking the provided code at the bottom of the page I noticed the document has missing information to incude **_fanOutTopCards()**; at the end of **acquireCard()** function.

Maybe adding a code snippet to show that _fanOutTopCards() also needed to be added here:
https://github.com/flame-engine/flame/blob/fa9665a566ac95869891199ff3eb449acf7c5005/doc/tutorials/klondike/step4.md?plain=1#L751-L760

# Why should this be improved

This would result the code bases the same as the expected outcome provided on the website, so the new users can easily follow the tutorial.

# Any risks?

No

# More information

It looks that the _fanOutTopCards() is only included in the functions below:
* removeCard()
* returnCard()

and the tutorial I followed is from the main branch.

**Comment by spydon** [comment]
Sounds reasonable, right @IanWadham?
Do you want to provide a PR with the fix @qmffkem? :)

**Comment by qmffkem** [comment]
haha 😅 I feel like i'm keep stumbling myself all again.
Here in line from 117-119 already mentioned that I need to include the function at the end of the acquireCard() function,
https://github.com/flame-engine/flame/blob/fa9665a566ac95869891199ff3eb449acf7c5005/doc/tutorials/klondike/step4.md?plain=1#L117-L119
But I totally missed reading this section and focused reading the bottom section where the code block associated to ADT exist and looked for a problem..

Sorry for confusion @spydon and @IanWadham 😅
