### ISSUE TITLE
ScalingParticle Proposal

### ISSUE THREAD

**Issue by brenoasm** [flame-engine/flame#2829]
# What could be improved
When experimenting with Flame's Particle System I found the need to add a scaling over lifetime, so I just copied another equivalent particle and created one but I found that the lifetime property of the particle is private, this way I couldn't create a good shorthand in the particle instance like the scaled, for example.

# Why should this be improved
I find that a scale over lifetime is just useful to have.

# Any risks?
I don't know the project, but for what I understand from reading the code, I don't think so.

# More information
I can do this PR if necessary, would be my first contribution.

**Comment by spydon** [comment]
Sounds like a good idea, we'll happily receive a PR for this. :)
If there are any questions about how to contribute etc don't hesitate to contact us in Discord.

**Comment by brenoasm** [comment]
Also, any objection on exposing a getter for the lifespan in the Particle class? This would enable us to not depend on new implementations to do a "good" custom particle and shorthand.

**Comment by spydon** [comment]
Go for it!
The particles haven't gotten any love for ages.
