### ISSUE TITLE
Add listener for when collision detection has been completed

### ISSUE THREAD

**Issue by christian-mindfulness** [flame-engine/flame#2849]
# Problem to solve
In certain situations one needs to know the order in which collisions happened (during a time step).  For instance if a player collides with both an enemy and the goal within the same time step.  To achieve this, one can assemble a list of objects that are passed to the multiple calls to `onCollision`.  By creating an additional callback `onCollisionsCompleted` which is called once all the calls to `onCollision` are finished, then the player has a full list of all the objects with which it collided within the time step.

# Proposal
Following discussion on discord, this can be achieved by adding a `Listenable` object to the `CollisionDetection` class.

# More information
I've started working on a branch for this: https://github.com/christian-mindfulness/flame/tree/add_collision_completed

**Comment by ufrshubham** [comment]
Doesn't `onCollisionEnd` work for this?

**Comment by christian-mindfulness** [comment]
`onCollisionEnd` is called on the time step when an object stops colliding with another.  This callback will be called at the end of the time step where the collision occurs.  Thus useful if an object is colliding with multiple other objects within a given time step.  There's more detail on the discussion thread that I had with @spydon about a month ago:
https://discord.com/channels/509714518008528896/1157721633109311560
