### ISSUE TITLE
Is it possible to controll rendering loops count per second? To reduce FPS

### ISSUE THREAD

**Issue by ProgrammingLife** [flame-engine/flame#285]
When I don't need to render at 60fps is there a chance to reduce it to 2-5? I mean not to call render function so often as it is in other situations.

Or should I write my own rendering system for binding it with Flutter?

**Comment by erf** [comment]
You only need 60fps because you are simulating / animating stuff that is moving on screen. If you dont do that, you usually trigger a redraw yourself. It sound like you might not need a game engine but could rather use vanilla Flutter.

**Comment by erf** [comment]
That said, i would look into `GameRenderBox._scheduleTick` and `GameRenderBox._tick` if you need some special behaviour. You could perhaps delay the next `_scheduleTick`.

**Comment by erickzanardo** [comment]
You can't control FPS with Flame, only thing you can do is pause or resume the engine.

If you need that small amount of FPS, I think you don't need to use Flame's Game loop, you should just use Flutter itself.

I don't think you need to write a whole rendering system, you can use CustomPainter widget, that way you get access to a Canvas and can even use Flame's Sprite, Animation classes.

**Comment by ProgrammingLife** [comment]
@erickzanardo Sounds great. In that way I should draw all Flame's Sprite that I use in my project to my CustomPainter manually?

**Comment by luanpotter** [comment]
the sprite class (not sprite component) has a render method that takes in the canvas, you can call that inside your custom painter draw function and provide the sprite

**Comment by erickzanardo** [comment]
Closing this, let us know if there is still any questions.

Consider joining our Discord for future questions :D

**Comment by curvednebula** [comment]
I think there still needs be a way to set FPS manually. Example: your game is quite heavy - so that you can't get consistent 60fps - in this case animations look choppy - sometimes smooth, sometimes lagging. Setting FPS let say to 30 would made the FPS stable, and your animation would look less choppy, may me not butter smooth, but without those sudden and annoying FPS drops.

**Comment by curvednebula** [comment]
BTW, in my case 60fps for some reason is never butter-smooth even when I reduce number of sprites to let's say 100 - I still see frame drops all the time - and what is more interesting it seems that release build even makes it worse than debug build or at lest have no effect on performance - so I would prefer having 30, but consistent fps.

**Comment by ufrshubham** [comment]
It is possible to manually limit the game's update at a desired lower rate by overriding the `updateTree` of the root game object.
```dart
double timeElapsed = 0;
static const timePerFrame = 1 / 30;

@override
void updateTree(double dt) {
  timeElapsed += dt;

  if (timeElapsed > timePerFrame) {
    timeElapsed -= timePerFrame;
    super.updateTree(timePerFrame);
  }
}
```
I am not 100% sure, but I think this would still render the game at 60 FPS. If that is the case, maybe the `GameRenderBox` will have to be modified to accumulate time and execute the game loop at a lower rate.

**Comment by curvednebula** [comment]
@ufrshubham Yes, interestingly FPS counter shows 30 FPS in this case. But I clearly see that it is still rendering at 60fps. I even set it to 5 fps - to make it obvious.

**Comment by ufrshubham** [comment]
> But I clearly see that it is still rendering at 60fps. I even set it to 5 fps - to make it obvious.

I think then we'll have to modify the `GameRenderBox` to allow for limiting just the rendering part.

**Comment by projectitis** [comment]
I am currently developing for WearOS (smart watch), and the ability to limit the framerate is important for battery life. I've modified my base game object to allow setting a max framerate (implemented using `updateTree` similar to above). Without limiting, my game is running at 60fps, but I am limiting it to 30fps, which I feel is an ok compromise.

The limiting is working, but the FPS counter (`FpsComponent`) is reporting incorrect numbers. E.g. when limited to 30fps (`updatePeriod = 1.0 / 30.0`) the framerate counter is showing 20fps. But I'm pretty sure the counter is wrong, not the update logic. I'll look into why that is later.

I'll be doing some tests to see if it really does save battery life, and if it does then I will provide it as an option in the game settings.

**Comment by projectitis** [comment]
Actually the FPS counter is correct. My game is running at 20fps because of, erm, math :)
Because of rounding, slight variations in timing etc, `update` is being called every 3rd time instead of every 2nd.

**Comment by projectitis** [comment]
Assuming `GameRenderBox.paint` is where the rendering happens, where is `GameRenderBox.paint` called from?
