### ISSUE TITLE
Remove hardcoded path prefixes for game assets

### ISSUE THREAD

**Issue by wednesdei** [flame-engine/flame#2859]
# What could be improved
Flame has hard coded prefixes for loading game assets that are not well documented on the website, and should be replaced with relative paths using the application root bundle.

```
// Prefix flame adds when loading images
assets/images/ 

// Prefix flame_tiled adds when loading tiles
assets/tiles/
```

The documentation is not clear what directories flame is expecting developers to use, and makes it difficult to load game assets correctly: 

https://docs.flame-engine.org/main/flame/structure.html

# Why should this be improved
The hardcoded path prefixes are not well documented and re-organizing assets for large projects is time consuming and costly. 60% of the time, using a path to load assets works every time. 

# Any risks?
It will take time to implement.

# More information

Example implementation:

```
final mapComponent = await TiledComponent.load(
        'Assets.maps.finalworld.path', Vector2(16, 16));
    add(mapComponent);
```

**Comment by spydon** [comment]
This is a documentation issue if anything, if you want to use a different base path for the caches it is already possible.

**Comment by ufrshubham** [comment]
> The hardcoded path prefixes are not well documented

This is quite a strong statement 😅. I'd say it is just missing the part about `assets/tiles`. Other than that, the docs clearly mentions where flame expects a certain type of assets by default.

And it also specifies this

> If you want to change this structure, this is possible by using the prefix parameter and creating your instances of AssetsCache, Images, and AudioCache, instead of using the global ones provided by Flame.
