### ISSUE TITLE
Split up game.dart into one file per class

### ISSUE THREAD

**Issue by erf** [flame-engine/flame#286]
The `game.dart` file is quite big, i think we could move each class to separate files to tidy it up. 

What do you think?

**Comment by erickzanardo** [comment]
Sure thing, I have already splitted it a little already, the widget builder was together on that file, and that was separated, but yeah, sure we could split it even more, we just need to be careful to not introduce a big breaking change on Flame.

**Comment by erf** [comment]
@erickzanardo ok great. btw could you look at my PR at #287 first ( it might be easier to split up game after this is merged ). btw should i make a separate issue for it ?

**Comment by luanpotter** [comment]
+100 :)

**Comment by luanpotter** [comment]
Fixed by #292
