### ISSUE TITLE
debugTextPaing should take viewport into the consideration.

### ISSUE THREAD

**Issue by erickzanardo** [flame-engine/flame#2881]
# What could be improved
Right now the code that creates the debug text paint for a component takes camera zoom into account, but it doesn't takes the viewport, so when using a fixed viewport and no zoom, the text paint used to render the coordinates looks very big.

# Why should this be improved
So debug mode can be better used on fixed viewports.

# Any risks?
None that I can think of:

# More information

Current implementation of the debug paint:

```dart
  TextPaint get debugTextPaint {
    final zoom = CameraComponent.currentCamera?.viewfinder.zoom ?? 1.0;
    if (!_debugTextPaintCache.isCacheValid([debugColor])) {
      final textPaint = TextPaint(
        style: TextStyle(color: debugColor, fontSize: 12 / zoom),
      );
      _debugTextPaintCache.updateCache(textPaint, [debugColor]);
    }
    return _debugTextPaintCache.value!;
  }
```

**Comment by spydon** [comment]
Sounds good, it should be easy to just multiply it with the `viewport.scale`.
