### ISSUE TITLE
Why MoveToEffect make position lost precision？

### ISSUE THREAD

**Issue by ysdxz207** [flame-engine/flame#2882]
# Current bug behavior

MoveToEffect make position lost precision.

# Expected behavior

# Steps to reproduce

```dart
void moveTo(Place place1, Place place2) {
    Tiles positionComponent1 = board[place1.x][place1.y];
    Tiles positionComponent2 = board[place2.x][place2.y];

    NotifyingVector2 position2 = board[place2.x][place2.y].position;
    print('move position:${positionComponent1.position} to ${positionComponent2.position}');


    final effect1 = MoveToEffect(
      position2,
      EffectController(duration: 0.3,),
      onComplete: () {
        print('【Result】positionComponent1 position:${positionComponent1.position}');
      }
    );
    positionComponent1.add(effect1);
  }
```

print result:
```
flutter: move position:[414.0,414.0] to [276.0,414.0]
flutter: 【Result】positionComponent1 position:[275.99999999999994,414.0]
```
It should be like this：
```
flutter: move position:[414.0,414.0] to [276.0,414.0]
flutter: 【Result】positionComponent1 position:[276,414.0]
```

I need to know how to fix this...............Please help!

# Flutter doctor output

```
Output of: flutter doctor -v




```

# More environment information

# Log information

```
Enter log information in this code block
```

# More information

**Comment by spydon** [comment]
I don't think we'll be able to easily support exact floating numbers in effects meanwhile still supporting composability of them in a nice way. It shouldn't have any visual impact of having the 13th decimal be off though.

**Comment by spydon** [comment]
You can easily just set the position in `onComplete` though if you want to have it exact.

**Comment by ysdxz207** [comment]
I need the exact position to do some logical judgment.

**Comment by spydon** [comment]
Then just set it in `onComplete` as mentioned. :)

**Comment by ysdxz207** [comment]
By the way, how to get a component by position?
I did not find some document about this.

**Comment by spydon** [comment]
> By the way, how to get a component by position?
> I did not find some document about this.

You can use raycasting if the components have hitboxes
