### ISSUE TITLE
Direct access to tiled images (Sprites)

### ISSUE THREAD

**Issue by Mythar** [flame-engine/flame#2900]
# Problem to solve
I would like to have direct access to the the images used by tiled.
For now i have to make a SpriteSheet like:

`
finale ss = SpriteSheet(
 image: images.fromCache('../tilesets/../../images/world/tiles/ground.png'), 
srcSize: { some size }
);
`

# Proposal
It would be nice to have something like:

`
 Sprite = TiledComponent.getSprite('ground.png', 1, 1);
`

# More information
I had to do an override of Images _assets as : "Map<String, _ImageAsset> get getAssets => _assets"
to find the key to the image:

`
images.getAssets.forEach((key, value) {
      print(key);
    });
`

**Comment by spydon** [comment]
Interesting, what is the use-case?

**Comment by ufrshubham** [comment]
`TiledComponent` creates atlases on the fly using all the images used by the tilemap. So it will require some bookeeping if you want to get the individual images. You can already access these atlases using `TiledComponent.atlases`

**Comment by erickzanardo** [comment]
I believe you can just pass a Images instances to the [`RenderableTiledMap.from` method ](`https://pub.dev/documentation/flame_tiled/latest/flame_tiled/RenderableTiledMap/fromFile.html), so all the images loaded by flame tiled, will be stored on the cache of that instance that you have control of

**Comment by ufrshubham** [comment]
> TiledComponent dose not have "atlases" property.

It does: https://github.com/flame-engine/flame/blob/caf2b90930ca500c85b9f9f63e7d3d7a5d82c18e/packages/flame_tiled/lib/src/tiled_component.dart#L206
Maybe you are on a older flame version?

> Sprite = TiledComponent.getSprite('ground.png', 1, 1);

I am not sure how that would work internally. Should the tilemap store a list of all the images even though an atlas was created out of it? And what does the (1, 1) represent?

**Comment by Mythar** [comment]
Im using:

flame: ^1.10.1
flame_tiled: ^1.17.0

I must be on an older version. With access to atlas, getSprite is not needed
