### ISSUE TITLE
Coordinate system not update with landscape orientation

### ISSUE THREAD

**Issue by neverewer** [flame-engine/flame#2902]
# Current bug behavior

When you assign an landscape orientation, the coordinate system is not updated and x and y remain the same as in portrait orientation. This causes difficulties when creating any calculations related to coordinates because when running on a device other than a phone, x and y will be normal and so you will have to do calculations for phones and tablets and separately for other devices

# Expected behavior
I expected that with a landscape orientation x would be greater than y, i.e. x in landscape orientation will be equal to y in portrait orientation, and y in landscape orientation will be equal to x in portrait orientation

# Steps to reproduce
To reproduce the bug, just set the orientation to the landscape via 
Flame.device.setLandscape();
And after that, in any component, get the size and display x and y

# Flutter doctor output
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.2, on Microsoft Windows [Version 10.0.22621.1848], locale ru-RU)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.5.4)
[√] Android Studio (version 2022.2)
[√] Connected device (3 available)
    ! Device 192.168.100.2:37509 is offline.
[√] Network resources

Output of: flutter doctor -v
[√] Flutter (Channel stable, 3.16.2, on Microsoft Windows [Version 10.0.22621.1848], locale ru-RU)
    • Flutter version 3.16.2 on channel stable at D:\Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9e1c857886 (6 days ago), 2023-11-30 11:51:18 -0600
    • Engine revision cf7a9d0800
    • Dart version 3.2.2
    • DevTools version 2.28.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: D:\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.5.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.5.33530.505
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2022.2)
    • Android Studio at D:\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] Connected device (3 available)
    • M2012K11AG (mobile) • 192.168.100.2:40071 • android-arm64  • Android 13 (API 33)
    • Windows (desktop)   • windows             • windows-x64    • Microsoft Windows [Version 10.0.22621.1848]
    • Chrome (web)        • chrome              • web-javascript • Google Chrome 119.0.6045.200
    ! Device 192.168.100.2:37509 is offline.

[√] Network resources
    • All expected network resources are available.

• No issues found!

# More environment information

* Flame version: 1.11.0
* Platform affected: android, windows
* Platform version affected: android 13,  windows 11

**Comment by spydon** [comment]
I think you must be doing something wrong, print the output in `onGameResize` and you will see that the x and y switches their values.
Possibly you look at the values before the resize has happened?

**Comment by ufrshubham** [comment]
> I expected that with a landscape orientation x would be greater than y, i.e. x in landscape orientation will be equal to y in portrait orientation, and y in landscape orientation will be equal to x in portrait orientation

This is a bit confusing. Why would x be greater than y in landscape? Are you talking about (x, y) or (size.x, size.y)? Assuming this is about the size, even then, size of any component won't depend on the orientation. It will stay whatever it was set to.

Yeah, `size.x > size.y` in landscape will be true for the game object. It will also be true of any component that is set to resize proportionally when the game resizes. But it is not true for all component. For example, if a component's size is (10, 20), I would expect it to stay the same after changing orientation.

**Comment by spydon** [comment]
> This is a bit confusing. Why would x be greater than y in landscape?

Ooh, are they not talking about the size? Then it is indeed very confusing...

**Comment by spydon** [comment]
@neverewer can you clarify a bit?

**Comment by spydon** [comment]
Closing this as stale.
@neverewer you can write here again if you want it re-opened.
