### ISSUE TITLE
Add continuous generation of particle effects

### ISSUE THREAD

**Issue by neverewer** [flame-engine/flame#2903]
# Problem to solve
Continuous generation of particle effects, their use

# Proposal
Add a component for continuous generation of particles with a system for setting up particles, for example there is a package in pub.dev spritewidget (https://pub.dev/packages/spritewidget),  you need to be able to configure their starting position, speed, gravity, acceleration, animation of appearance and removal, etc.

**Comment by ufrshubham** [comment]
@neverewer flame already has `ParticleSystemComponent` with some custom particles as described here: https://docs.flame-engine.org/main/flame/rendering/particles.html#particles

Does that not solve your use-case?

**Comment by spydon** [comment]
There are some examples [here](https://examples.flame-engine.org/#/Rendering_Particles) and [here](https://examples.flame-engine.org/#/Rendering_Particles%20(Interactive)) too.
We should really make the first one prettier. :sweat_smile: 
In the second one just drag around on the screen and particles will appear.

**Comment by spydon** [comment]
@neverewer did you see ufrshubham's question? :)

**Comment by spydon** [comment]
Closing this as stale
