### ISSUE TITLE
Question: getting absolute time in the update()

### ISSUE THREAD

**Issue by lastant** [flame-engine/flame#291]
What is the proper way of getting the absolute time in the update()? Is it ok to use DateTime.now().millisecondsSinceEpoch or is it better to add-up the delta-t or another way?

**Comment by spydon** [comment]
I don't think `DateTime.now().millisecondsSinceEpoch` is a very expensive call and if you add up the delta-t's you will slowly drift due to rounding errors, so I would go with the first one if it is important that it is exactly correct.

**Comment by luanpotter** [comment]
I think either work fine, depends mostly on what you'd be using for I guess. Someone recently suggested to add a elapsedTime to BaseGame, not sure if it would help and how often.

**Comment by erickzanardo** [comment]
Closing this for now, if you have further questions, please, let us know, also.

Consider joining our discord for questions.
