### ISSUE TITLE
Is there a way to set and/or animate sprite transparecy?

### ISSUE THREAD

**Issue by billy1380** [flame-engine/flame#293]
I have a sprite (called flare.png) that represents the flash that happens when a gun is fired. The effect that I am trying to reproduce is to show the sprite when the weapon is fired, then fade it out at a fixed rate until it is invisible and finally delete it.

In other 2d game engines I have used there is an opacity property e.g. 

```
sprite.opacity -= dt;

if (sprite.opacity <= 0) _deleted = true;
```

Is there a way that I can do something similar?

Many thanks.

**Comment by luanpotter** [comment]
Wdym? If your sprite png image has transparency it will be rendered properly as transparent. If you want you can change the paint property on the sprite/animation component to add a transparent tilt to the whole thing.

**Comment by erickzanardo** [comment]
@billy1380 please provide a meaningful description of your issue and not only a title.

**Comment by billy1380** [comment]
@erickzanardo updated description.

@luanpotter that transparent tilt sounds like the thing... let me look into it.

**Comment by erickzanardo** [comment]
@billy1380 hope this can help

```dart
    overridePaint = Paint()..color = const Color(0xFFFFFFFF).withOpacity(opacity);
```

**Comment by billy1380** [comment]
@erickzanardo I think that is it... thank you.

I found this https://github.com/flutter/flutter/issues/25969

Thanks again.
