### ISSUE TITLE
Suggest adding a SectorHitbox

### ISSUE THREAD

**Issue by zhou26192619** [flame-engine/flame#2941]
#Problem to solve
The attack area of the character in the game should be a fan-shaped area in front, but it is not currently available in Flame

#Proposal
Suggest adding a SectorHitbox component to address this issue

# More information

**Comment by ufrshubham** [comment]
I think it is already possible to achieve this with PolygonHitbox and CompositeHitbox

**Comment by zhou26192619** [comment]
> I think it is already possible to achieve this with PolygonHitbox and CompositeHitbox

Excuse me, could you give an example? Do I feel like I need to add countless points to achieve a smooth curve when using it?

**Comment by ufrshubham** [comment]
> Excuse me, could you give an example? Do I feel like I need to add countless points to achieve a smooth curve when using it?
> 
> 

Yeah, achieving a smooth curve won't be possible. But now I understand what you mean by SectorHitbox.

If it is just an attack hitbox, do you really need it to be perfectly curved? For example, if the attack is from a sword, adding a rectangle hitbox that wraps the sword and making it rotate about a point can help in achieving the same effect. I might be way off here, but just sharing this alternate approach because it worked for me 😄

**Comment by zhou26192619** [comment]
> > Excuse me, could you give an example? Do I feel like I need to add countless points to achieve a smooth curve when using it?
> 
> Yeah, achieving a smooth curve won't be possible. But now I understand what you mean by SectorHitbox.
> 
> If it is just an attack hitbox, do you really need it to be perfectly curved? For example, if the attack is from a sword, adding a rectangle hitbox that wraps the sword and making it rotate about a point can help in achieving the same effect. I might be way off here, but just sharing this alternate approach because it worked for me 😄

Well, mainly because what I need to do here is the NPC's warning area, and this field of view is fan-shaped.

**Comment by spydon** [comment]
@zhou26192619 can you show a picture of this fan-shaped area?

**Comment by zhou26192619** [comment]
> @zhou26192619 can you show a picture of this fan-shaped area?

![image](https://github.com/flame-engine/flame/assets/4471261/a45a4727-a0f6-4bfe-b840-b176395f0f54)

**Comment by spydon** [comment]
Aah, now I understand what you want to do, for this you should use ray casting, not hitboxes.
https://docs.flame-engine.org/latest/flame/collision_detection.html#ray-casting

**Comment by zhou26192619** [comment]
> Aah, now I understand what you want to do, for this you should use ray casting, not a hitbox. https://docs.flame-engine.org/latest/flame/collision_detection.html#ray-casting

Thanks. Although setting enough rays within the range can achieve the effect, it is an area where the rays have no area and always feels strange.

**Comment by spydon** [comment]
@zhou26192619 game dev is very often about approximations to reach an intended function (it's a trade-off for performance), all game engines I'm aware of use raycasting for the use-case you are describing.

**Comment by ufrshubham** [comment]
This can even be solved by doing some simple vector calculations and a circle hitbox. Essentially once any component is detected by the circle hitbox, you just find an unit vector from the player pointing towards the other component (red line). Then you just find the dot product of that vector with another unit vector that represents the line of sight of the player (blue line). The value of that dot product will indicate how close the other component is to the line of sight of the player. 
![image](https://github.com/flame-engine/flame/assets/33748002/5e141c0c-724b-41e4-9ff4-522c3015e884)

Dot product =  1 => Exactly in the line of sight
Dot product =  0 => Exactly at 90 degrees to the line of sight
Dot product = -1 => Exactly opposite to line to sight

**Comment by zhou26192619** [comment]
> This can even be solved by doing some simple vector calculations and a circle hitbox. Essentially once any component is detected by the circle hitbox, you just find an unit vector from the player pointing towards the other component (red line). Then you just find the dot product of that vector with another unit vector that represents the line of sight of the player (blue line). The value of that dot product will indicate how close the other component is to the line of sight of the player. ![image](https://private-user-images.githubusercontent.com/33748002/292298803-5e141c0c-724b-41e4-9ff4-522c3015e884.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMDUyMjgsIm5iZiI6MTcwMzIwNDkyOCwicGF0aCI6Ii8zMzc0ODAwMi8yOTIyOTg4MDMtNWUxNDFjMGMtNzI0Yi00MWU0LTlmZjQtNTIyYzMwMTVlODg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDAwMjg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3N2EwYmNjNTVkZjUzOWYyYzlkN2UwNTkzOThlZDBhZjQwMjM4MzQzZmYyOWE1NzlhOWFmMTg1ODVjMDkxNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IUlaPWdxK4HZCVsKPvD3K9f5WHTDp9Mvqa9AZpOm-W4)
> 
> Dot product = 1 => Exactly in the line of sight Dot product = 0 => Exactly at 90 degrees to the line of sight Dot product = -1 => Exactly opposite to line to sight

There is a slight discrepancy. Any other point that can move or flash into the area should be triggered in the form of a hitbox. If it is a ray, you must always calculate the positions and distances of all NPCs on the map. Not very reasonable.

**Comment by ufrshubham** [comment]
> Any other point that can move or flash into the area should be triggered in the form of a hitbox. If it is a ray, you must always calculate the positions and distances of all NPCs on the map. Not very reasonable.

Sorry, didn't quite understand the use case?

I did say all that calculations should be performed only when something is detected by a circle hitbox around the player.

**Comment by spydon** [comment]
That's a smart way to do it @ufrshubham! Hadn't thought about that.

@zhou26192619 our collision detection is handling this for you, and it's a lot more efficient than checking against all other hitboxes.
