### ISSUE TITLE
web game on box2d

### ISSUE THREAD

**Issue by rikinhim** [flame-engine/flame#296]
I am using flame with box2d now on a development of web based game. I used the BaseGame to start with and build a circle shape with fixture and bodydef set. I started to move it with a velocity at random then just let it bounce against the walls. It run smoothly on the browser.

The problem is when I started a new tab. And switch back to the tab where the game was, the ball slows down but not stop. And after a few more times of "switching between tabs" the ball eventually stops moving. Is there a clue about what is happening ?

**Comment by spydon** [comment]
I just noticed this in #307 too, it doesn't only affect web games apparently.
I will try to come up with a fix for it, but the fix will probably be in `Box2DGame` and not in `BaseGame`.

**Comment by spydon** [comment]
Have you tried wrapping it in a `GameRenderBox` @rikinhim ?

**Comment by erickzanardo** [comment]
Lets use #307 to track this.
