### ISSUE TITLE
Let raycast dynamically ignore some hitboxes

### ISSUE THREAD

**Issue by filiph** [flame-engine/flame#2966]
# Problem to solve
Currently, when calling `CollisionDetection.raycast()`, you can only ignore hitboxes with a pre-existing list of hitboxes.

```dart
  /// ...
  ///
  /// [ignoreHitboxes] can be used if you want to ignore certain hitboxes, i.e.
  /// the rays will go straight through them. For example the hitbox of the
  /// component that you might be casting the rays from.
  RaycastResult<T>? raycast(
    Ray2 ray, {
    double? maxDistance,
    List<T>? ignoreHitboxes,
    RaycastResult<T>? out,
  });
```

This means that we have to have (or construct) this list in advance. This is prohibitively expensive for games with more complex systems.

Imagine, for example, that a game entity in an top-down 2D game is trying to check whether it sees an enemy. If both the enemy and the entity are on the ground, then the raycast cannot ignore buildings. But if one of them is in the air, it can. (At least the buildings closer to the flying entity.) Similarly, a line of fire algorithm can ignore enemy units (i.e. I don't care that an enemy unit is partly blocking my line of fire — worst case scenario, I hit it instead of my target) but it shouldn't ignore friendlies.

Constructing the lists anew for every raycast could be very expensive if the raycast is done often. And managing a big variety of pre-populated lists is a recipe for bugs and memory leaks.

# Proposal

Apart from `List<T>? ignoreHitboxes`, the `raycast()` method should also accept a callback, something like:

```dart
  RaycastResult<T>? raycast(
    Ray2 ray, {
    double? maxDistance,
    List<T>? ignoreHitboxes,
    bool Function(T other)? filter,  // <-- added this
    RaycastResult<T>? out,
  });
```

The new `filter` callback is then used alongside of `ignoreHitboxes` like so:

```dart
    // ...
    for (final item in items) {
      if (ignoreHitboxes?.contains(item) ?? false) {
        continue;
      }
      if (!filter?.call(item) ?? false) {
        // When filter(item) returns `false`, we skip this item.
        continue;
      }
      if (!item.aabb.intersectsWithAabb2(_temporaryRayAabb)) {
        continue;
      }
      // ...
```

The naming could probably be improved. Something like `whereHitbox` instead of `filter`? I'd like to try staying positive (as in, when the callback returns `true`, we process that hitbox, otherwise no.

**Sidenote:** We should probably test performance. Even now, I'm not sure whether going through a `List` of `ignoreHitboxes` for every item is conducive to good performance. A `Set` would be better? Or maybe we can phase out `ignoreHitboxes` altogether in lieu of the callback? Of course, we'd need to measure first. It's also possible that `aabb.intersectsWithAabb2` is generally faster than checking `ignoreHitboxes` or running a callback, so that it should go first.

If the performance is too bad, we could do what Unity does (see below). Every component has something like a [`BitField`](https://api.flutter.dev/flutter/foundation/BitField-class.html) attached that's similar in practice to Unity's `layers` bit field. All tight loops (such as `raycast` or collision detection) then accept a bit mask.

# More information

- FWIW, Unity uses the following approaches for raycasts:
  - When calling the raycast, you can specify a bitmask for the [layers](https://docs.unity3d.com/Manual/Layers.html) you want to ignore. That is really low level, but is clearly very fast. (Every GameObject has a layer bit set.)
    - `Physics.Raycast(transform.position, transform.forward, out hit, 3f, layerMask)`
  - Some layers can be ignored altogether (every GameObject in those layers is ignored in every raycast call.)

**Comment by spydon** [comment]
> The new filter callback is then used alongside of ignoreHitboxes like so

Sounds like a good idea, do you want to do the implementation?

**Comment by filiph** [comment]
Yep, I'll look into it.

**Comment by filiph** [comment]
Ok, I'll just dump my measurements here for posterity. After the change, my benchmark with 800 moving robots has seen pretty decent improvement:

```
dart tool/compare.dart ignore_hitboxes_preexisting_hitbox.txt raycast_filter_involved.txt
<-- (improvement)                  UI thread                (deterioration) -->


                               █
                               █
                               █
                               █
                               █
                               █▄
                               ██
                               ██
                               ██
                               ██
                               ██
                               ██
                               ██
                               ██
                            ▄ ▄██
                            █ ███
                           ██ ███
                           ██████
                           ██████
               ▄▄    ▄▄▄ ▄▄███████▄▄
───────────────────────────────────────────────────────────────────────────────
-8.0ms                                 ^                                  8.0ms

* 600 vs 600 measurements
* 15.0% (-1056ms) improvement of total execution time
* 99.7% of individual measurements improved by 1ms+
* 0.0% of individual measurements worsened by 1ms+
```

This is comparing something like this (original):

```dart
  late final List<ShapeHitbox> _ownHitboxIgnoreList = [_ownHitbox];

  @override
  void update(double dt) {
    // ...

    gameRef.collisionDetection.raycast(
      centerRay,
      maxDistance: maxRayDistance,
      ignoreHitboxes: _ownHitboxIgnoreList,
      out: _raycastResultCenter,
    );
```

with something like this (improved):

```dart
  bool raycastFilter(ShapeHitbox hitbox) {
    if (hitbox == _ownHitbox) return false;
    final parent = hitbox.parent!;
    if (parent is! Robot) return true;
    return (parent.id % 2) == 0;
  }

  @override
  void update(double dt) {
    // ...

    gameRef.collisionDetection.raycast(
      centerRay,
      maxDistance: maxRayDistance,
      hitboxFilter: raycastFilter,
      out: _raycastResultCenter,
    );
```

I'm actually surprised, since the "improved" version has more logic in it. I guess checking `List.contains()` is quite expensive. 

When I try to recreate the `raycastFilter` logic by building a list every frame, the difference is obviously even bigger:

```
dart tool/compare.dart ignore_hitboxes_involved.txt raycast_filter_involved.txt
<-- (improvement)                  UI thread                (deterioration) -->


█
█
█
█
█
█
█
█
█
█
█
█
█
█
█
█
█
█
█
█
───────────────────────────────────────────────────────────────────────────────
-8.0ms                                 ^                                  8.0ms

* 600 vs 600 measurements
* 82.7% (-28529ms) improvement of total execution time
* 100.0% of individual measurements improved by 1ms+
* 0.0% of individual measurements worsened by 1ms+
```

I'm going to play a bit with the sorting of the various filters to see if I can squeeze out a bit more performance, but I'd be happy even with what I have now.

**Comment by spydon** [comment]
> I'm actually surprised, since the "improved" version has more logic in it. I guess checking List.contains() is quite expensive.

Maybe we should be using sets here in the long run, I think their creation is more expensive, but `contains` is definitely cheaper.

> I'm going to play a bit with the sorting of the various filters to see if I can squeeze out a bit more performance, but I'd be happy even with what I have now.

:+1:
