### ISSUE TITLE
Fix Component Lifecycle documentation

### ISSUE THREAD

**Issue by tibotix** [flame-engine/flame#2969]
# What could be improved

The [documentation](https://docs.flame-engine.org/latest/flame/components.html#component-lifecycle) part about the Component Lifecycle, especially about the `onLoad` method states:

> The onLoad method can be overridden to run asynchronous initialization code for the component, like loading an image for example. This method is executed after onGameResize, but before onMount. 

The phrasing can be improved to emphasize that `onLoad` is executed before `onGameResize`, and not after.
That being said, maybe it is in fact better to call `onLoad` after `onGameResize`, to allow sizing computations be run before `onLoad` (just like it is done in the `FlameGame` class).

# Why should this be improved

By looking at the provided diagram in the documentation section and some quick testing, it turns out the `onLoad` method is executed **before** `onGameResize` and before `onMount`. 
Also the docs should be as correct as possible to not irritate people new to flame.

# Any risks?

Just some doc change...

# More Information
The order of calls was changed in #2317 , where the documentation for `onGameResize` was changed, but not for `onLoad`.

**Comment by spydon** [comment]
>  That being said, maybe it is in fact better to call onLoad after onGameResize, to allow sizing computations be run before onLoad (just like it is done in the FlameGame class).

If I remember correctly it was a bit problematic to have `onGameResize` running before `onLoad` in normal components, and you can still get the size from the game with `HasGameReference` or just `findGame().size` in `onLoad`.

> The phrasing can be improved to emphasize that onLoad is executed before onGameResize, and not after.

Sounds good, do you want to submit a PR that updates the phrasing? You'll get the great honor of being our 200th contributor if you do. :wink:
