### ISSUE TITLE
`HasDraggables` not in flame engine code base

### ISSUE THREAD

**Issue by jtmcdole** [flame-engine/flame#2975]
The documentation for Joystick input references `HasDraggables`, a non-existent class.

https://github.com/flame-engine/flame/blame/622c855318b6c1731891b023ddc6429ba1f32329/doc/flame/inputs/other_inputs.md#L20

**Comment by spydon** [comment]
Ah yes, we've missed removing that one.
Do you want to put up a PR for it? It only needs to be removed.

**Comment by jtmcdole** [comment]
Yes, I can do that.
