### ISSUE TITLE
Using canvas.restore() in CustomPainterComponent is buggy

### ISSUE THREAD

**Issue by juskek** [flame-engine/flame#2978]
# Current bug behavior
When using a CanvasComponent, if the CustomPainter has canvas.restore() in its paint method, buggy behaviour occurs:
- only the last canvas.draw operation gets animated
- some canvas.draw operations are missing

![bug](https://github.com/flame-engine/flame/assets/57725347/03cd6cc2-a1bf-4f65-921d-e6a44f7ea32f)

# Expected behavior

![normal](https://github.com/flame-engine/flame/assets/57725347/8c661b89-df4b-4115-9cc9-5172699ec800)

# Steps to reproduce
1. Create CylinderComponent
2. Create CylinderPainter
3. Create CylinderWorld 
4. Add it to a FlameGame and GameWidget as usual

```dart

class CylinderComponent extends CustomPainterComponent
    with HasGameReference<EcoTossGame> {
  CylinderComponent();

  static const speed = 150;

  int direction = 1;

  @override
  Future<void> onLoad() async {
    size = Vector2.all(50);
  }

  @override
  void update(double dt) {
    painter = CylinderCustomPainter();
    x += speed * direction * dt;

    if ((x + width >= game.size.x / 2 && direction > 0) ||
        (x <= 0 && direction < 0)) {
      direction *= -1;
    }
    super.update(dt);
  }
}
```
```dart
class CylinderCustomPainter extends CustomPainter {
  CylinderCustomPainter();
  @override
  void paint(Canvas canvas, Size size) {
    final paintStyle = Paint()..color = Colors.red;
    final redPaintStyle = Paint()..color = Colors.grey.shade300;
    const circleOffset = 30.0;

    canvas
      ..drawCircle(const Offset(0, circleOffset), 15, redPaintStyle);
    canvas.restore();
    canvas
      ..drawRect(Rect.fromCenter(center: Offset.zero, width: 30, height: 60),
          paintStyle);
    canvas.restore();
    canvas
      ..drawCircle(const Offset(0, -circleOffset), 15, redPaintStyle);

    canvas.restore();
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) {
    return false;
  }
}

```
```dart
class CylinderWorld extends World {
  @override
  Future<void> onLoad() async {
    await add(PositionComponent(position: Vector2(0, 0), children: [
      CylinderComponent(rotationX: 0, rotationY: 0, rotationZ: 0)
    ]));
    await add(PositionComponent(position: Vector2(100, 100), children: [
      CylinderComponent(rotationX: 0, rotationY: 0, rotationZ: 0)
    ]));
    await add(PositionComponent(position: Vector2(200, 200), children: [
      CylinderComponent(rotationX: 0, rotationY: 0, rotationZ: 0)
    ]));
  }
}
```
# Flutter doctor output

```
Output of: flutter doctor -v
```

# More environment information

* Flame version: 1.0.0
* Platform affected: ios
* Platform version affected: android 9, ios 17.1.2

# Log information
No error logs

# More information
Willing to help on a PR if the cause can be diagnosed

**Comment by juskek** [comment]
The following code provides a temporary fix, but I am concerned that `saveLayer()` is an [expensive operation](https://api.flutter.dev/flutter/dart-ui/Canvas/saveLayer.html).

My current suspicion is that 
- with the original approach of only using `restore()`, the two circles and cylinder are being drawn on separate layers, and Flame only detects the last layer drawn.
- I then tried to use `saveLayer()` with `restore()` because I saw this in [the docs](https://api.flutter.dev/flutter/dart-ui/Canvas/restore.html): "If the state was pushed with [saveLayer](https://api.flutter.dev/flutter/dart-ui/Canvas/saveLayer.html), then this call will also cause the new layer to be composited into the previous layer."



```dart
class CylinderCustomPainter extends CustomPainter {
  CylinderCustomPainter();
  @override
  void paint(Canvas canvas, Size size) {
    final paintStyle = Paint()..color = Colors.red;
    final redPaintStyle = Paint()..color = Colors.grey.shade300;
    const circleOffset = 30.0;

    canvas
      ..drawCircle(const Offset(0, circleOffset), 15, redPaintStyle);
    canvas.saveLayer(Rect.largest, Paint());
    canvas.restore();
    canvas
      ..drawRect(Rect.fromCenter(center: Offset.zero, width: 30, height: 60),
          paintStyle);
    canvas.saveLayer(Rect.largest, Paint());
    canvas.restore();
    canvas
      ..drawCircle(const Offset(0, -circleOffset), 15, redPaintStyle);

    canvas.restore();
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) {
    return false;
  }
}
```

**Comment by spydon** [comment]
Since it is a component it shouldn't manually restore the canvas since that is already done automatically when the component is `add`ed to the component tree.

**Comment by spydon** [comment]
Ah, now I understand your problem. I see what your it is, you're never calling `canvas.save` and therefore restoring to the wrong state.

**Comment by juskek** [comment]
Hey @spydon , thanks for the quick response!!

I just tried the following code, and it worked! Thanks a bunch :) 

```dart
class CylinderCustomPainter extends CustomPainter {
  CylinderCustomPainter();
  @override
  void paint(Canvas canvas, Size size) {
    final paintStyle = Paint()..color = Colors.red;
    final redPaintStyle = Paint()..color = Colors.grey.shade300;
    const circleOffset = 30.0;

    canvas.save();
    canvas
      ..drawCircle(const Offset(0, circleOffset), 15, redPaintStyle);
    canvas.restore();

    canvas.save();
    canvas
      ..drawRect(Rect.fromCenter(center: Offset.zero, width: 30, height: 60),
          paintStyle);
    canvas.restore();

    canvas.save();
    canvas
      ..drawCircle(const Offset(0, -circleOffset), 15, redPaintStyle);
    canvas.restore();
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) {
    return false;
  }
}
```

**Comment by juskek** [comment]
Was this a Flutter issue or Flame issue? Just wondering if docs can be improved [here](https://api.flutter.dev/flutter/dart-ui/Canvas/restore.html), e.g. don't call restore() without a save() invocation beforehand

**Comment by spydon** [comment]
> Was this a Flutter issue or Flame issue? Just wondering if docs can be improved [here](https://api.flutter.dev/flutter/dart-ui/Canvas/restore.html), e.g. don't call restore() without a save() invocation beforehand 

That is flutter docs. Pretty much all canvas APIs work like this, what would it restore to if you don't have any saved state?
