### ISSUE TITLE
[space shooter tutorial] The position.x where Bullet is spawned at is unexpected.

### ISSUE THREAD

**Issue by linsite** [flame-engine/flame#2980]
FYI, I'm new to flame and flutter, I don't know this should be a improvement or something else.

# What could be improved

The "space shooter" tutorial is a good start for me into flame world. When I try it, find something strange. The bullet does not emerge at the player location.x, but at some position offset the right side. After some debugging, the `bullet.x` seems to be `2 * player.x`. So I update the `add(_bulletSpawner)` to `gameRef.add(_bulletSpawner)`, then the problem is solved.

# Why should this be improved

A little flaw in the tutorial.

# Any risks?

no.

# More information

Yes, I'd like to fix it .

**Comment by spydon** [comment]
@erickzanardo
