### ISSUE TITLE
getter for ComponentKey on Component itself

### ISSUE THREAD

**Issue by Koboo** [flame-engine/flame#2985]
# Problem to solve
Currently im trying to implement collision and need an id for the components. Since there is already the componentkey it would be pretty nice if I could just reuse it. But there is no getter for the key.

# Proposal
Add a getter for the ``ComponentKey _key`` to ``Component``.

# More information
No.

**Comment by spydon** [comment]
It would need a new method in `ComponentTreeRoot`, like `ComponentKey? componentToKey(Component component)` and then possibly a helper method on `Component` that would do `findGame()?.componentToKey(this)`.

Would you be interested in implementing this?
