### ISSUE TITLE
Animation fromAsepriteData method does not loop

### ISSUE THREAD

**Issue by ehoraizon** [flame-engine/flame#299]
I am trying to create an infinite animation using the **fromAsepriteData** method with **AnimationComponent**, when reaching the last frame it does not start the animation again.
This is the link to my assets folder and my main.dart below:

 https://drive.google.com/open?id=15vFq0CBZpy4bf_5Yg1P1lqvXEMu3VKql

`
        import 'package:flame/components/animation_component.dart';
        import 'package:flutter/material.dart';
        import 'package:flame/flame.dart';
        import 'package:flame/game.dart';
        import 'package:flame/components/component.dart';
        import 'package:flame/sprite.dart';
        import 'package:flame/animation.dart' as Animation;

        void main(){
          WidgetsFlutterBinding.ensureInitialized();
          runApp(MyGame().widget);
        }

        class MyGame extends BaseGame {
          AnimationComponent idle;

          MyGame() {
            _init();
          }

          void _init() async{
            
            await Flame.util.setLandscape();
            size = await Flame.util.initialDimensions();

            var animation = await  Animation.Animation.fromAsepriteData(
              'idle.png',
              'idle.json',
            );
            //21x35

            idle = AnimationComponent(
              21.0,
              35.0,
              animation,
            );

            idle.x = size.width / 2;
            idle.y = size.height / 2;

            Sprite background = Sprite('bkg.png');
            var bkd = SpriteComponent.fromSprite(size.width, size.height, background);

            this.add(bkd);
            this.add(idle);

          }
        }
`

**Comment by spydon** [comment]
Hi ehoraizon,
could you post the content of `idle.json`?

**Comment by ehoraizon** [comment]
It's in
https://drive.google.com/file/d/1xXjeE8axjB9IZFXogOEit3JQX9RxcuCG/view?usp=sharing

**Comment by ehoraizon** [comment]
> Hi ehoraizon,
> could you post the content of `idle.json`?

It's in
https://drive.google.com/file/d/1xXjeE8axjB9IZFXogOEit3JQX9RxcuCG/view?usp=sharing

**Comment by luanpotter** [comment]
@ehoraizon please try this:

```dart
Animation.Animation.fromAsepriteData(
    'idle.png',
    'idle.json',
)..loop = true;
```

I'm not sure if the loop property is provided by aseprite and if so if we actually carry it over.

**Comment by ehoraizon** [comment]
@luanpotter It doesn't work, I've already tried it before

**Comment by androidDL** [comment]
The `idle.ase` is duplicate object key in `idel.json` file .
So when you decode the aseprite file,you only get one frame.

**Comment by ehoraizon** [comment]
> The `idle.ase` is duplicate object key in `idle.json` file .
> So when you decode the aseprite file,you only get one frame.

problem solved.
