### ISSUE TITLE
Set the mass

### ISSUE THREAD

**Issue by glennmichaelmejias** [flame-engine/flame#300]
hello, on box2d how to set the mass of an object? even if i set the gravity to 1000, the simulation is still slow. thanks.

**Comment by spydon** [comment]
Hi, 
you set the density of the object and the mass is calculated by box2d.
When you create the body you do something like the **fixtureDef.density** here:

    final fixtureDef = FixtureDef();
    fixtureDef.setUserData(this); // To be able to determine object in collision
    fixtureDef.shape = shape;
    fixtureDef.density = 1.0;

    final bodyDef = BodyDef();
    bodyDef.type = BodyType.DYNAMIC;
    this.body = world.createBody(bodyDef)
      ..createFixtureFromFixtureDef(fixtureDef);

But it shouldn't be slow with the normal density, so this might not be the solution.
Is the simulation lagging or is it just slow?

**Comment by glennmichaelmejias** [comment]
thanks. i fix it already, i just found the settings.dart on the box2d_flame package and I set the maxTranslation from 2 to 100

**Comment by glennmichaelmejias** [comment]
test
