### ISSUE TITLE
Make `loaded`,`mounted` and `removed` Futures on FlameGame instance working

### ISSUE THREAD

**Issue by tibotix** [flame-engine/flame#3003]
# Problem to solve

Knowing when the game has finished loading/mounting or was removed.
Although one can argue the `removed` Future isn't really useful, so we can omit this maybe.

# Proposal

As `Component` already has the `mounted`,`loaded`,`removed` Futures with their respective Completers, we just need to access the completers `_mountCompleter`,`_loadCompleter`,`_removeCompleter` and mark them as completed. Right now these member variables are private and cannot be accessed by subclasses, so maybe we can introduce a protected getter for them.

For the mount case we can complete `_mountCompleter` in `FlameGame.mount`, after the `super.mount()` call.
For the loading case we can complete `_loadCompleter` in `GameWidgetState.loaderFuture`, before the `game.mount()` call.
One note: This way both `_mountCompleter` and `_loadCompleter` would complete before the mounting/loading bit is set through `setMounted()`, which is probably undesirable.
I think it would be best to make `_finishLoading` protected and introduce a similar function `_finishMounting`, which does the same things (set state bit, call completer). Then we can use these methods inside `FlameGame` to propagate loading/mounting completion events, and it would handle the state bits as well. The `setMounted` then is a bit unnecessary, as loading/mounting bits were already set (by `_finishdLoading`/`_finishMounting`), but `setMounted` is only used by `FlameGame`, so we can maybe change the behaviour or API there a bit.
We maybe could use the new `_finishMounting` function inside `Component._mount` as well, altough the order of `_clearMountingBit` and `_setMountedBit` are reversed there. Is there any reason why `_mount` does this:
```dart
// inside Component._mount:
    onMount();
    _setMountedBit();
    _mountCompleter?.complete();
    _mountCompleter = null;
    _parent!.children.add(this);
    _reAddChildren();
    _parent!.onChildrenChanged(this, ChildrenChangeType.added);
    _clearMountingBit();
```
instead of this:
```dart
// inside Component._mount:
    onMount();
    // clear mounting bit here instead of at the end
    _clearMountingBit();
    _setMountedBit();
    _mountCompleter?.complete();
    _mountCompleter = null;
    _parent!.children.add(this);
    _reAddChildren();
    _parent!.onChildrenChanged(this, ChildrenChangeType.added);
    
```

For the remove case i have no proposal yet, but it should be similar.

# More information

The relevant methods are:

```dart
class Component {
  // [...]
  void _finishLoading() {
    _clearLoadingBit();
    _setLoadedBit();
    _loadCompleter?.complete();
    _loadCompleter = null;
  }
}
```
```dart
class GameWidgetState<T extends Game> extends State<GameWidget<T>> {
   // [...]
  Future<void> get loaderFuture => _loaderFuture ??= (() async {
        final game = currentGame;
        assert(game.hasLayout);
        final onLoad = game.onLoadFuture;
        if (onLoad != null) {
          await onLoad;
        }
        game.mount();
        if (!game.paused) {
          game.update(0);
        }
      })();
}
```
```dart
class FlameGame<W extends World> extends ComponentTreeRoot with Game implements ReadOnlySizeProvider {
  // [...]
  @override
  @internal
  void mount() {
    super.mount();
    setMounted();
  }
}
```

I can work on a PR for this.

This would unblock #2971.

**Comment by erickzanardo** [comment]
> Knowing when the game has finished loading/mounting or was removed.

I am unsure I understand why we need to change here, The futures mounted, loaded, etc exists exactly for that reason so you can know that already.

What am I missing?

**Comment by tibotix** [comment]
Yeah, but exactly these futures (mounted, loaded, etc) are not working on the `FlameGame` instance, only on real `Components`. Thats what we try to fix now.

**Comment by spydon** [comment]
It should be possible to get it to go through the component lifecycle without having to add any methods.
The problem here is that the `Game` mixin can't call `super.mount` since it isn't applied `on` something that it knows has those methods, so we probably just need to create an interface that `Component` and `Game` implements so that `mount` and the rest of those lifecycle methods can be called.

**Comment by tibotix** [comment]
> It should be possible to get it to go through the component lifecycle without having to add any methods.

I am not entirely sure what you meant with "to get it to go through the component lifecycle".

In case you meant literally sharing the "component lifecycle methods" between `Game` and `Component`: i don't think this can be done easily. All lifecycle methods (`Component.handleLifecycleEvent*` and their called functions such as `_mount`, `_startLoading`, `_remove`, ...) are called through `ComponentTreeRoot.processLifecycleEvents`, which in turn is only called after the game finished loading and mounting. So the only thing that manages the component lifecycle of the game is `GameWidgetState` with its `loaderFuture`. Moreover, `_mount` for example assumes that this component is not the componentTreeRoot, by asserting `_parent != null` for example. Based on this knowledge i don't think we can share component lifecycle methods and their logic.

In the more probable case you meant to have some generalized `mount`/`load`, etc. methods in `Component`: i think this is a good idea. Though as stated above, we can't just simply use the existing component lifecycle methods in `Component` for the lifecycle management of `Game`. So we have to come up with some generalized lifecycle API in `Component` that can be reused/extended in `Game`. Maybe have some `mount`/`load` method which (only for mounting in this example):

1. calls `_setMountingBit`
2. calls `_doMounting`
3. calls `clearMountingBit`
4. calls `_setMountedBit`
5. calls `_mountCompleter?.complete`
6. sets `_mountCompleter = null`

with one new method `_doMounting`, which can be overridden by `Component` and `Game` to match the logic needs. 
Currently i don't see a way to achieve the desired features without adding new methods, or at least without adding new internal methods.

**Comment by spydon** [comment]
I think the interface idea would probably have worked, but I had a quick look at the code yesterday and since its already using  [setMounted](https://github.com/flame-engine/flame/blob/main/packages%2Fflame%2Flib%2Fsrc%2Fcomponents%2Fcore%2Fcomponent.dart#L931) when mounting the game, I figured we could just move the call to the completer in there and use that method inside of the component too. Will have a closer look at that today.

**Comment by spydon** [comment]
Alright, now they should be working in #3007 @tibotix, can you give it a try? :)

**Comment by tibotix** [comment]
yes its working now. Thanks :)
