### ISSUE TITLE
Raycasting unable to detect Hitboxes

### ISSUE THREAD

**Issue by xjyribro** [flame-engine/flame#3004]
# Current bug behavior
Raycasts returns null for all hitboxes above the component in the component tree. It works fine with any hitbox added in the same component

# Expected behavior
Raycasts should be able to detect hitboxes regardless of component tree structure just like collision detection

# Steps to reproduce
1. Create a Component (Component 1) and add it to the root (any component is fine)
2. Add a hitbox (any kind would do)
3. Add another component (Component 2)
4. Add a raycast inside Component2
5. Raycasts unable to detect hitbox of Component 1

# More information
I tried this even with the Raycasting example: https://docs.flame-engine.org/latest/flame/collision_detection.html#raycastall. Once the hitbox and raycast are in different components, the raycast cannot detect hitboxes.

**Comment by ufrshubham** [comment]
It shouldn't be happening unless you are adding `HasCollisionDetection` mixin to multiple components. 

> 4. Add a raycast inside Component2

👆🏼This makes me believe that you are adding `HasCollisionDetection` to `Component2`. If that is the case, you cannot expect it to find sibling or upstream hitboxes. It is also documented here: https://docs.flame-engine.org/latest/flame/collision_detection.html#hascollisiondetection

If that is not the case, can you share a sample code where this problem can be reproduced?

**Comment by xjyribro** [comment]
I have 2 components that have HasCollisionDetection: the main game 
```
class MyGame extends FlameGame
    with HasCollisionDetection, HasKeyboardHandlerComponents
```
and my player.
```
class Player extends SpriteAnimationComponent
    with KeyboardHandler, HasGameReference<GomilandGame>, CollisionCallbacks, HasCollisionDetection
```

My component that has a hitbox is under the main game component
```
class Component2 extends SpriteComponent
    with CollisionCallbacks, HasGameReference<GomilandGame> {
  Component2 ({required Vector2 position}) : super(position: position);

  late RectangleHitbox _hitbox;

  @override
  Future<void> onLoad() async {
    sprite = await Sprite.load(Assets.assets_images_rubbish_rubbish_small_png);
    _hitbox = RectangleHitbox(
      size: Vector2(16, 16),
      position: Vector2(16, 16),
      anchor: Anchor.center,
      collisionType: CollisionType.passive,
    );
    add(_hitbox);
  }

  @override
  void onCollisionStart(
      Set<Vector2> intersectionPoints, PositionComponent other) {
    super.onCollisionStart(intersectionPoints, other);
    final int bagCount = game.gameStateBloc.state.bagCount;
    final int maxBagCount = game.gameStateBloc.state.maxBagCount;
    if (bagCount < maxBagCount) {
      game.gameStateBloc.add(BagCountChange(bagCount + 1));
      sprite = null;
      remove(_hitbox);
    }
  }
}
```

My player will send the raycast on keyboard press. Currently it detects nothing. (I ignored the player own hitbox)

```
if (event.logicalKey == LogicalKeyboardKey.keyE) {
        final ray = Ray2(
          origin: Vector2(0, 0),
          direction: Vector2(1, 0),
        );
        final result = collisionDetection.raycast(ray);
      }
```

**Comment by ufrshubham** [comment]
Yup, that setup is wrong. Don't add `HasCollisionDetection` to `Player` just to get access to the `collisionDetection` object. By adding that mixin to `Player` class you are telling Flame that some of `Player`'s children will have hitboxes that need to collide with each other.

You should remove `HasCollisionDetection` from `Player` and modify the raycast code as below:

```dart
if (event.logicalKey == LogicalKeyboardKey.keyE) {
        final ray = Ray2(
          origin: absolutePosition, // Player's world coordinates
          direction: Vector2(1, 0),
        );
        final result = collisionDetection.raycast(ray);
}
```

**Comment by xjyribro** [comment]
How do you get the method `collisionDetection` then? In the docs it says "To use the ray casting functionality you have to have the HasCollisionDetection mixin on your game. After you have added that you can call collisionDetection.raycast(...) on your game class." But this doesn't explain how other classes get collisionDetection.

**Comment by ufrshubham** [comment]
> How do you get the method `collisionDetection` then? In the docs it says "To use the ray casting functionality you have to have the HasCollisionDetection mixin on your game. After you have added that you can call collisionDetection.raycast(...) on your game class." But this doesn't explain how other classes get collisionDetection.

You get it from the game class. See the edited code in my previous comment. Basically add `HasGameReference` to the component and access `collisionDetection`.

**Comment by xjyribro** [comment]
Ah ok I've made it work. Thanks for the clarification. Probably the documentation could be more explicit. It's not obvious that ONLY the top-level _Game_ Component shoold have HasGameReference and components below it should call the game ref for all raycasts.

**Comment by ufrshubham** [comment]
> It's not obvious that ONLY the top-level _Game_ Component shoold have HasGameReference and components below it should call the game ref for all raycasts.

I think you meant `HasCollisionDetection` here.

I agree that the docs could be improved, but understand that there are valid cases where you can have `HasCollisionDetection` on other components too. It is just that those are some advanced use cases that simple games won't ever need. I think the docs already say that the `HasCollisionDetection` mixin is to keep track of collectable components:

> If you want to use collision detection in your game you have to add the HasCollisionDetection mixin to your game so that it can keep track of the components that can collide.

It also explains a case where it might make sense to add `HasCollisionDetection` to non-game components:

> You can also add HasCollisionDetection directly to another Component instead of the FlameGame, for example to the World that is used for the CameraComponent. If that is done, hitboxes that are added in that component’s tree will only be compared to other hitboxes in that subtree, which makes it possible to have several worlds with collision detection within one FlameGame.

But if you think it is still unclear, feel free to simplify the docs 👍🏼
