### ISSUE TITLE
Is it possible to support Getx?

### ISSUE THREAD

**Issue by ltq918** [flame-engine/flame#3005]
# Problem to solve

Nice to see that we have flame_bloc and flame_riverpod available, can we request a getx-adapted package?
# Proposal

Riverpod and Bloc are very powerful and robust, but Getx seems more suitable for beginners to start projects.
# More information
Github https://github.com/jonataslaw/getx
pub.dev https://pub.dev/packages/get

Related documents https://github.com/jonataslaw/getx/blob/master/documentation/en_US/state_management.md#state-management

**Comment by spydon** [comment]
The Flame team does not encourage state management solutions that drives their users into anti-patterns (like getx does), hence we'll never have an official `flame_getx` package, but if anyone in the community wants to maintain such a package they are of course welcome to do so. :)

If you are more interested in why many Flutter profiles discourage getx you can read a quite good summary of it by Scott Stoll [here](https://twitter.com/scottstoll2017/status/1468431032240246784).

**Comment by ltq918** [comment]
Thank you for letting me see some voices in the community. It seems that getx is not supported by the mainstream voices in the community. I now know such a thing.
