### ISSUE TITLE
unable to load large number of frame

### ISSUE THREAD

**Issue by deepak-gehlot** [flame-engine/flame#301]
Hello, 

i am working on an app, which need to load a sprite sheet which has 135 images, and it unable to load the frame. app close direct without any error when at place for frame count i give 10 or 20 it load but when i give 135 it hang app and closed.

**Comment by erf** [comment]
It sounds like a memory problem. How big is the image file?

Can you add a minimal code example with image?

**Comment by erickzanardo** [comment]
That does sounds like a memory problem, images when loaded are stored raw on the memory, and 135 images is indeed a lot.

**Comment by erickzanardo** [comment]
Closing due inactivity, let us know if there is any news on this.
