### ISSUE TITLE
HoverCallbacks not working in IsometricTileMap

### ISSUE THREAD

**Issue by tejHackerDEV** [flame-engine/flame#3020]
IsometricTileMap returns its size as [0,0]. Due to which HoverCallbacks not working

# Current bug behavior
Hovers not working

# Expected behavior
Hovers should work as other PositionComponents

# Steps to reproduce
Create a tilemap with IsometricTileMap component & add desired hovercallback & do print statements

**Comment by spydon** [comment]
Should be solved by #3142
