### ISSUE TITLE
Expose TexturePackerAtlas

### ISSUE THREAD

**Issue by matthiasn** [flame-engine/flame#3046]
### What could be improved

I was running into a small issue where I wanted to reuse the `TexturePackerAtlas` from the `TexturePacker` package in order to avoid having to parse/create over and again. While this was possible, I had to ignore `implementation_imports`, which isn't so elegant. Instead, I suggest exposing `TexturePackerAtlas`.

### Why should this be improved

Reusing and existing `TexturePackerAtlas` for an animation that is created multiple times (e.g. in different positions) results in less CPU usage and likely also less garbage collection activity, as opposed to having to recreate it repeatedly. 

### Risks

Not that I'm aware of.

### Other

- [X] Are you interested in working on a PR for this?

**Comment by ufrshubham** [comment]
But `TexturePackerAtlas` is already exported by `flame_texturepacker` package. Are you talking about `flame_gdx_texture_packer`?

**Comment by spydon** [comment]
@ufrshubham it's not exported, as far as I can see at least?

**Comment by ufrshubham** [comment]
Ohh! You are right. I misread `import` as `export` on this line 😅

https://github.com/flame-engine/flame/blob/6270353af9a6ec58ee9275ddfa6a8b26276a2c20/packages/flame_texturepacker/lib/flame_texturepacker.dart#L4
