### ISSUE TITLE
Update documentation to change references from `RawKeyEvent` to `KeyEvent`

### ISSUE THREAD

**Issue by elibdev** [flame-engine/flame#3052]
### What could be improved

While going through the Flame Ember Quest tutorial I noticed an error from the example code when I overrode the `onKeyEvent` method due to the documentation using the deprecated `RawKeyEvent` type that has been changed to `KeyEvent` in the `KeyboardHandler` mixin: https://docs.flame-engine.org/latest/tutorials/platformer/step_5.html

I would be happy to make these changes and open a PR. I am new to the project so I wanted to make an issue first to make sure the changes are wanted. 

### Why should this be improved

This would fix an error in tutorial code.

### Risks

No risks, this would be documentation only.

### Other

- [X] Are you interested in working on a PR for this?

**Comment by spydon** [comment]
That's great that you're open to fixing it, I'll assign you to the issue!
