### ISSUE TITLE
flame_tiled Unable to load asset

### ISSUE THREAD

**Issue by howlwindy** [flame-engine/flame#3055]
### What happened?

```text
// My assets directory structure is like this.
/**
└── assets
    ├── images
    │   └── game
    │       └── image_name.png
    └── tiles
        └── tile_name.tmx
*/
```
```bash
# Already config flutter_gen in pubspec.yaml and get generated the file using this.
dart run build_runner build
```
```dart
// Update the game's prefix, because paths in generated file always started "assets/images" or "assets/tiles".
game.image.prefix = '';
// and loaded all images before use.
await game.images.loadAll(Assets.images.game.values.map((v) => v.keyName).toList());
```
```dart
// When I made a SpriteComponent, it worked.
class Water extends SpriteComponent with HasGameRef {
  @override
    Future<void> onLoad() async {
      final image =
          game.images.fromCache(Assets.images.game.imageName.keyName); // real path is "assets/images/game/image_name.png"
      sprite = Sprite(image);
    }
}
```
```xml
<!--In this file, the used image has a relative path-->
<image source="../images/game/image_name.png" width="64" height="64"/>
```
```dart
// But, when I use flame_tiled, it output error.
// [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unable to load asset "../images/game/image_name.png"
await TiledComponent.load(
    Assets.tiles.tileName,
    Vector2.all(64),
    prefix: '',
);
```
---
But I found when I don't update `game.image.prefix`, it will be worked.

### What do you expect?

When I update `game.image.prefix`, `TiledComponent.load` can be worked.

### Execute in a terminal and put output into the code block below

Output of: flutter doctor -v
```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.9, on macOS 13.6.4 22G513 darwin-x64)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.86.2)
[✓] Connected device (2 available)            
[✓] Network resources

• No issues found!
```

### Affected platforms

All

### Are you interested in working on a PR for this?

- [ ] I want to work on this

**Comment by ufrshubham** [comment]
If I'm not wrong the image paths in tilemaps are stored relative to the maps export location. Probably flame_tiled will have to modify the parsed paths based on the tilemaps location. The only problem is, prefix for `images` and `tiles` can be different and we wouldn't know the relation between them.

**Comment by xjyribro** [comment]
@howlwindy,
@ufrshubham is right. I faced this issue initially also. I tried to change the prefix to '' like you, but I realised this is not scalable. This is because Tiled exports supporting tileset _.tsx_ files in this format: `source="tiles.tsx"` so it makes sense for Flame to add a prefix "assets/tiles" to your tilemap files since they will be in the same folder. 

Technically you could still use add `prefix: '',` but you would have to change ALL your image sources to absolute paths: 
<image source="<root_path_here>/images/game/image_name.png" width="64" height="64"/>

**Comment by spydon** [comment]
I'll close this since there isn't any good way around it, if anyone come up with a good way we can re-open it again.

**Comment by Minority-ys** [comment]
Just pass in the corresponding path for the images in the images parameter, and it should be the same as the prefix for TiledComponent. For example, like this:
`tiledMap = await TiledComponent.load("ground.tmx", Vector2(210, 122),  
    prefix: "assets/tiles/build/",  
    images: Images(prefix: "assets/tiles/build/"));`
In this code snippet, both the prefix for TiledComponent and the prefix for Images are set to "assets/tiles/build/". This ensures that when loading the tilemap and its associated images, Flame can correctly locate and load them from the specified directory in your project's asset folder.

**Comment by Minority-ys** [comment]
Just pass in the corresponding path for the images in the images parameter, and it should be the same as the prefix for TiledComponent. For example, like this:
`
tiledMap = await TiledComponent.load(
   "ground.tmx", Vector2(210, 122),  
    prefix: "assets/tiles/build/",  
    images: Images(prefix: "assets/tiles/build/")
);
`
In this code snippet, both the prefix for TiledComponent and the prefix for Images are set to "assets/tiles/build/". This ensures that when loading the tilemap and its associated images, Flame can correctly locate and load them from the specified directory in your project's asset folder.
