### ISSUE TITLE
Render priority doesn't seems to be respected

### ISSUE THREAD

**Issue by rezendegc** [flame-engine/flame#306]
I have tried to set the priority to first render the HUD and then the world components, but it seems that no matter what the world is always rendered after the HUD. Here's the link for the project: [repository](https://github.com/rezendegc/vertical-scape-game/tree/bugs).

I don't think that there's a small piece of code to share but i've tried putting the priority as 0 on the world (box2dcomponent), and 100 on the score (lib->components->score), but still the winzone (lib->components->winzone) gets in front of the score...

**Comment by erickzanardo** [comment]
I can't spot anything wrong with your code, I wonder if the nem `Box2DGame` could be affecting this, any thoughts on this @spydon ?

**Comment by spydon** [comment]
I think it is, I'll put up a fix tomorrow.

**Comment by erickzanardo** [comment]
Fixed on 0.20.1
