### ISSUE TITLE
Box2D bodies lose momentum when app goes out of focus

### ISSUE THREAD

**Issue by spydon** [flame-engine/flame#307]
Someone else also had this problem when running in the browser and by switching back and forth between tabs, but it is not web specific.

It can easily be reproduced by running `docs/example/box2d/contact_callbacks` and turn off your device screen or change app, and then go back to the app and the bodies will have less or no momentum.

**Comment by spydon** [comment]
I think this can be fixed by pausing the update for box2d when it is not in focus, I will experiment a bit with this later. Maybe the whole engine should always pause by default when the app is not in focus?

**Comment by erickzanardo** [comment]
@spydon I don't know if we should automatically pause the engine when the app loses focus, I think that should be done by the developer, as they may want to do additional stuff when pausing.

**Comment by erickzanardo** [comment]
Any news on this @spydon ?

**Comment by spydon** [comment]
Haven't had time to investigate it more, but it's definitely a bug. I'll try looking into it tonight or tomorrow.

**Comment by erickzanardo** [comment]
Don't worry, take your time, just wanted to confirm, flagged this as bug.

**Comment by luanpotter** [comment]
I think it might be a rounding error that slowly builds up?

**Comment by spydon** [comment]
I don't think this is a rounding error, I think it is that since `dt` will be so large when the solver is called again that it will think that the bodies haven't moved or had any interaction for a long time so it puts them to sleep.
https://github.com/flame-engine/box2d.dart/blob/master/lib/src/dynamics/island.dart#L393

**Comment by erickzanardo** [comment]
@spydon did the #370 fixed this?

**Comment by spydon** [comment]
It should, but I need to confirm.

**Comment by spydon** [comment]
Confirmed that it is fixed.
