### ISSUE TITLE
TextBoxComponent with typer text shows pink image before rendering text

### ISSUE THREAD

**Issue by xjyribro** [flame-engine/flame#3070]
### What happened?

This error ONLY occurs in iOS. When trying to use the 'typer' mechanism in TextBoxComponent, a pink image is rendered for a split second before the actual text appears. This does not happen if the boxConfig param is null.

https://github.com/flame-engine/flame/assets/62128387/d7d7b59a-c793-4f3c-a122-ea8b41a224a8

### What do you expect?

There should not be a pink image rendered

### How can we reproduce this?

Create a custom TextBoxComponent and add param `boxConfig: TextBoxConfig(timePerChar: timePerChar)`. Example:

```
class DialogueTextBox extends TextBoxComponent {
  DialogueTextBox({
    required String text,
  }) : super(
          text: text,
          position: Vector2(16, 16),
          size: Vector2(704, 96),
          textRenderer: TextPaint(
            style: const TextStyle(
              fontSize: dialogueBoxFontSize,
              color: Colors.black,
              fontFamily: Strings.minecraft,
            ),
          ),
          boxConfig: TextBoxConfig(timePerChar: timePerChar),
        );
}
```

### Execute in a terminal and put output into the code block below

Output of: flutter doctor -v

### Affected platforms

iOS

### Are you interested in working on a PR for this?

- [ ] I want to work on this

**Comment by spydon** [comment]
This must be a rendering issue in Flutter, I wonder if we could reproduce it without Flame and report it.

**Comment by spydon** [comment]
@jaehong0721 does this happen without the `BlendMode`?

**Comment by spydon** [comment]
Nah, no need to downgrade, if it works on the latest version we can close this.
