### ISSUE TITLE
Strange phenomenon in flame rendering text

### ISSUE THREAD

**Issue by taosimple** [flame-engine/flame#3077]
### What happened?

The ball with text if over about 50, balls will collapse, overlap and always shaking.
![Screenshot_1710144139](https://github.com/flame-engine/flame/assets/4014593/3845bd15-5413-4c5a-8d88-02ee77b751e7)

### What do you expect?

![Screenshot_1710144009](https://github.com/flame-engine/flame/assets/4014593/13d37602-1b74-40ba-b74b-9d7f82403b3f)

### How can we reproduce this?

Just modify the contact_callbacks_example code.

contact_callbacks_example.dart
```
import 'dart:math' as math;

import 'package:examples/stories/bridge_libraries/flame_forge2d/utils/balls.dart';
import 'package:examples/stories/bridge_libraries/flame_forge2d/utils/boundaries.dart';
import 'package:flame/components.dart';
import 'package:flame/events.dart';
import 'package:flame_forge2d/flame_forge2d.dart';

class ContactCallbacksExample extends Forge2DGame {
  static const description = '''
    This example shows how `BodyComponent`s can react to collisions with other
    bodies.
    Tap the screen to add balls, the white balls will give an impulse to the
    balls that it collides with.
  ''';

  ContactCallbacksExample()
      : super(gravity: Vector2(0, 10.0), world: ContactCallbackWorld());
}

class ContactCallbackWorld extends Forge2DWorld
    with TapCallbacks, HasGameReference<Forge2DGame> {
  @override
  Future<void> onLoad() async {
    super.onLoad();
    final boundaries = createBoundaries(game);
    addAll(boundaries);
  }

  @override
  void onTapDown(TapDownEvent info) {
    super.onTapDown(info);
    final position = info.localPosition;
    if (math.Random().nextInt(10) < 2) {
      add(WhiteBall(position));
    } else {
      add(Ball(position));
    }
  }
}
```
---

balls.dart
```
import 'package:examples/stories/bridge_libraries/flame_forge2d/utils/boundaries.dart';
import 'package:flame/palette.dart';
import 'package:flame_forge2d/flame_forge2d.dart';
import 'package:flutter/material.dart';

class Ball extends BodyComponent with ContactCallbacks {
  late Paint originalPaint;
  bool giveNudge = false;
  final double radius;
  final BodyType bodyType;
  final Vector2 _position;

  final textPainter = TextPainter(textDirection: TextDirection.ltr);
  late Offset textOffset;

  Ball(
    this._position, {
    this.radius = 3.5,
    this.bodyType = BodyType.dynamic,
    Color? color,
  }) {
    if (color != null) {
      originalPaint = PaletteEntry(color).paint();
    } else {
      originalPaint = randomPaint();
    }
    paint = originalPaint;
  }

  Paint randomPaint() => PaintExtension.random(withAlpha: 0.9, base: 100);

  @override
  Future<void> onLoad() {
    textPainter.text = const TextSpan(text: '💊', style: TextStyle(fontSize: 3));
    textPainter.layout();
    textOffset = Offset(-textPainter.width/2, -textPainter.height/2);
    return super.onLoad();
  }

  @override
  Body createBody() {
    final shape = CircleShape();
    shape.radius = radius;

    final fixtureDef = FixtureDef(
      shape,
      restitution: 0.8,
      friction: 0.4,
    );

    final bodyDef = BodyDef(
      userData: this,
      angularDamping: 0.8,
      position: _position,
      type: bodyType,
    );

    return world.createBody(bodyDef)..createFixture(fixtureDef);
  }

  @override
  void renderCircle(Canvas canvas, Offset center, double radius) {
    super.renderCircle(canvas, center, radius);
    textPainter.paint(canvas, textOffset);
  }
}

class WhiteBall extends Ball with ContactCallbacks {
  WhiteBall(super.position) {
    originalPaint = BasicPalette.white.paint();
    paint = originalPaint;
  }

  @override
  void beginContact(Object other, Contact contact) {
    if (other is Ball) {
      other.giveNudge = true;
    }
  }
}
```

### What steps should take to fix this?

If comment the line `textPainter.paint(canvas, textOffset);` will work as expected, it seems like flame text(or emoji) rendering performance issue?

### Execute in a terminal and put output into the code block below

Output of: flutter doctor -v
[✓] Flutter (Channel stable, 3.19.2, on macOS 13.6 22G120 darwin-arm64 (Rosetta), locale en-US)
    • Flutter version 3.19.2 on channel stable at /Users/taotao/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7482962148 (12 days ago), 2024-02-27 16:51:22 -0500
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/taotao/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/taotao/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

### Affected platforms

Android

### Other information

Only test on android emulator
```
  flame: ^1.16.0
  flame_forge2d: ^0.17.0
  ```

### Are you interested in working on a PR for this?

- [ ] I want to work on this

**Comment by taosimple** [comment]
Supplementary video
[untitled-2.webm](https://github.com/flame-engine/flame/assets/4014593/8fa20bd6-e170-44d8-836a-51ea1b38a2e1)

**Comment by spydon** [comment]
Are you losing FPS when this happens?

**Comment by taosimple** [comment]
@spydon Yes, there seems to be some losing FPS.

**Comment by spydon** [comment]
I guess when `dt` starts growing when the FPS goes down it will hit max force between the balls and the calculations start to break down. I didn't know the text painter would be that heavy though, have you tried this on multiple platforms?

**Comment by taosimple** [comment]
@spydon The performance is still normal when I test up to 100 balls on the Android physical device. As it stands now, it is acceptable.

**Comment by spydon** [comment]
Ah alright, this was only in the emulator? Performance issues are quite common on the emulators.

**Comment by spydon** [comment]
I'll close this since it only seems to happen on emulators
