### ISSUE TITLE
Convert ClipComponent factory Constructor to redirecting Constructor.

### ISSUE THREAD

**Issue by YukiAttano** [flame-engine/flame#3083]
### What could be improved

The ClipComponent Class has 3 factory Constructor "circle", "rectangle", "polygon". 
I suggest that "circle" and "rectangle" factory constructor can be converted into redirecting constructor.

### Why should this be improved

As of my understanding, redirecting constructor are more performant than factory constructor as they initialize an object in one step and not taking one step per parameter.

But beside that, if they are converted to redirecting constructor, they allow subclasses to call them during initialization.
```dart
// Example:
Subclass.rectangle() : super.rectangle(); 
```

### Risks

As the notation do not change, this won't change the API for current users. 
Risks could be, that assertions in the constructor itself are no longer possible for further parameter (Thats why, ClipComponent.polygon should stay the way it is).

It will also no longer be possible, to change this behavior back without adding the risk to break implementations of user.

### Other

- [X] Are you interested in working on a PR for this?

**Comment by spydon** [comment]
Sounds good, I'll assign you to the issue.
Maybe the assertion could be moved to the builder instead, and then the polygon one could also be a redirect.
