### ISSUE TITLE
Problem with alpha in web

### ISSUE THREAD

**Issue by billy1380** [flame-engine/flame#309]
I have been working on a port of the godot game "Blaster Faster".

https://www.youtube.com/channel/UChv-gaPlKNROf6iMDhxIpUA/videos

I finished the port but when I ran it on web transparency/alpha does not seem to work as expected.

Mac OS
<img width="369" alt="Screenshot 2020-05-03 at 20 22 30" src="https://user-images.githubusercontent.com/1329727/80923527-45849780-8d7c-11ea-963d-45619c7ba3f8.png">

Web
<img width="369" alt="Screenshot 2020-05-03 at 20 21 24" src="https://user-images.githubusercontent.com/1329727/80923532-487f8800-8d7c-11ea-87d3-87bb9d698df2.png">

I have ported other flutter apps to web and as far as I know there is no issue with alpha. Any thoughts?

**Comment by billy1380** [comment]
Can also be viewed here

https://www.willshex.com/blasterfaster/#/

**Comment by erickzanardo** [comment]
Hey, before we go any further on this, keep in mind that the web support is really experimental, as Flutter is still on beta and many things are unstable, Flame does little regarding the graphics APIs, so many issues come directly from Flutter itself and there is little we can do.

By looking on your screenshot, it seems that you are not using the use skia flag to run your game, can you confirm that? If you indeed aren't using it, give it a try, just run:

```
$ flutter run --release -d Chrome --dart-define=FLUTTER_WEB_USE_SKIA=true
```

If that don't work as well, please tell us more how are you rendering, and share some code as well.

**Comment by billy1380** [comment]
@erickzanardo I just did a build using SKIA and it worked perfectly. Many thanks. Happy to close this.

**Comment by erickzanardo** [comment]
Awesome, glad you got this working!
