### ISSUE TITLE
texture packer can't override images

### ISSUE THREAD

**Issue by ABausG** [flame-engine/flame#3096]
### Problem to solve

When using an Animation from TexturePacker where the assets are in a separate package, it is required to override the prefix of both the `AssetsCache` as well as as the `Images` to include `packages/my_package`

The `AssetsCache` can be overridden easily as texture_packer uses `Flame.assets` https://github.com/flame-engine/flame/blob/b1f01986b440ac18bb35b0d76963b2c66f49ea33/packages/flame_texturepacker/lib/src/texture_packer_atlas.dart#L104

However when loading the texture it uses a private custom image storage.

https://github.com/flame-engine/flame/blob/b1f01986b440ac18bb35b0d76963b2c66f49ea33/packages/flame_texturepacker/lib/src/texture_packer_atlas.dart#L147

This can't be overriden.

### Proposal

Use `Flame.images` to load the texture.
When loading the texture from a Storage this is already hapenning
https://github.com/flame-engine/flame/blob/b1f01986b440ac18bb35b0d76963b2c66f49ea33/packages/flame_texturepacker/lib/src/texture_packer_atlas.dart#L142

Making https://github.com/flame-engine/flame/blob/b1f01986b440ac18bb35b0d76963b2c66f49ea33/packages/flame_texturepacker/lib/src/texture_packer_atlas.dart#L147 the only usage of the private `_images` field

### Other

- [x] Are you interested in working on a PR for this?

**Comment by ABausG** [comment]
I started to work on the change here:

https://github.com/ABausG/flame/commit/956bfd3778823debd60a78117239ac1a35e9745d

However I noticed that the current default/readme expects everything to be in `assets/` while the default `Flame.images` defaults to `assets/images/` 

For me this feels like there are some inconsistencies there. 

Maybe another approach might be to expose the `_images` of the `flame_texturepacker` to be able to override the prefix there?

**Comment by spydon** [comment]
One way could be to do it like in the [parallax](https://github.com/flame-engine/flame/blob/main/packages/flame/lib/src/parallax.dart#L147) to allow passing in a image cache.
I think it's worth removing the inconsistency and let it default to `Flame.images` and then we'll bump the major version of the bridge package.
@Yayo-Arellano might not be your code, but do you know if there is any point in it having its own cache as default like it does now?

**Comment by Yayo-Arellano** [comment]
@ABausG I think you can create a PR with the change. Remember to move the assets from `example/assets` to `example/assets/images`.

**Comment by ABausG** [comment]
Hope to get this done today. Otherwise will have to wait until after easter!

@spydon Apart from adjusting the readme and docs about this is there anything else I can/should do to provide a migration guide?

**Comment by spydon** [comment]
@ABausG when opening a PR there is a section with migration instructions, they will end up in the changelog, other than that there's nothing more to do.
