### ISSUE TITLE
I'd like to call the child onRemove.

### ISSUE THREAD

**Issue by ttb-inc** [flame-engine/flame#3102]
### What happened?

The onRemove function of the child Component added to the RouterComponent is not called.

### What do you expect?

You want to call the onRemove function of a child Component added to the RouterComponent.

### How can we reproduce this?

```dart
class Game extends StatelessWidget {
  const Game({super.key});

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: GameWidget(
        game: GameRouter(),
      ),
    );
  }
}

class GameRouter extends FlameGame {
  late final RouterComponent router;

  @override
  void onRemove() {
    super.onRemove();
    consoleLog('GameRouter::onRemove');
  }

  @override
  void onMount() {
    super.onMount();
    consoleLog('GameRouter::onMount');
  }

  @override
  void onLoad() {
    /// router
    router = RouterComponent(
      initialRoute: GameRoute.main,
      routes: {
        GameRoute.main: Route(SceneMain.new),
      },
    );

    /// add
    add(router);
  }
}


class SceneMain extends ShapeComponent with HasGameRef {
  @override
  void onRemove() {
    super.onRemove();
    consoleLog('SceneMain::onRemove');
  }
 
  @override
  void onMount() {
    super.onMount();
    consoleLog('SceneMain::onMount');
  }

  @override
  void onLoad() {
  }
}
```

log
```
... navigation push ...
GameRouter::onMount
SceneMain::onMount

... navigation pop ...
GameRouter::onRemove
```

In the code above, the "SceneMain::onRemove" log is not output.
How do I call the SceneMain::onRemove function?

Thank you.

### Execute in a terminal and put output into the code block below

Output of: flutter doctor -v

### Affected platforms

Android, iOS

### Are you interested in working on a PR for this?

- [ ] I want to work on this

**Comment by spydon** [comment]
This is working as it is intended (and is specified in the docs), if you want all the children to be removed from the game when you pop you can run something like this in the game's `onRemove`:
```dart
void remove() {
  propagateToChildren((c) {
    c.removeFromParent();
    return true;
  });
  super.onRemove();
}
```

**Comment by ttb-inc** [comment]
> This is working as it is intended (and is specified in the docs), if you want all the children to be removed from the game when you pop you can run something like this in the game's `onRemove`:
> 
> ```dart
> void remove() {
>   propagateToChildren((c) {
>     c.removeFromParent();
>     return true;
>   });
>   super.onRemove();
> }
> ```

Thank you for your help.

I read the comments and went a little bit further.
I don't know if it's right, but here's what I did.
```dart
  @override
  void onRemove() {
    propagateToChildren((p0) {
      (p0 as Component?)?.onRemove();
      return true;
    });
    super.onRemove();
  }
```

**Comment by spydon** [comment]
@ttb-inc that looks correct yes, it shouldn't need to be casted to `Component?` though.

**Comment by ttb-inc** [comment]
> @ttb-inc that looks correct yes, it shouldn't need to be casted to `Component?` though.

Yes, I got it.
Thanks a lot.

Have a good one!!!
