### ISSUE TITLE
Add onFinished callback to ScrollTextBoxComponent

### ISSUE THREAD

**Issue by KurtLa** [flame-engine/flame#3104]
### Problem to solve

If a long text is displayed, the caller cannot be notified when the text has fully appeared. This is necessary for playing animations, adding HUD elements or similar.

### Proposal

Enhance the `ScrollTextBoxComponent` by providing a callback function that triggers upon the complete display of the text.

### Other

- [X] Are you interested in working on a PR for this?

**Comment by spydon** [comment]
This is done right @KurtLa?

**Comment by KurtLa** [comment]
Yes, that's done - but the title is now misleading. It's `onComplete` now :)
