### ISSUE TITLE
rotate box2d component

### ISSUE THREAD

**Issue by glennmichaelmejias** [flame-engine/flame#312]
how i can rotate box2d component anumated? its like tweening between angles on a certain time. thanks

**Comment by spydon** [comment]
The simplest way is to give the body a angular impulse in the update method and then another angular impulse the other direction once it has reached the wanted angle. 
`body.applyAngularImpulse(impulse);`
I find this tutorial quite helpful when it comes to rotation:
https://www.iforce2d.net/b2dtut/rotate-to-angle
It is for C++, but it is quite easy to translate what to do in Dart.

**Comment by glennmichaelmejias** [comment]
thanks. i tried it but its not working, is there some setup for it?

**Comment by glennmichaelmejias** [comment]
all applyforces on my code is not working.

`final fixtureDef = FixtureDef();

      fixtureDef.shape = shape;


      

      fixtureDef.restitution =
          0.5;
      fixtureDef.friction = 0.1;

      final bodyDef = BodyDef();

      bodyDef.setPosition(Vector2(thep.dx, -thep.dy));

        bodyDef.type = BodyType.DYNAMIC;



      fixtureDef.density = 0.1;
      bodyDef.gravityScale =
          100;

      Body groundBody = world.createBody(bodyDef);

      groundBody.createFixtureFromFixtureDef(fixtureDef);

      this.body = groundBody;`

**Comment by spydon** [comment]
Can you show the part of your update method where you apply the forces?

**Comment by glennmichaelmejias** [comment]
when should i put the body.applyangularimpulse? i want that when i click a button it rotates.

**Comment by spydon** [comment]
You could for example set some boolean or state when pressing the button and then look at that in the update method and apply the angular impulse.

**Comment by erickzanardo** [comment]
Closing due inactivity, let us know if you have more question, or hit us on discord
