### ISSUE TITLE
Input System should be improve

### ISSUE THREAD

**Issue by devchenli** [flame-engine/flame#3137]
### What could be improved

Input System should be improved

### Why should this be improved

Currently, when using KeyboardEvents or KeyboardHandler, it's necessary to manually implement methods for keyUp and keyDown events. This becomes quite cumbersome, especially when developing games where player movement is controlled by keyboard inputs. We suggest implementing a new Input class. You can use it like 

> 'var direction = Input.get_axis("up|down|left|right")'

or 

> 'var direction = Input.get_axis("horizontal"| "vertical")'

to directly obtain the values generated by user key presses.

### Other

- [ ] Are you interested in working on a PR for this?

**Comment by spydon** [comment]
I don't fully understand how you suggestion would work, but have you tried the `KeyboardListenerComponent`?
