### ISSUE TITLE
Is it possible to make the camera smoothly follow the player?

### ISSUE THREAD

**Issue by devchenli** [flame-engine/flame#3138]
### Problem to solve

The camera's movement is too jerky when it follows the player. 

### Proposal

It would be great to have a smooth camera movement option with adjustable smoothness parameters.

### Other

- [ ] Are you interested in working on a PR for this?

**Comment by ufrshubham** [comment]
It depends on what the camera is following. If the component it is following moves smoothly, the camera should move smoothly too.

**Comment by spydon** [comment]
Just set the `maxSpeed` argument in `camera.follow` to something lower and it will move smoothly.

**Comment by devchenli** [comment]
> Just set the `maxSpeed` argument in `camera.follow` to something lower and it will move smoothly.

Thank you, I think I understand what you mean. However, unfortunately, setting the speed alone is not enough. If you have used Cinemachine in Unity or the Position Smoothing and Drag properties of the Camera in Godot, you will see that they achieve a very good effect. Similar to the protagonist in a movie, when the player only moves a short distance, the camera remains stationary. However, when the player moves a sufficient distance, the camera will follow the movement and accelerate smoothly linearly like a movie lens, rather than simply following the player's movement exactly.

**Comment by ufrshubham** [comment]
> However, when the player moves a sufficient distance, the camera will follow the movement and accelerate smoothly linearly like a movie lens, rather than simply following the player's movement exactly.

IMO, this can be easily achieved by introducing a follower component which implements these custom following logic. So FollowerComponent tracks Player and camera simply follows the FollowerComponent normally.

It might also be worth it to create a new package similar to cinemachine instead of adding more code to the existing camera.

**Comment by spydon** [comment]
> It might also be worth it to create a new package similar to cinemachine instead of adding more code to the existing camera.

Maybe we should add a curve argument for the movement, I think that should do it too.

**Comment by devchenli** [comment]
The expected camera movement is like this :

https://github.com/flame-engine/flame/assets/46481943/bafd8833-e711-41cb-88c7-f7886c2c790f

I would really appreciate it if this functionality could be implemented either by creating a new package(like unity) or adding a curve argument for the movement (like godot) . Thank you all for your consideration.

**Comment by renancaraujo** [comment]
I implemented this on [Turi](https://github.com/renancaraujo/turi) by having an invisible [position component](https://github.com/renancaraujo/turi/blob/105130def30538860569e19a34a88cea9da5a910/lib/game/components/camera_target.dart) as constant [camera target](https://github.com/renancaraujo/turi/blob/105130def30538860569e19a34a88cea9da5a910/lib/game/crystal_ball_game.dart#L65). Then, by apllying [Effects](https://docs.flame-engine.org/latest/flame/effects.html) to this component's position ([with curves](https://github.com/renancaraujo/turi/blob/105130def30538860569e19a34a88cea9da5a910/lib/game/components/camera_target.dart#L33)), one can have such effect.




Video for reference: https://twitter.com/i/status/1717496557422141465
