### ISSUE TITLE
Pixel Anti Aliasing

### ISSUE THREAD

**Issue by dbroadhurst** [flame-engine/flame#3149]
### What happened?

When I arrange sprites in a grid and see background pixel appearing due to anti aliasing

<img width="1274" alt="Screenshot 2024-05-06 at 8 53 12 AM" src="https://github.com/flame-engine/flame/assets/5667105/4d3f46da-ef78-4a47-9399-1e0b0da4d202">

I tried the following without any improvement

````
sprite.paint.isAntiAlias = false;
sprite.paint.filterQuality = FilterQuality.low;
````

### What do you expect?

Expect to see no unexpected visual artifacts

### How can we reproduce this?

Arrange sprites in a grid. I suspect this is a known issue but can't find a way to fix.

### Execute in a terminal and put output into the code block below

Output of: flutter doctor -v

### Affected platforms

All

### Are you interested in working on a PR for this?

- [ ] I want to work on this

**Comment by spydon** [comment]
It is this issue: https://github.com/flutter/flutter/issues/14288
Are you sure it is happening on all platforms for you? Even Impeller backed ones?

Erick has wrote a bit about it here:
https://verygood.ventures/blog/solving-super-dashs-rendering-challenges-eliminating-ghost-lines-for-a-seamless-gaming-experience

**Comment by spydon** [comment]
There's also some discussion about it in here: https://github.com/flame-engine/flame/issues/1152

**Comment by dbroadhurst** [comment]
I got AA working. Turns out setting AA in the constructor works but setting the instance does not work. Impeller seems broken right now.

Works
````
class BuildingBlock extends SpriteComponent
    with HasGameRef<PlunderGame>, CollisionCallbacks {
  BuildingBlock({required Sprite sprite, required double x, required double y})
      : super(
          sprite: sprite,
          position: Vector2(x, y),
          size: Vector2(32, 32),
          paint: Paint()..isAntiAlias = false,
        );
}
````

Does not work
````
  var sprite = spriteSheet.getSpriteById(block);
        sprite.paint.isAntiAlias = false;
        sprite.paint.filterQuality = FilterQuality.none;
        _world.add(BuildingBlock(
          sprite: sprite,
          x: blockX,
          y: blockY,
        ));
````

**Comment by spydon** [comment]
Right, that is because the component is using its own paint object, not the one inside `Sprite`, so you could also set it with `component.paint = ...` for example.
