### ISSUE TITLE
[iOS] I get an error when building iOS Archive.

### ISSUE THREAD

**Issue by ttb-inc** [flame-engine/flame#3161]
### What happened?

Hi,

I get an error when building iOS Archive.

[O] Android debug, release build.
[O] iOS debug build.
[X] iOS release(Archive) build.

It was working fine before, and it's happening after Flutter 3.22.0 upgrade.

Are there any possible workarounds?

```
  # flame
  flame: 1.17.0                     # https://pub.dev/packages/flame/versions
  flame_audio: 2.10.1               # https://pub.dev/packages/flame_audio/versions
  flame_forge2d: 0.18.0             # https://pub.dev/packages/flame_forge2d/versions
```

I'm using the above package and if I disable it, the archive will work fine.

[all_pubspec_yaml.zip](https://github.com/flame-engine/flame/files/15343756/all_pubspec_yaml.zip)

Thank you.

### What do you expect?

I want it to be an error-free release build.

### Relevant log output

```shell
error: Unhandled exception:
RangeError (offset): Invalid value: Not in inclusive range 0..174: 480
#0      RangeError.checkValueInInterval (dart:core/errors.dart:313)
#1      Source.getLocation (package:kernel/ast.dart:14992)
#2      Component.getLocation (package:kernel/ast.dart:14787)
#3      _getLocationInComponent (package:kernel/ast.dart:15181)
#4      Procedure._getLocationInEnclosingFile (package:kernel/ast.dart:3329)
#5      TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:207)
#6      TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:207)
#7      TreeNode.location (package:kernel/ast.dart:203)
#8      localFunctionName (package:vm/transformations/type_flow/utils.dart:449)
#9      SummaryCollector.createSummary (package:vm/transformations/type_flow/summary_collector.dart:628)
#10     TypeFlowAnalysis.getSummary (package:vm/transformations/type_flow/analysis.dart:1782)
#11     _DirectInvocation._processFunction (package:vm/transformations/type_flow/analysis.dart:398)
#12     _DirectInvocation.process (package:vm/transformations/type_flow/analysis.dart:287)
#13     _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1663)
#14     _WorkList.process (package:vm/transformations/type_flow/analysis.dart:1606)
#15     TypeFlowAnalysis.process (package:vm/transformations/type_flow/analysis.dart:1811)
#16     transformComponent (package:vm/transformations/type_flow/transformer.dart:121)
#17     runGlobalTransformations (package:vm/kernel_front_end.dart:589)
#18     compileToKernel (package:vm/kernel_front_end.dart:489)
<asynchronous suspension>
#19     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:639)
<asynchronous suspension>
#20     starter (package:frontend_server/starter.dart:101)
<asynchronous suspension>
#21     main (file:///Volumes/Work/s/w/ir/x/w/sdk/pkg/frontend_server/bin/frontend_server_starter.dart:13)
<asynchronous suspension>

Target kernel_snapshot failed: Exception
Failed to package /Users/myaccount/Desktop/work/myapp/myapp.
```

### Execute in a terminal and put output into the code block below

[✓] Flutter (Channel stable, 3.22.0, on macOS 14.4.1 23E224 darwin-arm64, locale ko-KR)
    • Flutter version 3.22.0 on channel stable at /Users/jeonglockpark/Desktop/work/flutter_sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5dcb86f68f (8 days ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/jeonglockpark/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Network resources
    • All expected network resources are available.

• No issues found!

### Affected platforms

iOS

### Are you interested in working on a PR for this?

- [ ] I want to work on this

**Comment by spydon** [comment]
Which of the packages is it coming from?

**Comment by ttb-inc** [comment]
> Which of the packages is it coming from?

Are you asking me to tell you which package has the error?

flame: 1.17.0
flame_audio: 2.10.1
flame_forge2d: 0.18.0

I'm guessing it's one of the three above, but let's check.

**Comment by ttb-inc** [comment]
```
  # flame
  flame: 1.17.0                     # https://pub.dev/packages/flame/versions
#  flame_audio: 2.10.1               # https://pub.dev/packages/flame_audio/versions
#  flame_forge2d: 0.18.0             # https://pub.dev/packages/flame_forge2d/versions

```

I get the same error when I apply only the [flame] package.

**Comment by ttb-inc** [comment]
There seems to be a conflict in the Run Script. 😥

<img width="844" alt="1" src="https://github.com/flame-engine/flame/assets/59724931/1a85d38f-afa9-47df-bdfb-3c8eb3a3a73d">

<img width="844" alt="2" src="https://github.com/flame-engine/flame/assets/59724931/c6aa890e-1a3b-452c-adf3-593083f9ef13">

**Comment by ttb-inc** [comment]
I'm looking into it, but it doesn't seem to be a Flame issue.
We'll do some more testing and close the issue.
