### ISSUE TITLE
Docs for IsometricTileMapComponent example shows something inexistent

### ISSUE THREAD

**Issue by immadisairaj** [flame-engine/flame#3163]
### What could be improved

I was just casually going through the component to try it out for the first time. Then I stumbled upon this below screenshot.
![Screenshot 2024-05-18 at 20 54 05](https://github.com/flame-engine/flame/assets/40348358/f6a6e7c7-7941-46b5-ab80-dad5c64cf88f)

Where there is `IsometricTileset` where I am confused as I don't see that method or class anywhere.

Until I saw the example code, I didn't know how to proceed further. Maybe this minimal example code could be updated to show proper working code. This kind of things might be there for other components as well? (not sure). But, as I came across this one, found it to be a problem.

### Why should this be improved

When trying out something with new components, the first place would be docs and when this kind of issue comes, people might back out or have to go into example to look why they are facing the error.

### More information

Line in code: https://github.com/flame-engine/flame/blob/6d7eeee3983ae2d9c169ab05a9674b6c30c40f6a/doc/flame/components.md?plain=1#L1234

Proposed solution:
Changing it to `SpriteSheet`?
```dart
// Creates a tileset, the block ids are automatically assigned sequentially
// starting at 0, from left to right and then top to bottom.
final tilesetImage = await images.load('tileset.png');
final tileset = SpriteSheet(image: tilesetImage, srcSize: Vector2.all(32));
// Each element is a block id, -1 means nothing
final matrix = [[0, 1, 0], [1, 0, 0], [1, 1, 1]];
add(IsometricTileMapComponent(tileset, matrix));
```

### Other

- [X] Are you interested in working on a PR for this?

**Comment by ufrshubham** [comment]
@immadisairaj nice catch 🙂. I've assigned this to you.
