### ISSUE TITLE
Use the flame_texturepacker , Paired with SpriteAnimationGroupComponent， but can't work.

### ISSUE THREAD

**Issue by ycfay** [flame-engine/flame#3180]
### Problem to solve

the code 
```
class YangMonster extends Monster {
  late TexturePackerAtlas atlas;

  @override
  Future<void> onLoad() async {
    atlas = await game.atlasFromAssets('tester/shiki/sni.atlas');
    await prepareAnimations();
    await super.onLoad();
  }

  @override
  Future<void> prepareAnimations() async {
    animations = {};
    for (var action in PlayerState.values) {
      final sprites = atlas.findSpritesByName(action.name);
      if (sprites.isNotEmpty) {
        SpriteAnimation animation = SpriteAnimation.spriteList(
          sprites,
          stepTime: 0.2,
          loop: true,
        );
        animations!.addAll({action: animation});
      }
    }
    current = PlayerState.idle_down;
    size = Vector2.all(60);
    //         add(
    //   SpriteAnimationComponent(scale: Vector2.all(0.5), animation: animation),
    // );
  }
}
```
i must `add(SpriteAnimationComponent...)` to be able to work, which is not what I was hoping for！

### Proposal

I hope to be able to support SpriteAnimationGroupComponent.

### Other

- [ ] Are you interested in working on a PR for this?

**Comment by spydon** [comment]
Can you do `print(animations);` after you have prepared them?

**Comment by ycfay** [comment]
print(animations)
the result:
`flutter: {PlayerState.attack_down: Instance of 'SpriteAnimation', PlayerState.attack_down_left: Instance of 'SpriteAnimation', PlayerState.attack_down_right: Instance of 'SpriteAnimation', PlayerState.attack_left: Instance of 'SpriteAnimation', PlayerState.attack_right: Instance of 'SpriteAnimation', PlayerState.attack_up: Instance of 'SpriteAnimation', PlayerState.attack_up_left: Instance of 'SpriteAnimation', PlayerState.attack_up_right: Instance of 'SpriteAnimation', PlayerState.idle_up: Instance of 'SpriteAnimation', PlayerState.idle_down: Instance of 'SpriteAnimation', PlayerState.idle_left: Instance of 'SpriteAnimation', PlayerState.idle_right: Instance of 'SpriteAnimation', PlayerState.idle_down_left: Instance of 'SpriteAnimation', PlayerState.idle_down_right: Instance of 'SpriteAnimation', PlayerState.idle_up_left: Instance of 'SpriteAnimation', PlayerState.idle_up_right: Instance of 'SpriteAnimation', PlayerState.run_down: Instance of 'SpriteAnimation', PlayerState.run_down_left: Instance of 'SpriteAnimation', PlayerState.run_down_right: Instance of 'SpriteAnimation', PlayerState.run_left: Instance of 'SpriteAnimation', PlayerState.run_right: Instance of 'SpriteAnimation', PlayerState.run_up_left: Instance of 'SpriteAnimation', PlayerState.run_up_right: Instance of 'SpriteAnimation', PlayerState.run_up: Instance of 'SpriteAnimation', PlayerState.death_down: Instance of 'SpriteAnimation', PlayerState.death_down_left: Instance of 'SpriteAnimation', PlayerState.death_down_right: Instance of 'SpriteAnimation', PlayerState.death_left: Instance of 'SpriteAnimation', PlayerState.death_right: Instance of 'SpriteAnimation', PlayerState.death_up: Instance of 'SpriteAnimation', PlayerState.death_up_left: Instance of 'SpriteAnimation', PlayerState.death_up_right: Instance of 'SpriteAnimation'}`

**Comment by ycfay** [comment]
the base class
```
class Monster extends SpriteAnimationGroupComponent<PlayerState>
    with HasGameRef<Test8Game>, CollisionCallbacks {
  @override
  Future<void> onLoad() async {

  }

  Future<void> prepareAnimations() async {}
}
```

**Comment by spydon** [comment]
Which version of Flame are you on?

**Comment by ycfay** [comment]
flame: ^1.18.0
  flame_texturepacker: ^4.0.1

I think it's the components haven't been adapted yet！

**Comment by spydon** [comment]
They should be fine, the output are just normal `SpriteAnimation` instances which is what `SpriteGroupComponent` handles. Can you provide a repository (it can be private, but you'd have to invite me) with a minimal reproducible example, containing the atlas etc?

**Comment by ycfay** [comment]
The code has been uploaded to GitHub:
[https://github.com/ycfay/tsdm.git](url)

Tkx

**Comment by spydon** [comment]
Now I see what you're problem is, you have to use the `animations` setter, not mutate the existing map since the animations then won't get any animation tickers etc. So do this instead:
```dart
  @override
  Future<void> prepareAnimations() async {
    // The size I would put in the constructor
    size = Vector2.all(60);
    
    final newAnimations = {};
    for (var action in PlayerState.values) {
      final sprites = atlas.findSpritesByName(action.name);
      if (sprites.isNotEmpty) {
        SpriteAnimation animation = SpriteAnimation.spriteList(
          sprites,
          stepTime: 0.2,
          loop: true,
        );
        newAnimations.addAll({action: animation});
      }
    }
    animations = newAnimations;
    current = PlayerState.idle_down;
  }
  ```

**Comment by spydon** [comment]
Disallowed these mutations in #3183 to avoid confusion in the future.

**Comment by ycfay** [comment]
It worked, thanks！
