### ISSUE TITLE
SpriteWidget.srcPosition and srcSize are not really used

### ISSUE THREAD

**Issue by erickzanardo** [flame-engine/flame#3194]
### What happened?

`SpriteWidget` class imitates `Sprite` and has two fields  `srcPosition` and `srcSize`.

Those are not used though, what matters are the fields inside the `Sprite` instance that it holds.

### What do you expect?

We should remove those fields from `SpriteWidget` to avoid confusion.

### Execute in a terminal and put output into the code block below

Output of: flutter doctor -v

### Affected platforms

All

### Are you interested in working on a PR for this?

- [X] I want to work on this

**Comment by spydon** [comment]
They only seem to be present on the `asset` constructor and there they are used?

**Comment by erickzanardo** [comment]
Yeah, they kinda are, but then on the `asset` constructor we can just transform them into constructors argument, they don't need to be fields

**Comment by erickzanardo** [comment]
Those two fields in the default constructor just made me stare at my game for around 5 minutes trying to understand why my sprite was being rendered messed up hahah

**Comment by spydon** [comment]
But they aren't fields, and they aren't on the default constructor, are we really looking at the same class? :sweat_smile: 
```dart
  /// renders the [sprite] as a Widget.
  ///
  /// To change the source size and position, see [Sprite.new]
  const SpriteWidget({
    required Sprite sprite,
    this.anchor = Anchor.topLeft,
    this.angle = 0,
    this.errorBuilder,
    this.loadingBuilder,
    super.key,
  }) : _spriteFuture = sprite;
```

**Comment by erickzanardo** [comment]
Oh, this was removed in the last version 😅 

https://github.com/flame-engine/flame/commit/f49d24c02dd0d9b781926908bad1fb6dfcbda5f2
