### ISSUE TITLE
ParallaxImageData class missing from import

### ISSUE THREAD

**Issue by co01y4p** [flame-engine/flame#3195]
### What happened?

wanted to use ParallaxImageData class, upon import, i still unable to use it
until i manually import via **import 'package:flame/src/parallax.dart';**

### What do you expect?

don't need extra **import 'package:flame/src/parallax.dart';**
just normal import 'package:flame/.....' will do

### How can we reproduce this?

try to use ParallaxImageData class
- flutter doctor:
Channel stable, 3.22.2, on macOS 14.0 23A344 darwin-arm64

### Do have an example of where the bug occurs?

<img width="1357" alt="Screenshot 2024-06-16 at 01 59 17" src="https://github.com/flame-engine/flame/assets/67593543/8a837cf1-f7e5-484b-96f5-f74d6b259a6e">
<img width="1358" alt="Screenshot 2024-06-16 at 02 00 00" src="https://github.com/flame-engine/flame/assets/67593543/c8c70b62-908b-4288-a0e1-492d6f10e213">

### Execute in a terminal and put output into the code block below

Output of: flutter doctor -v

[✓] Flutter (Channel stable, 3.22.2, on macOS 14.0 23A344 darwin-arm64, locale en-MY)
    • Flutter version 3.22.2 on channel stable at ***
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (10 days ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
    • Android SDK at /Users/yaphanyee/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.90.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (4 available)
    • iPhone 15 Pro (mobile)          • 7C3B40C7-F7DF-4272-BDC7-137E034024F4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 117.0.5938.149
    ! Error: Browsing on the local area network for HanYee’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

### Affected platforms

All

### Are you interested in working on a PR for this?

- [ ] I want to work on this

**Comment by spydon** [comment]
It is enough to just import that barrel file since it is exported from there:
```dart
import 'package:flame/parallax.dart;
```
