### ISSUE TITLE
`SpriteAnimationComponent.fromFrameData` missing nativeAngle

### ISSUE THREAD

**Issue by Mythar** [flame-engine/flame#3196]
### What could be improved

The SpriteAnimationComponent.fromFrameData is missing nativeAngle.

I would also love to have "Mirror" and "Flip" in the SpriteAnimationComponent :)

### Why should this be improved

Imo fromFrameData should have this.

### Risks

None

### Other

- [ ] Are you interested in working on a PR for this?

**Comment by spydon** [comment]
There are two different issues in here, the first one I fixed in #3197 :)

> I would also love to have "Mirror" and "Flip" in the SpriteAnimationComponent :)

Do you just mean `flipHorizontally` and `flipVertically`? Because those methods already exist
