### ISSUE TITLE
box2d collision

### ISSUE THREAD

**Issue by glennmichaelmejias** [flame-engine/flame#320]
how can i make a box2d object does not affect physics world but still able to detect collision? thanks.

**Comment by spydon** [comment]
Can you explain a bit more, should the object itself not move either if some object hits it?
Like a zone that your object can end up in?
https://www.iforce2d.net/b2dtut/collision-filtering
If I understand you correctly you probably need to change the fixtures `categoryBits` and `maskBits`.

**Comment by glennmichaelmejias** [comment]
like when the object hits it it will not move but still it can detect collision. its like an object will pass through an object and detect collision.

**Comment by spydon** [comment]
Then you'll have to have a look at how `categoryBits` and `maskBits` works, try the link that I sent.

**Comment by erickzanardo** [comment]
Closing due inactivity, let us know if you have more question, or hit us on discord
