### ISSUE TITLE
DraggableBox from forge2d examples does not follow the cursor smoothly. 

### ISSUE THREAD

**Issue by ksokolovskyi** [flame-engine/flame#3203]
### What happened?

When dragging `DraggableBox` it does not follow the cursor smoothly. When the box can move in both the X and Y axes, its movement becomes even more unpredictable.

The recordings of the mentioned behavior are present below:

<details closed><summary>GearJointExample</summary>
<video src="https://github.com/flame-engine/flame/assets/30288967/8188ed18-e0aa-4c0f-a6c4-092015ba471c">
</details>

<details closed><summary>PrismaticJointExample</summary>
<video src="https://github.com/flame-engine/flame/assets/30288967/80ca56cd-7b7c-4a12-a551-37f268011bb0">
</details>

<details closed><summary>PulleyJointExample</summary>
<video src="https://github.com/flame-engine/flame/assets/30288967/1d40b0a0-57d2-444e-a324-63112548f9e3">
</details>

<details closed><summary>RopeJointExample</summary>
<video src="https://github.com/flame-engine/flame/assets/30288967/60b2ceee-4a41-4443-a2db-de5515270f18">
</details>

### What do you expect?

`DraggableBox` smoothly follows the cursor.

### How can we reproduce this?

The behavior described can be reproduced in the following examples:
- `GearJointExample`
- `PrismaticJointExample`
- `PulleyJointExample`
- `RopeJointExample`

### Execute in a terminal and put output into the code block below

Output of: flutter doctor -v

### Affected platforms

All

### Are you interested in working on a PR for this?

- [X] I want to work on this

**Comment by spydon** [comment]
It runs smoothly in the examples for me, like one would expect it to move with the `MouseJoint`.
Since you've indicated that you want to work on this, what changes would you like to make?

**Comment by ksokolovskyi** [comment]
Hi @spydon, thanks for your quick response. 
I opened PR https://github.com/flame-engine/flame/pull/3204 addressing this issue.
