### ISSUE TITLE
multiple points collider

### ISSUE THREAD

**Issue by glennmichaelmejias** [flame-engine/flame#321]
how to make a collider with multiple points, not just box or circle, like a polygon with 3 or more sides. thanks.

**Comment by erickzanardo** [comment]
@glennmichaelmejias you seem to be having a lot of questions regarding box2d, please, consider joining our discord to ask such questions, as these questions would fit better there and would be easier for you to get help, as more people could answer.

**Comment by spydon** [comment]
When you create the fixture you can create it from a path.
Be aware that collision detection only works for convex objects, if you have non-convex objects you have to use multiple fixtures.

**Comment by glennmichaelmejias** [comment]
@erickzanardo where is the link for discord?

**Comment by glennmichaelmejias** [comment]
@spydon ok thanks. i will test it.

**Comment by spydon** [comment]
@glennmichaelmejias here is the discord https://discord.gg/pxrBmy4

**Comment by erickzanardo** [comment]
@glennmichaelmejias was your question solved?

**Comment by erickzanardo** [comment]
Closing due inactivity, let us know if you have more question, or hit us on discord
