### ISSUE TITLE
Is Possible to Loading Spine Files from URL in Flame?

### ISSUE THREAD

**Issue by chrislitw** [flame-engine/flame#3214]
### Problem to solve

Hello Flame Development Team,

I'm working on a project using Flutter and Flame, and I have a specific question regarding loading Spine files.
 
My current scenario:
I've developed a feature where users can drag and drop Spine files into a web page for preview, allowing them to check for any layout issues or other visual problems. I've successfully implemented the drag-and-drop functionality, which generates temporary URLs for the dropped files.

My question:
Is it possible to load both the atlas file and skeleton file from HTTP URLs in Flame? Currently, it seems that Flame only supports loading Spine files from the assets directory.

### Proposal

something method like this.

spine = await SpineComponent.fromUrl(
  atlasFile: 'http://xxx/test.atlas',
  skeletonFile: 'http:///test.json',
);

### Other

- [ ] Are you interested in working on a PR for this?

**Comment by spydon** [comment]
You can use our `AssetsCache` to load the file from a URL first and then you can feed it into the spine component.
