### ISSUE TITLE
Support package prefix for flame_texturepacker

### ISSUE THREAD

**Issue by hamberluo** [flame-engine/flame#3219]
### Problem to solve

Now flame_texturepacker don't support this feature.

### Proposal

Fix with passed image param.

### Other

- [ ] Are you interested in working on a PR for this?

**Comment by spydon** [comment]
Can you clarify with an example what you mean?

**Comment by spydon** [comment]
Since you can pass in an `Images` cache with a custom prefix I don't think that this is needed? But feel free to write a more thorough feature request if that is not covering your use-case.
