### ISSUE TITLE
"AI: Code Assist" badge for our Flame AI Agent

### ISSUE THREAD

**Issue by samyakkkk** [flame-engine/flame#3225]
### Problem to solve

We've the Flame agent accessible via the web app: https://app.commanddash.io/agent/flame_engine which new users that are not yet on the discord can use to get help.

### Proposal

We can link this as a badge in readme:

<a href="https://app.commanddash.io/agent/flame_engine"><img src="https://img.shields.io/badge/AI-Code%20Assist-EB9FDA"></a>
```md
<a href=“https://app.commanddash.io/agent/flame_engine”><img src="https://img.shields.io/badge/AI-Code%20Assist-EB9FDA”></a>
```

### Other

- [X] Are you interested in working on a PR for this?

**Comment by spydon** [comment]
Sounds good, do you want to provide a PR?
