### ISSUE TITLE
Yoyo Effects

### ISSUE THREAD

**Issue by cranst0n** [flame-engine/flame#324]
A nice addition to the Effects API would be the ability to mirror/yoyo the effect so it runs in reverse after completing it's initial cycle, and then potentially running infinitely.

This would make creating pulsing sprites pretty simple.

**Comment by spydon** [comment]
Very good suggestion!

**Comment by erickzanardo** [comment]
We probably could create a `SequencePositionEffect` which groups multiple effects, then the user could add two effects, the second been the inverted of the first, creating the desired yoyo effect, and that way, it would be generic enough to create sequences of effects.

**Comment by spydon** [comment]
@cranst0n this was just released in version 0.21.0
