### ISSUE TITLE
[FireAtlas] Scrolling is reversed from system scrolling

### ISSUE THREAD

**Issue by spydon** [flame-engine/flame#3274]
### What happened?

The scrolling is reversed from system scrolling

### What do you expect?

That the scrolling direction should be the same as the scrolling direction on the system.

### How can we reproduce this?

Scroll inside of an atlas.

### Execute in a terminal and put output into the code block below

Output of: flutter doctor -v

### Affected platforms

Linux

### Are you interested in working on a PR for this?

- [ ] I want to work on this

**Comment by ryzizub** [comment]
@spydon I created and PR for that :)
