### ISSUE TITLE
[FireAtlas] Border of selection could be thicker.

### ISSUE THREAD

**Issue by spydon** [flame-engine/flame#3275]
### What could be improved

The thickness of the selection tool could be thicker, right now it is very hard to see what is selected (see screenshot).
![image](https://github.com/user-attachments/assets/134c3845-69d2-4f78-8c34-c8e2562de699)

### Why should this be improved

So that the user can see what they have selected.

### Other

- [ ] Are you interested in working on a PR for this?

**Comment by ryzizub** [comment]
This one is annoying cause im blind haha. @spydon you can assign it me, im going to push a change tomorrow on this

**Comment by spydon** [comment]
Aaah, did you already fix this @erickzanardo? 😄

**Comment by erickzanardo** [comment]
I didn't changed anything 😅 

But for me, it shows a thick line hahah

**Comment by ryzizub** [comment]
@spydon do you have thick line? Maybe its environment thing (I doubt, but to make sure)

**Comment by spydon** [comment]
I can't reproduce it... It's the same thickness for me as for you now :man_shrugging: 
I'll close this issue then, until we can repro it.
