### ISSUE TITLE
Explain `onTapCancel` and `onDragCancel` in the docs

### ISSUE THREAD

**Issue by bryanoltman** [flame-engine/flame#3281]
### What happened?

Playing around with flame, making a Flappy Bird clone as my "hello world" project. I created a `FlameGame` subclass with the `TapDetector` mixin and noticed that if I pan after clicking/tapping, the `handleTapUp` is not invoked.

### What do you expect?

I would expect `handleTapUp` to be called regardless of whether I panned.

### How can we reproduce this?

```dart
class TapBehaviorGame extends FlameGame with TapDetector {
  @override
  void handleTapDown(TapDownDetails details) {
    print('handleTapDown');
    super.handleTapDown(details);
  }

  @override
  void handleTapUp(TapUpDetails details) {
    // This will not print if you pan after pressing down
    print('handleTapUp');
    super.handleTapUp(details);
  }
}
```

### What steps should take to fix this?

Uncertain

### Do have an example of where the bug occurs?

I believe this happens wherever a TapDetector is used. I've reproduced on macOS and Android.

### Execute in a terminal and put output into the code block below

```
⑆ flutter doctor -v
[✓] Flutter (Channel stable, 3.24.1, on macOS 14.6.1 23G93 darwin-arm64, locale en-US)
    • Flutter version 3.24.1 on channel stable at /Users/bryanoltman/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (4 days ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/bryanoltman/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.92.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (5 available)
    • Pixel 4 (mobile)                • 9B021FFAZ0033S            • android-arm64  • Android 13 (API 33)
    • Bryan Oltman’s iPhone (mobile)  • 00008110-000265A10E92801E • ios            • iOS 17.5.1 21F90
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.6.1 23G93 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.6.1 23G93 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 128.0.6613.84

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### Affected platforms

All

### Other information

I've verified this on macOS and Android.

It's possible to work around this by incorporating a `PanDetector` and treating a "pan end" event as a "tap up" event, but this is a bit awkward and nonobvious to introduce a second type of gesture handler when all I care about is whether the mouse/finger is down or up.

### Are you interested in working on a PR for this?

- [ ] I want to work on this

**Comment by spydon** [comment]
That is just how the event system in Flutter works (and in most other frameworks). `onTapCancel` will be called instead, so you can hook into that. :)

**Comment by bryanoltman** [comment]
Thanks! I was wondering if I just missed some docs. Maybe packages/flame/lib/src/gestures/detectors.dart should mention this or link out to docs?

**Comment by spydon** [comment]
@bryanoltman that's a good idea, I'll convert this to a docs issue!

**Comment by spydon** [comment]
If you're keen, feel free to provide a PR with an update to the docs (they live in the `doc` directory of this repo).

**Comment by spydon** [comment]
I see now that we already do explain this in the docs, so I'll close this one.
https://docs.flame-engine.org/latest/flame/inputs/tap_events.html#ontapcancel
