### ISSUE TITLE
Cannot use DevTools extension on example application

### ISSUE THREAD

**Issue by kenzieschmoll** [flame-engine/flame#3286]
### What happened?

I ran the example app from `flame/examples`: `flutter run -d chrome`. I opened DevTools from the link printed to the CLI and navigated to the `flame` tab to use the DevTools extension. Instead of the extension loading as expected, I saw this failure message:

![Screenshot 2024-08-27 at 10 25 27 AM](https://github.com/user-attachments/assets/f40234db-3aaf-44af-a91b-ee7c841d71f1)

This is because the example app uses `package:flame` from src due to the melos setup. The `flame` directory on disk does not have the `flame/extension/devtools/build` directory, because this is only included with the published package.

To resolve this issue for my local needs, I downloaded the latest `flame` package from pub.dev and copied the `extension/devtools/build` directory from there into my local `flame/extension/devtools` folder. After doing this and reloading DevTools, the flame extension loaded as expected.

### What do you expect?

I expected to be able to use the DevTools extension on the example app. 

### How can we reproduce this?

Run the example app, open DevTools, and navigate to the `flame` tab.

### What steps should take to fix this?

Is it possible to include the `extension/devtools/build` directory on GitHub? If not, perhaps the `examples/README.md` file could include documentation for an easy way to generate the extension build for local development.

### Execute in a terminal and put output into the code block below

Output of: flutter doctor -v

### Affected platforms

All

### Are you interested in working on a PR for this?

- [ ] I want to work on this

**Comment by spydon** [comment]
Did you run `melos bootstrap` before running it?

**Comment by kenzieschmoll** [comment]
Yes I ran `melos bootstrap` before running the example app. Is there an easy way to generate the devtools extension build? This would have been nice to be able to run before running the example app for the purpose of trying out the flame-provided tooling along with the example.

**Comment by spydon** [comment]
Ah right! I thought we built it as a hook on bootstrap, but apparently we only do on publish.
You can run `melos devtools-build` to build it.
