### ISSUE TITLE
Allow checking if camera sees the entire component

### ISSUE THREAD

**Issue by alestiago** [flame-engine/flame#3290]
### Problem to solve

Currently, one can use `camera.canSee` to check if a component is partially visible by the camera. I would love an API allowing the camera to check if it sees the entire element.

For example:

![camera](https://github.com/user-attachments/assets/5aafad97-c085-44d1-9eb0-4ea489ba29ee)

`canSee` would return `true`, since the implementation uses `overlaps`. 

### Proposal

Not quite sure what the API surface would be:

`camera.canSee(component, entirely: ture)`
`camera.canSeeEntire(component)`

### More information

Draft internals might be something along the lines:

```dart

final visible = game.camera.visibleWorldRect.has(parent.toAbsoluteRect());

extension on Rect {
  bool has(Rect rect) {
    return left <= rect.left &&
        top <= rect.top &&
        right >= rect.right &&
        bottom >= rect.bottom;
  }
}

```

### Other

- [X] Are you interested in working on a PR for this?

**Comment by spydon** [comment]
Hmm, what are the use-cases for this?
The `canSee` method is supposed to be used for render culling in the future.

**Comment by alestiago** [comment]
That's a valid question, my particular use-case is animating the back component into view if dragged outside what the camera is observing.

For example, consider this [demonstration](https://docs.flame-engine.org/latest/flame/inputs/drag_events.html#demo), you can drag flowers off-screen and be unable to drag them back into view. 

In mobile devices where the input type is not as precise as a mouse (but a finger), if the draggable component is only partially visible it might be also impossible to drag back. In my game I animate it back into view as soon as it is not entirely visible.

**Comment by spydon** [comment]
In this case I don't think that should be code living inside of the camera, but inside of your own components.

**Comment by spydon** [comment]
You could for example add a `ScreenHitbox` and raycast against it and use the `isInsideHitbox` to check if it is inside, or you could have the `ScreenHitbox` as a solid hitbox and count your other component as outside when it is not longer in contact with the `ScreenHitbox`.

**Comment by alestiago** [comment]
> In this case I don't think that should be code living inside of the camera, but inside of your own components.

I don't fully understand the logic here to conclude so, I am referring to the `CameraComponent`.

What I'm suggesting is adding something as follows:

```dart
extension on CameraComponent {
  canSee(PositionComponent component, {bool entire = false}) {
    final componentRect = component.toAbsoluteRect();
    if (entire) {
      return visibleWorldRect.has(componentRect);
    } else {
      return visibleWorldRect.overlaps(componentRect);
    }
  }
}

extension on Rect {
  bool has(Rect rect) {
    return left <= rect.left &&
        top <= rect.top &&
        right >= rect.right &&
        bottom >= rect.bottom;
  }
}

```

Following your logic `canSee` shouldn't exist at all?

**Comment by spydon** [comment]
It should, but that's because render culling is something that is traditionally handled by a camera, the method you're suggesting is not. We don't want code for all possible use-cases in a core component like the `CameraComponent`, and this use-case is simply too small, even if it would have been the correct place to have it.
