### ISSUE TITLE
Github-actions bot broken

### ISSUE THREAD

**Issue by MathiasDuus** [flame-engine/flame#3325]
### What happened?

The "github-actions[bot] chore(release): Publish all packages" failed the latest version 1.20. Resulting in the release not being on pub.dev

### What do you expect?

The chore release to work and the newest version being on pub.dev

### Execute in a terminal and put output into the code block below

Output of: flutter doctor -v

### Affected platforms

All

### Other information

The chore: https://github.com/flame-engine/flame/actions/runs/10966326702/job/30454016104

### Are you interested in working on a PR for this?

- [ ] I want to work on this

**Comment by spydon** [comment]
This is a known issue, since it's a work in progress.
I guess we should publish the latest version manually meanwhile though, I'll do that now.

**Comment by spydon** [comment]
Or actually I'll wait with that, since then we can use this publishing step as test to get the automated publishing up and running.
