### ISSUE TITLE
SpriteBatch Examples throw errors and show black screens

### ISSUE THREAD

**Issue by crcdng** [flame-engine/flame#3331]
### What happened?

On https://examples.flame-engine.org/ both "SpriteBatch" and "SpriteBatch Autoload" throw errors and show black screens.

### What do you expect?

Examples render

### How can we reproduce this?

Open "SpriteBatch" or "SpriteBatch Autoload" on https://examples.flame-engine.org/ 

### Relevant log output

```shell
"Invalid argument(s): If non-null, "colors" length must match that of "transforms" and "rects"."
```

### Execute in a terminal and put output into the code block below

Output of: flutter doctor -v

### Affected platforms

Web

### Are you interested in working on a PR for this?

- [ ] I want to work on this

**Comment by spydon** [comment]
Thanks for the report, something must have changed on the Flutter side.
