### ISSUE TITLE
gameRef 在1.20.0上不能用？

### ISSUE THREAD

**Issue by wengxianxun** [flame-engine/flame#3332]
### What happened?

如图，在1.18.0上没问题，但是1.20.0却报错了<img width="923" alt="image" src="https://github.com/user-attachments/assets/92676ea4-ba93-4d5a-97d5-4fd349d1333c">

### What do you expect?

怎么修复这个问题呢？

### Execute in a terminal and put output into the code block below

Output of: flutter doctor -v

### Affected platforms

All

### Are you interested in working on a PR for this?

- [X] I want to work on this

**Comment by spydon** [comment]
Hi, this is an English only bug tracker.
I can see what your problem is though, change `gameRef` to `game` and it should work.

**Comment by wengxianxun** [comment]
> Hi, this is an English only bug tracker. I can see what your problem is though, change `gameRef` to `game` and it should work.

yes ,working now,thks
