### ISSUE TITLE
raytrace outside of circle?

### ISSUE THREAD

**Issue by dailei2018** [flame-engine/flame#3333]
### What happened?

https://examples.flame-engine.org/      Raytracing page，why outside of circle.
![ray](https://github.com/user-attachments/assets/17f6910e-6fad-4278-b3c2-35805e545a7e)

### What do you expect?

...

### Execute in a terminal and put output into the code block below

Output of: flutter doctor -v

### Affected platforms

All

### Are you interested in working on a PR for this?

- [ ] I want to work on this

**Comment by spydon** [comment]
Interesting, I wonder why this has started to happen all of a sudden, we haven't made any changes to that code for a long while. Maybe some subtle changes with float numbers in Dart maybe... I'll have a closer look later.

**Comment by spydon** [comment]
This is fixed and released in Flame v1.21.0 :)
