### ISSUE TITLE
NineTileBoxWidget flickers inside of AnimatedOpacity container

### ISSUE THREAD

**Issue by wsv-accidis** [flame-engine/flame#3342]
### What happened?

When a `NineTileBoxWidget` is placed inside an `AnimatedOpacity` and the opacity changes, it will sometimes flicker. In my project, I was able to narrow it down to the use of `NineTileBoxWidget.asset` to create the widget. Loading the image earlier and then using the `NineTileBoxWidget` constructor that directly takes the `Image` instance works around the issue, even though I'm just using the `Flame.images.load` method in my code, which is what `NineTileBoxWidget` also does internally.

I've only tested this on web. Debug/release build makes no difference. With a child widget other than `NineTileBoxWidget`, the animation flicker does not occur.

### What do you expect?

I expect smooth animations with no flickering.

### How can we reproduce this?

See sample below.

### What steps should take to fix this?

I don't know Flame or Flutter well enough to suggest a fix, sorry.

### Do have an example of where the bug occurs?

This widget reproduces the issue when `visible` is changed from `true` to `false`. The widget itself is added as an overlay in the `GameWidget` and is always active.

This was the in-game menu; I've replaced the contents with a simple `Text` for brevity.

```
class MenuOverlay extends StatefulWidget {
  const MenuOverlay({super.key});

  @override
  State<StatefulWidget> createState() {
    return MenuOverlayState();
  }
}

class MenuOverlayState extends State<MenuOverlay> {
  var _visible = true;

  bool get visible {
    return _visible;
  }

  set visible(bool value) {
    if (value == _visible) return;
    setState(() {
      _visible = value;
    });
  }

  @override
  Widget build(BuildContext context) {
    return FractionallySizedBox(
        widthFactor: 1.0,
        child: AnimatedOpacity(
            opacity: _visible ? 1.0 : 0.0,
            duration: const Duration(milliseconds: 500),
            child: Container(
                color: Colors.black,
                margin: const EdgeInsets.symmetric(horizontal: 24, vertical: 32),
                child: NineTileBoxWidget.asset(
                    path: "ui/frame_64.png",
                    tileSize: 64,
                    destTileSize: 64,
                    padding: const EdgeInsets.symmetric(horizontal: 40, vertical: 32),
                    child: IgnorePointer(
                        ignoring: !_visible,
                        child: const Text(
                            style: TextStyle(color: Colors.white, decoration: TextDecoration.none), textAlign: TextAlign.center, "Hello, World"))))));
  }
}
```

![frame_64](https://github.com/user-attachments/assets/667222c0-c525-4c76-9968-58bd570d8573)

### flutter doctor -v

```
[√] Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version 10.0.22631.4317], locale sv-SE)
    • Flutter version 3.24.3 on channel stable at D:\Dev\Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (5 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at D:\Dev\Android\Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.7.34221.43
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2024.2)
    • Android Studio at C:\Program Files\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)

[√] VS Code, 64-bit edition (version 1.94.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.98.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.4317]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 129.0.6668.90
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 126.0.2592.87

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

### Affected platforms

Web

**Comment by spydon** [comment]
Thanks for a well-written issue!
If you wrap the `NineTileBoxWidget` in a `StatefulWidget` does it still flicker?
In your case it will recreate the widget on each animation step, and since it creates a `Future` when using the `asset` constructor (even when the image is already loaded in the cache) it might flicker. When using the normal constructor taking an `Image` it is `const`, so it doesn't recreate the widget, hence why it doesn't flicker in that case.

**Comment by erickzanardo** [comment]
Wrapping in stateful widget might work, but I feel that the widgets should handle that themselves!

I am taking a look on how to improve this.

**Comment by spydon** [comment]
Flame v1.21.0 is now released with this fix :)
