### ISSUE TITLE
API docs - links to Canvas, Color etc. in Flutter docs broken

### ISSUE THREAD

**Issue by crcdng** [flame-engine/flame#3355]
### What happened?

API docs links to the Flutter documentation which contain the subpath "painting" are broken

### What do you expect?

API docs links to the Flutter documentation work

### How can we reproduce this?

- go to https://pub.dev/documentation/flame/latest/game/FlameGame/render.html and click on link to "Canvas"

- go to https://pub.dev/documentation/flame/latest/effects/ColorEffect/color.html and click on link to "Color"

### What steps should take to fix this?

replace all links  to `https://api.flutter.dev/flutter/painting/...` with 
`https://api.flutter.dev/flutter/dart-ui/...`

### Do have an example of where the bug occurs?

see "How can we reproduce this?"

### Execute in a terminal and put output into the code block below

Output of: flutter doctor -v

### Affected platforms

All

### Are you interested in working on a PR for this?

- [ ] I want to work on this

**Comment by spydon** [comment]
Thanks for the report, do you want to provide a PR with a fix?

**Comment by crcdng** [comment]
Not sure how these links are generated, they are not in the source code.

**Comment by ufrshubham** [comment]
I don't think those links are generated by Flame. Closing this.
