### ISSUE TITLE
Found a few duplicate test cases, you might want to take a look

### ISSUE THREAD

**Issue by incendial** [flame-engine/flame#3356]
### What could be improved

1. [x] Duplicate test cases in `test/components/position_component_test.dart`: [this](https://github.com/flame-engine/flame/blob/main/packages/flame/test/components/position_component_test.dart#L290) and [that](https://github.com/flame-engine/flame/blob/main/packages/flame/test/components/position_component_test.dart#L301)
2. [x] Duplicate test cases in `test/components/priority_test.dart`: [this](https://github.com/flame-engine/flame/blob/main/packages/flame/test/components/priority_test.dart#L26) and [that](https://github.com/flame-engine/flame/blob/main/packages/flame/test/components/priority_test.dart#L43)
3. [x] Duplicate test cases in `test/components/scroll_text_box_component_test.dart`: [this](https://github.com/flame-engine/flame/blob/main/packages/flame/test/components/scroll_text_box_component_test.dart#L8) and [that one](https://github.com/flame-engine/flame/blob/main/packages/flame/test/components/text_box_component_test.dart#L125) in another file (test/components/text_box_component_test.dart)
4. [ ] Duplicate test cases in `test/effects/color_effect_test.dart`: [this](https://github.com/flame-engine/flame/blob/main/packages/flame/test/effects/color_effect_test.dart#L31) and [that](https://github.com/flame-engine/flame/blob/main/packages/flame/test/effects/color_effect_test.dart#L61)
5. [ ] Duplicate test cases in `test/experimental/has_game_reference_test.dart`: [this](https://github.com/flame-engine/flame/blob/main/packages/flame/test/experimental/has_game_reference_test.dart#L90) and [that one](https://github.com/flame-engine/flame/blob/main/packages/flame/test/components/mixins/has_game_ref_test.dart#L26) in another file (test/components/mixins/has_game_ref_test.dart)
6. [x] Duplicate test cases in `test/extensions/vector2_test.dart`: [this](https://github.com/flame-engine/flame/blob/main/packages/flame/test/extensions/vector2_test.dart#L278) and [that](https://github.com/flame-engine/flame/blob/main/packages/flame/test/extensions/vector2_test.dart#L293)
7. [ ] Duplicate test cases in `test/game/game_widget/game_widget_lifecycle_test.dart`: [this](https://github.com/flame-engine/flame/blob/main/packages/flame/test/game/game_widget/game_widget_lifecycle_test.dart#L162) and [that one](https://github.com/flame-engine/flame/blob/main/packages/flame/test/game/game_widget/game_widget_controlled_lifecycle_test.dart#L126) in another file (test/game/game_widget/game_widget_controlled_lifecycle_test.dart)
8. [x] Duplicate test cases in `test/game/game_widget/game_widget_test.dart`: [this](https://github.com/flame-engine/flame/blob/main/packages/flame/test/game/game_widget/game_widget_test.dart#L275) and [that](https://github.com/flame-engine/flame/blob/main/packages/flame/test/game/game_widget/game_widget_test.dart#L352), also [this](https://github.com/flame-engine/flame/blob/main/packages/flame/test/game/game_widget/game_widget_test.dart#L387) and [that](https://github.com/flame-engine/flame/blob/main/packages/flame/test/game/game_widget/game_widget_test.dart#L425)
9. [ ] Duplicate test cases in `test/particles/circle_particle_test.dart`: [this](https://github.com/flame-engine/flame/blob/main/packages/flame/test/particles/circle_particle_test.dart#L13) and [that one](https://github.com/flame-engine/flame/blob/main/packages/flame/test/particles/sprite_particle_test.dart#L16) and [also that one](https://github.com/flame-engine/flame/blob/main/packages/flame/test/components/particle_system_component_test.dart#L21)

### Why should this be improved

It's unclear if these test cases are accidental duplicates and can be simply removed (or kept as is) or they need to be update to test different things.

### Risks

Probably none.

### Other

- [ ] Are you interested in working on a PR for this?

**Comment by incendial** [comment]
cc @spydon

**Comment by spydon** [comment]
Thanks for the report, I'll have a closer look later today!
