### ISSUE TITLE
Effects improvements

### ISSUE THREAD

**Issue by spydon** [flame-engine/flame#336]
Things we could add to Effects:
- [x] Rotational effect
- [x] Sequenced effects (@erickzanardo's idea)
- [ ] Effect that can move along path, possibly just an extra parameter to MoveEffect
- [x] CombinedEffect, combine two effects into one, with potential offset in time to start
- [ ] ShakeEffect, an effect that inserts some noise to shake the component
- [ ] Elasticity
- [ ] Have an argument which decides between relative and absolute
- [x] onComplete callback
- [x] ~~Anchor for effects, right now the anchor is topLeft but it would be nice to be able to choose any anchor.~~

**Comment by erickzanardo** [comment]
I like the idea of both rotation and sequence effects.

But the Effect don't need to have an anchor, the component already has a property for that, and the effects are working fin with it.

**Comment by spydon** [comment]
Good point!

**Comment by spydon** [comment]
@erickzanardo what do you think about a CombinedEffect that combines two (or multiple maybe) effects with an optional offset in time between them?

**Comment by erickzanardo** [comment]
> @erickzanardo what do you think about a CombinedEffect that combines two (or multiple maybe) effects with an optional offset in time between them?

This seems like a good idea, but I don't know how easy would it be to implement this, imagine a MoveEffect together a ScaleEffect, wouldn't the scaling mess with the repositioning? 

Anyway, I think it is nice, I just worry that this would be a complex take.

**Comment by spydon** [comment]
It would depend on the anchor I think, on a centered anchor it shouldn't look too weird.
Not sure how bad it would be on other anchors, I'll do some testing.

**Comment by erickzanardo** [comment]
> It would depend on the anchor I think, on a centered anchor it shouldn't look too weird.
> Not sure how bad it would be on other anchors, I'll do some testing.

Actually, since we rely only on the curve progress, maybe we will not have any trouble... Anyhow, it would be nice to do some testing, let me know how it turned out.

**Comment by spydon** [comment]
It worked fine. :)
I think it would also make sense to have an optional anchor on the effects which can override the component anchor.

**Comment by spydon** [comment]
CombinedEffect is almost done so I think that one will be aimed for 0.23.0 along with a fix for a drifting bug that I found.

For 1.0.0 I will propose a general update to the effects where you can choose if you want them to be relative or absolute.

Potentially I will also fix so that when `isInfinite: true` and `isAlternating: false` the effect will start from the beginning instead of from where it currently is at, right now a MoveEffect with isInfinite would not move any more after it is done with its first iteration since it is already at its destination.

**Comment by erickzanardo** [comment]
@spydon Can you help me update the checklist on this after the release of the `0.22.1`?

Also, maybe we should have separate issues for which improve? Otherwise this issue will live forever

**Comment by spydon** [comment]
Updated the checklist!

**Comment by compositephp** [comment]
It would be great to be able to add onComplete callback to effects.
Maybe it’s not difficult to implement and you can add it to flame?

**Comment by spydon** [comment]
Very good idea, and should be easy to implement. I'll have a look at it tomorrow.

**Comment by spydon** [comment]
@compositephp this is implemented in #393 and will be released in the next version of flame. :)

**Comment by compositephp** [comment]
> @compositephp this is implemented in #393 and will be released in the next version of flame. :)

Many thanks! This callback is very useful.

**Comment by spydon** [comment]
Split up issue into smaller issues.
