### ISSUE TITLE
Strange phenomenon after using withFixedResolution

### ISSUE THREAD

**Issue by DavidChZh** [flame-engine/flame#3366]
### What happened?

I developed a composite game and everything worked fine until I didn't set the withFixedResolution property.
Because I couldn't set a suitable size on pads and phones, I wanted to use withFixedResolution, but after adding it, the game didn't work properly.
But I didn't reproduce this problem with sprite_body_example. I'm trying to solve it. Has anyone encountered this situation? Thank you very much

https://github.com/flame-engine/flame/blob/v1.17.0/examples/lib/stories/bridge_libraries/flame_forge2d/sprite_body_example.dart

https://github.com/user-attachments/assets/07a4400f-3975-4df3-9801-b7bcfc2943e4

### What do you expect?

I hope it can fall, collide, and combine normally, instead of flying around like there is no gravity.

### Execute in a terminal and put output into the code block below

```
[✓] Flutter (Channel stable, 3.24.1, on macOS 14.6.1 23G93 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.24.1 on channel stable at /Users/evdo/fvm/versions/3.24.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (3 months ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/evdo/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.95.2)
    • VS Code at /Users/evdo/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set
```

### Affected platforms

Android, iOS

### Are you interested in working on a PR for this?

- [ ] I want to work on this

**Comment by spydon** [comment]
Can you post a reproduction of this error? Since you say that it isn't reproducible in the example.
My best guess is that the body components aren't added to the world properly, but to some other parent.

**Comment by DavidChZh** [comment]
> Can you post a reproduction of this error? Since you say that it isn't reproducible in the example. My best guess is that the body components aren't added to the world properly, but to some other parent.

Thank you, we ultimately did not use withFixedResolution as it resulted in black borders on some phones.
