### ISSUE TITLE
Docs show incorrect example for ColorEffect

### ISSUE THREAD

**Issue by bradcypert** [flame-engine/flame#3383]
### What happened?

The docs for ColorEffect (https://docs.flame-engine.org/latest/flame/effects.html#coloreffect) show the following:

```dart
final effect = ColorEffect(
  const Color(0xFF00FF00),
  EffectController(duration: 1.5),
  opacityFrom = 0.2,
  opacityTo: 0.8,
);
```

but it should be

```dart
final effect = ColorEffect(
  const Color(0xFF00FF00),
  EffectController(duration: 1.5),
  opacityFrom: 0.2,
  opacityTo: 0.8,
);
```

### What do you expect?

I'd expect the documentation example to work after copy/paste.

### How can we reproduce this?

Open https://docs.flame-engine.org/latest/flame/effects.html#coloreffect, copy the color effect code and paste it into a project, then import necessary classes.

### What steps should take to fix this?

Fix documentation: https://github.com/flame-engine/flame/pull/3382

### Execute in a terminal and put output into the code block below

N/A

### Affected platforms

All

### Are you interested in working on a PR for this?

- [X] I want to work on this

**Comment by spydon** [comment]
I'll assign you to the issue since you've marked that you want to put up a PR with a fix @bradcypert :)

**Comment by spydon** [comment]
Oh, the PR is already up, great!

**Comment by bradcypert** [comment]
It was such a straightforward fix that I went ahead and made to PR alongside the issue :)

**Comment by spydon** [comment]
Thanks! To save you time, in the future you don't need to create issues for non PRs that don't need to be discussed.

**Comment by bradcypert** [comment]
Got it! I was just following the contributing guidelines :D
