### ISSUE TITLE
ClipComponent example weird?

### ISSUE THREAD

**Issue by large** [flame-engine/flame#3386]
### What happened?

See ClipComponent example, press on any shape to make them start clipping
https://examples.flame-engine.org/

From:
![image](https://github.com/user-attachments/assets/c0742f1e-2dea-417e-8daf-28d19b106e98)

To:
![image](https://github.com/user-attachments/assets/4e22dfcb-4cf4-457a-b793-53048756c8f0)

It flickers any does not make the clip "sharp" as you expect.

### What do you expect?

Clean clipped edge

### How can we reproduce this?

Se description in "What happened"

### What steps should take to fix this?

I think the clipcomponent does not work as expected. If you want to clip a circle and get a half-circle in some cases.

### Execute in a terminal and put output into the code block below

Output of: flutter doctor -v

### Affected platforms

macOS

### Are you interested in working on a PR for this?

- [ ] I want to work on this

**Comment by spydon** [comment]
Which version of Flutter are you on?

**Comment by spydon** [comment]
I think the example is intentionally looking like it does, I was also confused about it when I first saw it.
Can you confirm @erickzanardo, because I think you made that example?

**Comment by large** [comment]
Flutter version, but I am just testing the web version for reporting:
```
Flutter 3.24.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision dec2ee5c1f (4 weeks ago) • 2024-11-13 11:13:06 -0800
Engine • revision a18df97ca5
Tools • Dart 3.5.4 • DevTools 2.37.3
```

I could expect a ClipComponent to "cut sharp" ala ClipRect: https://akshaymkkr.medium.com/ultimate-guide-to-flutter-clipping-widgets-41272d298dee

If you for instance add a CircleComponent and add a TextComponent to it, if the text are to big a ClipComponent could help hide overlays. But when the result was not as expected ...

**Comment by spydon** [comment]
It is clipping sharp, but as you can see in the code the clip is rotating:
https://github.com/flame-engine/flame/blob/main/examples/lib/stories/components/clip_component_example.dart#L23-L25
If you remove the `RotateEffect` you'll see a static clip.

**Comment by large** [comment]
![image](https://github.com/user-attachments/assets/b39e6437-7391-409e-ad7b-1e4358d2a1b1)
![image](https://github.com/user-attachments/assets/ba2cb6fd-15b2-4a5d-b6ae-b793b87ad1f5)

I might misunderstood something about clipping in Flame.
But if I take two screenshots of the demo (have not compiled the example and removed the effect yet).
Here you clearly see that the cut "moves" based on the effect. Should not a clipping be a static thing? :)

**Comment by spydon** [comment]
The clipping is static, analyze the code and you'll see how it works, it's not a long example. :)
The rectangles that are children of the clipcomponents are rotating, they are what is colored, and different parts of them gets clipped during rotation.

I agree that we should have an example that is easier to understand directly from visual inspection though, especially since the description of the example is very vague.

**Comment by erickzanardo** [comment]
From what I remember, what we are seeing in the example is correct. But I am happy if we delete this one and create an easier to understand if it is confusing!
