### ISSUE TITLE
Box2D WeldJoint throwing failed assertion exception

### ISSUE THREAD

**Issue by yahel-ck** [flame-engine/flame#340]
An assertion exception is thrown whenever I add a WeldJoint to the Box2D world, no matter the configuration.

`'package:box2d_flame/src/math_utils.dart': Failed assertion: line 86 pos 10: 'out != v': is not true.`

The exception is thrown in some matrix/vector multiplication function. `out` and `v` are two parameters of type Vector2 or Vector3.
I've traced the back stack and it seems like the two vectors are retrieved by calling `popVec2` or `popVec3` on the Box2D world pool and for some reason it returns the same vector in both calls (maybe it's returning null, I haven't checked).

I tried reconfiguring the WeldJointDef with different values and the same assertion exception was thrown.

**Comment by spydon** [comment]
I have never tried the WeldJoint I'm afraid, could you add a minimal example to reproduce the exception?

**Comment by yahel-ck** [comment]
```
final bd = BodyDef()..type = BodyType.DYNAMIC;
final cs1 = CircleShape()..radius = 0.1;
final cs2 = CircleShape()..radius = 0.1;
final b1 = world.createBody(bd)..createFixtureFromShape(cs1, 1);
final b2 = world.createBody(bd)..createFixtureFromShape(cs2, 1);

final wjd = WeldJointDef()
  ..initialize(b1, b2, b1.worldCenter)
  ..collideConnected = false
  ..dampingRatio = 0.5
  ..frequencyHz = 0.5;

world.createJoint(wjd);
```

**Comment by erickzanardo** [comment]
@spydon any insights on this?

**Comment by spydon** [comment]
I started looking into it, but I don't really get what is happening, @yahel-ck might be onto something about both being null. I will look more into it on Sunday.

**Comment by erickzanardo** [comment]
@spydon any news on this?

**Comment by spydon** [comment]
Haven't had any time to look into it, will do it once the massive box2d refactor is merged

**Comment by spydon** [comment]
I just tried this, it works after the refactor.
So if you'll follow https://github.com/flame-engine/forge2d/pull/1 @yahel-ck you can start using that version, either now or when it is merged and published.
