### ISSUE TITLE
Would you recommend this for card games? 

### ISSUE THREAD

**Issue by Doetheman** [flame-engine/flame#347]
Working on a spade game. Would this be possible?

**Comment by erickzanardo** [comment]
Only if the game has a lot of interaction and effects.

A card game (Poker or Solitarie for example) are turn based and effects, animations and stuff only happens under user input. For those cases Flutter itself should cover what you need.

You usually only need a game engine, when there is so much happening on the screen, and when most of the action is not triggered by a player input.

If you have further questions, or more specific ones, please consider joining our Discord as it is easy to ask/answer questions there, you can find the invite on the README.
