### ISSUE TITLE
How to play mp4 video

### ISSUE THREAD

**Issue by daizongheng** [flame-engine/flame#359]
I want to play an mp4 video when I open the software, and also play an mp4 video during the game. How can I achieve this?

**Comment by spydon** [comment]
You can use a the normal flutter functionality for playing videos:
https://flutter.dev/docs/cookbook/plugins/play-video
You can put the video widget as an overlay widget or in a stack on top of the game.

**Comment by daizongheng** [comment]
> You can use a the normal flutter functionality for playing videos:
> https://flutter.dev/docs/cookbook/plugins/play-video
> You can put the video widget as an overlay widget or in a stack on top of the game.

thank you very much!
