### ISSUE TITLE
onForcePress not working.

### ISSUE THREAD

**Issue by glennmichaelmejias** [flame-engine/flame#363]
I want to have that when i press the screen its continuous updating and only end the updates when the finger is release.

**Comment by erickzanardo** [comment]
Please, make a good description on your issue, otherwise we can't help.

What is not working? Is there stacktrace? Etc..

**Comment by glennmichaelmejias** [comment]
no, PanUpdate is working but the ForcePress is not. or I just messed something on how to implement it?

**Comment by glennmichaelmejias** [comment]
or do you have suggestions on how I can implement a continuous tap on the screen and only stops when I release my finger.

**Comment by erickzanardo** [comment]
you probably only need TapDetector, using onTapDown is fired when the touch starts and on onTapUp when the touch has ended.

**Comment by glennmichaelmejias** [comment]
okay. so I have to declare a variable to detect if its on tap down and set it to false when on tap up?

**Comment by erickzanardo** [comment]
You can find how to that on the documentation, please take a look on it: https://github.com/flame-engine/flame/blob/master/doc/input.md#example

**Comment by glennmichaelmejias** [comment]
Thanks. I will close this now.
