### ISSUE TITLE
How to implement Listener class.

### ISSUE THREAD

**Issue by glennmichaelmejias** [flame-engine/flame#364]
GestureDetector is slow in flutter, but the Listener is so fast, how to use it instead of using GestureDetector or the flames detectors?

**Comment by erickzanardo** [comment]
We have never found any issues using `GestureDetector`, but if you don't want to use it, you can give it a try on the Multitouch detectors from Flame (you can find how on the docs).

And if you really want to use the Listener class, remember that a Flame game is a widget. So you can just wrap your game on that widget.

Please, prefer to ask those types of things on Discord, questions are more suitable there.
