### ISSUE TITLE
Vector2 - Unify to one tuple format

### ISSUE THREAD

**Issue by spydon** [flame-engine/flame#373]
Since we are starting to plan for 1.0.0.

Let's consolidate Size, Position, Offset (Any more?) into one type, suggestion Vector2.

Reasoning: It will be less confusing than today where for example Size is a Position in flame and Size in Flutter and we (and our users) will also easily be able to do operations between them.

Maybe we could also convert box2d to use this new type instead of its own Vector2?

**Comment by erickzanardo** [comment]
I am all for this, but I would suggest Vector2d. And to rename the Position class, to not loose all the work that is already done there.

**Comment by spydon** [comment]
Are there that much that we gain from using Position than from using something more standardized like https://api.flutter.dev/flutter/vector_math/Vector2-class.html ?
I can only think of adding angles expressed as doubles.

**Comment by luanpotter** [comment]
I think the main motivation of having a (own) Position class was to be able to easily add methods as needed. The classes from the stdlib like Offset and Size are extremely limited on what they provide for vector operations. Maybe this lib has more stuff (and by the name it should), but then we get back to not being able to add more stuff as we needed. I agree we can rename Position to Vector or Vector2, and we continue to provide `to` and `from` methods from all distinct classes used for this function: offset, size, Point, Vector2d (from box2d), etc

**Comment by spydon** [comment]
Then we still have to convert things when they interact with box2d though. We could have an extension of Vector2 if we just want extra methods on top of it, and it would still be able to do the efficient vector operations implemented by Vector2.

**Comment by spydon** [comment]
> Then we still have to convert things when they interact with box2d though. We could have an extension of Vector2 if we just want extra methods on top of it, and it would still be able to do the efficient vector operations implemented by Vector2.

Scrap that, the Vector2 class is close to useless when it is extended because everything depends on factories that creates a Vector2.

**Comment by spydon** [comment]
Maybe we should keep Offset as it is? Since that one is used as an immutable data structure meanwhile Vector2d will be used as a mutable one.

**Comment by camillo777** [comment]
Just a newbie here, but I would like to suggest to use Google "vector_math" library for Flutter, it is very optimized.

**Comment by spydon** [comment]
> Just a newbie here, but I would like to suggest to use Google "vector_math" library for Flutter, it is very optimized.

That was my thought at first since we use that in box2d, but it is not extendable in a nice way since it is using factories. (It also has a pretty ugly interface in general).

Also luans comment:
https://github.com/flame-engine/flame/issues/373#issuecomment-640247244

**Comment by erickzanardo** [comment]
Solved for the v1. On #459
