### ISSUE TITLE
Is applyTorque working in box2d?

### ISSUE THREAD

**Issue by cedarbob** [flame-engine/flame#374]
I'm trying to port some java steering behaviors to dart and can't get body.applyTorque to work.  I'm having no problems with body.applyAngularImpulse, but the code I'm porting uses applyTorque.  I added a trivial SpinnerTest class to the box2d_flame example (also added a reference to it in index.html and set gravity to 0 in demo.dart just for the purposes of this test) to verify the issue.  SpinnerTest just applies a fixed torque with applyTorque every update - but the body doesn't rotate.  Presumably I'm just missing something.  Attached is a zip of my modified example directory.
[example.zip](https://github.com/flame-engine/flame/files/4737185/example.zip)

**Comment by spydon** [comment]
Hello @cedarbob, 
your body type is dynamic, applyTorque only works on non-dynamic bodies.

**Comment by cedarbob** [comment]
That's odd.  I'm just trying to port some of the GdxAI steering behaviors to dart.  And in the process I'm porting many of their Box2d tests.  And they use dynamic bodies for their steering behaviors and applyTorque to generate angular velocities.  For example, this excerpt is from Box2dSteeringTest.java:
\\\
	public Box2dSteeringEntity createSteeringEntity (World world, TextureRegion region, boolean independentFacing, int posX, int posY) {

		CircleShape circleChape = new CircleShape();
		circleChape.setPosition(new Vector2());
		int radiusInPixels = (int)((region.getRegionWidth() + region.getRegionHeight()) / 4f);
		circleChape.setRadius(Box2dSteeringTest.pixelsToMeters(radiusInPixels));

		BodyDef characterBodyDef = new BodyDef();
		characterBodyDef.position.set(Box2dSteeringTest.pixelsToMeters(posX), Box2dSteeringTest.pixelsToMeters(posY));
		characterBodyDef.type = BodyType.DynamicBody;
		Body characterBody = world.createBody(characterBodyDef);

		FixtureDef charFixtureDef = new FixtureDef();
		charFixtureDef.density = 1;
		charFixtureDef.shape = circleChape;
		charFixtureDef.filter.groupIndex = 0;
		characterBody.createFixture(charFixtureDef);

		circleChape.dispose();

		return new Box2dSteeringEntity(region, characterBody, independentFacing, Box2dSteeringTest.pixelsToMeters(radiusInPixels));
	}
\\\
And in Box2dSteeringEntity.java, in the applySteering method:
\\\
		// Update orientation and angular velocity
		if (isIndependentFacing()) {
			if (steeringOutput.angular != 0) {
				// this method internally scales the torque by deltaTime
				body.applyTorque(steeringOutput.angular, true);
				anyAccelerations = true;
			}
		} else {
			// If we haven't got any velocity, then we can do nothing.
			Vector2 linVel = getLinearVelocity();
			if (!linVel.isZero(getZeroLinearSpeedThreshold())) {
				float newOrientation = vectorToAngle(linVel);
				body.setAngularVelocity((newOrientation - getAngularVelocity()) * deltaTime); // this is superfluous if independentFacing is always true
				body.setTransform(body.getPosition(), newOrientation);
			}
		}
\\\

Of course the referenced code is several years old.

**Comment by spydon** [comment]
The box2d implementations probably differ a bit, the dart port is from jbox2d and you can see here that it has the same behaviour:
https://github.com/jbox2d/jbox2d/blob/d958f4fadb5f756d5f48b809866dc42b7a446b2e/jbox2d-library/src/main/java/org/jbox2d/dynamics/Body.java#L525

**Comment by cedarbob** [comment]
I don't pretend to understand the box2d code very well.  But I did take the trouble to build and run some of the jbox2d testbed tests to investigate the issue.  In particular, I ran the Apply Force test and without giving the spaceship body any linear force or velocity I was able to rotate it clockwise and counterclockwise using the "a" and "d" keys - which just apply a torque of +/- 20.  Here is a link to it:
https://github.com/jbox2d/jbox2d/blob/master/jbox2d-testbed/src/main/java/org/jbox2d/testbed/tests/ApplyForce.java

**Comment by spydon** [comment]
Aah, I read the code completely wrong.
It clearly says that it should only run if it is a dynamic body, which makes sense.
Then it is weird that it doesn't work in our version.
Reopening the issue.

**Comment by spydon** [comment]
I found the issue, I'll submit a PR for it.

**Comment by luanpotter** [comment]
Fixed by #377
