### ISSUE TITLE
upgrade to latest version of tiled

### ISSUE THREAD

**Issue by billy1380** [flame-engine/flame#380]
Using a more up to date version of *tiled* in the project causes this issue.

Because flame 0.21.0 depends on tiled ^0.2.1 and no versions of flame match >0.21.0 <0.22.0, flame ^0.21.0 requires tiled ^0.2.1.
So, because ... depends on both flame ^0.21.0 and tiled ^0.4.0, version solving failed.
pub get failed

**Comment by erickzanardo** [comment]
Already been handled on #379

**Comment by billy1380** [comment]
Ah... I did a search on the issues not the pull requests... so sorry!

**Comment by erickzanardo** [comment]
Don't worry 😉
