### ISSUE TITLE
Add SpriteSheet.fromImage() to SpriteSheet

### ISSUE THREAD

**Issue by OsaXma** [flame-engine/flame#381]
Greetings,

Thank you all for the amazing package. 

**Suggestion**:
- Add `SpriteSheet.fromImage `constructor to `SpriteSheet` class

**Reasoning**: 
Unlike `Sprite`,  which has a constructor named `Sprite.fromImage`, `SpriteSheet` doesn't have a named constructor to load a spritesheet from an existing image (i.e. not from assets). For instance, in the case of having some sort of a character generator, the spritesheet will not be readily available in the assets folder but will be coming in from memory or network later on to be presented inside an AnimatedWidget as an example. 

**Suggested Solution:**
Adding the following named constructor to the `SpriteSheet` in `spritessheet.dart`:

```dart
  SpriteSheet.fromImage(
      Image image, {
      this.textureWidth,
      this.textureHeight,
      this.columns,
      this.rows}) {
    _sprites = List.generate(
        rows,
        (y) => List.generate(
            columns,
            (x) => Sprite.fromImage(image,
                x: (x * textureWidth).toDouble(),
                y: (y * textureHeight).toDouble(),
                width: textureWidth.toDouble(),
                height: textureHeight.toDouble())));
  }
```
Thank you,

**Comment by erickzanardo** [comment]
Solved on 0.22.1
