### ISSUE TITLE
Camera rotation and scale

### ISSUE THREAD

**Issue by aloisdeniel** [flame-engine/flame#384]
I'm trying to scale all the rendering of my game and I wonder if it is possible to change it globally (just like Camera's position).

It may be more natural to change the `Camera` object to add rotation and scale.

```dart
this.camera.position = Vector2(50,50);
this.camera.scale = 4.0;
this.camera.rotation = math.pi * 0.25;
```

**Comment by aloisdeniel** [comment]
My mistake, it is already the case with the `Position` object.

**Comment by erickzanardo** [comment]
@aloisdeniel consider joining our discord for questions, it is an easier and faster way to ask them 😉 

You can find the invite on the README
