### ISSUE TITLE
Remove component method / or a better way to destroy them.

### ISSUE THREAD

**Issue by alanlanglois** [flame-engine/flame#387]
Removing component from screen should be easier and as easier as adding.

We should be able to set the destroy method or pass an argument true from the wrapper
`this.text.destroy(true);`
Or have this kind of API : `this.add(text); ` & `this.remove(text);`

Have a look on [Starling](https://manual.starling-framework.org/en/#_display_programming), the whole display list concept, is pretty easy and could fit here. 

Let me know if you need help on this, I'd be happy to help.

**Comment by erickzanardo** [comment]
Alright I submitted a PR to add the remove method.

I still want to change the Components to change the method `destroy` to be a `bool destroyed` property. But that will be something to the `v1` since it is a major breaking change.

**Comment by erickzanardo** [comment]
This is already fixed on the develop branch and should be on the next release.
