### ISSUE TITLE
Effect that move along path

### ISSUE THREAD

**Issue by spydon** [flame-engine/flame#395]
Create an effect that moves along a path, possibly just an extra parameter to MoveEffect.

**Comment by luanpotter** [comment]
can't this be easily done just by conjoining multiple move effects one after the other with different destinations? a path is a list of points:

```
CombinedEffect(points.map((p) => MoveEffect(dest: p)))
```

something like that

**Comment by spydon** [comment]
There will be a lot of overhead if the path is long though, I think it would be more user friendly to create a separate class for it?

**Comment by spydon** [comment]
Added to v1.0.0 in the MoveEffect.
