### ISSUE TITLE
Provide access to artboard within FlameComponent

### ISSUE THREAD

**Issue by DanTup** [flame-engine/flame#401]
It seems like there's currently no way to access the FlareAnimation or FlutterActorArtboard from a FlareComponent. This means it's not possible to manipulate things other than the animation (for example to [change colours](https://github.com/2d-inc/Flare-Flutter/tree/master/example/change_color)).

Is this something that could be supported? (I can send a PR that just adds some getters if that would be acceptable, but I'm not sure if it'd be better done another way?).

**Comment by erickzanardo** [comment]
We are reworking all the API of our support of Flare for v1(you can see more on this WIP: https://github.com/flame-engine/flame/pull/328)

@renancaraujo can provide more context, Renan, please help us on this issue.

**Comment by DanTup** [comment]
Ah, cool - I'll keep my eye on that PR and see if it does what I need when it's a bit closer.

As an aside - it felt a bit weird for the relative paths passed to FlameComponent to require "assets/" in them. This seemed different to the other classes (eg. sprite, which is relative to "assets/images/").

**Comment by erickzanardo** [comment]
This support is ready on the `flame_flare` package. Closing this.
