### ISSUE TITLE
Remove deprecated methods

### ISSUE THREAD

**Issue by ironbatshashank** [flame-engine/flame#404]
Some methods are deprecated from the util package and should be removed from documentation to avoid confusion.
For example, addGestureRecognizer() has been removed from flame.util  and some more methods should be looked into

**Comment by erickzanardo** [comment]
That is already planned to happen for the v1 version, you can check it here https://github.com/flame-engine/flame/projects/1#card-40463501

**Comment by erickzanardo** [comment]
I am gonna keep this open so we can track this on this the issues as well

**Comment by erickzanardo** [comment]
Fixed on #486
