### ISSUE TITLE
image from newtork

### ISSUE THREAD

**Issue by cyberlahy** [flame-engine/flame#410]
Hi,
Any plan to load image from network with sprite?

thanks

**Comment by erickzanardo** [comment]
Sprites on Flame are loaded based on a `dart:ui` Image class, so it is pretty easy to obtain an image from the network, without the need of Flame.

You just need to use a http package like the `http` or even `Dio` package, than you can use the `decodeImageFromList` from the `dart:ui`, and then just pass it to your Sprites. So I don't really think there is much thing need on the Flame side for this. Or do you have any suggestion?

**Comment by erickzanardo** [comment]
closing due inactivity
