### ISSUE TITLE
Implement an optional parameter to do not block gestures after calling addWidgetsOverlay method

### ISSUE THREAD

**Issue by d-apps** [flame-engine/flame#413]
My request is to implement for example a bool value as parameter to block or don't block gestures in game when calling addWidgetsOverlay, this could make very easier to add simple buttons to the screen without need to add a new Component just to add a simple button to the screen for example.

addWidgetsOverlay("Pause Button, PauseButtonWidget(), **blockGestures: false**");

**Comment by erickzanardo** [comment]
I am not sure I understand the need of this. The method is meant to add an overlay on your game, so it will sure block the gestures. I don't even think this is something possible to do.

Also, the widget is supposed to block only the space it occupy.

**Comment by d-apps** [comment]
I'll try to explain the issue more detailed.

My game uses **PanDetector** to drag the player through the screen, 

```
class MyGame extends BaseGame with HasWidgetsOverlay, PanDetector {

        @override
  void onPanUpdate(DragUpdateDetails details) {

    // move the player
   player.move(details.delta.dx, details.delta.dy);

    super.onPanUpdate(details);
  }

}
```

I need to add a pause button in game on the top-right of the screen, to the user pauses the game when he needs.

![image](https://user-images.githubusercontent.com/20110433/86812767-c2224380-c055-11ea-991e-784db4019f48.png)

I realized that was two ways to do it:

**First (the easier, faster):** Add a widget overlay, the implementation will be easier since we can create a custom widget and just add it and handle the onTap to pause the game, plus I use Icons.pause from flutter, making even more easy, no need to import images to pubspec and to the project etc..


```
import 'package:flutter/material.dart';

class PauseButton extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: Alignment.topRight,
      child: Container(
        width: 50,
        height: 50,
        child: Material(
          color: Colors.blue,
          child: IconButton(
            icon: Icon(Icons.pause),
            onPressed: (){},
          ),
        ),
      ),
    );
  }
}
```

```
MyGame(){

addWidgetOverlay("Pause Button", PauseButton());

}
```

But even if I use Align or Positioned, calling addWidgetsOverlay it's blocking the gestures, even if my Container has it's own size and is not getting all the screen, it's 50 on the height and on the width.

**Second:**

I created a Pause Button Component, more code to do something that could be done with less code wih Widgets.

```
class PauseComponent extends PositionComponent with Tapable{

  Rect rect;
  Sprite spritePause = Sprite("pause_button.png"); // Had to import external image

  PauseComponent(){

    rect = Rect.fromLTWH(
        Get.find<Config>().screenSize.width * 0.92,
        Get.find<Config>().screenSize.height * 0.04,
        Get.find<Config>().screenSize.width * 0.05,
        Get.find<Config>().screenSize.height * 0.10);

  }

  @override
  void render(Canvas c) {

    spritePause.renderRect(c, rect);

  }

  @override
  void onTapDown(TapDownDetails details) {


  // This doesn't work, it seems PanDetector is overriding all screen, preventing Tapable to work.

    super.onTapDown(details);
  }
}
```

**Comment by erickzanardo** [comment]
>   // This doesn't work, it seems PanDetector is overriding all screen, preventing Tapable to work.

It seems you are not using the `HasTapableComponents` on you game class.

Please check the docs: https://flame-engine.org/docs/input.md#tapable-components

**Comment by d-apps** [comment]
> > // This doesn't work, it seems PanDetector is overriding all screen, preventing Tapable to work.
> 
> It seems you are not using the `HasTapableComponents` on you game class.
> 
> Please check the docs: https://flame-engine.org/docs/input.md#tapable-components

I just forgot to add here, because I wrote the code from scratch, didn't copy from the project, added now.

**Comment by d-apps** [comment]
I am not sure what really solved the problem, but I solved removing the Container from the Pause Button widget.

```
import 'package:flutter/material.dart';

class PauseButton extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: Alignment.topRight,
      child: Material(
        color: Colors.blue,
        child: IconButton(
          icon: Icon(Icons.pause),
          onPressed: (){
            print("TOUCH!");
          },
        ),
      ),
    );
  }
}
```

And removing HasTapableComponents mixin (not sure if it was conflicting with anything), now it's working.

```
class MyGame extends BaseGame with HasWidgetsOverlay, PanDetector {

}
```
