### ISSUE TITLE
AnimationComponents not rendering at the correct position on web

### ISSUE THREAD

**Issue by filleduchaos** [flame-engine/flame#414]
Basically, I'm trying to add web support to https://github.com/filleduchaos/grey_silence and I've hit a snag where AnimationComponents are being rendered out of place. For example compare this screenshot from Chrome (debug mode turned on for illustrative purposes):

<img width="641" alt="Screenshot 2020-07-08 at 3 51 13 PM" src="https://user-images.githubusercontent.com/29291843/86934543-bb69fe00-c133-11ea-8519-51ab398560e4.png">

with this screenshot from the iOS Simulator (and I can confirm that this is the way it renders on an actual iPhone and on an Android device as well):

<img width="832" alt="Screenshot 2020-07-08 at 3 51 02 PM" src="https://user-images.githubusercontent.com/29291843/86934628-d3418200-c133-11ea-8929-2b322fff848f.png">

The Player sprite in Chrome is clearly rendered outside of its intended bounding box. This affects all the other AnimationComponents I'm using as well.

I'm on the Flutter beta channel and flame 0.22.1. The bug happens in both debug and release mode on Chrome 83 if that matters.

**Comment by erickzanardo** [comment]
@filleduchaos can you confirm if you are using skia to render the game? There can be weird effects when not using skia on web.

**Comment by filleduchaos** [comment]
@erickzanardo no, not using skia. Will try again with that

**Comment by filleduchaos** [comment]
@erickzanardo Okay so the sprite renders as intended with skia, but now I have a new error (`CanvasKit threw an exception while laying out the paragraph`) :(

**Comment by erickzanardo** [comment]
> @erickzanardo Okay so the sprite renders as intended with skia, but now I have a new error (`CanvasKit threw an exception while laying out the paragraph`) :(
> 
> Edit: CanvasKit issue was from flutter/engine. Fixed by switching to master. I'm going to close this issue though it might be worth investigating why it renders weirdly in the first place

That paragraph issue is solved on `0.24.0` of Flame :D

**Comment by filleduchaos** [comment]
@erickzanardo alright now this is getting slightly weird 🙈 I don't quite want to open another issue for it since it's such a small thing, but there's a tiny somewhat breaking change in `0.24.0` - specifically that the `TextConfig` constructor is no longer `const`. I'm not sure if that's intentional because all the class fields are still final

**Comment by erickzanardo** [comment]
Yes, it is intentional, we had to add a cache for the text painters created for rendering the texts. That solved a weird crash that used to happen on web.

And by adding that cache on the class, the constructor couldn’t be const anymore.
