### ISSUE TITLE
Game not running on web

### ISSUE THREAD

**Issue by d-apps** [flame-engine/flame#416]
Everytime I try to run my game on web it gives me the error below, the game works fine on phone.

![image](https://user-images.githubusercontent.com/20110433/87114685-95358280-c247-11ea-91cb-cb13c14248fb.png)

![image](https://user-images.githubusercontent.com/20110433/87114708-a9797f80-c247-11ea-9e96-cc6c3ce2f7be.png)

**Could not load content for http://localhost:52472/C:/src/flutter/bin/cache/flutter_web_sdk/lib/_engine/engine/dom_renderer.dart (HTTP error: status code 400, net::ERR_HTTP_RESPONSE_CODE_FAILURE)**

**Pubspec.yaml**

![image](https://user-images.githubusercontent.com/20110433/87114763-c615b780-c247-11ea-8507-225e91093e2c.png)

**Error in the terminal:**

```
Error parsing request.
Invalid argument (requestedUri): handlerPath "null" and url "null" must combine to equal requestedUri path "/C:/src/flutter/bin/cache/flutter_we
b_sdk/lib/_engine/engine/dom_renderer.dart".: Instance of '_Uri'
dart:isolate  _RawReceivePortImpl._handleMessage
```

I aleady did flutter clean, I tried flutter run with --release and debug, same error. even if I don't render anything  (empty constructor) on the screen it gives me the error.

MyGame(){

// Empty here

}

**main.dart**

```
void main() async{

  WidgetsFlutterBinding.ensureInitialized();

  if(!kIsWeb){
    await Flame.util.fullScreen();
    await Flame.util.setOrientation(DeviceOrientation.landscapeLeft);
  }

  await Flame.images.loadAll([

      ...

  ]);
  await Flame.audio.loadAll(
    [

     ...

    ]
  );

  // Disable audio logs since it can confuse the log
  Flame.audio.disableLog();

  // Get the screen size
  Size size = await Flame.util.initialDimensions();

  // Create a singleton to retrieve the screen size in all app
  Config config = Config(screenSize: size);

  // Register singletons to retrieve it later
  Get.put(config);
  Get.put(AudioController());
  Get.put(MyGame());

  runApp(Get.find<MyGame>().widget);
  //runApp(MyGame().widget); //Also tried without retrieving the game class from the singleton


}
```

**flutter doctor -v**

```
[√] Flutter (Channel beta, 1.19.0-4.3.pre, on Microsoft Windows [versÃ£o 10.0.18363.900], locale pt-BR)
    • Flutter version 1.19.0-4.3.pre at C:\src\flutter
    • Framework revision 8fe7655ed2 (8 days ago), 2020-07-01 14:31:18 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Dih\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.46.0)
    • VS Code at C:\Users\Dih\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[√] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.116

• No issues found!
```

**Comment by erickzanardo** [comment]
This seems too deep on the flutter to be an issue on Flame, it rather seems a problem with your installation or Flutter itself.

To try to track this, can you share the full part of the code that you omitted here:

```
  await Flame.images.loadAll([

      ...

  ]);
  await Flame.audio.loadAll(
    [

     ...

    ]
  );
```

**Comment by erickzanardo** [comment]
btw, it seems that you are using dom to render your game, that is not recommend for Flame games, you should use skia instead.

You check how to use skia on web on this work in progress PR https://github.com/flame-engine/flame/pull/415/files

**Comment by d-apps** [comment]
> This seems too deep on the flutter to be an issue on Flame, it rather seems a problem with your installation or Flutter itself.
> 
> To try to track this, can you share the full part of the code that you omitted here:
> 
> ```
>   await Flame.images.loadAll([
> 
>       ...
> 
>   ]);
>   await Flame.audio.loadAll(
>     [
> 
>      ...
> 
>     ]
>   );
> ```

```
await Flame.images.loadAll([

      "title_screen_bg.png",
      "title.png",
      "play.png",
      "how_to_play.png",
      "exit.png",
      "shot.png",
      "player.png",

      "stage_1_1.png",
      "stage_1_2.png",
      "stage_1_3.png",
      "stage_1_4.png",
      "stage_1_5.png",

      "stage_2_1.png",
      "stage_2_2.png",
      "stage_2_3.png",
      "stage_2_4.png",

      "stage_3_1.png",
      "stage_3_2.png",
      "stage_3_3.png",
      "stage_3_4.png",
      "stage_3_5.png",
      "stage_3_6.png",

      "alien_1_1.png",

  ]);
  await Flame.audio.loadAll(
    [

      "title_screen.mp3",
      "button.mp3",
      "stage_1_audio.mp3",
      "stage_2_audio.mp3",
      "stage_3_audio.mp3",
      "stage_4_audio.mp3",
      "stage_5_audio.mp3",
      "boss.mp3",

    ]
  );
```

Only running this command it will use skia instead? If it's not recommended to use dom to render game, shoudn't be skia by default when using flame? if not, the command below will change to skia for all "flutter run"?

**flutter run -d chrome --release --dart-define=FLUTTER_WEB_USE_SKIA=true**

**Comment by erickzanardo** [comment]
> shoudn't be skia by default when using flame?
That is not something that Flame can do, Flame is just a package in the end. But would be very cool if there were a way t do that

> flutter run -d chrome --release --dart-define=FLUTTER_WEB_USE_SKIA=true

Yes, that is one of the ways

**Comment by d-apps** [comment]
> > shoudn't be skia by default when using flame?
> 
> That is not something that Flame can do, Flame is just a package in the end. But would be very cool if there were a way t do that
> 
> > flutter run -d chrome --release --dart-define=FLUTTER_WEB_USE_SKIA=true
> 
> Yes, that is one of the ways

I tried with skia but got the same error.

**Comment by erickzanardo** [comment]
Did a quick search on google and found this issue. This seems to be related https://github.com/flutter/flutter/issues/60235

**Comment by d-apps** [comment]
> Did a quick search on google and found this issue. This seems to be related [flutter/flutter#60235](https://github.com/flutter/flutter/issues/60235)

But your games like Flame and Watch, Rogue Shooter, works on web right? They were build beta channel too?

Bonfire works on web too: http://rafaelbarbosatec.github.io/bonfire/#/

Maybe a diferent beta version? That's strange.

**Comment by erickzanardo** [comment]
have you tried running one of these projects on your machine?

**Comment by d-apps** [comment]
> have you tried running one of these projects on your machine?

Trying to run rogue_shooter I have this error about favicon.

![image](https://user-images.githubusercontent.com/20110433/87186492-f863fb00-c2c1-11ea-8e04-97f8c2501e41.png)

**Comment by erickzanardo** [comment]
> > have you tried running one of these projects on your machine?
> 
> Trying to run rogue_shooter I have this error about favicon.
> 
> ![image](https://user-images.githubusercontent.com/20110433/87186492-f863fb00-c2c1-11ea-8e04-97f8c2501e41.png)

That is hardly related to the original issue, and this is just a matter of not having configured the favicon on the project rather than a real problem.

Anyway, have you been able to solve your issue? Is there any other help we can provide?

**Comment by d-apps** [comment]
> > > have you tried running one of these projects on your machine?
> > 
> > 
> > Trying to run rogue_shooter I have this error about favicon.
> > ![image](https://user-images.githubusercontent.com/20110433/87186492-f863fb00-c2c1-11ea-8e04-97f8c2501e41.png)
> 
> That is hardly related to the original issue, and this is just a matter of not having configured the favicon on the project rather than a real problem.
> 
> Anyway, have you been able to solve your issue? Is there any other help we can provide?

But a favicon error shouldn't stop to run the game right? I still the first error I described.

**Comment by erickzanardo** [comment]
> But a favicon error shouldn't stop to run the game right? I still have the first error I described.

No and I doubt that this error is preventing you for running the game, I will try running rogue shooter on web when I get some time and will report back.

**Comment by erickzanardo** [comment]
I just tested rogue_shooter on the web, and everything is working fine, I just had to update the codebase to the latest flame version, as the version that it was using previously (0.19.1-beta) wasn't compatible with the current beta channel.

Like I said, the favicon is really not the problema, as that error has occurred on my test, but didn't prevented the game from running.

Have you tried running any flutter app on web? One that don't use Flame? Also have you tried uninstalling Flutter from your machine and reinstalling it? Or even just upgrading your Flutter version?

**Comment by d-apps** [comment]
I am building a flutter web site and it's working fine.
I already reinstalled flutter sdk, delete all files inside flutter's sdk folder, downloaded and re-extracted a fresh new folder. (C:/src/flutter).

It's strange because I am using same packages in another flutter web project, the only difference is this two packages; flame and flame_scrolling_sprite.

Even if I am not rendering anything on the Game's constructor I get this error, that's strange.

```
Overflow on channel: plugins.flutter.io/path_provider.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need
to adjust the buffer size if of the channel.
```

**Comment by erickzanardo** [comment]
We use path provider on Audio players iirc, can you add this version on a plain flutter app and try it there?


  path_provider: ^1.5.1

**Comment by d-apps** [comment]
> We use path provider on Audio players iirc, can you add this version on a plain flutter app and try it there?
> 
> path_provider: ^1.5.1

I tried using path_provider versions: ^1.5.1 and ^1.6.11 on an Counter flutter web project and it worked fine.

I think I'll open an issue with this specific problem, there is one or two issues already opened about overflow but not about overflow on channel of the path_provider?

**Comment by erickzanardo** [comment]
@spydon @renancaraujo @luanpotter can you please try running the rogue shooter project on web and see if that issue happen on your machine? Maybe more people testing we an try to simulate this.

**Comment by d-apps** [comment]
> @spydon @renancaraujo @luanpotter can you please try running the rogue shooter project on web and see if that issue happen on your machine? Maybe more people testing we an try to simulate this.

When you have some time, if you want, you can access my machine through teamviewer and we can test investigate together.

**Comment by d-apps** [comment]
I found the problem just not the solution yet, it's something about the audios, If I comment them, the game works, but the audios work on phone sp it's overflowing only on channel of the path_provider when running on web.

```
 /*

  await Flame.audio.loadAll(
    [

      "title_screen.mp3",
      "button.mp3",
      "stage_1_audio.mp3",
      "stage_2_audio.mp3",
      "stage_3_audio.mp3",
      "stage_4_audio.mp3",
      "stage_5_audio.mp3",
      "boss.mp3",

    ]
  );

   */
```

**Comment by erickzanardo** [comment]
Dammit, how did I missed that, you cannot call load from the audio on web, please, there is an issue to track methods that can't be called on the web, please comment about that on that issue and close this one.

**Comment by d-apps** [comment]
> Dammit, how did I missed that, you cannot call load from the audio on web, please, there is an issue to track methods that can't be called on the web, please comment about that on that issue and close this one.

If you could add this information about not loading audios if is web will be very helpful.

if(!kIsWeb){
    await Flame.audio.loadAll(
        [

          "title_screen.mp3",
          "button.mp3",
          "stage_1_audio.mp3",
          "stage_2_audio.mp3",
          "stage_3_audio.mp3",
          "stage_4_audio.mp3",
          "stage_5_audio.mp3",
          "boss.mp3",

        ]
    );
  }

I couldn't find that issue about track methods you said, sorry.
