### ISSUE TITLE
Because every version of flutter_test from sdk depends on xml 3.6.1 and tiled >=0.4.0 depends on xml ^4.2.0, flutter_test from sdk is incompatible with tiled >=0.4.0. And because flame >=0.24.0 depends on tiled ^0.6.0, flutter_test from sdk is incompatible with flame >=0.24.0. So, because flutter_game depends on both flame ^0.24.0 and flutter_test any from sdk, version solving failed. pub upgrade failed (1; So, because flutter_game depends on both flame ^0.24.0 and flutter_test any from sdk, version solving failed.)

### ISSUE THREAD

**Issue by lohitbura** [flame-engine/flame#422]

**Comment by lohitbura** [comment]
Should I reduce flame version or what ??

**Comment by erickzanardo** [comment]
Please, use meaningful titles and description when opening a issue.

Anyway, you have two alternatives here

 - Stay on stable and replace the `flutter_test` dependency from the sdk to the `test` package from pub
 - Go to the beta channel

**Comment by erickzanardo** [comment]
Let us know if there are still doubts about this.

**Comment by ProgrammingLife** [comment]
I have the same issue.

**Comment by erickzanardo** [comment]
> >Stay on stable and replace the flutter_test dependency from the sdk to the test package from pub
> How to do it?

Just the remove the flutter_test dependency that is on your pubspec, and drop that one instead: https://pub.dev/packages/test

About the beta channel, I am talking about flutter's beta channel, so you can just run `flutter channel beta`, and keep using fame 0.24.0 from pub
