### ISSUE TITLE
How to drag an image?

### ISSUE THREAD

**Issue by ProgrammingLife** [flame-engine/flame#423]
I'm thinking about ```onTapDown()``` and ```onTapUp()```. But what about something like ```onTapMove()```? :) 
How do I get coords when my image is pressed and dragging? Should I use ```MultiTouchDragDetector``` and detect just the first touch?

**Comment by erickzanardo** [comment]
Please, take a look on the input section of the documentation, there are similar mixins like TapDetector but for for dragging, like PanDetector.
