### ISSUE TITLE
What's the top method of the engine which calls render()?

### ISSUE THREAD

**Issue by ProgrammingLife** [flame-engine/flame#424]
Wanna make some changes in render process in my own implementation but I can't find out what's the top render() method of the engines which calls other render() methods? What's the start point for all of this rendering system? Wish to know a little more about the engine structure.

In short words I wanna know what Flame's method calls my MyGame.render()? (MyGame extends BaseGame)

**Comment by erickzanardo** [comment]
Here: https://github.com/flame-engine/flame/blob/fb478f465bdc314ebcca70e759c91ad5b114f570/lib/game/game_render_box.dart#L66

Please prefer to use our Discord server for this kind of question.

Closing this as this is not an issue.
