### ISSUE TITLE
'ComposedComponent' can't be mixed onto 'PositionComponent'

### ISSUE THREAD

**Issue by ProgrammingLife** [flame-engine/flame#426]
Tried to deal with ComposedComponent which describes here https://flame-engine.org/docs/components.md but I faced an issue:

> 'ComposedComponent' can't be mixed onto 'PositionComponent' because 'PositionComponent' doesn't implement 'HasGameRef<Game>'.
> Try extending the class 'ComposedComponent'.

My attempt was simply just:

```
class GameOverPanel extends PositionComponent with Resizable, ComposedComponent {
...
}
```

How to properly use it in this way?

**Comment by ufylord** [comment]
The code of ComposedComponent is below ( [link](https://github.com/flame-engine/flame/blob/fb478f465bdc314ebcca70e759c91ad5b114f570/lib/components/composed_component.dart#L40) ) :
```
mixin ComposedComponent on Component, HasGameRef, Tapable {
...
}
```
It is `mixin XXX on XYZ`, so your component `GameOverPanel` should implement `Component`, `HasGameRef` and `Tapable`

**Comment by ufylord** [comment]
#167

**Comment by erickzanardo** [comment]
@ProgrammingLife the help provided by ufylord fixed, clarified your issue?

**Comment by erickzanardo** [comment]
closing due inactivity.
