### ISSUE TITLE
Docs URLs broken

### ISSUE THREAD

**Issue by Leviosar** [flame-engine/flame#428]
The [official website](https://flame-engine.org/docs) links on "Getting started" section that points to this repository markdowns are broken, for example the `Structures` link points to `https://github.com/flame-engine/flame/blob/master/structure.md` which gives a 404 error, i believe it should be `https://github.com/flame-engine/flame/blob/master/doc/structure.md`. Other links have the same problem.

Thanks for this awesome engine <3

**Comment by ufylord** [comment]
#420

**Comment by ufylord** [comment]
Duplicate of #420
And the repository for the [official website](https://flame-engine.org/docs/) is [flame-engine-site](https://github.com/flame-engine/flame-engine-site)

**Comment by Leviosar** [comment]
Sorry, I didn't know about the repository for the website. I am closing this issue then, thanks.
