### ISSUE TITLE
audioPlayer null exception

### ISSUE THREAD

**Issue by beyondacme** [flame-engine/flame#436]
void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.resumed) {
      if (isPlaying &&
          audioPlayer != null &&
          audioPlayer.state == AudioPlayerState.PAUSED) {
        audioPlayer.resume();
      }
    } else {
      **audioPlayer.pause();**
    }
  }

null

**Comment by erickzanardo** [comment]
Please provide a meaningful description for the issue, I have no idea what is the problem by just looking at some code without any explanation of what is happening

**Comment by beyondacme** [comment]
When I used this plugin, I encountered an exception. The player may not be initialized successfully, calling **audioPlayer.pause()** will throw an exception：**NoSuchMethodError: The method 'pause' was called on null. Receiver: null Tried calling: pause()
Bgm.didChangeAppLifecycleState**

Here to add a non-null judgment

void didChangeAppLifecycleState(AppLifecycleState state) {
if (state == AppLifecycleState.resumed) {
if (isPlaying &&
audioPlayer != null &&
audioPlayer.state == AudioPlayerState.PAUSED) {
audioPlayer.resume();
}
} else (**audioPlayer != null)**{
audioPlayer.pause();
}
}

**Comment by erickzanardo** [comment]
Your audioPlayer variable is null when you tried to call `pause` on it, maybe you forget to initialize it?

**Comment by beyondacme** [comment]
I called ```Flame.bgm.initialize();```  to auto-pause and resume.  But in ```bgm.dart```  Other codes have done audioPlayer non-null  processing， only this line do not do  non-null judgment.

**Comment by erickzanardo** [comment]
Oh, okay, that snippet you posted is from Flame, now I understand what is the problem

**Comment by erickzanardo** [comment]
Fixed on #468 will be released on 0.0.27
