### ISSUE TITLE
BoxGame可以放在非main的widget里面初始化吗？

### ISSUE THREAD

**Issue by wengxianxun** [flame-engine/flame#441]
BoxGame game = BoxGame();

runApp(game.widget);

这段初始化代码可以放在后面的某个具体Widget中吗，比如我现在项目里面main开始是一个纯flutter，然后点击一个按钮push到一个新的Widget在初始化这个BoxGame， 当我pop回main后注销掉BoxGame

**Comment by spydon** [comment]
Since I had to google translate your question I'm not sure that I got it correctly, but yes, you can put it wherever in your flutter tree since the game is just a widget. Please keep to English for future issues.
