### ISSUE TITLE
Custom method not drawing

### ISSUE THREAD

**Issue by diezep** [flame-engine/flame#445]
I have this code, when i call _generatePoint_ method, the print works, but the TapableSquare isn't drawing, someone can help me pls.
```
import 'dart:async';

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

import 'package:flame/components/mixins/tapable.dart';
import 'package:flame/game/base_game.dart';

import 'package:aimgame/main.dart';
import 'package:aimgame/src/game/components/point.dart';

class GameCanvas extends BaseGame with HasTapableComponents {
  static final Paint paint = Paint();
  Size screenSize;
  Timer timer;

  void generatePoint(String code, Offset offset) async {
    print('Point generated #$code @ $offset');

    this.add(TapableSquare()
      ..x = screenSize.width * offset.dx / 100  
      ..y = screenSize.width * offset.dy / 100);
      
  }

  @override
  void resize(Size size) {
    screenSize = size;
    // add();
    // timer = Timer.periodic(
    //     Duration(seconds: 1),
    //     (timer) => generatePoint(
    //         '',
    //         Offset(Random().nextInt(100.toInt()).toDouble(),
    //             Random().nextInt(100.toInt()).toDouble())));

    super.resize(size);
  }

  @override
  void render(Canvas canvas) {
    // Change background color.
    Rect bgRect = Rect.fromLTWH(0, 0, screenSize.width, screenSize.height);
    Paint bgPaint = Paint();
    bgPaint.color = ColorPalette.background;
    canvas.drawRect(bgRect, bgPaint);

    super.render(canvas);
  }
}
```

**Comment by erickzanardo** [comment]
What is the render method of the `TapableSquare`?

**Comment by diezep** [comment]
> What is the render method of the `TapableSquare`?
```
class TapableSquare extends PositionComponent with Tapable {
  static final Paint _white = Paint()..color = const Color(0xFFFFFFFF);
  static final Paint _grey = Paint()..color = const Color(0xFFA5A5A5);

  bool _beenPressed = false;

  TapableSquare({double y = 100, double x = 100}) {
    width = height = 10;
    this.x = x;
    this.y = y;
  }

  @override
  void render(Canvas canvas) {
    // canvas.drawRect(toRect(), _beenPressed ? _grey : _white);
    canvas.drawCircle(Offset(this.x, this.y), 10, _white);
  }

  @override
  void onTapUp(TapUpDetails details) {
    _beenPressed = false;
    print('object');
  }

  @override
  void onTapDown(TapDownDetails details) {
    _beenPressed = true;
    print('object');
  }

  @override
  void onTapCancel() {
    _beenPressed = false;
    print('object');
  }

  @override
  bool destroy() => _beenPressed;
}
```

**Comment by luanpotter** [comment]
This `screenSize.width * offset.dx / 100` is probably offscreen. You probably want something like `x = offset.dx`?

**Comment by luanpotter** [comment]
ohh I finally understood why you did that. You thought offset.dx was a percentage right? it's not, it's the absolute virtual pixel coordinates.

**Comment by diezep** [comment]
# Yes, it's the porcentage to show in different screens

**Comment by renancaraujo** [comment]
> `..y = screenSize.width * offset.dy / 100)`

Do you really mean to calculate `y` based on screen **width**?

**Comment by diezep** [comment]
> > `..y = screenSize.width * offset.dy / 100)`
> 
> Do you really mean to calculate `y` based on screen **width**?

Yes, because the offset always

**Comment by erickzanardo** [comment]
> > > `..y = screenSize.width * offset.dy / 100)`
> > 
> > 
> > Do you really mean to calculate `y` based on screen **width**?
> 
> Yes, because the offset always will be between 0 and 100

I don't think so @diezep, it is the absolute value of the virtual position where the tap happened, you can just use the value directly.

**Comment by diezep** [comment]
> > > > `..y = screenSize.width * offset.dy / 100)`
> > > 
> > > 
> > > Do you really mean to calculate `y` based on screen **width**?
> > 
> > 
> > Yes, because the offset always will be between 0 and 100
> 
> I don't think so @diezep, it is the absolute value of the virtual position where the tap happened, you can just use the value directly.

But.. The method has a variable offset as argument, i assign a value between 0 and 100, right?

**Comment by diezep** [comment]
I think that is not the problem, because i have a periodic timer in resize method that works

**Comment by diezep** [comment]
> > > > `..y = screenSize.width * offset.dy / 100)`
> > > 
> > > 
> > > Do you really mean to calculate `y` based on screen **width**?
> > 
> > 
> > Yes, because the offset always will be between 0 and 100
> 
> I don't think so @diezep, it is the absolute value of the virtual position where the tap happened, you can just use the value directly.

Or may i don't understand what you mean at all
