### ISSUE TITLE
Flame app FPS drops when upgrading from Flutter SDK 1.19.0-4.0.pre -> 1.19.0-5.0.pre

### ISSUE THREAD

**Issue by christopherfujino** [flame-engine/flame#448]
There seems to have been a regression in the Flutter engine on [`f46dde1`](https://github.com/flutter/engine/commit/f46dde1f06e11b18fb07f51cfc93286bdda3eaa6), which was first published in Flutter SDK 1.19.0-5.0.pre, that can lead to a regression in framerate for a Flame app.

Minimal app reproduction to follow via @jiack214

**Comment by christopherfujino** [comment]
This has independently been filed upstream as #63876, and it includes a minimal (non-flame) reproduction https://github.com/deckerst/flutter_image_anim_regression

**Comment by erickzanardo** [comment]
This is already solved on Flutter beta channel, and will probably be too on stable, closing this.
