### ISSUE TITLE
[Box2D] Random deletion of body components in release mode

### ISSUE THREAD

**Issue by tommybuonomo** [flame-engine/flame#456]
Hello there 🙂 , 

Each time I test my game in release mode, I have weird random behaviours, and those bugs **never** happen in debug mode.

The most annoying bug is the one that delete randomly some body component of the world. In this video, you can see that the circle component at the half of the worm is destroyed just after launching it.

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/15737675/92323656-b42f7580-f03a-11ea-9ad9-241c17a6118e.gif)

Here is the slow motion of the moment where the body component is deleted:
![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/15737675/92323722-58192100-f03b-11ea-808d-dfb70d394e45.gif)

There is another bug I encountered only in release mode (I can't explain this one, but it seems there is an position issue with a body) :
![ezgif com-video-to-gif (4)](https://user-images.githubusercontent.com/15737675/92323840-20f73f80-f03c-11ea-9ca3-31fb631a7f37.gif)

Thanks 🙏

**Comment by spydon** [comment]
Interesting, I don't know what difference between debug and release mode that would make this happen.
I will try to debug this when I get some time.
If you decide to go further and debug the box2d code we would of course accept a PR fixing this too.

**Comment by tommybuonomo** [comment]
Hey @spydon I tried to debug the box2d code but in fact, I don't really found something different between the 2 mode debug/release.
My theory is that it's maybe due to Android R8 obfuscation. I'll try with the `--no-shrink` option. I'll try also to reproduce the issue on iOS to confirm it's only an Android release mode issue.
Thanks for your help 🙏

**Comment by tommybuonomo** [comment]
Hey @spydon, 
I haven't found a solution yet, event with the --no-shrink option, the issue still happening in release mode :/ 
Keep me in touch if you work on this when you have time :)

**Comment by spydon** [comment]
@tommybuonomo If you want to try more things you could try to run it with this version of box2d https://github.com/flame-engine/box2d.dart/pull/9 which has quite a lot of changes in it, but since I don't know what the problem could be here yet I have no idea if anything in there would change anything. 
Thanks for the investigation so far, it is very valuable!

**Comment by tommybuonomo** [comment]
Wow good job @spydon this is a huge refacto 👍 
Unfortunately, there is breaking changes that prevent the libraries `flame` and `flame_svg` to compile if I switch the `box2d_flame` to your branch (even if I override the `flame` library to your `spydon.vector2d-unification` branch). 
Maybe due to the fact that the `spydon.vector2d-unification` is 126 commits behind master ?

**Comment by spydon** [comment]
Yeah, it gets a bit complicated to run it now before Flame v1.0 is released since the box2d support is moved out to `flame_box2d`.
I'll try to finish up what needs to be done on the flame side and make instructions of how to make it running.

**Comment by tommybuonomo** [comment]
Hey @spydon 🙂
A little update of the long investigation I made on this issue:

- It concerns both Android & iOS OS, so it's not a specific platform issue, but a dart issue
- Bodies are randomly set to **inactive** (there are not destroyed, but just set to inactive)
- I checked the box2d_flame code, and the method `setActive(false)` on a body is never called.
- In the class `Body`, the `_flags` field is never touched with the deletion of the `ACTIVE_FLAG`.

So, I am very confused about this issue, because it does not concern a code issue. It looks like a native memory issue, but I can't do much about this.

I've tried something to overpass the issue in the `update` method of the `Box2DGame` component:
``` dart
  @override
  void update(double t) {
    super.update(t);
    box.components.forEach((element) {
      if (!element.body.isActive()) {
        print("Element not active: ${element.body.getType()}");
        element.body.setActive(true);
      }
    });
  }
```

But this bring a new error with no description in the logs, and the game becomes totally stuck.. Not a viable solution 

I hope this will ring a bell for you. For the moment, I am in the obligation to postpone the launch of my game. 

I didn't found the way to test your `vector2d-unification` branch without compilation errors. You are my only chance 😊
Thanks a lot for your help 🙏

**Comment by spydon** [comment]
Hey again @tommybuonomo 
I think I bumped over the issue yesterday too in the benchmarking code, which is just pure dart code, so if it is the same problem it has nothing to do with flutter. Since you seemingly aren't handling a lot of bodies in your app maybe you can do a fork of `box2d.dart` and turn off that the bodies can go to sleep, if you don't want to delay your launch?

**Comment by spydon** [comment]
Ah sorry, it's too early in the morning. You shouldn't have to fork it, just call:
`world.setAllowSleep(false);`

**Comment by tommybuonomo** [comment]
Hey @spydon, I already try the setAllowSleep option and it's not working 😔
Thanks

**Comment by spydon** [comment]
Do they only go inactive outside of the viewport, or have you seen it on screen too?
Was your print ever invoked in the solution that you tried above?

**Comment by tommybuonomo** [comment]
Yes, the print is always invoked in release mode, with bodies inside of the viewport.

**Comment by tommybuonomo** [comment]
I confirm that even with the setAllowSleep at the right place, the bug is still here 😭
Plus, I had another issue, that is surely related. A ChainBody loose all contacts, but it remains active (cf gif the brown ChainBody is a static body and it had none contacts). It happened suddenly.
![ezgif com-video-to-gif (5)](https://user-images.githubusercontent.com/15737675/93335143-4e0ad580-f826-11ea-8880-b58800972380.gif)

**Comment by luanpotter** [comment]
I don't know a lot about box2d but one thing I would check is to play around with different velocities, angles, gravities, etc to try to identify when it happens. is it random (if you hardcode the params does it happen all the time or not), and if not what exact values cause it. might help to identify the issue in the code.

just to be safe, on your own code, are there any places at all where you delete/remove/inactivate anything? I would remove those even if you don't think it's related just to be sure the problem persists.

**Comment by tommybuonomo** [comment]
Hey @luanpotter ,
Every time the worm is out of the screen, I delete it from the world (using the `box.remove()` method) and I recreate it instantly at the right position. But I never touch the active option of a body. 
FYI, i create a simple project to provokes the bug in release mode: https://github.com/tommybuonomo/box2d-dart-release-issue/settings
To resume this project: I add one worm in the world every 500ms. I remove the worms after 10 seconds in the world. If a worm have the bug, it will be colored in black, and it will not be removed from the world (to let the bug visible).
Sometimes it takes 10 seconds for the bug to happen, sometimes 3 minutes, so be patient :)

**Comment by spydon** [comment]
Why do you delete it?
When you have such few bodies, why not let box2d handle it when it is outside of the screen too?

**Comment by tommybuonomo** [comment]
Yes you're right, I could recycle it and place it to the new position. I'll try this for my game !
But this will not fix the first issue. If someone create a game with a lot of bodies and a lot of deletion, the bug will pop again :/

**Comment by tommybuonomo** [comment]
The issue is still here, even with the recycling. The reason is that each level of the game, I navigate to a new fresh page to load a new level. So I think the leak persist

**Comment by spydon** [comment]
I think I misunderstand you, I'll hopefully have time to look at your example code tomorrow and that will probably make it clearer. But do you delete the body when it is not visible on the screen anymore, like when you shoot it upwards and it goes out on the top of the screen? If that is so, why not have the box2d world large enough to handle the parts outside of the screen too?

**Comment by tommybuonomo** [comment]
Yes I delete the bodies out of the screen because I don't need them anymore, and I don't want box2d to still handle those bodies because they affect performances of the game. If the user retry 100 times a level, I want to keep only one reference of the worm in my game, not 100.
And from what I saw, box2d doesn't automatically destroy the out-of-screen bodies. 
It could be a big help in fact if you could look at the example :)

**Comment by tommybuonomo** [comment]
FYI, and to give some update in this discussion, I opened an issue (just above) on flutter because the bug is more than a coding issue, and does not concerns the flame-engine library. 
Feel free to consult it the know more about it and how I fixed it.
Thanks again for your precious help !
