### ISSUE TITLE
Box2d doc and example

### ISSUE THREAD

**Issue by erickzanardo** [flame-engine/flame#47]
Add box2d docs and an example

**Comment by luanpotter** [comment]
Maybe @feroult can help with this?

**Comment by feroult** [comment]
Yes I can.

I'm planning to promote `haunt` as Box2D tutorial.

**Comment by luanpotter** [comment]
That'd be awesome! We should to bump it to flame 0.10.2 (latest), though.

**Comment by erickzanardo** [comment]
Fixed on #126
