### ISSUE TITLE
Create migration guide to 1.0

### ISSUE THREAD

**Issue by renancaraujo** [flame-engine/flame#470]
We shall provide a guide to point a path of migration of an existing project using a 0.x version fo flame to make it use the upcoming 1.x versions. 

This shall make the way to this milestone alongside the preview(RC) versions.

**Comment by st-pasha** [comment]
Are we still planning on doing this, or is it too difficult at this point?

**Comment by spydon** [comment]
> Are we still planning on doing this, or is it too difficult at this point?

I'm voting for too difficult, and not worth it since there are so few people that use 0.26.x now.

**Comment by renancaraujo** [comment]
And quite useless. If done, a migration guide should cover the migration from some RCs that is not doable. Shall we cancel this?
