### ISSUE TITLE
Any better way to interact from component to game instead of GameRef?

### ISSUE THREAD

**Issue by cloudseasail** [flame-engine/flame#477]
I see there is builtin GameRef mixin which could reference to game instance,  wondering is this the recommended way to interact between component and game?  
I am thinking to make async behaviour when user click component and trigger game state changing,  wondering is there any builtin method for this purpose?  or I have to add sth by myself  (like stream?)

Thanks!

**Comment by d-apps** [comment]
I think there is only 3 ways to retrieve the reference of your game instance, mixin inside component classes, singleton and passing through constructor (singleton is useful when you need to retrieve the game instance inside widgets that you'll call using `addWidgetOverlay`)

**Comment by cloudseasail** [comment]
Thanks for the advices,  I will try mixin or singleton.  
Actually I was expecting more elegent way to handle this,  will close this issue and might get back if some better idea rised.
