### ISSUE TITLE
question: how to create animation with component ?

### ISSUE THREAD

**Issue by bung87** [flame-engine/flame#478]
I want create a simple fade out animation, I know flutter can use `AnimationController` in `widget` which is simple.
however in component I can't get right `this` context pass to `AnimationController`'s `vsync` parameter .
below is the code demonstrate the logic.
```dart
   AnimationController controller = new AnimationController(
        duration: const Duration(milliseconds: 2000), vsync: this);
    Animation animation = new Tween(begin: 1, end: 0).animate(controller);
    animation.addListener(() {
      introBg.sprite.paint.color =
          const Color(0xFFFFFFFF).withOpacity(animation.value);
    });
    controller.forward();
```

**Comment by erickzanardo** [comment]
Flame components are not Flutter widgets, so you can't use AnimationController. To make a component fade, you will need to manipulate the `Paint` opacity that is used to render that component.

This probably can give you some idea: https://github.com/erickzanardo/cave-ace/blob/c2ef124c7b2e53cddb28c71eacf1f9b1b9311c4e/cave_ace/lib/components/effects/hit_effect.dart#L17

**Comment by bung87** [comment]
Thank you ! this is helpful, I have suggestion , I think better have `ComponentEffect` as basic class contains `Component` could be generic type make it more flexible.

**Comment by spydon** [comment]
That is actually a pretty good idea @bung87, I did an implementation of it here https://github.com/flame-engine/flame/pull/484 if you want to have a look.

**Comment by bung87** [comment]
nice!! That's what I need.
