### ISSUE TITLE
audio_pool example is not working on iOS

### ISSUE THREAD

**Issue by oakstair** [flame-engine/flame#488]
## Description

I fail to run the audio_pool example under iOS. After one or two click it hangs.

    Syncing files to device iPhone SE (2nd generation)...
    flutter: Fatal Error: Callback lookup failed!
    flutter: Fatal Error: Callback lookup failed!
    flutter: Fatal Error: Callback lookup failed!

When googling this issue I found some hacks around that probaly should be added to flame !?

## Development enviroment

Flame version: I cloned the repo today 2020-10-06

## Runtime

This issue is related to running on which platform? (Select all that apply)

 - [ ] Android :android:
 - [X] iOS :apple:
 - [ ] Web :browser:

**Comment by erickzanardo** [comment]
> When googling this issue I found some hacks around that probaly should be added to flame !?

Can you please share those hacks with us?

**Comment by oakstair** [comment]
https://stackoverflow.com/questions/61263458/flutter-fatal-error-callback-lookup-failed-with-audioplayers-package

**Comment by erickzanardo** [comment]
@luanpotter can you take a look on this? Seems a problem on AP

**Comment by erickzanardo** [comment]
@luanpotter news on this?

**Comment by luanpotter** [comment]
Will take a look!

**Comment by luanpotter** [comment]
Fixed in the latest flame_audio (rc3) for 1.0.0.
For v0.x I am planning on releasing a hot fix 0.29.0 version.
