### ISSUE TITLE
Is it possible to support plist format spritesheet?

### ISSUE THREAD

**Issue by MacroLove** [flame-engine/flame#489]
## Description

Describe your issue here

## Development enviroment

Flame version:

Flutter doctor:

```
 Include your flutter doctor output here
```

## Runtime

This issue is related to running on which platform? (Select all that apply)

 - [ ] Android :android:
 - [ ] iOS :apple:
 - [ ] Web :browser:

## Minimal reproducible code (Required for bugs)

Include a minimal code that reproduces the problem add it inline using code block markdown, or a link to Github repository:

**Comment by erickzanardo** [comment]
Please send your suggestion on our Discord, you can find the join link on the README.

We use github issue for tracking real issues like bugs and problems.

When you join, please explain what do you mean plist format as I am not sure what that means.

Thanks!
