### ISSUE TITLE
How to get the x & y coordinates of my sprite in a list of tiles

### ISSUE THREAD

**Issue by salah-rashad** [flame-engine/flame#490]
How to get the x & y coordinates of my sprite in a list of tiles

## Description

How to get the x & y coordinates of my sprite in a list of tiles

## Development enviroment

Flame version: ^0.27.0

Flutter doctor:

```
 [√] Flutter (Channel master, 1.22.0, on Microsoft Windows [Version 10.0.18362.1082], locale en-US)
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.49.3)
[√] Connected device (1 available)
```

## Runtime

This issue is related to running on which platform? (Select all that apply)

 - [*] Android :android:

## Minimal reproducible code (Required for bugs)

double x = getCoordinates(x);
double y = getCoordinates(y);

**Comment by renancaraujo** [comment]
Hi @salah-rashad, 
When openning the issue, you probably had seen something like this:

> We use Github issues for problem/bug reports, for questions please use the Discord channel
> The link for the Discord channel can be found on the projects README

Check dicord. 
https://discord.com/invite/pxrBmy4
