### ISSUE TITLE
Deadlink to https://flame-engine.org/docs/effects.md

### ISSUE THREAD

**Issue by daisy1754** [flame-engine/flame#492]
## Description

At the bottom of https://flame-engine.org/docs/components.md it links to https://flame-engine.org/docs/effects.md but it's deadlink. I believe it should point to https://github.com/flame-engine/flame/blob/master/doc/effects.md

**Comment by luanpotter** [comment]
@renancaraujo is this fixed on the new website?

**Comment by erickzanardo** [comment]
@renancaraujo is this fixed on the new website?

**Comment by rundun** [comment]
I can help test the new site if there is a staging instances?

**Comment by spydon** [comment]
The link now works, but it doesn't set the scroll position to the top of the page seemingly.

**Comment by luanpotter** [comment]
@renancaraujo can you take a look on the anchor issue?

**Comment by erickzanardo** [comment]
Tested on the new site and it is working now. Closing this.
