### ISSUE TITLE
Feature Request: API to specify effect with total duration

### ISSUE THREAD

**Issue by daisy1754** [flame-engine/flame#493]
## Description

Currently [Effects](https://github.com/flame-engine/flame/blob/master/doc/effects.md) takes speed as argument. There is a use case where user of library want to specify duration instead. 

Currently user has to look into implementation of Effect and reverse the math of calculating `travelTime`. It would be great if library can provide utility function so I can do like:

```
MoveEffect.withDuration(1000, destination, { curve: Curves.easeIn })
```

Another use case is that I want to make `CombinedEffect` where I move and scale the object. I want to start and stop both animation at the same time. 

## Development environment

Flame version: 0.27.0

Flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.6 19G2021, locale en-US)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.48.2)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by spydon** [comment]
Good suggestion, I'll try to get this feature into v1.0.0.
