### ISSUE TITLE
Error: Type 'FrameTiming' not found.

### ISSUE THREAD

**Issue by jamminc** [flame-engine/flame#497]
## Description

1. Create standard flutter app 
2. Added Flame dependences ^0.27.0, pub get.. 
3. Goto Example tab, copy example program from page and paste to main.dart
4. Run the app and get a long list of compile error:

Launching lib/main.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleDebug'...

Compiler message:
../../DevTools/flutter/.pub-cache/hosted/pub.dartlang.org/flame-0.27.0/lib/fps_counter.dart:10:8: Error: Type 'FrameTiming' not found.
  List<FrameTiming> _previousTimings = [];
       ^^^^^^^^^^^
../../DevTools/flutter/.pub-cache/hosted/pub.dartlang.org/flame-0.27.0/lib/fps_counter.dart:13:31: Error: Type 'FrameTiming' not found.
  void onTimingsCallback(List<FrameTiming> timings) =>
                              ^^^^^^^^^^^
... etc...etc...etc

## Development environment

Cleaned test machine on MacAir.  

Flame version:

0.27.0

Flutter doctor:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.6 19G2021, locale en-MY)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.46.1)
[✓] Connected device (1 available)

• No issues found!

## Runtime

Unable to compile...

## Minimal reproducible code (Required for bugs)

Just using the example code in pub.dev..

**Comment by erickzanardo** [comment]
The flutter version you are using is outdated, please update your flutter to the latest stable or beta and the problem will most likely be resolved.

**Comment by jamminc** [comment]
Thanks... working now!!!
Time to update my disk image again :)
