### ISSUE TITLE
is there a way to render scrollview?

### ISSUE THREAD

**Issue by daisy1754** [flame-engine/flame#506]
## Description

I want to render list of text. It's long text so I would like allow user to scroll through text. 
Is there equivalent of Android's ScrollView in flame? I realize I can probably implement something using ScrollDetector but ideally I would like to have standard component with scrollbar etc

## Development environment

Flame version:

Flame version: 0.27.0

**Comment by erickzanardo** [comment]
Flame don't provide any scrollable text component to be rendered inside the canvas.

My suggestion to you is to use Flame's widget overlay feature, where you can show Flutter widgets on top of the game canvas, that way you could simply Flutter widgets to show the scrollable text, an example here: https://github.com/flame-engine/flame/tree/master/doc/examples/with_widgets_overlay

Closing this as this is not an issue.
