### ISSUE TITLE
HorizontalDragDetector doesn't work with HasTapableComponents

### ISSUE THREAD

**Issue by daisy1754** [flame-engine/flame#510]
## Description

I want to add horizontal swipe gesture to my app. I added `HorizontalDragDetector` to my game but drag is not detected. It seems it doesn't work if `HasTapableComponents` is there.

Example code: 
https://github.com/daisy1754/flame/commit/7e3c95cf418714d6eec6d355fd8d7503f5be40e2

Is this bug or intended behaviour? https://flame-engine.org/docs/input.md says "Many of these detectors can conflict with each other" but it doesn't mention specifics nor there is no documentation on  `HorizontalDragDetector` mixin code. 
If this is intended behaviour, it would be great if I can get
1) documentation around what would conflict with what 
2) guidance on how to implement swipe detection on existing game with `HasTapableComponents`

## Development environment

Flame version: 0.27.0

## Runtime

I tested with ios simulator

## Minimal reproducible code (Required for bugs)

https://github.com/daisy1754/flame/commit/7e3c95cf418714d6eec6d355fd8d7503f5be40e2

**Comment by erickzanardo** [comment]
`HasTapableComponents ` Makes uses of "advanced" detectors, `HorizontalDragDetector` is a "basic" detector, when mixing advanced and basic detectors, only the advanced will work. To have drag support on your game, together with the tapable components, you will need to use `MultiTouchDragDetector` instead.

**Comment by daisy1754** [comment]
@erickzanardo is there a way to know which ones are advanced and which ones are basic?

**Comment by erickzanardo** [comment]
Yeah, basically all the ones who has MultiTouch prefix are advanced, here you can find some better explanation: https://flame-engine.org/docs/input.md#touch-and-mouse-detectors

**Comment by daisy1754** [comment]
hm but I guess the fact that `HasTapableComponents` uses advanced detector is not very clear. If you want to implement basic touch functionality to your app you would use `HasTapableComponents` so I assume most of people use advanced detectors without knowing it

**Comment by erickzanardo** [comment]
> hm but I guess the fact that `HasTapableComponents` uses advanced detector is not very clear. If you want to implement basic touch functionality to your app you would use `HasTapableComponents` so I assume most of people use advanced detectors without knowing it

You are correct, this is not very clear on our docs. I have assembled a PR to fix that for v1. Thanks for bringing this to our attention.

**Comment by spydon** [comment]
I guess we can close this now, right @erickzanardo?
