### ISSUE TITLE
The percentage of PositionComponentEffect is null

### ISSUE THREAD

**Issue by LBXjixiangniao** [flame-engine/flame#516]
## Description

'package:flutter/src/animation/curves.dart': Failed assertion: line 36 pos 12: 't != null': is not true.

## Minimal reproducible code (Required for bugs)
For a PositionComponent, add an PositionComponentEffect and remove immediately，then when PositionComponentEffect update ,the percent for curve is null.
final double c = curve?.transform(percentage) ?? 1.0;

**Comment by spydon** [comment]
We have a big rewrite of the effects system for v1.0.0, it will be released with the next RC and this bug should be fixed.
