### ISSUE TITLE
Util.addGestureDetector is deprecated

### ISSUE THREAD

**Issue by joaopehen98** [flame-engine/flame#521]
## Description

I'm starting to develop games with flame, but I'm facing this problem described above when I try to add a detector to receive the touches made to the screen. I already tried to downgrade my flame version, which ended that problem, but caused another one that prevented me from running the program. The android studio says I should try to use an equivalent to the addGestureDetector in the Game class in order to solve this, but this class doesn't seen to have any function related to that. What should I do?

## Development environment

Flame version: 0.28.0

Flutter doctor:

```
 Include your flutter doctor output here
[√] Flutter (Channel stable, 1.22.3, on Microsoft Windows [versÃ£o 10.0.18363.1139], locale pt-BR)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Android Studio (version 4.0)

```

## Runtime

This issue is related to running on which platform? (Select all that apply)

 - [x ] Android :android:
 - [ ] iOS :apple:
 - [ ] Web :browser:

## Minimal reproducible code (Required for bugs)

 Util flameUtil = Util();
  flameUtil.fullScreen();
  flameUtil.setOrientation(DeviceOrientation.portraitUp);

  LangawGame game = LangawGame();
  runApp(game.widget);
  TapGestureRecognizer tapper = TapGestureRecognizer();
  tapper.onTapDown = game.onTapDown;
  flameUtil.addGestureRecognizer(tapper); (this part is deprecated)

**Comment by erickzanardo** [comment]
That API is deprecated, you can still use it, but on future versions it will be removed. You can find the new API and an example on how to use on the site: https://flame-engine.org/docs/input.md#example

**Comment by joaopehen98** [comment]
Thank you, very much! Orgulho de brasileiros tendo sucesso!

**Comment by erickzanardo** [comment]
🇧🇷🇧🇷🇧🇷🎉🎉🎉
