### ISSUE TITLE
ComposedComponent will replace update method

### ISSUE THREAD

**Issue by CQZW** [flame-engine/flame#523]
## Description

//issues 1  mixin ComposedComponent will replace update method
class SomeCompoent extends PositionComponent
    with HasGameRef, Tapable, Resizable, ComposedComponent {
.....

  @override
  void render(Canvas canvas) {
//issues 2,if do not invoke prepareCanvas be myself,it SomeCompoent can not be render, as some problem, //PositionComponent can not be render,,this may not a issues,it may be design as this.
    prepareCanvas(canvas);
    super.render(canvas);
  }
}
Above code ,the PositionComponent's update can not be invoke,so can not do some Effect,
i just copy ComposedComponent code ,rename it:
mixin ZWComposedComponent on Component, HasGameRef, Tapable {

...code from ComposedComponent

//rewrite  update like this,it works.....
  @override
  void update(double t) {
    super.update(t);   // <- key point.
//code from ComposedComponent -->
 _removeLater.forEach((c) => components.remove(c));
    _removeLater.clear();

    components.forEach((c) => c.update(t));
    components.removeWhere((c) => c.destroy());
//code from ComposedComponent <---
}

}

## Development environment

Flame version:
0.28.0 

Flutter doctor:

```
 Include your flutter doctor output here
```

## Runtime

This issue is related to running on which platform? (Select all that apply)

 - [ x] Android :android:
 - [ x] iOS :apple:
 - [ x] Web :browser:

## Minimal reproducible code (Required for bugs)

Include a minimal code that reproduces the problem add it inline using code block markdown, or a link to Github repository:

**Comment by luanpotter** [comment]
`ComposedComponent` has been removed on v1 precisely because of this sort of issue. Now every position component can have potentially have children.
