### ISSUE TITLE
Is it possible to change the particle system to support particle editors?

### ISSUE THREAD

**Issue by cuong0993** [flame-engine/flame#529]
Currently, particles are composed programmatically.  Is it possible to change the particle system to support a particle editor as other game engines? For example, https://pixijs.io/pixi-particles-editor/#.

**Comment by spydon** [comment]
It doesn't exist at the moment, but it is a good suggestion for a feature!
I don't think anyone will have time to look at it in the very near future, but you can always put up a PR yourself if you want to contribute.
