### ISSUE TITLE
[1.0.0] Update examples

### ISSUE THREAD

**Issue by spydon** [flame-engine/flame#568]
This is the state of the examples for v1.0.0, compiled by @oboingo (xx_light_xx on Discord), some needs fixing and others work fine already.

## Examples (- [x] = working)

- [x] animations
        Works on android, web
- [x] asesprite
        Fails on web: sprite_animation.dart, line 167
        Error: Expected a value of type 'Map<String, Map<String, dynamic>>', but got one of type '_JsonMap'
        Fails on android: sprite_animation.dart, line 167_Cast
        Error (type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Map<String, Map<String, dynamic>>' in type cast)
- [x] debug
        Works on android, web
- [x] gestures
       Works on android, web
- [ ] go_desktop
       Works poorly on android, very slow
       Works on web
       Didn't test on fuchsia
- [ ] isometric
       Works on android, but is really off center, so you can only see a few tiles
       Works on web
- [ ] joystick
       Can't figure out what it is supposed to do on android or web, just a white square in the upper left corner
- [ ] keyboard
       Works poorly on android, very slow
       Works on web
- [ ] layers
       Works on android
       Does not work on web, processors.dart, line 26, Error: UnimplementedError
       Side note, Layers do not work on 0.28.x either
- [x] nine_tile_box
       Works on android, web
- [x] parallax
       Works on android, web
- [ ] particles
       Doesn't work on android or web, assertation failed in curves.dart
       "parametric value 1.0008000000000012 is outside of [0, 1] range."
- [x] render_flip
       Works on android, web
- [ ] sprite_batch
       Works on android
       Does not work on web: sprite_batch.dart, line 73
       Error: UnimplementedErrorspritesWorks on android,
- [x] webspritesheet
       Works on android, web
- [x] text
       Works on android, web
- [x] timer
       Works on android, web
- [x] widgets
       Works on android, web
- [x] with_widgets_overlay
       Works on android, web
### Effects
- [x]     simple
            scale works on android, web
            rotate works on android, web
            move works on android, web
- [x]     combined
            works on android, web
- [x]     sequence
            works on android, web
- [ ]     infinite
            Works on android, web, ... but a second tap crashes, from the update on the ComponentEffect

**Comment by erickzanardo** [comment]
Since FDE has evolved a lot, maybe we could just drop `go_desktop`?

**Comment by spydon** [comment]
We should add an example with priority too, I realized that we didn't have that (or docs about it) today when someone on discord asked.

**Comment by erickzanardo** [comment]
@spydon we have done a lot of work on examples, I wonder if we need to keep this open, what do you think?

**Comment by spydon** [comment]
Agree, probably time to close it
