### ISSUE TITLE
override method missing from component and it's not documented, Don't know how to use it

### ISSUE THREAD

**Issue by jefrisingh** [flame-engine/flame#582]
## Description

destroy method misson on component

## Development environment

Flame version: ^1.0.0-rc3

Flutter doctor:

[✓] Flutter (Channel dev, 1.25.0-8.0.pre, on Linux, locale en_IN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ Android SDK file not found:
      /home/jefri/Android/Sdk/build-tools/30.0.3/aapt.
[✓] Chrome - develop for the web
[✗] Linux toolchain - develop for Linux desktop
    ✗ The lzma development library is required for Linux development.
      It is likely available from your distribution (e.g.: apt install
      liblzma-dev)
[!] Android Studio (not installed)
[✓] Connected device (2 available)

! Doctor found issues in 3 categories.

## Runtime

This issue is related to running on which platform? (Select all that apply)

 - [ ] Android :android:
 - [ ] iOS :apple:
 - [X] Web :browser:

## Minimal reproducible code (Required for bugs)

```
class Crate extends SpriteComponent with HasGameRef<MyGame>, Resizable {
  bool explode = false;

  Crate(Vector2 gameSize)
      : super.fromImage(
          Vector2.all(CRATE_SIZE),
          Flame.images.fromCache('crate.png'),
        ) {
    x = rnd.nextDouble() * (gameSize.x - CRATE_SIZE);
    y = 0.0;
  }

  @override
  void update(double dt) {
    super.update(dt);
    y += dt * SPEED;
  }

  @override //this overrides nothing, never called
  bool destroy() {
    if (explode) {
      return true;
    }
    if (y == null || gameSize == null) {
      return false;
    }
    final destroy = y >= gameSize.y + CRATE_SIZE / 2;
    if (destroy) {
      gameRef.points -= 20;
      //FlameAudio.play('miss.mp3');
    }
    return destroy;
  }
}
```

**Comment by spydon** [comment]
Hi,
it has been renamed to `bool shouldRemove` (not a function), so now you can either override it like this:
```dart
@override
bool get shoultRemove {
    if (explode) {
      return true;
    }
    if (y == null || gameSize == null) {
      return false;
    }
    final destroy = y >= gameSize.y + CRATE_SIZE / 2;
    if (destroy) {
      gameRef.points -= 20;
      //FlameAudio.play('miss.mp3');
    }
    return destroy;
}
```
or just do that check in `update()` and call `remove()` if it should be removed.

There is also a function called `onRemove()` which I suggest you override and put things like the audio which I can see that you have commented out there.

**Comment by jefrisingh** [comment]
It worked, thanks  +1:
