### ISSUE TITLE
Keyboard up event on hold

### ISSUE THREAD

**Issue by MrMuMu** [flame-engine/flame#584]
## Description

I press and hold without releasing keyboard key "A" for example, but I still receive `RawKeyUpEvent`

## Development environment

Flame version: 1.0.0-rc3

This issue is related to running on which platform? (Select all that apply)

 - [ ] Android :android: api 30 simulator

## Minimal reproducible code (Required for bugs)

`game.dart`
```
import 'package:flame/game.dart';
import 'package:flame/keyboard.dart';
import 'package:flutter/services.dart';

class Game extends BaseGame with KeyboardEvents {
  Game();

  @override
  void onKeyEvent(RawKeyEvent event) {
    if (event is RawKeyDownEvent) {
      print("down");
    } else if (event is RawKeyUpEvent) {
      print("up");
    }
  }
}
```

`main.dart`
```
import 'package:flame/game/game_widget.dart';
import 'package:flutter/material.dart';

import 'game.dart';

void main() {
  runApp(GameWidget(game: Game()));
}
```

When you press and a button you should be seeing it printing both "up" and "down" like the following image
![image](https://user-images.githubusercontent.com/11612804/102719459-57ad4900-42ff-11eb-9be1-eb334a514669.png)

[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.18363.1256], locale en-US)
    • Flutter version 1.22.4
    • Framework revision 1aafb3a8b9 (5 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

**Comment by christopherfujino** [comment]
What Flutter version are you using? Sharing the output of `flutter doctor -v` would help.

**Comment by MrMuMu** [comment]
updated

**Comment by erickzanardo** [comment]
I have isolated this on a flutter app, without Flame, and the problem seems to originate on Flutter, I have opened an issue on the Flutter repository: https://github.com/flutter/flutter/issues/72816

**Comment by erickzanardo** [comment]
I did a bunch of investigation on this and it turns out that this is a problem with Android Emulators, when using a real device, the events work as expected, more info can be found on the issue linked on my previous comment.
