### ISSUE TITLE
Flame does not run on 1.25.0-8.1.pre: GameRenderBox class does not implement "computeDryLayout".

### ISSUE THREAD

**Issue by kickwaxapps** [flame-engine/flame#586]
## Description

Flutter 1.25.0-8.1.pre does not work nicely with Flame:

The following assertion was thrown during performResize():
The GameRenderBox class does not implement "computeDryLayout".

## Development environment

Flame version:
  flame: ^0.28.0

Flutter doctor:

```
jbc@jbc-a:~/sandbox/fisrv$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.25.0-8.1.pre, on Linux, locale en_CA.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
[✓] Connected device (1 available)

```

## Runtime

This issue is related to running on which platform? (Select all that apply)

 - [ ] Android :android:
 - [ ] iOS :apple:
 - [X ] Web :browser:

## Minimal reproducible code (Required for bugs)

void main() async {
  final anyFlame  =   AnyFlame();
  runApp(rv.widget(anyFlame.widget);

}

**Comment by spydon** [comment]
This is not in Flutter stable yet unfortunately, #552 is the PR with the fix on it.
We are considering adding this before it has reached stable due to the amount of people it affects.
