### ISSUE TITLE
Improve `JoystickAction.update` logic

### ISSUE THREAD

**Issue by lig** [flame-engine/flame#606]
existing code, but this could be:

```dart
final nextPoint = Vector2(nextX, nextY);
// ...
final Offset diff = _rectBackgroundDirection.center.toVector2() + nextPoint - _rectAction.center;
_rectAction = _rectAction.shift(diff.toOffset());
```

_Originally posted by @luanpotter in https://github.com/flame-engine/flame/pull/603#discussion_r551152386_

**Comment by lig** [comment]
Feel free to assign to me

**Comment by spydon** [comment]
This is not related to #595 right?

**Comment by lig** [comment]
> This is not related to #595 right?

I'm not sure yet as I'm not that familiar with the code. I will try to reproduce the test provided in #595 before and after the change.

**Comment by wolfenrain** [comment]
> This is not related to #595 right?

I don't think it is, the code functionality did not change, only the way it is written.
