### ISSUE TITLE
how to flip a sprite？

### ISSUE THREAD

**Issue by dreamfly32** [flame-engine/flame#615]
![image](https://user-images.githubusercontent.com/32086491/103871723-6457dc80-5108-11eb-9fdc-33a9e4e34921.png)
![image](https://user-images.githubusercontent.com/32086491/103871786-746fbc00-5108-11eb-9ff8-cdd63f8b9009.png)

I use DynamicLayer to make the explosion effect, but I only have one picture. How do I rotate a sprite ？ As shown in the picture, it should face down. I tried add AnimationComponent, but the drawing speed is too slow and the animation is inconsistent。

My DynamicLayer code is as follows：

![image](https://user-images.githubusercontent.com/32086491/103872025-c6184680-5108-11eb-8463-17741f82cd84.png)

**Comment by dreamfly32** [comment]
![image](https://user-images.githubusercontent.com/32086491/103872255-1e4f4880-5109-11eb-9f20-9ea31f693739.png)

**Comment by HarrisonQi** [comment]
try this:

```dart
import 'package:flame/flame.dart';
import 'package:flame/game/game.dart';
import 'package:flame/sprite.dart';
import 'package:flame/util.dart';
import 'package:flutter/material.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  Util flameUtil = Util();
  await flameUtil.fullScreen();
  final screenSize = await Flame.util.initialDimensions();

  final myGame = MyGame(screenSize);

  runApp(myGame.widget);
}

class MyGame extends Game {
  Size screenSize;
  Sprite sprite1;

  Sprite sprite2;

  MyGame(Size size) {
    screenSize = size;
    sprite1 = Sprite("派大星.gif");
    sprite2 = Sprite("派大星.gif");
  }

  @override
  void render(Canvas c) {
    // 背景图
    Rect backgroundRect =
        Rect.fromLTWH(0.0, 0.0, screenSize.width, screenSize.height);
    Paint backgroundPaint = Paint()..color = Color(0xff0077b6);
    c.drawRect(backgroundRect, backgroundPaint);
    c.save();
    
    // 正常的图片
    c.translate(screenSize.width / 2, screenSize.height);
    c.translate(-150, -600);
    sprite1.renderRect(c, Rect.fromLTWH(0, 0, 300, 150));
    c.save();

    // 翻转后的图片
    c.translate(screenSize.width / 2, screenSize.height);
    c.scale(-1, 1);
    c.translate(-100, -300);
    sprite2.renderRect(c, Rect.fromLTWH(0, 0, 300, 150));
    c.save();
  }

  @override
  void update(double t) {}
}
```

If use `PositionComponent`, try to change `renderFlipX` and `renderFlipY`

**Comment by dreamfly32** [comment]
@HarrisonQi 首先感谢你的回复。
renderFlipY我试过，可以旋转，但是会导致动画不一致，不知道是不是我写的问题
![image](https://user-images.githubusercontent.com/32086491/103873337-9c601f00-510a-11eb-8992-8ed7fbdff85c.png)
![image](https://user-images.githubusercontent.com/32086491/103873410-b437a300-510a-11eb-9fdd-72664881b961.png)

**Comment by dinoandcat** [comment]
In the `SpriteComponent` or other Component which is extends  `PositionComponent`, you can use the `renderFlipX` and `renderFlipY` to flip the Sprite and user the angle can rotate the Srpite.
在 `SpriteComponent` 或继承了`PositionComponent`的组件中,可以使用`renderFlipX`和`renderFlipY`属性来翻转图片,使用`angle`可以旋转图片.

**Comment by erickzanardo** [comment]
@dreamfly32 the advice received here solved your issue? Can we close this now?

**Comment by erickzanardo** [comment]
Closing due inactivity
