### ISSUE TITLE
Chain bgm plays

### ISSUE THREAD

**Issue by dominichamon** [flame-engine/flame#617]
## Description

I'm trying to chain two mp3s together so there's an intro and then a loop. I have tried:

```
    Flame.bgm.play("main_menu_intro.mp3").whenComplete(() {
      Flame.bgm.play("main_menu_loop.mp3");
    });
```

and (in case there are assumptions in the bgm code):

```
    Flame.audio.play("main_menu_intro.mp3").whenComplete(() {
      Flame.bgm.play("main_menu_loop.mp3");
    });
```

In either case on Android I get no audio but I do get errors:

```
E/MediaPlayerNative( 4932): pause called in state 4, mPlayer(0xe9110bc0)
E/MediaPlayerNative( 4932): error (-38, 0)
E/MediaPlayerNative( 4932): Attempt to perform seekTo in wrong state: mPlayer=0xe9110bc0, mCurrentState=0
E/MediaPlayerNative( 4932): error (-38, 0)
E/MediaPlayer( 4932): Error (-38,0)
E/MediaPlayer( 4932): Error (-38,0)
E/MediaPlayerNative( 4932): pause called in state 4, mPlayer(0xbeaff520)
E/MediaPlayerNative( 4932): error (-38, 0)
E/MediaPlayerNative( 4932): Attempt to perform seekTo in wrong state: mPlayer=0xbeaff520, mCurrentState=0
E/MediaPlayerNative( 4932): error (-38, 0)
E/MediaPlayer( 4932): Error (-38,0)
E/MediaPlayer( 4932): Error (-38,0)
```

on iOS I get audio, but i get both loops playing simultaneously, so it seems the "whenComplete" isn't when the loop ends on iOS at least.

Is there a way to do what i want? essentially play an mp3 and then start a loop right after it?

## Development environment

Flame version: 0.28.0

Flutter doctor:

```
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H114 darwin-x64, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.52.1)
[✓] Connected device (1 available)

• No issues found!

```

## Runtime

This issue is related to running on which platform? (Select all that apply)

 - [ X] Android :android:
 - [ X] iOS :apple:
 - [ untested] Web :browser:

## Minimal reproducible code (Required for bugs)

Include a minimal code that reproduces the problem add it inline using code block markdown, or a link to Github repository:

See above.

**Comment by erickzanardo** [comment]
The completion of the Future don't mean that the sound or music has ended, that future will return you an instance of AudioPlayer, which you could use to set listeners which will be called when the playing is completed, more here: https://github.com/luanpotter/audioplayers#completion-event
