### ISSUE TITLE
Little spaces between rectangles drawn on canvas

### ISSUE THREAD

**Issue by FelixBruebach** [flame-engine/flame#637]
## Description

I want to make a tile based game. Depending of their position there are little spaces between the rectangles I draw on the canvas.

![image](https://user-images.githubusercontent.com/41200990/105064849-87c24600-5a7d-11eb-859b-a673be80d05b.png)

## Development environment

Flame version:

flame: ^0.28.0

Flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.23.0-18.1.pre, on Microsoft Windows [Version 10.0.18363.1316], locale de-DE)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
[√] VS Code (version 1.52.1)
[√] Connected device (4 available)

• No issues found!
```

## Runtime

This issue is related to running on which platform? (Select all that apply)

 - [x] Android :android:
 - [?] iOS :apple:
 - [x] Web :browser:

## Minimal reproducible code (Required for bugs)

```
import 'dart:ui';

import 'package:flame/game/game.dart';
import 'package:flutter/material.dart';

main() => runApp(SimpleGame().widget);

class SimpleGame extends Game {
  double tileSize = 16;
  int tilesInX = 10;
  int tilesInY = 10;
  Paint paint = Paint()..color = Colors.blue;

  @override
  void render(Canvas canvas) {
    canvas.translate(1, 1); // if you remove this the spaces disappear
    for (int x = 0; x < tilesInX; x++) {
      for (int y = 0; y < tilesInY; y++) {
        canvas.drawRect(
          Rect.fromLTWH(x * tileSize, y * tileSize, tileSize, tileSize),
          paint,
        );
      }
    }
  }

  @override
  void update(double t) {
    // TODO: implement update
  }
}
```

**Comment by rundun** [comment]
@FelixBruebach maybe im not understanding your question.  But if you read the comments in your render method.

`canvas.translate(1, 1); // if you remove this the spaces disappear`

I ran the code like this :
```
@override
  void render(Canvas canvas) {
    // canvas.translate(1, 1); // if you remove this the spaces disappear
    for (int x = 0; x < tilesInX; x++) {
      for (int y = 0; y < tilesInY; y++) {
        canvas.drawRect(
          Rect.fromLTWH(x * tileSize, y * tileSize, tileSize, tileSize),
          paint,
        );
      }
    }
  }
```
And the spaces between the squares were removed.

Please could you specify what the actual problem you are trying to solve is?

**Comment by FelixBruebach** [comment]
@rundun I am well aware of the fact that removing the translation operation "removes the issue" (I wrote that comment). But in my opinion I shouldn't have to remove the translation in order to fix the issue. The translation is just one way to reproduce this issue. I encountered this issue when drawing a grid of tiles at float positions.

**Comment by spydon** [comment]
I would guess that this is due to rounding errors.
This doesn't really have anything to do with Flame, since you are just using the canvas to draw the tiles here.
Could be something like this: https://stackoverflow.com/questions/9942209/unwanted-lines-appearing-in-html5-canvas-using-tiles

I'll close this since it isn't flame-related, but feel free to share any conclusions that you come to here anyways.
