### ISSUE TITLE
showing this error while trying to run the app on device

### ISSUE THREAD

**Issue by akashlilhare** [flame-engine/flame#641]
/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flame-0.15.2/lib/flame.dart:62:7: Error: The non-abstract class 'FlameBiding' is missing implementations for these members:
 - _FlameBiding&BindingBase&GestureBinding with ServicesBinding.SchedulerBinding.addPersistentFrameCallback
 - _FlameBiding&BindingBase&GestureBinding with ServicesBinding.SchedulerBinding.addPostFrameCallback
 - _FlameBiding&BindingBase&GestureBinding with ServicesBinding.SchedulerBinding.addTimingsCallback
 - _FlameBiding&BindingBase&GestureBinding with ServicesBinding.SchedulerBinding.cancelFrameCallbackWithId
 - _FlameBiding&BindingBase&GestureBinding with ServicesBinding.SchedulerBinding.currentFrameTimeStamp
 - _FlameBiding&BindingBase&GestureBinding with ServicesBinding.SchedulerBinding.currentSystemFrameTimeStamp
 - _FlameBiding&BindingBase&GestureBinding with ServicesBinding.SchedulerBinding.debugAssertNoTransientCallbacks
 - _FlameBiding&BindingBase&GestureBinding with ServicesBinding.SchedulerBinding.endOfFrame
 - _FlameBiding&BindingBase&GestureBinding with ServicesBinding.SchedulerBinding.ensureFrameCallbacksRegistered
 - _FlameBiding&BindingBase&GestureBinding with ServicesBinding.SchedulerBinding.ensureVisualUpdate
 - _FlameBiding&BindingBase&GestureBinding with ServicesBinding.SchedulerBinding.framesEnabled
 - _FlameBiding&BindingBase&GestureBinding with ServicesBinding.SchedulerBinding.handleAppLifecycleStateChanged
 - _FlameBiding&BindingBase&GestureBinding with ServicesBinding.SchedulerBinding.handleBeginFrame
 - _FlameBiding&BindingBase&GestureBinding with ServicesBinding.SchedulerBinding.handleDrawFrame
 - _FlameBiding&BindingBase&GestureBinding with ServicesBinding.SchedulerBinding.handleEventLoopCallback
 - _FlameBiding&BindingBase&GestureBinding with ServicesBinding.SchedulerBinding.hasScheduledFrame
 - _FlameBiding&BindingBase&GestureBinding with ServicesBinding.SchedulerBinding.lifecycleState
 - _FlameBiding&BindingBase&GestureBinding with ServicesBinding.SchedulerBinding.removeTimingsCallback
 - _FlameBiding&BindingBase&GestureBinding with ServicesBinding.SchedulerBinding.resetEpoch
 - _FlameBiding&BindingBase&GestureBinding with ServicesBinding.SchedulerBinding.scheduleForcedFrame
 - _FlameBiding&BindingBase&GestureBinding with ServicesBinding.SchedulerBinding.scheduleFrame
 - _FlameBiding&BindingBase&GestureBinding with ServicesBinding.SchedulerBinding.scheduleFrameCallback
 - _FlameBiding&BindingBase&GestureBinding with ServicesBinding.SchedulerBinding.scheduleTask
 - _FlameBiding&BindingBase&GestureBinding with ServicesBinding.SchedulerBinding.scheduleWarmUpFrame
 - _FlameBiding&BindingBase&GestureBinding with ServicesBinding.SchedulerBinding.schedulerPhase
 - _FlameBiding&BindingBase&GestureBinding with ServicesBinding.SchedulerBinding.schedulingStrategy
 - _FlameBiding&BindingBase&GestureBinding with ServicesBinding.SchedulerBinding.schedulingStrategy=
 - _FlameBiding&BindingBase&GestureBinding with ServicesBinding.SchedulerBinding.transientCallbackCount
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class FlameBiding extends BindingBase with GestureBinding, ServicesBinding {
      ^^^^^^^^^^^
/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flame-0.15.2/lib/flame.dart:62:7: Context: 'BindingBase with GestureBinding with ServicesBinding.SchedulerBinding.addPersistentFrameCallback' is defined here.
class FlameBiding extends BindingBase with GestureBinding, ServicesBinding {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flame-0.15.2/lib/flame.dart:62:7: Context: 'BindingBase with GestureBinding with ServicesBinding.SchedulerBinding.addPostFrameCallback' is defined here.
class FlameBiding extends BindingBase with GestureBinding, ServicesBinding {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flame-0.15.2/lib/flame.dart:62:7: Context: 'BindingBase with GestureBinding with ServicesBinding.SchedulerBinding.addTimingsCallback' is defined here.
class FlameBiding extends BindingBase with GestureBinding, ServicesBinding {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flame-0.15.2/lib/flame.dart:62:7: Context: 'BindingBase with GestureBinding with ServicesBinding.SchedulerBinding.cancelFrameCallbackWithId' is defined here.
class FlameBiding extends BindingBase with GestureBinding, ServicesBinding {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flame-0.15.2/lib/flame.dart:62:7: Context: 'BindingBase with GestureBinding with ServicesBinding.SchedulerBinding.currentFrameTimeStamp' is defined here.
class FlameBiding extends BindingBase with GestureBinding, ServicesBinding {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flame-0.15.2/lib/flame.dart:62:7: Context: 'BindingBase with GestureBinding with ServicesBinding.SchedulerBinding.currentSystemFrameTimeStamp' is defined here.
class FlameBiding extends BindingBase with GestureBinding, ServicesBinding {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flame-0.15.2/lib/flame.dart:62:7: Context: 'BindingBase with GestureBinding with ServicesBinding.SchedulerBinding.debugAssertNoTransientCallbacks' is defined here.
class FlameBiding extends BindingBase with GestureBinding, ServicesBinding {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flame-0.15.2/lib/flame.dart:62:7: Context: 'BindingBase with GestureBinding with ServicesBinding.SchedulerBinding.endOfFrame' is defined here.
class FlameBiding extends BindingBase with GestureBinding, ServicesBinding {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flame-0.15.2/lib/flame.dart:62:7: Context: 'BindingBase with GestureBinding with ServicesBinding.SchedulerBinding.ensureFrameCallbacksRegistered' is defined here.
class FlameBiding extends BindingBase with GestureBinding, ServicesBinding {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flame-0.15.2/lib/flame.dart:62:7: Context: 'BindingBase with GestureBinding with ServicesBinding.SchedulerBinding.ensureVisualUpdate' is defined here.
class FlameBiding extends BindingBase with GestureBinding, ServicesBinding {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flame-0.15.2/lib/flame.dart:62:7: Context: 'BindingBase with GestureBinding with ServicesBinding.SchedulerBinding.framesEnabled' is defined here.
class FlameBiding extends BindingBase with GestureBinding, ServicesBinding {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flame-0.15.2/lib/flame.dart:62:7: Context: 'BindingBase with GestureBinding with ServicesBinding.SchedulerBinding.handleAppLifecycleStateChanged' is defined here.
class FlameBiding extends BindingBase with GestureBinding, ServicesBinding {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flame-0.15.2/lib/flame.dart:62:7: Context: 'BindingBase with GestureBinding with ServicesBinding.SchedulerBinding.handleBeginFrame' is defined here.
class FlameBiding extends BindingBase with GestureBinding, ServicesBinding {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flame-0.15.2/lib/flame.dart:62:7: Context: 'BindingBase with GestureBinding with ServicesBinding.SchedulerBinding.handleDrawFrame' is defined here.
class FlameBiding extends BindingBase with GestureBinding, ServicesBinding {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flame-0.15.2/lib/flame.dart:62:7: Context: 'BindingBase with GestureBinding with ServicesBinding.SchedulerBinding.handleEventLoopCallback' is defined here.
class FlameBiding extends BindingBase with GestureBinding, ServicesBinding {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flame-0.15.2/lib/flame.dart:62:7: Context: 'BindingBase with GestureBinding with ServicesBinding.SchedulerBinding.hasScheduledFrame' is defined here.
class FlameBiding extends BindingBase with GestureBinding, ServicesBinding {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flame-0.15.2/lib/flame.dart:62:7: Context: 'BindingBase with GestureBinding with ServicesBinding.SchedulerBinding.lifecycleState' is defined here.
class FlameBiding extends BindingBase with GestureBinding, ServicesBinding {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flame-0.15.2/lib/flame.dart:62:7: Context: 'BindingBase with GestureBinding with ServicesBinding.SchedulerBinding.removeTimingsCallback' is defined here.
class FlameBiding extends BindingBase with GestureBinding, ServicesBinding {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flame-0.15.2/lib/flame.dart:62:7: Context: 'BindingBase with GestureBinding with ServicesBinding.SchedulerBinding.resetEpoch' is defined here.
class FlameBiding extends BindingBase with GestureBinding, ServicesBinding {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flame-0.15.2/lib/flame.dart:62:7: Context: 'BindingBase with GestureBinding with ServicesBinding.SchedulerBinding.scheduleForcedFrame' is defined here.
class FlameBiding extends BindingBase with GestureBinding, ServicesBinding {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flame-0.15.2/lib/flame.dart:62:7: Context: 'BindingBase with GestureBinding with ServicesBinding.SchedulerBinding.scheduleFrame' is defined here.
class FlameBiding extends BindingBase with GestureBinding, ServicesBinding {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flame-0.15.2/lib/flame.dart:62:7: Context: 'BindingBase with GestureBinding with ServicesBinding.SchedulerBinding.scheduleFrameCallback' is defined here.
class FlameBiding extends BindingBase with GestureBinding, ServicesBinding {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flame-0.15.2/lib/flame.dart:62:7: Context: 'BindingBase with GestureBinding with ServicesBinding.SchedulerBinding.scheduleTask' is defined here.
class FlameBiding extends BindingBase with GestureBinding, ServicesBinding {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flame-0.15.2/lib/flame.dart:62:7: Context: 'BindingBase with GestureBinding with ServicesBinding.SchedulerBinding.scheduleWarmUpFrame' is defined here.
class FlameBiding extends BindingBase with GestureBinding, ServicesBinding {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flame-0.15.2/lib/flame.dart:62:7: Context: 'BindingBase with GestureBinding with ServicesBinding.SchedulerBinding.schedulerPhase' is defined here.
class FlameBiding extends BindingBase with GestureBinding, ServicesBinding {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flame-0.15.2/lib/flame.dart:62:7: Context: 'BindingBase with GestureBinding with ServicesBinding.SchedulerBinding.schedulingStrategy' is defined here.
class FlameBiding extends BindingBase with GestureBinding, ServicesBinding {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flame-0.15.2/lib/flame.dart:62:7: Context: 'BindingBase with GestureBinding with ServicesBinding.SchedulerBinding.schedulingStrategy=' is defined here.
class FlameBiding extends BindingBase with GestureBinding, ServicesBinding {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flame-0.15.2/lib/flame.dart:62:7: Context: 'BindingBase with GestureBinding with ServicesBinding.SchedulerBinding.transientCallbackCount' is defined here.
class FlameBiding extends BindingBase with GestureBinding, ServicesBinding {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flame-0.15.2/lib/flame.dart:62:7: Error: '_FlameBiding&BindingBase&GestureBinding' doesn't implement 'SchedulerBinding' so it can't be used with 'ServicesBinding'.
 - 'BindingBase with GestureBinding' is from 'package:flame/flame.dart' ('/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flame-0.15.2/lib/flame.dart').
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/C:/flutter/flutter/packages/flutter/lib/src/scheduler/binding.dart').
 - 'ServicesBinding' is from 'package:flutter/src/services/binding.dart' ('/C:/flutter/flutter/packages/flutter/lib/src/services/binding.dart').
class FlameBiding extends BindingBase with GestureBinding, ServicesBinding {
      ^
/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.14.4/lib/src/picture_stream.dart:92:3: Error: The superclass, 'Diagnosticable', has no unnamed constructor that takes no arguments.
  PictureStream();
  ^^^^^^^^^^^^^
/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.14.4/lib/src/picture_stream.dart:192:16: Error: The superclass, 'Diagnosticable', has no unnamed constructor that takes no arguments.
abstract class PictureStreamCompleter extends Diagnosticable {
               ^

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 904

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 21s
Exception: Gradle task assembleDebug failed with exit code 1
`
`

**Comment by spydon** [comment]
Hi, 
this is an extremely old version of flame, please use either `0.28.0` or `1.0.0-rc6`.

**Comment by akashlilhare** [comment]
After updating with the latest version it showing error while using  **ComposedComponent** mixin. How to solve that error.
I want to use **ComposedComponent** mixin as :


`class Horizon extends PositionComponent with Resizable, ComposedComponent {
...
...
}`

**Comment by spydon** [comment]
@akashlilhare you have to be more specific in your issues.
You have to post both the error that you get and code to reproduce it.
These kind of questions are much better suited for our [discord channel](https://discord.com/invite/pxrBmy4).
