### ISSUE TITLE
flutter pub get error

### ISSUE THREAD

**Issue by mulieli** [flame-engine/flame#648]
Because (project name) depends on flame ^0.29.0 which doesn't match any versions, version solving failed.
pub get failed (1; Because (project name) depends on flame ^0.29.0 which doesn't match any versions, version solving failed.)

**Comment by erickzanardo** [comment]
Cantou elaborate more on the problem, there isn't much info information here to work on.

0.29.0 is published as we can see here on pub https://pub.dev/packages/flame/versions/0.29.0

And please follow the issue template.

**Comment by mulieli** [comment]
> Can you elaborate more on the problem, there isn't much info information here to work on.
> 
> 0.29.0 is published as we can see here on pub https://pub.dev/packages/flame/versions/0.29.0
> 
> And please follow the issue template.

When I was using the flutter pub get library, the console prompted me an error

**Comment by mulieli** [comment]
> Can you elaborate more on the problem, there isn't much info information here to work on.
> 
> 0.29.0 is published as we can see here on pub https://pub.dev/packages/flame/versions/0.29.0
> 
> And please follow the issue template.

一个新建的项目，flutter 的版本是
![image](https://user-images.githubusercontent.com/24307960/106428858-90b30e80-64a4-11eb-8053-8fb210a8c293.png)

**Comment by erickzanardo** [comment]
Just to be sure I have just created a new project, used 0.29.0 and flutter pub get worked as expected, not sure why you are facing that issue but seems something local, try cleaning your flutter pub cache.
