### ISSUE TITLE
Tapable with angle change，it doesn't handle rotation

### ISSUE THREAD

**Issue by newPersonKing** [flame-engine/flame#649]
## Description

Wrong coordinate processing of angle rotation click event
```dart
class TapableSquare extends PositionComponent with Tapable {
  @override
  void onTapDown(TapDownDetails details) {
    angle += 1.0;
  }
}
```

I think `toRec`t is the area that responds to events, but it doesn't handle rotation

## Development environment

Flame version:

Flutter doctor:

```
 Include your flutter doctor output here
```

## Runtime

This issue is related to running on which platform? (Select all that apply)

 - [x] Android :android:
 - [ ] iOS :apple:
 - [ ] Web :browser:

## Minimal reproducible code (Required for bugs)

Include a minimal code that reproduces the problem add it inline using code block markdown, or a link to Github repository:

**Comment by spydon** [comment]
Hi,
Which Flame version are you running?

**Comment by newPersonKing** [comment]
0.29.0

**Comment by newPersonKing** [comment]
> Hi,
> Which Flame version are you running?

0.29.0

**Comment by spydon** [comment]
Right,it seems like the 0.x.0 branch doesn't support rotation.
You can upgrade to `v1.0.0-rc6` to get rotation and `Tapable` working properly.

**Comment by erickzanardo** [comment]
Closing this since this is fixed on v1. We advice for you to upgrade your flame version.
