### ISSUE TITLE
How can i listen onPointerDown,onPointerMove,onPointerUp,onPointerCancel event ?

### ISSUE THREAD

**Issue by songtao542** [flame-engine/flame#655]
I want to listen the pointer event. Can you provide a way to monitor pointer events?

**Comment by erickzanardo** [comment]
Flame already provides that, please look the docs and examples:

https://github.com/flame-engine/flame/tree/master/doc/examples/gestures/lib

https://github.com/flame-engine/flame/blob/master/doc/input.md#input
