### ISSUE TITLE
Zero sized component's containsPoint always return true

### ISSUE THREAD

**Issue by pedia** [flame-engine/flame#662]
## Description
Zero sized component's `containsPoint` always return true. Is this right? 

As test below:
```dart
test('zero size', () {
      final PositionComponent component = MyComponent();
      component.position = Vector2(2.0, 2.0);
      component.size = Vector2(0.0, 0.0);
      component.angle = 0.0;
      component.anchor = Anchor.center;

      final point = Vector2(3.0, 4.0);
      expect(component.containsPoint(point), false);
});
```

I think Point(3,4) is not in the component, `containsPoint` should return false.

but test failed as:
```
00:01 +0 -1: PositionComponent overlap test zero size [E]
  Expected: <false>
    Actual: <true>
```

## Development environment

Flame version: 1.0.0-rc6

Flutter doctor:

```
[✓] Flutter (Channel master, 1.27.0-2.0.pre.79, on macOS 11.0.1 20B50 darwin-x64, locale en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Community Edition (version 2019.1.3)
[✓] VS Code (version 1.53.2)
[✓] Connected device (2 available)

• No issues found!
```

## Runtime

This issue is related to running on which platform? (Select all that apply)

 - [✓] Android :android:
 - [✓] iOS :apple:
 - [✓] Web :browser:

## Minimal reproducible code (Required for bugs)

```dart
      final PositionComponent component = MyComponent();
      component.position = Vector2(2.0, 2.0);
      component.size = Vector2(0.0, 0.0);
      component.angle = 0.0;
      component.anchor = Anchor.center;

      final point = Vector2(3.0, 4.0);
      expect(component.containsPoint(point), false);
```

**Comment by spydon** [comment]
Good catch, thanks for reporting it!
I fixed it here now https://github.com/flame-engine/flame/pull/633/files#diff-9e66c4875dd208d36b553fdccbc6edaab29860cf826fdf18ecdd499431eb0e5cR109
The fix will be available in rc7

**Comment by erickzanardo** [comment]
> Good catch, thanks for reporting it!
> I fixed it here now https://github.com/flame-engine/flame/pull/633/files#diff-9e66c4875dd208d36b553fdccbc6edaab29860cf826fdf18ecdd499431eb0e5cR109
> The fix will be available in rc7

@spydon can we close this then?

**Comment by spydon** [comment]
> > Good catch, thanks for reporting it!
> > I fixed it here now https://github.com/flame-engine/flame/pull/633/files#diff-9e66c4875dd208d36b553fdccbc6edaab29860cf826fdf18ecdd499431eb0e5cR109
> > The fix will be available in rc7
> 
> @spydon can we close this then?

GitHub will automagically close it when the PR is merged.
