### ISSUE TITLE
Behavior of SpriteAnimationComponent.shouldRemove is much different with Component.shouldRemove?

### ISSUE THREAD

**Issue by pedia** [flame-engine/flame#663]
Normally we can remove a `Component` easily with `shouldRemove = true` or `remove()`, but this not worked in `SpriteAnimationComponent`.

I noticed SpriteAnimationComponent override `shouldRemove` as below:
```dart
class SpriteAnimationComponent {
  @override
  bool get shouldRemove => removeOnFinish && (animation?.isLastFrame ?? false);
}
```

I think it's better change to
```dart
bool get shouldRemove => removeOnFinish && (animation?.isLastFrame ?? false) || super.shouldRemove;
```
Is this right?

And this cause `BaseGame` bug: never remove a removeOnFinish=false `SpriteAnimationComponent`.

flame version: 1.0.0-rc6

Thanks

**Comment by spydon** [comment]
Sounds reasonable!
Do you want to make a PR with it? 
(Otherwise we'll fix it of course)

**Comment by pedia** [comment]
@spydon PR #666 fired and all passed. ;-)
