### ISSUE TITLE
Game.images and Flame.images are different instances

### ISSUE THREAD

**Issue by pedia** [flame-engine/flame#668]
I noticed `Game.images` and `Flame.images` are different instances and 
`Game.images` is not be able to change because marked as final.

Is this behavior right?

Library(flame) always use `Flame.images` in 7 times. 
Library user maybe preferred `gameRef.images` instead because of less file import.

```Dart
abstract class Game {
  final images = Images();
  final assets = AssetsCache();
}

class Flame {
  static AssetsCache assets = AssetsCache();

  static Images images = Images();
}
```

**Comment by erickzanardo** [comment]
We explain the diferente between the two instances on our docs, check it here for a better understanding: https://flame-engine.org/docs/#/images?id=flameimages

**Comment by pedia** [comment]
I understood.
Thanks your patient to explain it.
