### ISSUE TITLE
Support rotation canter is not geometric center?

### ISSUE THREAD

**Issue by pedia** [flame-engine/flame#674]
## Description

Set `Component.anchor` to `Anchor.center`, the rotation center is geometric center.
Rotation canter of Turrets on Tower always is not geometric center. The rotation is not desired.

## Development environment

Flame version: 1.0.0-rc6

Flutter doctor:

```
[✓] Flutter (Channel master, 1.27.0-2.0.pre.79, on macOS 11.0.1 20B50 darwin-x64, locale en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Community Edition (version 2019.1.3)
[✓] VS Code (version 1.53.2)
[✓] Connected device (2 available)

• No issues found!
```

## Runtime

This issue is related to running on which platform? (Select all that apply)

 - [✓] Android :android:
 - [✓] iOS :apple:
 - [✓] Web :browser:

## Minimal reproducible code (Required for bugs)

```dart
gun = SpriteComponent();
gun.anchor = Anchor.center;
gun.addEffect(RotateEffect(angle: 7, duration: 5));
```

**Comment by spydon** [comment]
Hi,
I don't understand what the issue is here, could you try to re-phrase it?
As far as I can see you set the anchor to the center, and it rotates around the center, what is your expected outcome?

**Comment by pedia** [comment]
Sorry for my poor english.
```txt
|-------|
|           |
|     A    |
|     B    |
|-------|
```
The turret's rotate center is B, but it rotate with A.

**Comment by spydon** [comment]
Aah, now I understand what you mean.
You don't want to use the predefined anchors, and set the anchor yourself?
Something like this right?
```dart
gun = SpriteComponent();
gun.anchor = Anchor(0.5, 0.7);
gun.addEffect(RotateEffect(angle: 7, duration: 5));
```
I'll write up a PR for that and see what the others think.
