### ISSUE TITLE
On the optimization of collidable and hascollidables aubot collide passively

### ISSUE THREAD

**Issue by au-top** [flame-engine/flame#689]
On the optimization of collidable and hascollidables,

In a game, there may be a large number of collidable instances that will not move actively but only collide passively. Can you add attr ``` activeCollision ``` of bool type to the collidable abstract class to judge whether they are active or not

,

And change the logic of collisiondetection

Decompose the collindables parameter into

```

  List<Collidable> activeCollisionList = [];
  List<Collidable> noActiveCollisionList = [];


  collidables.forEach((element) {
    if (element.activeCollision) {
      activeCollisionList.add(element);
    }else{
      noActiveCollisionList.add(element);
    }
  });

  List<Collidable> allCollisionList = [...activeCollisionList,...noActiveCollisionList];

```

And use

```
for (var x = 0; x < activeCollisionList.length ; x++) {

final collidableX = activeCollisionList[x];

for (var y = x+1; y < allCollisionList.length ; y++) {

final collidableY = allCollisionList[y];


```

Traverse

In some passive collidable scenes, the number of frames can be significantly increased

I have a crude code

**Comment by spydon** [comment]
Awesome to see a contribution to the collision detection code already, since it has only been out a few days!

**Comment by spydon** [comment]
This is now merged and will be released together with rc8, thanks for your contribution @au-top!
