### ISSUE TITLE
Consider making gameRef late in HasGameRef

### ISSUE THREAD

**Issue by luanpotter** [flame-engine/flame#706]
When I tried we had some issues with our testing framework. But now that we are ready for NS we should consider this carefully and make a change if necessary.

**Comment by renancaraujo** [comment]
This depends on what kind of error we want to be thrown when the customer tries to access `.gameRef `before components onload. Making it late, we would have a `LateInitializationError`. If that doesn't work for us and we want a custom error, we can make `.gameRef` a getter for a private nullable field and throw our custom error when this private field is null. 

Either way, `.gameRef` doesn't to be exposed as nullable.

**Comment by spydon** [comment]
Yeah, would be very nice to not expose it as nullable, since we now have to do `gameRef!` everywhere.

**Comment by luanpotter** [comment]
The error is not on flame side, but rather our own tests setup games in an incomplete manner which leads to the late init exception. I will take a look at this now if I can fix all the tests.

**Comment by luanpotter** [comment]
Fixed by #742
