### ISSUE TITLE
where have all the audio gone?

### ISSUE THREAD

**Issue by gnudles** [flame-engine/flame#713]
Flame.audio unit no longer there.
# Current bug behaviour

# Expected behaviour

# Steps to reproduce

# Flutter doctor output

```
Output of: flutter doctor -v
```

# More environment information

# Log information

```
Enter log information in this code block
```

# More information

**Comment by spydon** [comment]
It has moved out to a separate package: https://github.com/flame-engine/flame_audio/

**Comment by gnudles** [comment]
Great, thanks. could you please update the docs to reflect that change?
