### ISSUE TITLE
Possibility to set a package name for asset loading

### ISSUE THREAD

**Issue by GwaedGlas** [flame-engine/flame#715]
# Problem to solve
I have implemented my first game with flame in the last days. Because I want to divide this from the app where this should be integrated, I decided to handle the flame part in a separate package.
This guides to the problem, that the assets are always loaded from assets/images/ or assets/audios, which is leaking of the package name in the file path. So it is needed to have the images in the app, instead of the package, where the path is packages/myPackageName/assets/images.

# Proposal
Having the possibility to set a prefix for the assets. In this case it would be enough to set a packagename. So the prefix "packages/myPackageName" could be generated. 
This shouldn't be a static value, because of the possibility of implementing different games for a game collection app, where you have different packages.

**Comment by luanpotter** [comment]
Hey @GwaedGlas that is a good idea! In fact in flame audio (and audioplayers) I already made it configurable after a similar request. For flame itself, we have asset and images loading, and indeed those were still hardcoded (my bad).

Here is my proposed solution: https://github.com/flame-engine/flame/pull/741
What do you think?

**Comment by luanpotter** [comment]
Closing since the proposed PR was merged and relased.
