### ISSUE TITLE
SpriteAnimationComponent was removed prematurely

### ISSUE THREAD

**Issue by wenxiangjiang** [flame-engine/flame#727]
# Current bug behaviour

`SpriteAnimationComponent` was removed in the last frame immediately regardless of the `stepTime`.

```dart
@override
  bool get shouldRemove =>
      super.shouldRemove ||
      (removeOnFinish && (animation?.isLastFrame ?? false));
```

# Expected behaviour

I think `SpriteAnimationComponent` should be removed when `SpriteAnimation` is done.

```dart
@override
  bool get shouldRemove =>
      super.shouldRemove ||
      (removeOnFinish && (animation?.done() ?? false));
```

PS: `SpriteAnimationComponent` can never be automatically removed if `SpriteAnimation#loop` is true. Perhaps this is a breaking change.

# Steps to reproduce

# Flutter doctor output

```
Output of: flutter doctor -v
```

# More environment information

* Flame version: 1.0.0-rc8

# Log information

```
Enter log information in this code block
```

# More information

If my idea meets the needs, I'm interested in working on a PR for this.

**Comment by erickzanardo** [comment]
I think that makes sense, we should only remove the component when the animation is really done, not when it is on the last frame. Sounds like a good fix, if you are willing to work on this, it would be quite appreciated.
