### ISSUE TITLE
tutorials/1_basic_square/README.md version incompatible with paint()

### ISSUE THREAD

**Issue by mcpeakdb** [flame-engine/flame#753]
# Current bug behaviour
README.md states to use 1.0.0-rc8 version. I ran into issues with paint() until I tried using version 1.0.0-rc9

# Expected behaviour
Update README.md to reflect version change

# Steps to reproduce
Followed the tutorial with version 1.0.0-rc8, paint() does not compile

# Flutter doctor output
No issues found! exit code 0

**Comment by mcpeakdb** [comment]
apologies if this is labeled incorrectly as a bug, I am relatively new to open source contributions

**Comment by spydon** [comment]
Thanks for the report, do you want to contribute with a PR for it?
Could be a good thing to learn if you are new to open source contributions (and we'll guide you through it if you have any problems). :)
https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md

**Comment by mcpeakdb** [comment]
I will take a swing at it today, thank you!

**Comment by mcpeakdb** [comment]
thanks @spydon and @erickzanardo !
