### ISSUE TITLE
Basic suggestions to improve collision performance

### ISSUE THREAD

**Issue by camillo777** [flame-engine/flame#760]
# Problem to solve

Avoid unnecessary calculations in collision by eliminating not needed checks

# Proposal

1) allow to specify what specific object classes NOT to test for collision based on a tag or runtime type:
for example type ShotPlayer1 can collide with FlyingEnemy but not GroundEnemy, or ShotEnemy5 can collide with Player but not with other Enemies or only with Enemy4
I can filter in onCollision method to ignore specific collisions, but this is a waste of resources because they are tested anyway by the collision engine;
2) don't care about collision points if not interested: don't know if this will improve performance but maybe if a game is not interested in the exact touch points it can be specified with a check, and a simple overlap check can be made;
3) Broad phase like: calculate and save the higher distance of the hitbox from the center of the collider and perform a first check on the distance of the center of colliders, before doing math calculations to check for overlap; if the distance of the centers is higher then they do not overlap;

# More information

**Comment by spydon** [comment]
There are indeed a lot of improvements that can be made to the collision detection, the current implementation is quite naïve.

1. Do you have any suggestions of how this could be done in a performant way? Currently there is a simpler version of this with the `CollidableType`s.
2. I don't think this would be much of a performance gain.
3. A broad phase or a quad tree or something like that is the next step for making the collision detection more performant, but it is quite a large task so I don't know when it would be done. (Right now only the bounding boxes are first checked before the real collision detection is made)

Are you interested in contributing to any of these points?

**Comment by camillo777** [comment]
For point 1 I have implemented in the past with a simple hash list like this (not optimized code) using custom SpriteType tags.

class PairList<T> {
  List<String> l = [];
  String hash(T a, T b) => "${a.toString()}-${b.toString()}";
  bool contains(T a, T b) => l.contains(hash(a, b)) || l.contains(hash(b, a));
  void add(T a, T b) {
    if (!contains(a, b)) l.add(hash(a, b));
  }
  void clear() => l.clear();
}

PairList collisionFilter = PairList();

void addAllowedCollision(SpriteType a, SpriteType b) {
    collisionFilter.add(a,b);
}

bool isAllowedCollision(SpriteType a, SpriteType b) {
    return collisionFilter.contains(a,b);
}
