### ISSUE TITLE
Problems with ParallaxComponent

### ISSUE THREAD

**Issue by Vasilisk8** [flame-engine/flame#765]
1.
Calling the function 
`ParalaxComponent.parallax.currentOffset().setFrom(Vector2(0,0));`
only works for one layer
I expected that the recalculation would affect all layers, taking into account the multiplier

2.
I'm trying to make a character jump and that would work vertical scroll expect that when landing layers will be lined up in the original position, but this does not happen, there is some displacement.
```
@override
  void update(double dt) {
    paralaxComponent.parallax.baseVelocity.setFrom(player!.speed);
    super.update(dt);
  }
```
Since the player gains some speed after the jump, parallax gains the same speed, but when the player's speed becomes zero, parallax does not return to its original position. The documentation says that this should work correctly:
**ou can set the baseSpeed and layerDelta at any time, for example if your character jumps or your game speeds up.**

version flame 1.0.0-rc9

**Comment by spydon** [comment]
Hi, thanks for the report, not sure it is bug though.

1. `currentOffset` is meant as a getter and shouldn't be modified, we should update the docs regarding this. What is it that you want to achieve by changing it?
2. For your second question, you are potentially mixing up speeds and velocities here. A velocity is a speed with a direction, so after you have given it a bump upwards you need to do the same downwards once the player is starting to descend from its jump.

**Comment by spydon** [comment]
If you can present a small reproducible example where 2 happens you can post it here and we can investigate it more.

**Comment by spydon** [comment]
I'll close this due to inactivity, I'll open it again if we get in an example.

**Comment by Vasilisk8** [comment]
> Привет, спасибо за отчет, но не уверен, что это ошибка.
> 
> 1. `currentOffset`предназначен как получатель и не должен изменяться, мы должны обновить документацию по этому поводу. Чего вы хотите добиться, изменив его?
> 2. Что касается вашего второго вопроса, вы потенциально смешиваете здесь скорости и скорости. Скорость - это скорость с направлением, поэтому после того, как вы дали ей толчок вверх, вам нужно сделать то же самое вниз, когда игрок начинает спускаться после своего прыжка. У параллакса нет никакой базовой линии, к которой он возвращается, когда скорость равна нулю, он должен оставаться на том же уровне, что и в последний тик.

Hi, thank you for the answer, I apologize for the wait
1. I want to bring the position of the layers to some zero coordinate(when the player is on the ground)
2. In my code, I expect that this is exactly what happens, because the speed becomes like the player, i.e. if the player started moving from the top point to the ground, then the parallax should return to its original state, and it returns, but not to the end.

I understand correctly that the parallax component was conceived as something static, i.e. once configured, specified the speed and that's it?

**Comment by Vasilisk8** [comment]
> If you can present a small reproducible example where 2 happens you can post it here and we can investigate it more.

I'll try to do something

**Comment by Vasilisk8** [comment]
Class Player

`import 'dart:ui';

import 'package:flame/components.dart';
import 'package:flame/flame.dart';
import 'package:flame/sprite.dart';
import 'package:my_game/main.dart';

class Player extends SpriteAnimationComponent{
  
  final MyGame game;

  final double gravity = 1000;
  final double windage = -100;

  Vector2 speed = Vector2(0,0);

  Player(this.game){
    animation = SpriteAnimation.fromFrameData(
      Flame.images.fromCache('player.png'), 
      SpriteAnimationData.sequenced(
        textureSize: Vector2(80,80),
        amount: 2,
        stepTime: 0.1,
      )
    );
    size = Vector2(80,80);
  }

  @override
  void update(double dt) {

    super.update(dt);

    double localGravity = gravity * dt;
    double localWindage = windage * dt;

    if(position.y<0){
      speed.add(Vector2(localWindage,localGravity));
    }

    if(speed.x<0){
      speed.x = 0;
    }


    position+=(speed*dt);
    if(position.y>=0){
      speed = Vector2(0,0);
      position.y = 0;
    }
    
    
  }

  @override
  void render(Canvas canvas) {
    super.render(canvas);
  }

  void up(){
    speed.add(Vector2(500,-500));
  }

}`

Class Background 

`import 'dart:ui';

import 'package:flame/flame.dart';
import 'package:flutter/material.dart' as flutter;
import 'package:flame/components.dart';
import 'package:flame/parallax.dart';

class Background extends ParallaxComponent{

  Background(){
    List<ParallaxLayer> paralaxLayers = List<ParallaxLayer>.empty(growable: true);
    paralaxLayers.add(
      ParallaxLayer(
        ParallaxImage(
          Flame.images.fromCache('sun.png'),
          alignment: flutter.Alignment.bottomLeft,
          fill: LayerFill.none,
          repeat: flutter.ImageRepeat.repeatX
        ),
        velocityMultiplier: Vector2(1 * 2.0,1.0)
      )
    );
    paralaxLayers.add(
      ParallaxLayer(
        ParallaxImage(
          Flame.images.fromCache('earth.png'),
          alignment: flutter.Alignment.bottomLeft,
          fill: LayerFill.none,
          repeat: flutter.ImageRepeat.repeatX
        ),
        velocityMultiplier: Vector2(2 * 2.0,2.0)
      )
    );
    paralaxLayers.add(
      ParallaxLayer(
        ParallaxImage(
          Flame.images.fromCache('sky.png'),
          alignment: flutter.Alignment.bottomLeft,
          fill: LayerFill.none,
          repeat: flutter.ImageRepeat.repeatX
        ),
        velocityMultiplier: Vector2(3 * 2.0,3.0)
      )
    );
    parallax = Parallax(
      paralaxLayers,
      size,
      baseVelocity: Vector2(50, 0),
    );
  }
  
  @override
  void render(Canvas canvas) {
    super.render(canvas);
  }

}`

Main

`import 'dart:ui';

import 'package:flame/components.dart';
import 'package:flame/game.dart';
import 'package:flame/gestures.dart';
import 'package:flame/keyboard.dart';
import 'package:flame/palette.dart';
import 'package:my_game/background.dart';
import 'package:my_game/player.dart';
import 'package:flutter/material.dart' as flutter;
import 'package:flame/flame.dart';

main() async {
  flutter.runApp(
    GameWidget(
      game: MyGame(),
    ),
  );
}

class MyGame extends BaseGame with KeyboardEvents, TapDetector {
  Player? player;
  Background? background;
  bool running = true;
  static  final fpsTextConfig =  TextConfig (color :  BasicPalette .white.color);
  
  @override
  Future<void> onLoad() async {
    debugMode = true;
    await Flame.images.load('player.png');
    await Flame.images.load('sun.png');
    await Flame.images.load('sky.png');
    await Flame.images.load('earth.png');
    
    background = Background();
    player = Player(this);

    add(
      background!
    );

    add(
      player!
    );
    
  }

  @override
  void render(Canvas canvas) {
    super.render(canvas);
    final fpsCount = fps(120);
    fpsTextConfig.render(canvas, fpsCount.toString(), Vector2(0, 50));
  }

  @override
  void update(double dt) {
    
    background!.parallax!.baseVelocity.setFrom(player!.speed);
    super.update(dt);
  }

  @override
  void onKeyEvent(e) {
    player!.up();
  }

  @override
  void onTapUp(flutter.TapUpDetails details) {
    player!.up();
  }

}`
![1](https://user-images.githubusercontent.com/25765967/116469275-9b4e2b80-a87a-11eb-8467-1f7a459eaabc.png)
![2](https://user-images.githubusercontent.com/25765967/116469277-9be6c200-a87a-11eb-8b17-1dd274d03f17.png)
![3](https://user-images.githubusercontent.com/25765967/116469278-9c7f5880-a87a-11eb-8b0b-d74f4a6bb465.png)
![4](https://user-images.githubusercontent.com/25765967/116469279-9c7f5880-a87a-11eb-8500-bbc0f6934f1c.png)

**Comment by Vasilisk8** [comment]
> > If you can present a small reproducible example where 2 happens you can post it here and we can investigate it more.
> 
> I'll try to do something

I did something:)

**Comment by spydon** [comment]
So you want to reset it to how it was from the start?
That is not implemented today, but I'll try to get that in to rc10.

For now you could do something like this:
```dart
background!.parallax!.map((layer) => layer.currentOffset().setFrom(Vector2.zero()));
```

**Comment by spydon** [comment]
Or is it going down, but it doesn't go all the way down?
If that is the case you seem to be missing an update-tick, possibly due to the order of the updates in `DebugGame.update`.

**Comment by Vasilisk8** [comment]
> Значит, вы хотите вернуть все, как было с самого начала?
> Сегодня это не реализовано, но я постараюсь внести это в rc10.
> 
> А пока вы можете сделать что-то вроде этого:
> 
> ```dart
> фон ! .параллакс ! . map ((слой) => слой. currentOffset (). setFrom ( Vector2 . zero ()));
> ```

Not really, only the vertical should return to its original position

**Comment by Vasilisk8** [comment]
> Или он идет вниз, но не до конца?
> Если это так, похоже, вам не хватает флажка обновления, возможно, из-за порядка обновлений в `DebugGame.update`.
> Если вы суммируете скорость для каждого тика, получится ли ноль?



> Or is it going down, but it doesn't go all the way down?
> If that is the case you seem to be missing an update-tick, possibly due to the order of the updates in `DebugGame.update`.
> If you sum the speed for each tick, does it result in zero?

This part of the code should align vertically
```
if(position.y>=0){
      speed = Vector2(0,0);
      position.y = 0;
    }
```

**Comment by Vasilisk8** [comment]
> So you want to reset it to how it was from the start?
> That is not implemented today, but I'll try to get that in to rc10.
> 
> For now you could do something like this:
> 
> ```dart
> background!.parallax!.map((layer) => layer.currentOffset().setFrom(Vector2.zero()));
> ```

This does not work, so that the picture is updated, you need to call the resize
