### ISSUE TITLE
Proposal: Use impersonal tone on documentation

### ISSUE THREAD

**Issue by luanpotter** [flame-engine/flame#767]
I'm extracting this from our [styleguide PR](https://github.com/flame-engine/flame/pull/752), on behalf of @renancaraujo, because this was a contentious topic that we don't already follow. In order to go forward with the styleguide PR, we can merge it without this rule, and use this issue to discuss if we should add it and track progress to updating all our comments if we desire.

```
#### Use impersonal tone

Avoid using words such as "you", "ours" and "yours" on code documentation
```

**Comment by luanpotter** [comment]
I think @renancaraujo has started working on what would it take to add this rule in [this PR](https://github.com/flame-engine/flame/pull/757).

**Comment by st-pasha** [comment]
I found this great piece of advise in Flutter Style Guide (https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#use-the-passive-voice-recommend-do-not-require):

> Use the passive voice; recommend, do not require
> --------------------------
> Never use "you" or "we". Avoid the imperative voice. Avoid value judgements.
>
> Rather than telling someone to do something, use "Consider", as in “To obtain the foo, consider using [bar].”.
>
> In general, you don’t know who is reading the documentation or why. Someone could have inherited a terrible codebase and be reading our documentation to find out how to fix it; by saying "you should not do X" or "avoid Y" or "if you want Z", you will put the reader in a defensive state of mind when they find code that contradicts the documentation (after all, they inherited this codebase, who are we to say that they’re doing it wrong, it’s not their fault).

Here's my counts for **how many times this section fails to follow its own advice**:
- _Use the passive voice_: 6 times
- _Never use "you" or "we"_: 4 times
- _Avoid the imperative voice_: 3 times
- _Avoid value judgements_: 1 time
- _Rather than telling someone to do something, use "Consider"_: 4 times

So, I don't know what they were thinking when writing this, but it's certainly funny as hell.

Anyways, in reality Flutter Style Guide uses "you" / "we" / "our" over 250 times. They use active voice and imperative sentences all the time. And that's what all the manuals on technical writing actually recommend.

I'd vote to close this issue.

**Comment by spydon** [comment]
> Here's my counts for how many times this section fails to follow its own advice:

Hahaha that is hilarious 😂
If someone wants to go through our docs to do this the result would probably be good, but if nobody feels like doing it I think we can close this?
