### ISSUE TITLE
Problem with intersections of 2 shapes

### ISSUE THREAD

**Issue by wbeater** [flame-engine/flame#780]
# Current bug behaviour

Where: flame-1.0.0-rc9/lib/src/geometry/shape_intersections.dart
Method: 
Set<Vector2> intersect(
    Polygon polygonA,
    Polygon polygonB, {
    Rect? overlappingRect,
  })
The intesectionPoints return empty although 2 PositionComponent objects have HitboxShapes and overlapped.

# Expected behaviour

The method should returns non-empty set contains points when 2 PositionComponent object overlapped.

# Steps to reproduce
1. Add 2 PositionComponent objects to BaseGame
2. Add rectangle shape to both objects: addShape(HitboxRectangle(relation: Vector2(0.65, 0.25)));
3. Place 2 objects overlap each other.
4. Check intersection points in second component's update() method:
var intersect = gameRef.obj1.shapes[0].intersections(shapes[0]).length > 0;
The result should be true

# More environment information
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.18.3
  flame: ^1.0.0-rc9
  flame_audio: 0.1.0-rc5

# More information
The reason is because of this: flame-1.0.0-rc9/lib/src/geometry/polygon.dart:100

List<Vector2> hitbox() {
    // Use cached bounding vertices if state of the component hasn't changed
    if (!_cachedHitbox.isCacheValid([position, size, angle])) {
      ...
    }
    return _cachedHitbox.value!;
  }

The position value of shape always be Vector2(0, 0); size and angle were fixed values 
=> so that cache can not be invalidated

**Comment by spydon** [comment]
This should be fixed in #773

**Comment by spydon** [comment]
Fixed and released in rc10
