### ISSUE TITLE
support plist file sprite 

### ISSUE THREAD

**Issue by zhaoqp2010** [flame-engine/flame#781]
support plist file sprite

**Comment by erickzanardo** [comment]
Please, elaborate more on this, what is plist file sprite, is this a know sprite format? Without info there isn't much we can do.

**Comment by zhaoqp2010** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>frames</key>
        <dict>
            <key>1000_0_00000.png</key>
            <dict>
                <key>frame</key>
                <string>{{356,178},{50,94}}</string>
                <key>offset</key>
                <string>{5,54}</string>
                <key>rotated</key>
                <false/>
                <key>sourceColorRect</key>
                <string>{{236,155},{50,94}}</string>
                <key>sourceSize</key>
                <string>{512,512}</string>
            </dict>
            <key>1000_0_00001.png</key>
            <dict>
                <key>frame</key>
                <string>{{0,288},{48,122}}</string>
                <key>offset</key>
                <string>{3,43}</string>
                <key>rotated</key>
                <true/>
                <key>sourceColorRect</key>
                <string>{{235,152},{48,122}}</string>
                <key>sourceSize</key>
                <string>{512,512}</string>
            </dict>
            <key>1000_0_00002.png</key>

**Comment by erickzanardo** [comment]
Ok, that is an example. But is this a common standard? Is there some docs about this? Please, write an elaborated description.

**Comment by zhaoqp2010** [comment]
https://www.codeandweb.com/texturepacker     一般的2d游戏都是用这个软件设计精灵的，是非常普遍的方式，上面说的plist sprite就是用这个软件导出的

**Comment by zhaoqp2010** [comment]
原因是每个精灵的动作帧的尺寸是不一样的，目前引擎里的`SpriteAnimation.load(
        "player/knight_run.png",
        SpriteAnimationData.sequenced(
          amount: 6,
          stepTime: 0.1,
          textureSize: Vector2(16, 16),
        ),
      );`
这种固定的尺寸是无法满足开发要求的

**Comment by erickzanardo** [comment]
Please, use english.

**Comment by erickzanardo** [comment]
okay, after searching a little, I have discovered that texture packer supports exporting in plist in a specific format for cocos2d. Giving that this is an specific format for a game engine, I don't think we should support this format, what do you think @flame-engine/flame-colab ?

**Comment by spydon** [comment]
Agree, doesn't look like it is very widely used.

**Comment by erickzanardo** [comment]
Alright, closing this as this doesn't seems like something we would like to give support.

If anyone wants to implement this in an external package though, we would gladly link that package on [flame awesome](https://github.com/flame-engine/awesome-flame).

**Comment by zhaoqp2010** [comment]
i find  https://github.com/Brixto/flame_texturepacker

That's what I need      thank
