### ISSUE TITLE
Black background

### ISSUE THREAD

**Issue by Itrainlcincom** [flame-engine/flame#789]
# Current bug behaviour

Black background showed before my game.

# Expected behaviour

I want to remove black background.

# Steps to reproduce

Open game
Black background showed

# Flutter doctor output

```
Output of: flutter doctor -v
```

# More environment information

# Log information

```
Enter log information in this code block
```

# More information

**Comment by erickzanardo** [comment]
This isn't a bug, the black background is just the default color, you can change that by overriding the backgroundColor method on your Game class and return the desired color instead.
