### ISSUE TITLE
Update the audioplayers to 0.19.0

### ISSUE THREAD

**Issue by ale-getman** [flame-engine/flame#802]
# What could be improved
Update the audioplayers plugin to the latest version

# Why should this be improved
Because flame 0.29.4 depends on audioplayers ^0.18.3 and no versions of flame match >0.29.4 <0.30.0, flame ^0.29.4 requires audioplayers ^0.18.3.
So, because new_bg depends on both flame ^0.29.4 and audioplayers ^0.19.0, version solving failed.

# Any risks?
No risks expected

**Comment by luanpotter** [comment]
Note that the latest v1 rc + flame_audio already have AP v 0.19.x; I am not against launching a patch version for 0.29 but until then upgrading is an option as well :)

**Comment by erickzanardo** [comment]
@luanpotter will we release a patch for 0.x Flame?

**Comment by erickzanardo** [comment]
We just a couple of weeks away from the Flame v1 release, so the team decided to not release any more patches for the 0.x versions.

But If anybody really needs the patch though, lets us know on discord and we can open an exception.
