### ISSUE TITLE
joystick touch area moves with camera 

### ISSUE THREAD

**Issue by QiXi** [flame-engine/flame#811]
# Current bug behaviour
movement of the joystick does not work

# Steps to reproduce
insert a line of code:
`camera.followVector2(Vector2(100, 100));`
into the example:
flame/examples/lib/stories/controls/advanced_joystick.dart

# More environment information
* Flame version: 1.0.0-releasecandidate.11

**Comment by spydon** [comment]
Good find, this is indeed a bug.
Luckily we are in the works of refactoring the joystick component to be more aligned with the rest of the component system.

**Comment by luanpotter** [comment]
isHud=true is probably missing

**Comment by erickzanardo** [comment]
indeed, as a work around for now, you could extend the joystick component to maker isHud = true like Luan said. But this sure should be something default for that component

**Comment by erickzanardo** [comment]
@spydon is this fixed with the joystick refactor?

**Comment by QiXi** [comment]
I checked that this strange behavior no longer exists. I expected that the fix would take a long time, so I didn't waste time and wrote my own engine :)

**Comment by spydon** [comment]
> @spydon is this fixed with the joystick refactor?

It is fixed indeed. :)
