### ISSUE TITLE
textcomponent anchor is correct in rc9 but no effect in rc10 and rc11

### ISSUE THREAD

**Issue by tsehonkit** [flame-engine/flame#815]
# Current bug behaviour
 I used TextComponent in rc9 and anchor it correctly. But when I upgraded to rc10 or even rc11, the anchor method is no longer response. It always anchor at topleft. 

# Expected behaviour
 It should do anchor the position by the anchor setting method.

# Steps to reproduce

# Flutter doctor output

in rc9 I use the following code
    _playerHealth = TextComponent(
      'Health: 100%',
      position: Vector2(size.x - 10, 10),
      config: TextConfig(
        color: Colors.white,
        fontSize: 16,
      ),
    );
    _playerHealth.anchor = Anchor.topRight;

In rc10 and rc11 I used the following code
    _playerHealth = TextComponent(
      'Health: 100%',
      position: Vector2(size.x - 10, 10),
      textRenderer: TextPaint(
        config: TextPaintConfig(
          color: Colors.white,
          fontSize: 16,
        ),
      ),
    );
    _playerHealth.anchor = Anchor.topRight;
The 'Health: 100%' text component should anchor at the right top corner and the text anchored at top right position.
```
Output of: flutter doctor -v
C:\FlutterSDK\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version 10.0.19042.985], locale zh-HK)
    • Flutter version 2.2.0 at C:\FlutterSDK\flutter
    • Framework revision b22742018b (8 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\User\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\User\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31205.134
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code, 64-bit edition (version 1.55.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.985]
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 90.0.818.66

• No issues found!
Process finished with exit code 0
```

# More environment information

# Log information

```
Enter log information in this code block
```

# More information

**Comment by anleac** [comment]
+1, can repro with the sample app in RC 11

```
import 'package:flame/components.dart';
import 'package:flame/game.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(
    GameWidget(
      game: MyGame(),
    ),
  );
}

class MyGame extends BaseGame {
  @override
  Future<void> onLoad() async {
    add(
      TextComponent("Centered text", textRenderer: TextPaint(config: const TextPaintConfig(color: Colors.white)))
        ..anchor=Anchor.center
        ..x = size.x / 2
        ..y = 50,
    );
  }
}
```

And works in rc9 with the same code, except for the change to `TextComponent("Centered text", config: TextConfig(color: Colors.white))`.

**Comment by tsehonkit** [comment]
copied from 
2f2390f#diff-90d3c72bf35a566e143394cc5101f6d3384386c3826e1cda0d36ed7ddabf9c4fR49 

 void render(    Canvas canvas,    String text,    Vector2 position, {    Anchor anchor = Anchor.topLeft,  });

Is this code mean that it always align to topLeft no matter what you have changed the anchor?

**Comment by anleac** [comment]
@tsehonkit yes I believe so, you can see @spydon fix here: https://github.com/flame-engine/flame/pull/817/files - thanks for doing this!

**Comment by spydon** [comment]
No problem, thanks for reporting it!

**Comment by luanpotter** [comment]
@spydon that was actually the incorrect fix, but I addressed that in a followup PR. this should be completely fixed now on master :)
