### ISSUE TITLE
Documentation: Tutorials 1 and 2 are out of date

### ISSUE THREAD

**Issue by johndobsonUK** [flame-engine/flame#821]
The two tutorials call for the use of 'package:flame/game.dart' which Flutter 2.2.0 refuses to compile saying  'The library is legacy, and should not be imported into a null safe library.

**Comment by erickzanardo** [comment]
Unsure why you are seeing that issue. Both the tutorials and flame already uses null safe code, just to be sure I tested the code and it worked fine on flutter 2.2.0.

I wonder if you are trying to use flame 0.29.4? The tutorials are bound to flame v1, the latest being 1.0.0-releasecandidate.11

**Comment by johndobsonUK** [comment]
Exactly the reason, I’ using 0.29.4 as the latest version from pub.dev. Where would I get Version 1 from please

John

**Comment by erickzanardo** [comment]
It is on pub as well, it is listed as pre release as it hasn't been fully released yet.

https://pub.dev/packages/flame/versions/1.0.0-releasecandidate.11

Closing this as this isn't really an issue on Flame, but feel free to add addition comments if there is still doubts
