### ISSUE TITLE
Status bar issue on Android emulator when using Flame.device.fullScreen()

### ISSUE THREAD

**Issue by joshykautz** [flame-engine/flame#822]
# Current bug behaviour
_Note: This issue does **not** happen when I use a physical Android Google Pixel 4 device, only on Android emulator._

I am using the 1.0.0-releasecandidate.11.
When targeting the Android platform (Pixel 4 API 30 emulator) when using `Flame.device.fullScreen()`, the system UI overlay for the status bar is correctly removed from the screen, but the canvas underneath it does _not_ occupy the same space. I've attached screenshots to show what it looks like before and after using `Flame.device.fullScreen()`.

<img src="https://user-images.githubusercontent.com/17554471/119517057-e4d84c00-bd3c-11eb-9837-1ef59bf6cf67.png" width="389" height="820"><img src="https://user-images.githubusercontent.com/17554471/119517093-ed308700-bd3c-11eb-8839-27b04e59a64b.png" width="389" height="820">

# Expected behaviour
I would expect using `Flame.device.fullScreen()` to remove the system UI overlay status bar (and navigation bar) and _also_ have the canvas occupy the entire size of the screen - right now it does this for the navigation bar, but not the status bar.

# Steps to reproduce
I create a brand new vanilla Flutter 2.2.0 project, import the flame-engine package, and create a new game with `Flame.device.fullScreen()` in my main function; something like:

```
import 'package:flame/game.dart';
import 'package:flame/sprite.dart';
import 'package:flutter/material.dart';
import 'package:flame/flame.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Flame.device.fullScreen();

  runApp(
    GameWidget(
      game: MyGame(),
    ),
  );
}

class MyGame extends BaseGame {
  late Sprite audio;

  @override
  Future<void> onLoad() async {
    // Pre-Load Sprites to cache.
    var iconsSpriteSheet = await Flame.images.load('icons.png');

    audio = Sprite(
      iconsSpriteSheet,
      srcPosition: Vector2(24, 0),
      srcSize: Vector2(24, 24),
    );
  }

  @override
  void onResize(Vector2 canvasSize) {
    print(canvasSize.toString());
    super.onResize(canvasSize);
  }

  @override
  void render(Canvas canvas) {
    audio.render(canvas,
        position: Vector2(0, size.y - 24 * 2), size: Vector2(24, 24) * 2);
    super.render(canvas);
  }

  @override
  Color backgroundColor() => const Color(0xFFFFFFFF);
}
```

# Flutter doctor output
```
❯ flutter doctor -v
[√] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version 10.0.19043.985], locale en-US)
    • Flutter version 2.2.0 at C:\src\flutter
    • Framework revision b22742018b (11 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Josh\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code, 64-bit edition (version 1.56.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 90.0.4430.212   
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 90.0.818.66    

• No issues found!
```

# More environment information
* Flame version: 1.0.0-releasecandidate.11
* Platform affected: Android
* Platform version affected: Pixel 4, API 30.

# Log information
```
N/A
```

# More information
I'm happy to try out things to help resolve this issue - hopefully I've provided enough information to be at least slightly helpful. That's for providing the Flame game engine for all of us to use!

**Comment by spydon** [comment]
This is most likely a Flutter bug and not a Flame bug.
If you try to set fullscreen in a normal Flutter app, do you experience the same thing?

**Comment by joshykautz** [comment]
Ah, yes, this does appear to be the case. When I use `SystemChrome.setEnabledSystemUIOverlays([])` to hide the status bar / navigation bar (which I believe Flame uses as well) I experience the same behavior. So I agree, this isn't an issue with Flame.

**Comment by luanpotter** [comment]
Closing as it was agreed to be a Flutter bug; feel free to open an issue there and link to here.

**Comment by joshykautz** [comment]
Found an open issue on Flutter for this bug - I'll link here just in case that's helpful for anyone else who comes across this thread:
https://github.com/flutter/flutter/issues/66729
