### ISSUE TITLE
Detect collisions before the rendering phase

### ISSUE THREAD

**Issue by svprdga** [flame-engine/flame#844]
# What could be improved

Collision detection

# Why should this be improved

I have noticed that collisions are detected after the rendering phase, so this can led to the following problem:

1. update -> perform our update operations
2. render -> here we draw everything, but maybe at this point there is an object colliding to another object, but as collisions are not yet calculated, maybe the object is draw on top of the colliding object
3. collision detection -> here we know that there is a collision, and we re-calculate the position of the colliding object, so the next frame the object will be where it should be, but there is 1 frame in which the object has been drawn in the wrong position

So my proposal is:

1. update -> perform updates
2. collision detection -> this must be done before the rendering phase, so if there is an object on top on another (so, its colliding) the necessary corrections can be done _before_ drawing anything
3. render -> draw each object with the correct values

# Any risks?

I don't think that the API will change, though it can severely impact current games; so I think that maybe the best option is to apply this feature as something optional, something that doesn't change how the current games are designed.

# More information

-

-

I can help with a PR with this, if needed.

**Comment by spydon** [comment]
This is already how it is today, collision detection is part of the update-loop.

**Comment by spydon** [comment]
https://github.com/flame-engine/flame/blob/main/packages/flame/lib/src/game/base_game.dart#L228-L230
