### ISSUE TITLE
Add support for sprite of multiple layers

### ISSUE THREAD

**Issue by kuyum** [flame-engine/flame#858]
In some cases, we need a sprite composed of multiple layers of images. For example, the first layer is a hero, and the second layer is a weapon, and so on. This design is mainly to facilitate the replacement of weapons and reduce the total size of the images. Consider this feature?

**Comment by spydon** [comment]
Are you talking about spritesheets? Or a component that would support multiple sprites layered?

**Comment by erickzanardo** [comment]
Coincidently I was thinking about this this week. But I think this can be achieved already, since a component can have multiple children, so I believe this would just be a matter of adding multiple sprites/animations to the same component?

**Comment by kuyum** [comment]
> Are you talking about spritesheets? Or a component that would support multiple sprites layered?

a layered sprite/Animation

**Comment by kuyum** [comment]
> Coincidently I was thinking about this this week. But I think this can be achieved already, since a component can have multiple children, so I believe this would just be a matter of adding multiple sprites/animations to the same component?

I thought it would be a layered sprite/animation. I will have a try with your solution. I don't know if there will be synchronization problems for the animation, or other issues.

**Comment by erickzanardo** [comment]
@kuyum did the suggestion worked for what you are building?

**Comment by kuyum** [comment]
> @kuyum did the suggestion worked for what you are building?
Sorry for my reply so late. I found this is not suitable for my situation. I am using the Bonfire Engine which is based on the Flame Engine. It need to modified a lot of code to use this solution. For now, as an alternative, I just stack these images as one, and then pass it to the Sprite to construct an instance of the Sprite, the same to the animation.

**Comment by erickzanardo** [comment]
As we talked, this can be achieved by having a component with multiple sprite/sprite animations as children. So closing this.
