### ISSUE TITLE
add method within a Drag Controller works only on the first screen.

### ISSUE THREAD

**Issue by paulpmi** [flame-engine/flame#87]
Trying to render a white path where the User has inputs via his touch drag controller. It works fine using Flame addGestureRecognizer method, but unfortunately the add() method renders the PathSprites on a one time screen. For example, if I open the window containing the GameScreen, the path the user drags his fingers is shown, but once I close it and reopen it the screen (creating another instance of GameScreen), the path is no longer shown.

There are other renders within the Screen and they all work fine the 2nd, 3rd, 4th... time, but this breaks after the 1st time it works.

`  
     void _initializeDragController() {
        PanGestureRecognizer gestureDetector = new PanGestureRecognizer( );

       Flame.util.addGestureRecognizer(
       gestureDetector
        ..onUpdate = (startDetails) => dragInput(startDetails.globalPosition));

    Flame.util.addGestureRecognizer(gestureDetector
      ..onEnd = (DragEndDetails d) => onUp());
    }
    void dragInput(Offset position) {
       touchPositionDx = position.dx;
       touchPositionDy = position.dy;

       var newSprite = new PathSprite( touchPositionDx, touchPositionDy );
       _checkSize(); // checks so see if path.length > 30 and removes the first entry
       path.add(newSprite);

       add( newSprite );
    }

   PathSprite( this.xpostion, this.ypostion ) : super.square( PathSprite.baseSize, 'path.png' );

    @override
    bool destroy() {

        return toDestroy;
     }

     @override
      void resize(Size size) {
            this.x = PathSprite.baseSize * xpostion;
            this.y = PathSprite.baseSize * ypostion;
            this.maxY = size.height;
         }
`

Everything else is working fine, the Dx and Dy positions are correct and updated in real time on all screens, but again, the render works only once for the Path Sprites.

**Comment by erickzanardo** [comment]
@luanpotter any thoughts on this?

**Comment by luanpotter** [comment]
How are you handling your `Game` class and your `PathSprite` class? Can you share some more code on those bits? Basically if you are saving your data in a class that's going to get disposed when the user minimizes the app, it will be lost afterward. You can add it to the static context or inside a class that is going to be resilient towards that. However, if the user really closes (kills) your app, all runtime information is lost. The the only way to keep track of it using things like shared_preferences or sqlite.

**Comment by paulpmi** [comment]
Hi sorry for the late reply

    @override
    void initState() {
        super.initState();

       _getGameStart();
     }
    _getGameStart() async {

          Flame.audio.disableLog();
          Flame.audio.loadAll(['Calm.mp3']);
          Flame.images.loadAll(['star.png', 'starGlow.png', 'starCalm.png', 'path.png', 'starTrial.png']);

          var dimensions = await Flame.util.initialDimensions();
          gameController = new GameController( dimensions );

          gameWrapper = new GameWrapper( gameController );

      }
      GameController(this.dimenstions){
               initialize();
              _createStars();
             _initializeDragController();
       }

      void _initializeDragController() {
          PanGestureRecognizer gestureDetector = new PanGestureRecognizer( );

          Flame.util.addGestureRecognizer(
              gestureDetector
                  ..onUpdate = (startDetails) => dragInput(startDetails.globalPosition));

          Flame.util.addGestureRecognizer(gestureDetector
                ..onEnd = (DragEndDetails d) => onUp());
      }
`

The PathSprite beside its initializer as a square with super.square there are no other functionalities

**Comment by luanpotter** [comment]
@paulpmi , I'm assuming your GameWrapper is your implementation of the Game/BaseGame class. If you are saving that as a field of another component, it might get disposed, and then the constructor would be called again. I'd suggest creating a static variable to hold your instance, and only instantiate it once, as for the game state not to get lost. I'd suggest to add some logs in the constructor, where the points are all clear, and I suspect you shall find that it's being called again, because flutter disposes the widget tree when the app is minimized, including your game and the data. Saving it to a static context variable and making sure to instantiate it only once shall fix that problem :)

**Comment by erickzanardo** [comment]
Hey @paulpmi did @luanpotter advice fixed your problem?

**Comment by paulpmi** [comment]
Busy month, sorry. Yes making the class that extends the BaseGame, in my case the Controller which is not shown, static fixes this problem. Thank you, I would have never thought of this !

**Comment by erickzanardo** [comment]
No problem, thanks for the feedback
