### ISSUE TITLE
Flame.util.initialDimensions not found anymore)

### ISSUE THREAD

**Issue by louna-akkad** [flame-engine/flame#872]
hi how should i replace functions ?1.0.0-releasecandidate.12

# Current bug behaviour

after update this function is not found any more
# Expected behaviour

# Steps to reproduce
upgrade to version 

# Flutter doctor output

```
Flame.util.initialDimensions
  crown = Sprite('c'),

```

```
The getter 'util' isn't defined for the type 'Flame'.
Try importing the library that defines 'util', correcting the name to the name of an existing getter, or defining a getter or field named 'util'.
```

`The argument type 'String' can't be assigned to the parameter type 'Image'.
`# More environment information

**Comment by erickzanardo** [comment]
This function don't exists anymore, you can use the size attribute from the Game class instead
