### ISSUE TITLE
how to check image collision ?

### ISSUE THREAD

**Issue by pangoo-reuse** [flame-engine/flame#881]
hi， i am not found a function to  check image collision ,so what should i do?

**Comment by spydon** [comment]
Hi,
create your images as `SpriteComponents` and use the built-in collision detection system.
https://flame-engine.org/docs/#/collision_detection?id=collision-detection
You can see some example code for it here:
https://github.com/flame-engine/flame/blob/main/examples/lib/stories/collision_detection/circles.dart
(A `SpriteComponent` is extending `PositionComponent`)

**Comment by pangoo-reuse** [comment]
no,it doest check Irregular image,like cat,tree and so on,so what can i do? @spydon

**Comment by spydon** [comment]
You have to create a `HitboxPolygon` and add it with `addShape`.

**Comment by pangoo-reuse** [comment]
> You have to create a `HitboxPolygon` and add it with `addShape`.

For example, I'm going to split a picture with trunk and crown. Do you have any good suggestions?

**Comment by spydon** [comment]
Add two `HitboxShape`s, one for trunk and one for crown, depending on your picture you might be able to use a `HitboxRectangle` for the trunk and `HitboxPolygon` for the crown.

**Comment by spydon** [comment]
If you look at this snowman for example, it has three hitboxes that covers it:
https://github.com/flame-engine/flame/blob/main/examples/lib/stories/collision_detection/multiple_shapes.dart#L187

**Comment by pangoo-reuse** [comment]
> If you look at this snowman for example, it has three hitboxes that covers it:
> https://github.com/flame-engine/flame/blob/main/examples/lib/stories/collision_detection/multiple_shapes.dart#L187

final shape = PolygonShape();

final vertices = [
  Vector2(-size.x / 2, -size.y / 2),
  Vector2(size.x / 2, -size.y / 2),
  Vector2(0, size.y / 2),
];
shape.set(vertices);

whats meaing?

**Comment by spydon** [comment]
Please read the documentation for PolygonShape.
