### ISSUE TITLE
Add troubleshoot / configuration section

### ISSUE THREAD

**Issue by impulse** [flame-engine/flame#89]
To have the best game experience it might be needed to do additional configuration. 

One example for that would be drawing over the notch area in android ([fix here](https://github.com/impulse/flutters/commit/25d4ce726cd18e426483e605fe3668ec68b3c12c )). 

It would be nice to have a collection of those configurations available in the documentation or in the readme.

**Comment by luanpotter** [comment]
I'm thinking about a `FAQ.md` file with a list of tips and headsup in FAQ format

**Comment by luanpotter** [comment]
@impulse take a look, maybe you want to add something :) #169

**Comment by impulse** [comment]
Not as of now. Thanks for already adding my fix 👍🏻. I guess we can close up this issue now
