### ISSUE TITLE
PositionComponent can be scale()-able

### ISSUE THREAD

**Issue by st-pasha** [flame-engine/flame#891]
# What could be improved
Currently, a `PositionComponent` can be moved, rotated, and flipped horizontally or vertically. It would be great if it could also be scaled by a certain % factor.

Note that `PositionComponent` already applies scale factors when flipping, but they are limited to ±1. It would be a simple extension to allow the component to replace `renderFlipX` and `renderFlipY` flags with variables `scaleX` and `scaleY`, which could change their signs when "flip X" or "flip Y" operation is requested, but also allowing the user to apply any other scale transform.

# Why should this be improved
A scale transform can be useful in multiple situations:
  - short animation to make a button larger when clicked;
  - a buff on a hero making him stronger and visually bigger;
  - simulate entities that are moving closer to the screen, or further into the distance;
  - etc.

# Any risks?
Variables `renderFlipX` and `renderFlipY` will be replaced with methods for flipping the component horizontally/vertically. The `containsPoint()` method will need to be adjusted to take the scaling factors into account.

**Comment by spydon** [comment]
Hi, `PositionComponent`s can already be scaled, just change the `size` parameter.
An example can be seen here: https://examples.flame-engine.org/#/Effects_Scale%20Effect
(click somewhere on the canvas to make it run)

**Comment by st-pasha** [comment]
But the `size` is only a logical parameter, it affects only the virtual rectangle that the component uses for tap detection. In the example that you gave, the `SquareComponent` uses its size to draw itself (https://github.com/flame-engine/flame/blob/main/examples/lib/commons/square_component.dart), but this is only possible for the simplest cases.

For example, if the component is a sprite, then a change in its size won't affect the size of the image rendered -- you'd have to change the rendering logic manually. Or if the component is a text, you'd have to change its font size and re-layout, and even then it may not look very smooth. If the component is a group of multiple other components, then scaling all the children is even more challenging, since then you'd have to take into account the relative positions of each child within its parent.

**Comment by st-pasha** [comment]
For example, in the [composability demo](https://github.com/flame-engine/flame/blob/main/examples/lib/stories/components/composability.dart), if you add `_parent.size *= 1 - dt/10;` at line 50, then only the outer border of the parent group gets shrunk, while all the children's sizes will be unaffected.

**Comment by spydon** [comment]
It is only a logical parameter, but all components using `PositionComponent` are taking it into consideration. Try changing the `size` parameter in a `SpriteComponent` (which inherits from `PositionComponent`) for example and you'll see that it will scale the size will change for that one too.

But you are right that it might be good for some use-cases so I'll re-open it and talk to the team. (Text is not a very good idea though, since it will be blurry if it is scaled by the canvas.)

**Comment by st-pasha** [comment]
It's actually ok for text too:

Here i have some text at font size = 30:
<img width="96" alt="Screen Shot 2021-07-31 at 2 21 45 AM" src="https://user-images.githubusercontent.com/4231472/127735406-cdb8a1e5-9ef3-4b17-b4f7-10d189092f94.png">

Here's the same text scaled down 3 times using `canvas.scale(1/3, 1/3)`:
<img width="38" alt="Screen Shot 2021-07-31 at 2 22 19 AM" src="https://user-images.githubusercontent.com/4231472/127735424-620a8e87-58bc-4b70-a51c-f4570f1d74be.png">

And here it is again scaled up by a factor of 3 using `canvas.scale(3, 3)`:
<img width="239" alt="Screen Shot 2021-07-31 at 2 24 40 AM" src="https://user-images.githubusercontent.com/4231472/127735448-1373937a-f560-4d74-9d8a-373f1bd86159.png">

Neither of these look blurry. 

Obviously, rendering text at the native font size is always preferable, for example, if the font is smart enough to adjust the shape or kerning of the letters with the font size; but scaling up/down also works reasonably well, especially if the scale factor is close to 1.

[Btw, the Discord invite link in the README and documentation is no longer working].

**Comment by spydon** [comment]
That's good that it is not blurry, I think I was thinking of when we prerendered it and then scaled it.
The link is working for me, what error message are you getting?
This is the [link](https://discord.com/invite/pxrBmy4) you are using right?

**Comment by st-pasha** [comment]
Yes, here's what I see when I click the link:
<img width="493" alt="Screen Shot 2021-07-31 at 3 09 16 AM" src="https://user-images.githubusercontent.com/4231472/127736584-3757b215-be1a-4d11-9319-a53e3e27f53d.png">

**Comment by spydon** [comment]
Strange, will have to ask Erick about that.
Try this one meanwhile: https://discord.gg/jTKJaakj
