### ISSUE TITLE
Undefined class Util

### ISSUE THREAD

**Issue by optimisme** [flame-engine/flame#903]
# Current bug behaviour
Using 'package:flame/util.dart' library results in: Target of URI doesn't exist: 'package:flame/util.dart'

# Expected behaviour
This library should work after "flutter pub get"

# Steps to reproduce
Create an empty project
Add the .yaml dependency: flame: 1.0.0-releasecandidate.13
Try to import 'package:flame/util.dart' from main.dart file

# Flutter doctor output
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-arm, locale ca-ES)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.58.2)
[✓] Connected device (2 available)

# More environment information
1.0.0-releasecandidate.13

**Comment by spydon** [comment]
Hi, in `1.0.0-releasecandidate.13` there is no `util` package, it has been split up as can be seen here in docs:
https://flame-engine.org/docs/#/util

It is most likely the `device` package that you are looking for.
