### ISSUE TITLE
IMPOSSIBLE TO ASSIGN A NEW REFERENCE TO THE VARIABLE '_position' OF A 'PositionComponent' AFTER THE MANUFACTURER

### ISSUE THREAD

**Issue by elgsylvain85** [flame-engine/flame#908]
# Problem to solve

IMPOSSIBLE TO ASSIGN A NEW REFERENCE TO THE VARIABLE '_position' OF A 'PositionComponent' AFTER THE MANUFACTURER

# Proposal

If by the constructor, this operation is feasible then the code must offer us a possibility via the setter

# My Theory

`
  Vector2 posOne = Vector2(10, 10);

  // by indicating [posOne] as position in the constructor, it is assigned in the private variable [_position]

  var spriteComp = SpriteComponent(position: posOne);

  // even further, it is still possible to manipulate the position from the reference [posOne]
  // following the block '_size = size ?? Vector2.zero (), 'in constructor' PositionComponent '

  posOne.add(Vector2(50, 0));

  print(spriteComp.position);

  // but after the constructor, it becomes impossible to assign a new reference

  Vector2 posTwo = Vector2(20, 20);

  // because the following statement only copies the values ​​of [posTwo] to 'position' but does not affect this new refence
  // because of the setter code: 'set position (Vector2 position) => _position.setFrom (position)'
  // setFrom block:
  // void setFrom (Vector2 other) {
  // final otherStorage = other._v2storage;
  // _v2storage [1] = otherStorage [1];
  // _v2storage [0] = otherStorage [0];
  //}
  
  spriteComp.position = posTwo;

  // suddenly, the instruction below has no effect on the 'position' of the object, unlike the manipulation of [posOne]

  posTwo.add(Vector2(50, 0));

  print(spriteComp.position);
`

# Flame version

flame: ^1.0.0-releasecandidate.13

# Flutter doctor

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.1, on Mac OS X 10.15.5 19F101 darwin-x64,
    locale en-CD)
[✓] Android toolchain - develop for Android devices (Android SDK version
    30.0.2)
[!] Xcode - develop for iOS and macOS
    ✗ Xcode 11.7.0 out of date (12.0.1 is recommended).
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.59.0)
[✓] Connected device (1 available)

**Comment by spydon** [comment]
Hi,
This is intentional since the references within `PositionComponent` are used in other places. If you need to use it afterwards just do `posTwo = component.position` or use `component.position` directly (this will of course be problematic if you intend to use that reference for multiple components afterwards).

Ps. It seems like your caps lock button is stuck.
