### ISSUE TITLE
Samples/Tutorials are outdated

### ISSUE THREAD

**Issue by m-sadegh-sh** [flame-engine/flame#928]
I've got familiar with Flame this morning and after reading the docs, I tried to play around with the samples/tutorials, but none of them are up-to-date. So I wasn't able to compile the project against v0.29.4.

I will be happy to help you guys update those samples, but before that, I wanna know have you had any plan to sort them out?

**Comment by spydon** [comment]
Hi, all of them are up to date.
The newest version is not `0.29.4`, but `1.0.0-releasecandidate.13`
https://pub.dev/packages/flame/versions/1.0.0-releasecandidate.13

**Comment by dimiskil** [comment]
Hi!) so which version do you recommend using?

**Comment by spydon** [comment]
> Hi!) so which version do you recommend using?

Hi, `1.0.0-releasecandidate.13`
