### ISSUE TITLE
Define a standard for casing on test names

### ISSUE THREAD

**Issue by spydon** [flame-engine/flame#946]
# What could be improved
We should define a standard for casing on test and test group names in our test files.

# Why should this be improved
Since it is a mix now, and someone might start crying when reading the tests.

# Any risks?
No.

# More information

**Comment by erickzanardo** [comment]
IMO, we should use this as a guideline: https://www.betterspecs.org/

**Comment by st-pasha** [comment]
How about the following simple standard:
 - every source file has a single matching test file;
 - every class / top-level function in the source file is represented as a `group()` in the test file;
 - the name of the group is the same as the name of the class or top-level function;
 - the tests inside the group can have arbitrary names;
 - if it feels like a particular class needs more than one group (such as in `position_component_test`), then those can be arranged as groups within the main group.

**Comment by spydon** [comment]
> How about the following simple standard:
>  - every source file has a single matching test file;
>  - every class / top-level function in the source file is represented as a `group()` in the test file;
>  - the name of the group is the same as the name of the class or top-level function;
>  - the tests inside the group can have arbitrary names;
>  - if it feels like a particular class needs more than one group (such as in `position_component_test`), then those can be arranged as groups within the main group.

All these sounds good, but this specific issue was much simpler, it is about the one that isn't speced in your list: "the tests inside the group can have arbitrary names".

This issue was opened because we have varying casing of the names of the tests.

**Comment by st-pasha** [comment]
Do you mean whether they should be capitalized like a sentence, or be lowercase?

**Comment by spydon** [comment]
> Do you mean whether they should be capitalized like a sentence, or be lowercase?

Exactly, isn't "casing" the correct word for that in English? 😅 
We should open another issue for the rest you and Erick mentioned though.

**Comment by st-pasha** [comment]
Ok then, I think the easiest way to resolve this is through a vote.

I'll put up separate comments below for each alternative, and we can vote using emoji reactions:

**Comment by st-pasha** [comment]
1. Lowercase
```
test('breaks assertion when adding an invalid portion', () {...});
```

**Comment by st-pasha** [comment]
2. Capitalized
```
test('Breaks assertion when adding an invalid portion', () {...});
```

**Comment by st-pasha** [comment]
If this is now a standard, shouldn't it be formally recorded in the Flame Style Guide?

**Comment by spydon** [comment]
> If this is now a standard, shouldn't it be formally recorded in the Flame Style Guide?

Ah yes, forgot to update that one. Will do now.
There are a lot more things to unify with the tests as was mentioned before too.
