### ISSUE TITLE
A better abstraction than `propagateToChildren`

### ISSUE THREAD

**Issue by spydon** [flame-engine/flame#949]
# What could be improved
Code that is using `propagateToChildren` repeats some snippets of code a lot. 
It might be possible to create a better abstraction than `propagateToChildren` that requires each place to have less code...

# Why should this be improved
Less code duplication.

# Any risks?
It could be less efficient than `propagateToChildren`, very unlikely though.

# More information

**Comment by erickzanardo** [comment]
@spydon is this issue still relevant now with the game as component merged?

**Comment by spydon** [comment]
It is still a bit of code duplication in all the methods where `propagateToChildren` is called, but it is not as bad as it used to be.

**Comment by erickzanardo** [comment]
Maybe we can close this then?
