### ISSUE TITLE
Multi-version documentation

### ISSUE THREAD

**Issue by st-pasha** [flame-engine/flame#960]
## What could be improved

Currently, the main documentation site ([flame-engine.org](flame-engine.org)) shows only documentation for the latest release candidate. However, it would greatly benefit the users if we were able to show documentation for multiple versions of the library:
  - last stable releast (0.29.4);
  - latest release candidate (1.0.0.rc14)
  - previous release candidate(s) (1.0.0.rc13, ...)
  - current version in development (`main` branch)
  - not public, but still available somewhere: documentation for every current PR

The purpose here is to allow users to read the documentation for the specific version that they are using. Too often we see complaints that the documentation does not reflect the code.

## How

There could be several potential approaches here, but IMHO the simplest one is to use the external documentation hosting platform [readthedocs.io](readthedocs.io). Its features are the following:
  - Free hosting for open source projects;
  - Support for building and hosting multiple versions of the project at the same time;
  - Building from PR branches;
  - Fully customizable build process.

Here's how it would work in practice:
  - Locally, run `pip install sphinx` and then inside the `docs` folder: `sphinx-quickstart`;
  - This will create a `Makefile` and the configuration file `conf.py`;
  - (optional) run `make html` to verify that documentation can be generated properly, add the build directory to `.gitignore`. The resulting documentation won't look very nice, but that's ok for the initial draft;
  - create an account on `readthedocs.io` and point it to our GitHub repo.

That's it for the initial version. Later we can tweak the theme/style to make the generated docs look exactly like we want. 

## More information

- Readthedocs can be configured to serve at the `flame-engine.org` address;
- Readthedocs uses python `sphinx` library in order to convert markdown doc files into html.
  - PRO: the process is highly customizable - you can quite literally modify every single step in the generation pipeline, for example, if we want to create extensions for the Markdown syntax;
  - CON: Python language is not primary for Flame, so it may not be that easy.
- Local development is very easy: `make html` and it will build the entire documentation site locally.
- This proposal is relatively risk-free: it only involves adding 2 (or 3) new files without modifying any of the existing files. The site can be kept parallel to the existing one while we evaluate its feasibility.
- In order to enable readthedocs to build documentation for the past versions of Flame, those versions must have the same configuration file `conf.py`. Thus, once we finalize the settings in conf.py, we'd want to push that file to each of the released branches that we plan to document.

**Comment by spydon** [comment]
Sounds good to me, especially since @renancaraujo has given it a thumbs up.
I'll add a note about this to our meeting next week.

**Comment by st-pasha** [comment]
So, what's left here is for someone on the team to go to the [readthedocs.org](https://readthedocs.org/) website, sign up with GitHub, and connect with this repository. 
@luanpotter?

**Comment by spydon** [comment]
I'll close this since it is done, and create a follow-up issue to make the page where you choose the version more pretty.
