### ISSUE TITLE
Knob in JoystickComponent 

### ISSUE THREAD

**Issue by QiXi** [flame-engine/flame#969]
if the area of pressing went beyond the joystick and returned to the edge, then the result is not what the player expects.
For a simple explanation, I recorded a video https://www.youtube.com/watch?v=Lv1jzAT6054

---
flame: ^1.0.0-releasecandidate.14
Flutter 2.5.1 
Dart 2.14.2

**Comment by spydon** [comment]
Can you explain more in detail, what is the behaviour you expect and what is the current ourcome?

**Comment by QiXi** [comment]
> Can you explain more in detail, what is the behaviour you expect and what is the current outcome?

The video shows the pressed area, how the finger moved on the screen. The finger was always to the right of the joystick area. But when the area has turned to the outer perimeter, the handle moves to the left edge.  Why should there be a command to move to the left if the finger has never been to the left.
