### ISSUE TITLE
Signalization System

### ISSUE THREAD

**Issue by namzug16** [flame-engine/flame#972]
# Problem to solve

Listening to changes in a component can get a bit messy, especially if you have a lot of components listening to only one. For example if we want to change the color of different components present in the world in case our player is hurt, we could listen to the Player's component and see if its HP has changed or if a boolean isHurt has been set to true, however this implies creating variables for simple mechanisms and listening to other components when the solution could be much simpler.

# Proposal

## Signalization System 
By making a signalization system we could stop worrying about creating variables for simple responses and listening to other components all the time, it is worth saying that this system has been inspired by Godot's signals (you can read more about this [here](https://docs.godotengine.org/en/stable/getting_started/step_by_step/signals.html)).

### Implementation
The implementation of this system is very simple, we can create three basic mixins ```Signalable```, ```Emitter``` and ```HasSignalableComponents```.

### -> Signalable
This is a mixin on ```Component```, here you will have a ```List<String> signals``` which are the signals this component will receive and it will have only two methods, ```addSignal(String signal)``` and ```onSignalReceived(String signal)```.

--> ```addSignal(String signal)``` 
This method adds a signal to your ```List<String signals``` and it can be used from the constructor and even from the ```onLoad``` method.

--> ```onSignalReceived(String signal)```
This method is overridable so that you can implement what you want to happen when you received a certain signal which is present on your ```signals```

### -> Emitter
This is also a mixin on ```Component```, by using this mixin your component will be able to emit a signal with the only method present on it ```emitSignal(String signal, [bool isGlobal = false, bool once = true])```.

To be able to send this signal first of all it uses ```findParent<HasSignalableComponents>()``` to get the closest parent with this mixing and send this signal to it.

#### Signals
As you have seen, ```emitSignal``` has two more arguments apart from the signal.

```bool isGlobal```
when this argument is set to true, ```HasSignalableComponents``` will call ```onSignalReceived``` in all the ```Signalable```s components where its ```signals``` variable contains the emitted signal. In the other hand, when ```isGlobal``` is set to false, ```HasSignalableComponents``` will send this signal only to the first child that its ```signals``` variable contains the emitted signal.
  
![image](https://user-images.githubusercontent.com/77210010/134337082-550dde1e-329f-4395-ba9e-4bee00cde1ca.png)

```bool once```
This argument it is very important in case we are emitting the signal constantly, for example if we want to send a signal when objects are colliding (or in any other method that can be shoot each frame) and we wan it to be sent only once we should set ```once``` to true. When it is true, ```HasSignalableComponents``` will remember this signal and it will not let it pass if it is emitted again, until you clear the variable where the last signal has been saved, by emitting a different signal (or by calling a method ```clearLastSignal``` but I'm not really sure about this yet)

![image](https://user-images.githubusercontent.com/77210010/134338737-16bc60be-6684-4176-aef4-2c8ce05cffd4.png)

### -> HasSignalableComponents
This is a mixing on ```FlameGame``` . Just like ```HasCollidableComponents``` which stores ```Collidable```s in a list , this mixin stores the ```Signalable```s that will later on will be used on the method ```handleSignalEmissions```. 

# More information

I have already worked a bit on the implementation so I could share some of the code I've written so far to know what you think.

**Comment by erickzanardo** [comment]
I think this is a very nice idea. But I feel that this should be a package of its own.

I think this because we can come with many different ways of listening and emitting events throughout components, some ways may be more suitable for many different scenarios.

We could even create flame bridges using many of the famous events libraries we can find on flutter.

So, bottom line, awesome idea, but better if this is a package that the user can plug into their project.

**Comment by st-pasha** [comment]
Not sure why you need such a complicated design. Wouldn't it be enough to have several functions `emit()`, `subscribe()`, `unsubscribe()`, together with some private static map of events into the corresponding list of subscribers? This could be implemented completely independently from the component system.

As for the example that you have provided -- it can be implemented even easier, by declaring the player to be a `ChangeNotifier` and letting any other components subscribe to that. Of course, the primary limitation here is that there are no different "kinds" of events. At the same time, the proposed system also has some serious limitations:
  - there is no concept of who sent the event;
  - the events don't support any payloads.

**Comment by namzug16** [comment]
Actually, events can support payloads by just adjusting the method ```emitSignal()``` and we could know which component sent the event by specifying it on the signal.
Anyways I just thought having some sort of signalization system on Flame would be great, but if I think about how many other methods of doing this exit I came to the conclusion , just like @erickzanardo, that this project would be better as a third party package. 
Thank you for reading it, I'll be closing the issue here.
