### ISSUE TITLE
FixedResolutionViewport is not set up properly.

### ISSUE THREAD

**Issue by tatsuya-sagara** [flame-engine/flame#977]
# Current bug behaviour
FixedResolutionViewport is not set correctly.

# Expected behaviour
FixedResolutionViewport must be set correctly.

# Steps to reproduce
I have a question.
I don't understand it very well, so if I'm wrong, I apologize.

If I use Forge2DGame, is it okay to have a camera in both Forge2DGame and FlameGame?
```
Forge2DGame :
	final Forge2DCamera camera = Forge2DCamera();
FlameGame :
	Camera get camera => _cameraWrapper.camera;
```
If I use Forge2DGame and set the viewport to FixedResolutionViewport, I think FlameGame will be the DefaultViewpot.
```
class SampleGame extends Forge2DGame ... {
	:
	@override
	Future<void> onLoad() async {
		camera.viewport = FixedResolutionViewport(...
		:
	}
}
```
# Flutter doctor output
```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-x64, locale ja-JP)
    • Flutter version 2.2.3 at /Users/tatsuya/fvm/versions/stable
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/tatsuya/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at:
      /usr/local/Cellar/openjdk/16.0.2/libexec/openjdk.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Homebrew (build 16.0.2+0)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.107

! Doctor found issues in 1 category.
```
# More environment information
I ran it in the following environment.
flame: ^1.0.0-releasecandidate.14
flame_forge2d: ^0.8.1-releasecandidate.13

# Log information
None in particular

# More information
None in particular

**Comment by tatsuya-sagara** [comment]
Will there be a release of flame_forge2d for 1.0.0-releasecandidate.14 in the near future?

**Comment by spydon** [comment]
> Will there be a release of flame_forge2d for 1.0.0-releasecandidate.14 in the near future?

It will be a release for rc15, there was a change that wasn't compatible with Forge2DGame in rc14 that I missed.
But rc15 should not be long since we have some bugfixes that need to go out.

**Comment by tatsuya-sagara** [comment]
#981 response solved the above problem. Thank you very much. However, I can't explain the current situation well, but I got the following error
I just want to report it.
Bad state: Cannot find reference Forge2DGame in the component tree

I will close this issue if it is better to do so.

**Comment by spydon** [comment]
@tatsuya-sagara that is this bug #967, it seems to affect forge2d extra hard. I haven't had time to investigate it deeper.

**Comment by luanpotter** [comment]
Fixed by https://github.com/flame-engine/flame/pull/987

**Comment by tatsuya-sagara** [comment]
This issue has been closed, but I would like to include it.
(I apologize if this is inappropriate)

The error "Bad state: Cannot find reference Forge2DGame in the component tree" no longer occurs by changing onRemove() in component.dart as follows
Since I had cleared the _parent.
````
  /// Called right before the component is removed from the game
  @override
  @mustCallSuper
  void onRemove() {
    super.onRemove();
    children.forEach((child) {
      child.onRemove();
    });
    isPrepared = false;
    isMounted = false;
    // _parent = null;
    nextParent?.add(this);
    nextParent = null;
  }
````

Translated with www.DeepL.com/Translator (free version)
