### ISSUE TITLE
Improvements on collision detection.

### ISSUE THREAD

**Issue by namzug16** [flame-engine/flame#980]
# What could be improved

The way collision detection works can be improved and can be even made 4 times faster(more or less).

# Any risks?

No that I can think of

# More information

At the moment, every time we add a component to a game that has as a mixin ```HasCollidables```, this component will be added to a list of ```Collidables``` and then all the list will be evaluated with the function ```collisionDetection(List<Collidable> collidables)```. The problem with this implementation ( if I can call it a problem) is that one ```Collidable``` will check for collisions with all the other ```Collidable```s even if we don't want it to collide with everything. 

We could change this by setting the concept of "Layers", a layer would be an ```int``` that this ```Collidable``` is occupying and then we could specify with which layers can this component collide. 

These layers then would be stored on a map like so:
```dart
Map<int, List<Collidable>> collidables = {};
```
by doing this we can improved a lot the performance of the function ```collisionDetection()```.

This is the new implementation of the function that I came out with:
```dart
void collisionDetectionMap(Map<int, List<Collidable>> collidables) {
  // l stands for layer
  for (var l = 0; l < collidables.length; l++) {
    for(var x = 0; x < collidables[l]!.length; x++){

      final collidableX = collidables[l]![x];
      if (collidableX.collidableType != CollidableType.active) {
        break;
      }

      // all the collidables that this component can collide with
      final collidablesY = <Collidable>[];

      for(final lY in collidableX.collisionLayersToCollideWith){
        if(lY == l){
          // I think this can still be improved
          // here I'm adding any other component of the same layer
          // in case the layer is inside the layers this component can collide with

          // if this part stays like so, the entire function will be only 3.8(more or less)
          // faster than the original, in the other hand it this part is changed
          // the function could be more than 4 times faster
          collidablesY.addAll(collidables[lY]!.toList().sublist(0, x) + collidables[lY]!.toList().sublist(x+1));
        }else{
          collidablesY.addAll(collidables[lY]!.toList());
        }
      }

      for(final collidableY in collidablesY){
        if (collidableY.collidableType == CollidableType.inactive) {
          break;
        }

        final intersectionPoints = intersections(collidableX, collidableY);
        if (intersectionPoints.isNotEmpty) {
          collidableX.onCollision(intersectionPoints, collidableY);
          collidableY.onCollision(intersectionPoints, collidableX);
          final collisionHash = _combinedHash(collidableX, collidableY);
          _collidableHashes.add(collisionHash);
        } else {
          _handleCollisionEnd(collidableX, collidableY);
        }
      }

    }
  }
}
``` 

Then I tested the speed of the function like so:

```dart

class TestCollidable extends PositionComponent with Hitbox, Collidable {
// cL stands for collisionLayer 
// cLTCW stands for collisionLayersToCollideWith
  TestCollidable(Vector2 position, int cL, List<int> cLTCW)
      : super(
          position: position,
          size: Vector2.all(100),
        ) {
    collisionLayer = cL;
    collisionLayersToCollideWith = cLTCW;
    addHitbox(HitboxRectangle(relation: Vector2.all(1)));
  }
}

List<Collidable> collidablesList = [
  TestCollidable(Vector2(100, 100), 0, [1, 2]),
  TestCollidable(Vector2(200, 100), 1, [2]),
  TestCollidable(Vector2(300, 100), 1, [2]),
  TestCollidable(Vector2(400, 100), 1, [2]),
  TestCollidable(Vector2(500, 100), 2, [0, 1]),
  TestCollidable(Vector2(600, 100), 2, [0, 1]),
  TestCollidable(Vector2(700, 100), 3, [0, 1, 2, 3]),
  TestCollidable(Vector2(800, 100), 3, [0, 1, 2, 3]),
  TestCollidable(Vector2(300, 100), 3, [0, 1, 2, 3]),
];

Map<int, List<Collidable>> collidablesMap = {
  0: [
    TestCollidable(Vector2(100, 100), 0, [1, 2]),
  ],
  1: [
    TestCollidable(Vector2(200, 100), 1, [2]),
    TestCollidable(Vector2(300, 100), 1, [2]),
    TestCollidable(Vector2(400, 100), 1, [2]),
  ],
  2: [
    TestCollidable(Vector2(500, 100), 2, [0, 1]),
    TestCollidable(Vector2(600, 100), 2, [0, 1]),
  ],
  3: [
    TestCollidable(Vector2(700, 100), 3, [0, 1, 2, 3]),
    TestCollidable(Vector2(800, 100), 3, [0, 1, 2, 3]),
    TestCollidable(Vector2(300, 100), 3, [0, 1, 2, 3]),
  ],
};

void main(){
  final stopwatch1 = Stopwatch()..start();
  collisionDetection(collidablesList);
  print('Collision Detection with a List executed in: ${stopwatch1.elapsed}');

  final stopwatch2 = Stopwatch()..start();
  collisionDetectionMap(collidablesMap);
  print('Collision Detection with a Map executed in: ${stopwatch2.elapsed}');
}

```
and I got this output:
![image](https://user-images.githubusercontent.com/77210010/134778740-b15dc277-dad7-4abf-8498-dd83e1bc05dd.png)

if I run it more times:
![image](https://user-images.githubusercontent.com/77210010/134778762-cf8d6d16-e983-4188-aec9-e42b27a381c5.png)
![image](https://user-images.githubusercontent.com/77210010/134778835-398bd9c5-f50a-4599-9c3b-a992afd32faa.png)

and even if I set the same position for all the components Vector2(100, 100):
![image](https://user-images.githubusercontent.com/77210010/134778887-26e7b878-cf3a-41bc-bea8-4fdabf9304ac.png)

**Comment by st-pasha** [comment]
Not too long ago we had collidables operate within a single component layer only. That is, only the siblings of a single component were able to collide. Then we changed it (#943) so that any components were able to collide, regardless of where they are in the tree. Now you're suggesting that we added some concept of "collision layers" that would work independently from the main component tree structure?

It could make sense to have some notion of `zIndex`, so that only components at the same z-index can collide with each other.

I guess we should ask @spydon here what was his motivating example for putting all collidables into a single flat list, and then we can work from there.

**Comment by namzug16** [comment]
This map of collidables would replace the ```List<Collidable> collidables``` inside ```HasCollidables```, so it would work just like it works now.

```zIndex``` would still have some problems i.e. we could set enemies on a ```zIndex``` = 2 but that would mean that our bullets, to be able to collide with enemies, should also be at the same index, therefore when ```HasCollidables``` checks for collisions on that index, it would check for collision between bullets too, thing that we might not want to happen. 

In the other hand, by using a map, we could set enemies on a "layer" = 2, which for the map would be the key, and set its values to all the enemies on the game, then we could say that we only want this "layer" of enemies to be able to collide with "layer" 3 which would be our bullets layer (we specify which layer we want to collide with inside a variable in ```Collidable``` called ```List<int> collisionLayersToCollideWith``` ).

Now that I think about this example, this could be even faster if we set our enemies("layer" 2) to be able to collide only with bullets(from the point of view of the enemy component => "collisionLayerToCollideWith" = [3] ), and set "collisionLayersToCollideWith" to an empty array inside bullets , so that ```HasCollidables``` will only check for collisions between enemies and bullets when the component in question is an enemy and not a bullet, or we could do it the other way around, it could only check collisions when the component is a bullet or from the point of view of ```HasCollidables``` when the layer(key) is 3.

**Comment by st-pasha** [comment]
> zIndex would still have some problems i.e. we could set enemies on a zIndex = 2 but that would mean that our bullets, to be able to collide with enemies, should also be at the same index, therefore when HasCollidables checks for collisions on that index, it would check for collision between bullets too, something that we might not want to happen.

That's an excellent point! I knew it would be useful to think in terms of an actual example.

So what we have here is some kind of a directional _collision graph_, where each node of the graph contains a list of collidables, and vertices indicate which other components they can collide with.

**Comment by namzug16** [comment]
To make this possible I created two variables inside ```Collidable```, ```int collisionLayer``` with a default value of 0 and ```List<int> collisionLayersToCollideWith``` which has a default value of [0] meaning the collision system would work as if nothing would have changed. So it already has default values and an user can just ignore these layers.

**Comment by spydon** [comment]
I think the layer settings for e ach Collidable should be a const class ibstead of an int and then said class will contain an int for which layer it is and also aa variable for which CollisionType the Collidable should have in that layer, so that the direction can be different for different layers.

**Comment by namzug16** [comment]
This is how ```Collidable``` ended up being when I added the variables
```dart
mixin Collidable on Hitbox {
  int collisionLayer = 0;
  List<int> collisionLayersToCollideWith = [0];
  CollidableType collidableType = CollidableType.active;

 ...
}
```
But following your idea, a ```CollisionSettings``` class can be made so that it has all these variables and it'll be something like this 

```dart
class CollisionSettings {
  final int layer;
  final CollidableType collidableType;
  final List<int> layersToCollideWith;

  const CollisionSettings({
    this.layer = 0,
    this.collidableType = CollidableType.active,
    this.layersToCollideWith = const [0],
});

}

```

and then ```Collidable``` can be writing like so

```dart
mixin Collidable on Hitbox {

final CollisionSettings settings = const CollisionSettings();
 ...
}
```
and if we need to change these settings we can just override it, for example in ```ScreenCollidable```:

```dart
class ScreenCollidable<T extends FlameGame> extends PositionComponent
    with Hitbox, Collidable, HasGameRef<T> {

  @override
  CollisionSettings settings = const CollisionSettings(collidableType: CollidableType.passive);

  // instead of doing it like this
  // @override
  // CollidableType collidableType = CollidableType.passive;
 ...
}

```
Of course by doing this some stuff on the function ```collisionDetection()``` would change, but I don't think it would affect its performance.

**Comment by namzug16** [comment]
> This is how `Collidable` ended up being when I added the variables
> 
> ```dart
> mixin Collidable on Hitbox {
>   int collisionLayer = 0;
>   List<int> collisionLayersToCollideWith = [0];
>   CollidableType collidableType = CollidableType.active;
> 
>  ...
> }
> ```
> 
> But following your idea, a `CollisionSettings` class can be made so that it has all these variables and it'll be something like this
> 
> ```dart
> class CollisionSettings {
>   final int layer;
>   final CollidableType collidableType;
>   final List<int> layersToCollideWith;
> 
>   const CollisionSettings({
>     this.layer = 0,
>     this.collidableType = CollidableType.active,
>     this.layersToCollideWith = const [0],
> });
> 
> }
> ```
> 
> and then `Collidable` can be writing like so
> 
> ```dart
> mixin Collidable on Hitbox {
> 
> final CollisionSettings settings = const CollisionSettings();
>  ...
> }
> ```
> 
> and if we need to change these settings we can just override it, for example in `ScreenCollidable`:
> 
> ```dart
> class ScreenCollidable<T extends FlameGame> extends PositionComponent
>     with Hitbox, Collidable, HasGameRef<T> {
> 
>   @override
>   CollisionSettings settings = const CollisionSettings(collidableType: CollidableType.passive);
> 
>   // instead of doing it like this
>   // @override
>   // CollidableType collidableType = CollidableType.passive;
>  ...
> }
> ```
> 
> Of course by doing this some stuff on the function `collisionDetection()` would change, but I don't think it would affect its performance.

There is just a slight problem with this, that I just realize. 

I'd like to explain a bit of context first, so I'm making a game where the player can shoot a lot of bullets , the thing is that I didn't want to create and remove these bullets every time the player was shooting, so I made a ```BulletPool``` which renders bullets only when they are needed, meaning, the instances of these bullets are always there, the problem with this was that the collision detection was still working on them so the game got really really slow, to fix that I changed the ```collidableType``` of these bullets when they were not visible to "inactive", so the game engine wouldn't have to check for collisions when they weren't rendered.

The thing is that if some sort of constant class is implemented to store collision settings (at least as I've done in this example) an user wouldn't be able to change the collision type whenever he wants, so maybe this ```CollisionSettings``` would be better as a ```CollisionLayerSettings```

```dart 
class CollisionLayerSettings {
  final int layer;
  final List<int> layersToCollideWith;

  const CollisionSettings({
    this.layer = 0,
    this.layersToCollideWith = const [0],
});

}

// and Collidable would look like this

mixin Collidable on Hitbox {

final CollidableType collidableType = CollidableType.active;
final CollisionLayerSettings layerSettings = const CollisionLayerSettings();
 ...
}

```

**Comment by namzug16** [comment]
ACTUALLY BIG MISTAKE.

for some reason I wondered what would happen if I changed the order of execution of these functions inside ```main()```

>```dart
> void main(){
>   final stopwatch1 = Stopwatch()..start();
>   collisionDetection(collidablesList);
>   print('Collision Detection with a List executed in: ${stopwatch1.elapsed}');
> 
>   final stopwatch2 = Stopwatch()..start();
>   collisionDetectionMap(collidablesMap);
>   print('Collision Detection with a Map executed in: ${stopwatch2.elapsed}');
> }
> ```

and I got some result like this

> and I got this output:
> ![image](https://user-images.githubusercontent.com/77210010/134778740-b15dc277-dad7-4abf-8498-dd83e1bc05dd.png)
> 

so this result of speed was actually due to the compiler, for some reason it executes way faster the second one.

Despite the fact that there are no difference in performance by using a map ( it actually seems to be slower ), I didn't give up, so I used the concept of layers inside the original ```collisionDetection()``` and i came up with this function

```dart
void collisionDetectionLayers(List<Collidable> collidables){
  for(var x = 0; x < collidables.length; x++){

    final collidableX = collidables[x];
    // or 
    // final layersToCollideWithX = collidableX.layerSettings.collisionLayersToCollideWith;
    // if the class CollisionLayerSettings is created instead of the variables
    final layersToCollideWithX = collidableX.collisionLayersToCollideWith;

    if(collidableX.collidableType != CollidableType.active){
      break;
    }

    for(var y = x + 1; y < collidables.length; y++){
      final collidableY = collidables[y];
      // or
      // final layerY = collidableY.layerSettings.layer;
      final layerY = collidableY.collisionLayer;

      if(!layersToCollideWithX.contains(layerY)){
        break;
      }

      if (collidableY.collidableType != CollidableType.active) {
        break;
      }

      final intersectionPoints = intersections(collidableX, collidableY);
      if (intersectionPoints.isNotEmpty) {
        collidableX.onCollision(intersectionPoints, collidableY);
        collidableY.onCollision(intersectionPoints, collidableX);
        final collisionHash = _combinedHash(collidableX, collidableY);
        _collidableHashes.add(collisionHash);
      } else {
        _handleCollisionEnd(collidableX, collidableY);
      }

    }
  }
}
```
and to test them I executed them separately and I got a little improvement, so at the end of the day the idea isn't that bad.
 
Original function 
![image](https://user-images.githubusercontent.com/77210010/134810418-831edf66-496e-42af-a438-289d9f9f2fc7.png)
![image](https://user-images.githubusercontent.com/77210010/134810433-d37a7e1e-0c26-4e0f-abb3-5fd25d65148a.png)

Using Layers
![image](https://user-images.githubusercontent.com/77210010/134810460-f35f7d80-7ab5-4c19-bf9b-edbbb0254e06.png)
![image](https://user-images.githubusercontent.com/77210010/134810476-e16dd548-79c0-49f5-a967-58b9305db118.png)

**Comment by ufrshubham** [comment]
Hey, I gave quick thought on this and I found following major things to consider.

- With this proposed layering mechanism each Collidable will be restricted to only a single layer.
- `List<int> layersToCollideWith` will increase size of each Collidable.

Instead of using up a complete integer to store a single layer information, we can use each bit of an integer to represent a layer. With some bit wise operators we can easily check for possible collisions. Following is quick example to explain this:

```dart
const LAYER_ZERO = 1 << 0;
const LAYER_ONE = 1 << 1;
const LAYER_TWO = 1 << 2;
const LAYER_THREE = 1 << 3;

class Collidable {
  int myLayers = 0; // The layers on which this entity is present
  int myCollidableLayers = 0; // Layers to check for collisions
  String name;

  Collidable(this.name);

  @override
  String toString() {
    return name;
  }
}

void main(List<String> arguments) {
  final cList = List<Collidable>.empty(growable: true);

  var c1 = Collidable('C1');
  c1.myLayers = LAYER_ONE;
  c1.myCollidableLayers = LAYER_TWO | LAYER_THREE;
  cList.add(c1);

  var c2 = Collidable('C2');
  c2.myLayers = LAYER_TWO;
  c2.myCollidableLayers = LAYER_THREE;
  cList.add(c2);

  var c3 = Collidable('C3');
  c3.myLayers = LAYER_THREE | LAYER_ONE;
  c3.myCollidableLayers = LAYER_TWO;
  cList.add(c3);

  checkPossibleCollisions(cList);
}

void checkPossibleCollisions(List<Collidable> cList) {
  for (var c1 in cList) {
    var others = cList.where((element) => element != c1);

    for (var c2 in others) {
      if (canCollide(c1, c2)) {
        print('$c1 can collide with $c2');
      }
    }
  }
}

bool canCollide(Collidable c1, Collidable c2) {
  return (c1.myCollidableLayers & c2.myLayers != 0);
}
````
Output:
```
C1 can collide with C2
C1 can collide with C3
C2 can collide with C3
C3 can collide with C2
```

Notice how `c3` is present on `LAYER_THREE` as well as `LAYER_ONE` but is only interested in collision with `LAYER_TWO`. On the other hand, `c1`, despite being on `LAYER_ONE` can still get notified about collision with `c3`.

The only thing with this approach is that, Flame will have to decide upon how many layer does it want to support. Also, the API will have to be made user friendly because most users will not like bitwise operations in their code.

**Comment by spydon** [comment]
> Hey, I gave quick thought on this and I found following major things to consider.
> 
> - With this proposed layering mechanism each Collidable will be restricted to only a single layer.
> - `List<int> layersToCollideWith` will increase size of each Collidable. (This might not be a major issue)
> 
> Instead of using up a complete integer to store a single layer information, we can use each bit of an integer to represent a layer. With some bitwise operators we can easily check for all possible collisions. Following is quick example to explain this:
> 
> ```dart
> const LAYER_ZERO = 1 << 0;
> const LAYER_ONE = 1 << 1;
> const LAYER_TWO = 1 << 2;
> const LAYER_THREE = 1 << 3;
> 
> class Collidable {
>   int myLayers = 0; // The layers on which this entity is present
>   int myCollidableLayers = 0; // Layers to check for collisions
>   String name;
> 
>   Collidable(this.name);
> 
>   @override
>   String toString() {
>     return name;
>   }
> }
> 
> void main(List<String> arguments) {
>   final cList = List<Collidable>.empty(growable: true);
> 
>   var c1 = Collidable('C1');
>   c1.myLayers = LAYER_ONE;
>   c1.myCollidableLayers = LAYER_TWO | LAYER_THREE;
>   cList.add(c1);
> 
>   var c2 = Collidable('C2');
>   c2.myLayers = LAYER_TWO;
>   c2.myCollidableLayers = LAYER_THREE;
>   cList.add(c2);
> 
>   var c3 = Collidable('C3');
>   c3.myLayers = LAYER_THREE | LAYER_ONE;
>   c3.myCollidableLayers = LAYER_TWO;
>   cList.add(c3);
> 
>   checkPossibleCollisions(cList);
> }
> 
> void checkPossibleCollisions(List<Collidable> cList) {
>   for (var c1 in cList) {
>     var others = cList.where((element) => element != c1);
> 
>     for (var c2 in others) {
>       if (canCollide(c1, c2)) {
>         print('$c1 can collide with $c2');
>       }
>     }
>   }
> }
> 
> bool canCollide(Collidable c1, Collidable c2) {
>   return (c1.myCollidableLayers & c2.myLayers != 0);
> }
> ````
> Output:
> ```
> C1 can collide with C2
> C1 can collide with C3
> C2 can collide with C3
> C3 can collide with C2
> ```
> 
> Notice how `c3` is present on `LAYER_THREE` as well as `LAYER_ONE` but is only interested in collision with `LAYER_TWO`. On the other hand, `c1`, despite being on `LAYER_ONE` can still get notified about collision with `c3`.
> 
> The only thing with this approach is that, Flame will have to decide upon how many layer does it want to support. Also, the API will have to be made user friendly because most users will not like bitwise operations in their code.

We don't need to expose to the user that there are bitwise operations under the hood, but I think it is premature optimization.
We should not restrict the number of layers by a set of const variables, we can definitely do a more general architecture than that. 

I think we can start with each `Collidable` having a set of layers that it lives in and then a `CollidableType` for each layer.

**Comment by namzug16** [comment]
> I agree that the bit-masking approach is probably premature optimization, but I couldn't stop drawing the similarities between proposed layering system and Godot's collision layering system. I don't like comparing projects like this, because target audience of each project is different. But Godot seems to be doing pretty good with a 32-bit integer and a limit of 20 or so collision layers.
> 

This layering system was actually inspired by Godot's one.( only the name tho, I haven't seen the code )

> I think we can start with each ```Collidable``` having a set of layers that it lives in and then a 
> ```CollidableType``` for each layer.

I think each ```Collidable``` should live only in one "layer" and have a set of "layers" that this component can collide with, of course they each one of them will have its ```CollidableType```.

But as @ufrshubham said, as long as we can control what collides with what, it'll be a great implementation.

**Comment by st-pasha** [comment]
As we are talking of the collision layers, I don't think they should be mere integers, but instead actual objects:
```dart
class CollisionLayer {
  final List<CollisionLayer> collidesWith;
  final List<Collidable> items;
}

class Collidable {
  final CollisionLayer collisionLayer;
}

mixin HasCollidables {
  final List<CollisionLayer> allLayers;
  CollisionLayer makeCollisionLayer();
  
  void processCollisions() {
    for (final layer in allLayers) {
      for (final targetLayer in layer.collidesWith) {
        if (layer == targetLayer) {
          _interactSelf(layer.items);
        } else {
          _interact(layer.items, targetLayer.items);
        }
      }
    }
  }
}
```

**Comment by spydon** [comment]
We have decided not to take up this enhancement before we release v1, so we can take up the discussion about implementation details after that.

**Comment by st-pasha** [comment]
wait, is v1 coming up any time soon?

**Comment by spydon** [comment]
> wait, is v1 coming up any time soon?

Yes, well, soonish. We are finalizing the feature set for it at least.

**Comment by spydon** [comment]
I have started working on this, will try out a few things first and then put up a PR where we can discuss. :slightly_smiling_face:
