### ISSUE TITLE
Decide on exact linting rule for `prefer_mixin`

### ISSUE THREAD

**Issue by luanpotter** [flame-engine/flame#991]
We have a linter rule commented out on some lint configurations files:

```yaml
 #    - prefer_mixin 
```

We should study what it does and what it's for and if we wanna use it or not, and either have it enforced or not at all. Commented out code is a recipe for rot.

**Comment by st-pasha** [comment]
Here are some notes on this topic: https://github.com/dart-lang/language/blob/master/accepted/2.1/super-mixins/feature-specification.md
